### ISSUE TITLE
no text - macOS Sierra 10.12.3

### ISSUE THREAD

**Issue by madorn** [VCVRack/Rack#1]
Hi,

Trying to get this run on macOS Sierra 10.12.3.  Cannot see any text.

<img width="750" alt="screen shot 2017-02-28 at 5 13 42 pm" src="https://cloud.githubusercontent.com/assets/4207880/23438813/347fd214-fdd9-11e6-803a-31ab6fbc4621.png">

**Comment by AndrewBelt** [comment]
Looks like the resources folder is not being found. Are you running the Rack application from within the folder containing `res`, etc? If so, it's probably my fault. I currently don't have a working macOS computer to test this on, but I'm going to order a Mac Mini on eBay in a week or two for testing.

**Comment by AndrewBelt** [comment]
I've uploaded a new version 0.2.1 to the website. Try it and let me know if this fixed it. I've tested it on OS X 10.7, so it's hard to tell if this will work on something as new as 10.12.

**Comment by madorn** [comment]
Thanks for looking. Tried VCVRack 0.2.1 but still seeing the same thing on 10.12.3.

**Comment by AndrewBelt** [comment]
I have patched the latest version below to display the current working directory of the application in a popup box upon launch. It might display something like `/Users/vortico/Downloads/Rack` when you launch it, assuming the app is in that folder. If you could try this and let me know the path in the popup box and the path that you downloaded and unzipped the directory, that would be much appreciated.

[Rack_0.2.1_mac.zip](https://github.com/VCVRack/Rack/files/818933/Rack_0.2.1_mac.zip)

**Comment by madorn** [comment]
executed from: `/Users/myname/Downloads/Rack`.
working directory: it's giving me a path within `/private/var`.

**Comment by AndrewBelt** [comment]
Yup, looks like an issue with getting/setting the working directory.

Try this one: It uses a different method to get the app directory.

[Rack_0.2.1_mac.zip](https://github.com/VCVRack/Rack/files/822577/Rack_0.2.1_mac.zip)

**Comment by AndrewBelt** [comment]
Nevermind, the above won't work either, due to http://stackoverflow.com/a/42637115/272642

I'll have to find a workaround.

**Comment by AndrewBelt** [comment]
I have found a workaround to avoid Sierra's annoying "App Translocation". Download and unzip the archive to some folder, say `Downloads`.

1) Go into the directory and move the Rack app (not the Rack folder) to `/Applications`. This magically removes the "App Translocation" metadata from the .app.

2) Go into `/Applications` and copy the Rack app back to `Downloads` (Option-Drag). You may delete the original Rack app from `/Applications` if you wish.

Voila. It now works on Sierra. I'll try to figure out a real solution for this before closing this issue.

**Comment by AndrewBelt** [comment]
Fixed with 412759d, I think. The application will look in the `/Applications/Rack` folder for the resources on Sierra, so the caveat is that you have to use the application from that folder (but you probably should be doing that anyway).
