### ISSUE TITLE
Problem compiling rtmidi on Linux (using travis-ci)

### ISSUE THREAD

**Issue by bafonso** [VCVRack/Rack#1002]
Please read https://github.com/VCVRack/Rack/issues/730 before posting any code or terminal output.

Operating system(s): Linux
Version of Rack if using official binary, or commit hash and branch if compiling from source: 0.6 branch
All hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

Please see https://travis-ci.org/bafonso/Erratic/jobs/389408522 for the log output. I'm using the default commands to build Rack and all of its dependencies.

**Comment by AndrewBelt** [comment]
Looks like JACK isn't installed on your build server. See https://github.com/VCVRack/Rack/blob/v0.6/README.md#linux

**Comment by bafonso** [comment]
Thanks, I should have RTFM.
