### ISSUE TITLE
dep.mk needs an IFDEF for Mac OS to set WGET correctly

### ISSUE THREAD

**Issue by fractalgee** [VCVRack/Rack#1003]
Rack 0.6.1dev, cloned an hour ago, Mac OS X 10.11.6

The ```dep.mk``` setting of ```WGET``` makes ```make dep``` fail, as it sets WGET to ```wget -c``` which is illegal and ignored on Mac OS X. This needs to be ```wget --no-check-certificate``` for ```make dep``` to succeed

**Comment by AndrewBelt** [comment]
Mac includes an ancient version of wget, which is why you need to install a reasonable version of wget through brew.

**Comment by fractalgee** [comment]
GNU Wget 1.19.2 is the one I have, not reasonable enough?

**Comment by AndrewBelt** [comment]
`-c` (`--continue`) is present in that version, so it should work. Your installation is probably messed up. It would be a good idea to post the actual log instead of a paraphrase of it.

**Comment by AndrewBelt** [comment]
Disabling certificate protection because it doesn't validate is like killing your pet to cure its cold. Certicicate checking can't be removed.

**Comment by fractalgee** [comment]
Exact same issue, just fails to want to verify github's cert. Looked about but haven't found why that would be.

**Comment by AndrewBelt** [comment]
Then this is an issue with your computer rather than Rack.
