### ISSUE TITLE
Trouble Installing and Running VCV Rack on Ubuntu 18.04

### ISSUE THREAD

**Issue by jmarcopolov** [VCVRack/Rack#1006]
Hello all, I'm a newbie having some issues installing and running Rack on my Ubuntu 18.04. Let me go through my process to better help everyone understand whatever the problem might be.

First I downloaded the zip file from the Rack site and extracted it on to my desktop. When I open the extracted folder I can see many files including the Rack App and a Rack.sh. When I opened the Rack App from here Rack would actually run. Now, I obviously didn't want to keep Rack on my desktop and continue running it from there, so I ran the following commands to move it to the proper folders in order to run it from the Dock.

`sudo unzip ~/Desktop/Rack-0.6.0-lin.zip -d /opt/ `

`sudo ln -sf /opt/Rack/Rack /usr/bin/Rack `

`sudo gedit /usr/share/applications/Rack.desktop `

In the Rack.desktop file included this code:

[Desktop Entry]
Version = 1.0
Type = Application
Terminal = false
Name = Rack
Exec = /usr/bin/Rack
Icon = /opt/Rack/res/icon.png
Categories = Application;

That's all. Now, for some reason, the Rack App won't run from anywhere; the /opt folder, the /usr/bin folder, the shortcut on the Dock, or even on the extracted folder Ieft on the Desktop. I have no idea why this is happening.

Although, I should mention that I ran these other commands for the sake of dependencies.

` sudo apt install gnome-shell-extensions `

` sudo apt install make `

`sudo apt-get install build-essential `

` sudo apt install git curl cmake libx11-dev libglu1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev zlib1g-dev libasound2-dev libgtk2.0-dev libjack-jackd2-dev `

` git clone https://github.com/VCVRack/Rack.git `

I could really use everyone's help.
Thanks ahead of time guys!

**Comment by AndrewBelt** [comment]
Describe "won't run from anywhere".

**Comment by jmarcopolov** [comment]
@AndrewBelt Hi Andrew, thanks for your reply. What I meant is that the Rack App won't run from anywhere where it's located. There's a shortcut on the Dock and in /usr/bin that won't run Rack. The original App is in /opt and it also will not run from there. Additionally, the unzipped folder that was extracted from the downloaded zip file from the VCV Rack site is on my desktop, and it too has the Rack App in it. I was originally able to run it from here, but alas this location too will not run.

I hope that helps clarify my situation. Thanks again Andrew :)

**Comment by AndrewBelt** [comment]
That's not what I meant. Is there an error message? Does the cursor turn into an hourglass for a second? Does you computer shut down? Etc

**Comment by jmarcopolov** [comment]
@AndrewBelt Oh lol, no. Nothing seems to happen. I opened System Monitor to see if it even attempts some process but there doesn't seem to be anything happening at all. I'm at a loss here

**Comment by jmarcopolov** [comment]
@AndrewBelt In case

**Comment by jmarcopolov** [comment]
@AndrewBelt Just so there is no confusion, no error messages, prompts or anything at all appear. It's as if I didn't attempt to open it in the first place :/

**Comment by jmarcopolov** [comment]
*bump

Does anyone have any suggestions or ideas on what's going on or what I can do to help figure out what's happening?

Is there a log who's output I can share in order to help?

Thanks everyone :)

**Comment by AndrewBelt** [comment]
Does https://github.com/VCVRack/Rack/issues/1013 solve it?

**Comment by jmarcopolov** [comment]
@AndrewBelt This looks promising, however, I don't know how to implement the solution. Where do I copy/paste the code on this response:

` Okay, that's the issue, thanks. assetInit() does not the create the Rack local directory on boot. Fixed in c6be92e. Will test on all platforms and release a hotfix, replacing the current builds without changing their version numbers. `

Thanks!

**Comment by AndrewBelt** [comment]
Just get it at https://vcvrack.com/ or compile it from source, whichever you prefer.

**Comment by jmarcopolov** [comment]
@AndrewBelt Ok I found ~/Rack/src/asset.cpp however the addition of the line:

' systemCreateDirectory(localDir);
 } '

still doesn't allow the Rack to open. There's also the file ~/Rack/include/asset.hpp that reads:

` #pragma once

#include <string>
#include "plugin.hpp"


namespace rack {


void assetInit(bool devMode);
/** Returns the path of a global resource. Should only read files from this location. */
std::string assetGlobal(std::string filename);
/** Returns the path of a local resource. Can read and write files to this location. */
std::string assetLocal(std::string filename);
/** Returns the path of a resource in the plugin's folder. Should only read files from this location. */
std::string assetPlugin(Plugin *plugin, std::string filename);


} // namespace rack `

Should I add anything here? Is there anything else you think I should try?

Thanks again for all your help.

**Comment by AndrewBelt** [comment]
@jmarcopolov The issue has been solved. Just update your Rack installation.

**Comment by jmarcopolov** [comment]
@AndrewBelt  New information! When I `cd ~/Rack` and `make run` I get this error output:

make -C dep
make[1]: Entering directory '/home/marcopolo/Rack/dep'
cd glfw && cmake -DCMAKE_INSTALL_PREFIX="/home/marcopolo/Rack/dep" . \
	-DGLFW_COCOA_CHDIR_RESOURCES=OFF -DGLFW_COCOA_MENUBAR=ON -DGLFW_COCOA_RETINA_FRAMEBUFFER=ON
-- Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Using X11 for window creation
CMake Error: Could not open file for write in copy operation /home/marcopolo/Rack/dep/glfw/src/glfw3Config.cmake.tmp
CMake Error: : System Error: Permission denied
CMake Error at /usr/share/cmake-3.10/Modules/CMakePackageConfigHelpers.cmake:312 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:343 (configure_package_config_file)


CMake Error: Could not open file for write in copy operation /home/marcopolo/Rack/dep/glfw/src/glfw3ConfigVersion.cmake.tmp
CMake Error: : System Error: Permission denied
CMake Error at /usr/share/cmake-3.10/Modules/WriteBasicConfigVersionFile.cmake:46 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CMakePackageConfigHelpers.cmake:207 (write_basic_config_version_file)
  CMakeLists.txt:348 (write_basic_package_version_file)


CMake Error: Could not open file for write in copy operation /home/marcopolo/Rack/dep/glfw/src/glfw_config.h.tmp
CMake Error: : System Error: Permission denied
CMake Error at CMakeLists.txt:352 (configure_file):
  configure_file Problem configuring file


CMake Error: Could not open file for write in copy operation /home/marcopolo/Rack/dep/glfw/src/glfw3.pc.tmp
CMake Error: : System Error: Permission denied
CMake Error at CMakeLists.txt:354 (configure_file):
  configure_file Problem configuring file


-- Configuring incomplete, errors occurred!
See also "/home/marcopolo/Rack/dep/glfw/CMakeFiles/CMakeOutput.log".
See also "/home/marcopolo/Rack/dep/glfw/CMakeFiles/CMakeError.log".
Makefile:69: recipe for target 'lib/libglfw3.a' failed
make[1]: *** [lib/libglfw3.a] Error 1
make[1]: Leaving directory '/home/marcopolo/Rack/dep'
Makefile:56: recipe for target 'dep' failed
make: *** [dep] Error 2

Something is definitely wrong here. Does anyone know what this means and how to fix it?

Thank you :)

**Comment by AndrewBelt** [comment]
Locking this issue since you're clearly not reading anything I type.

**Comment by AndrewBelt** [comment]
Please read https://twitter.com/vcvrack/status/1008645406383853569 and respond 1) whether you have followed the instructions in the Tweet, and 2) exactly what happens if you are still having issues.

**Comment by jmarcopolov** [comment]
@AndrewBelt  Ok will do. Thank you

**Comment by jmarcopolov** [comment]
@AndrewBelt Thank you for reopening this issue Andrew. I have Rack working now but I can only access it in the terminal by going in to /Rack and running `sudo make run` Is there a way to make opening Rack easier? I have this code in /usr/share/applications/Rack.desktop:

[Desktop Entry]
Version = 1.0
Type = Application
Terminal = false
Name = Rack
Exec = /Rack/Rack
Icon = /opt/Rack/res/icon.png
Categories = Application;

 I re-purposed it here but I don't know how to get it to use the command `sudo make run`

Also, while I'm running Rack it doesn't seem to be able to source the Rack Icon and instead shows some type of default error icon.

Thanks for all your help so far Andrew. I know you're busy with all kinds of stuff and I really appreciate your time :)
