### ISSUE TITLE
Change foucs to possible Plugs

### ISSUE THREAD

**Issue by dschiller** [VCVRack/Rack#1008]
At the Moment all impossible Plugins will be more transparent. The Problem with that is that this is a graphical change and the User will get Atention to it. But what you want is the Attention to all the other Plugins. So I think it is a lot better to highllight all possible Plugins instead of highlighting all impossible Plugins. With Plugins I mean the Connections one can make.

Thanks and Cheers Dirk

**Comment by AndrewBelt** [comment]
What..?

**Comment by dschiller** [comment]
I believe you can ignore it. It's just an workflow improvement, nothing important. 

Cheers
