### ISSUE TITLE
Loadibg VCV Files will break Modules

### ISSUE THREAD

**Issue by dschiller** [VCVRack/Rack#1009]
If one open VCV Rack by opening a VCV File some Modules will not be displayed.

Open VCV Rack by EXE FIle:

![image](https://user-images.githubusercontent.com/3144986/41503599-76b03a9c-71d8-11e8-955d-22ab6c76e2c7.png)

Open VCV Rack by VCV File:

![image](https://user-images.githubusercontent.com/3144986/41503612-9f0f7462-71d8-11e8-8200-a08a27d089f6.png)

Cheers
Dirk

**Comment by AndrewBelt** [comment]
I assume you are double-clicking the .vcv file instead of using File > Open. This was not supported in Rack 0.6.0 but fixed in Rack 0.6.1dev.
