### ISSUE TITLE
Only "Audio Interface" & "MIDI Interface" visible

### ISSUE THREAD

**Issue by lvets** [VCVRack/Rack#101]
I compiled Rack on Ubuntu 16.04 LTS, but when I open the Rack interface and right click, I only see the "Core: Audio Interface" & "Core: MIDI Interface" options. How can I add additional modules?

System information:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

**Comment by TronicLabs** [comment]
you nedd some additional build step:
need to git clone the module from the other repo
$ make dist
this build the default plugin module

for the other modules need more to do

**Comment by AndrewBelt** [comment]
@TronicLabs No, you don't need to `make dist`, that's only for generating distributibles.

To build plugins, simply `git clone --recursive` your desired plugin in the plugins directory and `make` it.

**Comment by TronicLabs** [comment]
@AndrewBelt   To build plugins your info is correct, but without the creation of dist folder with all the dependency file, in windows it's hard to test.

**Comment by AndrewBelt** [comment]
`make run` doesn't work in Windows Mingw64?

**Comment by TronicLabs** [comment]
hehehe, I missed this

**Comment by AndrewBelt** [comment]
No worries, it was recently added.
