### ISSUE TITLE
Plugin testing infrastructure

### ISSUE THREAD

**Issue by modlfo** [VCVRack/Rack#1010]
I would like to have a simple command line application used to test and profile modules. Imagine you develop some new module and want to test that it loads correctly, that does not crash with different inputs and that is efficient.

The headless application should receive as input the slugs to load the plugin. It will create an instance of the module and render audio using the following stimuli:

- All plugin inputs will receive burst of test signals: sine, pulse, saw waves and noise. Initially, the inputs should be in a constrained range (-12 to 12V). An additional test can be carried out with larger signals (-120 to 120V).
- Parameters (UI objects) will receive changes simulating a very crazy user. The values could move softly or make big jumps in all the valid range of the parameter. 

To validate, the plugin should not crash and the outputs should be in a constrained range, for example not producing  NaN, +infinite or -infinite.

The input signals could be configured, for example, the range of the signal, the smoothness or the frequency content. Ideally the signal generators should ve very simple in order to not account for many CPU cycles. 

The same application should be possible to run with the profiling tools provided by the OS in order to detect hot spots. Ideally, it should be possible to run from a script in an automatic way on every platform.

This application can be used to discard buggy plugins from the plugin manager and inform their developers about which tests their plugins fail.

**Comment by AndrewBelt** [comment]
IMO everyone's plugin DSP behaves pretty well. 90% of the issues with plugins are their build system working across three platforms and their GUI crashing because of misusing Widgets or other hacks.

**Comment by squinkylabs** [comment]
I run a test like this on my own modules - it's called "extreme tester".  But I code my modules so they are not dependent on the VCV host environment.
