### ISSUE TITLE
Crash for modules using OSDialog

### ISSUE THREAD

**Issue by antoniotuzzi** [VCVRack/Rack#1012]
Operating system(s): OSX  10.13.5

I was testing in a separated branch the current HEAD (the 0.6.1 wannabe)
My NYSTHI modules are still compiled using the front v0.6 branch
all the modules opening the OSDialog are crashing

last working commit is 
7407d20b335813e5809fed01ee796356f4c5a431

Mon Jun 11 22:00:27 2018 -0400

**Comment by AndrewBelt** [comment]
Perhaps just compile against Rack 0.6.1 and release a new version?

**Comment by antoniotuzzi** [comment]
solved updating all the OSDialog instances with the use of the OSDialogFilters (in nysthi 0.6.5)

**Comment by AndrewBelt** [comment]
Not sure why that broke ABI (assuming it did) because you should have been passing NULL to the `const char *filters`, so the ABI would have been preserved when switching to `osdialog_filters *filters`.

**Comment by antoniotuzzi** [comment]
you are right: my fault
when doing the 0.5.0, I modified the osdialog to have a inner "nysthi" version
and was working correctly with "filters" string
but with 0.6.0 I removed it (from nysthi code) but I've left the "wav" and "scl" as strings in filters

**Comment by AndrewBelt** [comment]
Oh yes, `filters` did nothing until the above commit, which changed its type.
