### ISSUE TITLE
[solved] Plugin updates ad infinitum & 'could not extract package' warnings

### ISSUE THREAD

**Issue by alectron** [VCVRack/Rack#1014]
Heya,
just to document/mention this - as it did fix itself in the end:
Upon updating to 0.6.1 I got a few issues that seem to be related to each other. 
After re-opening, downloading & OK-in multiple times (on the same modules seemingly) - VCV Rack now opens fine again after stating 'All Plugins Have been updated', but before it was stuck in what looked like an endless cycle of downloading the same & extracting the same plugins over and over again (I saw Valley as well as mscHacks & MSM being downloaded and extracted multiple times).

So mostly for documentation purposed, as it is solved/has disappeared now as an issue:
First, when I opened Rack, I got pop up windows telling me:

------------------------------------------------------"
/!\ Could not extract package
     C:\Users\*\Documents/Rack/plugins/Valley.zip
                                                                 |     OK      |
"------------------------------------------------------

This happened for:
Valley.zip
and MSM, mscHack a few others I did not scribble down...

Then, once OK'd and Rack UI has started, the 'Update plugins' ui element is marked with a red dot = needs update.
Upon starting the update, it repeat progress:
'Downloading updating Plugins... '
iterating through each plugin, which is normal. Some plugins did appear multiple times though, and I saw a few of the above go from 0% to 100% multiple times, making it look like a reursive loop (maybe it was just multiple versions of each...?) 

Either way, it's all functional again now, after letting it update for 15+ mins and letting it re-itterate over the same multiple times.
Again, only to document this, and in case others see this as well.
Cheers.
c.

Operating system(s):
Windows10 64bit (On a Surface Pro - just mentioning this as these can be a tad finicky with audio...)

**Comment by modlfo** [comment]
Closing since it's marked as solve by the author.
