### ISSUE TITLE
Bridge in 0.6.1 not working with VSL Ensemble Pro

### ISSUE THREAD

**Issue by bkkjohn** [VCVRack/Rack#1015]
When Bridge 0.6.1 is instantiated in a Vienna Symphonic Library (VSL) Ensemble Pro channel, an error dialog box appears:  "VST: VCV-Bridge-64 (Incompatible channel configuration: Stereo to Stereo)".   No audio from Rack is passed from Rack to VSL Ensemble.   With v 0.6.0 no error appears and audio is fine.

**Comment by AndrewBelt** [comment]
It would help if you didn't delete the issue template it asks you to fill out.

Does your host support instrument plugins? Does it support instrument plugins with audio inputs?

**Comment by bkkjohn** [comment]
Reinstalled 0.6.0, then reinstalled 0.6.1 and it works okay.  Gremlins.

**Comment by AndrewBelt** [comment]
I'm going to guess that you loaded an existing VSL file containing the old Bridge plugin. You will need to re-add the plugin since the VST type has changed.
