### ISSUE TITLE
VCV Bridge VSTi and VST plugins

### ISSUE THREAD

**Issue by Uriel-A** [VCVRack/Rack#1017]
With the release of v.0.6.1 the VCV Bridge VSTfx plugin has been replaced by the long awaited VSTi version of it handling both MIDI and Audio inputs to VCV for processing.
 
This new method may result in a convoluted workflow if the user wishes to use VCV processing in a parallel (Dry/Wet) manner, especially in Ableton Live.
 
The problem is because a MIDI track cannot directly receive an audio input as source, it can only be sent directly from the source audio track and in doing so will effectively mute the source track's output.
 
I'm currently using the v0.6.0 VSTfx version of the VCV Bridge plugin (which still works in v0.6.1 by the way) side by side with the new VSTi plugin by renaming them.
 
My suggestion is why not keep both the VSTfx and VSTi versions of the VCV Bridge plugins for future releases? I find the VSTfx version very useful in many possible workflow applications.

Before in v.0.6.0 (2 Tracks used)
-----------------------------------
Track 1:
Audio signal > Effects Rack > Chain 1: VCV Bridge VSTfx
                                             > Chain 2: Dry Thru
_adjust chain volume independently to taste_
 
Track 2:
For recording Track 1's output.
 
Now in v.06.1 (4 tracks required)
------------------------------------
Track 1:
Audio signal
 
Track 2:
Audio input from Track 1 > Audio output to Track 3 (VCV Bridge VSTi)
 
Track 3:
Audio input from Track 2 > VCV Bridge VSTi
 
Track 4:
For recording VCV Bridge's output.
_adjust Track 1 and 4 volume independently to taste_

**Comment by AndrewBelt** [comment]
Why would you ever want to have a wet/dry control for the Bridge plugin? Why not just do that in Rack?
Managing two types of VST plugins is a mess, so I won't re-add the effect plugin.

**Comment by Uriel-A** [comment]
You can't do that in Rack if you have further VSTfx processing within that same chain than you want to parallel process.

**Comment by Uriel-A** [comment]
> Managing two types of VST plugins is a mess, so I won't re-add the effect plugin.

Andrew, I have a lot of respect for you coming up with this whole VCV project and I thank you for it. But I am rather surprised that you are taking your development in certain direction just because it is the easier way out. You never strike me as creating VCV because it was the easier path for you.

That being said, I will still respect whatever decision you make. After all, it is your project. We can only make suggestions and feedback.

**Comment by AndrewBelt** [comment]
If you think it's fun and easy, compile it yourself. Just comment out the line https://github.com/VCVRack/Bridge/blob/v0.6/VST/BridgeVST.cpp#L19, and that might work.

**Comment by Uriel-A** [comment]
https://github.com/VCVRack/Bridge/blob/v0.6/VST/BridgeVST.cpp#L20
`isSynth(false);`
will not work. isSynth() should not be declared at all if it is not a VST instrument. That said, declaring isSynth(true) is probably redundant as well for making it an instrument, just isSynth() should be enough.

**Comment by AndrewBelt** [comment]
@Uriel-A That code's untested, so you're probably right, but all it does it set/unset a bitmask, so why doesn't it work?

**Comment by Uriel-A** [comment]
I've just complied and tried it. I don't think the bitmask is taken into account at all. Only the declaration, or the lack of.

**Comment by AndrewBelt** [comment]
That's not a declaration, that's a function call. Are you familiar with C++ syntax?

**Comment by Uriel-A** [comment]
All long forgotten ages ago... 🤣

**Comment by Uriel-A** [comment]
This is how I found out:
https://www.kvraudio.com/product/vst-audio-plug-ins-sdk-c-and-and-by-steinberg (3rd comment):
"If you want to specify that your plugin is an instrument, and not an effect, you should add
isSynth();
in the constructor of the main class (like it is in vstxsynth)"

**Comment by AndrewBelt** [comment]
Ah, the fallacy of reading random people's comments on the internet.

Anyway, since you're now reporting an issue, could you fill out the bug report form https://github.com/VCVRack/Rack/issues/new?template=bug_report.md in a new issue?
