### ISSUE TITLE
login and plugin download missing after manual compiling

### ISSUE THREAD

**Issue by FrankBuss** [VCVRack/Rack#1018]
I compiled VCVRack for Linux Debian, as described at https://github.com/VCVRack/Rack , but with "make dep RTAUDIO_ALL_APIS=1". And I can see the JACK driver in the AUDIO module, which I wanted to try, because sometimes the ALSA driver doesn't work from the pre-built binary, it is distorted and I get buffer underflows. But when I start it with "make run", I don't see the Login and Plugin download buttons. This is what I see: https://i.imgur.com/u7ccaEb.png Did I miss something? I don't want to compile all modules by myself as well.

**Comment by AndrewBelt** [comment]
Use `make runr` to run the release version, or just use `./Rack`.
