### ISSUE TITLE
Save Application Settings in Patch

### ISSUE THREAD

**Issue by dschiller** [VCVRack/Rack#1024]
Would be nice to save some of the Rack's Application Settings within Patches if wanted.

- Save Rack Settings in Patch: Yes / No
- Save Rack internal Sample Rate
- Save Cable Opacity
- Save Cable Tension
- Save Zoom

**Comment by AndrewBelt** [comment]
Settings are saved to `settings.json`, not patches. If you want to transfer settings from one computer to the next, copy the settings.json file.
