### ISSUE TITLE
VST Bridge Block size is locked

### ISSUE THREAD

**Issue by dschiller** [VCVRack/Rack#1025]
How can I change the Block size in "Bridge" Mode ? It is "locked by device". The CPU Usage is almost 100 Percent because Block size is at 64. That is to low for my Machine. Would liek to change it to 512.

![image](https://user-images.githubusercontent.com/3144986/41607486-6910c1bc-73e6-11e8-8782-b9ea075ee14e.png)

The Block size ( Buffer size ) in the DAW App. is 512.

![image](https://user-images.githubusercontent.com/3144986/41607747-08d6e6f4-73e7-11e8-9415-e5da84e5f629.png)

Cheers
Dirk

**Comment by AndrewBelt** [comment]
That is up to the host. If the host sends blocks of `N` samples to Bridge, Rack needs to process and return `N` samples to the host. Not much I can do here.
