### ISSUE TITLE
Module Nesting

### ISSUE THREAD

**Issue by dschiller** [VCVRack/Rack#1027]
Make Module Nesting possible. A "Container" can nest any Module. To the Outside a Container can map any Inputs and any Outputs also any Parameter as Rotary. Inputs could be at the top, Rotarys in the middle and Outputs at the bottom. By doubleclicking a Container it will be opened. Special Modules inside the Container will reflect the Inputs, Outputs and Rotarys. The Rotary Mapping is new because one have to Patch a Knob / Fader to one of the Rotarys for the Outside world. Saving Nested Modules would save Building Time.

This is just an Idea I can imagine that this Approach does not follow the "real" Modular World and maybe you ( Andrew ) don't want this kind of behaviour.

Cheers

**Comment by AndrewBelt** [comment]
Duplicate of #655

**Comment by dschiller** [comment]
Hi Andrew, I am sorry for the duplicate!
