### ISSUE TITLE
Loading Beatstep into MIDI module closes VCVRack

### ISSUE THREAD

**Issue by rainbowjaw** [VCVRack/Rack#1029]
VERSION:  **0.6.1** 
OS: **Windows 10**
MIDI Driver: Windows MIDI
Hardware (not working): **Arturio Beatstep**  (simple version - _not_ pro)
Hardware (working): Akai APC40

Upon selecting the beatstep midi controller, VCV closes after a brief 1 second pause. 
As a control, in the same scenario my APC40 works fine, so it's something particular about the beatstep/my configuration.

**Comment by AndrewBelt** [comment]
If you have experience with GDB on MSYS2, post a stack trace. If not, we'll have to wait until someone can reproduce this.

**Comment by rainbowjaw** [comment]
Well, I figured out the problem... the software which comes with the beatstep hogs access: "MIDI control center"

"unsyncing" the device from and closing MIDI control center unlocks the beatstep to be used by other applications. 

I don't have experience with c++ or working on code on this level, but I will look into GDB on MSYS2 for any future bug reports.
