### ISSUE TITLE
Can only add core modules 

### ISSUE THREAD

**Issue by Malifick** [VCVRack/Rack#103]
Trying to load any other modules other than core is futile  , I tried downloading them and replacing the original ones . Json is loading and saving the patch settings but not sure why it's not working .

**Comment by AndrewBelt** [comment]
Need more details. What's your OS? What error message or result does loading or adding plugins have?

**Comment by Malifick** [comment]
Linux 0og33 4.10.0-33-lowlatency #37~16.04.1-Ubuntu SMP PREEMPT Fri Aug 11 16:01:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
 
No result no error,  trying the git method , when I am finished "make" ing the files I'll let you know the result .

**Comment by Malifick** [comment]
Ah hah! it worked Yay!
Dude , thank you for making this awesome virtual synth !
