### ISSUE TITLE
multiple row height modules

### ISSUE THREAD

**Issue by FrankBuss** [VCVRack/Rack#1030]
Is it possible to program modules that span 2 or more rows? I plan to create a big frontpanel kind of module for a custom instrument, which has all the (useful) knobs for the rest of the modules in a nice arrangement with custom graphics and labels. Knobs would change CV values, which are then connected to the other modules, and there will be some routing switches, graphics display etc.

Best would be if it is similar to LabVIEW, where you can switch between the backend implementation, which would be the standard VCV Rack interface, and a frontpanel view, but I guess this would be a lot of work to program.

**Comment by AndrewBelt** [comment]
It is known to work, but it's not "supported", which means that I could release an update that breaks it on a whim.

**Comment by FrankBuss** [comment]
The Portland Weather module uses it:
https://github.com/almostEric/FrozenWasteland/blob/master/src/PortlandWeather.cpp#L824
Would be nice if you could keep the feature, or if you need to refactor the interface, then provide a new method to do it.
