### ISSUE TITLE
CTRL-SHIFT-O key command access to Revert toolbar item

### ISSUE THREAD

**Issue by dirkleas** [VCVRack/Rack#1031]
can you add **CTRL-SHIFT-O** as key command for **Revert** toolbar item to enable instrumentation (any other preferred keyboard shortcut would be fine as well if you'd rather not use CTRL-SHIFT-O, perhaps CTRL-SHIFT-V, etc.)? it might also be worthwhile to use a more general term for the toolbar item, such as "**reOpen**" instead of "Revert" since the originally opened patch could have changed. this would make this feature more accessible and workflow efficient. as an additional use case, I often use MIDI-to-keystroke mapping in my toolchain to automate reopening externally transformed patches for such tasks as importing submodules, layout management, etc., often with a foot-switch/expression pedal. thanks in advance

**Comment by AndrewBelt** [comment]
Sure, that's reasonable enough. Added in 4bde271

**Comment by dirkleas** [comment]
thanks again, @AndrewBelt
