### ISSUE TITLE
Miraweb style screen mirror web app for touchscreen control

### ISSUE THREAD

**Issue by HelveticaScenario** [VCVRack/Rack#1033]
I propose the development of a [miraweb](https://cycling74.com/articles/content-you-need-miraweb) style screen mirror and control surface system to be built into rack and served from within the application to (most likely) be served to other devices on a local network connection.

Given the nature of the UI system is built around widgets I think there is a good analog to HTML and current day web apps using component architectures like React.js and Vue.js. In addition, as far as I can tell, the main UI elements are SVG, images, fonts, and framebuffers, each of which has an analog in web browsers. I believe that the UI system can be adapted to transparently send and receive updates to a web browser over WebSockets and that by creating a parity widget system in javascript for the browser we can reuse existing module UI code written for the current system to construct the UI in the browser.

Some other benefits that a system like this could allow for are multiscreen editing, where different portions of a patch, some possibly overlapping, can be viewed and edited on different screens on different devices. Expanding on this, this system would allow for multiuser patching, where multiple people, on multiple devices, possibly in completely different parts of the world (this is the web after all and pretty much anything that can be done on LAN can be done over the internet as a whole), can be editing the same patch simultaneously.

To be clear, this would be a 1 to 1 mirror of the rack patching ui.

I believe that I could write the web browser portion of this, and I do have a bit of experience with c++ so I could possibly do the integration as well but that would more likely be a better role for someone more familiar with the code base.

**Comment by ceci21** [comment]
I like this. You're a good writer

**Comment by AndrewBelt** [comment]
It'd probably be easier to create a Rack alternative. Not sure how any Rack code would be useful for this project.

**Comment by HelveticaScenario** [comment]
all audio processing would still be done with rack on the desktop or laptop, same as it is today. everything would still work as it does today, this would just add an extra option for control.

**Comment by HelveticaScenario** [comment]
the browser would just be a separate interface, communicating with rack over a network for control and view purposes

**Comment by AndrewBelt** [comment]
A plugin inherits from `ModuleWidget`. How could it tell the browser about this?

**Comment by HelveticaScenario** [comment]
the sequence of operations that the module widget does, all of the input and output additions, setting the panel, all of that would be issued as commands to the browser to dictate the construction of the UI on the browser. it would essentially be a set of RPC calls

**Comment by AndrewBelt** [comment]
What about `Widget` subclasses that use custom nanovg routines? Would you just not support those?

**Comment by HelveticaScenario** [comment]
I think not supporting those, at least initially, would be fine. The base component library would cover the majority of use cases, correct?

**Comment by AndrewBelt** [comment]
None of the VCV modules, so I have no motivation for this. I don't think a browser frontend would help most users either. But you're welcome to fork.

**Comment by HelveticaScenario** [comment]
are you saying that all of the vcv modules use custom nanovg routines?

**Comment by AndrewBelt** [comment]
The (currently) four commercial ones, yes.

**Comment by HelveticaScenario** [comment]
ok, i understand.
