### ISSUE TITLE
libRack.a missing from https://vcvrack.com/downloads/Rack-SDK-0.6.1.zip

### ISSUE THREAD

**Issue by dirkleas** [VCVRack/Rack#1036]
arch: windows build failure due to missing libRack.a (e.g `-lRack`) -- 0.6.0 version of rack-sdk included libRack.a. reproduced on Win10 with latest rack-sdk and Template clone

**Comment by dirkleas** [comment]
issue based on version zip from 8 days ago via reference [thread](https://github.com/VCVRack/Rack/issues/258) -- that seems to be the latest available version. not fixed or alternative build workflow required, but not documented in reference thread. to replicate fix, I pulled libRack.a from my full rack source build and added to unzipped rack-sdk folder and it built as expected -- possibly a regression in makefile hierarchy

**Comment by AndrewBelt** [comment]
Okay, but can you verify that the ZIP file now has libRack.a?

**Comment by dirkleas** [comment]
both links below from official reference [thread](https://github.com/VCVRack/Rack/issues/258) showing regression -- `libRack.a` needs to be added back to the new rack-sdk (e.g. added back to the upstream build workflow)...

current link, missing `libRack.a`: https://vcvrack.com/downloads/Rack-SDK-0.6.1.zip:

```
➜  Rack-SDK ls -la
total 88
drwxrwxr-x@ 10 dirkleas  staff    320 Jun 18 05:29 .
drwx------+ 49 dirkleas  staff   1568 Jun 25 20:42 ..
-rw-rw-r--@  1 dirkleas  staff  21138 Jun 18 05:29 LICENSE-dist.txt
-rw-rw-r--@  1 dirkleas  staff   1455 Jun 18 05:29 LICENSE.txt
-rw-rw-r--@  1 dirkleas  staff    518 Jun 18 05:29 arch.mk
-rw-rw-r--@  1 dirkleas  staff   1917 Jun 18 05:29 compile.mk
drwxrwxr-x@  3 dirkleas  staff     96 Jun 18 05:29 dep
-rw-rw-r--@  1 dirkleas  staff    821 Jun 18 05:29 dep.mk
drwxrwxr-x@ 23 dirkleas  staff    736 Jun 18 05:29 include
-rw-rw-r--@  1 dirkleas  staff   1214 Jun 18 05:29 plugin.mk
```

previous link, includes `libRack.a`: https://vcvrack.com/downloads/Rack-SDK-0.6.0.zip:

```
➜  Rack-SDK ls -la
total 4272
drwxr-xr-x@ 11 dirkleas  staff      352 Mar 26 15:43 .
drwx------+ 49 dirkleas  staff     1568 Jun 25 20:40 ..
-rw-r--r--@  1 dirkleas  staff    21138 Mar 26 15:43 LICENSE-dist.txt
-rw-r--r--@  1 dirkleas  staff     1455 Mar 26 15:43 LICENSE.txt
-rw-r--r--@  1 dirkleas  staff      379 Mar 26 15:43 arch.mk
-rw-r--r--@  1 dirkleas  staff     1452 Mar 26 15:43 compile.mk
drwxr-xr-x@  3 dirkleas  staff       96 Mar 26 15:43 dep
-rw-r--r--@  1 dirkleas  staff      819 Mar 26 15:43 dep.mk
drwxr-xr-x@ 20 dirkleas  staff      640 Mar 26 15:43 include
-rw-r--r--@  1 dirkleas  staff  2138768 Mar 26 15:43 libRack.a
-rw-r--r--@  1 dirkleas  staff     1011 Mar 26 15:43 plugin.mk
```

**Comment by AndrewBelt** [comment]
Okay, second try. Does it work now?

**Comment by dirkleas** [comment]
thank you, it works as expected now. I confirmed existence of `libRack.a` in updated .zip, and successful build on Windows 10 per reference docs -- thanks updating official `Rack-SDK-0.6.1.zip` in the reference thread! w00t!
