### ISSUE TITLE
Average CPU Meter over longer period

### ISSUE THREAD

**Issue by Chaircrusher** [VCVRack/Rack#1037]
I don't imagine this would actually help performance, since it looks like the CPU meters are probably refreshed on every window draw but...

Keep a running average over a longer time of the CPU usage of modules.  Even if the Power meter gets updated every window draw, the jitter to the value is distracting and doesn't give useful information.

Have not looked at source code to see how simple or difficult this might be.

**Comment by AndrewBelt** [comment]
The jitter is useful information, and the time constant does not effect performance.
