### ISSUE TITLE
initial template patch rather than blank rack

### ISSUE THREAD

**Issue by stefanougliano** [VCVRack/Rack#1039]
I think it could be nice to have the option of selecting a patch that would appear in place of the blank rack as one starts a new project. This would save the pain of putting in the usual fundamental pieces if going the CTRL+N way, or the pain of finding the "blank_template.vcv" if going the CTRL+O way.

**Comment by AndrewBelt** [comment]
See https://vcvrack.com/manual/FAQ.html?highlight=template#how-do-i-load-a-default-patch-when-selecting-file-new

**Comment by stefanougliano** [comment]
sorry :( stupid me, I went through the FAQ but somehow I missed that!
