### ISSUE TITLE
"stay-on" modules browser

### ISSUE THREAD

**Issue by stefanougliano** [VCVRack/Rack#1040]
I think it would help the workflow if rather than having to (rightclick > find the author I am looking for > choose the module) for each single piece I could have the browser open on the side > choose all the modules I need > close the browser

**Comment by molluskderek** [comment]
That could be cool, as a "pinnable" window.

**Comment by nay-seven** [comment]
I agree ! ;-) i often need this too !

**Comment by modlfo** [comment]
Closing as duplicate of #1114
