### ISSUE TITLE
Cloud Patch Storage

### ISSUE THREAD

**Issue by lnikj** [VCVRack/Rack#1041]
It would be useful to be able to specify, for example, iCloud and/or DropBox, as a cloud storage area for saved patches, to avoid having to manually (or otherwise) sync patches between boxes.

**Comment by AndrewBelt** [comment]
Why don't you want to use the services you mentioned?

**Comment by lnikj** [comment]
Sorry Andrew, you're right. When I was writing this I had more in mind than just patches. I have various paid modules that are not in the repository, and I compile other modules on one box and then have to manually copy them to the other box. That's what I'd like to be able to save centrally. Lots of DAWs have a system VST path and then the ability to specify an additional location; photoshop looks for plugins in different specifiable places. That's too niche though so I just, stupidly, put down patches, but that is just laziness regarding patch management on my part.

Embarassed! Sorry to have wasted your time.

**Comment by lnikj** [comment]
Thanks.

My apologies again. I have bought Router as a penance.
