### ISSUE TITLE
Build error: make: *** No rule to make target '../../plugin.mk'.  Stop

### ISSUE THREAD

**Issue by Cordoha** [VCVRack/Rack#1042]
~/.Rack/plugins$ cd MSCHack/
~/.Rack/plugins/MSCHack$ git submodule update --init --recursive
~/.Rack/plugins/MSCHack$ make dep
Makefile:9: ../../plugin.mk: No such file or directory
make: *** No rule to make target '../../plugin.mk'.  Stop.

**Comment by AndrewBelt** [comment]
See https://github.com/VCVRack/Rack#building-plugins for generic instructions for building Rack plugins.

**Comment by Cordoha** [comment]
Oh wow. How the heck did that happen. Thought I was in MSCHack's github. 
I'm sorry. :|

**Comment by Cordoha** [comment]
Can I delete this issue...?

**Comment by AndrewBelt** [comment]
GitHub doesn't even let maintainers delete issues.
