### ISSUE TITLE
Question: Built plugins only for dev version, or also use them for the released version? 

### ISSUE THREAD

**Issue by Cordoha** [VCVRack/Rack#1044]
Should I keep built plugins for the development version of Rack. Or will I have problems with the plugins migrating them to the released version?

My guess would be that something new might appear in the development version, while the released version has an older codebase and may not work properly? Not sure if that is the correct assumption, so I need some input.

**Comment by AndrewBelt** [comment]
Shouldn't matter. See https://vcvrack.com/manual/Version.html for ABI/API details.
