### ISSUE TITLE
'make dep' won't run if there is a space in the name of the Rack's containing folder in Windows

### ISSUE THREAD

**Issue by niksg** [VCVRack/Rack#1045]
Operating system(s):
Version of Rack if using official binary, or commit hash and branch if compiling from source: 0.6.0
All hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): Windows 10

When trying to run 'make dep' in my Rack folder, I was getting this error:
`gcc: error: Rack/Rack/dep/glew-2.1.0/build/cmake/../../include: No such file or directory`

My top level folder name is actually "VCV Rack", and when I changed it to "VCVRack" make ran successfully.

**Comment by AndrewBelt** [comment]
This is documented in the readme.

**Comment by niksg** [comment]
Ok, thanks! Must have missed it!
