### ISSUE TITLE
Add .reset() to PulseGenerator in digital.hpp ?

### ISSUE THREAD

**Issue by MarcBoule** [VCVRack/Rack#1047]
Resetting a pulse generator may be useful when/if someone is using it to generate long pulses and the module gets reset (i.e. we don't want the pulse to continue after the reset). It may be good to make this reset() more apparent to encourage good design practices. It would obviously be:

```
void reset() {
   time = 0.f;
   pulseTime = 0.f;
}
```

Devs would obviously need to invoke it apropriately in their code. I initially thought that calling `trigger(0.0f)` would do the trick but after looking at the code, it seems it will not work. Thanks!

**Comment by AndrewBelt** [comment]
Thanks, added to 1405fbe. The DSP library will go through a day or two of QC before Rack 1 is released.
