### ISSUE TITLE
login button not visible for big font size on Windows

### ISSUE THREAD

**Issue by FrankBuss** [VCVRack/Rack#1048]
Tested on Windows 8.1 on a Microsoft Surface, but it is a general problem. Maybe arrange the toolbar elements in 2 or more rows, if there is not enough horizontal space.
![screenshot](https://user-images.githubusercontent.com/1707296/42255067-2eb448c6-7f4a-11e8-900a-a13bc0cbfeea.png)

**Comment by AndrewBelt** [comment]
Duplicate of https://github.com/VCVRack/Rack/issues/903
