### ISSUE TITLE
Option to clear all wires from a patch but keep modules

### ISSUE THREAD

**Issue by KennyG5000** [VCVRack/Rack#1051]
First a quick but major thanks for this wonderful software, this piece of kit really does open so many doors for music making, unbelievable! Anyway, I was working with a downloaded (large!) patch today trying to understand how it worked, and it occurred to me that it would be very useful to tear it all down and re-patch it using the same modules. This would be really time consuming given the 50 to 100 or so connections already made. A simple option (with a fair warning probably!) would be great to auto remove them all. 

I figured this would be a fairly common procedure in a real Eurorack, where the core modules don't change, you just patch it up on a case by case basis (would also aid really learning the modules you currently have loaded).

Just a thought I would put forward anyway (and really looking forward to some MIDI out modules when they are ready!).

**Comment by AndrewBelt** [comment]
Click the cat icon in the toolbar.
