### ISSUE TITLE
Right-click button (laptop) activating pop-up menu?

### ISSUE THREAD

**Issue by patman023** [VCVRack/Rack#1053]
could this be implemented?

**Comment by AndrewBelt** [comment]
Right clicking on an empty space of the rack already opens the Module Browser. Comment if I misunderstood.

**Comment by patman023** [comment]
I'm referring to the keyboard button to the right of the space bar.
Apparently it's called the menu key.

Https://En.wikipedia.org/wiki/menu_key

**Comment by patman023** [comment]
Gah. I completely forgot about that one... Sorry :-(
