### ISSUE TITLE
Possible to not include Fundamental in release?

### ISSUE THREAD

**Issue by Cordoha** [VCVRack/Rack#1054]
An idea for plugin management which coincides with the latest builds for plugins in a stable VCV Rack.

Just seen that VCA-1 has changed. Wanted to try it out so I compiled it, deleted the package in the stable version, added the compiled version.

The store has it *included* as a pre-installed package. so removing the package cues the store to re-download it. But it's already been built and passed onto the plugins directory in stable. But I can't update plugins unless I want to re-build Fundamental again.

- Are there any plans to make a plugin manager in VCV Rack that will engage/disengage plugins being installed including Fundamental?
- Is it possible to not include Fundamental as a pre-installed set?

Or. I guess I could just build all the plugins and use the development version of Rack again. Which I did from the start. Until the installation changed with JACK(RELEASE=1).

**Comment by AndrewBelt** [comment]
When the Fundamental folder doesn't exist, Rack unzips its Fundamental.zip file before loading plugins.
When syncing plugins, updates to Fundamental are downloaded for all users.
