### ISSUE TITLE
Is the 'Start' output on MIDI-1 module working in current build (0.6.1)?

### ISSUE THREAD

**Issue by KennyG5000** [VCVRack/Rack#1055]
Hi, apologies to raise a new issue (but couldn't find this previously referenced on the forum), I am running Rack 0.6.1 and have MIDI-1 connected to the Bridge of Cubase 5 (64 bit) on Windows 7; everything else on this module (Clk 1, Clk 2 and Stop) are coming through fine but I receive no output from 'start' on starting the transport in Cubase 5. Is this feature not yet implemented or is it user error? 

Really hoping this is implemented (and I am doing something stupid!) as I think this output is the key to successfully syncing all the sequencers in Rack with the DAW host (so far this is proving very difficult to do consistently). It definitely syncs up well via the current Clock outputs, but getting VCV Rack in sync with the bar position is far more tricky without this 'Start' trigger to signal bar position.

**Comment by AndrewBelt** [comment]
START only triggers if transport changes state from stopped to running and the playhead is at beat 1 (beginning of song).

**Comment by KennyG5000** [comment]
Thanks for getting back to me about that so quickly Andrew, appreciate the support provided here. Had another try again with transport at beat 1 on Cubase 5 again but couldn't get a trigger out of the 'start' on Rack on beginning playback. It may be just the Cubase clock doesn't send this particular message, so no big deal, I will just use the 'cont' port instead as that is working fine. Thanks again for the support (and great software!).

**Comment by shurikenyo** [comment]
the reset works with ableton live and rack, maybe its a cubase issue..how about plonking down a specific note# or midi CC# at the start of your song and have that go to any of VCVRacks midi to "cv" modules, and use that as a reset.
I used the IAC bus on latest OSX to route the midi to vcvrack and it works..how tight...didnt test, just made sure i put the start jack into the reset on a sequencer (16 step by AS used)
