### ISSUE TITLE
midi 1 interface ...clock output doesn't genenrate pulses 

### ISSUE THREAD

**Issue by gentleclockdivider** [VCVRack/Rack#1068]
Unless I am completely wrong .
I have the midi 1 interface set to to computer keyboard /querty ...it generates gates and cv .
The clock output however doesn't generate anything .

**Comment by gentleclockdivider** [comment]
Please delete this .
VCV rack  should be slaved in order for clock pulses to be sent out from midi .
ALl good

**Comment by AndrewBelt** [comment]
Why are you not filling out the bug report form? https://github.com/VCVRack/Rack/issues/new?template=bug_report.md Is it not appearing for you?

**Comment by gentleclockdivider** [comment]
I don't get it .
I reported the bug,  no ?
Still new to this github stuff .

Op vr 20 jul. 2018 om 23:38 schreef Andrew Belt <notifications@github.com>:

**Comment by AndrewBelt** [comment]
I was asking because we've had a few people not fill it out, so I'm wondering if it's not appearing for some people. Here's the text you would see by default in the Bug Report text box. https://raw.githubusercontent.com/VCVRack/Rack/v0.6/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by gentleclockdivider** [comment]
I closed this because pulses are sent when vcv is slaved to midi .
In standalone version it doesn't .
SO I corrected it and closed report .

**Comment by AndrewBelt** [comment]
Right, the issue is resolved. I was asking you to test whether the Bug Issue template is displayed at https://github.com/VCVRack/Rack/issues/new?template=bug_report.md
