### ISSUE TITLE
GLFW3 macros issue in building from sources (Linux Mint 18.1)

### ISSUE THREAD

**Issue by leopard86** [VCVRack/Rack#107]
Hi there,
I was trying to compile from sources because the linux binaries are compiled with a newer version of  GLIBC and GLIBCXX, not present on my system. After preparing the system and compiling the dependencies I found this step troublesome and I need some help here:

```
g++ -Iinclude -Idep/include -Idep/lib/libzip/include -DVERSION=dev -MMD -O3 -march=core2 -ffast-math -g -Wall -DARCH_LIN -std=c++11 -c -o build/src/gui.cpp.o src/gui.cpp
src/gui.cpp: In function ‘void rack::guiInit()’:
src/gui.cpp:217:17: error: ‘GLFW_MAXIMIZED’ was not declared in this scope
  glfwWindowHint(GLFW_MAXIMIZED, GLFW_TRUE);
                 ^
src/gui.cpp:217:33: error: ‘GLFW_TRUE’ was not declared in this scope
  glfwWindowHint(GLFW_MAXIMIZED, GLFW_TRUE);
                                 ^
src/gui.cpp:248:75: error: ‘glfwSetWindowSizeLimits’ was not declared in this scope
  glfwSetWindowSizeLimits(gWindow, 640, 480, GLFW_DONT_CARE, GLFW_DONT_CARE);
                                                                           ^
src/gui.cpp: In function ‘void rack::guiClose()’:
src/gui.cpp:305:36: error: ‘GLFW_TRUE’ was not declared in this scope
  glfwSetWindowShouldClose(gWindow, GLFW_TRUE);
                                    ^
compile.mk:50: recipe for target 'build/src/gui.cpp.o' failed
make: *** [build/src/gui.cpp.o] Error 1
```

I think this is related with the version of GLFW I am using. This happens after I installed libglfw3-dev from the Linux Mint 18.1 official repos. If, instead, I install the old libgflw-dev the header file for glfw3 is, of course, missing:

```
g++ -Iinclude -Idep/include -Idep/lib/libzip/include -DVERSION=dev -MMD -O3 -march=core2 -ffast-math -g -Wall -DARCH_LIN -std=c++11 -c -o build/src/gui.cpp.o src/gui.cpp
In file included from src/gui.cpp:3:0:
include/gui.hpp:4:24: fatal error: GLFW/glfw3.h: No such file or directory
compilation terminated.

```
Not sure how to go on now. Maybe these macros were introduced with a later version of GLFW3? I don't think so because I can hardly see how a macro like GLFW_TRUE gets in at such a later point in the development of a library...

My version of glfw3 is:
```
Architecture: amd64
Source: glfw3
Version: 3.1.2-3
Depends: libglfw3 (= 3.1.2-3), libgl1-mesa-dev | libgl-dev, libglu1-mesa-dev | libglu-dev, libx11-dev, libxcursor-dev, libxi-dev, libxinerama-dev, libxrandr-dev, libxxf86vm-dev
Conflicts: libglfw-dev
Filename: pool/universe/g/glfw3/libglfw3-dev_3.1.2-3_amd64.deb
```

My system is Linux Mint 18.1 Cinnamon 64 bits:
`Linux  4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by leopard86** [comment]
On a second thought, among the dependencies in the dep folder I have the latest version of glfw3, so the compiler should look for that instead of looking for my system version.
What's the suggested way to do that?

**Comment by AndrewBelt** [comment]
Your glfw version is old. Use the dep folder.

**Comment by leopard86** [comment]
Yeah but should I change the -I path in the makefile manually?

**Comment by AndrewBelt** [comment]
The include path should already include `dep/include`

**Comment by leopard86** [comment]
Thanks, but...
$ ls dep/include/
curl  jansson_config.h  jansson.h  pa_linux_alsa.h  portaudio.h  portmidi.h  porttime.h  samplerate.h  zip.h

I soft linked glfw3.h in dep/include:
$ ll dep/include/glfw3.h 
lrwxrwxrwx 1 leopard leopard 63 Sep 18 19:12 dep/include/glfw3.h -> /home/leopard/temp/vcv/Rack/dep/glfw-3.2.1/include/GLFW/glfw3.h

However the error remains.

**Comment by AndrewBelt** [comment]
Did the `dep` build fail when you first ran it? Remove the glfw-* directory and rerun `make dep`.

**Comment by leopard86** [comment]
Apparently it did not, but cleaning and making the dependencies again worked. 

For future use:
Additionally I had to build the dependencies again after apt-getting libgtk2.0-dev because portmidi-dev was required.
Finally, the Rack.sh does not work as it is. We cannot just create a LD_LIBRARY_PATH but we have to export it, otherwise you get a missing library complaint like:
./Rack: error while loading shared libraries: libjansson.so.4: cannot open shared object file: No such file or directory

So my Rack.sh now looks like:
export LD_LIBRARY_PATH=/home/leopard/temp/vcv/Rack/dep/lib
./Rack.sh

As you see at the moment I am not installing anything and leaving in a temp folder. But I think I'll love this software and move it to my app folder very soon ;) ;) ;)
