### ISSUE TITLE
Rack for macOS does not contain any version information

### ISSUE THREAD

**Issue by core-code** [VCVRack/Rack#1070]
both the CFBundleVersion and CFBundleShortVersionString in your Info.plist file are empty strings. these should be filled with the correct version number of the release.

currently Rack just shows "--" as its version when you select it in the Finder and chose "Get Info" (and the "About Rack" dialoge also has no version number). also, third party tools that help you autmatically update apps can't update Rack because its impossible to determine its version.

**Comment by AndrewBelt** [comment]
The version is compiled into Rack and notifies you of updates when they release.

**Comment by AndrewBelt** [comment]
However, since it looks prettier when using Quick Look with the Rack.app bundle, I've fixed this in 51ea2695487bea419d8e6664f97a5bf3bffcb9a4
