### ISSUE TITLE
Warning indicating a failure in the brudge server

### ISSUE THREAD

**Issue by caecos** [VCVRack/Rack#1074]
Operating system:
Windows Pro 10, ASUS Rogue Core i7 processor

[6.659 warn src/bridge.cpp:330] Bridge server bind() failed
[6.659 warn src/bridge.cpp:321] Bridge server close() failed

**Comment by AndrewBelt** [comment]
This happens when Rack crashes and doesn't unbind properly, and you attempt to start Rack before the OS frees up the port binding. Or, when you have multiple instances of Rack open, which is unsupported. Other reasons could be antivirus or local firewall.

**Comment by caecos** [comment]
OK I will make a fresh build to see if I can manage to make it run properly...

**Comment by caecos** [comment]
You were right...it was my mistake, there was another instance of Rack running...everything works properly now...
