### ISSUE TITLE
Mouse Cursor Movement Out of Scale with Widget Adjustment

### ISSUE THREAD

**Issue by jonheal** [VCVRack/Rack#1075]
After many months, I suddenly realized the cursor disappears when I adjust a widget. Another user alerted me to the JSON setting to disable this behavior, but disabled, I now wee that the distance the cursor covers is way larger than the distance the widget adjusts.

Is this behavior "fixable?"

**Comment by AndrewBelt** [comment]
This issue is old and likely obsolete. Comment if issue is still present. Closing.
