### ISSUE TITLE
0.6.2 build prompts for installing 0.6.2b

### ISSUE THREAD

**Issue by CJunit** [VCVRack/Rack#1078]
I built for Linux 0.6.2 which appeared to be the most recent tag. But it displays as v0.6.1, and when starting it prompts me to install the more recent 0.6.2b. The beta usually comes first.

Sooo, simple question, really: which is the more recent version?

**Comment by AndrewBelt** [comment]
0.6.2b is the latest. I don't know why GitHub orders the way it does.

**Comment by CJunit** [comment]
OK, thanks!
