### ISSUE TITLE
Very high "Energy Impact" on OS X 10.11.6

### ISSUE THREAD

**Issue by qazwsxpawel** [VCVRack/Rack#1079]
Hi I've been experiencing very high "Energy Impact", as (reported by Activity Monitor app), from VCV Rack on my MacBook (and overheating) even with the simplest setup w/ minimal number of modules

*The number reported are in hundreds:*
<img width="1059" alt="screen shot 2018-08-03 at 10 54 25" src="https://user-images.githubusercontent.com/1409782/43637456-08c3a852-970d-11e8-9b82-49257175004e.png">
 

*CPU utilisation (is ok):*
<img width="1058" alt="screen shot 2018-08-03 at 10 53 03" src="https://user-images.githubusercontent.com/1409782/43637560-5f3fa834-970d-11e8-8928-365f733d0246.png">

*This is the results of running this random test setup (below) for ~2 minutes:*
<img width="1392" alt="screen shot 2018-08-03 at 11 06 14" src="https://user-images.githubusercontent.com/1409782/43637572-6e6807c0-970d-11e8-9514-e0d88c0a6c0f.png">

This happens regardless of modules etc. 

Thanks so much!

Operating system(s):
  OS X El Capitan--10.11.6 (15G31)
  Rack 0.6.2b (problem happens with previous versions of rack as well)
  MacBook Pro (Retina, 13-inch, Early 2015)
  Processor Name:	Intel Core i5
  Processor Speed:	2.7 GHz
  Memory:	16 GB
  Graphics:      Intel Iris Graphics 6100 1536 M

**Comment by AndrewBelt** [comment]
There are several duplicate issues about performance. See https://vcvrack.com/manual/FAQ.html#performance
