### ISSUE TITLE
src/gui.cpp line 240 expression gWindow dialog win64 failed load.

### ISSUE THREAD

**Issue by jackokring** [VCVRack/Rack#108]
0.3.1 official. click on Rack.exe in Rack folder, after extracting to desktop. No joy.
Intel HD 3000 graphics, system says latest drivers. Windows 10.

**Comment by jackokring** [comment]
Driver version 9.17.10.4459

**Comment by jackokring** [comment]
Went retrograde to intel's latest driver still no luck. It appears as though microsoft have destroyed opengl support in this driver, as there are reports win 7 works fine, win 10 does not do open gl with it.

**Comment by jackokring** [comment]
Is there a soft render opengl on windows? It's not as though rack is call of duty 900.

**Comment by jackokring** [comment]
Just run Geeks3D-0.7.0 GpuTest FurMark opengl 2.1/3.0 1280*800 FPS=7. So opengl is working. WebGL also works.

**Comment by AndrewBelt** [comment]
Can you clone the nanovg repo (it's already on ext/nanovg), build the `example_fbo` example, and run it?

**Comment by jackokring** [comment]
Maybe later. I have noticed though that fullscreen causes error. Not sure
if rack fullscreen gl.

**Comment by AndrewBelt** [comment]
Fullscreen, as in maximized?

**Comment by jackokring** [comment]
No full as in no window frame.

**Comment by AndrewBelt** [comment]
You can still do that? I thought I removed that feature.

**Comment by Cris--** [comment]
Also here with same Error.
[gpu_caps_viewer_report.txt](https://github.com/VCVRack/Rack/files/1321012/gpu_caps_viewer_report.txt)

**Comment by jackokring** [comment]
Last build just tested, some error about opengl 2.0, and drivers. Yes, latest drivers and win10. Gfx support says opengl3.1

**Comment by Cris--** [comment]
Found a fix! https://github.com/VCVRack/Rack/issues/643#issuecomment-360779715

**Comment by AndrewBelt** [comment]
This issue is old and likely obsolete. Comment if issue is still present. Closing.
