### ISSUE TITLE
can't build plugins with latest pull

### ISSUE THREAD

**Issue by davephillips** [VCVRack/Rack#1082]
Fedora 23 Linux
Rack v1 dev

Rack builds and runs fine but no plugins will load or build with the current tree. An example:

[dlphilp@The6300 21kHz-rack-plugins]$ make
g++  -Wsuggest-override -std=c++11  -DSLUG=21kHz -fPIC -I../../include -I../../dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/PalmLoop.cpp.o src/PalmLoop.cpp
In file included from src/PalmLoop.cpp:1:0:
src/21kHz.hpp:17:28: error: expected class-name before ‘{’ token
 struct kHzKnob : RoundKnob {
                            ^
src/21kHz.hpp: In constructor ‘kHzKnob::kHzKnob()’:
src/21kHz.hpp:19:74: error: ‘assetPlugin’ was not declared in this scope
         setSVG(SVG::load(assetPlugin(plugin, "res/Components/kHzKnob.svg")));
                                                                          ^
src/21kHz.hpp:19:76: error: ‘setSVG’ was not declared in this scope
         setSVG(SVG::load(assetPlugin(plugin, "res/Components/kHzKnob.svg")));
                                                                            ^
src/21kHz.hpp:20:9: error: ‘shadow’ was not declared in this scope
         shadow->box.pos = Vec(0.0, 3.5);
         ^
src/21kHz.hpp: At global scope:
src/21kHz.hpp:24:33: error: expected class-name before ‘{’ token
 struct kHzKnobSmall : RoundKnob {
                                 ^
And so on. Any suggestions ? I did not notice any announcement regarding the plugin API but maybe I missed something ?

**Comment by AndrewBelt** [comment]
The v1 branch is not ready for use.

**Comment by davephillips** [comment]
Understood. Not using it, just building and testing. Sorry for the noise.

**Comment by modlfo** [comment]
I'm closing this issue since it seems outdated.
