### ISSUE TITLE
Poly Mode

### ISSUE THREAD

**Issue by NothanUmber** [VCVRack/Rack#1084]
Hi,
great synth, it is a lot of fun fiddling around with!
Am mainly interested in creating patches for live-play with controllers suitable for expressive play.

Currently creating patches with several voices can be quite tedious for more complex patches - 8 voices requires copying stuff all around the place and every fine tuning step after "going multi voice" means copy'n'pasting dozens of module settings individually n times for each and every copy of that module.

It would be great if VCV would support the creation of poly-capable modules that can be connected with "poly-cables" which can transmit one signal per voice: Each input can receive a value on (e.g.) up to 16 channels and each output sends a separate signal on each channel.

If the output of a poly module is connected to the input of a normal single channel (but "poly-capable") module then VCV could internally create n instances of that module and route one channel of the incoming poly module to each instance of the cloned single channel module. Then this module is considered as "blessed" poly module and the search through the connection network continues to determine modules that have to be "blessed" to poly. Until a "poly to single" module is reached, which is essentially a mixer that mixes the channels from it's poly inputs into one channel.

This poly2single module could be put between modules that are supposed to be per voice and a global effects chain. Some modules could also be flagged as not "poly capable". A candidate for this would e.g. be the Audio-out module or CV out connections to hardware synths. Connecting a poly module (either natively poly or "blessed" poly) to a non-poly capable module wouldn't be possible, a poly2single module would always have to be put in between (can happen implicitly, see below).
Allowing to place poly2single modules explicitly would have the advantage, that people could also make expensive effect chains explicitly single voice - even though they theoretically would be "poly capable" and thus could be instantiated per voice. Additionally poly2single modules could be automatically added internally between poly networks and non-poly capable modules. Then connecting a previously single-voice network to a new poly-forcing module (see below) wouldn't lead to the situation, that some connections (e.g. the one towards the audio module) become invalid..

Single-modules who's outputs are connected to a poly-network but don't get poly-inputs wouldn't have to be instantiated per voice. VCV could multiplex their single output for each channel of the poly-inputs they are connected to.
Poly cables could get rendered differently than single cables (e.g. thicker), so people are aware of what is poly and what not.
When module parameters of "blessed to poly" modules are tweaked then VCV would automatically propagate this to all per-voice instances.

There could be different kinds of single-voice and poly modules that the SDK could support to write - so no complexity is added to writing new single-voice modules and making it easy to use existing modules in a poly context with optimally no (or very few) changes.
There could be four kinds of modules:
* Non-poly capable: These modules cannot be connected to an upstream poly network directly. A poly2single module has always to be placed in between implicitly or explicitly. This would e.g. be Audio, CV out or other modules that rely on unique resources (can only be instantiated once)
* Poly capable: These modules can only support a single voice but if connected to a poly network VCV can instantiate them several times internally and propagate voices and UI interactions to all instances accordingly.
* Native Poly supporting: Can be single-voice when connected to a single-voice-network and poly when connected to a poly network. In the latter case they don't have to be instantiated several times by VCV as they can handle several poly voices internally. (Supporting native poly modules would be good because it opens the door for optimizations like handling several voices at the same time via vectorization etc.)
* Native Poly-forcing: Inputs and outputs are always poly-cables, connected downstream poly-capable modules will be blessed to poly, upstream inputs from single-voice modules become multiplexed. Examples for this kind of module could be polymidi/mpe inputs or multitouch-capable onscreen keyboards.

This would make creating polyphonic patches a dream! And it would stay fully backwards compatible, as long as people aren't introducing a native "forcing" poly input everything can stay single voice - as is.

A caveat could be that this deviates from the hardware Eurorack concept - no poly-cables available in hardware. But imho this is a pretty intuitive deviation and not a capability-related but "just" a convenience feature - mapping a patch done with poly cables to single-voice hardware or vice versa should be trivial - it's just (potentially a lot) more patching work with only single-voice cables.

And last but not least: A poly patch with native poly-supporting modules could be more CPU-efficient than one built built from copy'n'pasted single voice modules by factors. This becomes even more crucial when looking at utilizing the capabilities of GPUs in the longterm where one or 16+ voices might not make a difference as long as they can be vectorized...

Would that be possible and viable? If yes, then it would instantly multiply the awesomeness of VCV by at least 8 to 16! ;)

**Comment by AndrewBelt** [comment]
Added along with #1118
