### ISSUE TITLE
Adjust virtual knobs using the mouse wheel

### ISSUE THREAD

**Issue by pkarydogiannis** [VCVRack/Rack#1086]
Be able to adjust the value of a knob/slider by hovering the cursor over it and adjusting the mouse wheel. 
It has been a very common mechanic with many audio plugins and it would improve the overall interaction with such a slider/knob heavy software environment.

Seems an obvious feature but I haven't been able to find a request for it. I apologise if it's a duplicate.

**Comment by AndrewBelt** [comment]
It's difficult to determine whether the user wants to scroll the rack or a knob. What's your proposal?

**Comment by pkarydogiannis** [comment]
Indeed, the solutions that come to mind are:

- Scrolling on top of a knob while holding a modifier key changes the value of the knob. 

- Two modes, one where the user can scroll as it is now, and a mode where the mouse wheel adjust      the parameters it's hovering above.

Or it could be a combination of both. Being able to assign a keyboard shortcut for the modes scenario, and having a clear simple indicator in the toolbar of which mode the user's on would be pretty neat.

**Comment by AndrewBelt** [comment]
Roughly what percentage of mouse wheels are continuous (or a very low step size) rather than discrete?

**Comment by pkarydogiannis** [comment]
It's hard to find any reliable data on that, purely anecdotally I would say the majority of mice I've encountered so far are stepped. The number of steps varies from model to model with only gaming mice publishing any specs on the number of steps (in the order of 12-24).
Also I guess trackpads are used a lot in rack and they are continuous.
Some sort of scaling will therefore be unavoidable. 
A suggestion might be to make it adjustable in the settings file.

**Comment by timm052** [comment]
This would be a great feature and make using knobs in vcv feel a lot more immediate, I use it all the time in ableton. The middle mouse is pretty good for navigating the rack so making it as an optional mode would make sense possibly with modifier keys to determine the value increment amount.

**Comment by chrisgr88** [comment]
Did anything ever come from this discussion?  It would be great to be able to adjust settings by holding a modifier key, hovering over a control and scrolling - either a continous mouse wheel or trackpad.  Is it planned for Rack version 2?  Has anyone created a private fork that does this?  If not, then I may look into it.

**Comment by AndrewBelt** [comment]
@chrisgr88 Rack 2 will have this feature.
![2021-05-22-115718_1600x900_scrot](https://user-images.githubusercontent.com/338179/119232999-ff1fe900-baf4-11eb-8363-2a4186b83e0b.png)

**Comment by stoermelder** [comment]
> Did anything ever come from this discussion? It would be great to be able to adjust settings by holding a modifier key, hovering over a control and scrolling - either a continous mouse wheel or trackpad. Is it planned for Rack version 2? Has anyone created a private fork that does this? If not, then I may look into it.

You can use my modules SPIN and SAIL right now for using mouse wheel on parameters.

**Comment by chrisgr88** [comment]
Thanks Ben!  You modules do exactly what I was looking for.  VCV Rack continues to amaze me...
