### ISSUE TITLE
use -fsanitize GCC and CLANG switch

### ISSUE THREAD

**Issue by BabeleDunnit** [VCVRack/Rack#1087]
Hello everybody,

First on, please allow me to introduce myself (cit. :) ) : I am an experienced C/C++ VR/AR/Videogame developer with a strong passion and some occasional experience in audio development, being also a semi-professional musician. I landed on VCV Rack some months ago on behalf of the stellar Antonio Tuzzi AKA NYSTHI, which also I know since many years, and I lurked since now. VCV is AMAZING, period. I hope to find some time to play with it and write some stuff I have in mind since forever.

So, in the meanwile, why am I writing here? I did a search on all the issues and code etc and I noticed that nobody seems to be using the -fsanitize GCC/CLANG switch. I myself have discovered it only recently, between the thousands of compiler switches we all know.

PLEASE PLEASE PLEASE give a try to this compiler option. This is the GOLANG sanitizer port, an IMPRESSIVE tool, and it is gonna find all of your memory overruns, out-of-bounds, memory leaks, even data race conditions in multithreaded scenarios, and more. For anybody used to work in plain C in the good ol' days, you will ask yourself how we managed to write working code without it. Forget the difficulty of use of Valgrind and similar tools. This is a BREEZE.

if used with -g option, It will print/generate detailed stack traces of who did what and where, memory dumps of offended/out-of-bounds/data race regions, malloc()s without free()s, new() without delete() (I see VCV does not use smart pointers...), etc etc. It is AMAZING.

At work, we mantain a debug makefile of our stuff with "-g -O0 -fsanitize=address" flags; you can even try an optimized "-g -O3 -fsanitize=address" build if performance is an issue (it always is). Obviously the sanitizer will instruments code, which will run significantly slower, but you are going to kill a lot of bugs anyway.

Please note: the sanitize switch is NOT implemented on MSYS (aka Windows) GCC port AFAIK. It IS implemented on both Linux GCC (since V5, i believe) and OsX CLANG, even if with minor differences.

I hope this small contribution can be of interest for this impressive product and community.

Aaron/Babele

**Comment by AndrewBelt** [comment]
https://github.com/google/sanitizers/wiki/AddressSanitizer
>The average slowdown of the instrumented program is ~2x

**Comment by BabeleDunnit** [comment]
Absolutely not. As stated, is just a debug trick to save time (potentially A LOT of time) from painful debugging sessions and use it in much better ways... just wanted to share the info with the devs community.
