### ISSUE TITLE
Building under slackware Linux issues

### ISSUE THREAD

**Issue by Strum** [VCVRack/Rack#1089]
Operating system(s): Slackware Linux
Version of Rack: Latest Source

So I'm trying to get Rack going on slackware.
I tried the Linux binary package on the front page of VCVRack.com, incompatible format.

So I cloned the code and it builds ok, loads in the blink of an eye, got a driver issue getting audio out of it but i expect that's nothing to do with rack, so far so good.

So I start to build the modules, starting with fundamental and I get a cast error

here is the console text:

```
src/Delay.cpp: In member function 'virtual void Delay::step()':
src/Delay.cpp:77:19: error: invalid conversion from 'const float*' to 'float*' [-fpermissive]
   srcData.data_in = (const float*) historyBuffer.startData();
                   ^
../../compile.mk:64: recipe for target 'build/src/Delay.cpp.o' failed
```

So I went on to try Audible which compiled and loaded ok, then befaco which failed due to incompatibility of a binary library in the befaco package for the reverb, output below

```
/usr/lib/gcc/i586-slackware-linux/5.5.0/../../../../i586-slackware-linux/bin/ld: i386:x86-64 architecture of input file `build/src/SpringReverbIR.pcm.bin.o' is incompatible with i386 output
collect2: error: ld returned 1 exit status
../../compile.mk:55: recipe for target 'plugin.so' failed
```

Judging by the performance of other applications on slackware and the eye blink loading speed of Rack I expect I'll get good performance and be able to run bigger patches than under windows on a similar powered machine if I can get it working.

**Comment by AndrewBelt** [comment]
Did you run `make dep` in the Fundamental repo?

**Comment by Strum** [comment]
Thanks  Andrew, no i didn't make dep for the fundamental, will try that.

not had to do that under windows

it's 64 bit linux

**Comment by AndrewBelt** [comment]
It looks like you're running an IA-32 version of Linux. That architecture is so niche, I definitely can't support it, but I suppose you could hack around in the Makefiles to make the `build/%.bin.o` target work.

**Comment by Strum** [comment]
Fair enough, personally I don't like the commercial Linux distros, I tried Arch but it's not for me so I've gone back to the original linux, slackware. My beard is not long enough for gentoo

Yes building everything from source and dealing with the incompatibilities due to it being somewhat niche is a bit of a hassle but boy does it go fast when you do get something going.

I don't know enough to mess with the make file for befaco but i can disable the reverb module in the code to get it to build.

I might have some issues with drivers, but I don't know enough about linux audio to tell if it's the system or Rack yet. 

I'll keep you posted on my progress but don't expect you to make changes just for one user using a niche OS.

Thanks again.

**Comment by modlfo** [comment]
I'm closing this one since it seems there's not much to do on the Rack side.
