### ISSUE TITLE
Application Not Responding on Mac

### ISSUE THREAD

**Issue by DaveTas** [VCVRack/Rack#1094]
So, I've just installed Rack-0.6.2b on my Mac Pro, and after right clicking to open, the Rack icon appears in my dock, bounces for a bit like it's loading and then stops. right clicking on the icon shows Application Not Responding and I have to force quit. 
I've reinstalled the drivers for my graphics card, just to make sure I had the correct one for my OS, hasn't changed anything though. 
Haven't attempted building from source yet, would prefer to just use the installer, so hoping it's something stupid simple that I'm missing. Any help will be much appreciated, keen to play with the Mutable Elements module. All my details below. Cheers.

MacOS Sierra - 10.12.6
Mac Pro (Mid 2010)
Processor - 2.8 GHz Quad-Core Intel Xeon
Memory - 20 GB 1066 MHz DDR3
GPU - NVIDIA GeForce GTX 770 4096 MB (has been flashed with a Mac BIOS)
Audio Interface - Focusrite Saffire Pro 14

FYI, I've tried installing on my MacBook Pro (2013) as well, and have the same problem. 

Would it have anything to do with old audio interface drivers causing problems? I used to run an Mbox Mini, but swapped it out for the Focusrite. I'll occasionally use the Mbox on my lappy,, but it has issues with the latest OS's, and I can't update the firmware on it anymore. I dunno, just a thought.

Cheers

**Comment by endreola** [comment]
Same issue here, same Rack rev.

MacOS 10.13.6

**Comment by AndrewBelt** [comment]
This issue is old and likely obsolete. Comment if issue is still present. Closing.
