### ISSUE TITLE
Stuttering issue with large buffers on SB Omni Surround 5.1

### ISSUE THREAD

**Issue by Rcomian** [VCVRack/Rack#1097]
**Operating system(s):** Linux (gentoo, kernel 4.17.19)
**Version of Rack:** 0.6.2b official linux binary
**All hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):** 

* SoundBlaster Omni Surround 5.1 <- problem device
* Scarlett Solo USB
* Realtek ALC1150 on motherboard
* ALSA & Pulseaudio

**Description**

When I output using the ALSA driver to the SoundBlaster surround sound card the sound is distorted if the block size is too *large*.

This is with the vanilla binary, running two modules (fundamental vco and the audio module) and pulseaudio configured to use other devices.

The distortion is kind of like stuttering. There are no outputs on the commandline at all - no buffer underruns or other messages or errors.

When I use 48kHz output, the stuttering is there for the 256 block size and up. When I use 96kHz output, it sometimes works on 256 block size, but is definitely present for all larger block sizes. The engine sample rate doesn't affect anything, only the output sample rate. The omni only supports those two rates..

This doesn't affect any of my other devices when talking directly to them with the ALSA driver. In particular, the scarlett solo usb is the cleanest sound you can get whatever you throw at it.

If I use default (pulseaudio) output then I can get a similar effect talking to my internal hardware, but only with block sizes of 2048 & 4096, and pulseaudio has weird issues anyway.

I'm raising this because I don't understand why having too large a block size could ever be a bad thing. Too small makes perfect sense and yes I do get issues with the 64 length blocks on occasion.

This happens even immediately after a clean power down and restart and is not transitory. For a long time I thought my Omni was broken, but using it for normal youtube and games through pulseaudio was fine.

Is there anything known that could be causing this? Is it some weird insidious bug in the buffering code?

I've just thought maybe it's a hardware issue - maybe the hardware only supports a buffer of 128 samples and overwrites itself if we write too much in? The distortion does sound very different for the different block sizes.

I've taken a video demonstrating the issue:
https://photos.app.goo.gl/cAcmVX156jGDpj5B8

**Comment by AndrewBelt** [comment]
This issue is old and likely obsolete, closing. Comment if issue is still present.
