### ISSUE TITLE
Scalar: Issue resetting CENTS

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#1099]
Operating system(s): Ubuntu 18.04
Version of Rack: 0.6.2b

- Add Scalar plugin to Rack
- Right-click on CENTS value, NOTES reset to 0.
- Right-click CENTS again, observe that NOTES changes to -4194304.
- Right-click CENTS again, observe that NOTES changes to -2147484648.

**Comment by AndrewBelt** [comment]
This issue is caused by the disabled CENTS value on note 0 (the root note) not actually being disabled, creating undefined behavior when the right-click action is triggered. Will be fixed in Scalar 0.6.1.

**Comment by AndrewBelt** [comment]
Updated

**Comment by cschol** [comment]
Fix confirmed. Thank you!
