### ISSUE TITLE
 Jack Xruns when the port 5 to 8 are connect

### ISSUE THREAD

**Issue by infamedavid** [VCVRack/Rack#1101]
I m using renoise as dummie  to enable the output ports from the 1 to 8 in vcvrack ,
I create 16 inputs mono channels in renoise (8 stereo)
I m using two audio modules, the first one work correctly if I select on the list 1-2 input , 1-8 output
if I added another audio module and connect using 9-16 output can get any sound , instead I get Xruns
(the first one module continue working perfectly and the sound is clear)
If I chose from the list the port 1-2 input, 1-8 output or simply duplicate the first one Audio module it work perfectly

http://pasteall.org/pic/show.php?id=f414f8cc1cc69967c80ca509ab9cd7ba

Operating system(s): lubuntu 16 4
Version of Rack if using official binary  0.6.2b 
audio/MIDI device scarlet solo

**Comment by infamedavid** [comment]
I m using renoise as dummie to to use the output ports  from the 1 to 8 in vcvrack ,
I create 16 inputs mono chanels in renoise (8 stereo)
 I m using two audio modules  the firt one work amazing if I select on the list 1,2 input - 1, 8 output 
if I added another audio module and connect using 9 ,18 output can get any sound , instead I get Xruns 
(the first one module continue working perfectly  and the sound is clear)
If I chose from the list the port 1,2 input - 1, 8 output or simply duplicate the first one Audio module it work perfectly

**Comment by martinbangens** [comment]
Same problem for me

Operating system(s): Ubuntu Studio 18.10
Version of Rack if using official binary 0.6.2b

**Comment by AndrewBelt** [comment]
This issue is old, closing. JACK is not officially supported, but comment if issue is still present.

**Comment by martinbangens** [comment]
yes its still present, why should the user even select a "device" from the list? when I use jack from application to Ardour with jack I get xrun and the lamps in vcv rack blinks from audio 8 module. Now its caches itself and I can't run it
