### ISSUE TITLE
Issue with VCVRack downgrading modules via plugin manager.

### ISSUE THREAD

**Issue by Nightquaker** [VCVRack/Rack#1103]
Greetings!
It's not really a bug, but seems more of an issue that was overlooked or maybe one that requires a lot of resources to solve.
Since VCVRack can actually "see" the plugin versions in the browser, is there a way for the Plugin Manager to skip the plugin download if there is already a newer version installed? Say, a newer version from GitHub or just about any third-party source.
Today, I was rather unpleasantly surprised to find some of my modules downgraded after pressing the "update plugins" button.

Thank you!

**Comment by AndrewBelt** [comment]
Remove them from your account in the Plugin Manager and they will no longer sync.
