### ISSUE TITLE
Accessing to all Audient ID22 optical outputs make Rack freezes

### ISSUE THREAD

**Issue by killkrt** [VCVRack/Rack#1106]
I need to access to all 8 digital outputs of my Audient ID22 in order to control an Expert Sleepers ES-3.
In order to do that I am supposed (as I understood) to instantiate two _Audio_ modules:

- Audient ID22 (1-8 in 1-8 out): in order to access first two digital outputs via ports 7 and 8.
- Audient ID22 (9-10 in, 9-14 out): in order to access the other six digital outputs via ports 9 to 14.

Anyway as soon I setup the second _Audio_ module the application freeze.

I've noticed that when it happens I have this warning on the console:

`[0.471 debug src/Core/AudioInterface.cpp:74] Audio Interface IO underflow`

Technical info:
OS: macOS 10.12.6
Audio interface: Audient ID22 (with both ADAT in/out connected)
Revision: [c0933e](https://github.com/VCVRack/Rack/commit/ec0933e8ff70fef69e90bc1c51bd65a468ac8c9c)
Compiler: clang-900.0.39.2
Sample rate used: 44KHz/48KHz

**Comment by AndrewBelt** [comment]
Using multiple VCV Audio modules will be supported in Rack v2.
