### ISSUE TITLE
Preset Manager: Core Module that remembers and recalls presets of other modules

### ISSUE THREAD

**Issue by andrew-e** [VCVRack/Rack#1107]
I tried to mark as a feature request, sorry it didn't!

This is inspired by a similar tool in puredata called [automatonism](https://www.automatonism.com/), and it's called 'Present Manager' there.

It's extremely powerful, as it lets you recall the settings of parameters of all the other modules, recall what the parameters were, and cycle through the different saved parameters on gate trigger.  It also allows the values to be panned over 1, 10, 60 seconds.

It's not really a module anyone else can make, other than the core rack, as it needs to know the values of every other module.  It really can make what you create so much more powerful to play with.

**Comment by AndrewBelt** [comment]
This would nonintuitive and bad UI. Modules shouldn't communicate with other modules through methods other than cables. (That's the nature of modularity.)
