### ISSUE TITLE
Rack window stays all white (can only see window bar) on Win10 Pro

### ISSUE THREAD

**Issue by Spamkob** [VCVRack/Rack#1108]
Hi Andrew and all on GitHub, 

after successfully running 0.62b on my Macbook - VCV Rack is simply great, thank you so much! - I switched to Windows 10 and ran into troubles: 

When I start the program, first I get the "could not load plugin" error (which is already covered in other threads) but then the screen stays all white. I can only see the window bar. I can move the window around; if I resize it the white background stays the same size, the rest of the window is black. 

Current setup is Win 10 Pro V1803; AMD 7790 graphics card with Radeon Settings Version
2018.0918.2010.36324 / OpenGL® Version 24.20.11000.13539 on an Intel i5-2500k; screen resolution is 1920x1080. 

So far I've tried the genuine windows graphics driver and two different drivers from 2013 and 2017 with the same results. Also tried so change the screen resolution. 

The on-board graphics card is turned of in BIOS and there's no intel drivers/software running in the background (onboard would be the HD 3000 with the Open GL 2.0 issue). 

Luckily I still have my old MB. Anyway, I hope this feeback is of any help. 
Well, and of course I would be more than happy if anyone has an idea to solve it. 

Thanks and keep up the good work! 
Jakob 

[log.txt](https://github.com/VCVRack/Rack/files/2417233/log.txt)
![capture_white_window_and_resized](https://user-images.githubusercontent.com/43588847/46045638-820efc80-c11e-11e8-98fa-4da1c810b992.PNG)
![capture_plugins](https://user-images.githubusercontent.com/43588847/46045642-8804dd80-c11e-11e8-9e5f-6c1163d9b13c.PNG)

**Comment by matass** [comment]
Error message says everything. You need to install missing plugins:)

**Comment by AndrewBelt** [comment]
Yeah, the white screen is because the dialog box opens before the first frame is rendered.

**Comment by Spamkob** [comment]
Thanks for the replies. Unfortunately the same white screen occurs after deleting the user folder (incl. plugins plugins) and uninstalling and reinstalling both V6.2. and V6.0. the log does not show any error messages. Tried isntalling with VST and and without...

**Comment by Spamkob** [comment]
Hi Again, 
don't know if anyone reads this still, since it's closed but running into the same problems (white screen, not even a menu bar) with LibreOffice I'm pretty sure that it has to do with OpenGL. 

For LibreOffice I changed the registry: 
[HKEY_CURRENT_USER\Software\Policies\LibreOffice\org.openoffice.Office.Common\VCL\UseOpenGL]
"Value"="false"
"Final"=dword:1
[HKEY_CURRENT_USER\Software\Policies\LibreOffice\org.openoffice.Office.Common\VCL\ForceOpenGL]
"Value"="false"
"Final"=dword:1

After that the program was starting without issues again. 
Anyway, I don't expect VCV rack will run without OpenGL? Any ideas on this?

Thanks, Jakob
