### ISSUE TITLE
Named and typed input, outputs and parameters in the module API

### ISSUE THREAD

**Issue by JTriggerFish** [VCVRack/Rack#1109]
Could future APIs require modules to declare a name string and an Enum type ( e.g INT, BOOL, FLOAT  ) for each of their inputs, outputs, and parameters ?
This would be a necessity for interfacing with OSC, hardware ( e.g Push2 or Maschine ), or programmatically patching modules etc.

Many thanks.

**Comment by AndrewBelt** [comment]
All ports and params are floats. Names will be added in Rack 1.0.

**Comment by JTriggerFish** [comment]
Yes they are floats but the range of meaningful values can vary.
For a switch only 0.0 and 1.0 for instance are useful.
Someone who wants to interact with that parameter without going through the GUI needs to know that information.

**Comment by AndrewBelt** [comment]
If a user is in MIDI map mode, they'll map a button to a CC command. If the controller is a button, it will send only 0 to 127. This will map to 0 and 1, exactly what button parameters need. It will be up to the user to decide which physical control is relevant for each virtual parameter. Type metadata is useless in this case and very tedious work.

**Comment by JTriggerFish** [comment]
I agree for manual midi mapping but my point was about the ability to create automatic control mappings of modules in e.g Push, Maschine, TouchOSC etc.
Manual control mapping is very tedious.
The main limitation of VCV is that tweaking buttons with a mouse is unpleasant so I do think catering for this is important.
Alternatively it could even be done at the gui control element  level ( e. Switches are BOOL etc ) as long as it gets registered in a dictionary somewhere that can be read.
