### ISSUE TITLE
Hotkey for Pause/Resume Engine

### ISSUE THREAD

**Issue by darloth** [VCVRack/Rack#1113]
I'd like a hotkey for pausing and resuming the sound engine.

I believe it would also be useful as a panic mute button, but there are more uses than this - I often pause the engine when I alt-tab to do something else, because that way Rack won't use fruitlessly use CPU it would otherwise be using processing sound that just gets muted.  (As an aside, Rack also uses a chunk of CPU when not in focus and not minimized, presumably on drawing stuff.)

If it doesn't cause any issues elsewhere, I would suggest Space as the toggle for this feature, if implemented.

**Comment by caillou** [comment]
Using the `Space` key is impracticable, as it is used when users input text, e.g. in the [Core Note Module](https://vcvrack.com/manual/Core.html#notes).

While I like the Idea of a pause button, quitting the application already feels like a freeze button, as it auto-saves the current patch with all of its state, and restarts quickly. Hitting `[Command] + Q` is really quick. Starting the app with Spotlight too.

**Comment by darloth** [comment]
ctrl/cmd-q is a hidden hotkey with no obvious UI hint nowadays.  Thanks for letting me know about it, but perhaps there should be (as a separate issue, no doubt) a hotkey list :)

On windows the first load is slow, and the rest are faster but still not instant.  It's a good workaround for now.  I still think a pause would be helpful.

At least on my keyboard, there's a pause key.  How about that?

**Comment by AndrewBelt** [comment]
I have removed engine pausing from Rack v2 because it no longer makes sense with the engine architecture. Now, modules like VCV Audio control stepping of Rack's engine, so pause functionality would have to be built into that module instead of Rack.
