### ISSUE TITLE
Plugin browser features

### ISSUE THREAD

**Issue by MazeOfEncryption** [VCVRack/Rack#1114]
There are a few things missing from the plugin browser which I feel could add a lot to the quality of workflow throughout VCV rack. The largest missing component is the ability to stay in a section/search after you have exited the browser or chosen a plugin. It would be much easier to look through new plugins and find the right plugin to use when you have a list of several. The second thing is maintaining scroll position - It's quite a pain when you're looking through modules, as you must scroll back down to where you were if you want to browse more modules alphabetically.

Besides these 2 features which are much more needed, there are 2 more which I would like to see. For one, a category with a list of all of the plugins currently in your project. This can be useful when you have a large project and want to use the same plugin twice without having to ctrl d over it or find it again. The other thing is custom categories - It would be quite nice to sort my favorite plugins into different categories, i.e. one category for mixing, perhaps, or another for sequencing.

Although I do think all of these features would be nice, the first one - maintaining current category - is the most important to workflow, and I feel like it is a must have for good workflow.

**Comment by mikeloveridge** [comment]
Check out Submarine's Module Browser.  It does most of what you're asking for.  I have come to include it in my template.vcv with his wire manager.  He also has some nice custom text blanks so you can label sections, etc.

**Comment by xaez** [comment]
@MazeOfEncryption,

yes, this feature (building of several plugin-categories) should be immediately embed into the next update of vcv rack, thx

**Comment by gilbertohasnofb** [comment]
> a category with a list of all of the plugins currently in your project. 

That would indeed be super handy. 

> sort my favorite plugins into different categories, i.e. one category for mixing, perhaps, or another for sequencing.

And this as well. I have tons of modules installed and I've favourited quite a few of them which I use often, and finding them among my favourites is already becoming a problem.

One more note. While I think that the organization of favourites according to the author is handy in many cases, I do miss to have a simple button that would sort them alphabetically. I find myself typing the name of the module more often than not, since that has become faster than finding it in my list.

**Comment by AndrewBelt** [comment]
This issue is old and likely obsolete since the Module Browser has been overhauled in Rack v1. Closing.
