### ISSUE TITLE
Proposal: Generate more than one sample at once

### ISSUE THREAD

**Issue by mcclure** [VCVRack/Rack#1115]
I hear work on 1.0 is starting so this seemed like a good time for an architectural proposal. (Note, I have not been following VCV Rack's design closely since 0.4, so if what I am about to say has already been discussed I missed it.)

In VCV rack plugins every audio sample is calculated one at a time. Inputs, outputs and params have this "value" value https://github.com/VCVRack/Template/blob/v0.6/src/MyModule.cpp. This model is easy to think about and easy for plugin devs. However, it has performance implications. If you calculate 1024 samples, module::step() will be called 1024 times, and you will be paying for 1024 virtual call dereferences. Because a compiler cannot inline a virtual call across a shared-library boundary, compiler optimizations related to loops will not be able to activate and my expectation (I have not tested this) is that cache utilization will not be as good as it could be.

I would like to propose a slightly different model. Plugins could opt-in to being able to process multiple “step”s at once. A plugin would volunteer the maximum number of samples it can handle per step() call. If VCV Rack realizes it’s found a situation where multiple samples can be processed at once, then instead of each Param, Input or Output containing a single value it would contain a pointer to an array and a “length”. The plugin could then process all 1024 samples (or whatever) in a loop within the step() call. The compiler would be able to do all its fanciest tricks like like loop coalescing or SIMD, and any buffers used by the plugin would stay in-cache the entire loop.

Situations where multiple samples could be processed at once include:

* The VCV Rack audio thread knows it will be at least a certain number of samples before any more knob twiddles come in from the UI thread (maybe it can just assume parameters do not change during a single call to the OS audio callback).
* If the mouse cursor is not hovering over a module (and there is no touch screen…), you can assume the user won’t be changing any parameters for at least a few milliseconds.
* It would be useful for VCV Rack embedding. I am very interested in embedding the VCV Rack audio engine inside of, for example, a video game. Similarly, you could imagine an “offline mode” for VCV Rack that runs a patch for 60 seconds and records its output. In either of these cases, all parameters are either known or somehow automated in a predictable way.

Sometimes doing multiple samples at once will not be possible. If two modules are recursively plugged into each other (output of A into input of B, output of B into input of A), you will have to calculate one sample at a time for each so that they always have an accurate last sample. (In this case, you’d just call the multisample step with a buffer length of 1.) But for most patches, doing multisample steps for some or most of the module graph would still be possible, so you would still get some speedup even on patches with recursion. Even if you have a plugin that doesn’t opt-in to multisample steps that is plugged into one that does, you can still get some benefit; you could run a 1-sample-at-a-time plugin 1024 times to fill out a buffer for a multisample plugin, or you could run a multisample plugin once and then call the one-at-a-time plugin 1024 times on the resulting buffer. You’d have to do some graph math at runtime to figure out the correct buffer strategy for a given configuration of wires, but things like the tarjan algorithm are pretty efficient and easy to find as open source so that’s not so bad.

I think VCV Rack is super cool, but performance is consistently my biggest problem with it. Crackling noises are consistently present when I try to run patches. Maybe I could fix that with the thread priority plugin, or by switching to Windows. But even if I was able to get Rack running without pops consistently on my computer, I really am interested in the idea of embedding Rack’s engine into other applications and in that case it would be necessary to squeeze out every bit of performance possible. I believe multisample steps would be one step toward better performance, and it would make VCV Rack more resemble other audio engines.

**Possible implementations**

One way to implement this: Param, Input and Output could all inherit from a new struct Data:

struct Data {
	float value = 0.0;
	float *buffer = &value;
}

and Module could have a virtual unsigned int maxSamplesPerStep() { return 1; } that modules can override. If the module doesn't care it could return 0xFFFFFFFF. Either step() would be changed to step(int samples) (and single-step modules would just ignore their int argument, or both could exist and the default implementation of step(int) would just call step()), or an unsigned int bufferSamples = 1; could be added to Module. Basic modules could thus just continue implementing step(), and using param[whatever].value.

When a patch is loaded, or when a wire is moved, VCV Rack could make a shadow graph with one node per module, store the maxSamplesPerStep() for each module and do a Tarjan sort on it. This would give you a list of which order to call the modules in on each step() (ie it would sort nodes by what data the direction flows in), and would flag the nodes which are in a cycle with other nodes (ie it would tell you which nodes have to run in one-sample-at-a-time mode)

When step() is called on multisample modules, VCV Rack could run down the Params, Outputs and Inputs and either set the buffer values to preallocated buffers from a pool, or leave buffer set to &value if the module has to run in one-sample-at-a-time mode currently. For inputs, it could set the buffer to the same buffer that the output it is wired to used. VCV Rack would guarantee that the buffer pointer always points to a buffer which is of size at least bufferSamples, and bufferSamples will always be less than the last value returned by that module’s maxSamplesPerStep. Since the value of "buffer" at times other than during a step() call should probably be undefined, Rack would probably also set "value" in the Input, Output and Param objects to the value from the final sample of the most recent  step, so that the value could be read by the GUI.

(I don’t know if there are situations where it would make sense for Param to be a single value instead of a buffer, and I don’t know what the correct thing to do with Lights would be.)

If you really wanted to get fancy, you could improve this a little more by introducing the idea of a GUI object on the rack which has multiple Modules inside it. Consider something like the Multiple module from the Audible Instruments package. This module is split into three sections that don’t interact. You could imagine someone creating a fake “cycle” by plugging the top third of Multiple into an input module X, then plugging an output of module X into the middle third of Multiple. The system described above would force both Multiple and X into one-sample-at-a-time mode even though this is not technically necessary. If each third of Multiple were a different Module object, on the other hand, it would be detectable that this is not really a cycle. But I don’t see any reason to attempt this for 1.0.

**Comment by AndrewBelt** [comment]
Yeah, I don't see a point of Rack managing the buffers for you, since you can easily buffer yourself, like in many of the Audible Instruments modules.

The overhead of tossing around one sample at a time and filling up the buffers of modules is low compared to the activity in the modules' `step()` function. For example, the overhead might be 0.1-0.5 [millisamples](https://vcvrack.com/manual/Toolbar.html#power-meter), while most useful plugins spend 10-50 mS on average doing their DSP. So if this proposal was implemented, it would save maybe 1% CPU. I disagree that this would be a massive improvement.

**Comment by mcclure** [comment]
I assume that if Clouds processes a block of 32 samples in one step, it is going to have to delay its output by 32 samples in order to do this…

Can you clarify— "you can easily buffer yourself"— what I'd be proposing is Rack managing buffers of data passed *between* plugins (not currently a meaningful concept since data is passed only in the value float). By buffering you mean delaying output…?

**Comment by AndrewBelt** [comment]
Regardless of whether your plugin or Rack handles the buffers, it has to be delayed by the buffer size, to assure generality for feedback loops.

**Comment by modlfo** [comment]
I'm closing this it seems like implementing something like it would require a big rewrite of the Rack engine and also all the plugins. There are unresolved problems like how to handle loops of connected modules. In addition, the benefits of doing this change are not entirely clear.
