### ISSUE TITLE
Non-bundle Linux installation

### ISSUE THREAD

**Issue by mkoskar** [VCVRack/Rack#112]
E.g., for Linux package should look like:

```

/usr/
/usr/bin/
/usr/bin/vcvrack
/usr/share/vcvrack/
/usr/share/vcvrack/plugins/
/usr/share/vcvrack/plugins/AudibleInstruments/
/usr/share/vcvrack/plugins/AudibleInstruments/plugin.so
/usr/share/vcvrack/plugins/AudibleInstruments/res/
/usr/share/vcvrack/plugins/AudibleInstruments/res/*
/usr/share/vcvrack/plugins/Befaco/
/usr/share/vcvrack/plugins/Befaco/plugin.so
/usr/share/vcvrack/plugins/Befaco/res/
/usr/share/vcvrack/plugins/Befaco/res/*
/usr/share/vcvrack/plugins/ESeries/
/usr/share/vcvrack/plugins/ESeries/plugin.so
/usr/share/vcvrack/plugins/ESeries/res/
/usr/share/vcvrack/plugins/ESeries/res/*
/usr/share/vcvrack/plugins/Fundamental/
/usr/share/vcvrack/plugins/Fundamental/plugin.so
/usr/share/vcvrack/plugins/Fundamental/res/
/usr/share/vcvrack/plugins/Fundamental/res/*
/usr/share/vcvrack/res/
/usr/share/vcvrack/res/*
```

For that to work CWD should be practically ignored and search path established with `/usr/share/vcvrack` for system resources and plugins, and (conforming to XDG specification) `~/.local/share/vcvrack/plugins` for user-specific plugins. Also `autosave.json` and `settings.json` should be placed into user's home directory e.g., `~/.config/vcvrack`.

**Comment by AndrewBelt** [comment]
In my opinion, Rack should go in /opt/Rack, and external files should be organized based on #113.

**Comment by mkoskar** [comment]
That's what I do, I put it into `/opt/vcvrack` for now. I compile and distribute against system dependencies (ArchLinux) so my `/opt/vcvrack` contains only `Rack` `plugins` and `res`, and then `/usr/bin/vcvrack` is shell script that just `cd /opt/vcvrack; ./Rack`. It seems to me that's how you envision it based on #113, i.e., CWD is in vcvrack's installation directory, right?

**Comment by CJunit** [comment]
I installed it in /opt/ as well. mkoskar, what sort of shell script do you use? When I type "./Rack" it fails to start, saying that it fails to locate the existing libraries. But when I type "make run" from within the directory the program starts fine.

**Comment by mkoskar** [comment]
@CJunit see https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vcvrack-git

**Comment by AndrewBelt** [comment]
You can install Rack to anywhere you like and use any user folder that you like by calling Rack with command line arguments. See https://vcvrack.com/manual/Installing#command-line-usage

For example in your case, create a script that calls
```bash
./Rack -s /usr/share/vcvrack -u ~/.config/vcvrack
```
and it should work as you intend.
