### ISSUE TITLE
Proposal: Add All Free Plugins To Account With One Click

### ISSUE THREAD

**Issue by lnorton89** [VCVRack/Rack#1120]
Seems rather bizarre you can't add all the free plugins to your account with one click on the web site. What's the reasoning there?

**Comment by MazeOfEncryption** [comment]
Agreed. With this enabled, you should also automatically have new plugins added to your account.

**Comment by AndrewBelt** [comment]
That would not be a good idea.

**Comment by lnorton89** [comment]
Any reasoning as to why?
