### ISSUE TITLE
VCV Scalar on Ubuntu 18.04

### ISSUE THREAD

**Issue by Cordoha** [VCVRack/Rack#1121]
VCV Rack 0.6.2b
VCV Scalar
Ubuntu 18.04

While right clicking, left clicking, ctrl+right clicking, ctrl+left clicking on the plugin, no notes appear. I think this is also a reference bug with the shortcut codes as well. I can't ctrl+d to duplicate either, haven't been able to for months. Any other ctrl+keystroke doesn't work.

I posted a video in the Facebook Group. Also here it is again.

![2018-10-13-17-06-52](https://user-images.githubusercontent.com/400846/46910984-f539b080-cf1d-11e8-9216-e9067ba19d00.gif)

Please fix it. More importantly, fix Scalar since I paid for it. Or fix the code in VCV Rack.
Thanks.

**Comment by AndrewBelt** [comment]
So Ctrl isn't working with any key commands at all?

**Comment by Cordoha** [comment]
Ctrl is not working in VCV Rack, no. Though, when I press "delete" to remove a module. It does indeed delete. I've also just rebuilt VCV Rack from Git.

**Comment by AndrewBelt** [comment]
Can you run `showkey` in the terminal and press ctrl to see its keycode?

**Comment by Cordoha** [comment]
Yes. Had to run it with sudo in the terminal emulator.
keycode  29 press
keycode  29 release

**Comment by Cordoha** [comment]
I've also tried both the generic and low-latency kernels yesterday and it's to the same effect.
I mainly use low-latency for JACK. One of the first things I do is use the low-latency kernel.

**Comment by AndrewBelt** [comment]
Not understanding the cause since I'm not familiar with Gnome 3, but glad you resolved it.
