### ISSUE TITLE
Fundamental/Core WAV MonoChannel Recorder

### ISSUE THREAD

**Issue by NotAVerb** [VCVRack/Rack#1124]
From what I can tell there isn't yet a module that allows you to create mono WAV recordings, there's only a few stereo recorders. 
Since a mono recorder would be the simplest recording module I think such a module would at least fit in Fundamental.

Featurewise the module should have CV control over when recording starts and stops, and automatic filename creation that allows for multiple recorders to be writing to the same directory.
Preferably there would also be a (vertical? to use hp efficiently) text input box that would be used in the automatic naming process. You would enter text to name the channel and while recording the files would be named something like this: (name+timestamp+moduleID?)
A window that shows the time elapsed would be nice too.

It strikes me that I don't actually know how bitdepth is handled in VCV Rack and whether or not a WAV recording module would need dithering, or should have audio passed through a dithering module first.

**Comment by NotAVerb** [comment]
While making a new patch today I noticed a new "1 channel recorder" by NYSTHI in my module browser. Thank you NYSTHI.

I'll leave this issue open in case Andrew thinks a mono recorder should be in the default package.

**Comment by AndrewBelt** [comment]
https://github.com/VCVRack/VCV-Recorder
