### ISSUE TITLE
step() function - buffer blocks

### ISSUE THREAD

**Issue by Mariastakh** [VCVRack/Rack#1126]
Hi, I am learning to write DSP code for VCV. Still learning on the DSP front, really happy that things like VCV exist as it motivates me to learn. 

I am used to working inside of an audio loop which buffers audio samples into chunks (512, 1024 etc.) when using Juce for example. 

In the VCV myModule::step() function one sample is output at a time. When doing things that require storing past output values (for example filters, delays) is the correct approach to simply store lots of the individual outputs into an array? Or are there ways of overriding the standard output method so I'm working with buffer blocks rather than individual outputs?

Best, 

Maria

**Comment by AndrewBelt** [comment]
Look at Tides or Clouds to see how this is easily done.

**Comment by modlfo** [comment]
I'm closing this issue since there's nothing else to do in the Rack side.
