### ISSUE TITLE
Ubuntu 18.04 - Rack 0.6.2b Not showing Menu Options

### ISSUE THREAD

**Issue by jmarcopolov** [VCVRack/Rack#1127]
Hello All,

I'm running Ubuntu 18.04 with VCV Rack 0.6.2b and it's not showing any of the menu options. It's all pictured on these screenshots.

![screenshot from 2018-10-26 00-10-01](https://user-images.githubusercontent.com/40305021/47550852-59148f80-d8b5-11e8-8a1b-1aea60a1f036.png)
![screenshot from 2018-10-26 00-10-12](https://user-images.githubusercontent.com/40305021/47550853-59148f80-d8b5-11e8-8855-28d65bc33ddc.png)

**Comment by AndrewBelt** [comment]
How do you launch Rack?

**Comment by jmarcopolov** [comment]
@AndrewBelt 
> How do you launch Rack?

Hello Andrew, I launch from the terminal like this:
`sudo /opt/Rack/Rack`

**Comment by AndrewBelt** [comment]
You need to to launch rack with the current working directory as the resource path. See https://vcvrack.com/manual/Installing.html#running-on-linux
Also, I would not highly not recommend running Rack as root. Now that you've launched it, there are probably a bunch of root-owned files created in your cwd.

**Comment by jmarcopolov** [comment]
@AndrewBelt 
> You need to to launch rack with the current working directory as the resource path. See https://vcvrack.com/manual/Installing.html#running-on-linux
> Also, I would not highly not recommend running Rack as root. Now that you've launched it, there are probably a bunch of root-owned files created in your cwd.

Hello Andrew, I've attempted to open and run VCV Rack as suggested in the Manual but it never ends up opening, and that's before I attempted to do it using the sudo command. When I first used the suggested methods to open VCV Rack, I could see Ubuntu working for a few moments then it stops and nothing happens. It was only after I tried using the sudo command that it finally worked, well partially.

What can I do to get VCV Rack working on my Ubuntu 18.04?

**Comment by MR4Y** [comment]
> @AndrewBelt
> 
> > You need to to launch rack with the current working directory as the resource path. See https://vcvrack.com/manual/Installing.html#running-on-linux
> > Also, I would not highly not recommend running Rack as root. Now that you've launched it, there are probably a bunch of root-owned files created in your cwd.
> 
> Hello Andrew, I've attempted to open and run VCV Rack as suggested in the Manual but it never ends up opening, and that's before I attempted to do it using the sudo command. When I first used the suggested methods to open VCV Rack, I could see Ubuntu working for a few moments then it stops and nothing happens. It was only after I tried using the sudo command that it finally worked, well partially.
> 
> What can I do to get VCV Rack working on my Ubuntu 18.04?

If you can find the launcher's *.desktop file (usually in `/usr/share/applications`) add this line to it

> Path=/opt/Rack

It will tell Rack which working directory it should use.

**Comment by N8NYE** [comment]
Deleting the .rack folder and then the Rack folder, then re-extracting everything happened to fix it for me.  Looks like a problem with plugins.  As soon as you import them it breaks.  Try removing them from your account and adding the ones you use one at a time until you figure out which one is causing the issue.

**Comment by N8NYE** [comment]
This could also be an issue with your path.  This command will help you

export PATH= $PATH:/where/you/stored/Rack

from there you can just CD into the RACK directory and run Rack.  This also fixed it for me.

**Comment by pfelwor** [comment]
changing into installation folder and then executing ./Rack in there also fixed the issue for me - thanks a lot

**Comment by AndrewBelt** [comment]
Since Rack v1 or maybe some earlier version, a dialog appears in Rack cannot find its resource directory.

See https://vcvrack.com/manual/Installing.html#running-rack for properly running Rack.
