### ISSUE TITLE
MIDI Smoothing and Its Effect on how MIDI Buttons Activate 

### ISSUE THREAD

**Issue by jonheal** [VCVRack/Rack#1129]

**Comment by AndrewBelt** [comment]
You forgot a description in this issue...

**Comment by AndrewBelt** [comment]
Bontric's smoothing was replaced with simple exponential smoothing. I could probably just use the logic "if the MIDI CC value goes from 0 to 127 or vise versa, just set the value directly."

**Comment by jonheal** [comment]
That sounds like that might do the trick.

--
Jon Heal
IT Specialist, Information Services Division - Business Solutions Management Branch
United States Department of Agriculture | Foreign Agricultural Service | Office of the Chief Operating Officer
202-720-5728 (Desk)
202-256-9637 (Cell)
Have a nice day!

**Comment by SpawnedHuman** [comment]
How about letting the user also deactivate smoothing for custom envelopes, lfos and stepped modulation thru a DAW? I don't know if it's the smoothing or Ableton but I can't get those nice sounding shapes like I do in Zebra with the MSEGs.

**Comment by Rcomian** [comment]
As seen in practice, the exponential filter prevents the built in schmitt trigger from resetting for quite a long time, maybe a second. It's very confusing because the value is so close to zero, all normal debugging just shows the CV value being zero. But the schmitt knows and doesn't reset. (I traced values out of the schmitt trigger to diagnose this).

**Comment by mdemanett** [comment]
I got issue on my plugin related to this: https://github.com/bogaudio/BogaudioModules/issues/34
Mentioning it as another example in case it's helpful.

My first thought was, I could rescale my input to SchmittTrigger, or something like that, such that the effective off threshold is 0.1V or 0.0001V or whatever, but more than zero.  Anyone know a downside to that?

**Comment by AndrewBelt** [comment]
@mdemanett The [standard](https://vcvrack.com/manual/VoltageStandards.html#triggers-and-gates) says to use 0.1V.

**Comment by Rcomian** [comment]
out of interest, did it always say that?

**Comment by AndrewBelt** [comment]
It changed probably last summer after realizing that ADCs coming from real Eurorack triggers had a 50% change of never actually going below 0V when LOW.

**Comment by AndrewBelt** [comment]
Fixed in f2ff949 but untested because I don't have a MIDI controller with buttons with me at the moment.
