### ISSUE TITLE
Reorganize paths on each platform

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/Rack#113]
Rack external files can be categorized into three groups. They should be separated depending on whether they are mutable.

### global (read-only): e.g. res/ComponentLibrary, res/DejaVuSans.ttf, plugins/Fundamental
- Mac: .app bundle /Contents/Resources directory, or ./ if not in bundle
- Windows: ./
- Linux: ./

### user (read/write): e.g. settings.json, autosave.vcv, plugins/*
- Mac: ~/Library/Application Support/Rack
- Windows: ???
- Linux: ~/.Rack

### plugin: e.g. plugin.{dylib,dll,so}
- Mac/Windows/Linux: wherever the plugin was loaded, path stored in Plugin class

Plugins can be stored in either <global>/plugins or <user>/plugins.

**Comment by sbcook0** [comment]
On windows consider using 
~/Documents/Rack if these are intended to be seen by the user (such as presets)
or 
~/AppData/Roaming/Rack for hidden files used by the application (usually settings and run time info).

**Comment by AndrewBelt** [comment]
Fixed by 47dc70721424d2fd4f7e1f67bfbe98a346d7f223. Needs some testing though. Currently Mac has `~/Documents/Rack` hard-coded as its "local" directory for external plugins and autosave/settings files. This might be a hassle for testing from source on Mac, so I need to way to determine in C++ whether the program is being run from an app bundle or not. Any Objective-C gurus that can direct me to the Apple function?

**Comment by AndrewBelt** [comment]
074653f4395bb7831069ca7437849d80ee88a15a solves this last problem.
