### ISSUE TITLE
VCV Rack on the MOD Duo?

### ISSUE THREAD

**Issue by unfa** [VCVRack/Rack#1130]
Could it be possible to run VCV Rack on a MOD Duo?

I imagine one could create a patch on a PC, and then transfer it to MOD Duo, mapping controls and inputs (audio and MIDI) inputs to hardware for performance.

What do you think of this?

**Comment by modlfo** [comment]
I think that making a complete port of Rack that runs on the MOD Duo is difficult. Rack needs a computer with a powerful processor. I don't know what's inside the MOD Duo but I doubt is an Intel (or AMD). 

I'm gonna close this issue since right now it seems not feasible.
