### ISSUE TITLE
use up down arrows for fine grain control of module parameters

### ISSUE THREAD

**Issue by wandersound** [VCVRack/Rack#1133]
# Feature Request
using keyboard UP & DOWN buttons for fine grained adjustment of module parameters.
Not sure of this has been covered as a request.

**Comment by robinparmar** [comment]
+1

^ if that is indeed a thing to say here

**Comment by AndrewBelt** [comment]
You can hold Ctrl (Cmd on Mac) to decrease the mouse sensitivity when dragging knobs.

**Comment by Coirt** [comment]
`speed = 1.0;` in componets.hpp for finer adjustments `speed = 0.5` or `speed = 0.1;`

This feature rocks! Thanks Andrew!

Can the ctrl press have an override in components.hpp? Using a very fine speed `0.1` though when control is pressed it is too fine as it scales. was thinking.

```
if (ctrlPressed==true){
speed = 0.08;
}
```

**Comment by AndrewBelt** [comment]
Closing this feature request since Up and Down arrows are already used for scrolling the rack.

@Coirt You're asking to change the speed multipler when Ctrl is held?

**Comment by AndrewBelt** [comment]
What about setting the overall speed to a higher value? Users expect Ctrl to slow down the knob by a fixed value, so it would be weird to make this configurable.

Ctrl for 1/16 speed, Ctrl+Shift for 1/256 speed.

**Comment by Coirt** [comment]
Will have another look into a speed that might work better or in the sweet spot thanks for the info! Dealing with values to 7 decimal places.

**Comment by AndrewBelt** [comment]
@Coirt Perhaps just assume that users will take advance of the value entry field in the context menu of Rack v1?

**Comment by Coirt** [comment]
Yes, definitely something I have considered also. Thanks again!
