### ISSUE TITLE
Module deprecation

### ISSUE THREAD

**Issue by jhoar** [VCVRack/Rack#1138]
Objective: allow module developers/long term module maintainers to remove modules from usage without breaking existing patches.

- A deprecated module should not appear in the Module Browser, nor contribute to the population of author or tag menus
- A deprecated module can still appear in a patch and be duplicated
- Add an option for developer mode to ignore module deprecation(?)

Hacking .vcv files can't really be prevented so is done at the user's own risk.

Alternatives:
- Do nothing. Unmaintained modules may fall behind API changes. Patches break, possibly irreparably.
- Module authors just delete the module. Patches break, possibly irreparably.

**Comment by mdemanett** [comment]
+1

It'd be a handy way to revise a module without breaking patches -- make a new one and deprecate the old.

**Comment by AndrewBelt** [comment]
Users would then ask for a way to create instances of the deprecated module, so it's best we just show everything.
