### ISSUE TITLE
Opening Rack from remote desktop

### ISSUE THREAD

**Issue by LOGUNIVPM** [VCVRack/Rack#1139]
As far as I see, Rack cannot run from a remote desktop or a team Viewer session.
Are there any workaround to this? 

My use case: i teach using a Linux laptop but i want to run Cubase + Rack from a Windows machine that is in another room of our reharsing facility that sends audio in the teaching room.

**Comment by leopard86** [comment]
RCJacH you are right, VNC leaves the graphic card to handle openGL and just sends the graphic rendering via the network, so VNC works. To solve your issue with the knobs a value must be changed in the settings.json file:
"allowCursorLock": false

This enables you to turn the knob.
All in all, VNC seems to be inferior in terms of performances (I'm using tightVNC on the remote and remmina on the client side), but it does the job.

**Comment by AndrewBelt** [comment]
Set `"allowCursorLock"` to false in settings.json.
Added a menu item in 419e467

**Comment by FrankBuss** [comment]
Thanks, this works!
