### ISSUE TITLE
VCV Host: LV2, LADSPA Support & other things

### ISSUE THREAD

**Issue by Cordoha** [VCVRack/Rack#1144]
In Linux, Ubuntu 18.04:

In anyway, could there be support for LV2, LADSPA plugins for VCV Host?

ZynAddSubFX - The new version: When trying to use the synth, the UI doesn't work. It's just a blank window then Rack  goes into a blank, then it'll crashes. I believe my source is from KXStudio.
Carlarack - I tried loading LV2 plugins through the host, but I failed at getting any results. Not 100% sure if it'll work still. 

Overall, awesome job! Just wish there were more Linux VSTs. This is why I ask for LV2 support. :)
Cheers

**Comment by AndrewBelt** [comment]
Could you email contact@vcvrack.com for VCV Host support?
