### ISSUE TITLE
Aftertouch on Core MIDI-1 module does not function

### ISSUE THREAD

**Issue by Worldsday** [VCVRack/Rack#1145]
Operating system: Linux Mint 18.1 (4.4.0-139-lowlatency x86_64)
Version of Rack: 0.6.2b

Hello! Longtime user, first-time bug reporter here.

I have several midi controllers which work very well with the core MIDI-1 module in Rack. All the keys and mod/pitch wheels work just as expected. The other MIDI modules (e.g. MIDI-CC, MIDI-4) work just fine as well. 

However, the Aftertouch (AT) output in MIDI-1 seems to be completely dead. It does not respond to aftertouch on any of my controllers no matter how I route them. I have verified with amidi and Gmidimonitor that my system is indeed receiving aftertouch data but it just isn't coming through in the Rack module.

Has anyone tested AT in a while? Could it be possible that this feature is broken?

**Comment by AndrewBelt** [comment]
Are your controllers generating polyphonic pressure/aftertouch or channel pressure/aftertouch?

**Comment by Worldsday** [comment]
Thanks for the responses! Aftertouch does not function for me on MIDI-4 either.
I confess I'm not sure whether the aftertouch signal on my controller is poly or channel. It's a Novation X-Station 25. I believe it is channel aftertouch, if I had to guess.

**Comment by MarcBoule** [comment]
Your guess seems to be right :-)

> The keyboard is transposable up or down across the entire MIDI note range and can transmit Channel Aftertouch.

https://encyclotronic.com/synthesizers/novation/x-station-25-r211/

**Comment by Worldsday** [comment]
Thank you, Marc! It seems that the core MIDI inputs just don't support channel aftertouch. I think that should be fixed, at least for MIDI-1. Is it really as simple as changing a single byte in the code?

**Comment by MarcBoule** [comment]
> Is it really as simple as changing a single byte in the code?

It could very well be, unless there are other implications we are not seeing. 
It is up to Andrew though to decide if/how to proceed with any changes. Cheers!

**Comment by doczelig** [comment]
Operating system: MacOS 10.11
Version of Rack: 0.6.2b

Hi folks! 
Same issue for me too, with an M-Audio correctly transmitting Channel Pressure.
No aftertouch present in Core>MIDI-1 and MIDI-4, while, for instance, it’s correctly managed in a third-party module like “MIDI to Dual CV” from moDllz.
I’m sure that in previous Core modules version it was functioning well, as I used it pretty much!

**Comment by MarcBoule** [comment]
This issue looks like it has just been fixed for Rack 1.0 in commit 42cbb51.

**Comment by AndrewBelt** [comment]
@MarcBoule Thanks, closing.
