### ISSUE TITLE
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)

### ISSUE THREAD

**Issue by Barbouze** [VCVRack/Rack#115]
OS (if applicable): Linux Mint 18.2 x64
Version (or "dev" if compiling from source):dev

Hi!

I had VCVRack working a few days ago, except MIDI input which now seems to be fixed with #111 , and wanted to give it a try. After compiling as per the readme Instructions, I get this error:
make run
LD_LIBRARY_PATH=dep/lib ./Rack
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  155 (NV-GLX)
  Minor opcode of failed request:  4 ()
  Resource id in failed request:  0x5600008
  Serial number of failed request:  142
  Current serial number in output stream:  142
Makefile:47 : la recette pour la cible « run » a échouée
make: *** [run] Erreur 1

How can I help you fix this?

**Comment by AndrewBelt** [comment]
Looks like a generic graphics driver issue, but I could be wrong. If you use Mesa, does `glxgears` work, or any other OpenGL application?

**Comment by Barbouze** [comment]
Good catch, seems that my NVidia driver was messed up
