### ISSUE TITLE
VST Host Module Tempo Clock Drift

### ISSUE THREAD

**Issue by sanderbaan** [VCVRack/Rack#1150]
I get a lot of drift when using the Tempo Clock inputs on the VST host module or VST host-fx module. It does not really matter which clock speed I select it always drifts -3 bpm to +3 bpm.

Operating system(s):
Rack 0.6c on OSX 10.14

**Comment by AndrewBelt** [comment]
Can't reproduce. Perhaps I'm not sure what you mean by "drift".

Closing since this isn't an issue about Rack. See the "VST support" section of https://vcvrack.com/Host.html for reporting Host issues.
