### ISSUE TITLE
Make still fails on Linux

### ISSUE THREAD

**Issue by 01ivier** [VCVRack/Rack#116]
Building dependencies is OK, but if I try to build the rack I got : 

```
~/Rack$ make
g++ -Iinclude -Idep/include -Idep/lib/libzip/include -DVERSION=dev -MMD -O3 -march=core2 
-ffast-math -g -Wall -DARCH_LIN -std=c++11 -c -o build/src/engine.cpp.o src/engine.cpp
In file included from src/engine.cpp:10:0:
include/engine.hpp:4:21: fatal error: jansson.h: Aucun fichier ou dossier de ce type
compilation terminated.
compile.mk:50 : la recette pour la cible « build/src/engine.cpp.o » a échouée
make: *** [build/src/engine.cpp.o] Erreur 1
```

I've seen the issue #7 but I couldn't say if it's the same. And, well, it fails despite the fix.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

**Comment by trebmuh** [comment]
It seems you're missing the "libjansson-dev" package which provides the jansson.h file. Try to install it.

**Comment by AndrewBelt** [comment]
You don't need to install your operating system's version. Just `make` in the `dep/` directory and make sure it compiles successfully. Delete the jansson folder to restart that build.

**Comment by trebmuh** [comment]
sorry

**Comment by AndrewBelt** [comment]
Going to close this. Feel free to open if there's still an issue.
