### ISSUE TITLE
Plugins with Custom Interaction (Mouse and Visuals)? 

### ISSUE THREAD

**Issue by interstar** [VCVRack/Rack#1163]
I have a couple of virtual instruments I've been developing in Processing, that I'd like to port to VCV Modules.

These have specific custom interactions (how mouse events are interpreted and what is drawn)

Is there a way to do this with the VCV API? For example, is it possible to create a "canvas" like component, capture mouseEvents from it and draw to it? (I'm happy to "draw" by creating custom SVG)

If so, can you point me to any examples showing how to do this?

**Comment by interstar** [comment]
Also I guess, can a plugin add a custom widget? Or are widgets only defined in the main codebase?

**Comment by interstar** [comment]
Thanks. That's useful.

Just to double-check, nanovg is this? https://github.com/memononen/nanovg 

That's the rendering engine you use for VCV?

**Comment by AndrewBelt** [comment]
Yes, the entire API is in the file nanovg.h

**Comment by interstar** [comment]
Cool
