### ISSUE TITLE
Feature Request: "replace with ..." in module right click popup

### ISSUE THREAD

**Issue by smok-e** [VCVRack/Rack#1166]
I would like to have this item "replace module..." in the right click popup menue of the modules, 
so that it would open the modulebrowser, for me it would really enhence my workflow.
Then you wouldn't need to delete the module first and then open the browser to choose a new module.
the old module should be deleted and the browser opened in one step.
for me it would be very handy.

**Comment by AndrewBelt** [comment]
Hitting Delete and right clicking is the same number of actions as right clicking and clicking Replace, so this wouldn't enhance anything.

**Comment by smok-e** [comment]
I think you didn't understand me right, for me it is really a big difference, I never focus on my keyboard when I use VCV, but use only my mouse,
so I need to first have a look at my keyboard, where the delete key is, and then I need to hit it, and then take again my mouse and make a right click. 
So this takes much longer ´than just a right click (for the meune) and then a left click for the "replace..." 

I hope you will consider it as a possibility.

**Comment by AndrewBelt** [comment]
Would be confusing when a module larger than the available space is selected.

**Comment by AndrewBelt** [comment]
Yes, but is clear to the user that the normal behavior of positioning a module will occur when they use the normal method for adding a module. When the "replace" terminology is used, it would be surprising when the module is not replaced at the same position.

**Comment by smok-e** [comment]
I don't think that users are so easy to confuse, maybe just the first time, 
but after one or two uses it will be clear, and it could be named "exchange ..." instead of "replace ..."
that wording doesn't imply the placement  ;-)

**Comment by odahan** [comment]
I think the "replace" function can easily adjust the placement of all modules to the right of the one being replaced. Lines are "infinite" on their right side. If there is room for 10 units and the new module needs 12 units, it seems easy to make a loop adding 2 unit to all modules on the right. It will not confuse the user and will allow to implement a very friendly feature.
And this can be the beginning of a new important feature : being able to make room at any point on a line without drag'droping each module one by one. But that's another story (leading to the complementary feature : collapsing existing space between modules).
