### ISSUE TITLE
Pick more than one module at a time (to move, delete, duplicate, etc.)

### ISSUE THREAD

**Issue by gnapier3** [VCVRack/Rack#1167]
It would be helpful to be able to select more than one module to move at a time, perhaps by holding the shift key as you click on modules. Once all desired modules are selected, you can move them as a group. Would work very well in combination with FR #307 Multiselect Mode.

**Comment by gnapier3** [comment]
Got it. Then FR 307 would be extremely helpful if selection isn't a concept here.

**Comment by FrankBuss** [comment]
I implemented such a feature already half a year ago, at least shifting more than one module at a time. Andrew has just to merge it in his version:
https://github.com/VCVRack/Rack/pull/1066
