### ISSUE TITLE
weird cpu meter behavior, shows over 1000ms

### ISSUE THREAD

**Issue by smok-e** [VCVRack/Rack#1169]
I have a patch that shows really weird ms meters,  using VCV 0.6.2c

I'm on win 10 home 64 bit,
laptop with Intel Celeron N2940 1.83ghz 4 cores,
4gb ram,
Realtech High Definition Audio,
Intel HD Graphics,
using the onboard soundcard with WASAPI driver

the Audio-plugin ms meter shows over 1000ms and the other used plugins add up to over 2000 ms

the internal processing of VCV is at 192000 Hz

I did the patch to try some visual processing in the JW fullscope, 
so the sounds are not important, but I have no crackles like normally when you have a system overload.

I add the patch here:

[ms-meter-bug-patch.zip](https://github.com/VCVRack/Rack/files/2728656/ms-meter-bug-patch.zip)

**Comment by AndrewBelt** [comment]
I think you mean us, not ms.

Around Rack v1, VCV Audio-* no longer includes time spent waiting for the audio device each block.
