### ISSUE TITLE
VCV Rack Bounces on the dock then just stops and nothing happens

### ISSUE THREAD

**Issue by arlomcwalter11** [VCVRack/Rack#1170]
I am running mac os x 10.14.2 on a 13" 2017 MBP.
- 2.3 GHz Intel Core i5
- 8 GB 2133 MHz LPDDR3
- 128GB SSD

Rack has worked perfectly for me before but I went to open it this morning and it just wouldn't?

Any ideas?

**Comment by deladriere** [comment]
almost the same here,  not bouncing but no windows - nothing
10.14.2 on MacBook Pro (13-inch, 2017)
3,1 GHz Intel Core i5
8 Go 2133 MHz LPDDR3

**Comment by arlomcwalter11** [comment]
I've tried reinstalling, deleting folders associated with the application but nothing changes and I have no idea why?

**Comment by AndrewBelt** [comment]
I haven't tested on MacOS >=10.13, so I'll be sure to do this for Rack 1.0.

**Comment by arlomcwalter11** [comment]
I just tried a different method, When installing it I opened the rack dmg and didn't drag the application to applications folder just to desktop and it works perfectly with no bug or anything. Hope this helps

**Comment by deladriere** [comment]
@arlomcwalter11  I tried but it doesn't work for me. My only option is force quit. nothing else

**Comment by nay-seven** [comment]
Hello, for several applications and new Mac OS, i generally succeed with drag the app on desktop, then right click /open.

**Comment by deladriere** [comment]
thanks @nay-seven but this doesn't work for me either

**Comment by arlomcwalter11** [comment]
Have you tried opening it directly from the dmg without dragging it anywhere?

**Comment by deladriere** [comment]
Yes I did both : from the dmg or on the desktop

**Comment by arlomcwalter11** [comment]
Sorry I'm really not sure then. I have no idea how or why mine magically started working again but Im very pleased it did

**Comment by AndrewBelt** [comment]
Closing as possibly obsolete
