### ISSUE TITLE
1.0 tooltip control could be more general

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#1171]
The new tooltip API does let some plugins display informative information. But it seems to be limited to continuous linear or exponential functions to map from knob position to value. There are many types of parameters that don't fit this model so well.

For example, the pitch of EvenVCO (or many Squinky Labs VCOs) does not map this way, as the pitch is combination of the octave and tuning controls.

Boolean switches don't work so welleither - a switch to switch from hard sync to soft sync can only display 1.0 or 0.0.

Audio-taper controls, like many in Squinky Labs plugins, are exponential at the top 3/4 of their travel, and linear below that.

stepped selector switches with multiple discrete values don't map so well either.

As an option it would be nice if the plugin could provide a  std::function<std::string()> to the parameter for custom formatting.

**Comment by AndrewBelt** [comment]
I don't like `std::function`, but we can use inheritance, although there currently isn't a way to use your own `ParamQuantity` subclass. I'm not sure where that could go.

>Boolean switches don't work so welleither - a switch to switch from hard sync to soft sync can only display 1.0 or 0.0.

How could value entry work in this case?

>Audio-taper controls, like many in Squinky Labs plugins, are exponential at the top 3/4 of their travel, and linear below that.

Users would be fine with just the unitless position of the knob in this case. Computing the "resistance" from the value and vise versa is too complicated and unnecessary.

**Comment by squinkylabs** [comment]
All good points. that's why you make the big bucks ;-) I still feel there might be compelling use cases, but I'm less sure now. Maybe it would be ok to show custom values for some things even if you couldn't type them in? Who's going to type in "3" to select the full wave rectifier shape in Shaper anyway, right?

**Comment by AndrewBelt** [comment]
Added the ability to define your own `ParamQuantity` subclass and give it to a `ParamInfo` with `paramInfos[...].config<MyParamQuantity>(...)` in 444d894.
