### ISSUE TITLE
allow compilation in MS VS compiler in v1

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#1173]
In v6 I am able to compile my plugin unit test suite in Visual Studio. Of course I use gcc for the real plugins.

I can't make this work any more with v1. MSVC barf when it hits the gcc-style ((deprecated)).

Would it be possible to allow this to be overriden? In common.hpp maybe:
```c++
#ifndef DEPRECATED
#define DEPRECATED __attribute__ ((deprecated))
#endif
```

For some reason I never ran into the deprecation issues before - I think the new structure of the Rack headers has ended my run of good luck.

**Comment by squinkylabs** [comment]
strangely enough, it seems like c++14 is the standard for MS, so I expect [[deprecated]] works for them.

**Comment by AndrewBelt** [comment]
Try efce654

**Comment by squinkylabs** [comment]
It appears to work fine. I ran into my own idiocies in porting that I'm just getting sorted out. I'll report back when it actually works, but I'm pretty sure the change in that SHA did the trick.

**Comment by squinkylabs** [comment]
Yes, it's fine, all working now. Pro tip: don't do this with MS compiler:
```c++
#define _V1
#include <random>
```

**Comment by AndrewBelt** [comment]
What?

**Comment by squinkylabs** [comment]
Oh, I meant your change worked fine, but at the same time I was bitten by my poor choice of #define _V1 in my own make file to switch between 0.6 API and 1.0 API. Microsoft's implementation of <random> uses variables called _V1 and _v2, so I had to change my define to __V1.

**Comment by modlfo** [comment]
The issue seems to be fixed. Closing now.
