### ISSUE TITLE
MIDI CC values not serialized

### ISSUE THREAD

**Issue by dschiller** [VCVRack/Rack#1174]
Hi all,

there is an Issue with saved MIDI CC vcv Files. I create my Rack and add a MIDI CC. Setup my Controler, connect all the Wires from MIDI CC to my Rack. Use my Controler to set a nice Sound. Save the Sound. Now the Issue: When I reload the Patch the Sound is completely different. It is not even close to the Settings I had. It has something todo with the MIDI CC Module because the Lights from the outgoing Wires are off means it seams the last Controller Settings seems not to be saved. The COntroller Mapping is still active only the Values seems to be missed which makes an enourmous impact to the Sound. Is there a way to fix that ? Otherwise using MIDI CC and findig Sounds and Saving oesnt make any Sense.

Operating system(s): Windows 10 Pro 1809
Rack Version 0.6.2b
MOTU Ultralite MK3
Geforce 670MX
Maschinewerks CSX 51

**Comment by AndrewBelt** [comment]
Are you saying that when restarting Rack, the MIDI-CC outputs are 0V until the hardware MIDI controller's knobs are touched (moved slightly)?

**Comment by dschiller** [comment]
Exact. Now I understand why this seems to be a kind of problematic but maybe it's possible to save the Voltages for each CC on the Module.

**Comment by AndrewBelt** [comment]
Fixed in 043db34

**Comment by dschiller** [comment]
Amazing! Thank's Andrew!

**Comment by dschiller** [comment]
Wehn will it be available ?

**Comment by AndrewBelt** [comment]
Now if you want to compile the v1 branch, or whenever Rack 1.0 releases if you want the binary.

**Comment by dschiller** [comment]
How can I get al lthe Plugins into v1 ? Maybe it's impossible because I tried to add Fundamental and there are Issues with cloning the submodules.

**Comment by AndrewBelt** [comment]
This is off topic for this issue, which has been resolved. Use the communities for general questions about Rack.
