### ISSUE TITLE
Append modules from saved files

### ISSUE THREAD

**Issue by infamedavid** [VCVRack/Rack#1176]
hello, here is a feature could be interesting to implement, the ability to add modules from saved files, a simple option to add saved patches to the current patch.  

eg.
I have the file "nice_effect_rack.vcv" saved in my hard drive, and I want t  add to my current song, selecting de option  "Append patch"  the browser is opened to  search and  select the file to be appended.

other way could be save the files in certain location and they will automatically loaded in the rack menu

eg.
I saved the file "nice_effect_rack.vcv" in the rack folder "Documents/Rack/templates"  right click to add modules and the file to be appended appears beside the favorites 

thanks!

**Comment by AndrewBelt** [comment]
Duplicate (actually subset) of #342
