### ISSUE TITLE
Number of channels Curiosity

### ISSUE THREAD

**Issue by therealkitman** [VCVRack/Rack#1178]
Hi. I'm using opensuse 43.3/kernel 4.4.115 and vcv rack 0.6.2c. Using cadence/jack/claudia/x42-scope
This is not so much a fault but a curio that I can't figure out. My motherboard's audio provide 2 input and 6 output channels.
![image](https://user-images.githubusercontent.com/14888092/51458926-c8552f00-1d91-11e9-814d-3838a4a579be.png)
Yet VCV Rack detects 3 input and 7 output.
![image](https://user-images.githubusercontent.com/14888092/51459056-3ac60f00-1d92-11e9-8a1f-34daf8c2cbdc.png)
I wonder if any of the 7 outputs were 'dud' so I did a little test by sending 1 volt on Output 1, 2 volts on Output 2 and so on to 8 volts on Output 8 (see pic above). using 2 instances of x42-scope and connecting via claudia -
![image](https://user-images.githubusercontent.com/14888092/51459224-c770cd00-1d92-11e9-91ae-2b9d3028150e.png)
-- I do indeed see that there are 7 active and unique channels.
![image](https://user-images.githubusercontent.com/14888092/51459305-0c94ff00-1d93-11e9-9389-6532aa5cd32c.png)
So I am asking how does VCV Rack add an extra input and output than what my sound card has? Also why doess VCV Rack list itself as and audio device with the number of in/outs swapped?
Thanks.

**Comment by AndrewBelt** [comment]
?

**Comment by therealkitman** [comment]
The curse of clicking prematurely :) See edited post above please.

**Comment by infamedavid** [comment]
rcm audio 16 https://github.com/Rcomian/rcm-modules/blob/v0.6/README.md
or perhaps the jack plugging https://community.vcvrack.com/t/jack-as-a-plugin/789

**Comment by therealkitman** [comment]
> rcm audio 16 https://github.com/Rcomian/rcm-modules/blob/v0.6/README.md
> or perhaps the jack plugging https://community.vcvrack.com/t/jack-as-a-plugin/789

Piano Roll?

**Comment by therealkitman** [comment]
My original issue is now null and void in V1 rack. All connections are now what I expect them to be.
