### ISSUE TITLE
Duplicate in direction of module edge

### ISSUE THREAD

**Issue by catronomix** [VCVRack/Rack#1179]
A much repeated activity in Rack is duplicating modules using the keyboard shortcut.
The program tries to put it in the nearest space, which is often virtual miles away :)
It would be very nice if there is a detection of which edge of the module is nearest to the mouse pointer and place the duplicate in the first free space in that direction!

**Comment by AndrewBelt** [comment]
Sounds reasonable. Changed in a77a04a
