### ISSUE TITLE
SVG co-ordinates

### ISSUE THREAD

**Issue by jackokring** [VCVRack/Rack#118]
Inkscape. It makes Path>Object render to path, svg of the right type with no text in, but the co-ordinates are based bottom left, where as the params[x] seem to be specified top left in code. Is this correct?

**Comment by AndrewBelt** [comment]
That is correct. SVG uses mathematical coordinates, but OpenGL, and thus the Rack renderer uses upside down coordinates.

**Comment by AndrewBelt** [comment]
Maybe WAY in the future I'll add a panel designer function to Rack to make this easier. But it's only a couple minutes to make a panel so it'll probably be around priority #10000.
