### ISSUE TITLE
Few suggestions regarding Plugin creation and UI design

### ISSUE THREAD

**Issue by KoreTeknology** [VCVRack/Rack#1183]
Hi,
i would like to share my observations and see if and how i can contribute...

1/ Plugin Creation
It would be very nice to have a devtool, dedicated to VCV, to create, compile and publish new modules. I am thinking of an UI to help new developers and standardize the process of making VCV plugins.
I suggest an integrated panel, not an other app !, something that let you test your new module directly in Rack. also, it would be great to have the publishing system or similar functions also inside this tool.

2/ UI Design, few observations...
- the header toolbar, love it, discreet, simple, effective... keep it this way, please :) it needs a couple of menus, like preferences or settings.. what do you think ?

- the patch browser, it is something that would be very usefull to load patch during live performance !
i recommand an integrated panel again....

- the midi controller system, (as a Nord Modular user, i like to right-click on a button, a slider or any UI control to perform Midi assign)... the feature is to provide a simple way to assign a virtual controller to a midi controller device (hardware), very useful for live performance and studio setup !

- the module browser is a bit confusing, when you have a lot of plugins installed... i suggest here that modules would have a category and we must find a filter somewhere in the browser panel. ( by the way, the favorites feature is awesome!)
and the best, would be to have a preview image on the side of the plugin name ;) 

ok,  i have various options to support one of this development, let me know if someone want to collaborate on these projects... have a nice day

**Comment by AndrewBelt** [comment]
Hi @KoreTeknology, please don't combine multiple features requests into an issue. I'm going to close this because it's unmanageable in its current form, but feel free to repost them after searching for duplicates (since many of these are).
