### ISSUE TITLE
Component low scale

### ISSUE THREAD

**Issue by regfaker** [VCVRack/Rack#1184]
Components scale is low and thus layout is bad. Zoom 100%.
Picture will sayl it better 
![rack_bad_scale](https://user-images.githubusercontent.com/1756775/51706606-4712cc00-201f-11e9-800f-7254b9fbbf29.jpg)

This behaviour is same for all components.
Is there some dependency or OS setting which I can tweak to fix this.
Thank you for such software.

Operating system(s):
Rack-0.6.2c-lin binary
Debian buster, kernel 4.19.0-1-amd64
Haswell-ULT Integrated Graphics Controller

**Comment by AndrewBelt** [comment]
Duplicate of https://github.com/VCVRack/Rack/issues/461
