### ISSUE TITLE
Feature request – Contextual help

### ISSUE THREAD

**Issue by diimdeep** [VCVRack/Rack#1185]
Variants

- Context menu on hover
- Separate panel on focused element
- Separate window by user request

![reaktor](https://user-images.githubusercontent.com/485713/51790459-aa7b3600-21a6-11e9-92a5-5356f13d4fc5.png)
<img width="1280" alt="pd automatonism" src="https://user-images.githubusercontent.com/485713/51790460-aa7b3600-21a6-11e9-9068-f15c69074472.png">

**Comment by AndrewBelt** [comment]
An entry to the Module Browser and likely the module right-click context menu will be added to Rack v1 which opens the browser with the `"manualUrl"` specified in `plugin.json` of the plugin folder.
