### ISSUE TITLE
Rack v1 hangs and no sound out

### ISSUE THREAD

**Issue by alfonso73** [VCVRack/Rack#1187]
Hi,
just compiled the v1 version.
I have no sound in Win10 64bit through ASIO driver (Presonus Quantum).
If i try to change device in the audio module or to change buffer size Rack v1 hangs.
BTW no problems with Rack 0.6.2c

thanks

**Comment by modlfo** [comment]
@alfonso73 Do this problem persists with a more recent version? if not please close the issue.
