### ISSUE TITLE
Error 2 , make dep, http problem ?

### ISSUE THREAD

**Issue by KoreTeknology** [VCVRack/Rack#1188]
Hi, i couldn t fix this issue when building, here is the output:

WIN10PRO@User1 MINGW64 ~/Rack
$ make dep -j4
make -C dep
make[1]: se entra en el directorio '/home/WIN10PRO/Rack/dep'
wget -c "https://vcvrack.com/downloads/dep/speexdsp-SpeexDSP-1.2rc3.tgz"
--2019-02-02 10:41:04--  https://vcvrack.com/downloads/dep/speexdsp-SpeexDSP-1.2rc3.tgz
Resolviendo vcvrack.com (vcvrack.com)... 168.235.102.117
Conectando con vcvrack.com (vcvrack.com)[168.235.102.117]:443... conectado.
Petición HTTP enviada, esperando respuesta... 416 Requested Range Not Satisfiable

    El fichero ya ha sido totalmente recuperado, no hay nada que hacer.

tar xf speexdsp-SpeexDSP-1.2rc3.tgz
speexdsp-SpeexDSP-1.2rc3/symbian/bld.inf: Can't create '\\\\?\\C:\\msys64\\home\\WIN10PRO\\Rack\\dep\\speexdsp-SpeexDSP-1.2rc3\\symbian\\bld.inf'
tar.exe: Error exit delayed from previous errors.
make[1]: *** [Makefile:83: lib/libspeexdsp.a] Error 1
make[1]: se sale del directorio '/home/WIN10PRO/Rack/dep'
make: *** [Makefile:58: dep] Error 2

everything was ok until now , thanks

ICore i7-7700, 8 Core 32ram

**Comment by AndrewBelt** [comment]
Make sure no programs are holding a file handle to that bld.inf file. To make sure, remove the speex folder and archive and rerun make.

**Comment by KoreTeknology** [comment]
i am sorry to say, that i did, :(  i did follow that page obviously... 
can it be an access right problem ? i mean, i use msys2, it should have been setting up the folders for me, right ? i explore all the possibilities

**Comment by AndrewBelt** [comment]
Are there any files in `dep/rtaudio`? Did `make dep` complete successfully?

**Comment by KoreTeknology** [comment]
i restart from scratch... and i saw something, when i do git submodule update --init --recursive

$ git submodule update --init --recursive
': no es un identificador válido8: export: `dashless
Submódulo 'dep/glfw' (https://github.com/glfw/glfw.git) registrado para ruta 'dep/glfw'
Submódulo 'ext/nanosvg' (https://github.com/memononen/nanosvg.git) registrado para ruta 'dep/nanosvg'
Submódulo 'ext/nanovg' (https://github.com/memononen/nanovg.git) registrado para ruta 'dep/nanovg'
...
and more "no es un identificador válido8: " follow this...

**Comment by AndrewBelt** [comment]
That's fine, you can ignore those warnings.

When pasting terminal output, surround the code with "```". See #730

**Comment by KoreTeknology** [comment]
next step.. i did re-install everything again... and i found that during installion of Msys2, it needs to add the "pacman -Su" command tu complete the update, see here:
[https://www.msys2.org/](url)

well, i did the process again for Rack..and make dep ran for a long time (good sign) until it stop on this:
```
...
checking size of int... 4
checking size of long... 4
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libspeexdsp/Makefile
config.status: creating doc/Makefile
config.status: creating SpeexDSP.spec
config.status: creating include/Makefile
config.status: creating include/speex/Makefile
config.status: creating speexdsp.pc
config.status: creating win32/Makefile
config.status: creating win32/libspeexdsp/Makefile
config.status: creating symbian/Makefile
config.status: creating win32/VS2003/Makefile
config.status: creating win32/VS2003/libspeexdsp/Makefile
config.status: creating win32/VS2003/tests/Makefile
config.status: creating win32/VS2005/Makefile
config.status: creating win32/VS2005/libspeexdsp/Makefile
config.status: creating win32/VS2005/tests/Makefile
config.status: creating win32/VS2008/Makefile
config.status: creating win32/VS2008/libspeexdsp/Makefile
config.status: creating win32/VS2008/tests/Makefile
config.status: creating include/speex/speexdsp_config_types.h
config.status: error: cannot find input file: `ti/Makefile.in'
make[1]: *** [Makefile:84: lib/libspeexdsp.a] Error 1
make[1]: se sale del directorio '/home/WIN10PRO/Rack/dep'
make: *** [Makefile:58: dep] Error 2

```

**Comment by AndrewBelt** [comment]
Your files are mysteriously randomly disappearing. Do you have an antivirus program that has control over your computer?

**Comment by KoreTeknology** [comment]
yes.. of course... why ? 
i will try without the antivirus activated... do you think it has something to do with this ?

**Comment by AndrewBelt** [comment]
That is almost certainly the cause. Antivirus programs are designed to prevent you from running your own software on your computer.

**Comment by KoreTeknology** [comment]
ok... that´s it ! :)
first, thanks to AndrewBelt for exploring the error
second, the **antivirus was the problem** as well as the **updated libraries for Msys2** !
maybe it could be added to the documentation ?

thanks a lot ! i am starting building my first module today !
