### ISSUE TITLE
Mac Build fails on Jansson

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/Rack#119]
Sierra 10.12.6

I have tried many times, always followed instructions in readme.md, changed references to /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk 

but make into dep folder always gives me an error about jansson...these are the results...

> wget -nc http://www.digip.org/jansson/releases/jansson-2.10.tar.gz
> --2017-09-20 19:30:42--  http://www.digip.org/jansson/releases/jansson-2.10.tar.gz
> Resolving www.digip.org... 91.232.156.81, 91.232.156.82
> Connecting to www.digip.org|91.232.156.81|:80... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 487855 (476K) [application/x-gzip]
> Saving to: ‘jansson-2.10.tar.gz’
> 
> jansson-2.10.tar.gz 100%[===================>] 476.42K   775KB/s    in 0.6s    
> 
> 2017-09-20 19:30:43 (775 KB/s) - ‘jansson-2.10.tar.gz’ saved [487855/487855]
> 
> tar xf jansson-2.10.tar.gz
> cd jansson-2.10 && ./configure --prefix="/Users/antonio_grazioli/desktop/vcv/rack/dep"
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... ./install-sh -c -d
> checking for gawk... no
> checking for mawk... no
> checking for nawk... no
> checking for awk... awk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking for gcc... gcc
> checking whether the C compiler works... no
> configure: error: in `/Users/antonio_grazioli/desktop/vcv/rack/dep/jansson-2.10':
> configure: error: C compiler cannot create executables
> See `config.log' for more details
> make: *** [jansson-2.10] Error 77

**Comment by AndrewBelt** [comment]
Why does "the C compiler not work"? Can you compile a test file?

**Comment by antoniograzioli** [comment]
other libraries before jansson compile correctly...GLEW, GLFW went fine...
when it comes to Jansson there is this error...

**Comment by antoniograzioli** [comment]
i tried having a look into gcc:
```

iMacdiAGrazioli:dep antonio_grazioli$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by antoniotuzzi** [comment]
do a check to the config.log in Jansson directory

**Comment by antoniograzioli** [comment]
this is what config.log in jansson says:

[http://txt.do/djcvc](http://txt.do/djcvc)

**Comment by antoniotuzzi** [comment]
ok, you are not using the gcc from the APPLE toolchain
you have more than one installed

**Comment by antoniograzioli** [comment]
I tried running gcc -v:

`iMacdiAGrazioli:dep antonio_grazioli$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
iMacdiAGrazioli:dep antonio_grazioli$ `

**Comment by antoniograzioli** [comment]
`iMacdiAGrazioli:rack antonio_grazioli$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
iMacdiAGrazioli:rack antonio_grazioli$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
iMacdiAGrazioli:rack antonio_grazioli$ `

**Comment by AndrewBelt** [comment]
The problem is that you're setting the flags

`-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.7`

for some reason. You've requested MacOS SDK 10.7, but you're telling it that it's located in a directory called MacOSX10.12.sdk.

**Comment by antoniotuzzi** [comment]
I changed my MAKE to point to:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk

(that is always the default pointing to last)

and I was able to recompile everything

**Comment by antoniograzioli** [comment]
I nearly managed to get past the make in /dep

in the meanwhile I updated Xcode and it has been updated to MacOSX10.13.sdk and I started getting errors because I was using 10.12...

there was probably something worng with another path:
(Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Carbon.framework/Versions/A/Headers/)

now I have problems with portmidi:

```

In file included from /Users/antonio_grazioli/desktop/VCV/Rack/dep/portmidi/pm_mac/pmmacosxcm.c:38:
In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20:
In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:35:
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/FixMath.h:123:8: error: 
      unknown type name 'Fixed'

```

**Comment by AndrewBelt** [comment]
Are you wanting to distribute plugins you make for other people?

**Comment by antoniograzioli** [comment]
yes, I was able to compile them on my PC but I have troubles here on my Mac...

**Comment by AndrewBelt** [comment]
Then keep the Makefile the way it is with no environment variables and use SDK 10.7, which you can obtain here. https://github.com/devernay/xcodelegacy

**Comment by antoniograzioli** [comment]
OK I will try to download legacy OSX SDKs. Doing as we speak ...

I think I need them because I am geting an error in configure in portaudio....it looks for SDKs from 10.5 to 10.12 and fails because I now have 10.13 installed...

**Comment by antoniograzioli** [comment]
I followed yor advice and googled a bit. I was able to download Xcode4.x which contains the SDK for iOs 10.7 and 10.8, I manually copied them in /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs

now EVERYTHNG works and I was able to compile even on Mac.
thanks a lot for your inputs @antoniotuzzi and @AndrewBelt

**Comment by AndrewBelt** [comment]
Added better instructions in 35f38f973e49cf29bf7afc53ba4c3954bedb865f for each OS.
