### ISSUE TITLE
Rack v1: Menu names overflow

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#1192]
Rack `v1`, SHA:  10112f0722c13206983c262d39d504f0477594d3
Windows 10, 4K display:

![image](https://user-images.githubusercontent.com/624427/52251703-bf00b200-28bb-11e9-96f3-e273cc981540.png)

Also reported on [Retina Display](https://github.com/VCVRack/Rack/issues/1189#issuecomment-460147308).

**Comment by AndrewBelt** [comment]
Fixed in e623048abe27f0bd2bc8d63bb9e062928000550e
