### ISSUE TITLE
Rack v1: in Notes module, use Arrow keys conflicts with Window movement

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#1194]
OS: Windows 10
Rack: v1, 1f5cec827d953d945ae2e548721bc93e51db5249

Expected behavior: when Notes module is in focus, the Arrow keys can be used to navigate within the Notes module's textual content.

Actual behavior: using the Arrow keys moves the Rack "view port" around. Up and Down are always overridden (or not available in Notes module) and Left and Right move the cursor AND the Rack "view port".

**Comment by AndrewBelt** [comment]
Fixed in aa16adc
