### ISSUE TITLE
Rack v1 crash at the startup on MAC

### ISSUE THREAD

**Issue by antoniotuzzi** [VCVRack/Rack#1195]
Mac OSX 10 13 14
branch v1 commit 42cbb5194a43a57b910e07a9ef81a03d8032fa52

If I have a non built plugin (example ESeries)
an Alert is displayed during launch (make run) ("cannot load plugin bla bla bla"), but the alert is launched from a secondary thread (and BTW is presented on the back of the console): the APP complains about it and crashes (invalid count of running instances)

**Comment by AndrewBelt** [comment]
>the alert is launched from a secondary thread

Plugins are loaded from the main thread, so that dialog should be called from the main thread. How do you know this?

**Comment by antoniotuzzi** [comment]
I'll redo a test and report results

**Comment by antoniotuzzi** [comment]
after the `make run`
I get this output if there are not built plugins (and the alert is displayed

```
[32.973 info src/main.cpp:113] Initialized environment
[32.973 info src/settings.cpp:156] Loading settings ./settings.json
2019-02-07 19:29:55.239 Rack[65382:5589305] *** Assertion failure in -[NSApplication run], /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1561.40.112/AppKit.subproj/NSApplication.m:3827
2019-02-07 19:29:55.248 Rack[65382:5589305] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSApp with wrong _running count'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff443256bb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff6ba54942 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff4432b2a2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff46463340 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   AppKit                              0x00007fff41826748 -[NSApplication run] + 447
	5   Rack                                0x0000000108cb5c9a _glfwPlatformCreateWindow + 74
	6   Rack                                0x0000000108caf271 glfwCreateWindow + 497
	7   Rack                                0x0000000108c63f72 _ZN4rack6WindowC2Ev + 290
	8   Rack                                0x0000000108c3474c _ZN4rack3app3AppC2Ev + 204
	9   Rack                                0x0000000108c348c6 _ZN4rack3app4initEv + 38
	10  Rack                                0x0000000108c5411e main + 654
	11  Rack                                0x0000000108bee034 start + 52
)
libc++abi.dylib: terminating with uncaught exception of type NSException
make: *** [run] Abort trap: 6```

here you can see the alert coming out in BGND
![screen shot 2019-02-07 at 19 29 36](https://user-images.githubusercontent.com/62518/52434201-1a76ae00-2b0f-11e9-8605-9529c8835036.png)

**Comment by antoniotuzzi** [comment]
here you can see the alert coming out in BGND
![screen shot 2019-02-07 at 19 29 36](https://user-images.githubusercontent.com/62518/52434201-1a76ae00-2b0f-11e9-8605-9529c8835036.png)

**Comment by neoh4x0r** [comment]
@antoniotuzzi 
The dialog is executed from the main thread, rack uses **osdialog** to create those pop-up messages.
The reason it appears in the background is because osdialog's messageboxes are not parented to the main application (ie put into the foreground above the main application, often referred to as modal).

**Comment by antoniotuzzi** [comment]
can't repro anymore

**Comment by AndrewBelt** [comment]
Yeah, I think I fixed this in osdialog a while ago.
