### ISSUE TITLE
Rack v1: Modules in module browser just show UI shells, no yellow text

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#1196]
OS: Windows 10
Rack: v1, d7b72c5b0f46b665934c58cc346281e3dec952a6

![image](https://user-images.githubusercontent.com/624427/52454728-14ca9980-2b0a-11e9-908a-076c36756c03.png)

**Comment by AndrewBelt** [comment]
What do you want it to say?

**Comment by cschol** [comment]
Fixed in latest version. Closing.
