### ISSUE TITLE
Segmentation Fault on Rack v1.dev.83ad852

### ISSUE THREAD

**Issue by alfonso73** [VCVRack/Rack#1197]
Hi, i have Segmentation fault on Rack v1.dev.83ad852. Rack quits after a while.
I'm on Win10 64bit.

**Comment by cschol** [comment]
Please either provide a backtrace or a detailed recipe to reproduce. Thank you!

**Comment by modlfo** [comment]
I have had segmentation faults in the v1.dev versions when the dependencies are outdated or the plugins were compiled with a previous version.

I'm closing this issue. If this issue keeps happening feel free to comment and provide more information.
