### ISSUE TITLE
Insert random module

### ISSUE THREAD

**Issue by freddyz** [VCVRack/Rack#1198]
**Feature Name:**
Insert Random Module

**Description:**
When the user opens the module browser, there is a button "Insert random module".  If the user clicks the button, one of the user's installed modules is randomly selected and added to the patch.  If the user has entered a search query in the module browser, clicking "Insert random module" will select and insert one of the modules from the filtered list.

This feature is effectively the same as closing your eyes, scrolling, and clicking a module at random from the module browser.

**Justification:**
- Encourages users to try out the (probably hundreds) of modules they have installed that have never been used

**Comment by thealienthing** [comment]
Sounds neat! Nice idea!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AndrewBelt** [comment]
See https://vcvrack.com/plugins.html#WhatTheRack
