### ISSUE TITLE
Mac 0.3.0 binary from website requires 10.12+ (instead of 10.7+ as stated)

### ISSUE THREAD

**Issue by zproc** [VCVRack/Rack#12]
Everything is in the title...

The Mac 0.3.0 .App from the website requires 10.12+ (instead of 10.7+ as stated), or at least that's what it says on my 10.11.6 system. (Building as mentionned in #6 worked here too.)

(Sorry if GitHub issues isn't the most appropriate place for this, but just in case...)

**Comment by noizehack** [comment]
I had the same issue, I am also on 10.11.6

**Comment by eb0687** [comment]
Same issue here, currently on OSX 10.11.6

**Comment by papernoise** [comment]
Same here, I've got OSX 10.10.5 and v0.3.0 won't run.

**Comment by eb0687** [comment]
re-download and try again from the official site. It works for me now.

Refer to this muffwiggler post:
https://www.muffwiggler.com/forum/viewtopic.php?p=2645995#2645995

**Comment by AndrewBelt** [comment]
I tested my second build attempt on 10.12, 10.10, 10.8, and 10.7, and all work except 10.7. Does anyone else experience this?

**Comment by papernoise** [comment]
It's now working just fine on 10.10
