### ISSUE TITLE
Make fails on MacOS 10.11.6

### ISSUE THREAD

**Issue by killiun** [VCVRack/Rack#120]
OS (if applicable):MacOS 10.11.6
Version (or "dev" if compiling from source):dev

I'm completely new to this but but finally built all dependencies successfully. But when I try to make I 
get this:

$ make
c++ -Iinclude -Idep/include -Idep/lib/libzip/include -DVERSION=dev -MMD -O3 -march=core2 -ffast-math -g -Wall -DARCH_MAC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk -mmacosx-version-min=10.7 -DAPPLE -stdlib=libc++ -std=c++11 -stdlib=libc++ -c -o build/src/app.cpp.o src/app.cpp
In file included from src/app.cpp:1:
include/app.hpp:3:10: fatal error: 'jansson.h' file not found
#include <jansson.h>
         ^
1 error generated.
make: *** [build/src/app.cpp.o] Error 1

**Comment by AndrewBelt** [comment]
`make dep`
