### ISSUE TITLE
Rack-DSK's include/dsp/digital.hpp does not match Rack's same file

### ISSUE THREAD

**Issue by korfuri** [VCVRack/Rack#1208]
Operating system(s): all
Version of Rack if using official binary, or commit hash and branch if compiling from source: 0.6.2
All hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): n/a

The Rack-SDK contains a trimmed version of `include/dsp/digital.hpp`. Several utility classes are missing, namely `BooleanTrigger`, `Timer` and `Counter`. AFAICT these are not meant to be internal-only, since they would be pretty useful to build 3rd party modules. 

Not a huge deal since the logic is trivial to reimplement, but for completeness' sake they would be great to have in the SDK.

Thanks!

**Comment by AndrewBelt** [comment]
Rack v0.6 does not include those classes. They are available beginning in Rack v1.
