### ISSUE TITLE
Rack v1: CV-MIDI Clock, Start, Stop, Continue give parse error

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#1212]
OS: Ubuntu 18.04
Rack: `v1`, 74361d4ce2b43e6eb5c52a6f8c45c804819b271d

Connecting a signal (LFO, Square) to the `CLK`, `STRT`, `STOP`, `CONT` inputs of the `CV-MIDI` module results in the following message in the console

```
MidiOutAlsa::sendMessage: event parsing error!
```

for every cycle of the LFO. MIDI Clock does not work on the receiving device, neither do the other functions.

Looking at the code, it looks like all message Rack sends are 3 bytes in size. Per the [spec ](https://www.midi.org/specifications/item/table-1-summary-of-midi-message), these messages are just 1 byte. 

**UPDATE**: For testing, I changed the code to introduce a `size` parameter in the `sendMessage` function that for `Clock` (or `Start`) gets set to 1 (instead of 3). Now the message does not encounter a parse error anymore and the MIDI messages are sent.

**Comment by AndrewBelt** [comment]
Thanks, fixed in b066025. Let me know if this doesn't solve it.

**Comment by cschol** [comment]
Works. Thank you.
