### ISSUE TITLE
Rack v1: CV-MIDI status bytes of Stop and Continue messages are swapped

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#1213]
Rack: `v1`, 74361d4ce2b43e6eb5c52a6f8c45c804819b271d

Per the spec:
- Continue: `0xfb`
- Stop: `0xfc`

These are swapped in `CV_MIDI.cpp`.

**Comment by AndrewBelt** [comment]
Thanks, fixed in f1a2068.
