### ISSUE TITLE
in /include/math.h: struct Rect, getLeft() should be named getRight() I assume

### ISSUE THREAD

**Issue by ErnstHot** [VCVRack/Rack#1214]
Operating system(s):
  All

Version of Rack if using official binary, or commit hash and branch if compiling from source: 
  Hash: 74361d4ce2b43e6eb5c52a6f8c45c804819b271d
  Branch v1

All hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):
  Not relevant

in /include/math.h: struct Rect, getLeft() should be named getRight() I assume:

```C++
float getLeft() const {
	return pos.x + size.x;
}
```

https://github.com/VCVRack/Rack/blob/8f31adef011500eb92df2bab1d253442221c169a/include/math.hpp#L282

**Comment by AndrewBelt** [comment]
Thanks, fixed in 9c9daed.
