### ISSUE TITLE
Feature request: Replays (record user actions, watch recorded 'replay')

### ISSUE THREAD

**Issue by diimdeep** [VCVRack/Rack#1217]
'Replay' [[1]](https://dota2.gamepedia.com/Replay) or 'Demo' [[2]](https://quake.fandom.com/wiki/Demo) [[3]](https://developer.valvesoftware.com/wiki/Demo_Recording_Tools).  
(from games where player have ability to record demo files of their playthrough)  
It is like 'movie' recored by person interacting with software.  
User would start record and it would save every action made from within software.  
It would allow to 
- save `replay` to a file and share `replay` with others.  
- playback `replay` in `spectator` mode.  
- `Take over` to take control of actions at any time during a `replay`.

**Comment by catronomix** [comment]
Seeing as there's undo and redo in v1, and (for me at least) it works lightning-fast, something like this seems feasible to me. The same underlying system could be used for live collaboration as well if the stream of events is synced over a network! :)

**Comment by glocke01** [comment]
Second this proposal. I was writing up a new issue when I found this.

Infinite undo surely requires an ordered container containing "actions" somewhere in the code. The contents of this container could be serialized/written to a file and then "played back" in reverse order.

I think this could be most sensibly implemented by setting a "Action Recorder" module that saves the current state of the patch and then attaches the undo-log (to which relative time-stamps are added). 

If you limited the possible actions to forbid adding or moving modules or adding cables ("fix the rack and connections") then the output could even be parsed and edited. It would be amazing if this could then be loaded and edited in a separate sequencer. Such a sequencer would obviously be a major undertaking that might possibly work as a "fan" effort.

**Comment by AndrewBelt** [comment]
I'm not interested in adding this feature, closing.
