### ISSUE TITLE
Notes module is black and broken

### ISSUE THREAD

**Issue by zbam** [VCVRack/Rack#1218]
The notes module is not drawn correctly and doesn't work. There is only a black rectangle in the rack that can't be moved, or removed or even right clicked. See attached png for details.

Operating system(s): Linux Ubuntu 18.10,
Processor: Intel® Core™ i5-3210M CPU @ 2.50GHz × 4
Graphics : Intel® Ivybridge Mobile
Version of Rack : 0.2.2c

![image](https://user-images.githubusercontent.com/1504536/53762959-5f4cf500-3ec1-11e9-9964-217cef257c09.png)

**Comment by AndrewBelt** [comment]
Is Notes.svg failing to load in log.txt?

**Comment by zbam** [comment]
Well this is odd, the notes module is back today after a reboot, everything is fine :

[0.105 info src/window.cpp:695] Loaded SVG ./res/Core/Notes.svg
[0.105 info src/window.cpp:695] Loaded SVG ./res/ComponentLibrary/ScrewSilver.svg
[0.105 info src/window.cpp:642] Loaded font ./res/fonts/ShareTechMono-Regular.ttf
