### ISSUE TITLE
Makefile support for shared sources

### ISSUE THREAD

**Issue by modlfo** [VCVRack/Rack#1220]
Hi Andrew, I would like to request for a way of creating plugins that share sources. This is the case:

All Vult modules share sources (code and graphics) for example the graphics of the knobs, the DSP code and other utilities. In my current build system I solve the issues by duplicating the graphics and pointing to sources outside the current directory, for example SOURCES = ../shared/code.cpp.

This has two problems, the build system leaves compiled objects outside the build directory (because of the "../" in the path) and these cannot be cleaned with `make clean`. The second problem is the duplication graphic assets.

It would be more convenient if I could point to a directory with the shared code and the Makefile does the rest.

If you don't have an easy way of doing this, I can still create some scripts that prepare my directories before building.

**Comment by AndrewBelt** [comment]
You could just write a dep target and run `make dep` before compiling.

**Comment by modlfo** [comment]
The solution with the `dep make` is close to what I have right now. It's still not optimal. I also need to generate `plugin.json` files for every package. My needs are very specific so I think they cannot be generalised for everyone.

I think I'll write my own makefile that does all the tasks I need. I just need to pay attention to changes in `plugin.mk`.
