### ISSUE TITLE
Most plugins wont load, and all patches that i have created appear as blank with cords

### ISSUE THREAD

**Issue by johnnycumquest** [VCVRack/Rack#1221]
So when I load a patch I have created it shows up as just patch cords with no modules.  When I am trying to start a new patch most of the modules wont load and if they do they are just balnk slates with no paramater information.  The first is of a new patch and the second is of a patch i had previously created.  This just started happening today, I dont beleive i have updated anything on my computer so i am very confused.
<img width="1280" alt="screen shot 2019-03-08 at 12 51 43 am" src="https://user-images.githubusercontent.com/48345841/54012698-721f2e00-413c-11e9-82fc-c86410806368.png">
<img width="1279" alt="screen shot 2019-03-08 at 12 52 52 am" src="https://user-images.githubusercontent.com/48345841/54012736-8f53fc80-413c-11e9-8918-d3d4502a72b0.png">

**Comment by AndrewBelt** [comment]
When posting issues, please don't delete the form of information you're supposed to fill out. I see 0 information about your system in your post.

Also, post your log.txt from `Documents/Rack/`.

**Comment by johnnycumquest** [comment]
oh I didnt realize that was an information form sorry!  Okay doing this again

**Comment by modlfo** [comment]
Closing this issue since there's no more information. @johnnycumquest I don't know if you created another issue with the missing parts.
