### ISSUE TITLE
stb_image_write prevents compiling

### ISSUE THREAD

**Issue by leopard86** [VCVRack/Rack#1223]
The dependency to <stb_image_write.h> in src/dep.cpp is unsatisfied as of Rack v1.dev.df0c8cf.
I can override this by hardwiring the path of the file manually, but another cleaner solution may be implemented.

System: Linux Mint 18.1 (ubuntu based).

**Comment by AndrewBelt** [comment]
You might need a `git submodule sync; git submodule update`
