### ISSUE TITLE
Saving the default parameter values for a specific module in the patch file

### ISSUE THREAD

**Issue by catronomix** [VCVRack/Rack#1224]
Being able to not just save a module's settings as default for that module, but as default for that specific instance in the patch, so that after changing knobs its always possible to recall the default for that patch, as long as the module has not been removed.
This could be implemented in the right click menu.
Along with this, some freeze option that prevents accidental clicks on or deletes of a module also comes to mind.

**Comment by Coirt** [comment]
Do you mean like overwriting the default settings programmed into to the module. Saving a default preset to load as the initialization settings?

**Comment by catronomix** [comment]
That too (I thought that was already a feature but then I checked again and it seems it isnt)

**Comment by AndrewBelt** [comment]
I'm not sure if the usefulness of this feature exceeds the corner case issues that would arise.
