### ISSUE TITLE
v1 param bug when clicking a param

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Rack#1226]
See https://github.com/VCVRack/Rack/issues/1021 for issue report standards and https://github.com/VCVRack/Rack/issues/730 before posting any code or terminal output.

Operating system(s): Windows 7
Version: v1.dev.4741892
All hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

Hard bug to reproduce. Sometimes when clicking a knob to change the value it will bounce to the default value on click. Not sure if it has anything to do with double click to reset but it seems a likely cause. It happened on one of my own modules first then on a different module as the gif shows but I could not reproduce on my module again, in the gif anyway. 

![paramResetClcik](https://user-images.githubusercontent.com/12150421/54404074-3e0eb480-46ca-11e9-9b4e-c120e29d2d3b.gif)

 It seems to be a specific spot on a knob where it happens also. As a side note my default double click speed is pretty high, but it seems double clicking to reset does not take the system double click speed into account.

I'm aware it is not the most recent build will update soon and see if it reproducible in that build also, so close if you wish.

**Comment by Coirt** [comment]
I installed latest build anyway and tried to reproduce. I have not been able to on the first go but If I am able to I will let you know!

**Comment by Coirt** [comment]
Scrap that!

**Comment by AndrewBelt** [comment]
Fixed in 6d75538
