### ISSUE TITLE
v1 nvgLetterSpacing with certain characters

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Rack#1228]
Operating system(s): win7
Version: v1 6d75538 and previous v1

Certain characters with nanovg will look squished against the previous character for example:

![nvgLetterSpacing_v1](https://user-images.githubusercontent.com/12150421/54477964-0bb5a200-4805-11e9-8472-c835d2b63e24.JPG)

The above is v1 `nvgLetterSpacing(Context, -1.f);` which is the same as below 0.6.x

![nvgLetterSpacing_v0 6](https://user-images.githubusercontent.com/12150421/54477979-2c7df780-4805-11e9-924d-789af1cebcf2.JPG)

Not sure if it has anything to do with the elimination of transparent box surrounding knobs but its seems like the only change that might effect the rendering.

I refer to the thread on the website https://community.vcvrack.com/t/v1-nvgletterspacing-values-different-from-0-6-x/2378 which contains some more screenshots and SquinkyLabs also see's something similar with LabelWidget for the letter T

**Comment by AndrewBelt** [comment]
>the elimination of transparent box surrounding knobs

What are you talking about?

This might be because of updating stb_truetype.h

**Comment by Coirt** [comment]
In 0.6.x and lower you can grab the space outside a knob circumference, there is a square hitbox surrounding a knobs diameter which is not present in v1.

Would reverting stb_truetype.h be a viable option?

**Comment by AndrewBelt** [comment]
@Coirt Yes, Knob is now assumed to be circular and rejects events outside its circular bounding box, but I have no idea how it's related to this issue.

>Would reverting stb_truetype.h be a viable option?

Yes, when I eventually have the time.

**Comment by AndrewBelt** [comment]
Reverting stb_truetype worked.
