### ISSUE TITLE
Authentication to vcvrack.com is not via https

### ISSUE THREAD

**Issue by robbyt** [VCVRack/Rack#123]
When connecting to vcvrack.com, the connection is currently being made via unsecured http. This should be changed to use https/tls instead, so that passwords are not sent via clear text, and so that plugins are securely downloaded.

**Comment by AndrewBelt** [comment]
It's planned but I've been avoiding it because openssl and libcrypt complicate the build system.

**Comment by AndrewBelt** [comment]
Fixed with dc91b5d403fe564f46cd9d7d49f9958952c2c81e

**Comment by AndrewBelt** [comment]
Reopening because I can't figure out how to get Mac and Windows to bundle certificates, or use native OS certs (ideally), so I'm disabling cert checking for Rack v0.5.1.

**Comment by baderbuddy** [comment]
I'm going to do some tests to be sure, but from the looks of it, it might already be working on Mac.

If LibCurl is using SecureTransport then it's already tying into the OS's cert store. It looks like it's trying by default to compile with SecureTransport.

**Comment by baderbuddy** [comment]
I was wrong about it already being set. I tested the install on Mac, didn't test on Windows, but this should make use of the native SSL now. https://github.com/VCVRack/Rack/pull/805

**Comment by AndrewBelt** [comment]
Not sure why I didn't close this. Root certificates have been bundled for a few months.
