### ISSUE TITLE
Issue building all repose OSX 10.14.3

### ISSUE THREAD

**Issue by sedurCode** [VCVRack/Rack#1230]
Hi, 
Following the instructions found at the bottom of the Wiki for this repo, I am failing to build the repos in the library.
![out](https://user-images.githubusercontent.com/25512064/54646729-f60bdb00-4a97-11e9-9a9f-18b81698d543.gif)
Could someone please point out if I have done something wrong here.
The Library is in the plugins folder of the Rack repo, built successfully on branch v0.6, and the submodules of the library repo have also been initialised.

**Comment by AndrewBelt** [comment]
The `dist_all` target doesn't exist, not sure why you typed that.

**Comment by sedurCode** [comment]
![Screenshot 2019-03-19 at 22 55 49](https://user-images.githubusercontent.com/25512064/54647397-32403b00-4a9a-11e9-9270-0d2b3dfb360c.png)
Because it is written in the README for the library

**Comment by AndrewBelt** [comment]
Ah, not sure why that's there. Removed from README.
