### ISSUE TITLE
[Feature Request] Support Two-Factor Authentication for VCV Rack Accounts (in App and Web)

### ISSUE THREAD

**Issue by SynthMage00** [VCVRack/Rack#1233]
Please add support for two-factor authentication whenever/wherever a login to vcvrack.com is required, preferably via a OTP application such as Google's Authenticator.

**Comment by Coirt** [comment]
Why?

**Comment by jonheal** [comment]
Nuclear reactor control rod control? Yes. VCV Rack. Please no.

**Comment by AndrewBelt** [comment]
Just use a decent password and uninstall all the keyloggers from your computer.
