### ISSUE TITLE
VCV Host - Midi out.

### ISSUE THREAD

**Issue by SmallTownSound** [VCVRack/Rack#1234]
Is there a chance to add Midi Out to VCV host if the vst supports it.  That would open up a LOT of very good pitch to voltage converters to use in rack.

Don Turnock

**Comment by AndrewBelt** [comment]
There are currently no plans for this, but we will consider it.

**Comment by stoermelder** [comment]
+1

**Comment by AndrewBelt** [comment]
This is the issue tracker for VCV Rack. Send bug reports and feature requests of VCV plugins to contact@vcvrack.com.
We have added this to our internal issue tracker. Comment your email address here if you would like to be informed of future updates to this issue.

**Comment by soundvisions** [comment]
gabriel.diego.rey@gmail.com
