### ISSUE TITLE
Higihlight module when selected

### ISSUE THREAD

**Issue by Nowhk** [VCVRack/Rack#1238]
Some time I think to have selected some module, but in reality I didn't.
So I delete or random a module that wasn't my target.

Could it possible to highlight the module with a lighter color around the border of it?
Such in a Browser when I focus a textarea: it draws a tiny border.

We can know on which module we are dealing ;)

**Comment by AndrewBelt** [comment]
There is no selection in Rack. Simply hover your mouse over it and hit Delete, etc.

**Comment by Nowhk** [comment]
This mean that [this](https://github.com/VCVRack/Rack/issues/1225) won't never be created?
So no chances to multi-select different modules for delete/random/etc?

**Comment by thouldcroft** [comment]
I wasn't aware of Rack working like this either - I come from a Max/Pd background and so the idea of selecting a module and then operating on it was my first intuition. Could this just be my background, or would this improve usability for other users with Rack? I also feel that a selection indication would also facilitate, as @Nowhk mentioned, multi-selection of modules and performing group actions on them. I often find myself duplicating a module chain, and wish that I could duplicate the chain all at once, with patch cables intact.
