### ISSUE TITLE
V1 module browser doesn't show module names

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#1239]
I have been using the names to help people know what the modules do. Now that there are only pictures, how will they find them? The TAGS don't help much for modules that don't happen to match the tags. Here is how they look in V0.6.x: 
![image](https://user-images.githubusercontent.com/16314838/55240202-8dd69b00-51f5-11e9-82ce-55ec4d5ed0cc.png)

**Comment by squinkylabs** [comment]
In V1: 
![image](https://user-images.githubusercontent.com/16314838/55240243-b9598580-51f5-11e9-9971-53ff70ff7b8c.png)

**Comment by squinkylabs** [comment]
It look like it's supposed to go somewhere. Maybe I'm missing it:
```
	ui::Label *descriptionLabel = new ui::Label;
		descriptionLabel->box.size.x = box.size.x;
		descriptionLabel->box.pos = pos;
		descriptionLabel->text = model->description;
		addChild(descriptionLabel);
		pos = descriptionLabel->box.getBottomLeft();
```

**Comment by AndrewBelt** [comment]
It was omitted per @milholen and my decision, since all well-designed modules should clearly have the name on their panel. If not, that's the problem of the module, not Rack IMO.

**Comment by Coirt** [comment]
On that note: on larger displays would it be a possibility to be able to set the zoom size for the module browser. My display is a 32" 1080p monitor but the default zoom for the browser is fairly small can just make out module text and that is for modules that have clear to read text.

I'm 3 feet away from the monitor btw and I have my glasses on!

**Comment by AndrewBelt** [comment]
@Coirt Their original sizes were actually 100%. Now they're 50%. I could change it back to 100%.

**Comment by squinkylabs** [comment]
I like the current smaller size. But I used a small monitor, I must admit

**Comment by Coirt** [comment]
That's the thing on a smaller monitor such as laptop screen the browser looks okay but bigger screen size is almost unreadable. If it could be set in a json I could settle for that myself. Wonder if there is a number that would work for both screen sizes.

I'm afk at the moment I could recompile/test different sizes tomorrow possibly. Where would I need to change to get a bigger zoom, can come back with a number.

**Comment by AndrewBelt** [comment]
`MODEL_BOX_ZOOM` in ModuleBrowser.cpp. I don't want anything but integer scaling factors because things look nonideal at things like 75%.

**Comment by milholen** [comment]
One suggestion: use the current zoom level from the patching view and set the module height in the module browser to match that.

**Comment by Coirt** [comment]
Something occurred to me, would a tooltip for module slug/description be another way to address or rather no need to address as you have the tooltip telling what the module is.

@milholen That could possibly be a better way.

For 768 screens 0.68 (2 rows) for 1080 0.695 (3 rows). The average difference between both being `0.6875` could work well for both sizes, on 1080 that shows 3 and a bit rows, the screws show on the 4th row. 0.674 (exactly 2 rows on 768) could also work but shows a little bit more of the top of the 4th row on a 1080.

Tested on a second monitor set to 1366 x 768.

**Comment by milholen** [comment]
@AndrewBelt and I did talk about having a tooltip on module hover to help with the learning curve, that might be a good solution for what @squinkylabs has mentioned.

**Comment by squinkylabs** [comment]
Tooltips would work. I love the new images, but until one memorizes the association between the image that the function it's difficult.

**Comment by MarcBoule** [comment]
Looks like tooltip names have been added in the module browser Bruce :-) https://github.com/VCVRack/Rack/commit/735dc0206593aab757c42170ada54d8abf164d5d
Great addition Andrew!

**Comment by Coirt** [comment]
Sweet, guess that solves it.

**Comment by squinkylabs** [comment]
Bravo!

**Comment by squinkylabs** [comment]
Will the module description ever be used? I would be pretty sweet to have that as the second line of the tool tip.

**Comment by AndrewBelt** [comment]
Plugin brand, module name, description, and tags are now displayed in tooltips.

**Comment by BoscoRemus** [comment]
Have noticed with the tooltip in the module browser that if the module is real close to the right-hand side the tooltip gets cut off.. it would be good if the tooltip shifted over to the left so it does not get cut off...

**Comment by BoscoRemus** [comment]
sorry for the above comment seems to have been fixed..
