### ISSUE TITLE
Small annoying graphic bug

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/Rack#124]
Small annoying bug (on Mac, on PC no problems)
Looks like all "closed" letters (O, A, D, Q, and so on) don't render properly, letters like I, L, M, N which have an "open" shape render correctly...
It happens on fundamentals and on some modules I am developing (see pic)

![graphicbug](https://user-images.githubusercontent.com/16060683/30725976-89e5e976-9f48-11e7-926f-692b72e57fd2.png)

**Comment by AndrewBelt** [comment]
You're right, I haven't added the implementation of the bezier crossing algorithm for computing winding direction of subpaths yet.

**Comment by antoniograzioli** [comment]
Great to know. On PC there are absolutely no problems....

![moduli](https://user-images.githubusercontent.com/16060683/30735342-ed88335e-9f7e-11e7-88d0-6537f8a975ee.png)

**Comment by AndrewBelt** [comment]
It's because your source trees are different, and I reverted back to old behavior a while ago. I still need to overhaul the renderer though.

**Comment by antoniograzioli** [comment]
ok, could be that my Mac sources are newer than the ones on PC

**Comment by AndrewBelt** [comment]
Fixed, mostly. SVG render isn't perfect but much better than that day I was ripping everything out of it.
