### ISSUE TITLE
[V1] Tool Tip on inputs and outputs

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#1240]
lots of times it would be very nice. Esp for module that have a lot on inputs and ouutpts, and not enough panel space to label them well.

**Comment by AndrewBelt** [comment]
>not enough panel space to label them well

You make it sound like there's a better way than the feature request you're suggesting. (*Use more panel space.*)

**Comment by Coirt** [comment]
This would be a nice feature to have IMO. Say you have a module with a long cable a quick glance at the inputs tooltip on the device it is connected to would tell you what the connection is e.g. `*module #1 Gate Output: 3`. Tracking the cable all the way to the device can get laborious.
