### ISSUE TITLE
[V1] module browser get stuck after user selects an Author

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#1241]
1. bring up the module browser in v1.0
2. select one of the authors, like `VCV`

You see the authors, but there is no way to see a different author, or get back to `all`.

**Comment by Coirt** [comment]
You click the tag again but if you can't remember what tag you clicked on that can be troublesome alright!

**Comment by squinkylabs** [comment]
oh, sure enough! But, yeah, I never would have guessed that. Well, at least I didn't.

**Comment by Coirt** [comment]
Perhaps down the line a check mark "✔" could be placed on each item on the filter. Already one for context menu iirc.

**Comment by modlfo** [comment]
There exists a button to Reset the filters. I think that the button would fix the issue. I'm closing it for now. @squinkylabs If you think that does not solve the problem, feel free to comment.
