### ISSUE TITLE
Upload Plugins Box makes a new line if the name is larger (messing the whole text)

### ISSUE THREAD

**Issue by Nowhk** [VCVRack/Rack#1245]
Operating system(s):
Windows 10 Professional, 64bit, MinGW (gcc + gdb) and VSCode.
Rack-SDK, 0.6.2c

When I update plugins, and the plugins "naming" is larger than the progress upload field, it mess the texts:

![newline](https://user-images.githubusercontent.com/19835752/56044120-cf5f5e00-5d3e-11e9-8a7a-ffe4f9594934.png)

**Comment by AndrewBelt** [comment]
This has been solved with Rack v1.
