### ISSUE TITLE
Build failure: "No rule to make target 'include/util.hpp'"

### ISSUE THREAD

**Issue by jamshark70** [VCVRack/Rack#1246]
Operating system(s): Ubuntu Studio 18.04
Version of Rack if using official binary, or commit hash and branch if compiling from source: c4fb4394c0
All hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): (fairly sure this isn't relevant to a build issue)

I had previously built v0.5.0 in Linux (with JACK support). I wanted to upgrade to v0.6.x. So I `pull`ed, checked out v0.6.2, de-inited and re-inited submodules (+ `--recursive`).

`make dep` went fine.

`make` stops with:

```
make: *** No rule to make target 'include/util.hpp', needed by 'build/src/engine.cpp.o'.  Stop.
```

I'm somewhat comfortable with git and with building things from source, but I don't know `make` and I'm not at all intimately familiar with Rack's source. Wondering what to do next. (Not a super-urgent question, either.)

**Comment by Coirt** [comment]
Was it a clean pull or did you overwrite the existing 0.5.0 build? If the later `make clean` and `git submodule update --init --recursive`  `make dep` `make` 
or 
Checkout to a new folder and in the new rack directory `git submodule update --init --recursive`  `make dep` `make`

**Comment by jamshark70** [comment]
I was updating in place.

`make clean` and repeating the process got a little further, but then:

```
/usr/bin/ld: dep/lib/libjansson.a(hashtable.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: dep/lib/libjansson.a(hashtable_seed.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: dep/lib/librtmidi.a(RtMidi.o): relocation R_X86_64_32S against symbol `_ZTV6RtMidi' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
compile.mk:55: recipe for target 'Rack' failed
```

So I think I will re-clone into a new folder and build from scratch. (Though, if one has to re-clone for a version update, that kind of defeats the purpose of git, doesn't it? :rofl: )

**Comment by jamshark70** [comment]
A fresh checkout resolved all the build issues.

(But, `make clean` had not resolved them... so maybe `make clean` isn't doing everything it needs to do?)

**Comment by Coirt** [comment]
`make clean` `git checkout vX.X` would probably be the one then but if you back up and running glad I could help!

If you are just testing a version you are much better off doing a clean pull you won't always see all changes between versions, it is bound to break something.

**Comment by jamshark70** [comment]
> If you are just testing a version you are much better off doing a clean pull you won't always see all changes between versions, it is bound to break something.

Hm. Maybe submodules or dependencies, then. If progressive updates break things in the main codebase, then git is not working.

Anyway I'm up and running, so, closing this one.
