### ISSUE TITLE
JACK audio module isn't auto-connecting to hardware

### ISSUE THREAD

**Issue by jamshark70** [VCVRack/Rack#1247]
Operating system(s): Ubuntu Studio 18.04
Version of Rack if using official binary, or commit hash and branch if compiling from source: Branch v0.6, 7d8c04c993
All hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): JACK, with built-in audio hardware and with a Focusrite Scarlett 2i4

1. `make run` Rack.

2. Add an Audio module.

3. Select the "system" device.

4. Check the Connections window in qjackctl. The Rack client exists but it isn't connected (so, of course, if I connect any other modules to the audio outputs, I hear nothing).

![vcv-no-connection](https://user-images.githubusercontent.com/318301/56415978-0646ee00-62c2-11e9-824a-3a9f40a9707d.png)

I do get sound (clean sound!) if I go into qjackctl and manually connect Rack to system:playback ports. I see no problem except the failure to connect automatically.

If it matters, I have disabled JACK dbus support in qjackctl because that has always caused me problems with audio device selection. If this is required for Rack to auto-connect, then I might have to revisit that.

Or maybe there's some other configuration thing that I missed.

**Comment by infamedavid** [comment]
I have success with the auto conection using a ladish ([Claudia](https://kx.studio/Applications:Claudia)  )  but actually it only wor wit the core audio and the rcm audio 16, for some reason it not work with [SKJack](https://github.com/Skrylar/skjack-vcv/issues/15)...

**Comment by jamshark70** [comment]
> I have success with the auto connection using a ladish

Oh, OK... I hadn't heard of that being a common requirement.

All of the other JACK-compatible software packages I've used (Ardour, Audacity, SuperCollider) manage their own JACK connections. I had thought it was a reasonable assumption that VCV Rack would, as well.

Also, when I used the experimental JACK support in v0.5, it did auto-connect. So at least this user's experience is a regression.

**Comment by jamshark70** [comment]
Further: When Audio-8 shows "JACK" for the driver but "(No device)" is selected, VCV Rack does not even appear in the qjackctl Connections window. Shouldn't the i/o ports be established at that time?

Then, choosing "system" as the device creates the i/o ports but doesn't connect. It's counterintuitive: Choose a "device" but you aren't actually talking to that device yet.

And one has to go create the connections manually *every time* an Audio-8 module is created (or loaded in a patch). Rather a high annoyance factor actually and I expect an easy fix.

**Comment by g4z** [comment]
Agreed! This behaivour is a bit weird. From a user perspective, seems like having VCVRack do the Jack connection in the background would be the best user experience (perhaps there's technical reasons for not doing this). 

Currently, i have to open qjackctl to connect Rack to something. If i want to record into my DAW, and i select my DAWs inputs as the output in Audio-8, i have to then manually create this connection myself :/

**Comment by AndrewBelt** [comment]
JACK doesn't fit perfectly into RtAudio/RtMidi's abstraction, so VCV doesn't support JACK. Perhaps https://vcvrack.com/plugins#SkJack will solve your issue.

**Comment by jamshark70** [comment]
May this at least be documented then (maybe FAQ)? You can expect this question to arise from basically every Linux audio user. (I do understand the risks involved in recommending third party plugins whose maintenance is outside your control, but it may be worth it here.)

**Comment by g4z** [comment]
> so VCV doesn't support JACK other than just including it in the build as-is

that's fine for me. i'm happy to have jack as an option. it's a minor inconvience having to manually connect. 

interesting to see that there's a VST plugin in the works. hoping this will support Linux! as a usually use Daw + Jack together, i would be happy to pay for a Linux VST version of Rack. :+1:

**Comment by jamshark70** [comment]
> Perhaps https://vcvrack.com/plugins#SkJack will solve your issue.

Ah, in fact, it doesn't... it also doesn't auto-connect (neither when adding an instance, nor when reloading a patch).

I can accept that it may be difficult to fix in Audio-8, and I'll follow up with the Jack plugin as well. But I'd also note the behavior of other Jack apps I've used:

- Ardour: Auto-connects to "system" ports (you can change that in the Ardour interface, and the connections are saved in the project file)
- SuperCollider: Auto-connects to "system" ports (configurable by system environment variables)
- Pure Data: Auto-connects to "system" ports
- Audacity: Auto-connects to "system" ports (at playback time)

And... VCV Rack: Does *not* connect.

Which is why I opened the issue. The expectation is pretty clear that a Jack app should be audible right away, without the user having to go somewhere else to hook it up.

**Comment by AndrewBelt** [comment]
Perhaps you can help other JACK users and develop a plugin that solves the issues you list.

**Comment by jamshark70** [comment]
For posterity: The solution is aj-snapshot - https://sourceforge.net/projects/aj-snapshot/
