### ISSUE TITLE
onDrag (Start/Move/End) is not triggered using middle mouse (or right) button

### ISSUE THREAD

**Issue by Nowhk** [VCVRack/Rack#1248]
Operating system(s):
Windows 10 Professional, 64bit, MinGW (gcc + gdb) and VSCode.
Rack-SDK, 0.6.2c

If I try to trigger the onDrags methods (Start/Move/End), it works only if I drag clicking left mouse button. With the middle (or right) mouse button nothing happens.

**Comment by AndrewBelt** [comment]
I am currently debating adding a `button` field to `Drag*Event`s in v1.
However, if plugin developers do not add a `if (e.button == HoverScrollEvent)` check to their event handler, right-click drag would trigger their events.

Middle-click should never initiate a drag behavior because this fakes a `HoverScrollEvent` instead.

**Comment by dhemery** [comment]
I think left and right drags represent different user intentions. Given that, I’d prefer calling a separate function.

**Comment by AndrewBelt** [comment]
@dhemery That's an option, but it adds cruft to the event system which would either 1) have to stick around for the next 20 years, or 2) be eventually deprecated, which would take more plugin migration effort than making the switch now. Also, you say "different user intentions", but if a plugin developer wanted to have two different functions for left- and right-click-dragging, they would have to add the above fix anyway.

**Comment by Coirt** [comment]
It might be a nice feature to have the ability to snap to on right mouse. Say for a sequencer or EQ that don't use snap values, it would be good for tuning Filter/EQ's. Any param that could make use of it LFO, timing etc.

**Comment by AndrewBelt** [comment]
@Coirt Right-clicking on `ParamWidget`s opens the parameter context menu in v1, can't add right-click-drag behavior to it.

**Comment by Coirt** [comment]
Left click then Right click drag I thought you meant? Currently if you press and hold Left click and then Right click you open the param context menu or the context menu of which ever module the mouse is over, but you still have the ability to drag with the menu open pressing enter at any point will snap to the value in the text field of the param context as long as you are not dragging of course but it does not interrupt left click drag.

**Comment by AndrewBelt** [comment]
Yeah idk, that sounds like an obscure gesture. I'm just talking about the behavior of the general event system in this issue though.

**Comment by MarcBoule** [comment]
I think adding adding a `button` field to `Drag*Event`s i might be the best way to go. Since we are all updating our modules (or will start soon), this may be the best time to do it, and if this is technically the most desirable/versatile solution, might as well do it now in my opinion.

**Comment by Nowhk** [comment]
My request Is because I'd like to zoom an eq plot... pressing middle mouse button and "move" it.

How would you do this?

**Comment by AndrewBelt** [comment]
`Drag*Event`s now have a `button` field as of 79f0fd7ed37b5ea2b481dbf30b3cb9813fb04bfe. You can do something like the following to enable dragging. Because superclasses like `OpaqueWidget` do not consume middle-click events by default, you need to consume middle-clicks with `event::Button` and then `event::DragStart` to finally set your `Widget` as being dragged.

```cpp
	void onButton(const event::Button &e) override {
		// Consume Button event so DragStart is triggered
		if (e.button == GLFW_MOUSE_BUTTON_MIDDLE) {
			e.consume(this);
		}
	}

	void onDragStart(const event::DragStart &e) override {
		// Consume DragStart event so the Widget can be dragged
		if (e.button == GLFW_MOUSE_BUTTON_MIDDLE) {
			e.consume(this);
		}
	}
```

**Comment by Nowhk** [comment]
Not sure what I Need to do now so. Do you fix it on a new release? Only on 1.0?

I'm with Rack SDK...

**Comment by AndrewBelt** [comment]
Yes, 79f0fd7ed37b5ea2b481dbf30b3cb9813fb04bfe is in the v1 branch

**Comment by Nowhk** [comment]
So I think I have to wait. SDK is only for 0.6.2 right? Or can I implement my own widget in some way to get the same behaviour? I don't think. It seems middle drag its not called at all...

**Comment by Nowhk** [comment]
@AndrewBelt: do you confirm that in 0.6.2 this won't be possible and I need to wait the release of (sdk) 1.0?

**Comment by Nowhk** [comment]
Yeah, I think so: https://github.com/VCVRack/Rack/blob/7d8c04c993fa6d2d37e41bfaef015970e1932e5c/src/window.cpp#L74

It handles only button left... so there isn't any chances I guess to have it to work in 0.6.2...

**Comment by AndrewBelt** [comment]
Yes, as I said, the commit 79f0fd7 is only in the v1 branch. This does not magically make it possible in previous versions.

**Comment by patman023** [comment]
Will/could this break my click+hold middlemouse to drag, whether dependent on my mouse position, or globally? I use a trackball, and this is crucial to my workflow.
