### ISSUE TITLE
[Feature Request] expanders for Core Audio-module

### ISSUE THREAD

**Issue by stoermelder** [VCVRack/Rack#1249]
I have an audio-interface with 32 ins and 32 outs (RME Digiface USB). I know there is a 3rd Party module supporting 16 ins and 16 outs, but I think i would be more convenient having expanders (available in V1) for the core module to access additional channels of an interface. 
Would also solve #749

**Comment by AndrewBelt** [comment]
Expanders probably aren't the best way to go about this. I still prefer to mux the channels of `audio::Device` backends.
