### ISSUE TITLE
Add Clipping LED to Audio Module

### ISSUE THREAD

**Issue by jonheal** [VCVRack/Rack#1250]
I propose adding an additional LED to the Audio module that would indicate when it receiving a voltage that will clip. Maybe this LED could be green up to -6dB, yellow from -6dB to 0dB and red at 0dB and above. This would save time for quick patches one wished to record as it would no longer be necessary to patch in meter module(s). I guess it would need one for each input.

**Comment by AndrewBelt** [comment]
No to adding LEDs, but what about making the existing green LED red, @milholen? Might incorrectly signal to the user that there is a driver issue with the channel pair.

**Comment by milholen** [comment]
Having the LED color change based on the input would be OK. How you do handle the LED colors on the MI/AI Resonator plugin for example?

**Comment by AndrewBelt** [comment]
@milholen Rings? I just have it change color based on the mode. Is there another purpose that I'm forgetting?

**Comment by milholen** [comment]
Yes, Rings. Just saying that you must have a protocol for changing the color of a single LED already.

**Comment by AndrewBelt** [comment]
Yes, multi-colored LEDs are somewhat common. I just add a multi-colored LED and send its "virtual leads" voltages which correspond to their base colors, like green/red or red/green/blue.

**Comment by milholen** [comment]
OK, well I'd approve of the request in general if there's no technical barrier then.

**Comment by jonheal** [comment]
> VCV Recorder has a clip indicator. No need for Audio to have one in this scenario.
I reckon that's all I'd need.

**Comment by Coirt** [comment]
It would be worth the thought to be able set a threshold level to aim for with core audio with an LED indicator (-3dB/-6dB), that being said there is a few modules that offer metering.

**Comment by squinkylabs** [comment]
simple clipping indication is a nice idea.

**Comment by AndrewBelt** [comment]
This feature will be present in Rack v2.
https://community.vcvrack.com/t/rack-development-blog/5864/47
