### ISSUE TITLE
[Feature Request] -- Mappable keyboard shortcuts (Zoom level To num. pad)

### ISSUE THREAD

**Issue by poowok95** [VCVRack/Rack#1251]
Hi Andrew,
I was thinking it would be awesome if mappable keyboard shortcuts could be implemented if possible. The flexibility for users to map any feature to any key combo would be great.

If that's too much of an undertaking, I was thinking more specifically of having numbers 0-9 be assigned to different zoom levels (say 1= %100 zoom; 2= %110 zoom etc., and maybe make 0= %50 zoom, or something to that effect.) Also when the number is pressed, the zoom should be centred around the mouse cursor

I think this would be good because some modules interfaces vary in legibility, so being able to zoom in and out on the fly would be great. The logic behind the 0= %50 zoom is that would provide a handy way to quickly have an overview of larger projects.
Thanks!

**Comment by AndrewBelt** [comment]
0-9 are taken by the computer keyboard MIDI driver. Ctrl-`-` and Ctrl-`=` could work.

**Comment by AndrewBelt** [comment]
Added in 98bd228

**Comment by Coirt** [comment]
Quick zoom could be very nice, could `GLFW_KEY_KP_0` to `GLFW_KEY_KP_3` be an option?
User settable zoom to keystrokes would also be a very nice feature.

**Comment by Coirt** [comment]
Keypad keys are not mapped are they?

**Comment by AndrewBelt** [comment]
@Coirt No. I'm just going to leave those out for now since not everyone has a number pad.

**Comment by poowok95** [comment]
Wicked, thanks! :)
