### ISSUE TITLE
Rack V1 port: FrameBufferWidget changed?

### ISSUE THREAD

**Issue by baconpaul** [VCVRack/Rack#1252]
Hello. I'm working on getting my modules running with the current V1 branch. The directions were clear and I did the "proper" as opposed to "rack0.hpp" port. After a couple of hours things are starting to run. 

One problem I can't figure out though is that FrameBufferWidget seems to not be drawing my custom lights properly. It does in small/preview gen mode (once I handle the new `module==nullptr` case the preview use) but when running they don't work.

My code has a FrameBufferWidget which takes a draw function then dispatches to it when dirty.  Here's my current port. As configured here (where it subclasses `widget::Widget` and has a bool dirty member which is ignored) my code draws; if I change it so that it subclasses `FrameBufferWidget` (and obviously remove the `bool dirty=true` when I do that) it does not.

I did some debugging; it seems I get all the way into `Widget::draw` from the `drawFrameBuffer` but for some reason which is opaque to me - but which is neither the visibility check nor the clip check - my `InternalBDW::draw` is not called.

The same code works fine in 0.6.2 but I can't see the change in the API.

Any help or ideas are appreciated. And I apologize if this is the wrong forum for asking V1 port questions. Please feel free to just redirect and close if there is a more appropriate venue.

I am on macOS 10.14.4 with a mid 2015 MacBook pro using Rack V1 that I pulled from GitHub saturday night.

Thank you.

```
template <typename T>
struct BufferedDrawFunctionWidget : virtual /* FramebufferWidget */ widget::Widget {
    typedef std::function<void(T *, NVGcontext *)> drawfn_t;
    
    // Put this in when I change baseclass to compile at least
    bool dirty = true;
    
    T *that;
    drawfn_t drawf;

    struct InternalBDW : Widget {
        T *that;
        drawfn_t drawf;
        InternalBDW(Rect box_, T *that_, drawfn_t draw_)
            : that(that_), drawf(draw_) {
            box = box_;
        }
        void draw(const DrawArgs &args) override {
            drawf(that, args.vg);
        }
    };

    BufferedDrawFunctionWidget(Vec pos, Vec sz, T *that_, drawfn_t draw_)
        : that(that_), drawf(draw_) {
        box.pos = pos;
        box.size = sz;
        auto kidBox = Rect(Vec(0, 0), box.size);
        InternalBDW *kid = new InternalBDW(kidBox, that, drawf);
        addChild(kid);
    }
};
```

**Comment by AndrewBelt** [comment]
I've added warnings in 7624c46 when framebuffers cannot be created. Try it now and see if there are warnings in the log.

**Comment by baconpaul** [comment]
Just pulled and built; no warnings and still no paint if I implement FBW as opposed to Widget.

Happy to debug it myself also if you want - any hints welcome. 

If you want I pushed a version to my `candidate_v1.0.0` branch which compiles (you renamed events since I last checked so I fixed that too - https://github.com/baconpaul/BaconPlugs/commit/a56160b069e17e289f2f6366780024c69218fe2a) if you want to look. Any of the widgets with a seven segment light fail (you can try `ChipNoise`) but I am not asking you to debug my code of course! Just in case you do want to run it.

Thanks

**Comment by baconpaul** [comment]
Just an update: Writing this up has me debugging my code. I am not assuming you are working on it but please hold off for a bit since I think I may have a lead on my problem.

**Comment by baconpaul** [comment]
Yeah I found it; nothing to do with FrameBufferWidget (really). 

The problem was that i had a custom subclass of Widget which had overriden `draw()` but not `step()` and handled children in a unique way; so with the introduction of `step()` on the widget I needed to delegate properly.

Sorry for the noise. I'll close the issue!
