### ISSUE TITLE
Add Authors to Favorites List

### ISSUE THREAD

**Issue by poowok95** [VCVRack/Rack#1255]
Hi Andrew,
It would be great if it was possible to add entire collections of modules from different authors to the favourites list instead of just individual modules.

Also, the ability to drag and drop favorites to reorder them could be a cool feature too. This would allow users to arrange their favorites list in order of their most used modules/authors 

Thanks!!

**Comment by AndrewBelt** [comment]
Closing since favorites has been removed.
