### ISSUE TITLE
[Feature Request] Set default zoom 

### ISSUE THREAD

**Issue by poowok95** [VCVRack/Rack#1256]
Hi Andrew,

It would be awesome if it was possible to set the current zoom level as the default for when users right click. 

For example, on my 13 inch laptop, the ideal zoom which fits my screen size comfortably while still being legible is 111%, so every time i zoom out It needs to be reset manually. Could speed up workflow if this was possible with one right click.

Giving users the option to set their default zoom would mean they could set their default zoom to whatever fits their resolution/screen size best. 

Thanks!

**Comment by modlfo** [comment]
Rack v1 remembers the zoom level you are using when creating a new patch. Closing this as fixed.

**Comment by AndrewBelt** [comment]
I think @poowok95 means that right-clicking on the zoom slider should reset to a custom value like 111%.
Although, I'll keep this closed, since I reject the feature request in its literal form. Right-clicking, or double-clicking in Rack v1, should always the zoom slider to 100%.
