### ISSUE TITLE
V1 Drag Events not propagating

### ISSUE THREAD

**Issue by baconpaul** [VCVRack/Rack#1257]
Hi!

Using this morning (6fd01b2) code drag event don't propagate reliably. dragStart happens but dragMove and dragEnd do not.

The reason for this I found is because the context in event::setDragged does not set the draggedWidget value Here's a diff that fixed it:

```
diff --git a/src/event.cpp b/src/event.cpp
index 0f6a355..0669981 100644
--- a/src/event.cpp
+++ b/src/event.cpp
@@ -44,6 +44,7 @@ void State::setDragged(widget::Widget *w, int button) {
        if (w) {
                // DragStart
                Context cDragStart;
+                cDragStart.target = w;
                DragStart eDragStart;
                eDragStart.context = &cDragStart;
                eDragStart.button = dragButton;
```

clearly without that there is no target in cDragStart so the code that does `draggedWidget = cDragStart.target` later sets the draggedWidget to 0 which suppresses the onDragMove messages and so on where they check `if (draggedWidget)` before propagating.

There may be another fix of course; but the one line change above means my widget gets the drag move events and I can get close to finishing my 1.0 port!

Hope this is a clear enough bug report! Thanks so much.

**Comment by AndrewBelt** [comment]
`event::DragStart` docstring:

>Must consume to set the widget as dragged.

You need to call `e.consume(this)` if you want to begin dragging the widget.

**Comment by baconpaul** [comment]
Thank you! And apologies for the noise.

**Comment by AndrewBelt** [comment]
On second thought, I will remove the requirement to set the target of `DragStart`, `Select`, and `Enter` to trigger other events, such as `onDragMove`, `SelectKey`, and `Leave`. This does not decrease the generality of the event system because you can unset the target with `e.setTarget(NULL)` to achieve the opposite behavior of `e.consume(this)`.

**Comment by AndrewBelt** [comment]
Removed as of faa96068af06103bd4e3aae008292f57b7bf09a4

**Comment by baconpaul** [comment]
Great thank you.

One other minor thought: onDragStart event type `DragStart : DragBase : Base` which means the onDragStart event doesn't carry the position of the drag point. As such I'm using onButton to capture the position at dragStart and onDragMove to accumulate deltas.

Any thoughts of making DragStart also inherit PositionBase? My code works either way but just thought I'd share the observation.

Appreciate the quick fix. My plugins now all seem to work fine with 1.0! Look forward to the release.

**Comment by AndrewBelt** [comment]
`onDragStart` is triggered by responding to `onButton`. Since the event is triggered directly rather than recursively by position, the event system cannot know the position relative to the widget.

**Comment by baconpaul** [comment]
OK gotcha. Thanks.

(I can just capture position 0 in onButton anyway so it’s not a big deal from a function perspective; just aesthetically using onButton / onDragMove vs onDragStart / onDragMove seemed like maybe I was missing something in the pattern - now I know I’m not!).
