### ISSUE TITLE
Not loading modules :( : (

### ISSUE THREAD

**Issue by johnnycumquest** [VCVRack/Rack#1259]
See https://github.com/VCVRack/Rack/issues/1021 for issue report standards and https://github.com/VCVRack/Rack/issues/730 before posting any code or terminal output.

Operating system(s):
Version of Rack if using official binary, or commit hash and branch if compiling from source:6.2 not modified
All hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):N/A  with or without my interface it is having this problem, I have a macbookpro running 10
.10.4 yosemite

Hi when ever I try to load a module the face is missing or it wont load at all.  All of the basic ones that vcv rack made wont load, and Alot of the modules are loading without faceplates.  I posted an issue earlier with the same problem and you told me to respond to the questionair so i am doing that.  Also I uninstalled my version and reinstalled it and it is doing the same thing, maybe I didnt do all that right?

**Comment by AndrewBelt** [comment]
Could you post your `log.txt` file from the [Rack local directory](https://vcvrack.com/manual/FAQ.html#where-is-the-rack-local-directory)?

**Comment by mattjhnsn** [comment]
I am experiencing similar issues. I'm new to VCV Rack and I have not been able to load any modules, including the fundamentals. I also tried adding other plugins on the site and then logging in in the app and clicking update plugins. Still nothing.

**Comment by mattjhnsn** [comment]
[log.txt](https://github.com/VCVRack/Rack/files/3180213/log.txt)

**Comment by AndrewBelt** [comment]
@mattjhnsn Your log says that Fundamental was loaded fine. What plugins do you have available in the Module Browser when right-clicking the rack?

**Comment by mattjhnsn** [comment]
I got it working, thank you!

**Comment by johnnycumquest** [comment]
I dont know what to say but its not loading anything

________________________________

**Comment by djpeterso23662** [comment]
My v1 Rack did not load any modules I compiled until I used the -d startup parameter.
