### ISSUE TITLE
Befaco and Eseries compilation fails on Win7 64 Dev version.

### ISSUE THREAD

**Issue by Strum** [VCVRack/Rack#126]
OS (if applicable):
Version (or "dev" if compiling from source):

**Comment by Strum** [comment]
src/E340.cpp:35:2: error: 'MinBLEP' does not name a type
  MinBLEP<16> sineMinBLEP;

Similar errors for the Defaco modules

**Comment by leopard86** [comment]
I can confirm. Just pulled from git and recompiled

**Comment by sbcook0** [comment]
ditto on Win10
just d/l source a few minutes ago

**Comment by srizzi88** [comment]
It fails on Mac OS, El Capitan, Xcode 8.0, too.
similar errors about MinBLEP.

**Comment by AndrewBelt** [comment]
Fixed in a8f30ca3c751e4368733991c351634bb38caebf7, sorry!
