### ISSUE TITLE
VCV Rack crashing when loading modules

### ISSUE THREAD

**Issue by Bassplayerwizard** [VCVRack/Rack#1260]
See https://github.com/VCVRack/Rack/issues/1021 for issue report standards and https://github.com/VCVRack/Rack/issues/730 before posting any code or terminal output.

Operating system(s):
Version of Rack if using official binary, or commit hash and branch if compiling from source:
All hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

**Comment by Bassplayerwizard** [comment]
Please help! I can load some plugins but not all.  Originally installed VCV rack and all plugins on another computer and have just installed VCV on my music pc and updated all plugins via manage plugins and they all show up on search box but its hit and miss which will load or not. VCV rack simply hangs.  Cannot load any previous saved sessions.

**Comment by AndrewBelt** [comment]
Please fill out the issue form and I will reopen.
