### ISSUE TITLE
Method request in Light.hpp: get/set value directly without brightness mechanism

### ISSUE THREAD

**Issue by MarcBoule** [VCVRack/Rack#1264]
Rack v1

In `include/engine/Light.hpp`, it is stated in the comments that accessing the light's value directly is not recommended for future stability reasons. However, currently the only methods to get/set the light's value have square_root/square in them, respectively, but in some cases we may want to directly write the light's value without this scaling. Two examples of this are:

1) if a developer was using `.value` directly and had hard-coded light values that already compensate for brightness, it would mean adjusting many modules if we were to only have access to the light's value through the brightness methods.
2) In cases when a light is 1.0f, there is square (likely a multiplication when optimized) in the setBrigntness() that is redundant, and for optimization reasons it could be avoided.

Thus I think it would be useful if those two small getter/setter methods could be added in `Light.hpp`. Thanks for considering this. Cheers!

**Comment by AndrewBelt** [comment]
Not sure why you'd need that. Just call `setBrightness` with your pre-squared value.
