### ISSUE TITLE
Rack v1: disabling infinite Rack for top and left

### ISSUE THREAD

**Issue by modlfo** [VCVRack/Rack#1265]
I'm hitting very often this problem. My trackpad has high resolution and when scrolling in the rack tends to move fast. Often when scrolling I'm moving (by accident) far from where my modules are. Since there are no coordinates or any visual aid, I spend quite some time trying to find where my patch start.

This problem is not that bad in v0.6 since I can always scroll to the top left until I hit the end.

Do you have any idea how improve this. One solution is to add an option to disable the infinite rack in all directions.

**Comment by MarcBoule** [comment]
Perhaps another idea would be to add a button to automatically position the screen at the location of the Code Audio module, since all patches should have them (I think?).

**Comment by Coirt** [comment]
Yes most definitely a user defined `0, 0` would be much needed in that case, I could settle with the core audio being the co-ordinates myself and just move that to the position I'd like to get jump back to (an icon button or key combo would be nice also) 

It is nice to be able to add a module to the top left further on in a patch without needing move a lot of modules. With v1 having massive performance improvements you can get a lot more modules in the rack.

Not sure if disabling infinite rack after the fact would help get back to where modules are without a co-ordinate system.

**Comment by gc3vcv** [comment]
@Coirt: +1 for user-defined origin. Should this become a feature request? A home position that defaults at the upper left of the start screen, snaps the screen back to that position on a toolbar or keypress, and which can be moved to reflect the current viewport (perhaps by Ctrl-clicking the toolbar button?) would do two good things with the same functionality: it would address @modlfo's problem (getting lost in rack space), and it would make it easier to usefully navigate the infinite rack. (If I'm dealing with a big, expanding patch, I might want to snap back to somewhere other than where I started, especially if I'm staying at a fairly high zoom level.)

@MarcBoule: I wonder if picking any individual module (even a very common one like Core Audio) might lead to confusion that outweighed the convenience. Also, it wouldn't have the side benefit of being a useful navigational feature (no one would want to move the chosen module around just to navigate, right?) As far as Core Audio goes, patches without it will probably be more common with Expert Sleepers now onboard, and it doesn't capture "home" in the sense of "where the patch starts." It always ends up on the right of at least my patches, and it would be odd if hitting the home button for the first time actually moved the viewport.

**Comment by infamedavid** [comment]
the solution that we have for this in the 3d software (we work with infinite canvas) if press certain key the software automatically make a "adaptive Zoom out"  that contain all the elements of your scene 

other solutions for 3d software is an adaptive zoom in to the   the selected object  and snap to the  0,0,0 coordinates  it is not possible here I think...

**Comment by AndrewBelt** [comment]
Fixed with 7b97c2e
