### ISSUE TITLE
Adding a field in the plugin.json to link to a module manual

### ISSUE THREAD

**Issue by MarcBoule** [VCVRack/Rack#1267]
Hi Andrew, this is a minor idea that I'm throwing out here since things are nearing stabilization in v1 (better now that later I guess). 

In `plugin.json`, it could be interesting to also have a `manualUrl` field in the modules themselves, which when present, would override the one in the top part of the plugin information. This way we could link to the relevant sections for each module when the manuals are large.

```
...
	"modules": [
		{
			"slug": "Tact",
			"name": "Tact",
			"description": "Tactile-inspired controller, dual channel",
			"manualUrl": "https://github.com/MarcBoule/ImpromptuModular#tact",
			"tags": ["Controller"]
		},
...
```

**Comment by MarcBoule** [comment]
Just want to ping this issue again to see if the format for `plugin.json` is finalized, or if there is still a chance this will make it in for v1. Myself and a few other devs think this would be quite useful for the users. Thanks for considering it. (@AndrewBelt)

**Comment by AndrewBelt** [comment]
Could be added later, when I start thinking about the new Plugin Manager.

**Comment by squinkylabs** [comment]
Yes, I actually do this in my 0.6 plugins (upcoming anyway). I put a "Manual" entry in my context menu, and that link goes to a page for that specific manual. It's a great feature. Would be great to make it easy for everyone to do that in V1.

**Comment by omricohenmusic** [comment]
I agree it will be great to have a link under the Plugin menu to the manual of a specific module when it's available. It works great with the links of the Squinky Labs collection, but the links are outside of the Plugin menu. It will make more sense I guess if everything will be under the Plugin menu.

**Comment by MarcBoule** [comment]
AB: "Developers may now use "manualUrl" for each module in your plugin manifest. However, they will not be used until Rack v2 or the upcoming VCV Library website."

Ref: https://community.vcvrack.com/t/rack-v1-development-blog/1149/534

**Comment by squinkylabs** [comment]
w00t!

**Comment by MarcBoule** [comment]
Closing the issue since it has been implemented and will be part of V2. More details here: 

https://community.vcvrack.com/t/call-for-plugin-developers-to-add-per-module-manual-urls-to-plugin-manifest/10981
