### ISSUE TITLE
Rack v1: single press of delete removes multiple modules

### ISSUE THREAD

**Issue by modlfo** [VCVRack/Rack#1268]
When pressing delete, sometimes multiple modules are removed. Seems to me that is because of the automatic recentering of the existing modules.

Here's how I trigger it. Place two modules next to each other. Shift them left in the window (so the most left module would end up in the place of the right one after deleting and recentering). Place the mouse over the right module and press delete. This would remove very fast both modules.

Here's a screenshot of the placement of my modules:

<img width="1439" alt="Screenshot 2019-05-04 at 08 47 15" src="https://user-images.githubusercontent.com/2001046/57174546-445b1a80-6e49-11e9-9d9f-74a41248b14a.png">

OS: Mac
Commit: d648860

**Comment by AndrewBelt** [comment]
Good catch, fixed by adding more math in f58fc44
