### ISSUE TITLE
[v1] why glfw extension glfwGetOpenedFilename() was added?

### ISSUE THREAD

**Issue by qno** [VCVRack/Rack#1269]
Hi Andrew,

I have a question regarding this addition to glew: https://github.com/AndrewBelt/glfw/commit/149195d26a55c9223215065a694ffa583a5340a9#diff-7a6c70f06dc23e69c5a9bfe9c3967e64R5631

There was the function `glfwGetOpenedFilename()` added, which is then used in the program main() function. But I don't understand what is this method doing at the end and how this works together? I see there is some kind of a delegate added for the glew Mac implementation that probably writes a string that can be obtained then by the `glfwGetOpenedFilename()`.

So my question is - where does this filename come from? Is this something that gets triggered if you click on a _vcv patch file_ in a file browser and then it just loads it?

And is it really necessary to add this to glew directly or can it be solved in a different way directly in Rack itself?

**Comment by AndrewBelt** [comment]
It's a horrible hack that wouldn't pass GLFW's contribution standards that allows Rack to know which file opened Rack by double-clicking on the file. It overrides
```m
- (BOOL)application:(NSApplication *)sender openFile:(NSString *)filename
```
which can only be done in `cocoa_init.m`.

**Comment by qno** [comment]
I see, thank you. So it is like I was thinking and basically it is a feature that at the end is just for user convenience? And it is not available on Windows and Linux? For me right now it is just important to know that it works also without this extension, as it is not available in v0.6.

**Comment by AndrewBelt** [comment]
The functionality can be implemented using `main(int argc, char *argv[])` on Windows and Linux, so it does not require modification to GLFW. Mac does things differently.

**Comment by qno** [comment]
I understand. Thank you for clarification.

**Comment by qno** [comment]
So probably we must wait until this feature is added in glew itself - https://github.com/glfw/glfw/issues/1024
