### ISSUE TITLE
Saving Screenshot when saving patch

### ISSUE THREAD

**Issue by nay-seven** [VCVRack/Rack#1275]
Maybe this could be an option when saving a patch to share patch idea or if a module for x reason crash Rack and you can't open it any more ?

**Comment by AndrewBelt** [comment]
You're asking to store the screenshot binary in the patch file? This breaks the simple JSON patch format so not sure if it's a good idea.

**Comment by nay-seven** [comment]
Hello, Not in the patch file, just to save a .jpg in the same folder and with the same name
so we can have 
 - myproject.vcv 
 - myproject.jpg

**Comment by AndrewBelt** [comment]
Well, first we'd need a way to *take* a screenshot of the patch. Taking a screenshot of the current screen is easy, but if you want the bounding box of the modules, that'd involve rendering everything in an offscreen framebuffer.

**Comment by nay-seven** [comment]
ok, i understand of course, was just an idea 
I think about when trying to help a user to recover a patch after Rack crash

**Comment by modlfo** [comment]
I see very limited use for this functionality and I believe some users will dislike the idea of having images laying around in the folders. However, the screenshot feature (manually triggered) could be useful, specially in the case where the patch is larger than the window size.

I'm closing this issue as a "won't fix". @nay-seven you can create a new feature request for the screenshot functionality if you want.
