### ISSUE TITLE
V1 INFO and WARN

### ISSUE THREAD

**Issue by baconpaul** [VCVRack/Rack#1276]
Hi

INFO is currently (7bd98943) defined as `logger::log( rack::logger::log::INFO, ...`

For a slightly annoying reason I'm not doing a blanket using namespace rack in my project so this required me, with the latest v1 update, to do a 

```
using namespace logger = rack::logger
```

in a couple of places. Just wondering if you could update the INFO (and WARN and so on) macros to have the fully namespace name in soon-to-be push?

Thank you!

**Comment by AndrewBelt** [comment]
If you don't have `using namespace rack;`, simply use `rack::INFO` etc.

**Comment by baconpaul** [comment]
Oh duh right. I did that with the APP macro and now I see the INFO macro setup I can do the same.

Sorry for the brain fart!
