### ISSUE TITLE
End of life for v0.6.x?

### ISSUE THREAD

**Issue by modlfo** [VCVRack/Rack#1277]
This questions was brought to me by a user and I don't have a full answer.

How long is v0.6.x of Rack gonna be supported?

Seems to be that people wants to stay at v0.6 for whatever reason. 

I understand that there are not gonna be more new features or bug fixes for Rack 0.6. Probably no updates for VCV plugins. Personally I'm not gonna release new versions for 0.6. But what if  a developer wants to release a 0.6.x version once Rack v1.0 is out?

How long the downloads for free and paid plugins for v0.6.x are gonna be available? For example, if someone purchases a paid plugin but wants the old version compatible with v0.6.x.

**Comment by AndrewBelt** [comment]
Rack v0.6 is already nearly unsupported with no updates for months. The server API will be switched off a couple weeks after v1 is released.
