### ISSUE TITLE
"right-click" "context-menu" on Knobs

### ISSUE THREAD

**Issue by Phal-anx** [VCVRack/Rack#1279]
Before I start to get ready for v1 I wanted to know if it is somehow possible to deactivate/forbid the context menu "right click" on certain knobs?
 
...e.g. the "octave selector" knob on my Treasure VCO doesnt need a context menu to enter a specific number...

**Comment by AndrewBelt** [comment]
No, users expect all knobs to serve context menu functions such as MIDI unmapping, future VST automation mapping, initialization, units, labels, descriptions, etc.
