### ISSUE TITLE
ESeries and Befaco plugins still won't compile

### ISSUE THREAD

**Issue by Strum** [VCVRack/Rack#128]
OS (if applicable): Win7 pro 64
Version (or "dev" if compiling from source): Dev.

Still seems to be having trouble finding minblep headers despite making the change from 

https://github.com/VCVRack/Rack/commit/a8f30ca3c751e4368733991c351634bb38caebf7

Here is the error text, similar error for the Eseries module.

build/src/EvenVCO.cpp.o:EvenVCO.cpp:(.rdata$.refptr._ZN4rack13minblep_16_32E[.refptr._ZN4rack13minblep_16_32E]+0x0): undefined reference to `rack::minblep_16_32'

**Comment by AndrewBelt** [comment]
Do a full rebuild `make clean`, `make` on the latest Rack repo.

**Comment by sbcook0** [comment]
First I tried building the two plug-in folders and got the same error. Reading about the fix, I realized the change was in the Rack itself.. Should have known from the reference to rack::minblep in the error message. It compiled OK for me a few hours ago on Win10.

**Comment by Strum** [comment]
Hadn't tried that, works now.

Cheers
