### ISSUE TITLE
default audio driver in V1 template (small nicety)

### ISSUE THREAD

**Issue by gc-c0** [VCVRack/Rack#1281]
I just ran V1 for the first time (woohoo!) and, thinking like a new user, I wonder if it might be worth assigning a default driver and output in Core Audio when the template loads up.

I know it's the first line in Notes, but new users reading from left to right will probably see Keyboard and QWERTY first (in the MIDI-CV display), and there may be a "huh?" moment if they start typing, see the beautiful scope and the port lights, but don't hear anything.

Most audio applications (in my experience) start with sound wired, and many don't provide visual feedback if the sound isn't going somewhere. 

The Notes language could be changed to something like:

1. Use the QWERTY and ZXCVB rows...
2. If necessary, change the audio device and/or driver in the AUDIO module.

I don't know if this should extend to all new instances of the Core Audio module, but it might be worth special-casing, at least for the default, factory-fresh template.

**Comment by AndrewBelt** [comment]
I can't reliably choose an audio driver automatically, so it's best that this decision is left to the user.
