### ISSUE TITLE
Suggestion to improve the "Demo patch instructions" text

### ISSUE THREAD

**Issue by gc-c0** [VCVRack/Rack#1282]
Right now, the keyboard item in the template patch notes reads:

Use the QWERTY and ZXCVB rows of your keyboard to generate MIDI notes, which are converted to 1V/oct and GATE signals.

This makes it sound as though the ASDF and numeric rows don't produce notes, when (of course) they produce accidentals. To be even more nit-picky, the patch is also relying on MIDI to produce triggers. 

What about something like the below (which fits in the same number of lines):

Use your keyboard to generate MIDI notes, which are converted  to 1V/oct, GATE, and RETRIG signals. (Z=C4, S=C#4, Q=C5).

**Comment by AndrewBelt** [comment]
The original makes more sense to me and is easier to read.
