### ISSUE TITLE
Module browser feature request: display description

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#1283]
Just a feature request. Show the plugin’s description somewhere - perhaps in a second line of the tool tip that is already showing the name (or hopefully somewhere better, like s

In V0.6 I just used long names that contained their own description, like "EV3: Triple VCO with even waveform.

Probably a feature like this will be coming, since the newer Fundamental plugins seem to have descriptions?

**Comment by AndrewBelt** [comment]
After thinking about this, I don't really like the idea of module descriptions. What are some examples of them? For say, all the Fundamental modules, or Audible Instruments.

**Comment by squinkylabs** [comment]
I'm not that familiar with the AI modules, and most of the fundamental's are pretty self explanatory.

A dev who seems to use the same scheme I do is Vult. as you can see from the attached image the "name" of every Vult module is actually "{name}: {description}". It's fine to carry that through to 1.0 - we can all leave the description blank, and move the description into the name like we have been doing in 0.6. It just seems that there is an opportunity to provide this information in a better way,

![image](https://user-images.githubusercontent.com/16314838/57978320-e3daea00-79bf-11e9-9e8e-38b69a478b8f.png)

**Comment by squinkylabs** [comment]
Not as well know, but for reference here is how I name mine to provide an embedded description:
![image](https://user-images.githubusercontent.com/16314838/57978336-6a8fc700-79c0-11e9-8040-2bf7c2e92d2f.png)

**Comment by modlfo** [comment]
In order to look fine, all developers would be required to provide a short description for all modules. I think it adds good visibility to the browser. Take as an example the way I showed them in my page.

<img width="766" alt="Screenshot 2019-05-19 at 09 31 14" src="https://user-images.githubusercontent.com/2001046/57978582-4c09ea00-7a19-11e9-93bf-0e9605f51b8f.png">

**Comment by AndrewBelt** [comment]
Okay, I see, so in both Fundamental and Audible Instruments, the names are "generic" like "VCO-1" or "Modal Synthesizer", so they wouldn't need descriptions, but if your names are more creative like "Nurage", then you'd definitely want descriptions.

**Comment by AndrewBelt** [comment]
Added with 59e4692.
You must rebuild the blendish dep with `git submodule update`, `rm dep/include/blendish.h`, and `make dep`.

**Comment by squinkylabs** [comment]
thanks!
