### ISSUE TITLE
FramebufferWidget does not support rotation/skew

### ISSUE THREAD

**Issue by korfuri** [VCVRack/Rack#1285]
Currently, FramebufferWidget doesn't support rotation and skew or similar transforms. On 0.6 it actually asserts so that using a TransformWidget whose matrix rotates/skews, the widget will crash Rack. On 1.0 it just warns and ignores the effect.

I wanted to use a rotation, not a skew, and still render the element in a framebuffer for performance reasons. I found that this could be achieved with a simple change to FramebufferWidget:

```
diff --git a/src/widgets/FramebufferWidget.cpp b/src/widgets/FramebufferWidget.cpp
index e51c048..d62dc54 100644
--- a/src/widgets/FramebufferWidget.cpp
+++ b/src/widgets/FramebufferWidget.cpp
@@ -39,11 +39,17 @@ void FramebufferWidget::draw(NVGcontext *vg) {
        // Get world transform
        float xform[6];
        nvgCurrentTransform(vg, xform);
-       // Skew and rotate is not supported
-       assert(fabsf(xform[1]) < 1e-6);
-       assert(fabsf(xform[2]) < 1e-6);
+       // Skew is not supported
+       assert(fabs(xform[2] + xform[1]) < 1e-6);
        Vec s = Vec(xform[0], xform[3]);
        Vec b = Vec(xform[4], xform[5]);
+       float theta = 0.0f;
+       if (fabs(xform[2]) > 1e-6 && fabs(xform[2]) > 1e-6) {
+         theta = asinf(xform[2]);
+         s = s.mult(1.0f / cosf(theta)); // Fix the scaling factors after removing the rotation
+       }
        Vec bi = b.floor();
        Vec bf = b.minus(bi);
 
@@ -97,6 +103,7 @@ void FramebufferWidget::draw(NVGcontext *vg) {
        nvgSave(vg);
        nvgResetTransform(vg);
        nvgTranslate(vg, bi.x, bi.y);
+       nvgRotate(vg, theta);
 
        nvgBeginPath(vg);
        nvgRect(vg, internal->box.pos.x, internal->box.pos.y, internal->box.size.x, internal->box.size.y);
```

This still does not support skewing, but I reckon it could be done in the same way: render an unrotated, unskewed version of the widget in the framebuffer, and apply the transformation to the framebuffer image instead. My solution above makes quite a few assumptions about what transforms may be used (mostly, that rotations are all around (0,0)), but I believe it should be possible to render a completely untransformed version of the widget in the framebuffer and apply all transforms when drawing the framebuffer image, which should still be fairly cheap on the GPU.

**Comment by AndrewBelt** [comment]
Currently `FramebufferWidget` is pixel-perfect in world coordinates, and your implementation breaks that.

**Comment by korfuri** [comment]
Thanks, hoisting the TranformWidget above the FramebufferWidget does work.
