### ISSUE TITLE
V1: When adding a new module by right click it does not place the module at the cursor position

### ISSUE THREAD

**Issue by sanderbaan** [VCVRack/Rack#1287]
When you want to add a module in V1 using right click it does not place the module at the cursor position but it places it in the row above which is pretty annoying.

Operating system(s):
Rack V1 dev ddf06a9, Mac OSX 10.14.4

**Comment by MarcBoule** [comment]
A neat trick is when clicking to select the module in the module browser, keep the mouse button pressed and then you will be able to drag it to the place you want.

**Comment by sanderbaan** [comment]
Nice I did not know that ;) still the workflow described about is what <1 rack users are used to

**Comment by sanderbaan** [comment]
Just did a git pull and this problem does not exist anymore, will close the issue
