### ISSUE TITLE
Loading a saved template re-arrages modules to upper left corner

### ISSUE THREAD

**Issue by sanderbaan** [VCVRack/Rack#1288]
When you have a patch where you add only a audio module and place it on the middle row to the right and add a midi map module next to then save it as a template. When you create a new patch it will place the audio and midi map module on the first row all the way to the left, they should placed at the same location when you saved the patch

Operating system(s):
OSX 10.14.4 Rack V1 dev669ace5

**Comment by AndrewBelt** [comment]
I could save scroll position (as I'm doing with zoom) in the settings.json file.

**Comment by AndrewBelt** [comment]
Deciding against this. It's fine the way it is, because most users would expect a newly opened "document" to appear on the top left.
