### ISSUE TITLE
V1: Modules load disabled

### ISSUE THREAD

**Issue by sanderbaan** [VCVRack/Rack#1290]
When loading modules sometimes they load up as disabled and enabling them sometimes crash Rack. For example on my MacbookPro15,2 loading the Befaco Spring Reverb loads up as disabled and when I enable it, Rack crashes. Attached screenshot and crashlog. This happens with other Fundamental and Befaco modules as well and also with our own plugins. We thought it was a issue with our plugins but it seems to be a issue with Rack.

Operating system(s):
Rackv1dev.669ace5, OSX 10.14.4
[Uploading Rack_2019-05-22-093336_ni-bln-07694.crash.z
<img width="377" alt="Screenshot 2019-05-22 at 09 33 30" src="https://user-images.githubusercontent.com/15910225/58155843-09444e00-7c75-11e9-851b-83265dfe467a.png">
ip…]()

**Comment by AndrewBelt** [comment]
Probably an ABI mismatch. Are the plugins built against your version of Rack?

**Comment by sanderbaan** [comment]
Build with latest dev and did a pull from Befaco and Fundamental and build those against latest dev. Can do a pull again and see if it persist.

**Comment by sanderbaan** [comment]
Oke after pull and rebuild the Befaco and Fundamentals load correctly, problem only remains with our modules so I will ask enzo to rebuild them with the latest dev. Guess we can close this one.

**Comment by AndrewBelt** [comment]
Okay, comment if persists.
