### ISSUE TITLE
SvgSwitch Range

### ISSUE THREAD

**Issue by martin-lueders** [VCVRack/Rack#1291]
I am using an SvgSwitch and my range is (-1,1).
However, the displayed SVGs are not reflecting this. For both -1 and 0 I see image 0), and for position 1 is see image 1.

In my previous version of the switch, based on
struct MLSVGSwitch : virtual ParamWidget, FramebufferWidget {..}
(written before SvgSwitch existed...
the positions -1,0,1 mapped correctly to the images 0,1,2.

Is the new way intended or a bug?

**Comment by martin-lueders** [comment]
I should add, it would be easy to change the code to accept the values 0,1,2 instead of -1,0,1. But that would break backward compatibility with patches saved under Rack 0.6.

**Comment by Coirt** [comment]
I think it shows the bit value false/true

**Comment by AndrewBelt** [comment]
Thanks, fixed in 8bca3de

**Comment by martin-lueders** [comment]
Thanks for the quick fix!!
