### ISSUE TITLE
CPU meters to scale opposite on positive zooms

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Rack#1294]
All skinny modules don't have enough room to show cpu meters.

![ScaleOppositeWay](https://user-images.githubusercontent.com/12150421/58341978-6c85da00-7e47-11e9-97e4-f004a1325875.JPG)

Possible fix would be to rescale the font to a smaller weight when zooming in. Which would not cut the end of the line off on the smaller modules. Another possible fix could be vertical meters for small modules (bottom right)

**Comment by AndrewBelt** [comment]
Fixed in 7f2db69
![2019-05-24-134814_111x123_scrot](https://user-images.githubusercontent.com/338179/58346974-98469700-7e2a-11e9-8dcf-a4697fe3dbb4.png)
