### ISSUE TITLE
midi controller feedback 

### ISSUE THREAD

**Issue by catronomix** [VCVRack/Rack#1295]
I would love to see supoort for sending midi feedback to controllers. Something like Midi-CC core module but with additional inputs that can send a CC value back to the selected midi device.
This way the leds on grid controllers etc can be controlled by vcv.
I guess this would be possible with a general midi-out module as well.

**Comment by AndrewBelt** [comment]
Why not just use MIDI-CC for device -> Rack and CV-CC for Rack -> device?

**Comment by nay-seven** [comment]
yes, works fine for a launchpad mini here
<img width="350" alt="image" src="https://user-images.githubusercontent.com/13808201/58348035-bc709b00-7e5f-11e9-9bd9-0d13469a8a1a.png">

**Comment by catronomix** [comment]
> Why not just use MIDI-CC for device -> Rack and CV-CC for Rack -> device?

@_@ whaaaat I didn't know that existed! I don't have this in VCV at all... is it part of a paid module set or something?

**Comment by catronomix** [comment]
Ooh I see now that's in v1! I only just compiled it for the first time. I notice though the Rack v1 installer uses the same automatic folder in Windows (under My Documents/Rack/Plugins), and by using the same slugs, v1 plugins overwrite v0.6 plugins, immediately breaking fundamental for 0.6 on installation.

**Comment by stoermelder** [comment]
Running multiple versions side-by-side:
https://community.vcvrack.com/t/howto-portable-and-or-parallel-0-6-2-and-v1-install-of-vcv-on-windows/3540/11

**Comment by modlfo** [comment]
Seems like this issue will be resolved by the MIDI output in v1. Closing the issue.
