### ISSUE TITLE
Setting exponent in config

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Rack#1296]
https://github.com/VCVRack/Rack/blob/v1/src/engine/ParamQuantity.cpp#L80

Is this line correct for setting exponents in the param config, seems log is used for exponent and exponent for log, or am I reading it wrong?

I'm attempting to set the hz value and it does not work out as the calculated value I made, unless I calculated wrong.

`configParam(EQFREQ_PARAM, 1.1726039399558574, 10.f, 3.3166247903554, "Freq", "Hz", 2, 20);	// .01375f`

(1.1726039399558574 * 1.1726039399558574) * 20 = 27.5hz 
but I get 45.084hz on the tooltip for the lowest value.

I'm using the values to set the center frequency of an eq and that works out to be correct when using pow
`std::pow(2.f, params[EQFREQ_PARAM].getValue() * 20);`

**Comment by AndrewBelt** [comment]
What is the formula your DSP uses to relate frequency to the EQFREQ param?

**Comment by Coirt** [comment]
Not sure that would be an issue as the config is unrelated to the DSP, config is just the display string isn't it?

I scale the values above up so 10.f will eventually be equal to 20kHz
v0.6x code: https://github.com/Coirt/Bark/blob/master/src/OneBand.cpp#L102

https://github.com/Coirt/Bark/blob/master/src/dependancies/filt/biquad.cpp#L108

**Comment by AndrewBelt** [comment]
I was offering to write the correct `configParam` arguments based on your frequency relationship, but honestly I can't interpret your DSP code.

It makes sense that you're getting 45.084hz because `2^1.1726039399558574 * 20 = 45.084`. What relationship are you trying to achieve?

**Comment by Coirt** [comment]
Aye, that makes two of us, just works! :blush:

2^1.1726039399558574 = 1.1726039399558574 * 1.1726039399558574 right?

**Comment by AndrewBelt** [comment]
No, exponential and power are different operations. There is no way to achieve a power relationship with ParamQuantity (unless you make a subclass and implement `getDisplayValue/setDisplayValue` yourself), but it sounds like you do actually want the exponential relationship, I think.

**Comment by Coirt** [comment]
News to me, haha. 

Not sure now.... must be exp had to change the min/max values but they corresponded in an earlier rack build. Will rethink and sort it cheers for the help!

**Comment by Coirt** [comment]
All sorted anyway, it was power I was looking for but I was calculating for exponential by mistake :+1:
