### ISSUE TITLE
V1: Two small requests to make typing and selecting modules quicker.

### ISSUE THREAD

**Issue by jeremywen** [VCVRack/Rack#1297]
# Request to Select all text when module browser reopened.
This way you can quickly hit enter in your rack, then start typing the next module you are looking for.  Currently the previously entered text stays there and you have to clear it before typing.  If the text was all selected then it would clear when you started typing.

# Request that hitting enter adds the first one found.
In v0.6 it was really quick to type a module name and hit enter.  I liked the hitting enter functionality.

**Comment by AndrewBelt** [comment]
The first was implemented in the past but broke because of a bug. Fixed in e270956.

I agree with the second feature request, but users will immediately begin asking for arrow keys to select modules with their keyboard, which clashes with the search field cursor.

**Comment by AndrewBelt** [comment]
Second feature added in 837efa6. We'll see how that works out.

**Comment by jeremywen** [comment]
Both are working great for me.  Thanks!
