### ISSUE TITLE
Jack compatibility under Linux

### ISSUE THREAD

**Issue by dilom** [VCVRack/Rack#130]
Is there a way to have Jack work with VCVRack at the moment? Any plans to support it in the future?

**Comment by AndrewBelt** [comment]
It looks like PortAudio supports Jack but since I don't use it myself I didn't include it in the builds. I could try to include it in the next v0.3.2 Linux build.

**Comment by dilom** [comment]
That would be great! I currently have to come up with "creative solutions" to record the output :) I am sure pretty much everybody that uses linux will find it incredibly useful.

**Comment by CaesuraMedia** [comment]
I found that if you have Ardour then start it first and then Rack - the audio output list contains a Jack Ardour selection which you can then select in the Audio inputs on Ardour - a nice way to record from Rack. Haven't dared to see if there is a MIDI connection too ... :)

**Comment by dromer** [comment]
I've gotten jack-audio to work by first starting jack, then selecting it + correct samplerate and block-size for the interface. However I only see 2 in/out puts in jack, even though there are 8 on the module. Would be great if all of these work (and expand as more modules are added .. ;) ).

Midi works by exporting alsa midi and using the midithrough port.

**Comment by AndrewBelt** [comment]
Reopen if there are any issues with Jack support.

**Comment by dilom** [comment]
@CaesuraMedia Ha! Yeah, I had to play with the settings to match Jack and it worked perfectly. I don't know why I overlooked it before. Thanks! 
It will be great to make the process more obvious, but still I am very happy that I can get this to play with all the other software I use!

**Comment by dromer** [comment]
@AndrewBelt well one issue is that the audio interface module does not expose all ports to jack.
