### ISSUE TITLE
V1: Poly Sum is clipping on high polyphony

### ISSUE THREAD

**Issue by zs-sz** [VCVRack/Rack#1301]
Today I had the time to try out some modules on full polyphony(16). it works like a charm(really good latency btw, way better than Live on the same card).  The only thing I found is this:  

If the note count goes above four the sum cant handle the peaks and starts clipping real badly. If I play two hand chords I can't turn the level more than the quarter mark. That of course solves the issue but single/double notes are getting too quiet. 

env: win10
modules: vult free, fundamental

[v1poly1.zip](https://github.com/VCVRack/Rack/files/3229639/v1poly1.zip)

**Comment by AndrewBelt** [comment]
That's why there's a volume knob on it. :)

**Comment by zs-sz** [comment]
well I thought I'd let you know, feel free to delete this if it isn't an issue. I can live with it thats for sure. as I said volume takes the top off but that makes single notes way too quiet... I'm not saying it should be a limiter or something just a bit more balanced.

**Comment by AndrewBelt** [comment]
If you play N notes, if will be N times louder than 1 note (for some definition of "louder"). I don't think there's a way around that logic.

**Comment by zs-sz** [comment]
I'm talking about hard digital clipping on 1/6th of the possible range of the pot. I never had any clipping on any modules when I built poly patches on individual VCOs, using fundamental mixers for example and I went up to 8-6 voices there as well.

**Comment by AndrewBelt** [comment]
I could use a log taper on the pot, if that's what you want.

**Comment by zs-sz** [comment]
well it would solve it visually for sure. couldn't the per channel input gain be lowered/limited or normalized based on the number of channels active? this might not be the sum's job(vca perhaps?) to do but there is no access to the gain otherwise. the dynamic range difference between one or the possible sixteen channels is immense. 

also as I said above, previously I never had this experience with these kind of setups: 

https://patchstorage.com/8xvoice-poly-template/
https://patchstorage.com/stereo-8-voice-ambient-drone/

The only other solution I can see later on is to use a compressor after the sum to try to bring up the single notes, once the upper limit is set by the sum's pot. But I'm also sure that this will come up once people start to properly grind on keyboards.

**Comment by AndrewBelt** [comment]
Gain dependence on number of channels is a bad idea, because it's impossible to predict the exact attenuation the user wants with N channels, and changing the number of channels would produce undesired level changes.

**Comment by zs-sz** [comment]
ok. I'm closing this. I just wanted to report it. It felt issue worthy :D
