### ISSUE TITLE
unable to log in on small resolutions

### ISSUE THREAD

**Issue by joelmartinez** [VCVRack/Rack#1302]
See https://github.com/VCVRack/Rack/issues/1021 for issue report standards and https://github.com/VCVRack/Rack/issues/730 before posting any code or terminal output.

Operating system(s):
Version of Rack if using official binary, or commit hash and branch if compiling from source:
All hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

I'm trying to use VCV on a surface Go device. its a rather small device, so even full screen I'm unable to access the password field as its off to the right and the top bar doesn't scroll.

![image](https://user-images.githubusercontent.com/90380/58676859-cabf2b00-8327-11e9-8258-44447f410bf3.png)

additionally, most scrolling interfaces are nigh unusable using touch. it would be fantastic if we could use vcv on the go. thanks!

**Comment by AndrewBelt** [comment]
Fixed in v1. As a workaround in Rack v0.6, change your screen resolution/scale in Windows settings, reopen Rack, log in, and reset the screen settings.

**Comment by joelmartinez** [comment]
@AndrewBelt ooh, awesome ... two questions:

1. Change my resolution/scale in windows settings **to what**? are you suggesting I should make the resolution higher? or make the scale smaller?
1. That's fair ... does your "Fixed in v1" answer also apply to the touch/scrolling? or should I open a separate issue?
