### ISSUE TITLE
Latest build fails in Debian

### ISSUE THREAD

**Issue by tank-trax** [VCVRack/Rack#1305]
Building on Debian 9.9 DVERSION=1.dev.4b3508b 

when trying to run Rack

```
Rack: src/plugin/Plugin.cpp:17: void rack::plugin::Plugin::addModel(rack::plugin::Model*): Assertion `isSlugValid(model->slug)' failed.
Aborted
```

Update: it was a plugin. will determine which one

**Comment by tank-trax** [comment]
DHE-Modules
Geodesics
ImpromptuModular

all produced the same error; if removed from plugins VCV Rack v1.dev.4b3508b loads

**Comment by AndrewBelt** [comment]
I didn't expect so many plugins to break the slug rules. https://vcvrack.com/manual/PluginDevelopmentTutorial.html#naming
I might have to remove the hard check, *sigh*. The following modules have incorrect slugs.
- Geodesics: `Blank-Panel Info` and `Blank-Panel Logo`
- DHE-Modules: I don't know why this is crashing because none of the modules break the slug rules.
- ImpromptuModular `Semi-Modular Synth`

**Comment by AndrewBelt** [comment]
Assuming that there are no more invalid slugs, I'd rather just have @MarcBoule change the above slugs.

**Comment by tank-trax** [comment]
I have only had the issue with these plugins and posted the issue on the respective plugin pages:

https://github.com/dhemery/DHE-Modules/issues/18
https://github.com/MarcBoule/Geodesics/issues/10

**Comment by MarcBoule** [comment]
No problem to change slugs, it will break patches, but the impact will be minor. I'll try to get to this within 24hr.

**Comment by tank-trax** [comment]
DHE-Modules used to have a v1 branch which is no longer available
I was able to build the master branch in the Rackv1 plugins folder

**Comment by dhemery** [comment]
When you publish a new SDK and corresponding dev Rack, I’ll build and test against that. As soon as I have a commit that works to my satisfaction, I will send you that specific commit. Are you expecting something beyond that from my repo.

**Comment by MarcBoule** [comment]
Fixed in both Geodesics and Impromptu, thanks for the head's-up guys.
(There's also Lindenberg that has some bad slugs
https://github.com/lindenbergresearch/LRTRack/blob/v1.0.0/plugin.json)

**Comment by tank-trax** [comment]
I can confirm that both Geodesics and Impromptu built and loaded successfully

**Comment by MarcBoule** [comment]
Just updated the slugs again a minute ago after seeing (https://github.com/MarcBoule/ImpromptuModular/issues/42), nice to see that no patches will be broken. Patrick L will surely appreciate :-)

**Comment by dhemery** [comment]
When you create issues in third-party plugin repos, please consider including the following information:
1. That you are a library maintainer.
2. If you are building against some Rack commit other than what’s in the SDK (which plugin developers may reasonably be focusing on), indicate why. For example, “We want to give you an early warning that your module is incompatible with an an upcoming change in Rack’s API/ABI.”
3. Which specific plugin commit you compiled and ran. Branch names are problematic.
4. All of the information you have readily at hand about the failure. I’m not asking for additional debugging effort—or any debugging effort—but whatever information you have readily at hand, such as stack traces for assertion failures.

This information would go a long way toward orienting me, and likely other developers, to the nature and significance of the problem.

I apologize for the tone of my earlier comment.

**Comment by tank-trax** [comment]
closing this issue as it is resolved
