### ISSUE TITLE
Format for slugs in v1

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#1306]
Revision 4b3508b introduced an `assert` for a valid **model** slug in `Plugin.cpp`.

Is the format for a valid **model** slug in `v1` defined anywhere?

So far `ImpromptuModular` and `modular80` have had "invalid" slugs defined in their `plugin.json` (spaces in the slug) and hit the assert. Those were valid slugs in `v0.6`. Which also means that patches will break.

Those two I found when testing the `v1` library branch, but there could be others.

**Comment by AndrewBelt** [comment]
Same as plugin slugs. https://vcvrack.com/manual/PluginDevelopmentTutorial.html#naming
Can your script print all the invalid slugs for ImpromptuModular and modular80?

**Comment by cschol** [comment]
Ah, sorry, I must have overlooked that section.

Yes, there is only 2: "Radio Music" (modular80) and "Semi-Modular Synth" (ImpromptuModular).
I load all migrated plugins in an Rack v1 instance, so I will catch them and can notify the authors.

As for pre-v1 patches, the normalizing sounds like a good idea, but that will only work if the `v1` slug is matching the normalized version and the author doesn't decide to change it to "Radio-Music" for the `v1` slug.

**Comment by AndrewBelt** [comment]
Okay, fixed both issues with 69c5ec8

**Comment by cschol** [comment]
OK. Upon further inspection there are actually more issues than just the 2. I will notify the developers.
