### ISSUE TITLE
V1: Audio-16 maxChannels still set to 8

### ISSUE THREAD

**Issue by SteveElbows** [VCVRack/Rack#1307]
OS: MacOS Mojave 10.14.4
Rack Version: 1.dev.4b3508b
Audio Interface: MOTU 828ES

When using Audio 16 module, list of audio devices is still splitting devices into batches of 8 inputs/outputs, not 16. And only half the green lights come on.

I checked the code and it looks like maxChannels is set to 8 in include/audio.hpp and there is no code anywhere else to ever change this value.

I manually edited the JSON for that module in my patch file, to change maxChannels to 16, and then things start to work as expected, at least on the UI side of things (I've not actually tried all the ports yet).

**Comment by AndrewBelt** [comment]
Thanks, does f678e52 fix it?

**Comment by SteveElbows** [comment]
Yes thanks, thats sorted it!
