### ISSUE TITLE
Implement functionality to do a smooth audio transition from one patch file to other

### ISSUE THREAD

**Issue by catronomix** [VCVRack/Rack#1308]
When loading a different patch, for a moment the audio is stopped and then restarted with the next patch. It would be cool if VCV could check for any audio/midi modules in a patch to see if identical devices are selected, then if the patches are compatible, kind of internally load the new patch first without unloading the running one, then transfering the audio and midi devices for a soft and transparent takeover.
Is this something to hope for? 
Combined with some module that can be triggered to load a certain patch. This would allow VCV to perform live with different patches without having glitches or silence inbetween.

**Comment by AndrewBelt** [comment]
I'm rejecting your feature request as you've stated it.
It could be possible to load two subpatches and use a crossfader between them, but it is up to you how you want to do it.
