### ISSUE TITLE
[Feature Request] Allow different colors on parameter mapping indicator

### ISSUE THREAD

**Issue by stoermelder** [VCVRack/Rack#1309]
Currently the circled mapping indicator has a hardcoded color. It would we helpful to be able to different colors for different kinds of mapping.

Forum discussion:
https://community.vcvrack.com/t/module-cv-map-for-cv-controlling-any-knob-slider-or-switch/1914/19

Reference in code:
https://github.com/VCVRack/Rack/blob/69c5ec8983ead07475752cbadba82373636a7a21/src/app/ParamWidget.cpp#L131

**Comment by AndrewBelt** [comment]
What is a "kind" of mapping? Currently there is only one, the existence of a `ParamHandle` present in the Engine.

**Comment by stoermelder** [comment]
Ok, when I said "different kinds of mapping" I actually meant "different interpretation of an existing `ParamHandle`". Currently Core's MIDI-MAP module sets parameters by incoming MIDI. I`ve done two simple modules, one that sets parameters by incoming CV, one that reads parameters and outputs CV.
It would be helpful if the user can distinguish these mappings by the indicator, e.g. MIDI-write = purple, CV-write = red, CV-read = yellow.

**Comment by AndrewBelt** [comment]
Didn't think I'd want to do this, but I went ahead and added `text` (which displays after "Unmap" in the parameter context menu) and `color` (which sets the parameter dot color) to `ParamHandle`. You *must* set `color` of all your `ParamHandle`s, but `text` is optional.

**Comment by AndrewBelt** [comment]
I went ahead and changed MIDI-Map's color to `nvgRGB(0xff, 0xff, 0x40)`.

For consistent color, I would highly recommend using a hue rotation of this color. Don't deviate from the saturation or value. So I'd recommend using `nvgRGB(0x40, 0xff, 0xff)` or `nvgRGB(0xff, 0x40, 0xff)`.

**Comment by Coirt** [comment]
A welcome change to see for the different colours. :+1: 

@AndrewBelt 
Not too sure I like the `nvgRect` on the indicator `nvgCircle` was way more sophisticated, imo.

**Comment by AndrewBelt** [comment]
@Coirt I can't tell a difference between LEDs and ParamHandle icons.

**Comment by Coirt** [comment]
@AndrewBelt Perhaps a heavier stroke width?
