### ISSUE TITLE
Alsa underruns 

### ISSUE THREAD

**Issue by Malifick** [VCVRack/Rack#131]
OS (if applicable): Manjaro (Arch)
Version (or "dev" if compiling from source):Binary
Expression 'err' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3350
Expression 'ContinuePoll( self, StreamDirection_In, &pollTimeout, &pollCapture )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3891
Expression 'PaAlsaStream_WaitForFrames( stream, &framesAvail, &xrun )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 4269 

wondering if I should use jack or pulseaudio instead?

**Comment by Malifick** [comment]
Might have fixed this by making the block size 1024 , will let you know

**Comment by Malifick** [comment]
Unfortunately   I can't figure it out, block size doesn't seem to change the buffer underruns

**Comment by maricn** [comment]
Ditto.

My console says:
```
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
Expression 'err' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3350
Expression 'ContinuePoll( self, StreamDirection_In, &pollTimeout, &pollCapture )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3891
Expression 'PaAlsaStream_WaitForFrames( stream, &framesAvail, &xrun )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 4269
^CMakefile:49: recipe for target 'run' failed
make: *** [run] Interrupt
```
It's been going on ea47c915 build, v0.4.0, and current master.
OS: Debian jessie.
aplay: version 1.0.28 by Jaroslav Kysela <perex@perex.cz>
Advanced Linux Sound Architecture Driver Version k3.16.0-4-amd64.

**Comment by Malifick** [comment]
I still get them but keep going till it stops me

**Comment by modlfo** [comment]
Closing this issue. Audio related problems in Linux will be covered in #1317
