### ISSUE TITLE
Dynamically load plugin's .svg

### ISSUE THREAD

**Issue by VegaDeftwing** [VCVRack/Rack#1311]
It'd be great if just like how custom face plates can be distributed for real modules the .svg files used by plugins dynamically loaded instead of requiring recompilation-- even if they're only loaded at Rack's launch time and a restart is required.

**Comment by AndrewBelt** [comment]
SVGs files are already loaded from files, not baked into the binary.

**Comment by VegaDeftwing** [comment]
hmm, let me play with it a bit more then. Trying on Arch Linux and changing the svgs is still loading the old ones. I'll update this issue in a bit after I experiment more across platforms

**Comment by VegaDeftwing** [comment]
Checked in Windows, and yeah, the SVGs change upon re-launching rack, so I imagine rack is caching the SVGs somewhere on linux, but I'm not sure where

**Comment by AndrewBelt** [comment]
You're probably changing the wrong SVG file.

**Comment by VegaDeftwing** [comment]
Alright, so some more poking around and I've found some modules will update but most don't. For example, anything from Southpole or Valley I can update just fine, but Fundamental or ZZC have no change. I'm editing the files in `~/.Rack/plugins/[plugin-name]/res/[compont/panel].svg` or `~/.Rack/plugins/[plugin-name]/res/[sub-folder]/[component/panel].svg and there don't appear to be any other alternative places the panels I'm editing could be stored.

**Comment by VegaDeftwing** [comment]
I figured it out, it wasn't that I wasn't editing the .svg it was that I was trying to edit with some of the unsupported svg properties. Sorry for wasting your time

**Comment by VegaDeftwing** [comment]
I realize you already closed the issue, but upon working on a few modules I've realized that the svgs provided in this repo that are used by the core modules, fundamental, and many 3rd party modules are baked in. Having a way to override these easily per plugin but fallback to these core/fundamental svgs if they don't exist would be great and probably be easier for plugin development as well.

**Comment by AndrewBelt** [comment]
Maybe you're referring to Component Library graphics (by Grayscale) provided in `<Rack user dir>/res/ComponentLibrary`?

**Comment by VegaDeftwing** [comment]
Yeah, from what I can tell those do get compiled into the Rack binary, correct?

**Comment by AndrewBelt** [comment]
No, they're in the directory stated above.

**Comment by VegaDeftwing** [comment]
oohhhhh you mean the actual install folder and not the .Rack folder. My bad. I still think having that per-plugin override ability would be a nice feature though. Thank you so much!
