### ISSUE TITLE
V1: isConnected() method of Port is wrong in some cases

### ISSUE THREAD

**Issue by zezic** [VCVRack/Rack#1312]
Operating system(s): Ubuntu 18.04
Version of Rack if using official binary, or commit hash and branch if compiling from source: cc9e0337e0a25de626591295fc16cb66ecf00053
All hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): probably, nothing is relevant

After adding a module from module browser the `isConnected()` method of any of its ports return `true`, but actually cables are not connected yet. The same happens if I load a patch without cables in it.
If I plug or unplug a cable into/from any port of just added or any other module in rack then `isConnected()` starts to work as expected. Also it works as expected if loaded patch has some cables in it.

_P.S.:
No one asked me for research and I'm not sure that I know the internals and architectural roadmap of Rack v1 good enough to do full analysis, but if it will help someone I guess that it is because freshly added module does not receive a call of `Port_setDisconnected` over each of its ports (or `Engine_updateConnected` is not called) or maybe even the `channels` property of `Port` struct should be initialized with `0` by default._

**Comment by AndrewBelt** [comment]
Nice catch, setting channels to 0 was the solution. fe18110
