### ISSUE TITLE
adding a new KEY to the plugin.json for "in development" modules

### ISSUE THREAD

**Issue by antoniotuzzi** [VCVRack/Rack#1315]
With last release, commit `3f513e1adb877e428531717a1a107441232d7b53`
at run time, VCV Rack doesn't load anymore a `plugin.lib` that is  misaligned with `plugin.json`

Till yesterday there was only a warning about **SLUG** **pincopallo** representing the module **pincopallo** not present in the `plugin.lib`

As I (but probably other developers too) have many modules that are in development and are present only in my debug version, 
1)
I 'd like to have the "WARNING" mode back

or at least 

2)
we add a new field to the single plugin entry in the `plugin.json`

for example
```                
            {
                "slug": "pincopallo",
                "development": "true",
                "name": "annoying module",
                "description": "annoying module with some features",
                "tags": ["VCO"]
            }
```

of course, the `Rack` app should be mute about it in this case (no warning)
and should load the plugin.lib not treating it as an error

**Comment by AndrewBelt** [comment]
Added in 5bba5e9 with `"disabled"` property.

**Comment by antoniotuzzi** [comment]
grazie mille ! :)
