### ISSUE TITLE
High cpu usage when enabling multi-threading in v1

### ISSUE THREAD

**Issue by stoermelder** [VCVRack/Rack#1316]
I'm noticing very high cpu usage when enabling multi-threading. To reproduce just start Rack and remove all modules. With a single thread everything is normal, when enabling two or more threads cpu increases while no real load is present. 100% usage when setting to the maximum.
I'm not sure but I think this problem was introduced in the last 2-4 weeks.

Operating system(s):  Windows 10
Rack v1 commit ca5e49637500094c67c8098f828502ee1fb45f4d

**Comment by modlfo** [comment]
Hi @stoermelder 

This problem has been explained before (I can find the issue). Enabling multithreading will consume more CPU (not less) but it will allow you to run more modules. For more detailed information you can check #195 or https://community.vcvrack.com/t/a-multithread-performance-experiment-with-rack-v1dev-the-0-6-2c-rcomian-fork-experiment2/1683

Can you check if you have this behaviour with an old build? If you find the same behavior please close the issue.

**Comment by stoermelder** [comment]
Thanks Leonardo, you're right, I checked a build from February and the behaviour is the same. 
I still consider this a problem that sould be addressed in some way, because once Rack v1 is released users will complain about that and create more issues.

**Comment by modlfo** [comment]
I think that you are seeing that behavior because you don't have a Core Audio module with a sound card selected. Can you repeat the experiment just with a functioning Core Audio.

When there's no Audio interface Rack can behave strange.

**Comment by stoermelder** [comment]
Didn't think about that... Thanks for your help, solved!
