### ISSUE TITLE
Sharable patches

### ISSUE THREAD

**Issue by mlinton** [VCVRack/Rack#1320]
This is probably way too late to be mentioning this type of feature.

As a beginning to modular synths it would be great if like the library of plugins there was also a sharable library of patches.  This would allow people to easily open a bass synth patch, or a kick-drum patch, or a Prog-trance patch with four voices.

This could also be ranked and rated by the community making it popular for people to share their best and most creative work.

**Comment by AndrewBelt** [comment]
- https://patchstorage.com/platform/vcv-rack/
- https://community.vcvrack.com/c/plugins
- https://www.facebook.com/groups/vcvrack/

are perfectly good places to share patches, no need for a centralized solution.
