### ISSUE TITLE
Should Rack allow downgrades?

### ISSUE THREAD

**Issue by SteveRussell33** [VCVRack/Rack#1322]
### Details
I had compiled a dist build of https://github.com/stoermelder/vcvrack-packone which is @ v1.0.1 as of the latest commit as per plugin.json. The VCV Library currently has a release build of v1.0.0. https://vcvrack.com/plugins.html#PackOne
Starting Rack shows that I have an update available: https://drive.google.com/open?id=1EKBsfr3FLq3KWdUJTrl9_X8-26jU_deW

NB: I have not tested this with other brands

Operating system: Win 10
Rack version: v1.dev.6b6c852

### Expected behavior
Only allow/show available upgrade(s)

### Actual behavior
Shows that currently I could downgrade this brand

**Comment by AndrewBelt** [comment]
Currently Rack does not define an order for version numbers. Adding a plugin to your VCV account makes Rack sync to Library's version. If you do not wish to sync, simply remove it from your account.
