### ISSUE TITLE
Can't disable smooth after Widget has been created

### ISSUE THREAD

**Issue by Nowhk** [VCVRack/Rack#1324]
Operating system(s): Windows 10 Professional, 64bit, MinGW (gcc + gdb) and VSCode.
Rack-SDK, 0.6.2c

I want to disable smooth for some knobs I have.

If I do `smooth = false;` within the ctor of my Knob, it works. 
But since I need to do it only for some knobs, I did this:

```
addParam(module->pKnobBPM = ParamWidget::create<NWKKnob>(Vec(padLeft + padLeftOffset1 + WIDTH_PORT + OFFSET_X_PORT_KNOB, row + distY * 0), module, Seqwhk::BPM_PARAM, 0.0, 1.0, rescale(60.0, 10.0, 999.0, 0.0, 1.0)));
module->pKnobBPM->smooth = false;
```
The smooth become correctly disabled. 
But once I reload the patch, it doesn't reload the stored value for the knobs. 
It reset the "dsp" `value` to default, while the GUI knob position is in the correct position of my prev stored value. Once I manually move it, the `value` of the knob take the correct value.

So if default if 0.5, I move it to 1.0, and I reload the patch, the real value is loaded as 0.5, while the knob is fully 1.0. Once I move a bit the knob, it takes the value of the knob position.

Bug? How can you disable smooth without do it in the ctor?
It seems a deserialization problem.

**Comment by AndrewBelt** [comment]
I believe you can do this with Rack v1's `Knob`. Just set `knob->smooth` at any time.
