### ISSUE TITLE
Enable smaller minimum window size

### ISSUE THREAD

**Issue by catronomix** [VCVRack/Rack#1325]
### Summary
Please don't constrain the minimum window size, or use a much smaller constraint.

### Motivation
I wanted to place VCV below another program on my desktop (Win 10) and have 1 row zoomed out a lot with all the devices next to eachother, then I found out I cant make my VCV window any smaller than about 800x600px :/

**Comment by AndrewBelt** [comment]
Fixed in e4c5f81.
