### ISSUE TITLE
For what is objcopy in compile.mk used?

### ISSUE THREAD

**Issue by qno** [VCVRack/Rack#1327]
Hello @AndrewBelt,

in  https://github.com/VCVRack/Rack/blob/b4bd09a2eb0cf0977cbc802b7711c85669acee26/compile.mk#L78

As far as I have figured this out, this is used to create object files to compile the Befaco SpringReverb plugin (embed the content of SpringReverbIR.pcm into binary object) and maybe other plugins that I'm not aware of. But as I'm not used to the Make "Build System" in general, I don't know if this objcopy directive is used for all objects that are getting compiled?

I just ask this, as you may know or not know from my post at https://community.vcvrack.com/t/build-vcvrack-with-conan-and-cmake-add-ci/3720 what I'm playing with, as I'm currently in the progress to adapt the Befaco plugin to be able to be build with CMake. But mimic this objcopy approach with CMake is very ugly, so I decided to create this object files with assembler (NASM), which is basically supported out of the box by CMake and it also then just works also for MacOS (not tested yet). 
I did it as it is described here - https://csl.name/post/embedding-binary-data and it worked out of the box then with the SpringReverb plugin.

**Comment by AndrewBelt** [comment]
The target that line is in is only used for files added to the `BINARIES` variable. Any binary data can be compiled into the binary and then accessed in code with the BINARY BINARY_START BINARY_END BINARY_SIZE macros.

**Comment by qno** [comment]
Thank you for clarifying.
