### ISSUE TITLE
multiple Audio-8 instances not working with Dante Virtual Soundcard and ASIO

### ISSUE THREAD

**Issue by FrankBuss** [VCVRack/Rack#1329]
### Details

Operating system: Windows 10
Rack version: 1.dev.b4bd09a
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): Dante Virtual Soundcard, over USB ethernet card

### Expected behavior
When I use the attached patch, it works. I want to instantiate a second Audio-8 instance.

### Actual behavior
As soon as I add a second Audio-8 instance, the first audio instance isn't working anymore, no audio data is output anymore. And when I try to close the application, it hangs. I have to hit the close button again and then the Windows "program is not responding" dialog comes and I have to terminate the application. The last lines in the log file:

```
[36.151 info src/audio.cpp:266] Opening audio RtAudio device 0 with 8 in 8 out
[36.254 info src/audio.cpp:279] Starting RtAudio stream 0
[44.158 info src/main.cpp:176] Stopped window
[44.158 info src/main.cpp:178] Stopping engine
[44.159 info src/patch.cpp:77] Saving patch C:\Users\frank\DOCUME~1/Rack/autosave-v1.vcv
[44.162 info src/main.cpp:185] Destroying app
[44.162 info src/audio.cpp:302] Stopping RtAudio stream 0
```

The LEDs on the first instance looks strange as well, all LEDs are off. Attached is a screenshot after adding the second instance.

When using only one Audio-8 instance, I can select all 4 sound cards and can send and receive audio to all 32 channels, but only 8 at a time. I want to use all 32 input and output channels in parallel.

PS: Same behavior in Rack V0.6.

[test.vcv.zip](https://github.com/VCVRack/Rack/files/3286878/test.vcv.zip)
![rack](https://user-images.githubusercontent.com/1707296/59444894-f39ef000-8dfe-11e9-8703-ec2a951667bf.png)

**Comment by AndrewBelt** [comment]
Use AUDIO-16, this is why it was designed.

**Comment by FrankBuss** [comment]
I have 32 input channels and 32 output channels (Dante supports up to 512 input/output channels over one dedicated gigabit ethernet port). This would need 2 instances of AUDIO-16. I guess it is the same as AUDIO-8, just for 16 channels? This would mean that it wouldn't work either.

**Comment by AndrewBelt** [comment]
Correct, you'll only be able to use 16/16 channels.

**Comment by FrankBuss** [comment]
Ok, but if it is not possible to instantiate 2 instances of the Audio module, then this should be not allowed, or this bug report should remain open until the bug is fixed.
