### ISSUE TITLE
Version is reported incorrectly. 

### ISSUE THREAD

**Issue by Euphorbium** [VCVRack/Rack#133]
OS: Mac
Version: 0.3.1 

If I go to Rack menu, about rack, it shows `0.0 (0.0.0)` but the version is correct on the app title.

**Comment by AndrewBelt** [comment]
Fixed in 90b3cc251c173bca8d1b393712743fc4b9fea281 by simply removing the version from Info.plist, so that nothing is displayed.

Resulted in a funny moment on SonicTalk
https://youtu.be/7jyAaQ8rtnk?t=2503
