### ISSUE TITLE
SS-2 code error (ports 2-4 don't work)

### ISSUE THREAD

**Issue by LaunchControlVCV** [VCVRack/Rack#1334]
The initialisation of click filters only does the first input, since SS-2 only has one output. At present only the first input "works".

for (int i = 0; i < OUTPUTS; i++) {
	clickFilters[i].rise = 400.f; // Hz
	clickFilters[i].fall = 400.f; // Hz
}

It should be as it was in 0.6
for (int i = 0; i < 4; i++) {
	clickFilters[i].rise = 400.f; // Hz
	clickFilters[i].fall = 400.f; // Hz
}

**Comment by AndrewBelt** [comment]
Thanks, fixed in 40fb17b
