### ISSUE TITLE
V1: Midi CV reading wrong byte for channel aftertouch value

### ISSUE THREAD

**Issue by SteveElbows** [VCVRack/Rack#1336]
### Details
Operating system: MacOS Mojave 10.14.5
Rack version: 1.dev.1ea9afc
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): Arturia Keystep Midi controller, various MPE controllers.

### Expected behavior
MIDI-CV AFT port value should change when midi channel aftertouch message received on the correct midi device/channel.

### Actual behavior
MIDI-CV AFT port value never changes when receiving channel aftertouch messages (but does work when receiving poly aftertouch messages).

The cause of this bug is that lines 183 and 188 of MIDI_CV.cpp are looking at the wrong midi message byte. They are looking for the value using getValue(), but as per the official midi spec, channel aftertouch messages send the aftertouch value as the first data byte, not the 2nd data byte. Changing those lines to use msg.getNote() instead fixes the problem. 

I originally discovered this issue when exploring stuff to do with MPE that I spoke about some time ago on the forum. But the channel aftertouch issue was nothing to do with MPE in particular, or the other stuff I was talking about in that forum thread. Just to be sure, I waited till I got a standard midi controller, the Arturia KeyStep, before formally filing this bug report.

I do not believe this issue affects the reently refactored code for sending midi from VCV, since that seems to be sending the value for channel aftertouch in the first data byte, as it should.

**Comment by AndrewBelt** [comment]
Does 2ae4a93 fix it?

**Comment by SteveElbows** [comment]
Yes it does, thanks as always!
