### ISSUE TITLE
Midi Map module crashes entire app if MIDI device is already in use

### ISSUE THREAD

**Issue by ciwolsey** [VCVRack/Rack#1337]
Present in commit: b4bd09a

I can reproduce it by loading Ableton Live, letting it initialised my Push 2, then start VCVRack and select the device in the Midi Map module.

Also the issue number for this issue is highly amusing :)

**Comment by AndrewBelt** [comment]
Nice issue number.

I can't reproduce this with my various MIDI controllers, but I don't have a Push 2. Let me know if you can debug with GDB/LLDB and can post a stack trace.

**Comment by ciwolsey** [comment]
Sorry I'm not very experienced with C++ or debugging it but I could get GDB to tell me this:
https://i.imgur.com/Wc9kX8p.png
I can only reproduce it using by Ableton Live (which is setup to use the push) and then trying to use the Push in VCV also. I've tried to reproduce it using a virtual midi port and Rack handles that fine so I guess it's something specific to the Push?
