### ISSUE TITLE
Add brand names to "Library" sub menu

### ISSUE THREAD

**Issue by stoermelder** [VCVRack/Rack#1340]
### Summary

Add brand name to menu items in "Library" when updates are available.

### Motivation

The new update manager in v1 allows to update single updates shown by their plugin name. Plugin names aren't that relevant in Rack and its brand or developer is not always obvious, e.g. "Fundamental" (though this is not updated through Library) . Known most are module names and brands, like in module browser.

**Comment by AndrewBelt** [comment]
How would this be presented? "Vult Modules Vult" looks dumb, and using just "Vult" isn't enough information.

**Comment by stoermelder** [comment]
For plugins already inluding the brand it looks dumb indeed. Maybe 
> "Vult Modules" by Vult

**Comment by AndrewBelt** [comment]
"by" implies author. Befaco isn't the author or the "Befaco"-branded plugins.

**Comment by stoermelder** [comment]
Hm, you're right. Maybe it's best to leave it how it is :-)
