### ISSUE TITLE
V1: zlib dependency wont build on mac, worked yesterday

### ISSUE THREAD

**Issue by SteveElbows** [VCVRack/Rack#1342]
### Details
Operating system: MacOS Mojave 10.14.5
Rack version: v1.0  4516856

### Expected behavior
make dep builds everything without errors
### Actual behavior
this error shows up and built halts:

zlib-1.2.11.tar.gz: OK
tar xf zlib-1.2.11.tar.gz
cd zlib-1.2.11 && ./configure --prefix="/Users/steve/vcv/Rack/dep" --host=x86_64-apple-darwin18.6.0
unknown option: --host=x86_64-apple-darwin18.6.0
./configure --help for help
** ./configure aborting.
make[1]: *** [lib/libz.a] Error 1
make: *** [dep] Error 2

**Comment by AndrewBelt** [comment]
Thanks, fixed in 8c89a50e22dc9621ab0aacaab61d8f83c7d5c1d0
