### ISSUE TITLE
QWERTY keyboard disappears as device in MIDI-CV

### ISSUE THREAD

**Issue by millxing** [VCVRack/Rack#1343]
Operating system: MacOS Mojave
2019 15" MacBookPro
Rack version: v1.Dev.b4bd09a

When I first ran V1, a default patch (template.vcv) was loaded and QWERTY keyboard was selected as the MIDI device in MIDI-CV.

But every time I load MIDI-CV into a new patch, QWERTY keyboard does not come up as a MIDI device option.  I went back to that original template.vcv patch and saved a preset for the module (which correctly showed QWERTY as a device).Loading that preset gets access to the QWERTY keyboard in other instances of MIDI-CV. But otherwise, I can't figure out how to access the QWERTY keyboard in a new instance of MIDI-CV.

**Comment by SteveElbows** [comment]
Are you changing the first option in that module so that it says 'Computer keyboard' (as opposed to, for example, Core MIDI) ?

**Comment by AndrewBelt** [comment]
Yes, select the Computer Keyboard driver.
