### ISSUE TITLE
Memory leak in MIDI-MAP

### ISSUE THREAD

**Issue by stoermelder** [VCVRack/Rack#1344]
### Details
Call `json_array_append` should be `json_array_append_new`.
https://github.com/VCVRack/Rack/blob/cc9e0337e0a25de626591295fc16cb66ecf00053/src/Core/MIDI_Map.cpp#L216

### Expected behavior
Allocated memory is freed.

### Actual behavior
Leaking memory on each autosave.

**Comment by AndrewBelt** [comment]
Thanks, fixed in 5919c4a
