### ISSUE TITLE
Rack prompts to clear patch in empty Rack

### ISSUE THREAD

**Issue by SteveRussell33** [VCVRack/Rack#1348]
### Details

Operating system: Win 10
Rack version: v1.dev.2ae4a93

### Expected behavior
No prompt using Ctrl+O or File->Open menu option in empty Rack; should open file picker dialog straight away.
![EmptyRack](https://user-images.githubusercontent.com/41975381/59663606-497cea80-91a7-11e9-939e-4fdfc9f243a1.png)

### Actual behavior
Rack prompts to clear patch if Rack is empty.

**Comment by AndrewBelt** [comment]
Fixed in f260e48
