### ISSUE TITLE
Revert menu option has no rightText

### ISSUE THREAD

**Issue by SteveRussell33** [VCVRack/Rack#1349]
### Details

Operating system: Win 10
Rack version: v1.dev.2ae4a93

### Expected behavior
Revert menu item to have modifier key text "Ctrl+Shift+O"

### Actual behavior
Revert menu item does not have modifier key text
![RevertItem](https://user-images.githubusercontent.com/41975381/59680548-8063f800-91c9-11e9-9800-181f24653be7.png)

**Comment by AndrewBelt** [comment]
Thanks, fixed in 5f35e78
