### ISSUE TITLE
Seq3 gate outs not working in Linux build

### ISSUE THREAD

**Issue by hippymulehead** [VCVRack/Rack#135]
OS (if applicable): Ubuntu Budgie 17.10
Version (or "dev" if compiling from source): 0.3.1

Gate out on Seq3 is not sending gates.  Also the step out for the gates is also not working.  Great job on getting a Linux build working !

**Comment by AndrewBelt** [comment]
You have to click on the LED buttons to enable each gate. Have you done that?

**Comment by antoniograzioli** [comment]
it works indeed, just click the gate buttons to enable the gates....
