### ISSUE TITLE
For modules with multiple panel themes, it would be nice if module browser reflected choice

### ISSUE THREAD

**Issue by almostEric** [VCVRack/Rack#1351]
<--
To request a feature, fill out the form below.
Use a descriptive title that best explains the feature request in one sentence.
-->

### Summary
This is admittedly a nice to have, and not sure how easy it would be to implement, but the whole point of the current module browser is to give visual feedback of the modules you can use. Right now if you choose a dark theme (I do believe only Marc Boule's Impromptu/Geodisic modules current offer this), but it would be nice if Module Browser used the same theme

What is your proposal for a new feature in Rack? Are there any alternative designs?
Module Browser respect theme choice

### Motivation
Right not for these modules there is a disconnect between what they look like on your rack and how they look in the browser

Why should this feature be considered?

**Comment by AndrewBelt** [comment]
Module skins are not supported yet. This feature request depends on that feature.

**Comment by AndrewBelt** [comment]
Echoing what I said above, there is no "Rack API" way to have multiple panel themes. So any method of offering switchable panels in your plugin is outside of Rack's control, and therefore it is up to your specific implementation whether the theme appears in the Module Browser.
