### ISSUE TITLE
make debug on OSX uses the wrong command

### ISSUE THREAD

**Issue by antoniotuzzi** [VCVRack/Rack#1353]
### Details

Operating system: OSX 10 13
Rack version: v1

when I try `make debug` from the CLI is trying to execute:

```
make debug
lldb --args ./Rack -d
lldb: unrecognized option `--args'
```

should be 
```
lldb -- ./Rack -d
```

(notice the no `args`)

**Comment by AndrewBelt** [comment]
Thanks, fixed in f813bff
