### ISSUE TITLE
CV Inputs for Cable Tension and Opacity

### ISSUE THREAD

**Issue by dijikul** [VCVRack/Rack#1354]
### Summary

The motivation for this feature is to add eye-candy for the sake of aesthetics.  This feature achieves a more-pleasant visual experience for anyone watching someone else "perform" with Rack.  This probably only concerns streamers, but would be a fun feature none the less.

### Proposed design

Providing two CV inputs - one for Cable Tension, and one for Cable Opacity, allowing cables to "bounce" to the beat of a patch, or fade in and out as desired.  Maybe the ports need to be in a module so you don't have cables tethered to the 'border' of the Rack usable space?  This might be cleaner and more-desirable overall than having cables string to the top of the screen.

Using the feature could be like adding the Core Audio or Midi module, where CV inputs become available tying to the program's settings.  Perhaps more CV inputs would be relevant at a later time.

Can't think of any corner cases or alternatives to achieve this.  Would need to hook into the Rack underlying code, I think, and is impossible as a 3rd party module on it's own.

**Comment by AndrewBelt** [comment]
A plugin can do this, although modifying `settings::` variables will never be a stable API, so the plugin developer will need to keep it up to date.
