### ISSUE TITLE
v1 browser should place selected module where mouse was before entering browser

### ISSUE THREAD

**Issue by millxing** [VCVRack/Rack#1355]
### Summary

The new v1 module browser puts the new module wherever the mouse is when the module is selected. This means that the module is placed in a somewhat arbitrary location, determined by where the module happens to show up in the browser. For example, if I select a module that is in the bottom left of the browser, the module is placed in the bottom left visible section of my rack. 

I think it would be better design if the new module were placed where the mouse was when entrance to the module browser was initiated.

### Proposed design

Whenever entering the module browser, I think Rack should note where the mouse is on initiation of the module browser and then place the new module at those coordinates, despite the mouse no longer being there.

Not sure if this is a feature request or a bug report. Am I missing some logic to doing it the current way? Thanks!

**Comment by AndrewBelt** [comment]
The problem here is that a "click" is actually a "drag". When you release your mouse, Rack assumes the drag is over and places the module where you drag it.

**Comment by millxing** [comment]
Ah, didn't realize it was a drag. I just tried it a few times and now it makes sense. Thanks!
