### ISSUE TITLE
Fundamental Scope don't work ?

### ISSUE THREAD

**Issue by nay-seven** [VCVRack/Rack#1357]
Hello , just try different sources, but don't work here ?

### Details

Operating system: Mac OS 10.10
Rack version: v1.00 official

**Comment by AndrewBelt** [comment]
I need more information. Comment and I'll reopen.

**Comment by nay-seven** [comment]
don't know what to say more, i connect an LFO but nothing happen in the scope, nothing visible except numbers moving
<img width="530" alt="Capture d’écran 2019-06-19 à 15 59 22" src="https://user-images.githubusercontent.com/13808201/59772022-49fea980-92ab-11e9-9165-ea3211c84283.png">

**Comment by nay-seven** [comment]
<img width="953" alt="Capture d’écran 2019-06-19 à 16 03 20" src="https://user-images.githubusercontent.com/13808201/59772298-cd1fff80-92ab-11e9-94e2-63e8d66ac3c9.png">

**Comment by AndrewBelt** [comment]
If you delete the `<Rack user dir>/plugins-v1/Fundamental` folder and relaunch Rack, does this solve it?

**Comment by nay-seven** [comment]
Yes ! solved !
Thanks
