### ISSUE TITLE
Host: Segmentation Fault when Ozone 8 added

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Rack#1358]
Adding Ozone 8 to v1 causes a seg fault. An error is displayed 4 times before that occurs.

![Ozone Error](https://user-images.githubusercontent.com/12150421/59788467-b2f21b80-92c3-11e9-8fbb-8eec23fc3981.jpg)

not much to go on
```
[New Thread 7924.0x44c]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) bt
#0  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)

```

### Details
Copied the Ozone.dll to a new folder for host. I think Ozone authorizes with login details, I'm nearly sure you just have to have this authorized once on the computer and it reads the license key from disk when opened. There are self contained options in the Ozone to check for updates etc. I will contact iZotope with the error code and see what they have to say, might take a few days to get back to me though. Will update when they do with more details. Interestingly iZotope Iris 2 loads okay but iZotope Vinyl(Free) displays the same error

Operating system: Win7
Rack version: v1.0.0dev f813bff

### Expected behavior
Ozone opens
### Actual behavior
Ozone seq faults and displays dialogue box 4 times

### Addition
I had updated from ozone 8 elements to advanced, also authorized with the iLok which was not plugged but the license was transferred to computer have both authorizing anyway but did not make a difference. I just uninstalled elements and installed the latest version of advanced 8.02. This is now the error I get in rack: prints  `make:*** [Makefile:54: run] Error 3`

![Ozone Error2](https://user-images.githubusercontent.com/12150421/59797089-c78bdf00-92d6-11e9-87a5-d8cabe9f2c4a.jpg)

**Comment by Coirt** [comment]
I emailed iZotope just waiting on a response. I managed to load Ozone 8 with Blue Cats Patchwork v2.4 there but the load times for patchwork are really shocking. BC plugs use skins that can change the UI. I recently updated patchwork to 2.4 because it was not loading the plugin (missing skin/infinite loop when trying to load the default.xml skin file).

**Comment by Coirt** [comment]
Okay all good now, figured out what the issue was... 

I had copied the .dll files for Ozone and iZotope plugs into a new location, Ozone didn't like that. The copies were the problem. Installing Ozone into the location directly has solved this issue.

**Comment by RichieHindle** [comment]
I believe it would have worked if you'd copied both DLLs into the same location:

iZOzone8Elements.dll
Ozone 8 Elements.dll

That worked for me.  If you only copy "Ozone 8 Elements.dll" then it fails as stated.  The error messages and the crash are all within Ozone, not in VCV Host, so it's outside of our control.  Thanks for closing the issue!

**Comment by Coirt** [comment]
I wasn't sure which was which so I copied both in to folder. Now that I think of it I probably had copied the 32bit iZ and the 64 Ozone .dll's
