### ISSUE TITLE
Rack 1.0 won't open (nor 0.6 after installing 1.0)

### ISSUE THREAD

**Issue by Mogur8** [VCVRack/Rack#1360]
Hello, thank you, everyone.

I'm experiencing some problems after downloading and installing 1.0. I've chosen a new folder to install the new version, in order to keep 0.6 separated.
The thing is, after installing 1.0 (it all seems correct), Rack.exe won't execute. My machine gets stuck loading, but it doesn't do anything else.
I've tried 0.6 too, and it does the same thing, Rack won't open. I know it was working properly a couple of hours ago, so I don't get what is the problem here.

Has anybody experienced a similar problem?

### Details

Operating system: Windows 10
Rack version: v1.0 (and 0.6)
I looked for the log.txt, but it wasn't created yet. I haven't been able to open Rack 1.0

**Comment by stoermelder** [comment]
I guess this is more a problem with your machine than with Rack. Does this problem still persist?

**Comment by Mogur8** [comment]
We've been discussing in a different issue, and it seems like a problem with non-english characters in documents path, but I haven't been able to solve it yet. I don't know if there is a different problem with my machine, but I've been using Rack since v0.3 and this is the first time this happens.

**Comment by stoermelder** [comment]
Ok. What exactly happens when you try so start Rack? Is there a file `settings-v1.json` or `autosave-v1.json` in your settings-folder (usually in c:\Users\<Username>\Documents\Rack)? No `log.txt` in that folder?

**Comment by Mogur8** [comment]
When I try to start it, I get the "loading" symbol in my mouse cursor. However, after a few seconds, it dissapears and Rack doesn't open. 
There is no log.txt, and the autosave looks like a modified version of the template.vcv, without the Fundamentals (just Core). The settings.json looks normal too.
I'll paste both:
autosave
`{
  "version": "1.0.0",
  "modules": [
    {
      "plugin": "Core",
      "version": "1.0.0",
      "model": "AudioInterface",
      "params": [],
      "data": {
        "audio": {
          "driver": 7,
          "offset": 0,
          "maxChannels": 8,
          "sampleRate": 44100,
          "blockSize": 256
        }
      },
      "rightModuleId": 8,
      "id": 1,
      "pos": [
        57,
        0
      ]
    },
    {
      "plugin": "Core",
      "version": "1.0.0",
      "model": "MIDIToCVInterface",
      "params": [],
      "data": {
        "channels": 1,
        "polyMode": 0,
        "clockDivision": 24,
        "lastPitch": 8192,`
settings
`{
  "token": "",
  "windowSize": [
    0.0,
    0.0
  ],
  "windowPos": [
    0.0,
    0.0
  ],
  "zoom": 0.0,
  "invertZoom": false,
  "cableOpacity": 0.5,
  "cableTension": 0.5,
  "allowCursorLock": true,
  "realTime": false,
  "sampleRate": 44100.0,
  "threadCount": 1,
  "paramTooltip": false,
  "cpuMeter": false,
  "lockModules": false,
  "frameRateLimit": 70.0,
  "frameRateSync": true,
  "autosavePeriod": 15.0,
  "patchPath": "",
  "cableColors": [
    "#c9b70e",
    "#0c8e15",
    "#c91847",
    "#0986ad"
  ]
}`

**Comment by stoermelder** [comment]
Maybe there is something wrong with the file system rights in your user folder? Can try to start Rack with administrative rights as v0.6 und v1 seem to have the same problem and there is no `log.txt`. Just to make sure.

**Comment by Mogur8** [comment]
I had already tried to open both as administrator, and they didn't open. I have the log.txt in v0.6, but I believe it was created before the error started to happen, so I don't think that's of great help. It only shows things like "loading plugin", "extracting packages", it doesn't show any fatal error.

**Comment by Mogur8** [comment]
I've reinstalled Windows from scratch and now it works perfectly
