### ISSUE TITLE
VCV Rack doing nothing yet maxing out GPU immediately

### ISSUE THREAD

**Issue by bvrp** [VCVRack/Rack#1361]
<--
To file a bug report, fill out the form below.
Use a descriptive title that best explains the bug in one sentence.
Attach screenshots if the bug is visual.
Attach your `<Rack user folder>/log.txt` file if something is crashing or not loading.
Surround terminal output with three tildes
```
like this.
```
-->

### Details

Operating system:
Rack version: v1.0
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): Dell XPS 13 9370, Intel UHD 620, Intel i7-8550U CPU, 16GB RAM, Realtek Audio, Windows 10.

### Expected behavior

Not maxing out GPU (Intel UHD 620 integrated) immediately and forever when doing nothing.

### Actual behavior

Launching VCV Rack 1.0 with default patch (which has no audio), causes immediate 90% GPU usage spike which stays at 90% even though CPU usage is minimal and nothing is being interacted with. This causes immediate maximum fan operation and subsequent heating, ultimately causing VCV Rack to be unusable on my XPS 13 9370.

**Comment by Coirt** [comment]
You kind of need a dedicated GPU for rack. Integrated graphics are fine for playing solitaire and browsing Youtube but they suck at rendering graphics.

There is a setting in the documents folder that allows you to limit frame rate this is set at 70.0 by default I suggest lowering it to maybe 30 and see where you're at with usage. File can be found in Documents/Rack/settings-v1 on line 22 you'll can edit the  "frameRateLimit": 70.0,

**Comment by bvrp** [comment]
No, the Intel 620 isn't just "fine for playing solitaire and browsing Youtube"- testing has clearly shown that it can do much more than that (please see: https://laptoping.com/gpus/product/intel-uhd-620-graphics-review/). To be stating otherwise with such hyperbole clearly shows lack of regard for the issue I am trying to bring to light.

There is no reason why VCV should instantly max out the GPU when literally nothing is taking place other than some blinking virtual lights on the virtual modules. I think it is far more likely related to the code of VCV Rack. Adobe software doesn't do this, WebVR doesn't do this, literally no other application of the hundreds on my laptop does this other than VCV Rack currently.

Hence the reason why I mention it. Further research is showing that I am also apparently not the first to do so.

**Comment by Coirt** [comment]
As I pointed out in the second part of that previous post does that help. If I wanted to show no regard for your issue I would not have responded.

**Comment by bvrp** [comment]
Btw- I was referring to the first part of your response of passing judgement on an integrated GPU, not the second, and indicated as such right in my post.

One does not start their car already having a brick on the accelerator and just sit in their driveway waiting to blow the engine. Nor should VCV Rack be grabbing huge chunks of CPU/GPU when it has an empty rack. Nor should it max out resources doing something so minimal as voicing single VCO which other programs have done successfully for decades prior on hardware that was less capable than today's standards by orders of magnitude no?

**Comment by Coirt** [comment]
I didn't realise it was such a sensitive piece of hardware.

Anything to do with audio is done by the CPU, anything to do with displaying graphics is done by the GPU. If your framelimit is set at default (70.0) and your not bothered about changing it to find out if it makes any difference to your GPU then I've said all I'm going to say, best of luck!

**Comment by bvrp** [comment]
"I didn't realise it was such a sensitive piece of hardware."

Except it really isn't, I've already given a link showing that it can run 3d gaming.

"Anything to do with audio is done by the CPU, anything to do with displaying graphics is done by the GPU"

If that's the case, then this is a valid bug/issue that should be addressed. There really is nothing display-wise that would require such a high frame rate, since it's primarily a static image. So it should not be attempting to grab so much resources, especially when other applications may also require them.

I had thought that perhaps VCV was offloading audio processing to the GPU first- seemed to be the only reasonable explanation.

"If your framelimit is set at default (70.0) and your not bothered about changing it to find out if it makes any difference to your GPU then I've said all I'm going to say, best of luck!"

"not bothered to change it" 

I haven't changed it yet because I am at a different location on a different computer. But yet, the original issue is still relevant. So kind of a moot point.

**Comment by bvrp** [comment]
So setting the "Frame rate" to "70" has little effect.

In fact- removing all modules and just having an *empty rack* uses 50% CPU and 70% GPU.

Something is obviously very wrong with the 1.0 build.

**Comment by Coirt** [comment]
I suggested 30 the default is 70, setting to 70 will not change anything.

**Comment by bvrp** [comment]
oops, my mistake, I set it to 30.

**Comment by bvrp** [comment]
I am seeing other issue threads here about this same CPU usage problem going back a couple years. Seems this software just isn't ready yet. I will delete it an move on.

**Comment by verstaerkermusic** [comment]
here on MBP it's also on 100%
changing the frame rate to 30 helps reducing it to around 70% ... turning the scope off reduces it to 60%

**Comment by Coirt** [comment]
The thread from 1½ years ago was when Rack was version 0.5. It has come a long way since then.

I'm not too sure what you mean by turning the scope off.

You could try closing every opened application besides VCV and get a baseline for performance. It is completely up to yourself whether to use VCVRack or not. Before you stop using it, I would recommend having a read of this documentation on optimising your system, you will find many useful tips in it: 
https://www.cantabilesoftware.com/glitchfree/

**Comment by verstaerkermusic** [comment]
I ment **deleting** the scope, frees roughly 10% of the GPU usage.
Thanks you for recommending this book for windows-users, wich I'm not.

I have no applications open. GPU usage shows 0%. I open VCV and it jumps to 100%. Even it's in the background and not actively used. 
I never said I stop using VCV as I like the software, I only wanted to report that this high GPU usage is a problem as the MBP heats up very fast.

With the Framerate set to 30 fps I can work. 

As a comparison using logic takes about 10% of GPU with a few mixertrackjs with meters.
Opening a near fullscreen scope costs 70% GPU.

So i believe there could be some optimisation  beeing done.

**Comment by Coirt** [comment]
Apologies I glanced at the wrong post! The response was for bvrp.

In your case does setting engine > threads to 1 help?

**Comment by verstaerkermusic** [comment]
> In your case does setting engine > threads to 1 help?

it's by default on 1 and it's CPU related ... CPU usage is anyway decent

**Comment by bvrp** [comment]
An EMPTY rack in VCV 1.0 is using >60% GPU. There's no reason that should be happening other than there is probably something wrong.

That's like opening a new blank document in Notepad and having it instantly start burning through your GPU.  Seriously.

**Comment by verstaerkermusic** [comment]
> An EMPTY rack in VCV 1.0 is using >60% GPU. There's no reason that should be happening other than there is probably something wrong.
> 
I can second that ... empty rack, frame rate set to 30fps -> GPU 50%
MacBook Pro 2016
RadeonPro 460

**Comment by verstaerkermusic** [comment]
i tested it now on my macMini with eGPU Vega56 ... there it runs with 70fps 
with 20-40% GPU usage , wich is very okay and let the GPU stay quit for hours

**Comment by webholics** [comment]
Since the update to v1.0 I have the same problem on MacOS Mojave. Previous version v0.6 was running fast and without any problems. There seems to be clearly an issue.

**Comment by AndrewBelt** [comment]
Closing, as this issue isn't concrete and a potential solution would be incremental/fuzzy rather than definite.
