### ISSUE TITLE
Limit One Instance of Module 

### ISSUE THREAD

**Issue by djpeterso23662** [VCVRack/Rack#1363]
Should a module be able to tell Rack that only one instance is allowed in a patch? I am thinking of Core Audio, but it might apply to other modules as well.

**Comment by AndrewBelt** [comment]
There should be no reason to limit the number of instances of a VCV Rack module. If a module's DSP requires that it's a singleton for example, the module should report that it's "disabled" in some form but should still allow instantiating multiple instances.
