### ISSUE TITLE
Install fail on Win 10 X64 (rack 1.0)

### ISSUE THREAD

**Issue by gl33mer** [VCVRack/Rack#1364]
https://snag.gy/dm9NOr.jpg

Get this when installing, and reinstalling. Won't finish install.

Operating system: Win10x64
Rack version: v1.0
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):
Radeon 460/ Scarlette 

Install Failed.

**Comment by stoermelder** [comment]
Did you try re-downloading the installer?

**Comment by gl33mer** [comment]
I did try re-downloading. (latest version also -v1.1) To no avail.

Searching the net for this error one will find recommendations to install the Windows_MediaFeaturePack (according to your specific version). I was holding back on actually trying this but as the newer version didn't work I gave it a try just now.

Everything seems to be working just fine. Loaded up the first demo scene and played the new Keboard_midi device. :-)

Thank you.
