### ISSUE TITLE
1.0 Device input is no longer audible

### ISSUE THREAD

**Issue by dburles** [VCVRack/Rack#1365]
### Details

Operating system: MacOS Mojave
Rack version: v1.0.0
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):
Yamaha AG06

### Expected behavior

In 0.6.2c audio input is functioning correctly.

### Actual behavior

In 1.0.0 however, audio input is no longer functioning. Directly to output, no sound is heard and directly to scope displays no change.

**Comment by lnikj** [comment]
10.14.5

Audio input working here (tested with Loopback).

<img width="566" alt="screenshot_169" src="https://user-images.githubusercontent.com/24451110/59851156-d1a7ef00-9363-11e9-9091-263995062d7a.png">

**Comment by LeonFedotov** [comment]
Also here, compiled from HEAD and audio in works for mac! so this is going to be resolved in the next update :)

**Comment by dburles** [comment]
Hey @LeonFedotov might be a different issue as there's only been a few commits in the v1 branch since the release of v1.0.0, and they don't seem related to audio input.

**Comment by LeonFedotov** [comment]
Very interesting, maybe the packaging is causing it to malfunction?

**Comment by AndrewBelt** [comment]
Fixed by adding `NSMicrophoneUsageDescription` property to Info.plist in 8341623cf2f49983e0d63a69041e180e25a222f3. Apple was in fact blocking microphone (and line input) access from Rack, since after Mac 10.14.5ish, all applications are blocked by default.
