### ISSUE TITLE
AZERTY keyboard issues

### ISSUE THREAD

**Issue by Motopomp** [VCVRack/Rack#1368]
Well, I hope I post it in the right place.
So, here is my request, I would like the layout of the keyboard to be adapted to my language.
I use an Apple keyboard with wired keypad in French language (azerty) with my mac-mini, otherwise I use the keyboard (azerty) of a macbook pro.
it's mostly to avoid looking all the time, for some shortcuts (undo / redo) and other that I did not have time to discover, perhaps in the use of the keyboard as MIDI keyboard of the type oct - / +. And certainly others
Thank you in advance, if this is not possible and in view of the diversity of keyboards in the world, I understand and try to force me a little, thank you very much
Ps: Would not it be simpler than Rack uses the keyboard of the OS.
If I'm not in the right place, do not hesitate to let me know.

![image](https://user-images.githubusercontent.com/33150728/59859380-e5138400-937c-11e9-9ff3-2095346c9d60.png)

or

![image](https://user-images.githubusercontent.com/33150728/59859399-ecd32880-937c-11e9-93c6-336f0ce2d846.png)

**Comment by AndrewBelt** [comment]
A couple questions about Rack 1.0.0:
- The key command for Quit is Ctrl-Q for example. To quit Rack, can you type Ctrl-Q or Ctrl-A on your keyboard?
- Using the Computer Keyboard MIDI driver with the QWERTY device, does it correctly play a scale when you type AZERTYUIOP, or do you have to type QWERTYUIOP?

**Comment by Motopomp** [comment]
well, I tested all the shortcut, finally there is not any.
I made you an image, it will be simpler, but ultimately nothing essential or serious, the limit keeps it for information, if one day you want to adapt the software to all keyboards and all languages.
It's the Undo / Redo that scared me

![AppleFullKeyFr](https://user-images.githubusercontent.com/33150728/59914496-d085c900-941a-11e9-800c-373fa0acce10.png)

**Comment by AndrewBelt** [comment]
Oops, I mean Cmd+Q and Cmd+A. Can you tell me which of those quits Rack?

What about the scale test I described above?

**Comment by Motopomp** [comment]
To quit the Cmd Q app works fine, and for the scale, everything looks ok.
only the red box on the previous picture, do not match, or like F1 (help) that does not work.
Se evening, I would test on the macbookpro

**Comment by AndrewBelt** [comment]
Hmm, the fact that Cmd-Q is correct but Cmd-Z is mapped incorrectly doesn't add up. I think it'd best that I wait a while and purchase an AZERTY keyboard to do my own testing.

**Comment by Motopomp** [comment]
No problem, to make "undo" I just do not forget that it is cmd + x and even to go down the octave the right key of w.
Thank you for taking the time to look at this minor problem.
Since you seem to have a few minutes, I have another question, see you a solution to use "bridge" even if you do not want to maintain it, it was all the same practical.
At some this function and not in others (like at home), if it's a thing at random or too complex, it does not matter I would do as before (iac / soundflower), I can understand that you is something else to do.
In any case again Thank you for your patience.

**Comment by gsynuh** [comment]
Hello,

AZERTY windows keyboard here. FR style with ²  on top of TAB and & as the first char under 1.

Scale test : all good with AZERTYUIOP keys when windows language settings are set to french azerty keyboard.

Shortcuts : Ctrl+Z and Ctrl+Q are not working, 
switching to my secondary language settings (US keyboard but physical AZERTY keyboard) with Ctrl+Shift  lets me undo with Ctrl+W and quit with Ctrl+A as expected. 
(I have both language settings setup specially for software that don't like my layout :P)

(for all tests I confirmed I was in AZERTY or QWERTY on the software side by typing in the notes module)

available for any further tests with a pc keyboard or whatever else.

**Comment by AndrewBelt** [comment]
Can either of you build Rack from source? Before making a release of a feature, it should be tested first.

**Comment by gsynuh** [comment]
@AndrewBelt , I just successfully built v1 at https://github.com/VCVRack/Rack/commit/7a1a41c6af5581ca372683c30e97efe80fbca629

(didn't build fundamentals yet)

**Comment by AndrewBelt** [comment]
Awesome, will let you know what to test soon.

**Comment by AndrewBelt** [comment]
Okay I've pushed a commit 0ae792b that debugs keys and scancodes. Could you pull, recompile, `make run`, and post the debug output when pressing the keys labeled as z, q, #, and 1? For example, on mine (although I'm pressing ` instead of #):
```
z [3.329 debug src/window.cpp:162] key 90 scancode 52 name 'z'
q [3.829 debug src/window.cpp:162] key 81 scancode 24 name 'q'
1 [4.528 debug src/window.cpp:162] key 49 scancode 10 name '1'
` [5.743 debug src/window.cpp:162] key 96 scancode 49 name '`'
```

**Comment by gsynuh** [comment]
Hi @AndrewBelt 

Um okay so here I go with multiple keyboards including images found on google of my models :

![image](https://user-images.githubusercontent.com/2741417/59981286-61b69480-9601-11e9-9040-5d7d904970b1.png)

[431.135 debug src/window.cpp:162] key 87 scancode 17 name 'z'
[435.469 debug src/window.cpp:162] key 65 scancode 30 name 'q'
[442.569 debug src/window.cpp:162] key 51 scancode 4 name '"'
[443.403 debug src/window.cpp:162] key 49 scancode 2 name '&'

And a bluetooth mac style azerty 
![image](https://user-images.githubusercontent.com/2741417/59981301-86127100-9601-11e9-98fb-ba34ffad774c.png)

[474.736 debug src/window.cpp:162] key 87 scancode 17 name 'z'
[475.736 debug src/window.cpp:162] key 65 scancode 30 name 'q'
[489.870 debug src/window.cpp:162] key 51 scancode 4 name '"'
[493.185 debug src/window.cpp:162] key 49 scancode 2 name '&'

that last one doesn't have the pound symbol drawn on so pressed 3.
removed duplicate lines and autosave logs

**Comment by gsynuh** [comment]
Apple 10.14.4
mac book pro retina mid 2014

FR layout
![image](https://user-images.githubusercontent.com/2741417/60014381-2f4c7c00-9681-11e9-8343-b0ece3e18356.png)

[33.885 debug src/window.cpp:162] key 87 scancode 13 name 'z'
[35.070 debug src/window.cpp:162] key 65 scancode 0 name 'q'
[35.603 debug src/window.cpp:162] key 161 scancode 10 name '@'
[36.069 debug src/window.cpp:162] key 49 scancode 18 name '&'

**Comment by AndrewBelt** [comment]
Since neither the keys nor scancodes match, I've added more debugging in 60d1037.
Repeat the test again, but instead of `#`, I meant the key immediately left of `1`. So `z`, `q`, `1`, and `>`.

**Comment by gsynuh** [comment]
'windows layout' :
```
[14.373 debug src/window.cpp:162] key 87 scancode 17 name 'z' Z scancode 44 Q scancode 16 1 scancode 2
[14.672 debug src/window.cpp:162] key 81 scancode 16 name 'a' Z scancode 44 Q scancode 16 1 scancode 2
[15.189 debug src/window.cpp:162] key 49 scancode 2 name '&' Z scancode 44 Q scancode 16 1 scancode 2
[15.639 debug src/window.cpp:162] key 96 scancode 41 name '²' Z scancode 44 Q scancode 16 1 scancode 2
```

**Comment by gsynuh** [comment]
and here's for the mac :

```
[8.287 debug src/window.cpp:162] key 87 scancode 13 name 'z' Z scancode 6 Q scancode 12 1 scancode 18
[8.544 debug src/window.cpp:162] key 81 scancode 12 name 'a' Z scancode 6 Q scancode 12 1 scancode 18
[9.039 debug src/window.cpp:162] key 49 scancode 18 name '&' Z scancode 6 Q scancode 12 1 scancode 18
[9.339 debug src/window.cpp:162] key 161 scancode 10 name '@' Z scancode 6 Q scancode 12 1 scancode 18
```

**Comment by AndrewBelt** [comment]
For the key sequence `z`, `q`, `1`, and the key immediately left of `1`, here's a table summarizing these tests.

| keyboard | `key` | `scancode` | `glfwGetKeyName(key, scancode)` | `glfwGetKeyScancode(GLFW_KEY_*)` |
|---|---|---|---|
| My QWERTY keyboard | 90,81,49,96 | 52,24,10,49 | `zq1\`` | 52,24,10,49 |
| Your AZERTY Windows keyboard | 87,81,49,96 | 17,16,2,41 | `za&²` | 44,16,2,? |
| Your AZERTY Mac keyboard | 87,81,49,161 | 13,12,18,10 | `za&@` | 6,12,18,? |

Nothing makes sense, there is no structure. If I want to say "I want Ctrl-Q to work", there's no single consistent code that can check for that. I can't do `key == GLFW_KEY_Z`. I can't do `glfwGetKeyName(key, scancode) == "q"`. I can't even do `scancode == glfwGetKeyScancode(GLFW_KEY_Z)`.

**Comment by gsynuh** [comment]
@AndrewBelt . oh my god I messed up.

 This entier QWERTY vs. AZERTY thing got me confused + the fact that I often need to switch, so I was pressing A.

 glfwGetKeyName(key, scancode) is the only constant in all of this and reflects exactly what key I pressed.

I apologize for wasting your time.

new logs for windows where I do press the keys by label, not by 'position' : 

```
[4.007 debug src/window.cpp:162] key 87 scancode 17 name 'z' Z scancode 44 Q scancode 16 1 scancode 2
[4.941 debug src/window.cpp:162] key 65 scancode 30 name 'q' Z scancode 44 Q scancode 16 1 scancode 2
[6.624 debug src/window.cpp:162] key 49 scancode 2 name '&' Z scancode 44 Q scancode 16 1 scancode 2
[6.957 debug src/window.cpp:162] key 96 scancode 41 name '²' Z scancode 44 Q scancode 16 1 scancode 2
```

**Comment by AndrewBelt** [comment]
Okay, updated the table. One last request: To check that you're doing this correctly, can you type in the text box below the four-character sequence you used in the above test? Do not hold modifier keys such as shift and make sure Caps Lock is off.

**Comment by gsynuh** [comment]
sure sure.
windows : zq&²
(will be back with mac.)

**Comment by AndrewBelt** [comment]
Rack v2 has fixed key commands for all keyboard layouts, including AZERTY and Dvorak. See https://community.vcvrack.com/t/rack-development-blog/5864/55
