### ISSUE TITLE
1.0 Won't open on Mac OS Mojave

### ISSUE THREAD

**Issue by ejarvik** [VCVRack/Rack#1369]
<--
To file a bug report, fill out the form below.
Use a descriptive title that best explains the bug in one sentence.
Attach screenshots if the bug is visual.
Attach your `<Rack user folder>/log.txt` file if something is crashing or not loading.
Surround terminal output with three tildes
```
like this.
```
-->
 0.6 always worked fine on my laptop, but when I downloaded 1.0, it simply wouldn't open. I get a notice that says
<img width="442" alt="Screen Shot 2019-06-20 at 8 02 07 AM" src="https://user-images.githubusercontent.com/52043242/59859550-c76cfd00-9331-11e9-8c08-ce46e924b4ce.png">

Normally, there would be a way to override stuff like this. But all the notice says to do is get an update

Operating system: Mac OS 10.14 Mojave
Rack version: v1.0
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): N/A

I would expect at least an "unidentified developer" notice, which there is an override for

Instead, I get only a prompt to contact the developer for an update. (but this is the update)

**Comment by witchbutter** [comment]
I have the same issue 10.4.5 on a MacBook Pro Late 2016

**Comment by nay-seven** [comment]
Use a right click on the .app and choose _open_ will do the job.

**Comment by LeonFedotov** [comment]
you can run this command in the terminal `sudo spctl --master-disable` to allow running apps from anywhere, if not automatically working following this command go to preferences -> security -> general and select Anywhere

**Comment by kevinsolie** [comment]
I get the unidentified dev dialog

spctl -a -t exec -vv Rack.app
Rack.app/: rejected
source=Unnotarized Developer ID
origin=Developer ID Application: Andrew Belt (VRF26934X5)
<img width="196" alt="image" src="https://user-images.githubusercontent.com/5263784/59890899-09815780-93a1-11e9-9942-a2b16a9dd945.png">

**Comment by AndrewBelt** [comment]
@kevinsolie Thanks! What does `codesign --verify --deep --strict --verbose=2 Rack.app` say?

**Comment by kevinsolie** [comment]
@AndrewBelt 
codesign --verify --deep --strict --verbose=2 Rack.app
Rack.app: valid on disk
Rack.app: satisfies its Designated Requirement

**Comment by AndrewBelt** [comment]
Here's my research. In order to run an app bundle from Mac 10.14.5+, the app must be notarized by Apple, which requires passing `--options runtime` in the `codesign` command. This flag forces the app to run in some type of quarantine, which disallows it from `dlopen()`ing unsigned shared libraries (like `plugin.dylib` of plugins).

It's of course ridiculous to require plugin developers to sign binaries with a $100+tax/year Apple Developer membership, so Rack should not use `--options runtime`, and therefore shouldn't be notarized by Apple, and therefore must have the 

>“Rack.app” can’t be opened because Apple cannot check it for malicious software.

message on first launch. So I believe the best solution is to make an announcement on social media with instructions to bypass Apple's warning message.

**Comment by kevinsolie** [comment]
@AndrewBelt may be your only option

**Comment by rubyglow** [comment]
Jeeeezus h christ, Apple has *really* lost their minds here. If the signing was for free *maybe* I could understand it, but this is greedy and ridiculous beyond the pale.

**Comment by AndrewBelt** [comment]
The real fear here is that Mac might soon remove the ability to do the right-click Open trick, which would mean that Apple has full control of what programs you can and cannot run on your computer.

There's another way though, by disabling Gatekeeper with `sudo spctl --master-disable`. I have no problem at all requiring users to run that in order for Rack to stay un-notarized.

**Comment by AndrewBelt** [comment]
I should probably close this because the "social media" solution above is the best we can get.

**Comment by Skeyelab** [comment]
Disabling gatekeeper is not an option for all users.  Some people use a computer owned by an employer.

**Comment by AndrewBelt** [comment]
@Skeyelab Unfortunately they will not be able to use VCV Rack if Apple removes the [right-click Open](https://twitter.com/vcvrack/status/1142123704215904257) trick.

**Comment by Skeyelab** [comment]
Seems like the proper solution is for you, the developer, to sign the package.

**Comment by Skeyelab** [comment]
Wouldn't the solution be to include the shared binary in Rack.app, you sign it, then plugin developers can access the shared library?

**Comment by AndrewBelt** [comment]
Are you recommending me to sign other people's binaries?
