### ISSUE TITLE
Rack 1.0 should auto-append needed .vcv file extension

### ISSUE THREAD

**Issue by wiqid** [VCVRack/Rack#1370]
### Details

Operating system: Windows 10
Rack version: v1.0
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): n/a

### Expected behavior

When I save a patch in version 1.0, VCV Rack should automatically append the .vcv file extension. Alternatively, if it does not auto-append the extension, it should be able to open files without extension, exactly as they were saved.

### Actual behavior

In version 1.0 Rack does not automatically append the needed file extension. It also is unable to open patch files without an extension.

**Comment by rubyglow** [comment]
No problems on MacOS here. Are you by any chance running with the default Windows settings, whereby it hides all file-extensions?

**Comment by AndrewBelt** [comment]
Can't reproduce this, works fine for me on all OS's.

**Comment by wiqid** [comment]
> Are you by any chance running with the default Windows settings, whereby it hides all file-extensions?

Yes indeed. Windows 10 Pro, default settings. But even when I enable file extensions in file names, it doesn't change the behavior of the Rack save as and open dialogs.

It's annoying because it works fine in 0.6.

**Comment by AndrewBelt** [comment]
@wiqid Are you saying Windows is hiding the .vcv extensions or are they not there?

**Comment by wiqid** [comment]
@AndrewBelt I am saying that they are not there. In 0.6 Rack used to add the .vcv extension automatically. In version 1.0 I need to do it manually, otherwise Rack cannot open the file again, because Rack saves the file without extension.

**Comment by AndrewBelt** [comment]
Okay, yeah, I can't reproduce it.

**Comment by wiqid** [comment]
This appears to be fixed in 1.1.1
