### ISSUE TITLE
Patch name in title bar encoding error

### ISSUE THREAD

**Issue by maxmcorp** [VCVRack/Rack#1371]
As the title says

### Details

Operating system: Windows 10
Rack version: v1.0.0

### Expected behavior
"Buggy title æøå ÆØÅ €.vcv"

### Actual behavior
![vcv-rack-bug](https://user-images.githubusercontent.com/681845/59873378-29fae300-939c-11e9-951d-9e2285151548.jpg)

**Comment by Coirt** [comment]
#436

**Comment by AndrewBelt** [comment]
Turned out not to be an issue with the titlebar but the file save dialog box. Fixed in 41eb965
