### ISSUE TITLE
Add jq to deps?

### ISSUE THREAD

**Issue by hwpfeil** [VCVRack/Rack#1374]
<--
To request a feature, fill out the form below.
Use a descriptive title that best explains the feature request in one sentence.
-->

### Summary
Suggest adding jq to Rack/dep

What is the motivation for this feature? What does the feature achieve?

I do not wish to install ad-hoc packages like jq systemwide on Slackware-current Linux. Rack/plugin.mk is the only place this package is used. Once plugins are built and installed, there is no further need for jq on the systems which I administer.

### Proposed design
Include jq in Rack/dep where all other Rack dependencies are already installed.

**Comment by AndrewBelt** [comment]
`jq` is a build dependency, not a dependency of Rack itself, so it does not belong in `dep/`.
