### ISSUE TITLE
Host Loads Slowly in Win7

### ISSUE THREAD

**Issue by midiguru** [VCVRack/Rack#1375]
The Host module takes about 2 minutes to produce a list of my VST instruments. This is consistent, repeatable behavior. When the list appears, it contains some VST .dll's as many as 7 times -- others only once. I don't see a reason for this. The screen shot shows a portion of the list:

![duplicate_vst_list](https://user-images.githubusercontent.com/10890978/59893414-ab00ad00-9391-11e9-9868-b9c691d03eb2.jpg)

Granted, I have more than the usual number of VSTs, but this behavior is not encountered in Host 0.6.x.

### Details

Operating system: Windows 7 64-bit
Rack version: v1.0.0
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): n/a

**Comment by Coirt** [comment]
Should be fixed in v1.0.1
#1356
