### ISSUE TITLE
Serious issue saving patch files, truncated files on MacOS X

### ISSUE THREAD

**Issue by fractalgee** [VCVRack/Rack#1376]
### Details

Operating system: Mac OS X 10.11.6
Rack version: v1.0.0
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): N/A

### Summary
On saving patch files (after my custom template opens and I start patching, then save as to a new patch file. I hit save before quitting and now 3/4 of my patch file are gone, not written to the .vcv file. This is the second time I have seen this, so now have to make sure the file size is sane before quitting or I risk losing the patch (well, the saved has less that the template it started with, so seriously truncated....)  No error reported anywhere, Rack or OS, plenty space available where it saves (1.1TB) and drive checks healthy

### Steps to reproduce

none I can find, happens at random seemingly. Never happened in 0.62

I really liked that patch, oh well, try to rebuild it, if I can remember exactly what I did. Guess this is the real Eurorack experience of 'it exists only in the moment' ;)

Here is the sadly truncated patch file:

[FG_01_06.vcv.zip](https://github.com/VCVRack/Rack/files/3314308/FG_01_06.vcv.zip)

**Comment by AndrewBelt** [comment]
Since the file is truncated at NYSTHI ScalaQuantizer, could you try to reproduce this again and see if it truncates at the same position?

**Comment by fractalgee** [comment]
Last one that truncated like this (didn't keep it) was truncated half way through the RCM G-Verb. So looks like some random place, but both only saved what reports as 9KB on this machine, whereas both should have been around 240ish KB in size

So I highly doubt it is the Nysthi's Scala Quant that causes this. Seems more an issue with the library you use to write the JSON out to file as you surely don't ask every module to write out but rather write out current state of each?

**Comment by AndrewBelt** [comment]
Well, if you can find steps to reproduce it, I'll take a look.

**Comment by fractalgee** [comment]
no real steps apart from 'start with custom template'

Now save as... new patch name.

Patch, periodically hit save (not save as)

Do so around at least a dozen times over the patch progression and then
like where you are, need to eat so you save and then quit rack around 20
seconds later or so without checking if saved patch file has a sane size,
which is then on reopen end getting JSON parsing error near end of line and
starting to feel a little depressed ;)

That is exactly how those two times happened....

**Comment by fractalgee** [comment]
OK, just lost another patch same exact issue so maybe it is the Nysthi Scala Quant, but I don't see how as you are saving the JSON, not Antinio, so am I missing something serious here on how patches get saved? This patch (recreation of previous one, as best as I could) saved around 10 times and then was borked, not even a save as then would save it as anything but 9K truncated file, same exact spot the previous one stopped writing at. Why? This sounds like memory corruption issue somehow, unless I really am missing something.

While I love 1.0, I will go back to 0.62 for now until you can work out what causes this, as I am tired of patching for 2 hours just to end up nowhere at this stage. If I need to report it to Antonio then let me know, but then please understand how it could be his issue before I go file an issue with him

**Comment by AndrewBelt** [comment]
Could you post the truncated patch?

**Comment by fractalgee** [comment]
Here is the truncated patch (_01) and the save as (_02) and the equally
borked autosave in a tidy zip

**Comment by fractalgee** [comment]
I have also asked Antonio to have a look with best repro scenario I could
provide, as it always seems to do that when I mess with a patch and then
the Scala Poly Quant from Nysthi. Always stops saving the patch at the
scala file name, with just an open quote and nothing further. But I still
don't get how it could cause that...

**Comment by fractalgee** [comment]
Finally tracked this one down: Issue was (Thanks to Antonio for spotting that) a non-UTF-8 char in the description line of a scala file that trips up the JSON saver by it seeing NULL and stopping saving at that spot. Once that illegal char is replaced with a legal one (should have been an ü) all seems fine and Antonio is fixing that this can happen by replacing any unreadable char (UTF-8) with some placeholder that is legal.
