### ISSUE TITLE
Host drop down rearranged by Vendor

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Rack#1379]
### Summary
Instead of a overwhelming list of VST's please consider adding sub menus to sort VST's into. Having collected a great many VST's over the years it would be very nice to be orderly on Host's drop-down menu. iirc most DAW's filter plugins by Vender / Manufacture. This would make adding and choosing VST's a lot easier. I'm nearly sure the information for Vendor is in most vst.dll's.

### Proposed design
Have Vendor filtering in Host's context menu. Instead of the VST name e.g.

Currently
see attached 

Proposed
_Vendor > Vendors VST's_
```
Fabfilter > FabFilter ....
iZotope, inc. > iZotope .....
Waves > ......
```
Those with no Vendor information could be placed in a menu called `Other`.

If there is a way to get Host to show folder hierarchy in its context menu that would probably be a better way to have it. You would then have the possibility to customise the folders in the OS i.e. folder named EQ, Compressor, Effect, Instrument etc. Or as above sorted by Vendor manually, any way you'd like really.

![VSTlistings](https://user-images.githubusercontent.com/12150421/59946164-ac010f80-9461-11e9-8fa9-fb69ef8e7a2a.JPG)

(About 1/8 of my VST's shown).

**Comment by AndrewBelt** [comment]
Folder hierarchy is possible, but we'd have to do away with searching. I think most people would prefer searching over folders.

**Comment by Coirt** [comment]
Hmmm, hierarchy would be my preference over searching. If searching would work sorted by Vendor then I'd propose a settable option for either.

**Comment by AndrewBelt** [comment]
This is the issue tracker for VCV Rack. Send bug reports and feature requests of VCV plugins to contact@vcvrack.com.
We have added this to our internal issue tracker. Comment your email address here if you would like to be informed of future updates to this issue.
