### ISSUE TITLE
After moving first Install or renew install "Procedure [...] in plugins.dll not found" [WIN10]

### ISSUE THREAD

**Issue by cpwnd** [VCVRack/Rack#138]
OS (if applicable): Windows 10 64bit
Version (or "dev" if compiling from source): 0.3.1

First of all, great work! Downloaded it today and its fun to explore it.

After the first installation everything worked fine and no error occured. Then I registered at the website, to be able to download the plugins within the program. Installation of the plugins were successfully. After the download the rack with plugins worked quite fine too.

However I decided to move the directory to another partition. After moving the directory, some .dll path seemed expectedly broken. Removing current installations and several reinstalltions (even into the same location as the first time) doesn't work out till now. 

When installing the plugins over 'Refresh Plugins' (after sign in) or on startup of Rack.exe, the following error occurs:
    
    Der Prozedureinsprungpunkt "_ZN4rack11ParamWidged17onMouseDownOpaqueEi" 
    wurde in der DLL "WIN_INSTALL_PATH\Rack-0.3.1-win\Rack\plugins\AudibleInstruments
    \plugins.dll" nicht gefunden

Same Message occurs for all installed plugins (Befaco and E-Series).

Since the first installation worked, I assume there are some hidden files? Maybe this is a known issue?

**Comment by AndrewBelt** [comment]
Rack v0.3.2 was released a few minutes ago at https://vcvrack.com/, and now old versions are not supported anymore. In this version, you'll be notified for new Rack updates on launch to prevent this issue.

**Comment by cpwnd** [comment]
Great works fine !
