### ISSUE TITLE
[Feature Request]Add keyboard shortcuts for the zoom function  

### ISSUE THREAD

**Issue by AScustomWorks** [VCVRack/Rack#1384]
### Summary

To speed up the zoom in/out function and increase zoom accuracy
### Proposed design

Add two shortcuts to the zoom function:
While we can use the zoom option on the menu, or command + mouse scroll to zoom in/out is a bit hard to control the exact amount of zoom, so this two shortcuts would be pretty useful here.

**Comment by AndrewBelt** [comment]
Use Ctrl-`-` and Ctrl-`=` (or Cmd on Mac).

**Comment by AScustomWorks** [comment]
Just tried but nothing happens... besides, the extra shortcuts would still speed things up.
Thanks!

**Comment by AndrewBelt** [comment]
Then this is now a bus issue. What is your OS version and keyboard layout (QWERTY, AZERTY, etc)?

**Comment by AScustomWorks** [comment]
Os X Mojave 10.14.5, qwerty spanish (tried both spanish and english settings).

**Comment by AndrewBelt** [comment]
Hmm, can't reproduce. The key commands work fine for me.

**Comment by AScustomWorks** [comment]
Weird,  pretty much any other app that supports zoom with Cmd + - works just fine here.

**Comment by michellewalbeck** [comment]
Had the same issue. Cmd - and Cmd + only work using the + and - on the Typing Keypad above the letters. They do not work on the Numeric Keypad. Just in case anyone was having a similar issue, you might try this...

**Comment by AScustomWorks** [comment]
Yes, the numeric keypad keys are the ones not working, but only in Rack, everywhere they work as intended, the mapping is missing here.
