### ISSUE TITLE
Knobs jump to random position on V1. 

### ISSUE THREAD

**Issue by Deniou** [VCVRack/Rack#1385]
Sometime, the knobs on any module is "jumping" on a random position by clicking before dragging.

Operating system: Windows 10
Rack version: V1.0
Hardware relevant to your issue: AMD READON, 2012 

I currently don't know how to reproduce it. It just happens sometime.

**Comment by AndrewBelt** [comment]
Duplicate of https://github.com/VCVRack/Rack/issues/1367
