### ISSUE TITLE
Octal Router activates routes when mouse 'is in a click&drag state' and mouse hovers the matrix area

### ISSUE THREAD

**Issue by gsynuh** [VCVRack/Rack#1387]
### Details

Operating system: Windows 10
Rack version: v1.0.0
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):
nvidia 1080 , WASAPI and usb audio device (edirol UA-25EX)
### Summary

- Octal router in a medium patch appeared to activate/deactivate matrix routes/points randomly.
- it appears that this happens when the mouse is in click/drag state from another module
- it also happens from within octal router
- I have pinpointed how to reproduce this issue , explained below

### Steps to reproduce

1. open default/template patch in Rack 1.0.0
2. create octal router instance anywhere. don't connect it to anything.
3. [IMPORTANT] click on the top left point in the router matrix so that at least one route is set
4. 1. mouse down on LVL knob in Octal Router of any input, drag over matrix area. routes should activate on the mouse's path.
4. 2. mouse down on any knob of another module (ex: LFO) and drag to octal router, over the matrix area. similarly, routes activate on the mouse's path.

The issue cannot be reproduced on my side if no routes are active (see 3.) 

---

edit : additional tests and info :  

- apparently any click&drag action causes the matrix display to activate routes when the mouse is over that area, when the left mouse button is down and at least one route is already activated. 
- dragging a module over the matrix area, starting the drag from an empty area, starting drag on a menu item, dragging a cable end over the matrix area.
- [important] if the last mouse action in the matrix area was to drag to remove routes instead of adding routes, then all behaviour described earlier would remove routes instead of adding them.

**Comment by gsynuh** [comment]
(apologies for the initial issue's empty state, I misclicked something. re-opening with full details and better title.

**Comment by AndrewBelt** [comment]
Thanks, will be fixed in Router 1.0.1.

**Comment by AndrewBelt** [comment]
For some reason I had forgotten to release this. Released VCV Router 1.0.1.
