### ISSUE TITLE
omit menu items in ParamWidget::createContextMenu()

### ISSUE THREAD

**Issue by cclark2a** [VCVRack/Rack#1388]
Tooltips include menus that are not relevant for momentary buttons. 

Allow omitting the second (`ParamField`) and third (`ParamResetItem`) menu lines.

Motivation for omitting `ParamField` : momentary buttons do not retain a value. Showing a value field is confusing.

Motivation for omitting `ParamRestItem`: it is sometimes desirable to press momentary buttons quickly multiple times. Since momentary buttons have no value, double-click to reinitialize does not have a purpose. Double-click itself can be disabled by overriding `onDoubleClick()`, but the misleading menu item is not easily removed.

If there is a way to override the default behavior;  that's fine. It isn't obvious how to do so. (It doesn't appear that `Switch` has a way to suppress showing the double click tooltip even though it disables the double click action.)

**Comment by cclark2a** [comment]
I added this to my subclass of `ModuleWidget` and it does help by suppressing the right-click context menu while permitting the hover-style tooltips. 

```
    void onButton(const event::Button &e) override {
        if (e.action == GLFW_PRESS && e.button == GLFW_MOUSE_BUTTON_RIGHT
                && (e.mods & RACK_MOD_MASK) == 0) {
            e.consume(nullptr);
        }
        ModuleWidget::onButton(e);
    }
```
However, I don't like it because it removes all right-click parameter entry -- I suppose I could add my own context menu when I need one in the future, if I must.

Without the `ModuleWidget` hack, I see right clicks that look like this:

<img width="204" alt="rightclick" src="https://user-images.githubusercontent.com/36116331/60221380-68cee400-9847-11e9-9135-439924ad279f.PNG">

**Comment by AndrewBelt** [comment]
I wouldn't worry about it. Buttons are parameters like everything else, so it's reasonable to have a consistent UI.

**Comment by cclark2a** [comment]
Not sure what your reply means. Are you saying that all parameters should have a right-click context menu even if it is not useful?

Since I prefer to allow the context menu on the module while disallowing the context menu on buttons, I override the module's `onButton` and call `e.consume()` if a child button's bounding box contains `e.pos`, and that works. I would prefer to override the button's `onButton` directly, but the override isn't called on a right-click event.
