### ISSUE TITLE
empty space and module on Mac Mini

### ISSUE THREAD

**Issue by tecnologiemusicali** [VCVRack/Rack#139]
[Hi, I'm using Rack on in my music lab, the software works well on all the newer computer (Mini mac late 2014, graphic card Intel Iris 1536MB), but I'm experiencing some problems on all old Mini Mac (mid 2010, Invidia GeForce 256 MB), regardless of the operating system installed on each computer (10.10.5 and 10.12). 
The work space is empty and there are not knobs on the module, as you can see on the pictures attached.
Any idea about that?

![rack vcv](https://user-images.githubusercontent.com/17990079/30805440-afe4fd3c-a1f1-11e7-8c53-e4873ff71f42.jpg)
![mac](https://user-images.githubusercontent.com/17990079/30805449-c135288c-a1f1-11e7-9730-0da61d7caabe.jpg)

**Comment by AndrewBelt** [comment]
This was a problem with ~2010 Macs, and it has been fixed in Rack v0.3.2. https://vcvrack.com/ Let me know if this fixes it.
