### ISSUE TITLE
Mouse sensitivity when making cable connections

### ISSUE THREAD

**Issue by CheyenneWills** [VCVRack/Rack#1392]
### Details

Operating system: Linux (Gentoo / Enlightenment window manager)
Rack version: v1.0
Hardware relevant to your issue: 
    Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz, 
    NVIDIA GTX 960 Video, 
    NVIDIA GM206 HD audio

### Summary
When creating a cable connection, the cable will be "dropped" at times when crossing other "elements" e.g. crossing another cable, moving over an input, etc.   Doesn't happen with V0.6c
### Steps to reproduce
connect an input/output with a cable while crossing lots of cables.  Really evident if the connection is being made "across" a large number of elements.

**Comment by CheyenneWills** [comment]
Maybe something related -- when using the mouse to "twist" a knob, the mouse seems to be released when crossing another element as well

**Comment by AndrewBelt** [comment]
I can't reproduce. Is there a certain module/component that dragging over makes the cable release?

**Comment by CheyenneWills** [comment]
One example is Plateau.

However.. I'm noticing some other odd mouse behavior on my system, so this might not be directly related to Rack, but might be a general load issue on my system.. (will continue to investigate) -- so hold off just a bit before researching on this.

**Comment by CheyenneWills** [comment]
Closing this -- sorry .. it's an issue with the inputlib driver.  It's detecting a BTN_RELEASE when it shouldn't when under a large CPU load.  I suspect the connection with VCVRack  is that VCVRack V1 is using more CPU (I have it configured for 4 thread).

**Comment by CheyenneWills** [comment]
Just as a quick follow up on the problem.. Ultimately it turned out to be an issue with detecting/modeling the debouncing on the left mouse button.  I ended up cleaning the switch inside the mouse and it seems to have corrected the problem.
