### ISSUE TITLE
No midi cv via bridge (Rack v1)

### ISSUE THREAD

**Issue by TimUtting** [VCVRack/Rack#1394]
### Details

Operating system: Windows 10 Pro 
Rack version: v1.0
DAW: Reaper x64 v5.978

### Summary
None of the midi functionality of bridge is working on rack v1.0, I get no option in the installer to install a new version of bridge if that is what is required
### Steps to reproduce
Install rack v1
Insert bridge vsti on track in Reaper, default preset (port 1)
add midi-cv module to rack and set to bridge port 1
no output from midi-cv module on any port

**Comment by stoermelder** [comment]
Already fixed in 7a1a41c6af5581ca372683c30e97efe80fbca629. Will work again in the next release.

**Comment by TimUtting** [comment]
Awesome, appreciate the quick response
