### ISSUE TITLE
[Feature Request] Add keyboard shortcuts for the zoom 100% function

### ISSUE THREAD

**Issue by pojitonov** [VCVRack/Rack#1400]
### Summary
To speed up the zoom to 100% function and increase efficiency.
After the user used Zoom In/Out options in many cases you want to get back to 100%, this feature will allow to do it quickly. 

### Proposed design

Assign Ctrl(win)/Cmd(mac) + 0(zero key) for Zoom to 100% as it used in most applications where the user need to deal with scale (Apps like Photoshop, Chrome etc.).

**Comment by AndrewBelt** [comment]
Thanks, added in 71c28eb
