### ISSUE TITLE
[Feature Request] Add pan function with the keyboard shortcuts for it

### ISSUE THREAD

**Issue by pojitonov** [VCVRack/Rack#1401]
### Summary
To speed up the navigation ob the Rack canvas provides a feature that will help the user to do panning. Like it happens in applications where the user need to deal with the canvas (Apps like Photoshop, Sketch etc.).
After the user used Zoom In/Out options in many cases you want to get back to 100%, this feature will allow to do it quickly. 

### Proposed design
Assign Spacebar as a keyboard shortcut that will invoke the Pan tool.
Pan tool should work as an intermediate tool, so it enabled only when the Spacebar is pressed.
When the Spacebar is released the pan tool become disabled. 
When the Pan tool is enabled the cursor needs to be changed to **openhand**
When the user starts dragging the canvas by using the mouse the cursor needs to be changed to **closedhand**
Refer to macOS cursors http://cursor.in/

**Comment by AndrewBelt** [comment]
Use middle-click-drag to scroll the screen.

**Comment by AndrewBelt** [comment]
Hmm, some Apple mice don't have a middle mouse button, so add a key command to emulate it. Discussion on Facebook. https://www.facebook.com/groups/vcvrack/permalink/368976343762516/

**Comment by AndrewBelt** [comment]
Okay, added in 9eb61ecec024da8b91bcec3b69aa05b95d6a1af4. Middle-click-drag can now be emulated with Ctrl-shift-click-drag.

**Comment by pojitonov** [comment]
Exactly, that's why the Space bar become a standard in many apps.

**Comment by AndrewBelt** [comment]
Space can be used for more useful things like sequencers, so I'd rather assign it to that (when the time comes).

**Comment by pojitonov** [comment]
Hi Andrew,
It's great I have already installed the update with this feature, work on macOS become more comfortable.
The only suggestion that I would recommend is to change:
**Control + Shift + LMB** to **Cmd + LMB** - for pan
**Cmd + LMB** to **Shift + LMB** – for rearrangement
The reason is the [keyboard layout](https://core0.staticworld.net/images/article/2012/10/keyboardcaption-100010086-orig.jpg)
As you can see the Cmd and Control are placed following that it becomes a little challenging to switch from Cmd for zooming and Shift + Control for panning.
Also, the meaning of Shift modifier perfectly aligns with the meaning of the command to shift the blocks around. As a result, for navigation, the user will need to use only the one button on keyboard Cmd (on mac). for rearrangement the Shift key. Looks logical for me.

It will require to make the appropriate change on Windows as well for consistency reasons
**Ctrl + LMB** – for pan
**Shift + LMB** – for rearrangement

P.S. Thanks for your job!

**Comment by AndrewBelt** [comment]
Sorry, these suggestions do not work.
- Cmd-click should trigger... a Cmd-click. Many many plugins need to receive this event.
- I like Cmd better as a primary modifier, so Cmd-click should be used for most secondary left-clicks, such as module dragging.

**Comment by joshdavenport** [comment]
Would really love to see hold spacebar dragging as seen in loads of creative software (Photoshop, Illustrator, Indesign, Sketch - come to mind.) Or an option to configure, so space could be used and then another key for the ideas you have around sequencers etc? I find myself fighting against muscle memory when space does nothing, but definitely recognise this is niche!

**Comment by AndrewBelt** [comment]
@joshdavenport The rack in Rack v2 can be dragged with the left mouse button with no key modifiers, provided you drag the empty rack space or enable "View > Lock modules" from the menu bar. No spacebar needed.

**Comment by joshdavenport** [comment]
That sounds cool. Though speaking from a personal perspective, I tend to keep modules tightly packed, so finding empty space would seem a chore. Look forward to trying it though.

I think muscle memory will still kick in for me, thanks to the day job. But hey, if it really bothers me that much I should implement the feature myself!

Could be really nice if space actually controlled lock modules, with an option for toggle or hold of the key.

**Comment by AndrewBelt** [comment]
@joshdavenport I suggest to get a mouse with a middle mouse button and get used to that.

As I said above, spacebar is reserved for other things.

**Comment by joshdavenport** [comment]
Yeah, indeed, fair enough. Thanks for taking the time to discuss anyway @AndrewBelt and for this phenomenal project.
