### ISSUE TITLE
Duplicating module crashes with Assertion `module->id != m->id' failed.

### ISSUE THREAD

**Issue by ndrspcfd** [VCVRack/Rack#1402]
Operating system: KDE Neon
Rack version: 382f67a53ebde88413b7ebf602152b44c94483f2

### Summary
Duplicating module either with ctl--D or context menu crashes vcv with Rack: src/engine/Engine.cpp:513: void rack::engine::Engine::addModule(rack::engine::Module*): Assertion `module->id != m->id' failed.

### Steps to reproduce
Open default patch, click on oscillator, hit ctl-D

### Mitigation
Seems like this was introduced with the recent json refactor. A stupid ugly fix is:

```

diff --git a/src/app/ModuleWidget.cpp b/src/app/ModuleWidget.cpp
index 4b57ac1..263e099 100644
--- a/src/app/ModuleWidget.cpp
+++ b/src/app/ModuleWidget.cpp
@@ -728,6 +728,7 @@ void ModuleWidget::cloneAction() {
        // JSON serialization is the obvious way to do this
        json_t *moduleJ = toJson();
        clonedModuleWidget->fromJson(moduleJ);
+       clonedModuleWidget->module->id = -1;
        json_decref(moduleJ);
 
        APP->scene->rack->addModuleAtMouse(clonedModuleWidget);
@@ -829,4 +830,4 @@ void ModuleWidget::createContextMenu() {

```

But, I expect you would want to fix it more intelligently than that! 

### Congratulations

V.1.x ! Yay! Multithreading! Yay! Hats off all around!

**Comment by AndrewBelt** [comment]
Thanks, fixed in d148176. That's the proper way to do that.
