### ISSUE TITLE
Favorites feature back in 1.0

### ISSUE THREAD

**Issue by nuclearsound** [VCVRack/Rack#1403]
Sorry for dupes, and bravo @AndrewBelt for having created VCV, which is great.

I first didn't find a topic about favorites/bookmarking management for 1.0, then commented the feature request nr 1292 (and talked about "user-defined tags" more widely), but discovered the thread closed right after sending my contribution. So I'm not too sure that this topic is discussed anymore, read, up-to-date. Hopefully now it is. I hop my "user contribution" can help have a point of view UE-wise.

**Comment by AndrewBelt** [comment]
Merging with discussion at #1292
