### ISSUE TITLE
error: thread-local storage is not supported for the current target

### ISSUE THREAD

**Issue by Miserlou** [VCVRack/Rack#1405]
I get this error when trying to build Rack 1.0.0 on OSX 10.10:

```
error: thread-local storage is not supported for the current target
thread_local uint64_t xoroshiro128plus_state[2];
^
1 error generated.
make: *** [build/src/random.cpp.o] Error 1
```

If I just remove that `thread_local` from `random.cpp`, then it compiles and functions normally, so it seems like this can be removed to support building from 10.10 until the 1.0.0 SDK is out.

**Comment by AndrewBelt** [comment]
Unfortunately `thread_local` will be used increasingly more often, so omitting out the keyword will only break Rack more in the future.

**Comment by Miserlou** [comment]
Okay. Closing.
