### ISSUE TITLE
Win 10 file chooser filter sometimes does not work and can create a garbage filter entry

### ISSUE THREAD

**Issue by SteveRussell33** [VCVRack/Rack#1407]
### Details
Operating system: Win 10
Rack version: v1.1.0 (built from latest commit 619e1e452333e987e31bca95ca341078ba9cbec9)

### Summary
.vcv file filter sometimes fails to pick up any file. 
![v1-filechooser1](https://user-images.githubusercontent.com/41975381/60239860-fb52a000-98a6-11e9-8b77-5fbe5c6dc6a2.png)

Using wildcard as filename brings up patch files
![v1-filechooser2](https://user-images.githubusercontent.com/41975381/60239894-1de4b900-98a7-11e9-83e1-34e084bb706b.png)

Also - if it picks up patches - it won't filter out other files e.g. in this case screenshots of patches
![v1-filechooser3](https://user-images.githubusercontent.com/41975381/60239972-6308eb00-98a7-11e9-8a32-5b231281b255.png)

File->Save as also shows this bug
![v1-filechooser5](https://user-images.githubusercontent.com/41975381/60240851-ec212180-98a9-11e9-9e91-7250be2079f5.png)

### Steps to reproduce
Start Rack, use Ctrl-O or File->Open to open patch.
Most times it's reproducible by opening a patch (when filter works) then trying to load another patch.
![v1-filechooser4](https://user-images.githubusercontent.com/41975381/60240388-aca60580-98a8-11e9-96e4-8527e0f87ac3.png)

Reverting  [dep/osdialog 502fe29e6813858e5554e25f8e4d52ad0af5e4fc](https://github.com/AndrewBelt/osdialog/commit/502fe29e6813858e5554e25f8e4d52ad0af5e4fc) ~~and 724b4287eae674779855adaf250b9ae2ebe85f72~~ solves these issues, but leaves a garbage entry in the filter list as mentioned below.

**Comment by dag2099** [comment]
a similar thing happens in Windows 7. Additionally I notice that when you open the filename extension widget it has the choice between vcvrack and random garbage,

**Comment by SteveRussell33** [comment]
I've noticed this as well with a build that reverts just 502fe29e6813858e5554e25f8e4d52ad0af5e4fc. Reverting both commits I mentioned solves that issue as well as the ones seen in the screenshots.

**Comment by SteveRussell33** [comment]
The garbage entry above appears in an empty Rack, loading a patch after previously loading another patch sometime makes it disappear.
Saving an edited patch, then opening another creates the entry again but with different characters.
![v1dialogrubbish](https://user-images.githubusercontent.com/41975381/60271698-b94b4d80-98ea-11e9-8f02-5db302c29db0.png)

Saving an already saved patch using Save as, on occasion, will produce a line of text seemingly from the patch itself.
![v1dialogrubbish](https://user-images.githubusercontent.com/41975381/60271979-31b20e80-98eb-11e9-9e83-f74ec29d36fc.png)

**Comment by catronomix** [comment]
I have the same issue, also Win 10, for me the garbage looks like chinese :)
![image](https://user-images.githubusercontent.com/42138122/60324331-cfa5e780-9984-11e9-8253-30a8e4f0b200.png)

**Comment by Rcomian** [comment]
Can confirm this bug does not exist in: 8341623cf2f49983e0d63a69041e180e25a222f3
It does exist in: 41eb965839671e5b50553d26778a92af8ce38445

So it's something with the new osdialog library or its usage.

To test: Blank patch, only core modules. Open file open dialog 50 times.
8341623 failed to show patch files 0 times.
41eb965 failed to show path files 11 times.

**Comment by AndrewBelt** [comment]
Locking because I don't need any more details, thanks.
Issue is around https://github.com/AndrewBelt/osdialog/blob/master/osdialog_win.c#L133-L153

**Comment by AndrewBelt** [comment]
I believe this is fixed now in 7211590cfbb6b0b43db53787d9740eaf5d463f87, thanks to @Rcomian's suggestion.
