### ISSUE TITLE
On Linux, the Rack command is not executable

### ISSUE THREAD

**Issue by teknico** [VCVRack/Rack#1408]
### Details

Operating system: Ubuntu Linux 18.04
Rack versions: v0.6, 1.0, 1.1

### Summary

On Linux, the `Rack` command is not executable.

### Steps to reproduce

Every time I upgrade I have to add executable permissions to the `Rack` command.

### Fix
Adding the command:

```
chmod u+x dist/Rack/$(TARGET)
```

around line 103 of the Makefile should fix it.

**Comment by AndrewBelt** [comment]
It's executable for me, can't reproduce.
What command/program are you using for unzipping?

**Comment by teknico** [comment]
It's Midnight Commander's fault. When using the `unzip` command, the `Rack` file is indeed executable. Sorry for the noise.
