### ISSUE TITLE
How do i upload new modules to share?

### ISSUE THREAD

**Issue by Strum** [VCVRack/Rack#141]
I've made a couple of simple but useful modules and was wondering how to go about uploading them for others to use if they wanted.

New to git and contributing to open source projects and don't know the form.

**Comment by AndrewBelt** [comment]
The best method would be to post the source on your own Github in a new repo.

Later (after v1.0) I'll develop a procedure for those who want their modules to be featured on vcvrack.com, but the standards will be very high.

**Comment by Strum** [comment]
Ok, thanks, not really sure how to make a repo but I can learn.

I've made a stereo mixer with pan and a dual 1 to 5 multiple so far. 

I was going to work on a clock divider/multiplier next and had ideas for a pitch quantizer and a chord generator module like the Q-bit chord. Heaps of things actually, the code is so clean developing new modules is easy. Great work.

If you could give me some guidelines as to what you are looking for in 3rd party modules it might help me in my development.

Thanks again.

**Comment by dekstop** [comment]
A further emerging convention: tag the project with "vcvrack", so it becomes very easy to find new projects: https://github.com/search?q=topic%3Avcvrack&type=Repositories

**Comment by AndrewBelt** [comment]
I should create a list of plugins and their modules and functions in an unofficial document somewhere. I wonder if I should just make the Rack wiki public-editable.

**Comment by Strum** [comment]
That would be a useful resource and might save some duplicated effort , though you know what coders are like, they always want to reinvent the wheel. As for opening the wiki, well I'd suggest thinking long and hard about that, maybe just open it to selected users. Where is it btw?
As far as the modules I am working on I'm not in any great hurry to get them out and would rather take my time and get them all working well, have the code nice a clean and tidy, and get the GUIs looking good before releasing them.

**Comment by AndrewBelt** [comment]
Created page https://github.com/VCVRack/Rack/wiki/List-of-plugins

**Comment by Strum** [comment]
Cool

**Comment by modlfo** [comment]
@AndrewBelt  I tried to add my plugins to the wiki page but it's not public. Can you list my plugins please https://github.com/modlfo/VultModules

Thanks!

**Comment by jackokring** [comment]
I wonder if there is a virtual PAT tester to keep you safe as it would go nice instead of a blank panel. 🥇

**Comment by dekstop** [comment]
And these please:
https://github.com/dekstop/vcvrackplugins_dekstop

**Comment by AndrewBelt** [comment]
@modlfo @dekstop  Thanks, added!

**Comment by antoniograzioli** [comment]
I think I managed to put some of my sources on gitHub:

https://github.com/antoniograzioli/Autodafe

**Comment by AndrewBelt** [comment]
Added https://vcvrack.com/plugins.html and https://github.com/VCVRack/community recently, so closing.
