### ISSUE TITLE
Update to 1.1.0 wrong link

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Rack#1410]
### Details
Clicking on update to Rack 1.1.0 brings user to VCVRack homepage. `https://vcvrack.com/`

Operating system: win7
Rack version: v1.0.0

### Summary
The link in the Help menu brings users to the home page. I expected it to download, wishful thinking! It should instead bring users to the download for OS page `https://vcvrack.com/Rack.html`

Also there is no changelog link in the help menu as is the case with plugin updates.

### Steps to reproduce
N/A

**Comment by AndrewBelt** [comment]
The home page is good enough, people will figure it out.

**Comment by Coirt** [comment]
@AndrewBelt 
 I can create an new issue if you prefer, but it is minor.
There is no changelog link in the help menu as is the case with plugin updates. Has that changed in v1.1.1.

**Comment by squinkylabs** [comment]
I literally could not find it, and I tried.

**Comment by Coirt** [comment]
Same more or less it is not obvious where to download from that page.

@AndrewBelt
