### ISSUE TITLE
Regression Error - Case sensitivity in plugin manager

### ISSUE THREAD

**Issue by sbcook0** [VCVRack/Rack#1412]
### Details

Operating system: Win10
Rack version: v1.1.0

### Summary
The plugin manager has reverted to case sensitive sort. This was fixed in v0.6 see issue #861

**Comment by AndrewBelt** [comment]
Reverted in 2fb6c9f

**Comment by BoscoRemus** [comment]
If this was fixed in, "This was fixed in v0.6 see issue #861" why was it not in v1, but returned again in v1.1.0... 

I say we should ditch the case sensitive in the developer list since not all developers have a company listed which starts with capital letters..

**Comment by AndrewBelt** [comment]
>I say we should ditch the case sensitive in the developer list

Not sure if I was clear, but this was fixed in 2fb6c9f, thus why this issue is closed.
