### ISSUE TITLE
1.1 not opening on OSX 10.14.5

### ISSUE THREAD

**Issue by Skeyelab** [VCVRack/Rack#1414]
### Details

Operating system: OSX 10.14.5
Rack version: v1.1
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

### Summary

Attempting to open Rack.app, I get this (screenshot): http://cloudapp.skeyelab.com/8ca6b355332c

### Steps to reproduce

Open Rack in 10.14.5

**Comment by AndrewBelt** [comment]
https://twitter.com/vcvrack/status/1142123704215904257
