### ISSUE TITLE
Version 0.3.2 Flags AVG virus warning in Windows 10

### ISSUE THREAD

**Issue by stutzjr** [VCVRack/Rack#142]
OS: Windows 10 Home 64 bit
Version: 0.3.2

Warning raised by AVG AntiVirus Free resident "CyberCapture" monitor:
"This file might be dangerous
Rack.exe
It's been submitted for interrogation at the AVG Virus Labs"

I don't recall having any issues with version 0.3.1.

**Comment by AndrewBelt** [comment]
Thanks for letting me know. No idea how to "fix" though.

**Comment by AndrewBelt** [comment]
These results all look clean. https://www.virustotal.com/#/file/1e050181717ce66ae2a995fae7d6094e444f3028f4afdbad75ab80f71e8f61b5/detection

Also,

>It's been submitted for interrogation at the AVG Virus Labs"

Now I know how to steal everyone's files under the radar. Just make an anti-virus scanner!

**Comment by stutzjr** [comment]
As long as you can confirm the current download is good, would including an MD5 on the page add any precaution against malware injection?

**Comment by AndrewBelt** [comment]
Ideally that would be best, but it would clutter the design too much to be worth it to the 2-3 people that actually check it.

**Comment by stutzjr** [comment]
fair enough, thanks for checking it out anyway

**Comment by AndrewBelt** [comment]
Closing because there's not much I can do about it.
