### ISSUE TITLE
Could not open GLFW Window on Windows 10 

### ISSUE THREAD

**Issue by alexxmed** [VCVRack/Rack#1421]
![VCVRackError](https://user-images.githubusercontent.com/16687076/60364076-435ee900-99b3-11e9-956d-bb99d826fbcd.png)

### Details

Operating system: Windows 10 Pro 64 bit
Rack version: v1.0.0 
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):
Intel(R) HD Graphics 2000 w 1796 MB into 1920x1080 Samsung Monitor
OpenFL Version 3.1
Driver Version 9.17.10.4459 5-19-2016
### Summary
Can't run VCVRack because system reports "Could not open GLFW window. Does your graphics card support OpenGL 2.0 or greater? If so make sure you have the latest graphics driver installed."
### Steps to reproduce
Install and attempt to run VCVRack on a Dell Optiplex 790 I7 2.8 GHz 4 GB RAM. VCVRack immediately reports the error. 

I have attached a screen shot showing my video adapter should support OpenGL 3.1.

**Comment by AndrewBelt** [comment]
Although Intel HD 2000 graphics might claim that it supports OpenGL 3.1, users in the last 2 years have never had success with it, so I think it's safe to say that it can't run VCV Rack.

**Comment by alexxmed** [comment]
Thanks.
