### ISSUE TITLE
Expanders get not updated when moving a group of modules with MOD-key

### ISSUE THREAD

**Issue by stoermelder** [VCVRack/Rack#1423]
# Details

Operating system: Windows 10 1903
Rack version: v1.1.0

### Summary

When moving a group of modules with holding down the MOD-key the members `rightExpander.module` and `leftExpander.module` of the modules get not updated. 
Moving a single module updates the members as expected.

### Steps to reproduce

Move a group of modules and check the the members of the first or last module (when "merging" more groups even more modules have wrong expanders),

**Comment by AndrewBelt** [comment]
Thanks! Fixed in 266b63d
