### ISSUE TITLE
Incorrect password on a valid vcv account on version 1.1.0

### ISSUE THREAD

**Issue by ysig** [VCVRack/Rack#1426]
### Details

Operating system:
Rack version: v1.1.0
OS: Linux Mint 18 (Sarah)

### Summary
I get incorrect password when I am trying to log in with a valid vcv-account.
(As the program is able to connect to the internet you can also add an option of doing authentication, by checking if it is authenticated for example on google chrome.)

### Steps to reproduce

Type a valid email-account and password, that has small letters - capital letters, numbers and slashes.

**Comment by AndrewBelt** [comment]
Email contact@vcvrack.com for account assistance.

**Comment by ysig** [comment]
My account seems to work on the vcv-rack site and in the windows version.
(Issue still there in v.1.1.0)

**Comment by AndrewBelt** [comment]
What is the error message?

**Comment by ysig** [comment]
Incorrect password (but the password is correct it is a copy paste I made
multiple times :)).

Στις Δευ, 1 Ιουλ 2019 στις 9:18 μ.μ., ο/η Andrew Belt <
notifications@github.com> έγραψε:

**Comment by AndrewBelt** [comment]
Perhaps a UTF-8 issue with non-ASCII7 passwords? If you manually type it, does it work?

**Comment by ysig** [comment]
No I have the same problem :(
(v.1.1.1)

**Comment by ysig** [comment]
I updated the version on another ubuntu `Ubuntu 16.04.6 LTS` system that I have and I have the same problem having as a result, that I can't access any of the other than the core libraries.
Will you please fix this problem? I guess it is not something really complicated.

**Comment by AndrewBelt** [comment]
I can't fix a problem I can't reproduce.

**Comment by ysig** [comment]
I changed my password and now it works.
Anyway strange error, maybe it had to do with characters although I typed it manually a lot of times.
Thanks for your time.
