### ISSUE TITLE
libsamplerate failing on 10.12.6 with XCode 9

### ISSUE THREAD

**Issue by mhetrick** [VCVRack/Rack#143]
OS (if applicable): 10.12.6
Version (or "dev" if compiling from source): dev

The most recent commits fixed GLFW and Jansson compilation for me. I'm now running into a failure when compiling libsamplerate, specifically the audio_out.c example. It is unable to find Carbon. Is it possible to compile the library and skip the examples?:

/Applications/Xcode.app/Contents/Developer/usr/bin/make -C libsamplerate-0.1.9
Making all in M4
make[2]: Nothing to be done for `all'.
Making all in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CC       samplerate.lo
  CC       src_sinc.lo
  CC       src_zoh.lo
  CC       src_linear.lo
  CCLD     libsamplerate.la
Making all in doc
make[2]: Nothing to be done for `all'.
Making all in examples
  CC       sndfile-resample.o
  CCLD     sndfile-resample
  CC       varispeed-play.o
  CC       audio_out.o
audio_out.c:38:3: warning: redefinition of typedef 'AUDIO_OUT' is a C11 feature
      [-Wtypedef-redefinition]
} AUDIO_OUT ;
  ^
./audio_out.h:9:28: note: previous definition is here
typedef struct AUDIO_OUT_s AUDIO_OUT ;
                           ^
audio_out.c:435:10: fatal error: 'Carbon.h' file not found
#include <Carbon.h>
         ^~~~~~~~~~
1 warning and 1 error generated.
make[2]: *** [audio_out.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [lib/libsamplerate.dylib] Error 2

**Comment by AndrewBelt** [comment]
Possible fix with 6216171. `git pull` and try it now. You might need to delete the libsamplerate-* directory.

**Comment by mhetrick** [comment]
Great, thanks! I got most of the way through compilation. I'll open a new issue for the new error.
