### ISSUE TITLE
VCV Rack + UAD plugins in HOST :(

### ISSUE THREAD

**Issue by z-plane** [VCVRack/Rack#1430]
### Details

Operating system: OSX 10.13.6
Rack version: v1.1.0
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): UAD Octo Core

### Summary
UAD plugins crash VCV rack when loaded via host

### Steps to reproduce
load UAD plugin, instant death to VCV

**Comment by AndrewBelt** [comment]
We have been able to reproduce this, pending on a fix.

**Comment by SmoothSailingMusic** [comment]
@AndrewBelt Just posted a work around in the forum a couple of days ago.
https://community.vcvrack.com/t/uad-working-in-rack-w-blue-cat-patchwork/4634

I have zero coding background so tagging you in this just in case it gives you some sort of clue as to what may be going on.

**Comment by AndrewBelt** [comment]
A fix has been made for the next update to VCV Host.

**Comment by AndrewBelt** [comment]
Fixed in VCV Host 1.0.3.
