### ISSUE TITLE
Paste login credentials using dvorak layout

### ISSUE THREAD

**Issue by dromer** [VCVRack/Rack#1431]
### Summary

Currently it is not possible to paste login credentials into the UI. When working with a password manager there is no other way and when you have any decent passwords they are impossible to remember or type manually.

### Proposed design

Make sure the input fields for the login-form allow pasting from a paste-buffer (ie. Ctrl+V)

**Comment by AndrewBelt** [comment]
It works for me. What's your OS, Rack version, and steps to reproduce?

**Comment by dromer** [comment]
Hmm interesting. I'm on Linux, latest 1.1.0 zip

**Comment by AndrewBelt** [comment]
Still can't reproduce

**Comment by dromer** [comment]
I'm trying to copy text from all kinds of programs and cannot paste anything in the input fields from the paste buffer. Debian stable with fluxbox btw (not that it should matter).

**Comment by AndrewBelt** [comment]
Comment with additional information if issue is still present.

**Comment by dromer** [comment]
This still doesn't work in the latest version on linux.

I'm not sure what "additional information" you want.

`ctrl+c/v` or `middle-button` or `shift+insert` do not input text from any of the available paste buffers.

**Comment by AndrewBelt** [comment]
"Additionally information" includes information that would allow me to reproduce your issue such as your Linux distro, keyboard layout, etc. It works on my Arch Linux machine, so I need enough information about your system for me to experience this bug myself, in order to find the cause on your machine.

**Comment by dromer** [comment]
Debian stable (buster), fluxbox window manager and plain X11 (not wayland or anything).

A keyboard that has the keys `ctrl`, `c` and `v`.

**Comment by AndrewBelt** [comment]
QWERTY US keyboard layout?

**Comment by dromer** [comment]
What does the keyboard layout matter exactly? I press the keys ctrl+c and ctrl+v

If you really must know I use us-dvorak, but the keys that are sent to the program are exactly what I said. I can type into the fields normally.

**Comment by AndrewBelt** [comment]
Aha, I was just making guesses but that's likely it. Key commands use keycodes instead of OS scancodes. Text input is different than both of those, as that uses OS abstractions of text input in X11 windows. I might switch to using scancodes for key commands in Rack v2, but I'm not sure if the benefits outweigh the issues.

**Comment by dromer** [comment]
Hmm, but how can I type normally into the textfields then? is this not done using scancodes?

I'm very much confused (this is why I'm not a GUI programmer ..)

**Comment by dromer** [comment]
I guess this is why I'm not a GUI programmer ...

I can imagine there are loads of people out there not using qwerty though. Then again many other layouts will have c & v in the same location so practically it won't matter to those I guess.

**Comment by AndrewBelt** [comment]
>is this not done using scancodes?

I just said, "Text input is different than both of those".

I will look into switching to scancodes, but it will require extensive testing.

**Comment by dromer** [comment]
Ok top. Much appreciated. For now I changed my password to something utterly simple so I can type it without any hassle, but who knows .. somebody might steal all my free modules :o

**Comment by AndrewBelt** [comment]
Took a look at this. I can't figure out how to use GLFW's key input in such a way that correctly works on QWERTY, Dvorak, AZERTY, etc. Neither `key == GLFW_KEY_Q` nor `scancode == GLFW_KEY_Q` are true when pressing the key labeled "q" with a Dvorak layout.

**Comment by dromer** [comment]
What if you use `glfwGetKeyName()`?
(just browsing the GLFW docs to see what you're up to)

**Comment by AndrewBelt** [comment]
It returns a string which I'd rather not deal with and returns null for nonprintable keys.

**Comment by AndrewBelt** [comment]
Rack v2 has fixed key commands for all keyboard layouts, including AZERTY and Dvorak. See https://community.vcvrack.com/t/rack-development-blog/5864/55

**Comment by dromer** [comment]
Awesome! Looking forward to it :)
