### ISSUE TITLE
Allow MIDI notes to be mapped to VCV switches using MIDI MAP module

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#1436]
### Summary

Allowing MIDI notes to toggle controls in VCV modules would allow all kinds of creative uses, the most obvious being triggering a bunch of different things by (for example) mapping MIDI notes to mixer mutes on a VCV mixer.

### Proposed design

MIDI Map accepts note events. maps note on -> parameter value max. note off -> parameter value min.

**Comment by gabrihyper** [comment]
And, please, allow the option of momentary (note on -> max; note off -> min) or toggle (alternating pair of note on/off -> max ->min)

**Comment by AndrewBelt** [comment]
This seems like a job for a third-party plugin. I don't think it's likely that a new "GATE-MAP" module will be released.

**Comment by stoermelder** [comment]
Can be done with available modules without much effort.
![1](https://user-images.githubusercontent.com/47640667/60508501-f2106b80-9cca-11e9-9ebf-4ab52b13f703.gif)

**Comment by squinkylabs** [comment]
Don't want a new module, but I guess there is something about midi map module that makes it impossible to use the note commands? I just thought it was a simple omission.
