### ISSUE TITLE
Generic module/panel extension for controls with missing ports

### ISSUE THREAD

**Issue by limstepf** [VCVRack/Rack#1437]
### Summary

Offer the possibility to spawn missing input ports for controls of any module in a generic module/panel extension. 

#### Preceding discussion
There's a related discussion, originally about MIDI-Map, that spawned the idea for this feature request: https://community.vcvrack.com/t/vcv-midi-map-shortcomings-ideas-vs-generic-rack-extensions/4416

### Proposed design

New ports can be simply added/requested by a control's context menu. In this example I'd like to have ports for the gates of the step sequencer:
![Adding new ports](https://i.imgur.com/Oc6CSYw.png)

New ports populate the proposed module extension, which gets placed to the ride side of a module. In case a module has its own/further module extension, the extra ports extension shall be placed to the outer right, after any other extensions in between.
Only a single additional port can be spawned for each control, so the option too add a(nother) port should disappear in the context menu once its port has been added.
![Module extension](https://i.imgur.com/jhNZMg6.png)

The module extension adapts in size as needed. Ports can be removed again, and their labels can be changed too; both via context menu.
![Module extension adapts in size](https://i.imgur.com/3ml4RlI.png)

Depending on the type of the control (knob, switch, button, slider) a different, standardized signal mapping is used, probably similar to how MIDI-Map does it.

**Comment by AndrewBelt** [comment]
I think this is a bad idea. Dynamic panels have all sorts of problems. The best solution is to make the panel good in the first place.
