### ISSUE TITLE
Since V1.1.1, some patch don't laod

### ISSUE THREAD

**Issue by Dom2Dom99** [VCVRack/Rack#1438]
### Details

Operating system: windows 10
Rack version: v1.1.1
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): Nvidia GTX 9700, Focusrite Claret 4pre USB

### Summary
When i whant to load patch, some are laoded, some not. when patch is not loaded, nothing appears, never box nor incompatibylity or absent module, nothing change. previous patch stay loaded but the news is just ignored.
I test with the 0.6.2c, all is ok. patch are loaded normally and change normally after selection in VCV explorer.

### Steps to reproduce
just test with lot of patch, if all are loaded normally

**Comment by AndrewBelt** [comment]
Rack v0.6 patches are backwards compatible with Rack v1. If the patch contains a plugin and module slug that are not installed on your computer, a dialog box will display with a list of unavailable modules. Of course, Rack can't load what doesn't exist.

**Comment by Dom2Dom99** [comment]
No, it's not a problem of compatibility modules, it is a problem of loading of patch.
i select a certain patch and NOTHING happen. i select another pacth and he load correct, later i select another and again he don't load.... nothing, nerver message, never change of screen, zero activity.
Sorry for my english but... this is a bug.
if i use V0.6.2c all of these patch are loaded without difficulty.
;)

**Comment by AndrewBelt** [comment]
I agree, if a v0.6 patch cannot load for any reason other than a plugin/module being unavailable, it is a bug. So can you elaborate on how I can reproduce this? Perhaps attach a .vcv patch that demonstrates the behavior?

**Comment by Dom2Dom99** [comment]
yess with pleasure. i will do now... take a minute.
:))

**Comment by Dom2Dom99** [comment]
i can't attach .vcv
box say "we don't support that file type"
:/

**Comment by Dom2Dom99** [comment]
[Vult Modules Series – Flux Quad Voltage Processor Example 3.txt](https://github.com/VCVRack/Rack/files/3346895/Vult.Modules.Series.Flux.Quad.Voltage.Processor.Example.3.txt)
changed extension to txt. it's the only way to attach .vcv for me
:)

**Comment by AndrewBelt** [comment]
It loads fine for me, except "Erwin" from AezelpenModules is unavailable. Does this screenshot match yours?

![2019-07-01-143346_1169x825_scrot](https://user-images.githubusercontent.com/338179/60458696-5240d800-9c0d-11e9-8c74-89e84d626bf9.png)

**Comment by Dom2Dom99** [comment]
no, sceenshot match previous patch wich are good loaded.
if i laod with V0.6.2c yess, it is.
:(

**Comment by AndrewBelt** [comment]
Can you post a screenshot of the patch with your Rack v0.6? I would guess that it matches except for the missing AezelpenModules module.

**Comment by Dom2Dom99** [comment]
there it is :
![vcv 0 6 2](https://user-images.githubusercontent.com/52319653/60459526-baa9ac80-9c41-11e9-93c1-b686560e1171.jpg)

**Comment by Dom2Dom99** [comment]
and there is the V1 version :
same name of patch but ... old patch.
![vcv](https://user-images.githubusercontent.com/52319653/60459580-dad96b80-9c41-11e9-89b3-db7d87d25e43.jpg)

**Comment by AndrewBelt** [comment]
My screenshot looks the same as your Rack v0.6 screenshot (minus AezelpenModules). Are you sure you're opening the correct patch?

**Comment by Dom2Dom99** [comment]
yess, 100% sure.
if you douts, i can record a video if you want.
i starded vcv in admin mode but same problem.
:/

**Comment by Dom2Dom99** [comment]
it's a mp4, change extension from txt to mp4.

[2019-07-01 21-21-50.txt](https://github.com/VCVRack/Rack/files/3347051/2019-07-01.21-21-50.txt)

**Comment by Dom2Dom99** [comment]
captured with OBS

**Comment by AndrewBelt** [comment]
Could you post your log.txt from the [Rack user folder](https://vcvrack.com/manual/FAQ.html#where-is-the-rack-user-folder) after attempting to load the patch?

**Comment by Dom2Dom99** [comment]
yes.
voila
:)
[log.txt](https://github.com/VCVRack/Rack/files/3347561/log.txt)

**Comment by AndrewBelt** [comment]
Unfortunately I don't an issue in the log.

**Comment by Dom2Dom99** [comment]
if i'm only one to have this... go ahead and leave this problem.
i can't understand... maybe african marabout would have a solution...
:D

**Comment by Dom2Dom99** [comment]
Ok. i tried to save a new named version with 0.6.2c, and open with V1.1.1.
Work !!!
I feel it's a problem of Rights, or adminitsration files... beetween 2 versions.
i have to resave each patch with a new name and switch on V1.1 after that.
Don't spend more time on this issue and close.
thank you really
:)
