### ISSUE TITLE
Allow partial range (min/max value) to MIDI MAP controllers 

### ISSUE THREAD

**Issue by gabrihyper** [VCVRack/Rack#1439]
### Summary
User-defined range of MIDI MAPPED controllers

Often, it is not necessary to allow a midi controller tracing the entire range of a knob values, but only a partial part of it. Furthermore, in many cases the limited resolution of midi controller (7 bits) doesn't allow to obtain a decent precision.
### Proposed design
In Ableton Live there is the possibility to define the min/max range of an assigned controller referred to the corresponding parameter. I would like the same feature to be implemented in the midi-map module of VCV rack (see the included screenshot of ableton feature). 
![Schermata 2019-07-01 alle 18 26 18](https://user-images.githubusercontent.com/36381055/60452514-f5561980-9c2e-11e9-8f15-94832212a933.jpg)
Also, it would be useful to allow the midi-map module to be enlarged horizontally, in order to see all the text of the parameters and controllers, which, due to the small size, often remains partially hidden.

**Comment by AndrewBelt** [comment]
The feature that sets VCV Rack apart from other DAWs is the ability to use CV through patch cables to patch anything and manipulate your signal. If you need to rescale your MIDI parameters, I recommend using MIDI-CC to obtain CV and patch it to a module designed for rescaling. If you need to modulate a virtual parameter that doesn't have a CV input, you may use [PackOne by Benjamin Dill](https://vcvrack.com/plugins.html#PackOne).
