### ISSUE TITLE
Change signal color for mono input ports

### ISSUE THREAD

**Issue by catronomix** [VCVRack/Rack#1441]
It's a bit confusing at the moment with poly cables. It's not clear from module connectors if they accept poly inputs or not, and difficult to expect module makers to adhere to 1 standard for indicating so.

It would be much clearer if input ports connected to a poly cable were to only turn blue when they can actually accept multiple channels, This way it's immediately clear what will happen to the signal when plugged in any input port (blue when poly, default red-green when mono)

**Comment by stoermelder** [comment]
I like to gereralize this feature request: We have now in Rack v1 tooltips for parameters, which are great.
I like to suggest tooltips for ports. With these developers can add some information about polyphony, voltage-ranges, trigger behaviour etc. directly to the port.

**Comment by AndrewBelt** [comment]
@stoermelder Could you post a new issue for that?

**Comment by AndrewBelt** [comment]
There is no way to tell whether an input port is "polyphonic". Plugins simply call or not call
```cpp
inputs[...].getVoltage(channel);
```
to inspect channels higher than 0.
