### ISSUE TITLE
Feature Request: Patch Import

### ISSUE THREAD

**Issue by aptrn** [VCVRack/Rack#1443]
### Summary

Importing saved patches without clearing the whole Rack.
The issue this would solve is scalability on complex patches.

This was already proposed in   #129, #209 , #234, #342, #1046 and #1176 but I thought it could be nice to get it summed up in here and adding my thoughts about it. 
If it's not, please close this issue.

### My Experience

For now I'm having two kind of sessions when using Rack; ones about random experiments, brainless patching to discover things I like, and ones about taking puzzle pieces togheter to assemble a single coherent patch that I can play live, mainly shifthing from one logic to the other smoothly.
For now my workflow is paper-based, whenever I save something during experiment sessions I do take notes about what is going on and how I can reproduce this when making a more complex patch. Issues with this method are copying stuff from notes takes time and won't always get to same results, due to my inaccuracy and general modular mutability. I sometimes use single modules presets too, in order to recall main modules parameters (usually for timbres); but it's not applicable for a patch of 10-15 modules.
The ability to import other patches would save me lot of time and would be much more accurate than my eye and ear.

### Proposed design

The implementation could be divided in three subfeatures, with different difficulties and development time spans.

The main theme I think is about an "Import" button under File dropdown menu which simply opens an already saved .vcv file without clearing the whole rack. Implementing this could be easy and fast  I think and would already solve my problem.

As proposed in other feature requests, saving subsections of patches (always as standard .vcv files) with rectangle selection could be nice too. Directly exporting what you need without saving a copy of your patch and clearing modules you won't use when importing. It could be achieved always in the File dropdown menu as a "Export Rectangle" button and then having a selection tool to choose modules to be exported. This is actually not that game-changing for me though and the implementation could be not worth it.

Third and most complex one could be actually a module which loads other .vcv patches, replicating a whole rack in a single module istance. This would lead to a subpatch system like in Max or Pure Data and should be caring about macros, CVs and routing between main and sub patches. This could be actually a major update for future Rack versions but it's up to @AndrewBelt deciding where Rack should go during next few years, this won't be discussed here.

**Comment by aptrn** [comment]
### Update
The issue is perfectly solved with the STRIP module by @stoermelder, thank you a lot Ben. 
[https://github.com/stoermelder/vcvrack-packone/blob/v1/docs/Strip.md](url)

**Comment by modman2019** [comment]
yes patches is the word. thanks
