### ISSUE TITLE
Loading module presets can cause wrong expander pointers

### ISSUE THREAD

**Issue by stoermelder** [VCVRack/Rack#1444]
### Details

Operating system: Windows 10 1903
Rack version: v1.1.1

### Summary

Information about expanders are loaded from module presets and can point to wrong modules when the same module id exists within the patch.

### Steps to reproduce

Save a preset of any module and load the preset into the same model in another row. The fields `rightExpander.moduleId` and `leftExpander.moduleId` point to modules in the wrong row.

**Comment by AndrewBelt** [comment]
Thanks, fixed in f855667
