### ISSUE TITLE
Component Placement Incorrect When Using Helper.py Script

### ISSUE THREAD

**Issue by Eoin-ONeill-Yokai** [VCVRack/Rack#1445]
### Details
When using the helper script to layout components on a module, it is often the case that the y position can be incorrectly placed too high on the module. This sometimes happens to every component on a given module design but sometimes some components can end up being placed in the right area. I have a file that can reproduce my issue. The document is correctly set to `mm` for all unit scale settings.

OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 4.19.49-1-MANJARO
Rack version: Master (139f9a0da3694aed)
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): N/A

### Steps to reproduce
- Try the attached file to see if you get the same results I do. When trying the file below, the output jacks (and others) are often misaligned on the y axis compared to the desired location. You can examine the SVG in inkscape to get a sense of the document layout / setting.

[rack-test.zip](https://github.com/VCVRack/Rack/files/3352485/rack-test.zip)

**Comment by dheles** [comment]
@Eoin-ONeill-Yokai There is a transformation on the component layer `transform="translate(0,27.958328)` that is adjusting the coordinates of all the shapes on that layer. The helper script does not take this adjustment into account, so it places the components 27.958328mm too high. If you remove the transformation and then individually adjust the shapes coordinates accordingly, they should render correctly in vcv rack (once you re-run helper.py & make).

**Comment by AndrewBelt** [comment]
I think if you group and then ungroup the components, the transformation will be normalized.

**Comment by Eoin-ONeill-Yokai** [comment]
I'll give that a try when I get some more time to work on my VCVRack project. Thanks!

**Comment by AndrewBelt** [comment]
Comment if issue is still present. Closing.
