### ISSUE TITLE
Return JACK-MIDI support

### ISSUE THREAD

**Issue by polyzium** [VCVRack/Rack#1450]
I just realized I made an issue in the wrong repository lol

### Summary
Since Rack 0.6.0 (or so), JACK-MIDI is no longer present in any of the MIDI modules (at least in the official builds). I'd prefer JACK over ALSA because of better timing/rate on stock Linux kernels. Getting good rate with ALSA would require changing and recompiling the kernel, which is something I don't want to do.
JACK-MIDI is still not present in 1.1.1. Any plans on getting it back?
![image](https://user-images.githubusercontent.com/22579935/60677186-70b30780-9e89-11e9-9fb6-53843688baa1.png)

### Proposed design
N/A

**Comment by AndrewBelt** [comment]
Added JACK MIDI in 2b0e8350e7c5f4396fac4acc4cc9d2714293cbb1
