### ISSUE TITLE
Make dep fails on RtMidi with Jack support enabled (macOS 10.14)

### ISSUE THREAD

**Issue by liquidcitymotors** [VCVRack/Rack#1452]
### Details

Operating system: MacOS 10.14.5
Rack version: v1.dev.11518f9
Hardware relevant to your issue: Macbook Pro Mid 2015

### Summary

The build of the RtMidi dependency fails with Jack support enabled on MacOS 10.14.5.

Here is the error message:

```
RtMidi.cpp:3407:5: error: use of undeclared identifier 'sem_timedwait'
    sem_timedwait( &data->sem_cleanup, &ts );
    ^
```

It is preceded by a number of deprecation warnings such as this:

```
RtMidi.cpp:3257:3: warning: 'sem_init' is deprecated [-Wdeprecated-declarations]
  sem_init( &data->sem_cleanup, 0, 0 );
  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/semaphore.h:55:42: note: 
      'sem_init' has been explicitly marked deprecated here
int sem_init(sem_t *, int, unsigned int) __deprecated;
                                         ^
```

When altering the Makefile in dep so that ```--with-jack=no```, the build is successful.

I did some research, but I do not have the knowledge to suggest a fix to RtMidi. I worried it might get messy if I reported the issue there before you had a chance to look at the situation.

### Steps to reproduce

On MacOS 10.14.5 (and likely earlier versions):
Clone the repository
Update the submodules
Attempt to build the dependencies

**Comment by AndrewBelt** [comment]
Fixed in 4c6255e
