### ISSUE TITLE
Copy cable color on ctrl+shift drag

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Rack#1453]
### Summary
The ability to copy the current cable colour on ctrl+shift would be a nice feature. I'm forever looping through cableColors just to get to the first index.

### Proposed design
on ctrl+shift drag on an in/out port copy the current color index.

**Comment by wapiflapi** [comment]
Love the idea but why not just shift-drag?

**Comment by Coirt** [comment]
Because control will already need to be pressed to copy the input/output

**Comment by wapiflapi** [comment]
Oh right. I misunderstood.

Then I propose that shift drag would just use the same color as last time
again without cycling through colors. Both behaviours are useful I think.

**Comment by catronomix** [comment]
> Love the idea but why not just shift-drag?

Or because shift could be used for another very useful feature: https://github.com/VCVRack/Rack/issues/1482

**Comment by AndrewBelt** [comment]
I don't want another key command, so I've added a poll for the default behavior. https://community.vcvrack.com/t/poll-when-cloning-a-cable-with-ctrl-click-should-the-color-be-copied-as-well/9068

**Comment by AndrewBelt** [comment]
Due to early poll results, I went ahead and made cable cloning copy the original cable's color.
