### ISSUE TITLE
Crashes when module preset is pasted to the rack

### ISSUE THREAD

**Issue by pgatt** [VCVRack/Rack#1455]
### Details

Operating system: Mac OS 10.14.5
Rack version: v1.1.1
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): None that I know of

### Summary
Copying a preset to a blank part of the rack used to create the module where the mouse was at or nearby if it isn't empty.

### Steps to reproduce
1. Mouse over a module 
2. Copy preset
3. Mouse over blank rack
4. Paste preset
5. Crash.

This worked in v0.6. Maybe it wasn't supposed to work then but it did.

**Comment by pgatt** [comment]
[](url)https://www.dropbox.com/s/fk39m5sczqeeldv/log.txt?dl=0

**Comment by AndrewBelt** [comment]
Can reproduce, probably simple fix.

**Comment by pgatt** [comment]
Thanks Andrew

**Comment by stoermelder** [comment]
Add
```
// Reset ID so the Engine automatically assigns a new one
mw->module->id = -1;
```
after
https://github.com/VCVRack/Rack/blob/2f8af62b6e24c35691de4d745f8b1eaae26f8b8a/src/app/RackWidget.cpp#L295

**Comment by Coirt** [comment]
Nice find that! Can confirm happens on windows also.

**Comment by AndrewBelt** [comment]
Thanks, that's the correct fix. f3bd8ba
