### ISSUE TITLE
NEW VERSION (0.3.2) Works even less well on PC

### ISSUE THREAD

**Issue by SKYNET23** [VCVRack/Rack#146]
OS (if applicable):WIN 7 ULT SP 1
Version (or "dev" if compiling from source):0.3.2
Well, i had the no buttons and no knobs issue with the last ver (issue #17), but now trying out the new ver i get even less graphics - No anything but LEDs for fundamentals and Befaco - no knobs or buttons again for Audible and E-series...    I tried refreshing, redownloading, and restarting already...  Here is a screen shot 
![rack glitch 32](https://user-images.githubusercontent.com/32086246/30842247-f8a95fec-a24e-11e7-83ff-4884f8dd27e7.jpg)

**Comment by SKYNET23** [comment]
that's a Befaco module on the left and a fundamentals sequencer between the Auds...

**Comment by SKYNET23** [comment]
Any ideas?

**Comment by AndrewBelt** [comment]
If you want, compile GLEW, run glewinfo, and post a gist/pastebin of the result.

Andrew

**Comment by SKYNET23** [comment]
Ok, here is the pastebin-   GLINFO_Andrew_9_2017
I am excited about this software, and have been making patches "in the dark" so to speak -  i hope i can get it to run correctly, any info you can provide would be appreciated, thanks again!

**Comment by AndrewBelt** [comment]
Could you post a URL? I don't know what that ID is supposed to point to.

**Comment by SKYNET23** [comment]
Sorry, i thought it would be a link.  Here is the URL  -     https://pastebin.com/KNLc4T3y

**Comment by modlfo** [comment]
I'm closing this one since it happens in a very old version of Rack. @SKYNET23 If this error still happens with the latest version, feel free to comment.
