### ISSUE TITLE
Plugin GUI greyed out in HOST

### ISSUE THREAD

**Issue by SmoothSailingMusic** [VCVRack/Rack#1460]
When opening Pro 2 Editor in Host in 1.0.2, the GUI is greyed out.

![Screen Shot 2019-07-07 at 2 49 14 PM](https://user-images.githubusercontent.com/51094038/60772638-70a04b00-a0c7-11e9-968b-b51f5314efca.png)

Host does not crash, and the plugin will send its default to my DSI pro 2, but I am unable to change any parameters in the VST.
This VST is critical for integration with VCV.
Works fine in 0.6.2c patches.

![Screen Shot 2019-07-07 at 2 46 35 PM](https://user-images.githubusercontent.com/51094038/60772633-654d1f80-a0c7-11e9-985b-cb4f1c220eb5.png)

### Details

Operating system: OSX 10.14.5
Rack version: v1.1.1
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): DSI/Sequential  Pro 2 connected via USB

### Steps to reproduce
Open codeknobs Pro 2 Editor in Host 1.0.2.

**Comment by Coirt** [comment]
Does the VST use any skins, seen a similar issue with Blue Cats Audio VST's which need to load a default skin, had to be located in the same folder as the VST with BCA.

**Comment by AndrewBelt** [comment]
Interesting, no idea. @RichieHindle

**Comment by RichieHindle** [comment]
I'll see if I can figure out what's happening.  (Codeknobs Pro 2 Editor has a demo version.)

**Comment by SmoothSailingMusic** [comment]
@AndrewBelt @RichieHindle I appreciate you guys looking into this so quickly. Thank you very much :)

**Comment by RichieHindle** [comment]
@SmoothSailingMusic No problem!

I've reproduced the issue, but there's one difference between what you're seeing and what I'm seeing - you say "Works fine in 0.6.2c patches" and there's a screenshot of it working, but for me it fails in both v0.6 and v1.

Would you mind attaching a minimal v1 patch (.vcv file) that fails, and a minimal v0.6 patch that works?  Thanks!

**Comment by SmoothSailingMusic** [comment]
@RichieHindle For sure! Here you go! Zipped and attached below!

[Rack Pro Testing Patches.zip](https://github.com/VCVRack/Rack/files/3388740/Rack.Pro.Testing.Patches.zip)

**Comment by RichieHindle** [comment]
@SmoothSailingMusic: Sorry to keep batting this back to you, but your patches use a lot of modules and VSTs that I don't have, so I can't really test with them.  If I load them up and ignore the errors about missing modules, Pro 2 Editor still comes up blank in 0.6.2, but I'm not sure that tells us much.

If you create a minimal patch that just contains an Audio module and Host instance with Pro 2 Editor in it, does it still work in 0.6.2 but fail in 1.1?  If so, could you attach those patches?

**Comment by SmoothSailingMusic** [comment]
@RichieHindle no worries at all, and sorry about the delay on my end. should work this time
[Rack Pro 2 Test.zip](https://github.com/VCVRack/Rack/files/3403841/Rack.Pro.2.Test.zip)

**Comment by RichieHindle** [comment]
@SmoothSailingMusic: Thanks, that's very helpful.  I can now reproduce the bug, with the Pro 2 editor appearing correctly in Rack 0.6.2c but appearing blank in Rack 1.1.1.

But here's the weird thing: it also appears blank in 0.6 if I build 0.6 from source.  The stock 0.6 works, a freshly-built 0.6 fails, even when using the same Host plugin.  Host doesn't seem to matter, nor does the version of Rack, it's the build of Rack itself that makes the difference.

As far as I can tell, both the stock 0.6.2c and my own build are the same (though the executables are slightly different sizes) and load all the same system libraries in the same order (as reported by DYLD_PRINT_LIBRARIES=1).

So my guess is that something in the Apple toolset has changed since the stock 0.6.2c was built, that affects the Rack process to cause this UI breakage.  That sounds implausible, but I have no other ideas.

@AndrewBelt: Do you have any clues?

**Comment by SmoothSailingMusic** [comment]
Hi @AndrewBelt and @RichieHindle .
I'm on v.1.1.4 and host 1.0.4.
No change as of yet.

**Comment by RichieHindle** [comment]
No, I'm sorry, but I haven't been able to figure out what's causing this problem.  I haven't forgotten about it, but I don't yet have a fix.

**Comment by SmoothSailingMusic** [comment]
@RichieHindle No problem man and I appreciate the reply!

**Comment by SmoothSailingMusic** [comment]
@AndrewBelt @RichieHindle This is now resolved. I was able to get a hold of the developer directly and he released an update today that addresses the issue. I appreciate this being looked into your guys' end regardless. 
Cheers,
Stephen

**Comment by SmoothSailingMusic** [comment]
He didn't indicate anything other than he was fixing it and also making it Catalina friendly.
gooooood ol catalina!

**Comment by RichieHindle** [comment]
OK, thanks.
