### ISSUE TITLE
Module Bypass

### ISSUE THREAD

**Issue by Eurikon** [VCVRack/Rack#1462]
### Summary

Now that we have "Disable Module" i find it hardly useful since it also breaks the signal path flowing through. 
Instead it would be much more useful if the signal is passed on from input to output of the disabled module. 

### Proposed design

Either optional by menu (thus keeping both) or replace the Disable feature  with Bypass.
I'd rather have both, same as in for example Reason where the switch adds 2 options: Bypass / Off .

**Comment by AndrewBelt** [comment]
Obviously not generally possible. It can be implemented per module by the plugin developer though.
