### ISSUE TITLE
Make module browser search in descriptions.

### ISSUE THREAD

**Issue by catronomix** [VCVRack/Rack#1463]
The search function does not search the description of the modules, only the name, author and tags. This removes a lot of modules from the results that should (in natural human thinking) be included. For example if I want to get all flip-flops, and I type this in the search field, Submarine's flip-flop modules don't show, because they use codenames like ff-206, but they do have the useful search term in their descriptions. Or if I type 'octave' to get modules that do octave-related stuff, it omits vult nopskate, although it describes itself as an 'octaver'.

Some basic word filtering which filters out words like 'and', 'the', 'a', etc... could ideally be added, but other than that I imagine it's just a matter of including the description in the search function :)

**Comment by AndrewBelt** [comment]
This has been planned for a couple years and is estimated 2019-Q4. Closing since it's not a feature of Rack.
