### ISSUE TITLE
Helper.py can't parse SVGs from Illustrator

### ISSUE THREAD

**Issue by dheles** [VCVRack/Rack#1464]
### Details

Operating system: MacOS
Rack version: v1.1.0

### Summary

Helper.py can't parse SVGs from Illustrator. 
* Requires the components layer to be identified by an Inkscape label (rather than an ID). 
* Requires the fill colors to be lowercase.

### Steps to reproduce

Generate a panel graphic in Illustrator (rather than Inkscape). 
Save as an SVG file. 
Run helper.py's createmodule command against the file. 
Will fail with the error, "Could not find 'components' layer on panel."

**Comment by ShockValu3** [comment]
Just discovered this. Adobe Illustrator CC.   no component layer found.
