### ISSUE TITLE
General ON/OFF

### ISSUE THREAD

**Issue by nay-seven** [VCVRack/Rack#147]
Hello,
Sometimes, when working on a patch , you need to pause your work and do other things.
Could be useful to have a general ON/OFF switch for Rack, this one will free all cpu and lets you do what you have to do quietly.
As workaround, generally i disable audio interface, but don't free all cpu.

What do you think ?

**Comment by AndrewBelt** [comment]
Would be pretty easy. The only edge case is that the Audio Interfaces would missing their buffer deadlines, so I'd have to check that they handle that well on all audio drivers.

**Comment by nay-seven** [comment]
great !

**Comment by AndrewBelt** [comment]
Added engine pausing/resuming in 35c4e27
