### ISSUE TITLE
Cables are no highlighted when the mouse is moving over an port

### ISSUE THREAD

**Issue by icet99** [VCVRack/Rack#1477]
### Details
Operating system: Windows 10
Rack version: v1.1.1
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): GeForce GTX660 Ti

### Summary
In V0.6x the cables were highlighted while moving the mouse over a cable connected port. This does not work on my Installation in V1.1.1 on the pc I normaly use. I tested this on an other pc, and there it was working as expected.

### Steps to reproduce
Move with mouse over an cable connected port in Rack.

**Comment by AndrewBelt** [comment]
I can't reproduce this, it works for me.

**Comment by icet99** [comment]
Sorry, I made a mistake. The “Cabel opacity” was set to 100%.
