### ISSUE TITLE
VCV Scalar Plugin: support Rack 1.x polyphonic cables

### ISSUE THREAD

**Issue by wjbuys** [VCVRack/Rack#1478]
### Summary
The VCV Scalar plugin only supports 4 channels of quantization with monophonic cables. Using more voices than this requires two instances of the plugin, and manually copy/pasting the presets between them.

For applications that require quantization of > 4 voices, adding support for polyphonic cables to one or all of the inputs/outputs of the plugin would be much more convenient.

### Proposed design
For backwards-compatibility, it's probably wise to keep the layout with the 4 separate inputs/outputs as is, but add polyphonic cable support to one (or all) of the quantization channels.

**Comment by AndrewBelt** [comment]
This is planned.

**Comment by AndrewBelt** [comment]
Closing since this is the VCV Rack issue tracker.
