### ISSUE TITLE
VCV v1.1.1 - MS C++ Runtime Lib Error when duplicate Modul, while holding them

### ISSUE THREAD

**Issue by cxbignekoc** [VCVRack/Rack#1479]
**OS:**
Win7 64 bit
VCV 1.1.1
Bitwig 3.0

Bitwig 3 is running with VCV Bridge 64.dll **not and in use.**

**Issue:**
Duplicate a Modul with **[Strg/Cntrl] +[d]**, while holding the Modul with the left mouse button
to move it to another place.
Microsoft Visual C++ Runtime Library - Freeze/Error
No specific Notification in the Error Box
[OK] - Quit Programm

**Reproduce:**
1. Open Basic Project
2. click and hold a module with the left mouse button,
3. move the Module to a specific place and hold the mouse button, then **[Strg/Cntrl] +[d]** to duplicate
in some cases the error happens **if not:**

4. From 3. hold **[Strg/Cntrl] +[d]** to copy multiple times
in some cases the error happens after around 10 to 15 copies

**Hint:**
Why this procedure?
I use this sometimes in DAW to copy a clip after replace it or in the unfinished process of replacing a clip. I can hold the clip by moving around and **[Strg/Cntrl] +[d]** to make a copy one the initial place while holding the clip.

cheers.

**Comment by squinkylabs** [comment]
Rack doesn't use ms runtime lib. maybe some other program is crashing, not rack?

**Comment by cxbignekoc** [comment]
Interessting. Thanks for that. i have a eye on it.
