### ISSUE TITLE
Cannot compile anymore (MAC)

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/Rack#148]
Tonight I re-cloned the project on my mac.
after cloning and updating submodules I launch

"make dep"

result:

```
tar xf glew-2.1.0.tgz
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
make[1]: *** [lib/libGLEW.dylib] Error 1
make: *** [dep] Error 2
```

10 minutes ago everything was working perfectly...

**Comment by AndrewBelt** [comment]
Remove glew-2.1.0.tgz and rerun `make dep`. Maybe the download was incomplete.

**Comment by antoniograzioli** [comment]
already tried, removed the tgz file and redownloaded. No luck...

**Comment by AndrewBelt** [comment]
Same error after it re-downloads? Can you go to the file https://downloads.sourceforge.net/project/glew/glew/2.1.0/glew-2.1.0.tgz in your browser and download that? Probably SF's mirror is being flaky.

**Comment by antoniograzioli** [comment]
nope, same error even if I put glew-2.1.0.tgz manually in the dep folder...
I had already tried copying another copy of the file I had on my hd...nothing it always says "Unrecognized archive format"

**Comment by AndrewBelt** [comment]
What is the filesize of the archive? What does running `tar zxvf glew-2.1.0.tgz` say?

**Comment by antoniograzioli** [comment]
652 bytes
tar zxvf glew-2.1.0.tgz gives the exact same error...

**Comment by AndrewBelt** [comment]
Looks like http://glew.sourceforge.net/ is down, so it's probably giving you an HTML file saying something along the lines of "SourceForge is a horrible host and you should find an alternative." Attempting to find a mirror...

**Comment by AndrewBelt** [comment]
Try it now after a `git pull` and deleting the archive again. 6723d9e

**Comment by antoniograzioli** [comment]
ok it's working now.
