### ISSUE TITLE
Make Inputs and Outputs MIDI mappable

### ISSUE THREAD

**Issue by dschiller** [VCVRack/Rack#1481]
### Summary

The Motivation is that I created a MIDI Controller which also has TRS Jacks to simulate Connections. To be able to use those Connections I need the Ability to MIDI map Inputs and Outputs in VCV.

### Proposed design

The TRS Jacks send Message Type CC with a Control ID and as Toggle with On and Off Values.
Visually just show a yellow Square like for the Mapping for the Knobs and Buttons. 

Connecting:
The Magic happens by the Order of sending the Data. Means if one connects a Cable to first Jack then VCV recognize this MIDI CC Message and waits for the second CC. If the second Jack is connected VCV connect those two Ports if possible ( Just Inputs to Outputs and vise versa ). A Message would be nice if a Connection is impossible and a Waiting for a possible Port. 

Disconnecting / Repatch:
And the discconnection happens by unplug one of the Ports by getting Message Off Value sended. If only one Cable is disconnected wait for the Second Port to be disconencted or wait for a new possible Conenction of the disconnected Port.

Corner Cases:
If VCV wait for a CC Message from a new Port while Connecting and one send MIDI CC from a Knob by rotating just ignore this for the Connection and wait until a Port MIDI CC will be send.

Stacking - Connecting:
Sending the same MIDI CC On Message again and a new Port.

Stacking - Disconnecting:
Waiting for both MIDI CC Off Messages to find the correct Cable Path.

Stacking - Repatch:
Getting one Port Off Message and waiting for new Port.

Without Stacking:
The good thing is with this Implementation one is also able to use a simple MIDI Controller Button Matrix to simulate Connections.

**Comment by Coirt** [comment]
How would you stack outputs?

**Comment by dschiller** [comment]
@Coirt Hey Phil, that's what I am saying. It's just a start. In a later Phase we can think about this.

**Comment by stoermelder** [comment]
I think this is a job to be done by a special purpose module that interprets MIDI messages the way you describe and creates cables, which is perfectly possible with the existing API of Rack.

**Comment by AndrewBelt** [comment]
Likely won't happen. How would undo history work for example?

**Comment by dschiller** [comment]
Undo could work as normal. Just remove connections in opposite direction. Nice that you close the ticket. @ben That sounds interesting!
