### ISSUE TITLE
"Rack" can't be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by dncnmckn** [VCVRack/Rack#1483]
#1454 # Details

Operating system: macOS Mojave 10.14.5
Rack version: v1.1.1
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): Spec on attached image

<img width="698" alt="Screenshot 2019-07-19 at 09 36 24" src="https://user-images.githubusercontent.com/5285423/61521866-14afbd80-aa09-11e9-8833-ae745d010d0f.png">

### Summary

<img width="532" alt="Screenshot 2019-07-19 at 09 32 06" src="https://user-images.githubusercontent.com/5285423/61521858-0feb0980-aa09-11e9-9028-d47e6f488142.png">

Downloaded the app. opened the app. Apple can't open it to check for malicious software (see attached image). Suggests getting in contact with developer.

### Steps to reproduce

1 - Download macOS link from https://vcvrack.com/Rack.html
2 - double click on it
3 - wait for popup

**Comment by LomasModules** [comment]
Use a right click on the .app and choose open.

https://community.vcvrack.com/t/rack-cant-be-opened-because-apple-cant-check-it-for-malicious-software/4247/12

https://twitter.com/vcvrack/status/1142123704215904257

**Comment by AndrewBelt** [comment]
Duplicate issue

**Comment by dncnmckn** [comment]
Thanks.
