### ISSUE TITLE
stdatomic.h not found

### ISSUE THREAD

**Issue by scoresmexico** [VCVRack/Rack#1484]
### Details

/Users/···/Rack/dep/glfw/src/nsgl_context.h:35:10: fatal error: 
      'stdatomic.h' file not found
#include <stdatomic.h>

Operating system: Mac OS 10.10
Rack version: v1,0
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

I found https://gist.github.com/nhatminhle/5181506 and downloaded a version of stdatomic.h

But when I do 'make run' this came out

c++ -std=c++11 -stdlib=libc++ -DVERSION=1.dev.578d104 -Iinclude -Idep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7 -c -o build/src/random.cpp.o src/random.cpp
src/random.cpp:14:1: error: thread-local storage is unsupported for the current
      target
thread_local uint64_t xoroshiro128plus_state[2];

**It is related? How I can make it work?**

**Comment by scoresmexico** [comment]
I'm building the SDK...

**Comment by AndrewBelt** [comment]
Downloading a random `stdatomic.h` file is definitely not the right way to solve the problem.

Your compiler is too old to support `thread_local`. You need to upgrade your Xcode version (and possibly your Mac version) to compile Rack from source.
