### ISSUE TITLE
VCV-Host: Enhancement HOST-FX CHAIN

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Rack#1485]
### Summary
I can use up to 5-6 different Host-FX on the master chain it would be nice to slim this down a bit. I do not need to use the CV inputs to mod any of these VST's as they're on the master chain, although I sometimes automate the master chain on breakdowns if required or dynamic EQ'ing etc but not often.

### Proposed design
Have a new version of Host which is able to stack/chain plugin instances with a context menu option to move/swap a VST Up/Down the chain. Here is a mock-up. 
![hostFXChain](https://user-images.githubusercontent.com/12150421/61561806-bcf46f00-aa67-11e9-884c-d9d1cca9b5d8.JPG)

and in comparison current master chain:
![masterChain](https://user-images.githubusercontent.com/12150421/61562023-43a94c00-aa68-11e9-8fa8-4f8fc8164a2e.JPG)

Also text scroll on the learned parameter would be an nice enhancement a lot of vst parameters are named in the VST but they mostly have long names which get cut off. e.g. Master Level, Global Input Level. A context menu to turn on/off text scrolling would help with that.

The learn function could work differently as there is added devices in the one Host it can not know which window to call, clicking learn and then clicking the preview icon could negotiate that behaviour. The chain starts from input 1st in chain to 6th and output. Hopefully clicking on another preview button would not close any other opened windows.

**Comment by stoermelder** [comment]
I support this request, because of this: 
A VST chain take advantage of the block processing of VSTs. If I set up an identical chain with multiple Host modules the sample delay sums up the blocksize with each additional VST. A complete chain in one module would result in delay of just one blocksize.

**Comment by AndrewBelt** [comment]
This is the issue tracker for VCV Rack. Send bug reports and feature requests of VCV plugins to contact@vcvrack.com.
We have added this to our internal issue tracker. Comment your email address here if you would like to be informed of future updates to this issue.

**Comment by Coirt** [comment]
@AndrewBelt 

philg@live.ie
