### ISSUE TITLE
v1.1.2 (Windows): can't log in to Library (No response from server)

### ISSUE THREAD

**Issue by DomiKamu** [VCVRack/Rack#1488]
### Details

Operating system: Windows 7 SP1 (64-bit), French.
Rack version: v1.1.2
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): Not applicable.

### Summary

From rack.exe I can't login to Library (using my account),
Everytime I get "No response from server" when I click "Log In".
I don't have this issue by using previous releases.

### Steps to reproduce

From "Library" menu, I enter my login, then password, I get the "No response from server" when I click "Log In".

![image](https://user-images.githubusercontent.com/24851960/61592406-28a71b00-abd3-11e9-94c0-500ba8d2ad1a.png)

**Comment by DomiKamu** [comment]
If I stay logged from v1.1.1, uninstall v1.1.1, install v1.1.2, I get this message instead:

![image](https://user-images.githubusercontent.com/24851960/61592218-8e45d800-abd0-11e9-8b50-78cd1ad8082d.png)

**Comment by joopvdl** [comment]
same here, mac OSX

**Comment by Coirt** [comment]
Works just fine for me win7. Random thought, move the settings-v1 file to another location and retry.

**Comment by joopvdl** [comment]
Triest that on the Mac, didn't help

**Comment by DomiKamu** [comment]
> 
> 
> Works just fine for me win7. Random thought, move the settings-v1 file to another location and retry.

The first test I've done, but... unsuccessfull.

**Comment by DomiKamu** [comment]
...and we're not alone : 
![image](https://user-images.githubusercontent.com/24851960/61595155-d32f3600-abf3-11e9-896e-e3ed4e96ed41.png)

**Comment by AndrewBelt** [comment]
Rack 1.1.2 switched to using Schannel instead of OpenSSL for cryptography. It's likely that Schannel on Windows 7 SP1 either isn't picking up the OS's root certificates or doesn't support TLS 1.1+ or something.

If someone wants to do a full rebuild of dependencies (after running `cd dep; make clean`), uncomment
```cpp
curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);
```
in `src/network.cpp`, and run `./Rack` in the terminal.

**Comment by DomiKamu** [comment]
> 
> 
> Rack 1.1.2 switched to using Schannel instead of OpenSSL for cryptography. It's likely that Schannel on Windows 7 SP1 either isn't picking up the OS's root certificates or doesn't support TLS 1.1+ or something.
> 
> If someone wants to do a full rebuild of dependencies (after running `cd dep; make clean`), uncomment
> 
> ```c++
> curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);
> ```
> 
> in `src/network.cpp`, and run `./Rack` in the terminal.

It's not Windows 7 SP1 specific - some are MacOS users. Thanks for this tip, I'll try it.

**Comment by Coirt** [comment]
Rebuilding atm (win7 sp1) to see if it is reproducible.

**Comment by DomiKamu** [comment]
> 
> 
> Rebuilding atm (win7 sp1) to see if it is reproducible.

I'm rebuilding it to test... Win7 SP1.

**Comment by AndrewBelt** [comment]
As for the Mac users, I believe it is a completely different issue. Rack 1.1.2 enabled certificate verification, but my guess is that the user's Mac installation doesn't have OpenSSL / Secure Transport certificates available in a way what OpenSSL can read them, for some reason.

**Comment by Coirt** [comment]
Build fails with very latest commit

```
-- Installing: C:/msys64/home/Phil/rack-1.1.2_983476f/Rack/dep/lib/cmake/glew/CopyImportedTargetProperties.cmake
make[2]: Leaving directory '/home/Phil/rack-1.1.2_983476f/rack/dep/glew-2.1.0/build'
cd glfw && mkdir -p build
cd glfw/build && cmake -G 'MSYS Makefiles' -DCMAKE_INSTALL_PREFIX="/home/Phil/rack-1.1.2_983476f/rack/dep" -DCMAKE_INSTALL_LIBDIR=lib .. \
        -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF
CMake Error: The source directory "C:/msys64/home/Phil/rack-1.1.2_983476f/Rack/dep/glfw" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make[1]: *** [Makefile:77: lib/libglfw3.a] Error 1
```

**Comment by AndrewBelt** [comment]
Maybe missed the "clone submodules" step?

**Comment by Coirt** [comment]
Thought that was no longer required will retry.

**Comment by Coirt** [comment]
With `curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);` uncommented it takes about 1 second longer to query for updates compared to commented but other than that it checks and updates okay.

I do see `* schannel: failed to decrypt data, need more data` in the terminal

**Comment by therealkitman** [comment]
I have this same issue on my linux opensuse leap 15.0 machine using the pre-compiled linux zip.

**Comment by fractalgee** [comment]
hmmm, was working fine yesterday, but this morning I also have the 'Cannot query updates...' message, though I am logged in via Rack 1.1.2 (MacOS X 10.11.6, Rack 1.1.2). I am off to downgrade to 1.1.1 until this is resolved.....

**Comment by DomiKamu** [comment]
Downgraded to 1.1.1 too, until solved.

**Comment by DomiKamu** [comment]
Why my previous message was deleted? it was not angry, I've just told I go back to v1.1.1 until solved.

**Comment by AndrewBelt** [comment]
It's irrelevant to investigating this bug.

**Comment by nay-seven** [comment]
If this can be useful, i've same issue on Mac Yosemite and El Capitan, 
but it's ok on my Mojave partition

**Comment by alexxmed** [comment]
I am having the same problem and I would really like to be able to resolve it

**Comment by DomiKamu** [comment]
Solved! (Windows 7 SP1) but many Registry keys to add manually (to enabled TLS 1.1 & TLS 1.2), then allowing C:\Windows\system32\lsass.exe from firewall...
![image](https://user-images.githubusercontent.com/24851960/61662946-cb44c400-accf-11e9-870d-9674929c324a.png)

**Comment by AndrewBelt** [comment]
Interesting. Schannel's TLS 1.1 is enabled on all my testing Windows computers so not sure why it isn't on yours. I'm considering switching back to OpenSSL instead of Microsoft Schannel and including Firefox's certificate list in the distribution.

**Comment by Coirt** [comment]
@alexxmed are you on windows 7 SP1 also?

**Comment by DomiKamu** [comment]
Having worked from here: https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-wi

**Comment by alexxmed** [comment]
I am on an IMax running El Capitan.

**Comment by alexxmed** [comment]
I am on an iMac running El Capitan.

**Comment by benjamindauer** [comment]
Same issue, running an iMac on Mojave. Would love to have this resolved.

**Comment by joshkrahn** [comment]
Same here. Macbook Pro running El Capitan.

**Comment by AndrewBelt** [comment]
Can someone using Windows whose 1.1.2 build fails to connect to the internet ("No response from server") confirm that the following build *does* succeed to connect?
[Rack-1.dev.b6e5ad5-win.zip](https://github.com/VCVRack/Rack/files/3420570/Rack-1.dev.b6e5ad5-win.zip)

**Comment by alexxmed** [comment]
i am standing by my iMac, mid 2007, 2 GHz Core 2 Due, 3 GB RAM, 256MB HD, ready to provide information, or try anything to get this working.

**Comment by AndrewBelt** [comment]
I'm sure it'll work on Mac, but here's a dev build. [Rack-1.dev.62179a1-mac.zip](https://github.com/VCVRack/Rack/files/3421383/Rack-1.dev.62179a1-mac.zip). Confirm that this connects to the server.

**Comment by nay-seven** [comment]
For Mac users, and waiting for a fix, we can have several version, so unzip a version 1.1.1 in your download folder, rename it if needed. 
Run it, run the update for plugins, closed it. 
Now start the 1.1.2, your plugins are updated

**Comment by AndrewBelt** [comment]
I'm not looking for workarounds. I'm looking for 1-3 testers of the above Windows and Mac build so I can release this ASAP.

**Comment by nay-seven** [comment]
ooops cross posted...;-)

**Comment by nay-seven** [comment]
just test your version, give me the up-to-date message ! cool

**Comment by AndrewBelt** [comment]
@nay-seven What OS?

**Comment by nay-seven** [comment]
yes, sorry, Mac OS Yosemite 
and yes, the Official 1.1.2 give me the message 'Could not query updates"
gone to test on El capitan

**Comment by AndrewBelt** [comment]
Okay, anyone able to test the Windows build?

**Comment by alexxmed** [comment]
Excellent --. Rack-1.dev.62179a1-mac.zip works.
Whatever you did, it has solved my problem. I was able to log in and update all my modules.
Thank you Andrew.

**Comment by nay-seven** [comment]
confirmed also on El Capitan, thanks

**Comment by joshkrahn** [comment]
Hmm, I just installed Rack-1.dev.62179a1-mac.zip and still get the same "No response" message.

2014 Macbook Pro, El Capitan v10.11.6

**Comment by AndrewBelt** [comment]
@joshkrahn Can you post a screenshot of your screen with the Library menu open, showing the message?

**Comment by fractalgee** [comment]
@Andrew Belt <contact@vcvrack.com> : dev build does the trick on the mac,
so whatever you did solved this, thanks!

**Comment by AndrewBelt** [comment]
For anyone wondering what I did in 27ae93d85ecb851f555c3ffbd6f18355a3d772f8, I added a built-in root certificate list into the Rack distribution, copied from Mozilla Firefox. I thought that all Macs versions and Linux distributions included a root certificate list compatible with OpenSSL at `/etc/ssl/cert.pem` or similar, and I preferred to use the system's list over my own, but it seems that some OS's either 1) don't have that list, or 2) it's in a format not parsable by CURL.

**Comment by joshkrahn** [comment]
@AndrewBelt Thanks 
<img width="390" alt="Screen Shot 2019-07-23 at 3 19 56 PM" src="https://user-images.githubusercontent.com/53202497/61740793-823b5100-ad5d-11e9-8505-5de6f9cc261c.png">

**Comment by DomiKamu** [comment]
Windows 7 SP1 (test on another OS than regular I've fixed)
I confirm build **Rack-1.dev.b6e5ad5-win.zip** is okay for plugin updates.

**Comment by AndrewBelt** [comment]
@DomiKamu Thanks, I'll go ahead and release today.

**Comment by AndrewBelt** [comment]
@joshkrahn Could you do the following test?
- Download and unzip [Rack-1.dev.62179a1-mac.zip (unsigned, verbose CURL build)](https://github.com/VCVRack/Rack/files/3423930/Rack-1.dev.62179a1-mac.zip)
- Open the Terminal. Change you directory to the download location, e.g. `cd ~/Downloads`
- Run `./Rack.app/Contents/MacOS/Rack`
- Does it still give "No response from server"?
- If so, email the terminal output to contact@vcvrack.com, or make sure your tokens are stripped from the output and post it here.

**Comment by joshkrahn** [comment]
@AndrewBelt Yes, I'll post results in a couple hours. Thanks!

**Comment by AndrewBelt** [comment]
Fixed in b6e5ad5515a244af7b051e3551fc04ed3b72e306

Still interested in @joshkrahn's result.

**Comment by joshkrahn** [comment]
@AndrewBelt I followed your instructions above, and jackpot! I am able to log in and update plugins (didn't need to do the last step).

Thanks Andrew, this app/platform is incredible!

-Josh

**Comment by flying-sheep** [comment]
I get the following in 1.1.6:

```
* Connected to api.vcvrack.com (168.235.102.117) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* error setting certificate verify locations:
  CAfile: ./cacert.pem
  CApath: none
* Closing connection 0
```

**Comment by AndrewBelt** [comment]
@flying-sheep What is your OS version and Rack download URL you used to download Rack?

**Comment by flying-sheep** [comment]
Linux, I’m building it into a system package using a modified PKGBUILD script from the AUR, which is apparently not quite finished. It currently ends up with those files:
```
/opt/vcvrack/Core.json
/opt/vcvrack/Rack
/opt/vcvrack/res/ComponentLibrary/*.svg
/opt/vcvrack/res/Core/AudioInterface.svg
/opt/vcvrack/res/Core/AudioInterface16.svg
/opt/vcvrack/res/Core/*.svg
/opt/vcvrack/res/fonts/DejaVuSans-LICENSE.txt
/opt/vcvrack/res/fonts/DejaVuSans.ttf
/opt/vcvrack/res/fonts/ShareTechMono-Regular-LICENSE.txt
/opt/vcvrack/res/fonts/ShareTechMono-Regular.ttf
/opt/vcvrack/res/icon.png
/usr/bin/Rack
/usr/include/vcvrack/**/*.h
/usr/include/vcvrack/**/*.hpp
/usr/share/applications/vcvrack.desktop
/usr/share/licenses/vcvrack/LICENSE.md
/usr/share/pixmaps/vcvrack.png
/usr/share/vcvrack/arch.mk
/usr/share/vcvrack/compile.mk
/usr/share/vcvrack/dep.mk
/usr/share/vcvrack/plugin.mk
```

**Comment by AndrewBelt** [comment]
The AUR script is not managed by VCV and is therefore not supported. Use the download links at https://vcvrack.com/Rack.

**Comment by flying-sheep** [comment]
Sorry, installing things that aren’t managed by my package manager isn’t a thing I do. My system would get too messy.

I figured it out, it’s the location of the Rack binary, i.e. `/opt/vcvrack` on my system.

**Comment by AndrewBelt** [comment]
>Sorry, installing things that aren’t managed by my package manager isn’t a thing I do.

Your only option then is to become the maintainer of your package manager's Rack package, or pay/convince a package maintainer to make your desired changes.

**Comment by flying-sheep** [comment]
Well, I updated the PKGBUILD and it works now, including login.

The way the package works is to make /usr/bin/Rack a script that changes the working directory to /opt/vcvrack, where everything is installed. Loading essential assets from the working directory is weird! Software should be able to be launched from everywhere.

Would you accept a patch that tries to load assets and plugins from /usr/share/vcvrack (or /usr/share/Rack or …)? That would allow people to install the Rack binary into a standard directory in $PATH (e.g. /usr/local/bin or /usr/bin) and to install plugins systemwide.
