### ISSUE TITLE
V1.1.2: Crash on module search

### ISSUE THREAD

**Issue by therealkitman** [VCVRack/Rack#1489]
### Details

Operating system: opensuse leap 15.0
Rack version: v1.1.2
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

### Summary
Found this by sheer chance. Each time I enter a specific search term for a module, Rack crashes. Was searching for 'meter', as soon as I enter 'me' - crash! But any other letters are ok 'mt', 'mr' etc. Only 'me' (so far) crashes rack. Does not occur in previous version.

### Steps to reproduce
Start Rack.
Right click to bring up modules.
Enter 'me' (for meter).
[log.txt](https://github.com/VCVRack/Rack/files/3414344/log.txt)

**Comment by AndrewBelt** [comment]
Update Ohmer since it's crashing Rack.
