### ISSUE TITLE
Info on breaking API changes

### ISSUE THREAD

**Issue by tildebyte** [VCVRack/Rack#149]
Can there be an update to the README, or maybe a changelog?
The recent change to having `init()` for plugins has broken all 3rd-party stuff.

**Comment by AndrewBelt** [comment]
I'll be plowing through API changes until I finish this v0.4.0 release. Hold on to your seats, or use `git checkout v0.3.2` if you want a constant API to use. Unfortunately I'm not tagging the plugins (I forgot), but you can match dates.

**Comment by tildebyte** [comment]
Cool, thx. I managed to sort out the differences pretty quickly.
