### ISSUE TITLE
dev: version control against Rack release

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Rack#1491]
### Summary
Currently I add a new project to a solution in VS and name it the same as the commit (short version) to keep track. If I do a git pull if the change is not significant I rename the project, otherwise it is a clean pull and project.

### Proposed 
Currently dev version says `1.1.2` on make run. Could this be incremented every now and then for commits added to help keep version checking obvious, relating to a release version. There has been a couple of people caught out by the port `assert` added in 1.1.2. Knowing what the next release could be will help builds be sync'd to the release and avoid unnecessary issues arising. Having the version and commit show on make run helps a tonne. 

If the next version is going to be `1.2.0` or `1.1.3` knowing in advanced would make life easier. Even if it's noted in the change log what version it is, at least it will be there for anyone willing to look. If that is not necessary, the next version would still require testing in advanced of the release. Adding the version at that point will show that it is closer to next release.

**Comment by AndrewBelt** [comment]
I don't really understand why you're talking about Visual Studio. Rack plugins don't use Visual Studio.

Usually I set `VERSION` to an actual version string on commits referring to releases and `1.dev.<commit>` for other commits.

Plugin developers don't need to release a new version of their plugins when a new version of Rack is released. That would be an absurd requirement.

The changelog already includes future versions if they exist.
