### ISSUE TITLE
Display tags at bottom of Module Browser tooltip

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Rack#1498]
Not sure how everyone else feels about the tags position changed in `1.1.2` to above the description. My personal opinion is they look much better on the bottom. Could they be moved back to the bottom?

At least there if a dev chooses to include a new line in the description `\n` it gives the tags room to be seen. If the tags are staying there then I'd request to add a new line at the end of tags to give the description and tags room on the tooltip.

It is solely for readability reasons to have newlines sperating tags/description in most cases a one line or few word description can not best describe a module.

Screenshot of 1.1.2 and 1.0.x:
![tagToBottom](https://user-images.githubusercontent.com/12150421/61749382-8e91cf00-ad9a-11e9-8e30-e71aeb47e74b.png)

**Comment by AndrewBelt** [comment]
Changed in Rack v2 to match the order of module boxes on the [VCV Library](https://library.vcvrack.com/).
