### ISSUE TITLE
Add 0 numeric keypad 0 to the - zoom to 100% - shortcut

### ISSUE THREAD

**Issue by AScustomWorks** [VCVRack/Rack#1499]
### Summary

Just noticed numeric keypad 0 key is not mapped to the zoom shortcut.
Thanks to a lot of design apps, my hands are hardwired to this combination:
 Cmd/Ctrl + 0 on the numeric keypad, of course this is on a desktop keyboard, but pretty much all come with numeric keypad.

### Proposed design

The standard way on most apps with zoom functions is to have both the regular number keys and the numeric keypads mapped to do the same thing, so, is it possible to add this?
Thanks!

Edited: the same request goes for ENTER, + and  - keys on the numeric keypad

**Comment by AndrewBelt** [comment]
Added in 69681d2.
