### ISSUE TITLE
Dragging cables to top or bottom of screen should scroll up or downwards

### ISSUE THREAD

**Issue by sanderbaan** [VCVRack/Rack#15]
When you have more then 3 rows of modules and you want to connect a cable from the bottom to a module at the top you cannot do this now, ideally it should scroll up or down when you drag the cable to the top or the bottom of the screen

**Comment by AndrewBelt** [comment]
Good idea!

**Comment by AndrewBelt** [comment]
Fixed with dbd4e44eda34189ed626429462f76e57ca25c66a
