### ISSUE TITLE
plugins broken with Modules() change

### ISSUE THREAD

**Issue by davephillips** [VCVRack/Rack#150]
OS (if applicable): Linux, Fedora 21
Version : dev

Got this with the latest Fundamental and Vult code :

error: no matching function for call to ‘rack::Module::Module()’

Latest code for everything.

**Comment by AndrewBelt** [comment]
It works for me. Are you sure you're using the latest code from Fundamental and Rack?

**Comment by davephillips** [comment]
I restarted with a fresh pull, everything was building nicely until I tried compiling extra modules from Vult, av500, and luckyxxl. Here's a typical error from trying to build the av500 modules :

$ make
g++ -fshort-enums -DTEST -I./eurorack -Wno-unused-local-typedefs -fPIC -I../../include -I../../dep/include -DVERSION=dev -MMD -O3 -march=nocona -ffast-math -g -Wall -DARCH_LIN -std=c++11 -c -o build/src/p0wr.cpp.o src/p0wr.cpp
src/p0wr.cpp: In constructor ‘p0wr::p0wr()’:
src/p0wr.cpp:22:12: error: no matching function for call to ‘rack::Module::Module()’
 p0wr::p0wr() 
            ^
src/p0wr.cpp:22:12: note: candidates are:
In file included from ../../include/rack.hpp:6:0,
                 from src/av500.hpp:1,
                 from src/p0wr.cpp:1:
../../include/engine.hpp:43:2: note: rack::Module::Module(int, int, int)
  Module(int numParams, int numInputs, int numOutputs) {
  ^
../../include/engine.hpp:43:2: note:   candidate expects 3 arguments, 0 provided
../../include/engine.hpp:33:8: note: rack::Module::Module(const rack::Module&)
 struct Module {
        ^
../../include/engine.hpp:33:8: note:   candidate expects 1 argument, 0 provided
src/p0wr.cpp: In member function ‘virtual void p0wr::step()’:
src/p0wr.cpp:31:42: error: cannot convert ‘__gnu_cxx::__alloc_traits<std::allocator<rack::Param> >::value_type {aka rack::Param}’ to ‘float’ for argument ‘1’ to ‘float roundf(float)’
  switch ((int)roundf(params[SWITCH_PARAM])) {
                                          ^
../../compile.mk:49: recipe for target 'build/src/p0wr.cpp.o' failed
make: *** [build/src/p0wr.cpp.o] Error 1


Any suggestions ?

**Comment by AndrewBelt** [comment]
The `Module()` contructor has been removed. Plugins should be `Module(int numParams, int numInputs, int numOutputs)` by way of 

	MyModule::MyModule() : Module(NUM_PARAMS, NUM_INPUTS, NUM_OUTPUTS) {
	}

**Comment by davephillips** [comment]
Thanks, Andrew. I figured it out about an hour ago, I've got the Vult Modules successfully built and working now. I'll try the ML and luckyxxl modules next. Meanwhile, I've hit a snag with the av500 modules, specifically with a case switch :

[dlphilp@The6300 vcvrackplugins_av500]$ make
g++ -fshort-enums -DTEST -I./eurorack -Wno-unused-local-typedefs -fPIC -I../../include -I../../dep/include -DVERSION=dev -MMD -O3 -march=nocona -ffast-math -g -Wall -DARCH_LIN -std=c++11 -c -o build/src/p0wr.cpp.o src/p0wr.cpp
src/p0wr.cpp: In member function ‘virtual void p0wr::step()’:
src/p0wr.cpp:31:42: error: cannot convert ‘__gnu_cxx::__alloc_traits<std::allocator<rack::Param> >::value_type {aka rack::Param}’ to ‘float’ for argument ‘1’ to ‘float roundf(float)’
  switch ((int)roundf(params[SWITCH_PARAM])) {
                                          ^
../../compile.mk:49: recipe for target 'build/src/p0wr.cpp.o' failed
make: *** [build/src/p0wr.cpp.o] Error 1

Any idea how to fix that ?

**Comment by AndrewBelt** [comment]
The av500 developer needs to fix this. Tell him that there are changes in engine.hpp to look out for in the latest Rack source tree.

**Comment by davephillips** [comment]
Thanks again, Andrew, I'll contact him. I've run into a similar error with the ML modules, I'll notify Martin on his github page. Btw, I've been having a lot of fun with VCV Rack. Tonight I got the MIDI input working - I wasn't building Portmidi - so it looks like more fun on the way.
