### ISSUE TITLE
v 1.1.3 Crash when searching mixers in module browser

### ISSUE THREAD

**Issue by Scumbag01** [VCVRack/Rack#1500]
v1.1.3 when searching "mixer" in module browser, crash

### Details

Operating system: OSX 10.12.6
Rack version: v1.1.3
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): mid-2012 MBP i7Quad, 16GB, HD Graphics 4000 1536 MB, internal sound, no external devices.

### Summary
When opening module browser and selecting Mixer category filter, Rack crashes immediately
### Steps to reproduce
Launch Rack, open module browser, select Mixer from module type, crash

[log.txt](https://github.com/VCVRack/Rack/files/3426605/log.txt)

```
VCV Rack has crashed. See /Users/owner/Documents/Rack/log.txt for details.
```

**Comment by jeremywen** [comment]
Looks like you need to update KlirrFactoryOverdub.  Go to your klirrfactory account to get the update.

**Comment by Scumbag01** [comment]
Yes, that solved it.  Thank you.
