### ISSUE TITLE
VCV.com Manual, search not functioning 

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Rack#1503]
### Details

Operating system: win7 sp1
Rack version: N/A
relevant to issue: Opera Browser 62.0.3331.99, Chrome and IE11

### Summary
Tried to search for `infinity` on the manual page, which takes a infinite amount of time :eyes: Also tried to search other terms `Voltage`. The search does not function. I believe this is a recent bug I have searched the manual in the past and it worked as expected.

### Steps to reproduce
https://vcvrack.com/manual/search.html?q=infinity&check_keywords=yes&area=default

**Comment by AndrewBelt** [comment]
Removed search. You may use something like https://www.google.com/search?q=infinity+site%3Avcvrack.com%2Fmanual
