### ISSUE TITLE
Demo Patch Remains After "File|New" Clicked

### ISSUE THREAD

**Issue by Mortarm** [VCVRack/Rack#1505]
### Details

Operating system: Windows 7 Home, 64-bit
Rack version: v1.1.3
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): n/a

### Steps to reproduce:  Load VCV, click File|New, click "Yes" in the dialog box.  Poof, it's back.

I found by deleting the Template file that fixes the issue, but you shouldn't have to.

**Comment by Coirt** [comment]
Clicking file>new will load the template which happens to be the demo patch. You can save your own template to override this feature, which will load your template when you click new.

**Comment by AndrewBelt** [comment]
To save a blank template, delete all modules from the rack and choose `File > Save Template`.
