### ISSUE TITLE
Soniccharge plugins via HOST/HOSTFX modules crash VCVRack

### ISSUE THREAD

**Issue by occubusjive** [VCVRack/Rack#1508]
### Details

All Soniccharge VST plugins via HOST/HOSTFX modules cause crash VCVRack 1.1.3
Plugins worked in v.06 VCV Rack. Uncertain if issue created by v1.0 since only trying with latest build.

Operating system: OS X 10.4.6
Rack version: v1.1.3
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): 
MacBook Pro (15-inch, 2018)
2.6 GHz Intel Core i7
16 GB 2400 MHz DDR4
Intel UHD Graphics 630 1536 MB

### Summary

When attempting to load any of the Soniccharge VST plugins (Synplant, Microtonic, Bitspeek, Permut8, Echobode) they cause a crash and the program terminates. This is accompanied by an audible feedback of whatever sound is passing through the VST. Also it seems the core audio will crash. Upon relaunch it will need to be reset.

### Steps to reproduce

Add Host or Host FX module and select one of the above Soniccharge VST plugins. VCVRack will display its crash error dialog box. After selecting ok the program will close and the audio will feedback. If the MacBook speaker was being used, the volume will reset back to 0. Upon relaunch, with the VST removed and audio driver reset, VCVRack will perform as normal.

Here are the contents of the log:

[log.txt](https://github.com/VCVRack/Rack/files/3437742/log.txt)

<img width="1677" alt="Screen Shot 2019-07-26 at 6 52 04 PM" src="https://user-images.githubusercontent.com/53358183/61988464-845c1480-afd6-11e9-808d-5793a0a64edf.png">

**Comment by AndrewBelt** [comment]
Thanks, we're taking a look.

**Comment by AndrewBelt** [comment]
This is the issue tracker for VCV Rack. Send bug reports and feature requests of VCV plugins to contact@vcvrack.com.
We have added this to our internal issue tracker. Comment your email address here if you would like to be informed of future updates to this issue.
