### ISSUE TITLE
Saving Default Module Presets

### ISSUE THREAD

**Issue by FunkybotsEvilTwin** [VCVRack/Rack#1509]
Summary of Issue: Users may want to create default presets for each module, as developers may use settings that may differ from user preferences. 

Proposed Implementation:

1. User right+clicks module, menu opens
2. New menu option exists to "Save Current Settings as Module Default"
3. User clicks this option
4. A new file called **default.vcm** is written to the default location: **Rack\Patches\Module Patches\ (module name) \** (or a new folder Rack\Module Patches\ (module name) \)
5. Whenever a module is loaded going forward, VCV Rack will check for Rack\Patches\Module Patches\ (module name) \default.vcm 
6A. If a default.vcm exists, these parameters are recalled automatically on module load (unless module is duplicated of course)
6B. If no default.vcm exists, the normal default parameter is loaded

This would be a huge workflow enhancement.

I couldn't find a very specific FR for this outside of this old discussion for 2017 where it was one of multiple requests (https://github.com/VCVRack/Rack/issues/276). Sorry if this should be merged with that thread but portions of that FR were implemented so it's difficult to tell what's still open.

**Comment by modman2019** [comment]
I would also like to see the saved presets location be module specific so that whenever we open a preset for a certain module, only those presets associated with that module are displayed and loadable. Right now sort of any folder opens and we have to locate the correct preset somewhere we can find it again

**Comment by AndrewBelt** [comment]
This was added to the (currently private) `v2` branch a few months ago. Didn't realize there was an issue for it.
![Capture](https://user-images.githubusercontent.com/338179/93745229-308c9180-fbc1-11ea-9465-a7d4a202a661.PNG)
