### ISSUE TITLE
pull in tan, cot, atan, atan2

### ISSUE THREAD

**Issue by JerrySievert** [VCVRack/Rack#1511]
### Summary

there were extensions of `sse_mathfunc.h` that added `tan`, `cot`, `atan`, and `atan2` released at https://github.com/to-miz/sse_mathfun_extension ([blog](https://handmade.network/forums/wip/t/1439-sse2_implementations_of_tan,_cot,_atan,_atan2)).

these would be useful additions for `float_4`.

the authors' stated goal was to get these added to `sse_mathfunc.h` directly, so there may not be any license issues (license is zlibc license).

additional math functionality for audio filters.

### Proposed design

extend `sse_mathfun.h` with these.

alternately, module developers could implement this functionality in modules that need it.

**Comment by AndrewBelt** [comment]
Thanks, ported in cdc0bde.
I'd love it if someone could port `sse_mathfun*.h` to `functions.hpp` using `float_4` etc instead of `__m128` etc for clarity.

**Comment by JerrySievert** [comment]
I'm a little curious about what specific pattern you were thinking about for this.

given that `float_4` is a struct containing a union, and that many of the lower level calls in `sse_mathfun*.h` are trying to do as much as possible without additional memory access, there likely would still need to be an underlying `__m128` or other named 128 bit type for the math.

would the pattern you're looking for be to replace something like:

```
inline float_4 log(float_4 x) {
	return float_4(sse_mathfun_log_ps(x.v));
}
```

with something to the affect of:

```
inline float_4 log(float_4 x) {
	__m128i emm0;
	__m128 one = _mm_set_ps1(1.0);

[...]

        return float_4(ret);
}
```

where the logic itself is encapsulated?  or did you have something else in mind?

**Comment by AndrewBelt** [comment]
I'd prefer that you write the line
```cpp
__m128 one = _mm_set_ps1(1.0);
```
as
```cpp
float_4 one = 1.f;
```
or better yet, just use `1.f` when you need it (e.g. `a * b + 1.f`). The idea is to turn the 60-line functions into 10-line functions using the `simd::Vector` DSL, which makes it easier to read, write, and review.

**Comment by JerrySievert** [comment]
ok, thanks for the clarification - I'll make a pass on a single function and get some feedback before doing the rest and opening a PR.

**Comment by AndrewBelt** [comment]
Obviously in some cases you can't really do that, such as in the definition of `rsqrt`, which just calls the `rsqrtps` instruction.

**Comment by JerrySievert** [comment]
well, yeah, I figured that anything that used the instructions directly was about as clear as it was going to get.
