### ISSUE TITLE
dBiz / VCA4 bug

### ISSUE THREAD

**Issue by mrshinigami77** [VCVRack/Rack#1512]
### Details

Operating system: Mac Os Mojave
Rack version: v 1.1.3.
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): Audio

### Summary
Brand : dBiz
Module : VCA4
v 1.1.0

- Issue in Outputs 
- Outputs 1 to 4 receive signal only from Input D.
- Input D goes out perfectly from 1 to 4 outputs.

### Steps to reproduce

I fill all A,B,C, D Inputs with 4 waveforms from the same VCO (anyone) 
I have an output signal only from the D Input on Outputs 1 to 4 when activating The Unmute button.
I can't get A,B and C inputs to go on any of the Outputs 1 to 4. 

-- > Since the signal not working, I don't have the possibility to test the Black Knobs on the knobs, so I don't know if they working fine or not. They are working for the D channel.

**Comment by LomasModules** [comment]
You should post this on the dBiz github not here.

**Comment by mrshinigami77** [comment]
It's all new to me :)
Thanks.

Le mar. 30 juil. 2019 à 00:25, Andrew Belt <notifications@github.com> a
écrit :
