### ISSUE TITLE
"make install" does not work

### ISSUE THREAD

**Issue by probonopd** [VCVRack/Rack#1515]
### Details

Operating system: Ubuntu
Rack version: git master

### Summary

`make install` does not work.

### Steps to reproduce

```
$ make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
make: *** No rule to make target 'install'.  Stop.
find: ‘appdir/’: No such file or directory
```

Detailed log: https://travis-ci.com/probonopd/Rack/jobs/222261397#L5798-L5801

**Comment by stoermelder** [comment]
Please follow the official build manual:
https://vcvrack.com/manual/Building.html

**Comment by probonopd** [comment]
Even after reading that I am under the impression that make install does not work. This is a feature request to have make install implemented.

**Comment by AndrewBelt** [comment]
I'm rejecting the feature request. The install directory of `make install` would be ambiguous.

**Comment by probonopd** [comment]
> The install directory of make install would be ambiguous.

It is normally `/usr/local`, unless the user specifies a different location such as `/usr`. This is really pretty much totally common standard in the Unix and Linux world, really.
