### ISSUE TITLE
Plugin developers should add more tags

### ISSUE THREAD

**Issue by Jairodallos** [VCVRack/Rack#1516]
### Details

Operating system: win 10
Rack version: last
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

### Summary
Hi friends,

i suggest a better browser; there are modules not showed when we search some categories, having the modules the word requested
![2019-08-04_05-49-49](https://user-images.githubusercontent.com/22566357/62422704-559c0900-b67c-11e9-9bce-b3c5338d6715.png)

Thanks in advance

**Comment by Coirt** [comment]
I suggest you request that the relevant developer for a given module adds the tags to the module you want to filter!

The 2 in the example are "Dynamics"

**Comment by AndrewBelt** [comment]
This is an issue with specific plugins, not Rack itself. VCV does not manage plugin manifests for third-party plugins.
