### ISSUE TITLE
Question: Does this work on Linux without Jack?

### ISSUE THREAD

**Issue by probonopd** [VCVRack/Rack#1517]
Question: Does this work on Linux without Jack?

**Comment by stoermelder** [comment]
Yes.

**Comment by probonopd** [comment]
How? I am looking for a standalone binary that does not need Jack.

**Comment by AndrewBelt** [comment]
In order to support JACK at all, Rack needs to link to JACK, so you need to install the JACK library to launch Rack. However, you can use the ALSA audio/MIDI driver instead of JACK.

**Comment by probonopd** [comment]
> you can use the ALSA audio/MIDI driver instead of JACK

Thanks, that sounds exactly like what I am looking for. What would I need to do for that? Is it a build-time option?

**Comment by AndrewBelt** [comment]
You could edit the line
```Makefile
RTMIDI_FLAGS += --with-jack --with-alsa
```
in `dep/Makefile`.
