### ISSUE TITLE
Load resources from a path relative to the main executable, not from cwd

### ISSUE THREAD

**Issue by probonopd** [VCVRack/Rack#1518]
### Details

Operating system: Linux
Rack version: git master

### Summary

Rack tries to load resources from `./res` and from `./Fundamental.zip` from the current working directory the user happens to be in. Instead, it should try to load those resources from a path relative to the main executable, e.g., `<where Rack lives>/../share/rack/`.

### Steps to reproduce

```
me@host:~$ sudo strace -f ./Rack 2>&1 | grep zip
[pid 12405] stat("./Fundamental.zip",  <unfinished ...>
```

**Comment by AndrewBelt** [comment]
I could use `readlink("/proc/self/exe", buf, bufsize)` on Linux, but I think it's hacky, and cwd is more straightforward to users.

**Comment by probonopd** [comment]
> cwd is more straightforward to users.

...but does not do the right thing: It breaks if the user is not in the same directory as the application (which is actually the case most of the time, at least on Linux-based systems when you open an app from the menu).

**Comment by AndrewBelt** [comment]
If you want to "install" Rack, create the following file called `Rack` and place it in your `$PATH`
```bash
#!/bin/sh
cd /path/to/Rack && ./Rack
```
or just add Rack's path to your `$PATH`.

**Comment by probonopd** [comment]
And the plugins? And the icon? And the desktop file?
