### ISSUE TITLE
nanovg.h: No such file or directory

### ISSUE THREAD

**Issue by probonopd** [VCVRack/Rack#1519]
### Details

Operating system: Ubuntu xenial
Rack version: git master

### Summary

Getting `fatal error: nanovg.h: No such file or directory` when compiling

### Steps to reproduce

* Build script: https://github.com/probonopd/Rack/blob/patch-1/.travis.yml
* Build log: https://travis-ci.com/probonopd/Rack/builds/121873821#L1504

**Comment by stoermelder** [comment]
Please follow the official build manual:
https://vcvrack.com/manual/Building.html

**Comment by probonopd** [comment]
That is what I used... but it is a bit vague at times. So what am I doing wrong?

**Comment by Coirt** [comment]
Did you test the script manually?

The vagueness of build instructions work for everyone else.

**Comment by AndrewBelt** [comment]
`nanovg.h` should be in `dep/include`. If it's not, you're probably forgetting to `git submodule update --init --recursive`.

**Comment by probonopd** [comment]
Thanks, but looking at https://github.com/probonopd/Rack/blob/patch-1/.travis.yml I am actually doing it twice to be extra sure... ;-)

**Comment by stoermelder** [comment]
Your script is not following the instructions, you have to build the dependencies before any plugins.

**Comment by AndrewBelt** [comment]
This is definitely a problem with your script or Travis or whatever, not Rack.
