### ISSUE TITLE
VCV Console FR: Stereo Inputs and Pre/Post Fader Sends

### ISSUE THREAD

**Issue by FunkybotsEvilTwin** [VCVRack/Rack#1521]
I'd like to request 1) stereo (L/R) inputs to VCV Console, and a button to toggle between 2) Pre/Post Fader for each channel's Aux send. 

Stereo inputs would allow for dealing with a stereo sub-mix on a single channel (e.g. stereo drums) versus two channels in the current state. This would have the trickle-down effect of simplifying the routing of mutes/solos/level, etc.

Pre/Post fader sends just offers additional flexibility commonly found in consoles. 

### Proposed design

1. There's some white space above the Channel inputs. I suggest adding a second input there, and having the top input represent the left portion of the stereo channel, with bottom being the right. In this configuration, the pans can become a stereo balance panner.

If you move the title "Console" from the top of the GUI, to the bottom (e.g. "VCV Console" along the bottom), this will create a lot of room to move on the GUI for the required changes.

2. For the pre/post fader sends, a toggle button could be added next to each send if the middle section of the GUI is moved up a bit after moving the title "Console" downwards. I envision two new toggle buttons per channel to change the send behavior.

**Comment by AndrewBelt** [comment]
Send bug reports and feature requests of VCV plugins to contact@vcvrack.com.
Added to internal issue tracker.
