### ISSUE TITLE
Recurring crashes while scrolling through Module Browser

### ISSUE THREAD

**Issue by seangarland** [VCVRack/Rack#1523]
### Details

Operating system: Mac OS Mojave 10.14.6
Rack version: v1.1.3
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

### Open Rack, right-click to open Browser, scroll down through browser, resulting in crash.
[log.txt](https://github.com/VCVRack/Rack/files/3473378/log.txt)

**Comment by seangarland** [comment]
In re-testing this issue several times, it seems to always crash as I scroll and get to the Bog Audio and Vult modules.

**Comment by AndrewBelt** [comment]
It's odd that the log doesn't include a stack trace. Does the Apple "Report an issue" dialog box appear after the crash?

**Comment by seangarland** [comment]
Yes it does. Shall I copy/paste the text?

**Comment by AndrewBelt** [comment]
Attach a text file of the full report text if you'd like.

**Comment by seangarland** [comment]
Here is the report.
[Rack Issue 1523.txt](https://github.com/VCVRack/Rack/files/3473661/Rack.Issue.1523.txt)

**Comment by AndrewBelt** [comment]
The culprit is Byte Beat Machine. https://vcvrack.com/plugins.html#byte
Are your plugins updated? Is anyone else experiencing a crash with this plugin?

**Comment by seangarland** [comment]
Thanks! I thought I had deleted that module previously, as I read that it was causing issues. 

I have deleted the plugin, and everything seems to be working now. ByteBeat appears to be a 0.6.1 version, which I'm guessing might be the issue?

**Comment by Coirt** [comment]
Byte Beat Machine v1 was on the plugin Manager for a time and was removed because it was crashing Rack.

Any 0.6.1 version will not be downloaded by v1 but it will say it in the log that you have it added, it waits for v1 for a v0.6.x plugin.

**Comment by rubyglow** [comment]
@AndrewBelt I think this issue can be closed now, since it was due to ByteBeatMachine crashing Rack, and was removed from the library because of it. All that remains would be the advice: If your Rack is crashing, and you have ByteBeatMachine in your plugins-v1 directory, please delete it from there and restart Rack.
