### ISSUE TITLE
Unable to use same audio interface in ableton and VCV rack

### ISSUE THREAD

**Issue by 0mars** [VCVRack/Rack#1525]
### Details

Operating system: Windows 10 
Rack version: v1.1.3
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):
Interface: Behringer UMC1820
Driver: UMC ASIO Driver

Note: could not find the log.txt in Program Files/VCV/Rack

Other configurations on the system:
ASIO4ALL installed with offline settings
Synchronous Audio Router installed

This problem used to happen randomly, but since the installation of both softwares above it had become permanent

### Summary
VCV rack freezes each time I select the same audio interface being used in ableton, and if there is a selected patch from before no input/output going through, just displays the interface in question, when I restart it and it is the only one using the interface it works properly

### Steps to reproduce
Open Ableton, select the audio interface in question
Open VCV rack, open audio 16 module, select the same interface in question

**Comment by 0mars** [comment]
Update, uninstalled asio4all, async audio router, same issue persists

**Comment by AndrewBelt** [comment]
Most ASIO drivers are application-exclusive, meaning that only one application can open a device's audio stream.
