### ISSUE TITLE
Links to list of allowed tags broken in manual and helper

### ISSUE THREAD

**Issue by mgunyho** [VCVRack/Rack#1529]
I was looking for the list of allowed tags for a module, but the links [here](https://vcvrack.com/manual/Metadata.html#modules-tags) and [here](https://github.com/VCVRack/Rack/blob/v1/helper.py#L203) are broken. I believe they should point to [tag.cpp](https://github.com/VCVRack/Rack/blob/v1/src/tag.cpp).

**Comment by AndrewBelt** [comment]
Thanks, fixed in ad2ca6c and updated the manual.
