### ISSUE TITLE
Knobs/Jacks Misaligned at Zoom >100%

### ISSUE THREAD

**Issue by jonheal** [VCVRack/Rack#1533]
If Rack is zoomed to less than 100% (I used 86%), loading a module will sometimes cause knobs or jacks graphics to become misaligned on the module's panel. Moving the module to another row can alter the misalignment. Restarting Rack resolves the problem until you move one of the affected modules again. Not every module has this problem, but BEFACO and SYNTHKIT do for sure.

Operating system: Windows 10
Rack version: v1.1.3
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): i7 HD4000

Steps to reproduce:
1. Zoom to 86%
2. Add a BEFACO Mixer
3. Move it from row to row

![Off-Center](https://user-images.githubusercontent.com/33180867/63559652-b783bc00-c520-11e9-96cd-b7b193eb6717.png)

**Comment by AndrewBelt** [comment]
This has been fixed several months ago in Rack v2.
