### ISSUE TITLE
Rack 1.1.4 triggers MyLittleTools infinite update loop

### ISSUE THREAD

**Issue by wiqid** [VCVRack/Rack#1534]
### Details

Operating system: Win 10 Pro
Rack version: v1.1.4

### Summary

Updating Rack to 1.1.4 shows an update for MyLittleTools to 1.0.2, but after updating the same notice appears.

The problem may be in the plugin library, but I noticed it after updating to Rack 1.1.4.

**Comment by Petervos2018** [comment]
Andrews Answer in the FB group : 

> Andrew Belt  : MyLittleTools is a "hacky" plugin so it should be expected to break on most releases.

**Comment by AndrewBelt** [comment]
This is an issue with MyLittleTools using the "private" API of Rack which does not follow Rack's ABI versioning rules. Please report to the MyLittleTools developer.
