### ISSUE TITLE
Compile to Wasm (WebAssembly)?

### ISSUE THREAD

**Issue by Catsvilles** [VCVRack/Rack#1535]
Hi! Sound designer here, at the moment I play around with Web Audio API and explore libraries, plugins, and possibilities for creating cool and powerful software that can run in the browser. Just stumbled upon Rack and gosh it looks and sounds amazing! What do you think, could it be possible to compile VCV Rack to WebAssembly and use it in the browser with javascript?

**Comment by diimdeep** [comment]
There is heavy modded vcv fork and same guy compiled it with Emscripten to web https://assets.mifki.com/mirack/Rack.html
Here I requested source https://github.com/mi-rack/Rack/issues/18

**Comment by AndrewBelt** [comment]
Closing since I see no commercial, personal, or promotional reason to do this.
