### ISSUE TITLE
Rack on Windows numerically different to macOS

### ISSUE THREAD

**Issue by expertsleepers** [VCVRack/Rack#1539]
Hi,

with regard to my Expert Sleepers Encoders plug-ins for Rack, these rely on specific numerical manipulation to effectively do bit manipulation on the floating point audio stream.

The Windows version is behaving differently. Testing Rack 1.1.4 against my Silent Way VST plug-ins:

- mac, Silent Way in Live -> OK
- mac, VCV -> OK
- windows, Silent Way in Live -> OK
- windows, VCV -> not OK

Are you aware of anything that the Windows version of rack is deliberately doing differently? (e.g. changing the FPU rounding mode or similar) If not, it's probably on me to put in a fiddle factor to make it work.

Thanks.

**Comment by expertsleepers** [comment]
0x9FE0 on both.

**Comment by expertsleepers** [comment]
Putting printfs() in the plug-ins, the output on both platforms is the same, so any difference must be downstream with Rack.

**Comment by expertsleepers** [comment]
By "not OK" I mean the results are not as expected, i.e. not the same as the other combinations listed.

I'm not talking about VCV Host. I'm comparing the results of the Silent Way VST plug-ins hosted in Live, against my Encoders plug-in for Rack.

By any difference I mean whatever is altering the value that I want to be sent to the hardware. 



### Details

Operating system: macOS 10.14.6, Windows 10
Rack version: v1.1.4
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): Tested with RME UCX, Expert Sleepers ES-3/ES-5/ESX-8GT

### Summary
As above.

### Steps to reproduce
With a patch similar to this, the expected LEDs on the hardware do not light.
<img width="423" alt="Screenshot 2019-08-27 at 14 21 19" src="https://user-images.githubusercontent.com/7710860/63774812-f4133700-c8d5-11e9-9e4f-b72cc8711a61.png">

**Comment by expertsleepers** [comment]
FWIW I also put some printfs() in AudioInterface.cpp and the values appear correct at that point. I don't really understand where it goes from there though.

**Comment by expertsleepers** [comment]
I'm aware that it might be hard for you to repro this without the hardware. The correct results are a 24 bit integer on the audio channel that matches the bit pattern set in the plug-ins. (Each 8GT generates 8 of those bits, and the ES-5 encoder combines 3 of them into a 24 bit word.)

This definitely does not work with sample rate conversion. It's not in use in any of my setups.

It looks as though the value getting through to the hardware on Windows is 1 LSB less than the correct one, which is why I mention rounding. If you could point me at what processing takes place after AudioInterface.cpp I could attempt to trace it further.

**Comment by expertsleepers** [comment]
I'm using an RME UCX with the latest RME drivers.

Same driver/interface for VCV and Live.

To be clear I've not yet been able to observe different values as floats, but that's probably due to not knowing where to look. What I'm observing is the output of the hardware, at which point we're dealing with 24 bit integers.

**Comment by expertsleepers** [comment]
ASIO. Sorry I forget there are all these variables on Windows.

**Comment by expertsleepers** [comment]
Thanks, I'll have a look. I've been successfully relying on bitwise accuracy for about 8 years now and don't intend to stop any time soon :)

**Comment by stoermelder** [comment]
> Are 32-bit integers defined as x / (2^31) or x / (2^31 - 1)?

Been one of the persons who reported this problem I tested this some minutes ago.
Changing the conversion from float to int32 to
`out[info.outOffset[j]] = (Int32) (in[info.inOffset[j]] * 2147483646.5 - 0.5);`
from
`out[info.outOffset[j]] = (Int32) (in[info.inOffset[j]] * 2147483647.5 - 0.5);`
makes it work (line 10332 in RtAudio.cpp).

**Comment by stoermelder** [comment]
I'm not so sure anymore that Rack is the cause, because I can't reproduce it with the release version 1.1.4 anymore. Please ignore my comment above.

**Comment by expertsleepers** [comment]
That line in RtAudio.cpp would seem to be the point of difference. The mac version doesn't hit that because the input & output formats are both RTAUDIO_FLOAT32. I guess the underlying mac driver wants floats whereas the underlying windows driver wants ints.

It's not clear what the 'right' solution is. Changing RtAudio would make Rack behave more like other windows apps. In which case, I would suggest changing
* 2147483647.5 - 0.5
* 2147483648.0 + 0.0 plus a clamp to 2147483647

Looking back at the file history of RtAudio.cpp, there's clearly been differing views on the right calculation, even within that project.

**Comment by expertsleepers** [comment]
So are you suggesting we report this as a bug to them?

**Comment by AndrewBelt** [comment]
Yes, feel free to attempt to add this fix to the RtAudio project.

**Comment by expertsleepers** [comment]
Hi Andrew, I see you submitted a change to the RtAudio project. Have you had someone verify that this fixes the ES-5 issue when using Rack on Windows?

**Comment by AndrewBelt** [comment]
I don't have an ES-5 and don't have time to orchestrate volunteer testing against your hardware.
But I have verified that at least on some of the to/from pairs, the code works according to the scaling formulas.

**Comment by expertsleepers** [comment]
OK thanks. I can find testers. Which version of Rack will this be available in?

**Comment by stoermelder** [comment]
I can test. Can I build Rack 1.1.6 with the latest commit of RtAudio?

**Comment by AndrewBelt** [comment]
@expertsleepers  Rack v2.0.0.
@stoermelder Yes, just pull the submodule, or use https://github.com/AndrewBelt/rtaudio, which I will switch to for Rack v2.

**Comment by stoermelder** [comment]
- Windows 10 1909
- RME Digiface USB, ADAT to ES-3 with ES-5 connected on channels 7+8, additionaly an ESX-8GT on port 2 of the ES-5
- Using the Expert Sleepers Encoders plugin

Rack v1.1.6 official release from website: triggers on every port are all over the place on the hardware outs
Rack v1 branch with updated RtAudio submodule: everything's fine, all outputs work as expected

Thanks Andrew and Andrew for fixing this!

**Comment by AndrewBelt** [comment]
Nice! Appreciated!
