### ISSUE TITLE
Save as menu stay open

### ISSUE THREAD

**Issue by nay-seven** [VCVRack/Rack#154]
OS : Yosemite
Version : 0.3.2

When using the _save as_ from the menu, patch is correctly saved, but the menu stay open, and i need to close Rack and reopen.

**Comment by AndrewBelt** [comment]
By "menu" do you mean the Mac dialog box?

**Comment by nay-seven** [comment]
no, Rack menu :


<img width="142" alt="rack menu" src="https://user-images.githubusercontent.com/13808201/31026195-ca4ce084-a545-11e7-8ee8-26e408487d1c.png">

**Comment by oblivionratula** [comment]
See my Issue #37  Also on Yosemite.

**Comment by nay-seven** [comment]
Yes,  oblivionratula, looks like the same type of issue

Strange, i've delete the RACK application and install again
if i create a new patch i can save normally, but now i can't open old ones, same issue , menu is blocked..will try on High Sierra, works fine ( but not the same machine..  :-(  )

**Comment by nay-seven** [comment]
note i don't have this issue before , when first use on yosemite, works fine
i've switch my mac book pro to a second screen, via an elgato hub , gone to test without it...

**Comment by AndrewBelt** [comment]
I think is a window focusing issue. What if you try clicking on the window title bar at the top to bring it in focus?

**Comment by nay-seven** [comment]
ok, so same issue without the second screen...
Is there a way to delete rack in a clean way before reinstalling ?  , ive test "clean my mac" but same..

**Comment by nay-seven** [comment]
clicking in the title bar don't solve it

**Comment by nay-seven** [comment]
all works fine on High Sierra

**Comment by nay-seven** [comment]
and for info, i precise i use the last beta of High Sierra ( 10.13.1)

**Comment by AndrewBelt** [comment]
Is the Mac file dialog perhaps behind the window. Could you try moving the Rack window out of the to see if something is behind it?

**Comment by oblivionratula** [comment]
On my system, the hang happens AFTER the load or save, so the file dialog is done and goes away (no, it's not lingering behind), but the file drop menu remains, as pictured above, and the rest of the UI is non-responsive (but the audio engine continues).

**Comment by nay-seven** [comment]
exactly, same here

**Comment by Syndhro** [comment]
Same problem here. Running Windows 10, at the beginning everything worked fine. Now if I want to open a patch from the "open" option in the menu, after selecting the patch the window crashes.

**Comment by unlessgames** [comment]
Got a similar problem (more like #555) with the osdialog file-explorer popup and the "Clear patch and start over?" prompt opening behind the fullscreen Rack window, leaving me with a seemingly frozen Rack until I exit fullscreen, and react to them.
Using i3 window manager on arch linux and even if i have the '[popup_during_fullscreen](https://i3wm.org/docs/userguide.html#_popups_during_fullscreen_mode)' set to 'leave_fullscreen' (inside i3 config) it still doesn't help.

**Comment by geslotencirkel** [comment]
Getting a similar issue on v1 rack - might be related to the rack being run from Mingw64

after initiating save as dialog and clicking the main VCV window, a new save as dialog is opened.

Windows 8.1 64bit
built from v1 branch - 24/03/2019

**Comment by AndrewBelt** [comment]
Fixed 2de7e9e98b329bd46739f3bd3a273e33f0dab823 via changes in https://github.com/AndrewBelt/osdialog
