### ISSUE TITLE
Consider migrating to CMake from autoconf

### ISSUE THREAD

**Issue by luzpaz** [VCVRack/Rack#1541]
### Summary
Move away from autoconf clutter. CMake is more modern and potentially easier to use with Continuous Integration.

Edit: Also easier for downstream packagers since some repos are trying to deprecate `autoconf`

**Comment by AndrewBelt** [comment]
Rack doesn't use autoconf.

**Comment by luzpaz** [comment]
Why is it a required dependency then ?  
ref: https://vcvrack.com/manual/Building.html

**Comment by AndrewBelt** [comment]
jansson, zlib, libspeexdsp, libsamplerate, and rtmidi use it, which are dependencies of Rack.

**Comment by luzpaz** [comment]
Apologies for the noise.
