### ISSUE TITLE
Add repology badge to README.md

### ISSUE THREAD

**Issue by luzpaz** [VCVRack/Rack#1542]
### Summary
A way for users to see what downstream repositories carry vcvrack

### Proposed design
The full badge looks like so:  
[![Packaging status](https://repology.org/badge/vertical-allrepos/vcvrack.svg?header=vcvrack)](https://repology.org/project/vcvrack/versions)  

but since it take up a lot of room it can be simply added as a single badge such as:

[![Packaging status](https://repology.org/badge/tiny-repos/vcvrack.svg)](https://repology.org/project/vcvrack/versions)

**Comment by luzpaz** [comment]
Preview: https://github.com/luzpaz/Rack/blob/repology-badge/README.md

**Comment by AndrewBelt** [comment]
I don't need this
