### ISSUE TITLE
Enable endless Mouse Movement on Panning

### ISSUE THREAD

**Issue by dschiller** [VCVRack/Rack#1547]
#1454 # Summary

If panning with middle mouse button the screen border stops the panning even if i didnt get where i want to go. for that reason an endless panning like in blender 3d app would be good to be able to pan as far as one wants until releasing the mouse button. even that vcv already uses blenders ui maybe its also nice for philosophy to implement its gestures.

### Proposed design

if the mouse hits one of the four screen borders then the pan continues and the mouse jumps to the opposite site of the screen. eg. if the mouse is on the top right side it goes to the beeginning of the left side. so to say it spawns to its corresponding side to be able to continue the panning gesture.

**Comment by AndrewBelt** [comment]
I don't like this idea, rejecting issue.
