### ISSUE TITLE
auto scroll for modules menu

### ISSUE THREAD

**Issue by nay-seven** [VCVRack/Rack#155]
OS (if applicable): Yosemite and High Sierra
Version : 0.3.2

i 'm testing new modules ( around 20 new modules) from  [autodafe](https://www.autodafe.net/virtual-instruments/vcv-rack-modules.html) but the modules menu is too big for my screen now ;-) so i can access to all modules

**Comment by AndrewBelt** [comment]
Duplicate of #68

**Comment by nay-seven** [comment]
ok, sorry
