### ISSUE TITLE
MIDI-CV Pitchbend Only Detected On MIDI Channel 1

### ISSUE THREAD

**Issue by jwchamb** [VCVRack/Rack#1554]
Using VCV Rack 1.1.4 with Scala microtuning program. Scala relay function rotates through MIDI channels, sending note and pitchbend on each in turn. In rack, hooked up MIDI-CV module to Split and Viz modules, selected 6 channel polyphony. V/OCT and GATE both show and transmit 6 channels, PW only shows and transmits channel 1.

**Comment by AndrewBelt** [comment]
MIDI pitch wheel is global per MIDI channel, not per note, so this is correct behavior. (You only have one pitch wheel on your MIDI keyboard, right??)

**Comment by jwchamb** [comment]
Hi Andrew,
I think you misunderstood my Scala example. Let me try a different one. If you connect the modules as I said, you should see that the splitter connected to the PW output only lights channel 1 regardless of the polyphony settings on the MIDI-CV module. Setting the polyphony mode to rotate through several channels, you should see note and gate messages cycle among the different splitter channels, while the pitch bend messages are always routed to channel 1. I agree that most keyboards will only be transmitting from one pitch wheel. If you are only playing a single pitch wheel to a polyphonic instrument, this is not a problem. However, if you should want to send a pitch bend along with each note, *and not affect the notes that are already sounding*, you need to rotate the pitch bend along with the note and gate. Please see the attached patch snapshot.
![PW Not Rotating Through Channels Example](https://user-images.githubusercontent.com/22661737/64960063-7d2be700-d860-11e9-9be4-22bdaf691ded.PNG)

**Comment by AndrewBelt** [comment]
Again, PW is a monophonic output because MIDI pitch wheel is a global value. Thus there is no signal in output 2 of Split because there is no channel 2 of the PW output. There is no need to use Split. Simply connect PW directly to the destination.

**Comment by dllmusic** [comment]
> Hi Andrew,
> I think you misunderstood my Scala example. Let me try a different one. If you connect the modules as I said, you should see that the splitter connected to the PW output only lights channel 1 regardless of the polyphony settings on the MIDI-CV module. Setting the polyphony mode to rotate through several channels, you should see note and gate messages cycle among the different splitter channels, while the pitch bend messages are always routed to channel 1. I agree that most keyboards will only be transmitting from one pitch wheel. If you are only playing a single pitch wheel to a polyphonic instrument, this is not a problem. However, if you should want to send a pitch bend along with each note, _and not affect the notes that are already sounding_, you need to rotate the pitch bend along with the note and gate. Please see the attached patch snapshot.
> ![PW Not Rotating Through Channels Example](https://user-images.githubusercontent.com/22661737/64960063-7d2be700-d860-11e9-9be4-22bdaf691ded.PNG)

what you actually want is MPE mode.
