### ISSUE TITLE
Separate plugin version and target ABI version into two properties.

### ISSUE THREAD

**Issue by HelveticaScenario** [VCVRack/Rack#1555]
### Summary

Currently, the `version` property in `plugin.json` serves double duty, specifying the version of the plugin as well as specifying the compatible ABI version. This isn't how semantic versioning works and can be [confusing to new plugin devs that have prior experience with semantic versioning](https://github.com/VCVRack/Rack/issues/1552), as well to users who may mistake a new plugin's 1.x.y version to mean it is stable. According to [the official semantic version specification](https://semver.org/#spec-item-4)

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

yet any new plugin project started today, in order to load in Rack v1.x.x, has to start at major version 1, which according to [the spec](https://semver.org/#spec-item-5)

> Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.

### Proposed design

I propose we add a new field,  `targetABIVersion` (open to suggestions on the name), that when present, will be used for the [abi compatibility check](https://github.com/VCVRack/Rack/blob/d4586c3481e868ded261f7321e486f44d3005b10/src/plugin/Plugin.cpp#L49) leaving the `version` field to only represent the plugin version. If it is not present, the old behavior will be enforced to keep compatibility with older plugins and plugins that choose to keep using the old behavior. The JSON spec for patch files also currently uses the version for ABI version and should probably be updated as well for internal consistency, but this is much less important as these files are not meant to be hand edited.

**Comment by AndrewBelt** [comment]
Currently plugins should not use Semantic Verisoning. The advantage of your proposal of adopting Semantic Versioning for plugins is that that developers that happen to assume their plugins should use Semantic Versioning will end up to be correct. But developers are smart, they can adapt to things.

The disadvantage is that developers would need to market their packages as "VCV Whatever v1.4.5 for Rack v2". This is a mess from the viewpoint of a user. If the developer fails to specify the ABI version by saying "VCV Whatever v0.4.5", it will confuse the user. This is even more of a mess, and it would take several minutes for users to learn and figure this out.

Thus I am rejecting this proposal.
