### ISSUE TITLE
OPENGL32.dll not found on fresh Windows 10 install

### ISSUE THREAD

**Issue by DimitrisKyriakoudis** [VCVRack/Rack#1557]
Fresh install of Windows 10 on a new machine, latest Nvidia drivers, everything else seems to be working fine, but running Rack throws:

> System Error: The code execution cannot proceed because OPENGL32.dll was not found. Reinstalling the program may fix this problem.

Reinstalling my GPU drivers and Rack didn't change anything.

**Comment by AndrewBelt** [comment]
Do you have a file at `C:\WINDOWS\SYSTEM32\OPENGL32.dll`? Do other OpenGL applications fail to open?

**Comment by DimitrisKyriakoudis** [comment]
There was no file, downloading it there solved the problem. 
Does Windows not come with OpenGL by default or did I mess up the installation? I've never had to do that manually before.
