### ISSUE TITLE
Can't open Roland TB-303 since Rack v1

### ISSUE THREAD

**Issue by Cleanthis6** [VCVRack/Rack#1560]
Loadind the 303 vst in Host immediatly crashes Rack
Others Roland's VST of the same bundle are working and the 303 worked fine in 0.6

Windows 10

**Comment by AndrewBelt** [comment]
Do you mean this plugin from Roland Cloud? https://www.rolandcloud.com/Catalog/Legendary/TB-303

**Comment by Cleanthis6** [comment]
Yes it's him, in a VST2 64bits version

**Comment by AndrewBelt** [comment]
Transfering to email, closing.
