### ISSUE TITLE
Sequential Switch 2: If nothing is plugged in to the 1st input, none of the other inputs will work.

### ISSUE THREAD

**Issue by bofusbeats** [VCVRack/Rack#1563]
### Details
Operating system: Windows 10
Rack version: v1.1.1

### Summary
If nothing is plugged in to the 1st input of the ss2, none of the other inputs will output anything.
you can work around this by plugging a 0v source into the first input.
The issue only existsts with vcv sequential switch 2 and with the 1st input. The other inputs can be left empty without problems.

It's not really a problem once you know about it but it can leave one very confused until they figure it out.

Thank you for the amazing software! 
Just thought you should know about this but I understand if it's not a priority.
Best regards, Lukas.

**Comment by AndrewBelt** [comment]
Thanks, fixed in 3ad450c
