### ISSUE TITLE
VCV Crashes when I try to Enter Label on module cf LABEL from Clement Foulc's "cf" plugins

### ISSUE THREAD

**Issue by jon-joy-1999** [VCVRack/Rack#1564]
### Details

Operating system: Windows 10 1903
Rack version: v1.1.4
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

### Summary
VCV Crashes to desktop when trying to enter label text on Clement Foulc's LABEL module
### Steps to reproduce
install plugin library cf 
load cf LABEL
Right-click cf LABEL (LBL) and choose Enter Label
Experience crash

**Comment by Coirt** [comment]
https://github.com/cfoulc/cf/issues/new

**Comment by AndrewBelt** [comment]
Closing. Reopen if this is an issue on Rack's end.
