### ISSUE TITLE
1.1.5: Mapped knobs forget previous value

### ISSUE THREAD

**Issue by jonheal** [VCVRack/Rack#1566]
### Details

Operating system: Windows 10
Rack version: v1.1.5
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): MIDI Twister Fighter

### Summary
I'm pretty sure that with Rack 1.1.4, knobs (mapped to a MIDI pot/encoder) retained their previously set value even after quitting Rack and restarting. With 1.1.5, mapped knobs are at ZERO value upon restarting Rack. I will back off to 1.1.4 to see if this is truly the case.

EDIT: Confirmed. With Rack 1.1.4, previous set values are retained. With 1.1.5, they are lost.

### Steps to reproduce
Map a knob to a MIDI pot/encoder. Move the knob to a value. Quit Rack. Upon restarting Rack, knob is at ZERO value instead of its previously set value. MIDI pot/encoder remains a previously set value. Twist the MIDI pot/encoder slightly, and Rack knob jumps to that value.

**Comment by AndrewBelt** [comment]
Thanks, fixed in 82098f2

**Comment by jonheal** [comment]
Thanks.
