### ISSUE TITLE
VCV Recorder volume LED's not working after upgrade to 1.1.5

### ISSUE THREAD

**Issue by alasdairmoons** [VCVRack/Rack#1568]
I don't know if this really is a vcv bug, 
but after upgrading to vcv 1.1.5 on sunday I saw that the volume LED's of the recorder stopped working on my Linux Mint. 
I now co-checked with 1.1.4 and they still do not work. 
Last saturday (28.09.) I recorded a vid and posted it on YT and you can see that the LED's work just fine.

Any idea?

**Comment by alasdairmoons** [comment]
I made some other testes and it was just the recorder in that particular patch that did not show any LEDs, I deleted the recorder and added another one and all seems to work fine again.

**Comment by AndrewBelt** [comment]
Reopen if you experience this again. VCV Recorder should not be able to get in a state where the VU meter lights do not work.
