### ISSUE TITLE
Addition of a couple more frame rates for extreme use cases.

### ISSUE THREAD

**Issue by circadiansound** [VCVRack/Rack#1569]
### Summary

There are some instances, in my personal usage, where a patch can be too large to record and perform, without introducing some clicks and pops during playback. I understand why “10hz” was selected to be the lowest frame rate resolution, as the graphical updating becomes really choppy at anything lower. 

There are some use cases where a frame rate of 5hz and even 3hz is suitable enough to capture a video with clean audio, and live perform the patch with a MIDI controller. I understand that mouse interaction with the interface becomes too laggy to work with at these lower rates, but a static video capture would still function with less audio playback issues.

### Proposed design

I would suggest to add frame rates of 5hz and 3hz to the view menu, as solution for extreme cases where patches are too big to record and perform with clean audio. Another solution would be to reintroduce the ability to edit the .json file again, to get at these “inbetween” and “lower” frame rates.

**Comment by AndrewBelt** [comment]
You can edit `settings-v1.json` to set `frameSwapInterval` to any factor. The frame rate is `1 / frameSwapInterval`.

**Comment by circadiansound** [comment]
Oh, that’s awesome! I was confused when I opened the `settings-v1.json` file and saw the `frameRate` was missing. Glad that we’re still able to go under the hood and tweak this, if need may be. I’ll close this now, considering this feature is still implemented.
