### ISSUE TITLE
SVG components layer positioning in Rack

### ISSUE THREAD

**Issue by knchaffin** [VCVRack/Rack#1570]
After working on this a couple of days, I have my module SVG file working to display the panel the correct size in Rack.  But, when I create the components layer and add one green input circle, in Rack the input jack renders at the wrong vertical coordinate but the correct horizontal coordinate.  I'm using Inkscape with all units set to mm.  I've looked through the forums and see some similar issues but can't find a fix to my problem.  I'm probably doing something stupid but this is my first Rack plugin and module.  I am using helper.py for module creation.

**Comment by AndrewBelt** [comment]
Sometimes Inkscape randomly puts `translate()` styles on the `components` layer. I don't know why, but you can try the following.
- Select all objects in the components layer
- Cut
- Delete layer, create another called `components`
- Edit > "Paste in place"
- Regenerate the panel with the `helper.py` script

**Comment by knchaffin** [comment]
By golly, that worked.  Inkscape does a lot of mysterious things:)

Thank you very much for your quick response.
