### ISSUE TITLE
Make parameter tool tips aware of their position on the screen relative to the edges of the display

### ISSUE THREAD

**Issue by jonheal** [VCVRack/Rack#1571]
### Summary

Parameter tool tips currently can fall off screen with modules near the edges. Is it possible to ensure that they are always drawn on screen?

### Proposed design

The position a parameter tool tip on the screen will be such that no portion of it is drawn off screen (at least on the left and right sides of the display).

**Comment by AndrewBelt** [comment]
>Parameter tool tips currently can fall off screen with modules near the edges

I can't reproduce this. Can you post a screenshot?

**Comment by AndrewBelt** [comment]
Ah, I noticed this on `ParamTooltip`s. Fixed in 08f97d2

**Comment by jonheal** [comment]
Thanks.
