### ISSUE TITLE
Renaming Engine => Threads into Cores or similar

### ISSUE THREAD

**Issue by alasdairmoons** [VCVRack/Rack#1573]
Hi all, 

I know this is not a real request but more an idea, resulting out of some frustration as VCV noob.

It took me a while to understand, that by Engine => Threads the numbers off CPU-cores was meant.
I did set rack to "lowest CPU usage" cause I though, then the modules use less CPU and not, only one Core is used in total. 
It was very frustrating to get the typical jitters and freezes with only a couple of modules, specially on an i7 with 8 cores cause that one core was flooded to 100%.
I know that, seeing it from a pro-side, THREAD is absolutely correct wording, BUT, for some, it could be a bit confusing .. 
In Renoise f.e. there is a menue called CPU, where I can choose how many "CPUs" I want Renoise to use .. maybe wrong wording, but absolutely understandable for NoN-Core-Developers ;) ..

not nagging or comparing to others ....  cause I am happy now that I found out how to set the Threading right ;)
just an idea
 
Greetings, Sascha

**Comment by AndrewBelt** [comment]
"Threads" is fine. As you said "cores" and "CPUs" is incorrect.
