### ISSUE TITLE
app.hpp doesn't build any more

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#1574]
the define of APP is now `rack::rack::getApp()` (I think).

In my code I had always accessed it like this:

return rack::APP->engine->getSampleRate();

Now even if I remove that code I get errors just trying to compile app.hpp. btw: I include SDK files one at a time - I don't use the big "include everything" header.

Here's a typical error:
```
In file included from src/seq/SqGfx.cpp:7:
src/seq/SqGfx.cpp: In static member function 'static void SqGfx::drawText(NVGcontext*, float, float, const char*, int)':
../../include/app.hpp:52:13: error: 'rack::rack' has not been declared
   52 | #define APP rack::appGet()
      |             ^~~~
src/seq/SqGfx.cpp:32:19: note: in expansion of macro 'APP'
   32 |     int f = rack::APP->window->uiFont->handle;
      |  
```

**Comment by squinkylabs** [comment]
Oh - I think the problem is that my old "work around" code isn't needed any more! I was using rack::APP, which I don't need to do now. I think it's all my mistake. One moment....

**Comment by AndrewBelt** [comment]
No, `rack::APP` expands to `rack::rack::getApp()`.
If you write this, the API is backward compatible, because `rack::rack::getApp()` exists due to
```cpp
	namespace rack = rack;
```
in rack.hpp, which your code should include.

**Comment by squinkylabs** [comment]
Oh, I get it it now. Yep, that's my problem, I don't like to include rack.hpp since it includes the world. Admittedly I probably should include it, as I now realize I'm relying on unsupported behavior.

tx!

**Comment by AndrewBelt** [comment]
Yes, all plugins must include rack.hpp, so it is indeed unsupported behavior.

**Comment by squinkylabs** [comment]
And I see that's why the DEBUG macro does't work for me ;-)

It is difficult for me to accept having `using` statements in global includes. To me it sort of defeats the purpose of having a namespace in the first place. But I don't need to be dogmatic about it.

**Comment by AndrewBelt** [comment]
There are no root `using` statements in Rack's header files. All symbols are in the `rack` namespace.

**Comment by squinkylabs** [comment]
ah - then I withdraw my comment. This sounds just fine. tx.
