### ISSUE TITLE
Change default browser

### ISSUE THREAD

**Issue by zeronoises** [VCVRack/Rack#1575]
I really like the right click option to open a browser window with the manual or other website for each module - it goes a long way to giving me the functionality I requested at a much earlier stage in the project (probably on the Facebook group).
However, instead of launching my resource intensive main browser, I'd like to be able to opt to open a lightweight browser - I'm thinking of surf for myself - that doesn't put a strain on an already overloaded box. As I use i3 I could direct it to speedily open a small floating window - at the mouse position! That would be very pleasing...
A section in the settings file would suffice.

**Comment by AndrewBelt** [comment]
Rack's `system::openBrowser()` just calls `xdg-open <url>` on Linux, so just change what browser that uses.

**Comment by zeronoises** [comment]
But I'd like to keep my main browser as the default for (most) other uses....
