### ISSUE TITLE
Problem creating launcher for VCV Rack

### ISSUE THREAD

**Issue by pat-san** [VCVRack/Rack#1576]
Hello,
I have a problem with a launcher for VCV Rack on Linux Solus OS.
I created a .desktop with this:

> [Desktop Entry]
> Name=VCV Rack
> GenericName=VCV Rack
> Comment=Modular Rack Synthetizer!
> Icon=/opt/icon.png
> Exec=/opt/Rack/Rack
> Terminal=false
> Type=Application
> Categories=AudioVideo;Audio;Midi;
> Name[fr_FR]=VCV Rack

But when I launch it I have this window that appears:
![Capture de 2019-10-04 13:50:56](https://user-images.githubusercontent.com/44109252/66206023-56621300-e69e-11e9-9785-72e8db68710d.png)

What I don't understand is why there is a hidden folder needed `./res` (with a dot) instead of `/res`.
Is there anything I did wrong?

Thank you

Operating system: Linux Solus OS
Rack version: v1.1.5

**Comment by AndrewBelt** [comment]
The cwd of Rack needs to be its own directory. I think you can add
```
Path=/path/to/rack/dir
```
or
```
Exec=cd /path/to/rack/dir && ./Rack
```

**Comment by pat-san** [comment]
Thx for answering,
It doesn't work.
There is something odd with the ./res folder, it doesn't exist nowhere. there is only a /res  in  /Rack folder. 
I will continue to launch VCV from his folder but if someone know what's going on, any help will be welcome

**Comment by AndrewBelt** [comment]
If the cwd is not being set, there's either an issue with your launcher or Rack's system directory. What is the pathname of Rack's system directory on your computer, and what is the `Path` line in your launcher?

**Comment by pat-san** [comment]
Ah ok, my mistake, I've add `Path=/opt/Rack` and it works now.

Thank you so much for helping me Andrew.

**Comment by AndrewBelt** [comment]
Glad you solved it
