### ISSUE TITLE
Automate panel workflow a bit

### ISSUE THREAD

**Issue by ensonic** [VCVRack/Rack#1578]
# Summary

The [Panel Guide](https://vcvrack.com/manual/Panel.html#svg-limitations) explains that all text must be converted to path. Doing this manually is error prone, but luckily it can be automated.

### Proposed design
This makefile snippet would do this automatically.
```Makefile
# Convert text to path
# run the $RACK_DIR/helper.py with the input to find the layers
res/MyModeule.svg: src/MyModule.svg
	inkscape -z --vacuum-defs -T -f $< -l $@ 
```
One difference is that we now put the original svg into src, the generated one will be in res.
On downside is that it needs to be run manually `make -B res/MyModule.svg` after editing the panel, the makefile rules don't know that the plugin would depend on a `res/MyModule.svg'. Also in the instruction we need to tell people to run the ` $RACK_DIR/helper.py` with the file in src.

If you are willing to accept a tool dependency on xmlstarlet we can even do:
```Makefile
# Convert text to path, ensure that the component layer is hiddne
# run the $RACK_DIR/helper.py with the input (in src) so that it finds the layers
res/MandelOsc.svg: src/MandelOsc.svg
	inkscape -z --vacuum-defs -T -f $< -l - | \
	xmlstarlet ed -u "/_:svg/_:g[@id='components']/@style" -v "display:none" >$@
```
This will also ensure that one does not forget to hide the component layer (can probably also be done using sed or event using the $RACK_DIR/helper.py ).

WDYT?

**Comment by david-c14** [comment]
related item https://github.com/VCVRack/Rack/issues/828

**Comment by AndrewBelt** [comment]
There are many methods for obtaining an SVG file without text objects, so I will leave it up to the plugin developer to chose and implement their method.
