### ISSUE TITLE
Audio Interface input normalling.

### ISSUE THREAD

**Issue by dphelmer** [VCVRack/Rack#1580]
Would it make sense to normal the left input to the right input until something is plugged into the right input for each of the stereo pairs of the Audio Interface module? Seems like it would slightly streamline most people's workflow.

**Comment by AndrewBelt** [comment]
We've decided against this for Audio-8/16, but if an Audio-2 module releases, it will be more "beginner-oriented" and will likely have normalized L/MON and R inputs.
