### ISSUE TITLE
FrameRateLimit param disappeared from settings-v1.json

### ISSUE THREAD

**Issue by dadakopf** [VCVRack/Rack#1581]
Rack version 1.1.5
MacOS 10.11.6

I have been resetting FrameRateLimit in the settings file to avoid crackling in the audio. The crackling returned and I looked at the file. The params are no longer there. This was a good workaround regarding CPU performance. i have been making some hefty VCV patches...

This was the content of the file today.

```
{
  "token": "",
  "windowSize": [
    0.0,
    0.0
  ],
  "windowPos": [
    0.0,
    0.0
  ],
  "zoom": -0.0809999257,
  "invertZoom": false,
  "cableOpacity": 0.5,
  "cableTension": 0.5,
  "allowCursorLock": true,
  "realTime": false,
  "sampleRate": 44100.0,
  "threadCount": 2,
  "paramTooltip": false,
  "cpuMeter": false,
  "lockModules": false,
  "frameSwapInterval": 1,
  "autosavePeriod": 15.0,
  "patchPath": "/Users/nealjohnson/Desktop/LyraRedesign.vcv",
  "cableColors": [
    "#c9b70e",
    "#0c8e15",
    "#c91847",
    "#0986ad"
  ]
}
```

**Comment by AndrewBelt** [comment]
Please do not post user tokens on the internet.

`frameRateLimit` was replaced with *View > Frame rate*.
