### ISSUE TITLE
MW and PW Messages are Mono Even in Poly Mode

### ISSUE THREAD

**Issue by FunkybotsEvilTwin** [VCVRack/Rack#1587]
Using the MIDI CV module, I noticed that MW and PW didn't function as expected in Poly Mode. Both messages were only being transmitted on channel one. In standard Poly Mode, I'd expect these messages to also be polyphonic and applied to all channels equally. In MPE mode, obviously pichbend would need to be per channel. 

Operating system: windows 10 x64
Rack version: 1.15

### Steps to reproduce

1. Load MIDI CV
2. Load the polyphonic A*B+C module from the unofficial beta
3. Load an LFO-1
4. Send vOct to the c1 input of the Befaco module, set the c1 knob to max
5. Route the triangle output of LFO-1 to the A1 input and increase the B1 knob slightly
6. Route the MW output to the B1 input

Expected Result: polyphonic modwheel. 

Actual Result: modwheel is monophonic. A Merge module with 16 copies of MW Input is required to get this working. 

7. Replace MW with PW...

Same expected/actual results.

**Comment by AndrewBelt** [comment]
This is expected behavior. On a normal keyboard, pitch wheel shifts the pitch of all pressed keys, and mod wheel applies modulation to all voices.
On an MPE keyboard, PW and MW are polyphonic, meaning that generating a PW/MW message on channel N is intended to affect only the note played on channel N.
VCV MIDI-CV handles this correctly in both cases.

**Comment by FunkybotsEvilTwin** [comment]
Andrew, I agree that's what should be happening, but it's not what I'm seeing here. If I run Modwheel or Pitchwheel into something like A*B+C with V/OCT as the C, modwheel and pitch do NOT effect all channels on a polyphonic patch. As you indicate, they should be audible on ALL channels in poly mode like any other polyphonic synth but they're just not.

They're only polyphonic if I run 16 copies of MW and PW into a MERGE module, then route that into A*B+C, which I don't think is expected or should be required.

**Comment by AndrewBelt** [comment]
Befaco is not a polyphonic plugin. You need to use modules tagged with Polyphonic to process polyphonic cables.

**Comment by FunkybotsEvilTwin** [comment]
I'm using the Polyphonic versions of Befaco found here: https://github.com/martin-lueders/Befaco/issues/3

**Comment by AndrewBelt** [comment]
Then this is a bug with that fork. Report it in that project's issue tracker.

**Comment by FunkybotsEvilTwin** [comment]
I get that I'm probably coming across as a pest, but how can I test and confirm with default Rack modules? Here's what I'm seeing

1. The MW and PW cables are mono cables. 

2. If I run a MW or PW output from MIDI-CV directly into Poly Viz and increase either, I only see activity on poly channel 1. Wouldn't MW or PW be visible in all channels? Shouldn't those cables be polypohonic coming out of MIDI-CV?  

3. I can setup tests where I'm running 8 channels of polyphony in rotate mode, playing one note at a time, and pitchbending every single note but only the 1st voice of 8 actually gets pitchbend. 

This all makes me think that even in Polyphonic mode, MW and PW signals are only impacting Poly Channel 1 and not Channels 1-16 as expected. I could totally not be getting something about how this is supposed to work but what I hear you saying, and what I'm actually seeing are not in sync.

**Comment by AndrewBelt** [comment]
Maybe this will clear it up. https://community.vcvrack.com/t/rack-development-blog/5864/41

1) That is correct behavior. (Except in MPE mode, they're polyphonic, which is correct.)
2) That is correct behavior. 

>Wouldn't MW or PW be visible in all channels? Shouldn't those cables be polypohonic coming out of MIDI-CV?

No and no, as explained above. PW and MW are global signals. (Except in MPE mode.)

3) This is *not* correct behavior, and it is due to a bug in Befaco A*B+C or other modules.

**Comment by FunkybotsEvilTwin** [comment]
Thanks for taking the time to explain it Andrew. Sorry for the rabbit hole, but I get it now. I'll report the issue with the poly Befaco.
