### ISSUE TITLE
avoid crashed due to faulty calls of configParam from within process

### ISSUE THREAD

**Issue by Stubs42** [VCVRack/Rack#1589]
Calling configParam from with the process Method invalidates pointers, resulting in crashes of Rack.

I'm sure there will other developers running in similar problems and more important this does not always show up in testing modules with this faulty use of configParam. Those modules might show up in plugin manager causing problems to users.

I propose to change configParam to not delete and recreate the parameterQuantity if it already exists but just setting the member variables of the existing pararameterQuantity to make configParam available to reconfigure parameters from with process.

If this is not feasible then just assert this situation by crashing every time a module tries to do that by checking whether there is already a parameterQuantity assigned, so testing will reveal the problem immediately. A line of API documentation in the paramConfig telling that this is not allowed in process would be a good idea too in this case.

**Comment by AndrewBelt** [comment]
`configParam()` should be called once in the `Module` constructor.
If you want dynamic `ParamQuantity` data, either subclass that class and call `configParam<MyParamQuantity>()` in the constructor, or set variables directly such as
```cpp
paramQuantities[MY_PARAM]->minValue = 0.f;
```
