### ISSUE TITLE
Can't manage or add modules behind a proxy

### ISSUE THREAD

**Issue by stibinator** [VCVRack/Rack#1593]
### Details

Operating system: Windows 10 x64
Rack version: v1.1.5
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): N/A

### Summary
I'm on a machine on a corporate LAN, the firewall on this machine is off, but it connects to the internet through a proxy (yes, I get paid to play with VCV, how good is that!).
The problem is that VCV rack doesn't allow me to manage modules. All I see is the message "Could not query updates". 
I'm guessing that VCV is either using a port number that our firewall does not permit, or is not aware of the system's proxy settings. If it's the former I'll make this a feature request - allow using port 80 for module downloads.
My workaround is to download the modules using VCV on a machine at home, and then copy the files to my work machine.

### Steps to reproduce
install VCV on machine behind proxy
add modules to your library from the website
VCV application shows "Could not query updates" in the Library menu.
However, modules that are manually placed into the modules folder are recognised.

**Comment by AndrewBelt** [comment]
Rack uses libcurl, so you use the following environment variable. https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html

**Comment by stibinator** [comment]
Hmm. I tried setting the http_proxy and https_proxy environment variable, but no luck.

**Comment by AndrewBelt** [comment]
Apparently proxies were disabled in the libcurl build. Fixed in 72abbf8.
If you compile from source, let me know if that fixes it.

**Comment by stibinator** [comment]
Great work, thanks!

**Comment by stibinator** [comment]
Seems to have done the trick.
