### ISSUE TITLE
Some modules fail to build after log2 change

### ISSUE THREAD

**Issue by netboy3** [VCVRack/Rack#1595]
Operating system: Ubuntu 18.04
Rack version: v1 @043401c3

### Summary
[Commit 7eb5017](https://github.com/VCVRack/Rack/commit/7eb5017efd79854f0c6691da2dcaced14d21a1a0) introduced an issue using log2() in some plugins. The new template log2() is not type-safe and generates a compile error if any calls to the new log2() template are called as log2(float). Previously, it simply used the overloaded std::log2().

### Steps to reproduce
Build any of the modules that use log2(float), such as AmalgamatedHarmonics:

```
g++  -std=c++11 -Wsuggest-override   -fPIC -I../../include -I../../dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_LIN  -c -o build/src/Generative.cpp.o src/Generative.cpp
In file included from ../../include/rack.hpp:7:0,
                 from src/AH.hpp:5,
                 from src/Generative.cpp:5:
../../include/math.hpp: In instantiation of ‘T rack::math::log2(T) [with T = float]’:
src/Generative.cpp:286:56:   required from here
../../include/math.hpp:82:11: error: invalid operands of types ‘float’ and ‘int’ to binary ‘operator>>’
  while (n >>= 1) {
         ~~^~~~~
```
### Resolution
I'm not sure if this should be reverted or the plugin developers should be notified to either use explicit std::log2 or (int)cast their call (if applicable).

**Comment by AndrewBelt** [comment]
Ah, forgot that people are using the C-style version of `log2`. Reverted in 47b7995.
