### ISSUE TITLE
Feature request: after updating plugins show the Module browser featuring the updated modules

### ISSUE THREAD

**Issue by Thihi** [VCVRack/Rack#1596]
### Summary

As a user, I would like to see a quick summary of what changed when I update plugins without having to search for it on the forums, the Facebook group, or a readme somewhere in my filesystem.

### Proposed design

After a plugin update, add an "Updated" tag to new and updated modules. Add the "Updated" tag as one of the browsable tags in the module browser. Remove the "Updated" tag from a module after a week or so.

After updating plugins and relaunching VCV Rack, open the module browser automatically with the "Updated" tag selected. This gives a quick view of what's changed and what's new.

Might be a nice addition to also have a button which adds all the currently filtered modules into the Rack. It would make it nice and easy to quickly to play around with the updated stuff.

I think this should be pretty robust. It's quick to click it out of the way if you don't want to see the updated modules after relaunch.

The only big ux problem I see is that the additionally suggested button to quickly add all filtered modules to rack might fry some people's CPUs if they press it when nothing is filtered and they have a large plugin selection. So maybe limit the number of modules that can be added with the button to 10 or so? Maybe also add a setting into the settings file to select the maximum amount of plugins that can be added this way.

**Comment by AndrewBelt** [comment]
The Module Browser displays plugins in order or most recent, so this is effectively already a feature, just without an "Updated" tag. I'm unable to get more granular than plugins because there's currently no data structure containing lists of *modules*, only plugins. Maybe in Rack v2 when the ability to whitelist modules in a plugin is added, we could work something like this into the high-level design.

**Comment by Thihi** [comment]
Yup, I've noticed that the module list is sorted by the newest and that is already pretty good, but for instance, now that the Fundamental modules updated, I'm not sure which modules actually changed. Would love some kind of implementation of this in Rack v2.

**Comment by AndrewBelt** [comment]
The point is, *I'm not sure which modules actually changed* either. What would define a "change" to a module? Obviously new modules, but what about other cases?

**Comment by stoermelder** [comment]
Maybe you can add an optional `version` property for each module in `plugin.json`?

**Comment by AndrewBelt** [comment]
@stoermelder That's an idea, hadn't thought of that. Kinda weird though. It wouldn't be immediately obvious that `.modules[].version` means "The module was last updated in this plugin version" to developers. Also, if say VCV VCO-1 is marked `1.2.0` and the plugin is `1.3.0`, the manifest wouldn't be able to sort by last-updated, just display whether it was updated or not in the last plugin update. For example, if VCV VCO-1 was updated in `1.2.0` and a quick patch to VCV VCO-**2** was made in `1.2.1`, even though VCO-1 was just updated, it would lose its updated status.

To do that, you'd need timestamps. Timestamps per module would be even more time-consuming to manage than versions per module. I can't think of another way of doing it that doesn't have correctness issues.

**Comment by stoermelder** [comment]
I agree. I don’t think it’s worth the effort handling something like timestamps. 
Even if Rack can promote updated modules in the browser the user still doesn’t know what has changed exactly and needs to read the changelog or something.

**Comment by AndrewBelt** [comment]
Closing since the Module Browser already displays modules in order of plugin folder timestamps.
