### ISSUE TITLE
Host-FX cannot recall Fabfilter plugin presets

### ISSUE THREAD

**Issue by dedeqtor** [VCVRack/Rack#1597]
Hello, 

Operating system: Windows 10 Pro 1903, 32Gb RAM, Intel i7 4770
Rack version: v1.1.5

With host fx when I load a fabfilter plugin it works fine but when I load again the patch, fabfilter effect goes back to default preset.

**Comment by AndrewBelt** [comment]
Thanks, we'll take a look.

**Comment by RichieHindle** [comment]
@dedeqtor: I can't reproduce the problem.  Here's what I'm doing:

1. Make a patch with just a Host FX instance, and load FabFilter Pro-Q 3 into it.
2. In the Pro-Q window, select a preset from the dropdown menu.
3. Save the patch.
4. Go File / New to clear the patch.
5. Go File / Open and reload my saved patch.
6. The Pro-Q preset that I selected before is still selected.

If I repeat steps 2 to 5, it all still works - the selected preset is correctly selected when I load the patch.

Are you doing something differently?  Using a different FabFilter plugin, maybe (you didn't say which one you were using)?

**Comment by Coirt** [comment]
Tried the above with Q2 it will load the last preset curves but it is named "Default Setting" this is greyed out with a check mark in the Q2 preset menu on "Default Setting".

I just tested this in another DAW and the behaviour is different. It will load the preset but it will name it to the parent preset which is greyed out, e.g. "Drums" with the check mark on Drums in the menu.

Also Tested:
- Fabfilter C2, the same behaviour.
- Ozone 8 Maximizer, saves/loads the same patch even if changed, i.e. asterisks on the patch will still be there when Rack patch reloads

**Comment by RichieHindle** [comment]
Ah, thanks, yes - I can reproduce that if I use FabFilter C2.

Sadly I'm about to go away for a week, so I probably won't be able to look at this until I get back - I apologise for the bad timing.

**Comment by dedeqtor** [comment]
I was testing this with fabfilter pro-R. I tried again but same result. it goes back to default preset on recall.

**Comment by AndrewBelt** [comment]
This is the issue tracker for VCV Rack. Send bug reports and feature requests of VCV plugins to contact@vcvrack.com.
We have added this to our internal issue tracker. Comment your email address here if you would like to be informed of future updates to this issue.
