### ISSUE TITLE
build script - Ensure the result is a string rather than being formatted as a JSON string with quotes

### ISSUE THREAD

**Issue by polyclash** [VCVRack/Rack#1598]
### Details

Operating system: ALL
Rack version: v1.1.5
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): no

### Summary
https://github.com/VCVRack/Rack/blob/95ddb89d07fcd3f2585e1036d6cb72a0d1b2039b/plugin.mk#L5-L6
**jq --raw-output** ensure the result is a string rather than being formatted as a JSON string with quotes.

### Steps to reproduce
```json
$ jq .slug plugin.json
"SLUG"

$ jq .slug --raw-output plugin.json
SLUG
```

**Comment by AndrewBelt** [comment]
What's the bug?

**Comment by polyclash** [comment]
this format a directory name /rack/plugin/"SLUG"

**Comment by AndrewBelt** [comment]
I don't understand, can you post the error message?

**Comment by polyclash** [comment]
fortunately this not generate any error,
but for safe file system specification you not have to use quote char in directory name.

**Comment by polyclash** [comment]
all directory and filename have quote:
```
$ make install
rm -rf dist
mkdir -p dist/"SLUG"
cp plugin.dll dist/"SLUG"/
strip -s dist/"SLUG"/plugin.dll
cp -r --parents LICENSE.txt res plugin.json dist/"SLUG"/
cd dist && zip -q -9 -r "XY-Z_80"-"1.0.0"-win.zip "SLUG"
cp -au dist/"SLUG"-"1.0.0"-win.zip C:/Rack/plugins/
```

**Comment by AndrewBelt** [comment]
Although slugs or versions are not allowed to have spaces in them, if they do, the quotes keep those commands safe. So I'll use your suggestion to define `SLUG` and `VERSION` without quotes, but add the quotes back when using them in paths. 3cd9c13

**Comment by polyclash** [comment]
I think that the quote need to be add like this:
```bash
$ make install
rm -rf dist
mkdir -p "dist/SLUG SPACED"
cp plugin.dll "dist/SLUG SPACED/"
strip -s "dist/SLUG SPACED/plugin.dll"
cp -r --parents LICENSE.txt res plugin.json "dist/SLUG SPACED/"
cd dist && zip -q -9 -r "SLUG SPACED-1.0.0-win.zip" "SLUG SPACED"
```

**Comment by AndrewBelt** [comment]
`"Th"is` works fine in all the shells I use. Let me know if you find one where it doesn't.

**Comment by polyclash** [comment]
this is not elegant, but I can accept you convention
