### ISSUE TITLE
Audio Device Selection menu FLASHING making it unusable on WIN10

### ISSUE THREAD

**Issue by M4R71Ngitub** [VCVRack/Rack#16]
In core audio interface module, clicking on the Audio Device selection menu makes it flash and duplicate (trouble vision like effect) making it unreadable.

Windows 10

**Comment by QrchackOfficial** [comment]
I can confirm the issue, here's a screenshot. The menu flickers up and down, seems like a redrawing issue?

![image](https://user-images.githubusercontent.com/3584315/30278762-a66d78ce-970b-11e7-89b8-0d3ab0a2bda7.png)

**Comment by JoeSleaze** [comment]
Having the same issue.

**Comment by AndrewBelt** [comment]
Fixed with 72593654eaf2794dddd737599d38aed0561bcfb8

**Comment by QrchackOfficial** [comment]
Great! When can we expect a release? Have you thought of using something like Travis CI for nightlies?

**Comment by AndrewBelt** [comment]
Travis CI would be fantastic, but does it handle

- Mac, Windows, and Linux?
- The ability to link system libraries that might not be installed on a headless machine, specifically libgl and gtk+-2?
- `make dep` takes 15 minutes and lots of CPU. Any way to do only once the `dep/Makefile` is updated?
- Optionally SSH access to investigate why a build failed?

Actual question, I don't have the time to look this up right now.
