### ISSUE TITLE
VCV Host crashing when Waves Electric 88 Instrument is selected.

### ISSUE THREAD

**Issue by pgatt** [VCVRack/Rack#1600]
### Details

Operating system: Mac OS X 10.14.6
Rack version: v1.1.5
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):
None, AFAIK.

### Summary
Waves Electric 88 Instrument crashes Rack upon selection in the VST Host selection menu.

### Steps to reproduce
Place VCV Host Instrument Module in the Rack.
Select WaveShell1-VST 10.0
Select Electric88 Stereo.
Rack immediately crashes

Log and Crash report attached.
[log 9.txt](https://github.com/VCVRack/Rack/files/3748542/log.9.txt)
[Waves Electric 88 Crash.txt](https://github.com/VCVRack/Rack/files/3748543/Waves.Electric.88.Crash.txt)

**Comment by AndrewBelt** [comment]
Thanks, we'll take a look.

**Comment by RichieHindle** [comment]
Works fine on Windows.  Will check MacOS, hopefully later today.

**Comment by AndrewBelt** [comment]
@pgatt Can you verify that your Waves Electric 88 plugin is installed correctly? If you have another DAW, does the plugin crash there as well?

**Comment by pgatt** [comment]
No it definitely works in other software.

**Comment by AndrewBelt** [comment]
This is the issue tracker for VCV Rack. Send bug reports and feature requests of VCV plugins to contact@vcvrack.com.
We have added this to our internal issue tracker. Comment your email address here if you would like to be informed of future updates to this issue.

**Comment by pgatt** [comment]
pgatt@yahoo.com
