### ISSUE TITLE
Bind hotkey(s) to user defined location within the rack window

### ISSUE THREAD

**Issue by OhW3ll** [VCVRack/Rack#1601]
### Summary
To speed up workflow (especially on small screens), bind key(s) to user-defined locations within the rack. 

Example use cases: 

- The new MixMaster module by MindMeld takes up almost all of the screen width at 100% on a 13" laptop screen. Being able to use a key to move the screen to and from the area of the rack where the module is located and the rest of a patch would make for a similar workflow to toggling back and forth between the mixer view and arranger view in a DAW. 
- More generally, users could quickly navigate between areas of a patch that exceed their screen’s dimensions at a zoom distance comfortable enough for fine-tuning parameters. 

### Proposed design
Implementation concern: the current computer keyboard MIDI driver takes up the majority of the keys that would make intuitive sense for this use (such as the number row.)

Possible solution: use the **TAB** key only. 

Implementation option 1 (toggle to location L and back): only 1 user-defined location L can be defined per patch. Pressing **TAB** moves the rack window to location L. Pressing **TAB** again moves the rack window back to the last location prior to using TAB to move to location L. 

Implementation option 2 (toggle between L1-L4): For any patch, users can define up to 4 locations L1-L4. Pressing TAB cycles between those locations in a user-defined order. 

Allow two procedures for saving the current location(s):    
- (Mouse and Menus) Clicking on the relevant option within the **View** topmenu. (If more than 1 locations per patch are allowed, use a submenu to specify which location slot the current location will take.)
- (Keyboard Shortcut) Using the relevant keyboard shortcut. (Perhaps **cmd(Mac)/ctrl + L** if there is only 1. If there are more than 1 location, perhaps **cmd/ctrl + 1**, **cmd/ctrl + 2**, **cmd/ctrl + 3**, **cmd/ctrl + 4** to save to the relevant L1-L4 slot.)

**Comment by OhW3ll** [comment]
**Amended design proposal**
In hindsight, a much more straightforward approach would be: allow mapping midi messages to camera locations through the MIDI-MAP module.

**Comment by stoermelder** [comment]
You can use this module for your request:
https://library.vcvrack.com/Stoermelder-P1/Goto

**Comment by OhW3ll** [comment]
I noticed on the forum! :) I’m amazed by how much functionality your modules add, and by how extensible vcv is designed to be.
