### ISSUE TITLE
compiling plugin: make always generate the /dep folder

### ISSUE THREAD

**Issue by polyclash** [VCVRack/Rack#1602]
### Details

Operating system: ALL
Rack version: v1.1.X
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): none

### Summary
https://github.com/VCVRack/Rack/blob/89f14d5699032454f835d45d39af020b7fbbe1f8/dep.mk#L3-L6
This create always the /dep folder in the makefile root folder, and this is not needed when compiling the plugin and can produce conflict with user folder.

acceptable solution?
```makefile
# The install location for `make install`
DEP_LOCAL ?= dep
ifeq ($(RACK_DIR), .)
	$(shell mkdir -p $(DEP_LOCAL))
endif
DEP_PATH := $(abspath $(DEP_LOCAL))
```

### Steps to reproduce
just make the plugin.

**Comment by AndrewBelt** [comment]
Unfortunately there's no way for the build system to know whether `dep/` is used or not. Some plugins' `dep` target starts off with doing `cd dep && $(WGET) http://...`, and this would fail if `dep/` doesn't exist.

**Comment by polyclash** [comment]
I think is responsibility of the developer of plugin to create this folder if not exist and not the built-in makefile.

**Comment by AndrewBelt** [comment]
Perhaps, but it's very easy to forget adding `mkdir -p "$(DEP_LOCAL)"` to the top of all targets. And I can't make breaking changing to the Rack API.

**Comment by AndrewBelt** [comment]
Comment if you can think of a solution to avoid creating `dep/` unless it's needed.
