### ISSUE TITLE
VCV Host - Additional midi in channels

### ISSUE THREAD

**Issue by MiguSchweiz** [VCVRack/Rack#1607]
In VCV host: provide additional midi in channels via e.g. cv-midi modules

### Summary

Some vst plugins (eg virus Ti panel) provide multiple parts on different midi channels. With this feature it would be possible to control more than 1 part via vcv rack.

### Proposed design

Provide the vst midi device for channel 2+ via e.g cv-midi modules.

**Comment by AndrewBelt** [comment]
Email contact@vcvrack.com for VCV Host feature requests.
Already in internal issue tracker.
