### ISSUE TITLE
VCV Host: NI Reaktor 6 Ensemble causes unresponsive VCV GUI and crash on quit.

### ISSUE THREAD

**Issue by ninoxrufa** [VCVRack/Rack#1608]
**System**
2012 Macbook Pro
External display
Mac OS 10.13.6. (Bug was also present in 10.11.x).
All Rack v.1.x.x versions. (I'm 80% certain the issue was not present in v0.6).

**Summary**
When two instances of the Reaktor Ensemble 'Granmaster' (one that I use all the time unfortunately) are present in Rack, the Rack GUI becomes unresponsive, and crashes on quit (see log.txt).

**Steps to reproduce**
1. Load the attached patch. It contains two Host modules and an 8Vert (but any module will do).
2. Locate and load Granmaster in each Host. There are two modes: 'Audio In' and 'Sample'. Make sure at least one Granmaster is set to 'Audio In'
3. Attempt to turn a knob on the 8Vert. It's unresponsive.
4. Select 'Sample' mode on both Granmasters. Problem stops.

**Cause**
It seems to be related to data that is being sent by the System Info module to another module. This data is related to the display update. Disconnecting the wire stops the problem.

**Notes**
- In earlier versions of Rack 1.x the GUI would remain unresponsive regardless of the mode, until samples were loaded (drag and drop). This does not seem to happen currently. 
- Using two Host modules each containing a Reaktor plugin is not part of the problem. I.e. I tested combining two Granmasters into one ensemble in one Reaktor plugin in just one Host. Made no difference.
- I've used multiple instances of this Ensemble in Ableton Live without an issue.
- Yep it's pretty niche. I haven't found other ensembles with the same problem (only tried a couple). Though of course it may signal a broader underlying issue.

[Granmasters Bug.vcv.zip](https://github.com/VCVRack/Rack/files/3760836/Granmasters.Bug.vcv.zip)
[Granmaster Test 101.ens.zip](https://github.com/VCVRack/Rack/files/3760837/Granmaster.Test.101.ens.zip)
[log.txt](https://github.com/VCVRack/Rack/files/3760839/log.txt)
![Overview](https://user-images.githubusercontent.com/52100257/67369900-8b8ac280-f5c5-11e9-96c5-2dcbfdf8b012.png)
![Location of System Info module](https://user-images.githubusercontent.com/52100257/67369325-88db9d80-f5c4-11e9-9612-c1c57f5ce7ec.png)

**Comment by AndrewBelt** [comment]
Thanks, we'll take a look.

**Comment by RichieHindle** [comment]
I've reproduced the problem, but I'm afraid I'm away for the next week, and I won't be able to look at it until after I get back.  Sorry for the poor timing.

**Comment by AndrewBelt** [comment]
This is the issue tracker for VCV Rack. Send bug reports and feature requests of VCV plugins to contact@vcvrack.com.
We have added this to our internal issue tracker. Comment your email address here if you would like to be informed of future updates to this issue.
