### ISSUE TITLE
Plugin: Process by block of samples

### ISSUE THREAD

**Issue by Flowstoner** [VCVRack/Rack#161]
could we have a dual system, in addition to the sample process, to have a block process, so to reduce memory consumption and increase performance in complex plugins?

**Comment by AndrewBelt** [comment]
I'm effectively doing this in many of the Audible Instruments plugins, but yes, good idea. It would be a good idea to write a Module subclass with a given block size, number of inputs/outputs to be samplerate converted, and the preferred samplerate (or "don't care", which disables samplerate conversion). You could use implement `step()` and `stepBlock()` to do stuff at the frame and block level.

**Comment by Flowstoner** [comment]
yes, and also a module delay compensation system? 
but I do not know how it might be feasible.

**Comment by AndrewBelt** [comment]
Can you explain specifically what you mean? Do you want to predict the future with noncausal DSP?

**Comment by Flowstoner** [comment]
Plugin Delay Compensation (PDC) like in DAW?
Calculate or get reported the audio delay for each module,
add delays into other serialized paths, so the final output is in sample-accurate sync?
So you can virtually shift forwards or backward... but the master out have the whole delay accumulated,
is this the the best approach?

**Comment by AndrewBelt** [comment]
There are two cases:

What if the module has both inputs and outputs? How can you implement this in a way that doesn't break causality?

What if the module only has outputs? In that case, what benefit do you get out of shifting time at all?

**Comment by AndrewBelt** [comment]
Getting back to the original topic, I now think it would be a bad idea to subclass the entire Module. Without samplerate conversion, buffering is almost trivial.

```cpp

Frame<INS> inBuffer[N];
Frame<OUTS> outBuffer[N];
int frame = 0;

void step() {
	inBuffer[frame].values[0] = inputs[WHATEVER0_INPUT].value;
	inBuffer[frame].values[1] = inputs[WHATEVER1_INPUT].value;
	...

	if (frame >= N) {
		// Process inBuffer to produce outBuffer
		process(inBuffer, outBuffer);

		// Reset frame
		frame = 0;
	}

	outputs[WHATEVER0_OUTPUT].value = outBuffer[frame].values[0];
	outputs[WHATEVER1_OUTPUT].value = outBuffer[frame].values[1];
	...
}```

**Comment by martin-lueders** [comment]
Just wondering, is block processing really compatible with a modular design? Would this not necessarily introduce a latency of the blocksize when creating feedback loops?

**Comment by AndrewBelt** [comment]
It is *compatible* with modular design, but not *in the spirit*. However, Mutable Instruments does it, with around 16-48 sample delays, so it's not a horrible idea. And yes, it makes feedback loops non-exact, but the Mutable modules are so powerful nobody cares anyway.

I would go by this rule of thumb: Analog-modeling VCV modules should evaluate sample-by-sample, and this is convenient because analog is highly nonlinear and doesn't benefit much from processing in blocks anyway. Digital-modeling (is that a phrase now?) modules should use a buffer because FIRs, IIRs, and FFTs benefit greatly from block evaluation.

**Comment by antoniotuzzi** [comment]
I think the block processing it is perfectly usable everywhere, and engine should be able to adapt to standard power of 2 sizes.
the important thing is to add a timestamp to a processed block to avoid recalculations: every module will store last created block, and reuse it if any other modules will request in the same time frame (for example if 2 VCO are connected to the same LFO doing FM:the first time is a calculation, the second request is just a memcpy like)

This is how AU works (or used to works internally )

**Comment by antoniotuzzi** [comment]
timestamp generation is responsibility of the renderer (could be the audio output, or a file writer)

**Comment by AndrewBelt** [comment]
@antoniotuzzi If you're proposing a rewrite of Rack's engine to support blocks, I don't see the point other than avoiding some cache misses and avoiding the lightweight overhead in lines https://github.com/VCVRack/Rack/blob/master/src/engine.cpp#L52-L76. This code is dwarfed by the effort it takes to generate a sample of a VCO for example.

**Comment by martin-lueders** [comment]
@AndrewBelt I agree with your statement about analog and digital modelling. In the digital world, it is probably a good idea.

Are you proposing two different processing strategies for digital and analog modelling modules? How would that possibly work? In particular if you start mixing them in one feedback loop?

**Comment by AndrewBelt** [comment]
Yes, my rule of thumb should be followed and already has been followed with the Audible Instruments plugin and others like Befaco Spring Reverb where a FIR is used.

Buffered modules with a block size of N will have an N sample delay. There's no way around that.

    ----1 sample delay----> [analog, 0 sample delay] ----1 sample delay----> [digital, 32 sample delay] ---- (continue to start)

**Comment by jackokring** [comment]
Removing a 1 sample delay is possible by polynomial and differential extrapolation at the cost of some "noise". To remove an N-sample delay is computational extremely complex and very noisy the bigger N gets. Also it is just an estimate, and does not work well for chaotic signals.

There is less cache miss with common code, suggesting a lib of routines is most effective. Also organising written cache lines to not interleave with read only lines helps some, hence struct of arrays performing better than array of struct sometimes.

Being able to see a cables delay to output might be useful, as normalising this when changing sample rate will help with consistency.

**Comment by AndrewBelt** [comment]
Closing this issue because I instead recommend the above method of buffering. https://github.com/VCVRack/Rack/issues/161#issuecomment-333462686

**Comment by Atavic** [comment]
Plugin Delay Compensation is used in a DAW for a reason: time-align *different* audio processes.

An audio process in VCVRack is a *single* one, with no meaning for any delay compensation.
