### ISSUE TITLE
Redefinition of APP macro breaks code which doesn't 'using namespace rack'

### ISSUE THREAD

**Issue by baconpaul** [VCVRack/Rack#1613]
Hi

In surge-rack I don't have a 'using namespace rack' in my code and so have code which does things like

```
rack::APP->window->loadSVG
```

or

```
rack::INFO( "here's some info" )
```

In fact I think you actually told me that was the fix when I was trying to make 0.6.2 and 1.0 both work back in the neolithic era.

But https://github.com/VCVRack/Rack/commit/dbd117ea62a1529bc43fd74c4484d1369f0e4691 this change makes APP become `rack::APP` which then gives a compile error that @SteveRussel33 reported over on the surge-rack at https://github.com/surge-synthesizer/surge-rack/issues/258#issuecomment-546738810

Wonder what the intent of that change is for people who can't `use namespace rack` but want their code to not have a big bang moment at the release of that change. Any thoughts on what to do?

Thanks!

**Comment by AndrewBelt** [comment]
Use `APP` without the `rack::` namespace and it should build against future SDKs.

**Comment by baconpaul** [comment]
Right; but it won’t build against past SDKs.

So this is a breaking change for me.

Is that on purpose?

**Comment by AndrewBelt** [comment]
Yes, this is breaking for you. You need to change your source code.

**Comment by baconpaul** [comment]
The changes to my code require a using namespace rack in header files. That’s completely gross even though a user has kindly submitted them as a PR.

Are you really sure that you have to make me do that?

I’m sure I don’t need to link you to all the places which explain why using namespace in header files is terrible.

But if you’re going to make me, I can. But really - using statements in header files are terrible. 

If you say “do it” I will. Just want to check once more.

**Comment by AndrewBelt** [comment]
You don't have to use `using` if you don't want to. You just have to switch from `rack::APP` to `APP`.

**Comment by baconpaul** [comment]
Right. So my choices are

1. Only build against master with APP and break against 1.1.5 (or build against 1.1.5 and break against master)
2. Add a using 
3. Ignore the APP and INFO macros and use their expansion explicitly

Basically?

**Comment by AndrewBelt** [comment]
Or

4. Add `using rack::appGet; using rack::logger;`

I'd probably go with 1a though.

**Comment by baconpaul** [comment]
Yeah OK cool. Thanks!

What’s the release date for this being production-able code? Will your next build of community be ahead or behind this being the production build environment for community modules? Like if I did a surge release in 2 weeks would I be in APP or rack::APP land?

Also do you have a URL-addressable name for the always-latest SDK? I need to configure our pipelines to download an SDK at build time.

Thanks!

**Comment by baconpaul** [comment]
And as always, appreciate the clarity and immediacy of your answers!

**Comment by AndrewBelt** [comment]
I really have no idea when the next production version of v1 will be. Almost all of the upcoming features are being added to v2, but I could make a release if bug fixes are needed.

**Comment by baconpaul** [comment]
OK; so them I’m a bit stuck. Should I adapt my code to master or should I not?

It seems if I want to release the code soon and I build against master (1a) then I’m in trouble in 2 weeks since you and cschol will tell me my code doesn’t work.

If I keep building against 1.1.5 (1b) I’m in good shape for a release but I get folks telling me they can’t build against head

And if I want to build against both I have a variety of code changes with using in my header files or unnatural workarounds skipping the macros, which of course I can do but you know, they are kinda gross.

You see my dilemma right?

I’m not trying to be a pest honestly! I’m just trying to figure out what SDK I should build against if I want to update my modules in November since master has a breaking change.

Thanks as always

**Comment by AndrewBelt** [comment]
I think most people build against HEAD, and others will just use the VCV Library binaries. If you need to support both for some reason, use (4).

**Comment by baconpaul** [comment]
I would have thought most people build against the stable SDK! That’s interesting that they don’t.

When you build in the community pipeline you build against head? If that’s the case then I’ll move to head.

The reason I need to support both is I want my CI pipeline to work; and I also want the community builds to work. To do that I need to know what software the community builds use - and probably to whack my CI pipelines to not use the production SDKs.

**Comment by AndrewBelt** [comment]
I can choose the SDK at will when running builds, but it defaults to HEAD. I still think 1a is the best because users can download recent dev builds of the SDK at https://vcvrack.com/downloads/

**Comment by baconpaul** [comment]
Yeah fine
So move to head
And adjust my ci pipeline to get that index and then find the name
Of the dev sdk and pull that sdk

As a feature request it would be great if there was a stable url for the latest sdk

But I can figure it out 

Thanks. Closing this.

**Comment by baconpaul** [comment]
You know I’m just going to merge the (crappy) changes which make it build against both that our helpful user submitted. I hate em but it’s too painful to keep our CI pipeline running against head.

Thanks for the quick response. But of a bummer this change is breaking me in a way that’s so irritating but I’m sure it is for good reason. Best!
