### ISSUE TITLE
Cable notes/info: add notes to a cable, hover/click for notes and other info

### ISSUE THREAD

**Issue by gabrielreygoodlatte** [VCVRack/Rack#1620]
### Summary

I often forget what part of a patch does, and need to retrace connections to understand what's going on, find the cable I'm looking for, etc. This gets harder to manage the bigger a patch is, and the more it uses multiple instances of the same module. It also gets difficult to trace cables back from a port that has a lot of cables connected to it. It would be nice to be able to have cables display some information when hovering. This could be a mix of custom notes and other info, which are useful in different ways.

Custom notes would help users keep track of what a cable does, qualitatively, in their patch. (for example, I'd add notes like "v/oct -> bass", "clock to bass sequencer", etc.

If cables are going to display info when hovered, they could also display other info that Rack has about the cable:
- Where it is connected from/to. 
- Current value
- Mini scope?
- (for poly cables) which channels are active

### Proposed design

I haven't fully thought through the design of this, but here are my ideas about how it might work so far:

- Cables now highlight when hovered directly (not just when hovering ports they are connected to)
- Right-clicking a cable brings up a small pane of information about it, with ability to edit/save a custom note
- Escape key or clickable "x" close button closes the pane

Could start by just having it display info about where the cable is connected (and perhaps its current value), with no ability to add custom notes. This would get the first layer of interaction and design happening before it has to get more complex with things like a custom notes field, mini scope, etc.

Another possible way to design this would be to have the info display automatically on hover (no click required), but have it be an option that can be turned on/off (like parameter tooltips).

Similarly, the "mini scope" could be something that always happens on hover (of a port or cable), but can be turned on/off.

Questions/obstacles:
- Do ports on modules have "names"? If not, there's not a way to display, in text form, where cables are connected to/from. Would still be great to be able to add custom notes. Even if ports are not currently named, could be useful even to just be able to see what kind of module a cable is connected to.

**Comment by AndrewBelt** [comment]
Most of these features are added in the (currently private) Rack v2 branch.
https://twitter.com/vcvrack/status/1192213643884142594
I am rejecting all other feature requests, except for "scope in tooltip", which I am leaving open.

**Comment by gabrielreygoodlatte** [comment]
I saw that! Looks great, thanks
