### ISSUE TITLE
JACK issues on Linux

### ISSUE THREAD

**Issue by tmladek** [VCVRack/Rack#1622]
# Details

Operating system: Arch Linux, fully updated
Rack version: v1.1.6
Hardware relevant to your issue: Lenovo T570
jackd version: 0.125.0 tmpdir /dev/shm protocol 25

### Summary
I can see JACK from VCV Rack fine, I can select a `system (1-2 in, 1-4 out)` device in the dropdown, but when I do so, VCV Rack doesn't appear in the `qjackctl` graph, and furthermore, `Rack` prints this:

```
RtApiJack: the Jack server is shutting down this client ... stream stopped and closed!!
```

meanwhile, I can find this in the JACK log:

```
19:02:54.790 JACK connection graph change.
subgraph starting at VCV Rack timed out (subgraph_wait_fd=9, status = 0, state = Running, pollret = 0 revents = 0x0)
**** alsa_pcm: xrun of at least 10113.836 msecs
19:02:54.825 XRUN callback (1).
19:02:54.903 JACK connection graph change.
```

I've found this error mentioned once before, in issue #868, but the issue comments implied that it is resolved already; yet I encounter it as well.

### Steps to reproduce
1. Start JACK
2. Start VCVRack
3. Select device in Audio-8
4. See above

**Comment by AndrewBelt** [comment]
Looks like an issue with RtAudio.

**Comment by tmladek** [comment]
Would that be an issue of my system (that I can fix) or of Rack?

**Comment by AndrewBelt** [comment]
No, it's an issue with the RtAudio library.

**Comment by tmladek** [comment]
Hello, any news? :) Can I anyhow help with the troubleshooting?

Due to this issue I can't use Rack at all on my laptop :(

**Comment by AndrewBelt** [comment]
JACK isn't supported by VCV but simply included in the RtAudio/RtMidi build. You can try a third party plugin [SkJack](https://vcvrack.com/plugins.html#SkJack).

**Comment by alasdairmoons** [comment]
@tmladek .. have you tried using cadence from the kxstudio repos?
I have VCV running on my linux with jack and Audio8, all works fine.
Try using the skjack too, like @AndrewBelt mentioned. 
If both do not show vcv, it is probably the jack config.
Do other software use jack without problems?

**Comment by tmladek** [comment]
Yup, as far as I can tell, SkJack works fine, thank you! This will do as a workaround for now.
(Also, didn't know about Cadence, looks very neat.)

So as I understand it, it's RtAudio in that specific build my distro (Arch) packages, that is the problem?

**Comment by alasdairmoons** [comment]
>  it's RtAudio in that specific build my distro (Arch) packages

Probably yes, I use portaudio (and Jack portaudio) on my Linux Mint, so I can not help you with the rtAudio config

**Comment by AndrewBelt** [comment]
>So as I understand it, it's RtAudio in that specific build my distro (Arch) packages, that is the problem?

No, Rack statically links its own RtAudio/RtMidi build.

**Comment by tmladek** [comment]
It seems that switching to JACK2 fixed the issue on my machine.
(SkJack also worked, if I recall.)

So I think this can be closed.
