### ISSUE TITLE
Basic Maths in Input Fields

### ISSUE THREAD

**Issue by calslate** [VCVRack/Rack#1624]
I think it could be useful to support basic mathematical operations in input fields. For example, if I wanted one VCO at `261.63Hz` and a second VCO at exactly half the frequency (for FM, for example), I could right-click the 'FREQ' knob and type `261.63/2`.

**Comment by AndrewBelt** [comment]
If anyone can give me a C++ function `float evaluate(std::string expr)`, I'll add it. You can use NaN to return an error.

**Comment by AndrewBelt** [comment]
https://github.com/codeplea/tinyexpr might be the best way to do this.

**Comment by AndrewBelt** [comment]
Added to Rack v2.
