### ISSUE TITLE
Rack outputs crackling sound

### ISSUE THREAD

**Issue by hacker-hippo** [VCVRack/Rack#1629]
### Details
Operating system: macOS Catalina
Rack version: v1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):
MacBook Air 13 in. 2019
### Summary
When given a simple Sine wave, Rack outputs a sound wave with unwanted noise and crackling. This also happens with headphones.
### Steps to reproduce
1. Patch VCO-1 SIN to AUDIO-8 to device 1
2. Set audio output to MacBook speakers.

**Comment by stoermelder** [comment]
Did you try to increase the buffer size?

**Comment by jtodom04** [comment]
Thank you, that helped, but there is still some unwanted noise. I think my CPU is too slow to handle Rack patches. Would it help to boot Windows and try it there?

**Comment by Walther** [comment]
One curious, repeatable way to get crackles in Rack:
![Screenshot 2020-01-27 at 3 12 55 (2)](https://user-images.githubusercontent.com/2943750/73144934-0676e400-40b3-11ea-8ed5-8305c72771c7.png)


- Have a simple patch playing: even just a VCO to VCF to scope and output
- Press CMD+space to open Spotlight
- Type something, as if you were opening another app or document
- Observe crackling

I'm able to repeat this consistently, with various thread numbers, with and without real-time priority checked.

_I guess_ this might point towards something in the drawing process actually blocking the audio thread - or something along the lines?

Extra curious detail: if you type fast enough that spotlight doesn't try to render any of the semi-transparent letters, you don't necessarily get a crackle. If you type a bit slower, you'll hear crackles every time the screen updates with the em dash and filename or "No Results"-text.


These crackles can happen with some other applications as well, presumably if they too are doing something graphical. This is just a very simple and repeatable way to get the crackles.

<details>

- Rack version 1.1.6
- Focusrite Scarlett 4i4 3rd gen
- macOS Catalina 10.15.2 (19C57)
- 2,6 GHz 6-Core Intel Core i7
- 16 GB 2400 MHz DDR4
- Radeon Pro 560X 4 GB
- Intel UHD Graphics 630 1536 MB

</details>

**Comment by AndrewBelt** [comment]
This is not a concrete issue, closing. See https://vcvrack.com/manual/FAQ#how-do-i-improve-performance-of-vcv-rack
