### ISSUE TITLE
Module slug is not normalized when loading params

### ISSUE THREAD

**Issue by netboy3** [VCVRack/Rack#1630]
When a .vcv patch file has a module with a slug that has space in it (such as a pre-v1 patch file), Rack will use normalizeSlug() to load the module, but the check:

https://github.com/VCVRack/Rack/blob/a419381f710684a828651a091edcd076353f7380/src/engine/Module.cpp#L102

does not have the normalized name, will fail and stop any params import from this point on. `modelSlug` probably needs to be normalized before doing this test. This should probably also be applicable to the `pluginSlug` string assignment too.

**Comment by AndrewBelt** [comment]
Fixed in 26bda06
