### ISSUE TITLE
MIDI-MAP selection of devices crashes Rack

### ISSUE THREAD

**Issue by walrusmustgo** [VCVRack/Rack#1632]
Operating system: Windows 10
Rack version: v1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): Focusrite Scarlett 6i6 1gen, Evolution UC-33, Arturia Beatstep, Arturia Keystep, Novation Launchpad

### Summary
When selecting a device from the drop-down menu, rack always crashes. Happens on Stoermelder device as well.

### Steps to reproduce
1) Launch Rack.
2) Open or start a new patch.
3) Load MIDI-MAP module.
4) Select device from the list of devices.
5) Crash.

[log.txt](https://github.com/VCVRack/Rack/files/3849411/log.txt)

**Comment by AndrewBelt** [comment]
I'm guessing this is an issue with RtMidi and your hardware. Does it crash when removing all MIDI devices?

**Comment by walrusmustgo** [comment]
Just tested it, i have disconnected and reconnected all of the devices one by one, selecting the devices as i've connected them, and now it no longer crashes. Thanks!
