### ISSUE TITLE
Double click background for full screen / windowed toggle

### ISSUE THREAD

**Issue by DominoMarama** [VCVRack/Rack#1634]
I've got muscle memory for double clicking (youtube, video players etc) to switch between windowed and full screen. Even though I know it doesn't work, I keep double clicking the rack backdrop by habit, so it'd be really helpful if support for this time saver was added.

**Comment by AndrewBelt** [comment]
I'm deciding against this. This particular "muscle memory" is less common than users who would be surprised by this behavior if they accidentally double-click the rack.

**Comment by DominoMarama** [comment]
Fair enough, though I'd have thought the chances of accidentally double clicking the background (not a module) are pretty low. For the few that did maybe the surprise is a good one?
