### ISSUE TITLE
DAW like ASIO setup configuration for VCV Rack

### ISSUE THREAD

**Issue by Eurikon** [VCVRack/Rack#1636]
Hi, 
thank you for adding support for multiple audio modules while using different audio interfaces, 
and even use of same audio interface spread over multiple instances of Audio module!

I would like to propose a feature for VCV Rack that follows the same method as can be found in most major DAW's:
Allowing us to enable/disable available ASIO channels from within VCV Rack to create a setup that is **saved with the patch**.
I have proposed this before and this was marked as something that should be done out of VCV Rack, but that is not the same/or equaling to what i propose.

Setting the ASIO configuration and routing in the hardware makes the channels available for use in any DAW.
Which could look like this for example in my MOTU hardware:

**MOTU setup**
![MOTU-driver-channels-setup](https://user-images.githubusercontent.com/40998416/69462461-55359400-0d79-11ea-825e-8216ff421974.png)

But it is the DAW where we should be available to setup which channels the DAW should access and more importantly, which channels it shouldn't access.
So that the non-accessed channels stay "free" "unoccupied" for use in other programs.

Currently Audio core loads the channels as they are presented by the driver in groups of 8,
and occupies the channels, so that when any of the channels that you would want to user in another DAW will cause either VCV or the other DAW to crash.

In the following pictures,
i hope to can show you all what it visually looks like in other DAW's that i use:

**Reason**
![Reason-Asio-config](https://user-images.githubusercontent.com/40998416/69462573-a04fa700-0d79-11ea-8c17-3a328642cd5e.png)

**Bitwig**
![Bitwig-Asio-config](https://user-images.githubusercontent.com/40998416/69462587-a776b500-0d79-11ea-8979-0d5f11be8851.png)

**Maschine**
![Maschine-Asio-config](https://user-images.githubusercontent.com/40998416/69462596-b1001d00-0d79-11ea-94ee-06ba561dac29.png)

**Ableton**
![Ableton-Asio-config](https://user-images.githubusercontent.com/40998416/69462604-b9585800-0d79-11ea-815f-e8dc0e26df7d.png)

**Comment by AndrewBelt** [comment]
I don't understand the purpose of this. It is not possible to simultaneously use multiple ASIO devices, or for multiple applications to use the same ASIO device. Am I wrong about that?

**Comment by Coirt** [comment]
The top screenshot is Reaper, if I'm not mistaken this is routing options etc... but because Rack's routing is graphical with cables there would not be much need for a screen such as this. I'm also not sure if the Applications above are disabling the use of that particular channel rather like in Rack if its port is not connected then it is not enabled essentially or rather that channel is muted!?

**Comment by stoermelder** [comment]
> for multiple applications to use the same ASIO device. (Am I wrong about this?)

Some device drivers support multiple applications using the same ASIO device the same time. I know this about RME drivers definitely because I own a one and use it this way from time to time. There is even a (unsupported) ASIO wrapper-driver from Steinberg themself but I don't know how good this works.
https://www.steinberg.net/forums/viewtopic.php?t=48

**Comment by RemiCollin** [comment]
Multi application driver is driver dependant, and just a few manufacturers supports it. RME does. I don't think MOTU does,  as far as I remember I never got it to work on my Ultralite MK3, but maybe MK4 supports it

**Comment by Eurikon** [comment]
> 
> 
> The top screenshot is Reaper, if I'm not mistaken this is routing options etc... 
@Coirt the top image is the routing matrix of the MOTU hardware, in there essentially the device driver is setup how it will present itself in the application that will use the driver, as you can see Reason reports the driver correctly with the assigned names.

I need to add to the conversation that in my title i have used the word ASIO, this might create some confusion.

What i propose in my request is more of a method of assigning channels to the Core Audio module, based upon what the driver supplies. 
ie: if the driver supplies 16 channels, there would be an option to assign: channel 1,2,6,7,8,9,12,13,15,16 - to the audio module, for whatever reason.

This is what you can see in the setup options of the other DAWS.
It allows for a very flexible setup conditions.

As to ASIO drivers being shared by multiple applications: yes this is possible, with multi-client enabled pro hardware. (MOTU/RME/etc.)
Nothing new , been around for very long.

About the WASAPI driver, not all DAW's handle the use of this driver the same.
And every daw handles the latency that will be used differently.
VCV handles the WASAPI driver correctly, but that has no way of assigning the channels seperatly, which is what this proposal about (see screenshots of other DAW's)

Probably i should have not used the word ASIO in my initial post, to further avoid debates about driver vs driver. 
And unnecessary commenting about contacting device manufacturers, which has nothing to do with the feature request.

**Comment by RemiCollin** [comment]
Yes ASIO is probably not the best choses term as it's solely windows specific. I must admit I completely misunderstood your request then. 

I'm with you on the ability of choosing I/O in Core Audio Module, instead of the fixed 8 I/O selector. More granularity would be useful. That said, I never had any issue with activating the same ports for example in Ableton and in VCV, but again it could be driver specific.

**Comment by AndrewBelt** [comment]
>What i propose in my request is more of a method of assigning channels to the Core Audio module, based upon what the driver supplies.

If this is your request, I'm rejecting it. Just use whatever VCV Audio modules you need and patch cables where they need to be.
