### ISSUE TITLE
VeeSeeVSTRack does not open in Reason 10 / 11

### ISSUE THREAD

**Issue by dukimusic** [VCVRack/Rack#1640]
Hello, 

I put vst2-bin into VST2 directory and try to open the vst plugin in Reason 10 / 11 / Cubase 10.0.50 (WIN10, Focusrite 18i20)
It did not open and directly crashed Reason.
Anybody knows why?

**Comment by SteveRussell33** [comment]
You're in the wrong place; you need to be here: https://github.com/bsp2/VeeSeeVSTRack/issues
