### ISSUE TITLE
Host crashes when loading Carla Rack

### ISSUE THREAD

**Issue by ex3lio** [VCVRack/Rack#1641]
### Details

Operating system: Manjaro
Rack version: v1.1.6

### Summary

When I try to load Carla (in order to use my windows VST under Linux), it crashes with the following stack trace :

[69.566 fatal src/main.cpp:45] Fatal signal 8. Stack trace:
7: /home/exelio/Music/Rack/Rack() [0x56d2b1]
6: /usr/lib/libc.so.6(+0x3bfb0) [0x7fbf83407fb0]
5: /usr/lib/vst/carla.vst/CarlaRack.so(+0x32e1b) [0x7fbf59820e1b]
4: /home/exelio/.Rack/plugins-v1/VCV-Host/plugin.so(_ZN9HostedVST7_MCStepEv+0x119) [0x7fbf73fbd42f]
3: /home/exelio/.Rack/plugins-v1/VCV-Host/plugin.so(_ZN9HostedVST9_MCWorkerEv+0xed) [0x7fbf73fbd6d9]
2: /usr/lib/libstdc++.so.6(+0xd0282) [0x7fbf837c5282]
1: /usr/lib/libpthread.so.0(+0x94cf) [0x7fbf843b14cf]
0: /usr/lib/libc.so.6(clone+0x43) [0x7fbf834cb2d3]

Carla opens, but VCV Rack crashes immediately...

### Steps to reproduce

To reproduce the bug, just install Carla and load "CarlaRack" in VCV Host.

**Comment by AndrewBelt** [comment]
This is the issue tracker for VCV Rack. Send bug reports and feature requests of VCV plugins to contact@vcvrack.com.
We have added this to our internal issue tracker. Comment your email address here if you would like to be informed of future updates to this issue.
