### ISSUE TITLE
Don't load module previews in Module Browser until filter is selected

### ISSUE THREAD

**Issue by midiguru** [VCVRack/Rack#1643]
With more than 1,500 modules, it takes quite a while for the browser to load all of the graphics of the module panels. It would be nice to have an option to skip loading the graphics until a specific category is selected in one of the left-hand lists -- or to skip the graphics entirely in favor of a text list.

Restoring the Favorites feature would save a lot of time. (I know there's a module that does this, but it would be nice to have it integrated into the browser.)

**Comment by AndrewBelt** [comment]
Since 0fdad2faa809d7f3c34cb67adabf0f2a81a42cdd, module previews are saved indefinitely until close (instead of a few seconds) after being generated, so opening the Module Browser the first time will generate the first "screen" of modules and will take 0 frames after that.
