### ISSUE TITLE
Duplicate multiple modules, while maintaining connections between them

### ISSUE THREAD

**Issue by Euphorbium** [VCVRack/Rack#1644]
Currently it is possible to duplicate a module while maintaining all of the custom choices made for that module. But a lot of functionality is built from multiple modules. It would be usefull to be able to duplicate the functionality that you have built, without manually having to redo the work of setting up the cables.

It would be possible to mark multiple modules and then duplicate them as a group, with all of the cables between them. Marking could be done by shift clicking on a module, and then some color transparent overlay over the module could indicate that it is selected, or some icon over the module could appear next to a module, like it is currently done with midi mapped knobs.

**Comment by Euphorbium** [comment]
#1238 is a prerequisite of this. With multiple module selection it would be possible to implement randomisation, deletion and duplication.

**Comment by stoermelder** [comment]
You can try my STRIP module which provides functionality of duplicating multiple modules including cables.

https://github.com/stoermelder/vcvrack-packone/blob/v1/docs/Strip.md

**Comment by modman2019** [comment]
Yes we need the ability to load module groupings that are already routed to add them into an existing project. things like FX mixer chains etc.  Sort of like building blocks without having to go through all the routings from scratch.

**Comment by AndrewBelt** [comment]
There is no concept of selection in Rack, so this feature request is not possible (or requires adding a concept of selection to Rack, which I have rejected).

**Comment by XtremeSounds** [comment]
the module STRIP will work to achieve the goal here thanks
