### ISSUE TITLE
Support for JACK CV ports?

### ISSUE THREAD

**Issue by mxmilkb** [VCVRack/Rack#1645]
### Summary

The JACK system has (along with the LV2 plugin format) support for sending audio rate control signals between apps (and plugins).

This port type ("CV" in JACK, "CVPort" in LV2) has started seeing support in various further software projects, so I made a [post](https://linuxmusicians.com/viewtopic.php?f=1&t=20701) recently with an overview and some links on the subject.

### Proposed design

I don't have a proposal that is that far developed. I guess you know best how this could fit in to VCV Rack and its modules.

**Comment by AndrewBelt** [comment]
Rack abstracts all audio drivers into a single cross-platform API, and ASIO, WASAPI, CoreAudio, etc don't support anything like this, so this is beyond the scope of Rack and should be implemented in a third-party plugin. Perhaps you could develop a JACK interface plugin for VCV Rack?

**Comment by mxmilkb** [comment]
I'm not a developer. Maybe the skjack-vcv author will get a new laptop or someone else will be interested.
