### ISSUE TITLE
rack::app::MidiDeviceChoice::step() should cache deviceId to avoid redundant calls to getDeviceName()

### ISSUE THREAD

**Issue by rhrhunter** [VCVRack/Rack#1646]
### Details

Operating system: macOS 10.14.6
Rack version: v1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): N/A

### Summary
When using CV-MIDI or any of the core MIDI modules, once a device ID is selected, the 
step() function in the MidiDeviceChoice class will lookup the device name of the selected device id over and over leading to high CPU usage.

### Steps to reproduce

1. Open CV-MIDI (or any core midi module)
2. Select a midi device from the drop downs.
3. Sample the process tree (via Activity Monitor on OSX) and notice the high CPU time spent in the step function.

**Comment by AndrewBelt** [comment]
The audio and MIDI APIs have been rewritten in Rack v2, and they do not have this problem, so this bug is fixed with the future version.
