### ISSUE TITLE
Thoughts on the polyphonic tag

### ISSUE THREAD

**Issue by MarcBoule** [VCVRack/Rack#1651]
### Summary

As more and more modules become polyphonic, I'm wondering if the polyphonic tag's main benefit will diminish as time goes on. Currently, I have 867 modules installed, 205 of which are polyphonic.

### Proposed design

Would it make sense to make the polyphonic tag separate, perhaps as its own line in a module's meta data in plugin.json? This would allow the module browser and new plugin library to more easily have polyphony as a separate filter option, giving much more power to this tag.

```
	{
		"slug": "Energy",
		"name": "Energy",
		"description": "Relativistic oscillator",
		"manualUrl": "https://www.pyer.be/energy.html",
		"tags": ["Oscillator", "Synth voice"],
		"polyphonic": "true"
	},
```

With this, we could then refine our searches for polyphonic VCAs, or polyphonic VCFs, for example. Thought I'd mention this before 2.0 is finalized :-)

**Comment by AndrewBelt** [comment]
I think it still belongs as a tag.

>This would allow the module browser and new plugin library to more easily have polyphony as a separate filter option

The data structure of `.modules[]` really has nothing to do with the Module Browser's presentation of the data.

**Comment by MarcBoule** [comment]
All good then. To achieve the goal stated above, the module browser would have to allow us to select the polyphonic tag simultaneously with another tag, such that we can have the module browser show only polyphonic VCAs, but that would probably require a more involved module browser interface. Thanks for the followup.
