### ISSUE TITLE
Reconfiguring a Parameter to have 0 range causes display issue on startup

### ISSUE THREAD

**Issue by almostEric** [VCVRack/Rack#1652]
I have been using the ability to dynamically set parameters' range to reflect different states. Sometimes a parameter is essentially deactivated so I have been setting the range from/to 0/0 - this works (although maybe a disable flag would be more elegant).

What I am doing actually works fine while using VCV. However, if VCV is closed while the parameter is in the 0 to 0 state, when it is reopened, the parameter is not drawn, and resetting the range does not fix it - you need to close out and restart

**Comment by AndrewBelt** [comment]
0-range parameters should be undefined behavior. Use something else to encode whatever you're doing.

**Comment by almostEric** [comment]
except that it is only 0 range *sometimes* - like I said, the ability to disable a parameter would be better. Also, as mentioned it works fine during use - having controls disappear is not a good behavior

**Comment by AndrewBelt** [comment]
Added sanity checks in Rack v2, so knobs appear in their middle position if the range is 0.

It still might be a good idea to add a `disabled` variable to `ParamQuantity`, which makes nothing happen when `setValue()` is called.
