### ISSUE TITLE
Global multiplier for user defined knob speed (touch screen)

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Rack#1655]
### Summary

It came up on the forum about touch screens taking too long to drag parameters. A simple multiplier seems to help with adjusting when Cursor Lock is disabled as mentioned [here](https://community.vcvrack.com/t/trying-to-use-vcv-on-a-cintiq-like-graphics-tablet-any-way-to-increase-the-sensitivity-of-knobs/7065/8?u=coirt). This would be user preference with a field in settings.json

### Proposed design
in Knob.hpp

```
float userSpeed = 1.f;  //unedited json value
float speed = 1.f;
```

Keep `speed` as a dev option and have `float sensitivity = userSpeed * speed;` where  unchanged, in both json and constructors it will be `sensitivity = 1.f * 1.f;`

in Knob.cpp
`delta *= sensitivity;`

If a users touch preference is is 3 and a dev's preference is 0.8, `sensitivity = 2.4f`. Most parameters remain unchanged defaulted to 1.

**Comment by AndrewBelt** [comment]
Added "knobLinearSensitivity" to settings.json. It is defined by
```
deltaValue = pixels moved * knobLinearSensitivity * parameter value range / knob angle range * (2*pi)
```
and its default is `0.001`.

**Comment by Coirt** [comment]
Is it a v2 commit?

**Comment by AndrewBelt** [comment]
Yes.
