### ISSUE TITLE
VCV rack recordings are mono

### ISSUE THREAD

**Issue by FatalError666** [VCVRack/Rack#1658]
Hi. i've been using vcv rack for a while now and i'm able to record my sounds via vcv bridge or the module called "rec" inside vcv rack. But no matter what i use the audio channels are shown as stereo recordings but when i check iZotope insight it's like mono so there is a perfect line going in the middle and it's stable. When i put a reverb or something everything changes of course but i don't want to do that. Does anybody know why or what should i do ? 
![Screen Shot 2019-12-11 at 02 43 36](https://user-images.githubusercontent.com/58754473/70579260-16993980-1bc1-11ea-803c-4b13bb146e6b.png)
<img width="151" alt="Screen Shot 2019-12-11 at 02 43 29" src="https://user-images.githubusercontent.com/58754473/70579261-16993980-1bc1-11ea-9a91-2e5c9ad8c9f6.png">

**Comment by AndrewBelt** [comment]
Looks like you double-posted this and it was solved in the other thread. https://community.vcvrack.com/t/vcv-rack-recordings-are-mono/7153/6
