### ISSUE TITLE
Updated to new code now my modules won't compile

### ISSUE THREAD

**Issue by Strum** [VCVRack/Rack#166]
Excuse the noob question, I'm probably doing something wrong.

I just updated my local copy of the code and did a clean build but now my module code won't compile

Win 7 pro 64

Do i need to rebuild the dependencies as well?

$ make
g++ -fPIC -I../../include -I../../dep/include -DVERSION=dev -MMD -O3 -march=nocona -ffast-math -g -Wall -DARCH_WIN -D_USE_MATH_DEFINES -std=c++11 -c -o build/src/MentalMults.cpp.o src/MentalMults.cpp
src/MentalMults.cpp: In member function 'virtual void MentalMults::step()':
src/MentalMults.cpp:42:43: error: cannot convert '__gnu_cxx::__alloc_traits<std::allocator<rack::Input> >::value_type {aka rack::Input}' to 'const float*' for argument '1' to 'float rack::getf(const float*, float)'
   float signal_in_1 = getf(inputs[INPUT_1]);

**Comment by AndrewBelt** [comment]
`getf(inputs[X_INPUT])` has changed to `inputs[X_INPUT].value`, etc. Look over the engine.hpp header, and/or use Fundamental as a guide.

**Comment by antoniograzioli** [comment]
basically you need to rework all:

> getf(inputs[X_INPUT])  ----->   inputs[X_INPUT].value
> 
> setf(outputs[X_OUTPUT])  ----->   outputs[X_OUTPUT].value
> 
> params[MY_PARAM] ----->params[MY_PARAM].value

as well as some minor stuff in the main .cpp and .hpp files, and possibly in the SVG loading for the backgrounds (not mandatory, I believe). 
Have a look in the fundamentals for how it is implemented.

I have done it this morning, quite a lot of Find/Replace to do ;-)

**Comment by AndrewBelt** [comment]
And one more: `getf(inputs[X_INPUT], default)` -> `inputs[X_INPUT].normalize(default)`

**Comment by antoniograzioli** [comment]
and I beleive also the 

> if(getf(inputs[MY_INPUT]))---->(if inputs[MY_INPUT].active)

**Comment by Strum** [comment]
Thanks heaps guys.

I found the change to the way inputs, control parameters and outputs are addressed and have fixed that.
My code now compiles but the plugin doesn't load when I run Rack.

"Another big change the init() callback, and I no longer recommend subclassing Plugin but instead building it in the init() callback. Definitely take a look at Fundamental.{cpp,hpp}."

Sorry but I don't really understand what that means.

How do I make my plugin run under the release version as well as the development version?

**Comment by Strum** [comment]
"getf(inputs[X_INPUT]) has changed to inputs[X_INPUT].value, etc. Look over the engine.hpp header, and/or use Fundamental as a guide."

I have been_using the fundamental and other plugin code to work from and haven't looked deeper into the underlying code much at all yet. 

A lot of it still goes over my head but I am slowly learning by playing around.

**Comment by AndrewBelt** [comment]
The `init` function signature changed from `Plugin *init()` to `void init(Plugin *plugin)` or something (from my memory). It will make sense if you copy the Fundamental plugin.

You can't make your code work for both versions. You'll have to follow along Rack's version scheme.

**Comment by Strum** [comment]
I think I see the difference in the code, instead of overloading the constructor you are initialising with the default constructor? or something like that?

Should it still work the old way?

Thanks for your help again.

**Comment by Strum** [comment]
"You can't make your code work for both versions. You'll have to follow along Rack's version scheme."

antoniograzioli  has released his plugins as a binary file that works with the release version and I was wondering how he did it.

**Comment by AndrewBelt** [comment]
Oh, I see what you mean. You can check out older versions of Rack with `git checkout v0.3.2`

**Comment by Strum** [comment]
"You can check out older versions of Rack with git checkout v0.3.2."

I see, I think.

So I change the constructor thing and it still won't load in rack though it compiles ok.

no idea what to do now.

**Comment by antoniograzioli** [comment]
want to post your code somewhere so we have a quick look?

**Comment by Strum** [comment]
Failed to read init() symbol in ./plugins/mental/plugin.dll

found the error in the rack log

**Comment by antoniograzioli** [comment]
dunno, double check fundamentals.cpp and .hpp files and make sure you used the correct "new" method

**Comment by Strum** [comment]
ok, 

haven't made a repo for it yet, wanted to work on the guis get it a bit cleaner yet before releasing it.

[Strums_mental_plugins.zip](https://github.com/VCVRack/Rack/files/1349734/Strums_mental_plugins.zip)

**Comment by antoniograzioli** [comment]
I cannot compile, there's no MakeFile in it.
Also, as we already suggested, check the double check fundamentals.cpp and .hpp, they don't look correct if you want to buid for the current source version.
Which version are you trying to build for? half code is for the current, half is for 0.32...

**Comment by Strum** [comment]
I see, I hadn't changed to main plugin header and .cpp file to the new format.

works now

thank you both so much for your help.

**Comment by AndrewBelt** [comment]
Great! I'll mark this as resolved

**Comment by Strum** [comment]
No worries.
