### ISSUE TITLE
Dark versions of module panels

### ISSUE THREAD

**Issue by modman2019** [VCVRack/Rack#1663]

**Comment by modman2019** [comment]
It would be nice to have dark versions of the native vcv rack modules.

**Comment by AndrewBelt** [comment]
@milholen has actually designed dark panels of Fundamental modules. Here's a low-res screenshot.
![2019-12-15-075308_198x88_scrot](https://user-images.githubusercontent.com/338179/70862885-001c1680-1f10-11ea-9de0-ea73932d6e91.png)
Obviously we won't change all the panels to dark just because someone suggested dark panels.

So the question instead is how one would switch the panels. I could add an option "View > Suggest dark panels" to the menu bar, which would set `settings::darkPanels` to true. But every `SvgButton.hpp`, `SvgKnob.hpp`, `SvgPanel.hpp`, `SvgPort.hpp`, `SvgScrew.hpp`, `SvgSlider.hpp`, `SvgSwitch.hpp`, and possibly others would need some way to store two SVG files for each asset. Every `*::setSvg()`-like method would need a dark version or have two arguments. Because those methods accept `Svg` objects rather than paths, this would require both versions to be loaded, which would double the time to load assets for each module upon first instantiation.

Each `Svg*` class would need a way to periodically read `settings::darkPanels` and swap out the graphic as needed.

At this point, I'm not sure it's worth the time and performance hit to accept this proposal.

**Comment by modman2019** [comment]
just a thought. probably no biggie anyway

**Comment by modman2019** [comment]
some have made their dark panels available in res folder and we can manually just replace them

**Comment by Coirt** [comment]
> @milholen has actually designed dark panels of Fundamental modules. Here's a low-res screenshot.

Probably be easier to `make` an optional version of fundamental with the dark theme.

**Comment by AndrewBelt** [comment]
@Coirt I typically focus first on what "the masses" can use (100,000's) and leave the fact that the VCV Rack platform is free software to allow what niche users (100's) want.

Also, it would still be difficult to add the necessary components to allow users to build a "dark" Fundamental plugin. It would take 2x longer to convert @milholen's dark panels to separate SVG files (which only takes 10m each but still), and it would need to bundle dark versions of each Component Library graphic.

**Comment by Coirt** [comment]
@AndrewBelt I'd be happy to help here if you need it. I can fork fundamental and submit it to the Library with the converted theme.

**Comment by AndrewBelt** [comment]
@Coirt Not a good approach. A plugin with a different slug should be a completely different plugin, not a superficial variant of a similar plugin.

**Comment by Coirt** [comment]
@AndrewBelt It's an easy alternative imo but I know what you are saying. Those who want the dark theme will only see 2 versions of Fundamental in the browser, those who don't care for it, me included won't see it as they haven't sub'd to it. 

Offer is here if you want to take me upon it!

**Comment by ptrumpet** [comment]
another option might be an svg override value  (file path) in the JSON for any module in the core.  saves added menu options etc,  low impact on development.  the override could point to any dir.  saves loading extra svgs.  If someone wants to, they can write a module to manage it all independently of the core

**Comment by milholen** [comment]
FWIW most of the design work is done. I'd like to see this option too, as long as there's an elegant way to swap the panels (no duplicating the plugin, no swapping SVG files in a directory).

Ideally I could mod-click a panel and get a menu item listing panel options. The developer would specify the name of each option (they might want a red one, not a black one, or might want to use signifiers other than color). If there is only one option this menu would not appear at all, since it serves no purpose. This also avoids the need to regenerate existing plugins with a redundant new menu. The menu would only show up for new modules that support this feature. 

There might also be a checkbox within the panel menu that makes the selection persistent, so that when the module is duplicated or  new instance is added from the module browser, users won't need to change the panel option on each instance of the module.

Also the "dark mode" components could become part of the standard VCV component library so that they don't have to be bundled separately with each plugin. That would cut down on the load time for a subset of the components. Obviously developers using custom components would still have to duplicate everything as Andrew describes above.

**Comment by AScustomWorks** [comment]
I can see a marketplace just for skins if there's official support on VCV Rack itself for this (with commission for VCV Rack of course), so maybe unlimited skin support, not only bright/dark?
The question remains, how to make the option available for each and every plugin without developers intervention?(if an alternate skin is available for said plugin).

**Comment by antoniotuzzi** [comment]
my 2 €/100

I've implemented in my modules the transparent switch;
everyone can design a new set (or just a subset of modules) for NYSTHI modules and put it in a folder called "res_users/myfantasticset/"

you can switch between skins using the contextual menu of one of my modules (nysthiometer)

the choice is preserved between launches

of course I override the method to reach the resources to deal with 3 cases:

1) I want to use the original RES sources
2) I want to use the custom RES sources
3)  I want to use the custom RES sources but they don't exist and I fall back to the original RES sources

**Comment by AndrewBelt** [comment]
For dark/light panels, the only proposal I'd likely accept is the one described here https://github.com/VCVRack/Rack/issues/1663#issuecomment-565807769. If >2 themes or per-plugin switchable themes are desired, that proposal would be insufficient, so a different proposal would be needed.

**Comment by modman2019** [comment]
im sorry if my question turned it into this thing.

**Comment by milholen** [comment]
It's a common feature request and something that @AndrewBelt and I have talked about, but as you can see, every feature request adds a certain degree of overhead and complexity.

**Comment by AndrewBelt** [comment]
[Poll: Dark mode for panels and components?](https://community.vcvrack.com/t/poll-dark-mode-for-panels-and-components/7256)

**Comment by baconpaul** [comment]
I added multiple swappable modes to surge a while ago and people seemed super happy. I rolled my own RMB for picking a theme but I could definitely have 2 of my themes be “light” and “dark” globals.

Implementation: would you have some new API point in the ModuleWidget (or Module? I suppose ModuleWidget makes more sense) like “void setDisplayColorMode( enum )” where that enum is SYSTEM_DARK_MODE or SYSTEM_LIGHT_MODE and we would just respond to that? Easy as pie for me to adapt to something like that if so and I would do so as soon as the API was there.

**Comment by AndrewBelt** [comment]
@baconpaul No, it will be a global function `bool settings::isDarkMode()` or something.

**Comment by RemiCollin** [comment]
I like the idea of VCV providing an unified API for switching panel themes, but I think it would be preferable to let the user have the option to do it on a module instance basis. IE; When I build a patch I often use these feature on plugins that supports it to achieve a kind of balance, or even use this as a "color code" telling which part/functionnality of a patch a module is related. Having this feature only as a global option feels a bit off to me.

**Comment by spectromas** [comment]
That would be a great addition. I would just hope that it wouldn’t stop you from manually changing skins on modules that support it after the global mode is selected.

That Fundamental mock-up looks beautiful.

**Comment by AndrewBelt** [comment]
@RemiCollin I think I'll go ahead and reject the proposal for "Adding multiple color themes and/or per-module switchable themes." Multiple color themes wouldn't make sense on a global level, and on a per-plugin level, the Rack API doesn't need to be involved in any way.

**Comment by baconpaul** [comment]
> @baconpaul No, it will be a global function `bool settings::isDarkMode()` or something that all panel and component widgets would check in their `draw()` method.

Ok cool and you will invalidate my widget when it toggles and it would be my responsibility would force invalidate all my framebuffers and reload assets and stuff when there’s a state change? That’s fine but it means I’ll add a bool to track the state so I can write the if for when it changes, which is why I was thinking an onSystemColorModeChanged type approach may be useful for module devs

I can work either way though of course! Easy with either.

**Comment by AndrewBelt** [comment]
@spectromas Plugin developers have invented many ways to support color themes for their panels and components. The most common is to offer a context menu option to set a global variable, which is checked by `ModuleWidget`s to switch panel/component graphics when changed. Depending on the details of their implementation, it will require none to little code changes to coexist with Dark mode.

**Comment by AndrewBelt** [comment]
@baconpaul A possible implementation might look like
```cpp
void SvgKnob::step() override {
	// Set Dark mode
	std::shared_ptr<Svg> svg = isDarkMode() ? this->darkSvg : this->svg;
	if (sw->svg != svg) {
		sw->svg = svg;
		dirty = true;
	}
}
```

**Comment by baconpaul** [comment]
Oh yeah I know - I do something similar now in surge when I change skins. Just my skin change is an event (triggered by a button) which changes a global asset catalog not an if I poll in all my draws. I wonder how many other home rolled skin mechanisms are event based too? It’s pretty natural way to respond to a menu. 

But the two are totally equivalent (or can be made so trivially) so I’m good with the global function too. I think this would be a useful feature independent of the api and I would happily support it.

**Comment by RemiCollin** [comment]
@AndrewBelt : I agree supporting two themes is largely enough.

I just have doubt on this global approach on the widget side. Let's say I want to provide a way for the user to switch light/dark mode from the context menu of a module, my only option then if I want to use the component library would be either to subclass every component it uses from the library to support both local & global UI mode. In that case having the setting in the `draw()` method arguments would probably be a better choice, as it would give the option of overriding in from the `ModuleWIdget`

**Comment by AndrewBelt** [comment]
@RemiCollin Yeah, that's an issue with https://github.com/VCVRack/Rack/issues/1663#issuecomment-567140238. If the user enables Dark mode, all Component Library widgets will indeed change from "default" to "dark". If your *completely separate* theme system relies on a "default" Component Library widget, it will appear incorrectly.

To solve this problem, might I suggest implementing only a "hue" selector and rely on Rack's "default/dark" choice as an orthogonal choice to the user's hue choice? For example, have "light green", "light blue", etc. and "dark green", "dark blue", etc. when Dark mode is enabled.

**Comment by ContemporaryInsanity** [comment]
![image](https://user-images.githubusercontent.com/12547379/71113050-af811380-21c4-11ea-8c5c-2e08f238a34d.png)

**Comment by AndrewBelt** [comment]
@ContemporaryInsanity Can you give some context to your comment? What in the world are you addressing?

**Comment by ContemporaryInsanity** [comment]
The extreme contrast between knobs & background on the fundamental dark mockup.  I could not use that as is.

**Comment by JerrySievert** [comment]
I disagree that supporting only 2 themes is enough, and for those cases where >2 panels is desired the note here https://github.com/VCVRack/Rack/issues/1663#issuecomment-565843328 seems to point to the need for an alternate proposal.

my alternate proposal is to standardize how modules themselves can have their themes changed, and not use a binary "light" and "dark" choice.

**Comment by ContemporaryInsanity** [comment]
Something I'm playing with atm:


![image](https://user-images.githubusercontent.com/12547379/71113581-cd9b4380-21c5-11ea-8764-58c26925b686.png)

As I have vision issues and appreciate others problems re colour blindness I wanted to provide for all tastes / requirements.

**Comment by AndrewBelt** [comment]
@ContemporaryInsanity I'll let @milholen address graphics feature requests.

**Comment by RemiCollin** [comment]
@AndrewBelt : Ok that's what I was concerned with.. Just trying to find a way to make "per module dark/light switching" works with the proposed implementation. If it doesn't work I can still switch to custom widgets then, just please provide an ETA (v2 ?) not to have our panels "look weird" after a vcv update.

> To solve this problem, might I suggest implementing only a "hue" selector and rely on Rack's "default/dark" choice as an orthogonal choice to the user's hue choice? For example, have "light green", "light blue", etc. and "dark green", "dark blue", etc. when Dark mode is enabled.

I'm not sure I understand this.

**Comment by spectromas** [comment]
@ContemporaryInsanity that is a very pertinent point. Any visual changes should be accessible-friendly to as many people as possible. I would imagine there are at least a few visually impaired users and this should definitely be factored in.

**Comment by milholen** [comment]
> my alternate proposal is to standardize how modules themselves can have their themes changed, and not use a binary "light" and "dark" choice.

IMO there is a need for a single app-level toggle between light and dark modes (which is consistent with OS-level support for this feature on Mac, Windows, and many Linux distros).

Consider that you have a patch with 50-100 modules and you want to change to "dark mode" after sunset. Without an app-level toggle, users would have to manually change every module in the patch.

Implementing a global option does not preclude individual developers from having their own secondary methods of controlling the module appearance. Developers can then decide how they want their modules to respond to the global setting (including not responding at all) and they can also provide local overrides for more than two color options if desired.

**Comment by AndrewBelt** [comment]
@JerrySievert
Sorry, I have already rejected this feature request above. https://github.com/VCVRack/Rack/issues/1663#issuecomment-567134272
If anyone is interested in my reasons, I can perhaps set up a time to explain over Discord voice chat, but I've already surpassed my time window on this issue so I'm unable to elaborate in text at this time.

**Comment by JerrySievert** [comment]
@AndrewBelt if you end up going with a binary only ui choice, it's going to be a hard-baked-in api decision that will be hard to back out of later when the realization that it was a bad choice is discovered.

**Comment by AndrewBelt** [comment]
@RemiCollin 
>I'm not sure I understand this.

What I mean is that if you wish to have more than two color schemes (other than light and dark), you may offer the choice of several hues (e.g red, green, blue, etc) in a context menu and allow their brightness to be controlled by the user's global Dark mode choice. In other words, `color = hsv(custom menu choice, 1, isDarkMode() ? 0.2 : 0.8)`.

**Comment by JerrySievert** [comment]
> Implementing a global option does not preclude individual developers from having their own secondary methods of controlling the module appearance. Developers can then decide how they want their modules to respond to the global setting (including not responding at all) and they can also provide local overrides for more than two color options if desired.

but it does cause for a very confusing user interface for those developers not supporting a binary "light/dark" choice.  as I've commented before (and had deleted already by @AndrewBelt), the binary choice is a bad user experience for something that already has multiple choices.  this isn't an operating system, it's a virtual eurorack.

**Comment by AndrewBelt** [comment]
I'll make a final decision 24 hours after the poll was posted, but we can already estimate the following facts.

- Users want this feature, based on overwhelming votes and Facebook/Twitter post activity.
- Surprisingly to me, developers are willing to implement this feature. ~10 of the ~13 who voted say they would add Dark graphics, which is a high enough proportion for me to expect the feature to be adopted.
- The proposal is mostly technically sound.
	- Dark mode in `setSvg()` and `step()` will have to be implemented for each `Svg*` class.
	- I'll have to process all Component Library graphics to obtain SVG files.
	- A setting, menu item, and API function are trivial.
	- Core, Fundamental, and all VCV modules will need to add dark panels.
	- That's it, right? I can't think of any other tasks or issues with the technical proposal.

**Comment by baconpaul** [comment]
The only other technical thing I see is giving developers access to the api early enough to adapt in the plugin manager which is more technical administrative. I could turn this around given a weeks notice maybe 2 and figure most of the rest of the devs feel the same. 

And the one thing that occurs to me: would there ever be any use of supports dark mode as a plugin.json property?  I can’t think of one but seems like it’s the sort of thing you’d wish you had done if you do think of one :)

**Comment by AndrewBelt** [comment]
@baconpaul If accepted it will be included in the v2 branch, which will probably be available Jan 2020, several weeks before Rack v2 is released.

**Comment by mdemanett** [comment]
As a developer, I've been more or less waiting around for blessed Rack support for dark mode to implement it in my plugin.  

In the spirit of open source, another person maintains dark versions of my panels, which users can install by unpacking a zip to overwrite the default panels in the plugin directory, but it's a hassle to maintain for everyone involved.

I've resisted the current state of the art of having a dark mode toggle (or skin select) on each module, not least for the reasons @milholen [lays out above](https://github.com/VCVRack/Rack/issues/1663#issuecomment-567165758), and also it just seems like a goofy thing to have to go into the context menu every time you add a module to a patch, though people do, and frequently.

So big thumbs up on the idea, would like to see it.

That said, it seems like an issue that non-compliant, or not immediately compliant, plugins might/will look weird when the Rack-provided widgets switch to dark mode.  So maybe it'd be cool if plugins have to opt in to dark mode support, probably by a flag in plugin.json (which actually @baconpaul just suggested above).  This would mean Rack would render light or dark widgets on a per-plugin basis, and probably also that isDarkMode() would return a different answer depending on which plugin is asking.  Which is feature creep on the implementation, for sure.

A related thing that might come up is users clamoring for a way to override dark mode for certain plugins.  Which would get into per-plugin, global-to-the-plugin settings.  Which would incidentally solve problems for those plugins with multiple skins.  Plugin-level settings could be as easy as allowing dataToJson(), dataFromJson() and addToMenu() callbacks to be defined on the plugin.  (And, harder, find a place to display these settings menus in Rack's UI.)

**Comment by AndrewBelt** [comment]
@mdemanett 
I can't think of a clean way to implement your **override Dark mode by plugin developer** request.

I don't see the value in allowing users to set Dark mode per-plugin.

**Comment by AndrewBelt** [comment]
This was a good idea, but I think I'm going to reject the Dark mode proposal. There are many advantages/disadvantages of Dark mode, but for the amount of work it takes to create two SVG graphics for each component, it's not worth the near-zero actual benefit. I can't imagine a scenario where it would increase sales of Rack plugins, but I *can* imagine a scenario where a user would think a commercial plugin is no longer polished because it doesn't support Dark mode.

**Comment by schuster-rainer** [comment]
Would you mind If I maintain a dark-mode branch? So users would have to choose on startup which one to use or just download a different binary. This way you would not have to worry about performance or being polished. I am definitely going to maintain my own branch of rack and fundamentals. It just the way I work... All my dev environment and OS is setup as dark mode. Here is a preview of a first draft. My dark theme is less high contrast.

I would also volunteer for creating dark themes for commercial plugins

Is it okay regarding the license of the graphics for the fundamentals to have a public branch with derived work, because of the license. Otherwise I'm going to close down my branch an make it protected @AndrewBelt

**Comment by AndrewBelt** [comment]
The licenses of Core (https://github.com/VCVRack/Rack/blob/v1/LICENSE.md) and Fundamental (https://github.com/VCVRack/Fundamental/blob/v1/LICENSE.md) make this clear as day. The *Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)* license does not allow derivative works.

**Comment by schuster-rainer** [comment]
I deleted the fork. Will create a new one excluding all the graphics changes and only apply the patches for the code changes. Sorry for the inconvenience
