### ISSUE TITLE
MIDI-CV: Pitch Bend response is slewed

### ISSUE THREAD

**Issue by anlexmatos** [VCVRack/Rack#1670]
### Details

Operating system: Windows 7
Rack version: v1.1.6
Hardware relevant to your issue: Network MIDI connection via rtpMIDI, using the iOS app GeoShred Control on an iPad Pro (2018) as a MIDI controller

### Summary
Using GeoShred Control with VCV Rack [as described here](https://community.vcvrack.com/t/guide-using-geoshred-control-ios-app-as-a-mpe-controller-for-vcv-rack/7217/4), when two notes are being held, the third note and any additional notes will usually respond as if pitch bend is being released from a previously-held state. It feels something like a "ghost portamento" sliding the note from some mysterious, non-existent prior note. I have attached an audio file demonstrating the behavior as well as the patch file used to generate this example recording.

[MIDI-CV MPE Issue.zip](https://github.com/VCVRack/Rack/files/3993887/MIDI-CV.MPE.Issue.zip)

**Comment by anlexmatos** [comment]
Upon testing GeoShred Control with the Surge Synthesizer VST, I have found that the behavior exists there as well. Therefore, this seems to be a problem with GeoShred Control. However, I have noted a difference in the behavior of VCV Rack and Surge VST:

VCV Rack appears to slew incoming changes to pitch bend. Whereas the bending problem exhibits in Surge VST as an extremely rapid blip, in VCV Rack it is a more dramatically audible portamento-like slide.

I've submitted a bug report to moForte (GeoShred devs), and am re-titling this Issue to instead focus on VCV Rack's apparent slow response time in regards to pitch bend data.

**Comment by Ahornberg** [comment]
Yes, I encountered this phenomen too. I'm actually adding a parameter to the MIDI-CV module to give the ability to switch between the actual behaviour and the "correct" behaviour (no pitch-glitch). After completing my tests with the VST-Bridge in some DAWs, I'm going to put my solution on a branch here.

**Comment by anlexmatos** [comment]
Fixed in 2.0, see here:
https://community.vcvrack.com/t/rack-development-blog/5864/56
