### ISSUE TITLE
Allow Engine Sample Rates Below 44.1kHz

### ISSUE THREAD

**Issue by Miserlou** [VCVRack/Rack#1671]
This might be a little bit tricky since 44.1 is considered a "base" in the code and everything else is oversampling, but I'd love it if we could choose lower engine sample rates (ex., 11.025 kHz and 22.05 kHz) so that I can get a lot more oomph out of my "live"/realtime patching and avoid nasty crackling, and then I can switch back to 44.1 for my renders.

If you accept as a concept - and it's not too crazy to implement - I'd be happy to submit a PR.

**Comment by AndrewBelt** [comment]
1/2x and 1/4x sample rates (relative to 44.1 and 48 kHz) were added to Rack v2 as officially supported sample rates.
