### ISSUE TITLE
No sound on Ubuntu : Jack RT Scheduling

### ISSUE THREAD

**Issue by johhnry** [VCVRack/Rack#1676]
### Details

Operating system: Pop!_OS 19.10 (very close to Ubuntu)
Rack version: v1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):
Audio device: Intel Corporation Sunrise Point-LP HD Audio

### Summary
Hi everyone,

I am on a Linux laptop and I just downloaded the latest version of VCVRack.
However no sound is coming out of my computer when I press a MIDI key.

### Steps to reproduce

I first launch the jack server : `jack_control start`
Then I launch Rack : `./Rack`

This is the output in the console : 

```
Cannot lock down 82280346 byte memory area (Cannot allocate memory)
Cannot use real-time scheduling (RR/5)(1: Operation not permitted)
JackClient::AcquireSelfRealTime error
Cannot use real-time scheduling (RR/5)(1: Operation not permitted)
JackClient::AcquireSelfRealTime error
```

Then when I press a key it should play a sound (with the default startup setup) whether I choose ALSA or JACK in the AUDIO-8 module.

Where is the issue?

Thanks

**Comment by johhnry** [comment]
Finally I managed to fix it with those two links :

- to enable real time scheduling
https://jackaudio.org/faq/linux_rt_config.html

- to connect vcv rack in qjackctl
https://forums.linuxmint.com/viewtopic.php?t=303315

Is it the right way to do it? Every time I want to use VCV Rack I have to use qjackctl to start the server and connect the output ?

**Comment by mattcollier** [comment]
@johhnry I can confirm similar behavior on Ubuntu Studio 18.04.  Having to start the JACK server is expected.  However, I expect that VCV should be making the connection to the output device when that selection is made in the VCV UI.  Instead we must currently make the connection manually in the JACK UI.

VCV *is* able to make MIDI connections via JACK successfully.

**Comment by AndrewBelt** [comment]
JACK is not supported in Rack, but it is compiled into RtAudio/RtMidi as-is.
