### ISSUE TITLE
Plugin parameter enhanced tactile control (keyboard /midi hover-over)

### ISSUE THREAD

**Issue by tokkeherfst** [VCVRack/Rack#1677]
Hello,

I would like to be able to to control module knobs/parameters in a more tactile way than mouse-right-click-drag. I really love the midi-cc control mappings but they require setting up mappings for each and every knob.

I do have a Shuttle Pro controller which be mapped to specific keypresses so a keypress combination (up/down arrow eg.) for mouse-right-click-drag would do it. That would allow to control whatever parameter the mouse is hovering over at the moment.

Another feature/solution that comes to mind is to be able to map a specific midi CC to whatever button the mouse is hovering over at the moment.

I think being able to turn a knob or jog physically to modify any module value really would enhance the tactile experience of vcv rack.

Thanks!

Tom.

**Comment by stoermelder** [comment]
Hi Tom, nice suggestion! I took it and created a new module called SAIL an hour ago which allows you to change the parameter currently hovered by mouse with CV. If you like you can try it out in the "nightly build" of my PackOne plugin available on my GitHub repository. Feel free to open an issue if you want to discuss additional features!

**Comment by AndrewBelt** [comment]
This idea doesn't really fit into MIDI-Map's scope, and I'm not interested in making a separate module for it, so a third party plugin like @stoermelder's would be my recommendation.

**Comment by tokkeherfst** [comment]
Wow Ben, SAIL is awesome! Just mapped modwheel CC output from one of my beatstep pro knobs and it works absolutely great ;-)
The only downside I can see if the knob is already in a low CC value 'positition' going lower on a control that is set to a higher value doesn't work, but nevertheless they way you've implemented this works quite well!!!

You might just have saved me from a hardware eurorack addiction, because having a hardware knob to wiggle was my main reason for preferring hardware ;-)

Now I am just wondering how I might go about mapping a set of computer keyboard keys to a changable CV value so I can use my shuttlePRO as well for this. Or would you be able to add this into SAIL easily?

Thanks again!

Tom.

**Comment by AndrewBelt** [comment]
Please move discussion of stoermelder PackOne to that project's issue tracker.
