### ISSUE TITLE
"sample & hold velocity" mode for MIDI-GATE modul

### ISSUE THREAD

**Issue by MaZe6K** [VCVRack/Rack#1678]
### Summary

A built in "sample & hold mode" for the MIDI-GATE module in velocity mode could be useful for making use of the velocity part of incoming triggers and gates more convenient.
As it is now in most common use cases an additional sample and hold module is needed for every output to make use of the velocity value.

### Proposed design

A second velocity mode option in the right-click menu of the MIDI-GATE module.
If possible this mode should just output the received velocity as a constant value until a new value is received without delay, so it is completely in sync with a received trigger from another MIDI-GATE module in regular mode.

**Comment by AndrewBelt** [comment]
The velocity (and therefore the voltage) of each output should not change until the note is triggered again.

Open a bug report if this is not the case.

**Comment by MaZe6K** [comment]
What I mean is it should ignore note off events, which it doesn't.
I created a new issue as a bug report.
