### ISSUE TITLE
Velocity falls back to 0 on note off in velocity mode of MIDI-GATE

### ISSUE THREAD

**Issue by MaZe6K** [VCVRack/Rack#1681]
### Details

Operating system: Windows 10
Rack version: v1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): Beatstep Pro (MIDI Gate Sequencer)

### Summary

When in velocity mode, the outputs of the MIDI-GATE module always fall back to 0 on note off, but they should be held until the next note on event and then continue with the new velocity value.
Velocity mode should ignore note off events and their velocity values altogether.

### Steps to reproduce

Connect a Beatstep Pro and send some triggers to a MIDI-GATE module in velocity mode.
The Beatstep Pro sends a velocity value of 64 on note-off events, but the value of the connected output falls back to 0 (which of course is better than if it would snap to 64 at that point).

**Comment by AndrewBelt** [comment]
This is expected behavior. The purpose of MIDI-Gate is to produce a gate when a note is active, with a height of 10V, or `10V / (velocity / 127)` when velocity mode is enabled.

**Comment by MaZe6K** [comment]
Would you consider it as a new feature? A velocity mode which ignores note-off events?

**Comment by AndrewBelt** [comment]
I'm not sure how that would be useful. You wouldn't know when a trigger happens if the note has been played before.

**Comment by MaZe6K** [comment]
I would like to use constant velocity values with the triggers coming from a second MIDI-GATE module in regular mode.
It makes sense to me to use it this way anyway, since many modules require a certain threshold to trigger and thus don't react to the triggers with very low velocity values.
So it would be nice to have constant velocity values until the next note on without having to add a s&h to the outputs.
