### ISSUE TITLE
Rack 1.6.2 crashes often on open of previously saved patches, eventually loads

### ISSUE THREAD

**Issue by fractalgee** [VCVRack/Rack#1682]
Operating system: Windows 10 Pro
Rack version: 1.6.2
no specific hardware other than my Presonus Audio interface. Win 10, Rack and Audio modules are all using 48KHz sampling rate as the Presonus supports that. It is also my headphone out, as well as speaker out.

### Summary
Quite often on trying to reopen a patch (not a single one, happens on quite a few on and off, no rhyme or reason found yet.... if retrying to open it it will likely eventually load after 2 or 3 attempts.

### Steps to reproduce
No sure repro but I am attaching one that bailed out twice this morning before loading. Had this happen yesterday a few times on a couple other patches. Log has been attached, last was a successful start and quit of Rack

The patters is always:
 it loads all the SVGs it needs to draw the modules, then it starts the Rack engine, which reports that it started, then a few more svgs load (varying) and then log stops and Rack is gone.

Patch: 
[CrashyPatch.zip](https://github.com/VCVRack/Rack/files/4029780/CrashyPatch.zip)
[log.txt](https://github.com/VCVRack/Rack/files/4029791/log.txt)

**Comment by AndrewBelt** [comment]
According to the log, Rack didn't crash but quit cleanly by user request (or something calling `Window::close()`.) Are you sure this is the log file immediately Rack has crashed?

**Comment by fractalgee** [comment]
as I said, the log is from last clean start and quit. It did crash twice,
will attach one with a crash as soon as it happens again....

**Comment by fractalgee** [comment]
64BG DDR4 RAM,
RX590 8GB
Ryzen 3900X 12 cores/24 thread.

Rack is configured with 2 threads

**Comment by AndrewBelt** [comment]
If you can reproduce this without Southpole and Klirrfactory, I can debug when Rack quits, but I don't have those plugins.

**Comment by fractalgee** [comment]
Just found in Event Viewer that the faulting module is Southpole module.
Had forgotten about Event Log possibly having something useful ever ;)  If
I can repro without I will amend this, else I will close it, sorry for any
bother if not your issue.

**Comment by Petervos2018** [comment]
> the faulting module is Southpole module

Annuli or piste ? My guess is Annuli

**Comment by fractalgee** [comment]
Annuli I guess, I just found Steve Russel's beta build with a few fixes, and now seems to not crash on open, so closing this one
