### ISSUE TITLE
System wide plugins and config on Linux?

### ISSUE THREAD

**Issue by flying-sheep** [VCVRack/Rack#1684]
I see the code `pluginsPath = userDir + "/plugins-v" + app::ABI_VERSION;` in assets.cpp, which seems to imply that there’s only one location Rack loads plugins from.

On *NIXoids, people expect three locations to work for data:

1. The system dir with the default being: `/usr/share/<appname>` (this one is managed by the package manager)
2. The local system dir with the default being: `/usr/local/share/<appname>` (this one is managed manually by the admin)
3. The user dir with the default being: `$HOME/.local/share/<appname>` (this one is managed by the user)

The best way to support this would be to load all plugins similarly to this:

```cpp
auto sys_data_dirs = std::getenv("XDG_DATA_DIRS");
if (sys_data_dirs == nullptr) sys_data_dirs = "/usr/local/share/:/usr/share/";
auto user_data_dir = std::getenv("XDG_DATA_HOME");
if (user_data_dir == nullptr) user_data_dir = get_homedir() + "/.local/share/";

auto data_dirs = split_into_vector(sys_data_dirs, ":") << user_data_dir;
```

The same applies to configuration except that this is supposed to be in `$XDG_CONFIG_DIRS` and `$XDG_CONFIG_HOME`.

All this is documented here: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by AndrewBelt** [comment]
If folder locations change, it would confuse existing users.

**Comment by flying-sheep** [comment]
That’s why people usually introduce such things while maintaining backwards compatibility.
