### ISSUE TITLE
Make Module Browser and tooltips zoomable for high resolution screens

### ISSUE THREAD

**Issue by fractalgee** [VCVRack/Rack#1685]
### Summary
Given more and more high resolution screens are in use, please make module browser zoomable or make it adapt to high res display by itself. It is near impossible to make out anything module wise in the browser on a 4K screen. Also tooltips are tiny and very low contrast and don't adapt to normal screen zoom (125% for the apps so menus are usable etc.)

### Proposed design

It could either be:
- zoomable like the main Rack space
- settable via Settings file
- settable via View menu

Tooltips should also heed that zoom, or be settable as right clicking any parameter gives me a tiny little box, and with light grey on dark grey it is impossible to use, other than if I know what to set it to, but reading them is futile without magnifying glass.... Somewhat older eyes also don't help, and glasses don't improve on the light grey on dark grey which should be white on dark grey pretty please, especially when highlighted it is almost obliterated as is

**Comment by AndrewBelt** [comment]
You're saying that high resolution screens imply that things on the screen appear smaller. This should not be the case. A UI element in Rack should be *proportional* to your OS's UI elements (such as the Windows taskbar), so text in any other program should be just as easy to read as text in Rack.
If this is not the case, open a bug report.

**Comment by fractalgee** [comment]
OK, bug coming up.....

**Comment by EbE404** [comment]
For me, this actually has value beyond dealing with screen resolutions. For example, I frequently open the browser to look at a category of modules and may be looking for a specific kind of input or feature (a CV mod for a specific parameter, a clock input, etc.). With smaller modules or highly populated modules, those can be difficult to make out. Thus, having a zoomable browser would be very helpful for those use cases to be able to see more detail on specific modules without having to add them to the project, zoom in, see that it doesn't have what I need, delete it, then do it over again with something else.

**Comment by AndrewBelt** [comment]
Rack's menu bar (for example) is the same size as its window bar in your example. Therefore, if you have trouble seeing Rack's text, you have trouble seeing your OS's text, so you should adjust the OS scaling.
See https://www.eizoglobal.com/support/compatibility/dpi_scaling_settings_windows/ for setting your OS's scaling. Let me know if this doesn't work.

**Comment by EbE404** [comment]
Agreed. For my comment, I'm speaking specifically about the images of the modules, not the text.

**Comment by AndrewBelt** [comment]
Also, this is a duplicate of https://github.com/VCVRack/Rack/issues/1395.

**Comment by fractalgee** [comment]
Fair enough, added my vote there
