### ISSUE TITLE
Saving Presets with a German Umlaut in the name is saved with a wrong name

### ISSUE THREAD

**Issue by asedev** [VCVRack/Rack#1686]
### Details

Operating system: Windows 10
Rack version: v1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): none

### Summary
When saving a preset using the Rack modules standard preset manager the German Umlaut in the entered filename is saved incorrectly.

Example:
ÄäÖöÜüß.vcvm  <- this is entered in the file save dialog
Ã„Ã¤Ã–Ã¶ÃœÃ¼ÃŸ.vcvm <- this is the result in the file system

Analysis:
It looks like the entered name is somewhere encoded as UTF8 and at some other places encoded as ASCII.

Impact analysis:
A. Good thing: the saved file can be opened properly.
B. Most likely this is also the case for other languages special characters.

### Steps to reproduce
1. Use the Rack module standard menu "Preset|Save as.."
2. Enter the name "Öö.vcvm"
3. Save the preset and check the name in the file system.

**Comment by AndrewBelt** [comment]
Fixed in Rack v2 by redirecting `fopen` etc to wrapper functions which convert from UTF-8 strings to UTF-16 wide strings and calls the wide versions of those functions.

```hpp
#if defined ARCH_WIN
#define fopen fopen_utf8
#define remove remove_utf8
#define rename rename_utf8

extern "C" {
FILE* fopen_utf8(const char* filename, const char* mode);
int remove_utf8(const char* path);
int rename_utf8(const char* oldname, const char* newname);
}

namespace std {
	using ::fopen_utf8;
	using ::remove_utf8;
	using ::rename_utf8;
}
#endif
```
