### ISSUE TITLE
Crash after installation Rack 1.1.6

### ISSUE THREAD

**Issue by ekine001** [VCVRack/Rack#1689]
### Details: Crash after first installation

Operating system:
Rack version: v1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):
Windows 7 64bits sp1
I5 M430
ATI HD5650

### Steps to reproduce : 
Install rack 1.1.6 and run

[log.txt](https://github.com/VCVRack/Rack/files/4067245/log.txt)

**Comment by AndrewBelt** [comment]
The crash is occuring the first time GLFW (the windowing library used by Rack) draws to the window. Does upgrading your graphics driver solve this?

**Comment by ekine001** [comment]
I've update my graphic drivers like you told me, and now all working fine.
Thx you
