### ISSUE TITLE
Splash Screen implementation

### ISSUE THREAD

**Issue by walrusmustgo** [VCVRack/Rack#1690]
**Summary**

This is a really arbitrary feature request, but it would be nice to have a splash screen while VCV is loading, like Ableton Live, Photoshop, After Effects, etc. 

**Proposed design**

An image with texts displaying the current version number, account details and copyright details.

- After Effects
![image](https://user-images.githubusercontent.com/57779757/72520793-7e930d80-385a-11ea-93b9-77a0e3fb4ef5.png)

- Blender
![image](https://user-images.githubusercontent.com/57779757/72520823-95396480-385a-11ea-80a5-659d330b8e0a.png)

- Ableton Live
![image](https://user-images.githubusercontent.com/57779757/72520861-a4b8ad80-385a-11ea-93d4-488b30d1e475.png)

**Comment by AndrewBelt** [comment]
I don't see a need. Rack boots very fast.

**Comment by MarcBoule** [comment]
It might have use for when we update plugins: when Rack launches again, it can sometimes have lots to unzip, and may appear unresponsive to the untrained eye. I always use the dev version though, which I launch in the command line, so perhaps my point is not relevant, but just a thought.
