### ISSUE TITLE
VCV Rack crash with loopMIDI (Orca bridge) + 16n faderbank (MIDI - CC)

### ISSUE THREAD

**Issue by sisyphusssss** [VCVRack/Rack#1691]
With loopMIDI running (Virtual MIDI host to bridge Orca), the introduction of 16n (MIDI hardware controller) crashes VCV Rack immediately (Win 10). 

The 16n faderbank operates fine on VCV Rack (via MIDI - CC) without loopMIDI (and vice versa).

**Comment by AndrewBelt** [comment]
Closing since the issue template was not filled out.
