### ISSUE TITLE
RTRG mode for MIDI-GATE

### ISSUE THREAD

**Issue by ROGAVKA** [VCVRack/Rack#1692]
Sorry if it's a wrong place to post feature requests for Core modules.

In the modular world (including VCV) when controlling stuff with external sequencer, we have a persistent problem of merging MIDI gates when two notes are adjacent. Now, MIDI-CV solves this problem with RTRG output, but nothing similar is available for MIDI-GATE. Since MIDI-GATE is supposed to be used for drums much more frequently (e.g. very fast hats or snare rolls) it seems reasonable to add the same functionality to MIDI-GATE. My exact proposal is to add an option in right-click menu called "Retrigger mode" or something; when activated, the module outputs fast triggers same as RTRG output of MIDI-CV.

**Comment by AndrewBelt** [comment]
This is the correct place.

Is your MIDI device sending a "note off" and "note on" of the same note less than 1ms apart? You can solve this by adding some space between notes. I can't think of a reason why a MIDI controller would be this close between notes.

**Comment by ROGAVKA** [comment]
I'm currently using Synthstrom Deluge https://synthstrom.com/product/deluge/ 
The special feature of this device is the ability to zoom in and out to different grid resolutions. When for example viewing 16th notes and filling all 16 pads with hat notes, the behaviour of MIDI-GATE is actually very strange: it seems that retriggering each new note is a random event (about 50% chance to skip next adjacent note).

Yes, I can zoom in to 32nd notes and create pauses, but it's a tedious thing to do each time :)
 
I totally understand that my use case might be a rare one, but thought that if something similar is done already for MIDI-CV it may be possible to implement. I also had exactly the same problem with Ableton + Bridge + VCV combination. Though I abandoned bridge now, I expect this problem to return when Rack for DAWs is out :)

**Comment by ROGAVKA** [comment]
On a side but maybe related note I noticed that if i feed RTRG output of MIDI-CV to GATE input of CV-MIDI there's also a huge chance of skipping the note by CV-MIDI itself. Perhaps RTRG pulse is too short?

**Comment by AndrewBelt** [comment]
This is a result of #1654
