### ISSUE TITLE
FR: Menu option to set cc 74 for MW in MIDI-CV

### ISSUE THREAD

**Issue by lnikj** [VCVRack/Rack#1694]
### Summary

MPE controllers send Y-axis data on cc74. Currently to intercept that you can either use multiple MDI-CCs or reconfigure your controller (with variable ease of doing so) to cc1.

### Proposed design

Add a checkable menu option: Set MW to cc74 (MPE)

**Comment by AlexanderPavlenko** [comment]
Another option would be to make a polyphonic version of MIDI-CC module.

**Comment by AndrewBelt** [comment]
@AlexanderPavlenko I like this idea better. Added MPE mode to MIDI-CC and MIDI-Gate in Rack v2.
