### ISSUE TITLE
Unbounded ParamQuantity still shows Initialise item in right click menu of widget

### ISSUE THREAD

**Issue by david-c14** [VCVRack/Rack#1699]
### Details

Operating system: Ubuntu
Rack version: v1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

### Summary

a rotary controller (paramQuantity with range -INFINITY to +INFINITY) will not reset. But the associated paramWidget still shows the initialize menu item in the context menu, with the 'double click' shortcut specified. 

There doesn't seem to be a clean way to suppress the context menu item to fix the discrepancy

### Steps to reproduce

configure a parameter with a minValue of -INFINITY and a maxValue of +INFINITY

**Comment by AndrewBelt** [comment]
Removed "Initialize" menu item when param is unbounded in Rack v2.
