### ISSUE TITLE
Grafix issue Mac OSX 10.12.6

### ISSUE THREAD

**Issue by stephanovici** [VCVRack/Rack#17]
![screen shot 2017-09-11 at 2 46 31 pm](https://user-images.githubusercontent.com/31855288/30279527-1f29247a-9716-11e7-8c4d-222f1c35962d.png)

**Comment by Kinetikai** [comment]
Same issue. Running 10.12.6. All knobs and jacks function but graphics are missing.

**Comment by Bombaclaat** [comment]
same issue here. I'm running 10.11.6

**Comment by tsonesound** [comment]
I'm having the same issue on 10.9.5

**Comment by mattimoe** [comment]
Same: 10.7.5

**Comment by AndrewBelt** [comment]
This is likely an issue with OpenGL's framebuffer. What Apple models does everyone have?

**Comment by mattimoe** [comment]
An old 2010. I am surprised it is working at all. :)

**Comment by stephanovici** [comment]
Late 2010.

**Comment by Kinetikai** [comment]
Mid 2010 MacBook Pro. Noticing a theme here...

**Comment by stephanovici** [comment]
Yeah, but still. First time I have encountered this situation.

**Comment by oblivionratula** [comment]
Displays fine here (but runs one CPU near 100% and warms the lap considerably).

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.5 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	MBP112.0138.B18
  SMC Version (system):	2.19f12

Intel Iris Pro:

  Chipset Model:	Intel Iris Pro
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel (0x8086)
  Device ID:	0x0d26
  Revision ID:	0x0008
  gMux Version:	4.0.8 [3.2.8]

NVIDIA GeForce GT 750M:

  Chipset Model:	NVIDIA GeForce GT 750M
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Total):	2048 MB
  Vendor:	NVIDIA (0x10de)
  Device ID:	0x0fe9
  Revision ID:	0x00a2
  ROM Revision:	3776
  gMux Version:	4.0.8 [3.2.8]
  Displays:
Color LCD:
  Display Type:	Retina LCD
  Resolution:	2880 x 1800 Retina
  Retina:	Yes
  Pixel Depth:	32-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Built-In:	Yes

**Comment by AndrewBelt** [comment]
Are the cables visible if you were to drag from where a port would be?

**Comment by mattimoe** [comment]
Yes, cables are visible.

**Comment by Kinetikai** [comment]
Cables are visible and functional.

**Comment by synthi** [comment]
Had this issue several times while patching, windows7 x64, tried with both intel3000 gfx and nvidia 555M graphic processors

**Comment by naus3a** [comment]
Same issue here: MBP mid 2012, NVIDIA Geforce GT650, OpenGL 2.1.

How are you drawing knobs?

**Comment by AndrewBelt** [comment]
Knobs are drawn into a framebuffer, so the framebuffer is 99% likely the issue. Framebuffers were introduced in OpenGL 3, while I'm using OpenGL 2 with the framebuffer extension enabled. Perhaps the extension was removed from your GL implementation in favor of the actual standardized thing, so this "fake" framebuffer extension doesn't actually exist.  Completely arbitrary thought though.

**Comment by naus3a** [comment]
Yes, could be different nuances of the same thing :)

For the record I use framebuffers everyday on this machine and the framebuffer extension too. If some GLSL is involved in the rendering, it could be just a shader exploding for something silly.

If I manage to find some free time I'll try to build from source and hunt down the incriminated code :)

**Comment by AndrewBelt** [comment]
Okay, we need to fix this and it'll take a community effort. I can't reproduce this on 10.7, 10.10, or 10.12. It might take a Skype call with someone, or for me to prepare a different binary with debug tools enabled.

**Comment by naus3a** [comment]
10.8 here: available for Skype session and debug builds.
Which time one are you into?

**Comment by DalienDalien** [comment]
Same issue here..10.9.5

**Comment by Zoob1200** [comment]
I am having the same issue here, Mac OSX10.8.3 ~ 2.7Ghz Intel i7 /8GB/SSD... no knobs, some knobs don't function, but all jacks seem to.

**Comment by AndrewBelt** [comment]
Still not working with v0.3.1? I didn't change anything with the framebuffer, but just in case.

I've gotten about 30 emails about this, so I imagine 300+ people are having this problem. It works fine on three different Macbooks I've tested, so it must be something about the OpenGL drivers on ~2010 Macbooks.

**Comment by stephanovici** [comment]
![screen shot 2017-09-14 at 2 59 55 pm](https://user-images.githubusercontent.com/31855288/30428748-6d94b658-995d-11e7-8479-facb58867662.png)

Same issue! And also, when I open the "about" tab it says version 0.0.0 :)) P.S On the apple site it is specified that Mac 2010 is supposed to support openGL untill 3.3 version.

**Comment by stephanovici** [comment]
And there's also this guy "I am having the same issue here, Mac OSX10.8.3 ~ 2.7Ghz Intel i7 /8GB/SSD... no knobs, some knobs don't function, but all jacks seem to." 2.7 i7, not a 2010 Mac for sure.

**Comment by DalienDalien** [comment]
![schermata 2017-09-14 alle 16 31 11](https://user-images.githubusercontent.com/31928736/30435599-6467a9c0-996a-11e7-80a0-7e93e50c00ac.png)

**Comment by naus3a** [comment]
I find it interesting that LEDs glow correctly: without looking at how they are drawn it means nothing, but it ringed a bell for me since they look like a ball + a couple blur passages into an fbo :)

**Comment by AndrewBelt** [comment]
The LEDs aren't drawn in fbos. But knobs are.

**Comment by naus3a** [comment]
Makes sense, and probably you already though about it, sorry :)

**Comment by Eltanoloko** [comment]
I am having the same problem on 10.10.5 

Leds working, cables dragging, but i can see buttons, knobs, sliders and connection points

**Comment by neonanthracite** [comment]
same problem here.
no knobs, no grid.

MacBook Pro (17-inch, Mid 2010)
2,66 GHz Intel Core i7
4 GB 1067 MHz DDR3
NVIDIA GeForce GT 330M 512 MB
Mac OS X El Capitan 10.11.6

**Comment by abggon** [comment]
Same, same...
MacBook Pro Mid 2010
Processor  2.4 GHz Intel Core 2 Duo
Memory  4 GB 1067 MHz DDR3
Software  OS X 10.8.5 (12F2560)

**Comment by AndrewBelt** [comment]
Could someone with this issue download GLEW (`brew install glew`), and run `glewinfo` and paste it here or email me a text file of it?

**Comment by reakttekno** [comment]
same problem, theres no solution yet right?:)

**Comment by AndrewBelt** [comment]
Not yet

**Comment by craigbirmingham** [comment]
Andrew, I think I have the glewinfo for you and have emailed you a txt file.

**Comment by naus3a** [comment]
Here's my report:
https://gist.github.com/naus3a/08feaac7e23426a1d3b339aa9d50fed0

**Comment by lorenzmsk** [comment]
Same problem. MacBook Pro mid2009 OSX 10.9 Mavericks.

**Comment by SKYNET23** [comment]
I'm having same issue, running on a PC w Win 7 Ult...

**Comment by AndrewBelt** [comment]
Could someone having this problem email me if you're willing to test some development builds for me? I'll email you a DMG and ask for a screenshot of the result.

**Comment by craigbirmingham** [comment]
Would be happy to test it out for you, Andrew.

**Comment by AndrewBelt** [comment]
I believe this is caused by ~2010 Macs not supporting stencil attachments of framebuffer objects. This is the offending line of nanovg_gl_utils.h:

	glRenderbufferStorage(GL_RENDERBUFFER, GL_STENCIL_INDEX8, w, h);

A workaround is not obvious.

**Comment by AndrewBelt** [comment]
To anyone that can write C++: I have confirmed that the `example_fbo` binary in the repo https://github.com/memononen/nanovg does not work on the above list of Macs. If you can get this to work on your Mac by modifying the `nvgluCreateFramebuffer` function in `nanovg_gl_utils.h`, post what you did here (or submit a PR upstream) and this issue will be solved.

**Comment by naus3a** [comment]
Will have a look, thanks

**Comment by SKYNET23** [comment]
hi, Andrew - I am experiencing the same problem (no sound, knobs, ins or
outs, but can drag cords), but using a PC -  core i7 processor running Win
7 Ult SP1...  I am open to try a new build if you like...

**Comment by alexisdel79** [comment]
Exactly same issue here, no knobs and no patch jacks... OS X Yosemite. MacBook Pro core2duo late 2010.

**Comment by AndrewBelt** [comment]
I fixed patched nanovg upstream to use a render buffer object fallback and updated the submodule with b1f8e0977de30f7f5ee7e2cfd88954f201b15405.

**Comment by Eltanoloko** [comment]
Hi Andrew, when are you planning the release of the fix under this issue?

**Comment by AndrewBelt** [comment]
v0.3.2 is planned for Sunday.

**Comment by jgborghi** [comment]
Thanks!!!!


VCVRack v.0.3.2  - Graphic problems fixed - White background rack and knobs that didn't appear.


OSX High Sierra


NVIDIA GeForce 330M




________________________________
De: Andrew Belt <notifications@github.com>
Enviado: sábado, 23 de setembro de 2017 13:39
Para: VCVRack/Rack
Cc: jgborghi; Manual
Assunto: Re: [VCVRack/Rack] Grafix issue Mac OSX 10.12.6 (#17)


v0.3.2 is planned for Sunday.
