### ISSUE TITLE
Keyboard Shortcuts not working (on some layouts)

### ISSUE THREAD

**Issue by MovGP0** [VCVRack/Rack#1700]
### Details

Operating system: Windows 10
Rack version: v1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

### Steps to reproduce

- Use a multi-layered keyboard layout like [Neo2](https://github.com/neo-layout/neo-layout/blob/master/windows/Neo2.0_setup.exe)
- Try to use keyboard shortcuts in VCV Rack (ie. Ctrl+V or Ctrl+D, etc.)

### Expected behaviour

The keyboard shortcuts should work.

### Current behaviour

The keyboard shortcuts don't work.

### Additional information 

Those kind of bugs are usually because of a bug in the the dead-key detection system of the native windows library. Microsoft is not fixing it for backward compatibility. So in C++ programs, there is often some work around needed. Mostly those kind of bugs also happen with layouts like the french AZERTY keyboard, but haven't tried that yet.

**Comment by AndrewBelt** [comment]
Rack v2 has fixed key commands for all keyboard layouts, including AZERTY and Dvorak. See https://community.vcvrack.com/t/rack-development-blog/5864/55
