### ISSUE TITLE
MIDI-MAP Akai APC Key 25 crash

### ISSUE THREAD

**Issue by VisionEEG** [VCVRack/Rack#1701]
### Details

Operating system: Windows 10
Rack version: v1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): Akai APC Key 25

### Summary

VCV Crash when selecting the Akai APC Key 25 USB MIDI controller.

### Steps to reproduce

1. New project
2. Insert MIDI-MAP module
3. Select "APC Key 25 1" from the list
4. Crash

![image](https://user-images.githubusercontent.com/29256980/73790299-dc35be00-4765-11ea-8862-9851f016c6e3.png)
[log.txt](https://github.com/VCVRack/Rack/files/4156336/log.txt)

**Comment by AndrewBelt** [comment]
Thanks for the good bug report. As a guess, it could be crashing in `MidiInWinMM::openPort` because the device is in use by another DAW. If this isn't the case, *can* another DAW use this MIDI device without crashing?

**Comment by VisionEEG** [comment]
You are right, it does not crash when Ableton is closed.  This is weird though since the other controller Novation Launch Control XL is able to control both VCV and Ableton at once with the same MIDI CC (I see both knobs moving).

**Comment by AndrewBelt** [comment]
I don't think the Windows MIDI API guarantees that multiple applications can use a single MIDI device simultaneously. Same with ASIO. Some drivers might support it, like your Launch Control XL, but it appears that the Akai APC Key 25 driver does not. Since this is a limitation of the Windows MIDI API, Rack cannot fix this.

**Comment by VisionEEG** [comment]
Just to confirm, as you said, this particular controller can't be used by two software at the same time.  When I load it in VCV, then go into Ableton MIDI settings, it is displayed in orange and is unusable.
![image](https://user-images.githubusercontent.com/29256980/73984839-3918ac00-48ff-11ea-97b0-19a892512103.png)
