### ISSUE TITLE
Non-session-manager (NSM) support 

### ISSUE THREAD

**Issue by grammoboy2** [VCVRack/Rack#1706]
Working in a modular setup with different applications via JACK is made much easier with the 
Non-session-manager (nsm). 

It saves and restores applications in a session, as well as the JACK connections between them. Huge improvement for a modular workflow on Linux.

Non-session-manager is officially supported by the JACK developer all though it doesn't depend on JACK or any soundsystem.

http://non.tuxfamily.org/wiki/Non%20Session%20Manager
http://non.tuxfamily.org/nsm/API.html

**Comment by mxmilkiib** [comment]
There's a new community development team fork of NSM, https://github.com/linuxaudio/new-session-manager, same OSC API but with slight clarifications. NSM is becoming moreso the de facto Linux/libre session management system, with new GUI client [Argodejo](https://laborejo.org/argodejo/) alongside [RaySession](https://github.com/Houston4444/RaySession) (which is older and both GUI and backend).
