### ISSUE TITLE
Invisible connections instead of cable clutter - WiFi pins (?)

### ISSUE THREAD

**Issue by wodorost** [VCVRack/Rack#1707]
There are some cables like those connecting **CLK**, **RUN** or **RESET** in the clock generator or the notes of a chord progression which are connected to many, many inputs and add unreasonable clutter to a rack.

I would like to propose a **special “cable” which is invisible** and can be connected from a certain output to many inputs without the cable visibility and some chaos which can exist in those random generated clock driven sequences.

Imagine those i will call them "WiFi Pins" with distinct colors and maybe a possibility to name them. There would be just ONE send pin of any color and any number or receiver pins of the same color. There could be also a function to "peek" the imaginary cables if You like to visualize how much cable clutter You are missing :)

Maybe a sketch would be more helpful to understand my idea. This rack has no sense it is just some quick illustration how they could look and feel - every pin could also pop his name by mouse hover.

![Pins1](https://user-images.githubusercontent.com/2078351/74330888-cf7f1e80-4d92-11ea-81fc-f2e84c763fb3.png)

**Comment by AndrewBelt** [comment]
You can set cable opacity to 0 and hover ports to see the cables connected to them.

**Comment by wodorost** [comment]
I know about the opacity Andrew, but this function makes ALL cables invisible.

I would like to see all other cables, but not those clock ones -- which in my three last racks made maybe half of the connections...

**Comment by AndrewBelt** [comment]
This would overcomplicate the UI in my opinion, so I'll reject feature request.
