### ISSUE TITLE
Suggested standard clipboard format for Rack sequencers

### ISSUE THREAD

**Issue by RichieHindle** [VCVRack/Rack#1708]
### Summary

It should be possible to copy and paste sequences of notes between sequencer modules from different vendors.

### Proposed design

There is a proposed standard at https://github.com/squinkylabs/SquinkyVCV/blob/master/docs/clipboard-format.md

The standard has been created by Marc of Impromptu Modular, Bruce of Squinky Labs, and Richie of Entrian Audio.  Each vendor has written a working implementation in prototype form, to prove the concept, but the spec is by no means set in stone.  All feedback is welcome!

**Comment by AndrewBelt** [comment]
This cannot be an official standard because no proposal can cover all use cases, but of course any developer is welcome to make/use any proposal.
