### ISSUE TITLE
VCV Rack: Core Audio in Windows: Jack is only allowing 4 output 

### ISSUE THREAD

**Issue by Cordoha** [VCVRack/Rack#1709]
Windows 10
JACK Audio
VCV Rack v1.1.6

Core audio is only allowing 4 Output and 4 Input connections. How can I enable 8 Output, and 8 Input, or 16, or 64? Even with both 8 and 16 Core Audio plugins. Is it a JACK issue?

I tried Stoer Melder's "64 Audio" plugin to see if it'd increase the number more than 4 ins and outs, but it does not.

As an example: [Picture of the issue](https://i.imgur.com/hgkm7M0.png)

**Comment by Cordoha** [comment]
Skrylar Jack Audio plugin seems to fix the issue, now I can have as many ins/outs I want while running Jack. Will still leave this open to see if I get a reply back.

**Comment by AndrewBelt** [comment]
JACK is unsupported in Rack but enabled as-is in the RtAudio/RtMidi build. Anyone is welcome to create a third-party plugin that registers a better JACK audio/MIDI driver with Rack's audio/MIDI API.
