### ISSUE TITLE
Module calling sequence

### ISSUE THREAD

**Issue by martin-lueders** [VCVRack/Rack#171]
OS (if applicable): all
Version (or "dev" if compiling from source):

I am just wondering which functions of the plugin / module are called when?

In particular, I seem to have a problem with my Quantum module that sometimes it starts up in a strange state (some LED's on and the buttons unreactive). Once I call the 'initialize()' routine from the module menu, everything works fine.

I am wondering in particular under which circumstances initialize() or fromJson could go wrong?

Thanks,
Martin

**Comment by antoniograzioli** [comment]
I have somethins strange happening with my Mixer, I didn't look into it too deeply but the "Mute" buttons seem to "start" quite randomly

**Comment by martin-lueders** [comment]
Assuming, that you initialise the module correctly, it looks like the same issue as with my Quantum.

I do initialize, but it seems that sometimes initialize() is not called, or something else overwrites the memory. I guess I will have to look into it with Valgrind.

Can you switch these buttons, which are on on loading the module? Does it recover when you call initialise from the menu?

**Comment by antoniograzioli** [comment]
when I load my mixer, sometimes one or two "mute buttons" (they are all Schmittrggers) are selected, sometimes 3 or 4...sometimes none...

It looks lke my Initialize is correct (in the initialize method I set 8 variables to zero...) and if I click "Initialize" from the menu, all buttons load correctly (they are all set to OFF)

you can test this behaviour with my 8-Channel mixer, I can share the code with you if it helps understand the issue...

**Comment by martin-lueders** [comment]
Yes, definitely sounds like the same problem I am having with Quantum. You can see the code in my github.

**Comment by AndrewBelt** [comment]
`initialize()` is only called when the user hits initialize. If you want to call it on startup, call it from the constructor.

**Comment by martin-lueders** [comment]
Ah! I guess that explains it. Will try that later. Thanks a lot!

**Comment by AndrewBelt** [comment]
Maybe I should rename it to `reset()`?

**Comment by martin-lueders** [comment]
I think the name could stay as it is, if it is noted somewhere that it is not called automatically. If you think about changing it, doing that before 0.4.0 would be good, as that involves more changes to the plugin codes anyway.

Just out of curiosity: How does the initialization work in SEQ3? That code was the example which I followed, and I could not see any call to initialize() in the constructor. But still it does work and always comes up in the correct state. What is the trick there?

Is the line
`bool gateState[8] = {};` 
enough to set all to 'false'?

Cheers,
Martin

**Comment by AndrewBelt** [comment]
Yup, that sets the array to all zeros, which corresponds to false.

**Comment by martin-lueders** [comment]
OK. great. I was not sure whether an empty array is enough to reset the elements to zero, or whether it will only allocate the storage and assign the pointer.

I only had an empty declaration of my array and was relying on the fact that initialize() would be called after the constructor. (should have read the rack sources more carefully...).

Now it all seems clear, and first tests show that my module is not coming up correctly. 
Thanks again for your help!!

Martin

(feel free to close that issue. I leave it open in case Antonio wants to comment.)

**Comment by AndrewBelt** [comment]
Okay, great. I'll close

**Comment by antoniograzioli** [comment]
ok thanks. In my case I had to set 8 variables to false to unmute the 8 channels. I think I didn't put the initilization code in the right place ;-)
