### ISSUE TITLE
isMonophonic() always evaluates to true

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Rack#1710]
### Details

Rack version: v1.dev.7a789af

### Summary
[Port.hpp](https://github.com/VCVRack/Rack/blob/v1/include/engine/Port.hpp#L162) isMonophonic() always evaluates to true even when not monophonic

a use case: 
`inputs[GATE_INPUT].isMonophonic() ? nCh = inputs[GATE_INPUT].getChannels() : nCh = 1;`

This line will always set nCh to 1 but in this or similar use cases, nCh would need to evaluate to the false condition 'number of channels' when !isMonophonic(). 

I have switched to using isPolyphonic() and this works as expected. Should isMono only evaluate to true here? Channels was not equal to 1, it was 3 so more confused why it would not evaluate the ternary nCh to false and set number of channels to 3. but anyway...

Changing isMonophonic() condition to:

```
/** Returns whether the cable exists and has 1 channel. */
	bool isMonophonic() {
		return (channels > 0) | (channels < 2) ;
	}
```

This works and evaluates the ternary. Is there use cases for isMonophonic() where it always should be True?

**Comment by MarcBoule** [comment]
I have just tried some tests in line with what you are describing and I can't reproduce your indicated behavior when you say "_isMonophonic() always evaluates to true even when not monophonic_". In my experiments on an input port, it returns true if and only if a mono cable is connected; when no cable or a poly cable, it returns false.

**Comment by Coirt** [comment]
On Viz it will show 3 channels however with debug it will only show 1. 

in the code:

```
inline const char * const BoolToString(bool b) {
	return b ? "True" : "False";
}

process {
bool	 monoGate = inputs[GATE_INPUT].isMonophonic()

inputs[GATE_INPUT].isMonophonic() ? nCh = inputs[GATE_INPUT].getChannels() : nCh = 1;
outputs[OUT_OUTPUT].setChannels(nCh);


    if (storeValues){//    debugTrig.process(button press)
         DEBUG("\n\nDebug Mono: %s\nNumber of Channels = %d\nValue of monoGate = %d (%s)", 
        BoolToString(storeValues), nCh, 
        monoGate, BoolToString(monoGate));
    }

}

console output:
```
[10.670 debug src/Panel6.cpp:139]

Debug Mono: True
Number of Channels = 1
Value of monoGate = 0 (False)

```

**Comment by Coirt** [comment]
isPolyphonic() works channels from the output are set to 3.

**Comment by MarcBoule** [comment]
In your code example above, you have one line backwards I think, I would try this:

`nCh = inputs[GATE_INPUT].isMonophonic() ? 1 : inputs[GATE_INPUT].getChannels();`

instead of this:

`inputs[GATE_INPUT].isMonophonic() ? nCh = inputs[GATE_INPUT].getChannels() : nCh = 1;`

**Comment by Coirt** [comment]
Interesting, this does work. Thanks Marc!

 Is either way not the same? Your way looks nicer.

**Comment by MarcBoule** [comment]
I could be wrong here, but other than the swapping of conditions, I think you have to move the `nCh =` part outside of the conditional statement. Not sure it works like you think.
https://www.tutorialspoint.com/cplusplus/cpp_conditional_operator.htm

**Comment by Coirt** [comment]
Strange google does not want to show me the results of the search were I seen it explained like the aforementioned. Learn the hard way I guess!

Cheers!
