### ISSUE TITLE
"Building" steps don't produce a situation where Rack can see plugins

### ISSUE THREAD

**Issue by mxmilkb** [VCVRack/Rack#1714]
Operating system: Linux

I've cloned and build VCV Rack, and it runs. I've cloned various modules into the plugins directory, as per the first path [here](http.s://vcvrack.com/manual/Building#building-rack-plugins), built, and the plugin.so is in the directories, but running ./Rack doesn't show them on right click. Might there be a step missing from the documentation?

**Comment by AndrewBelt** [comment]
There are two options proposed in the manual.

>Run Rack
>```make run```

which runs Rack in development mode. (See https://vcvrack.com/manual/Installing#command-line-usage.)
Or in the plugin directory,

>```make install```

and then run Rack normally.

**Comment by mxmilkb** [comment]
Thanks you!

How does one "`make install`" Rack itself?

**Comment by AndrewBelt** [comment]
There is no `install` target in Rack's Makefile.

**Comment by mxmilkb** [comment]
I know, that's why I put it in quotes.

Is there an automated way of extracting the runtime files to a directory from the source/build directories?

**Comment by AndrewBelt** [comment]
Well there's `make dist` but it's not intended for public use.

**Comment by mxmilkb** [comment]
`make install` is generally used as the method of extracting runtime files the source directory post-build. `/usr/local` is standard (as in local to the machine, not the system-wide base-profile/distro `/usr` level (that used to be read-only)).

To package, one uses a variable to alter the this prefix, [like this](https://github.com/kmatheussen/radium_compressor/blob/master/Makefile#L39) used along with `make DEST_DIR="$pkgdir/usr/" install`, or something similar.

Or a manual `cp`/`install` into the $pkgdir could be done, though traditionally this is the purview of the `make install`, if that might be something you would be willing for the Makefile to provide?

**Comment by AndrewBelt** [comment]
`make install` wouldn't make much sense on Mac and Windows. On Mac, app bundles must be signed and notarized to run. On Windows, it would need to build the NSIS installer and the user needs to click through their desired install options. Neither of these can be automated.

**Comment by mxmilkb** [comment]
True, though Mac and Windows users would simple avoid using such a `make install`. Or, to avoid ambiguity, it could instead be called `make linuxinstall`.

**Comment by AndrewBelt** [comment]
There is actually no standard install location for Rack on Linux. This is because I'd like all Rack system files to be in one folder rather than different things spread out on your system. `make install` on Linux would require me to standardize an install location, which I don't want to do. It would also require the user to build and obtain the Fundamental plugin, since Rack needs `Fundamental.zip` in order to extract it upon first launch.

**Comment by mxmilkb** [comment]
What is the path of the one directory that you have Rack and associated files in?

**Comment by AndrewBelt** [comment]
I'm not sure what you're asking. There are two folder variables, Rack's system folder and its user folder. The user folder on Linux is `~/.Rack`. The system folder is `.`, the current working directory.

**Comment by mxmilkb** [comment]
I wasn't sure what you were implying by saying "rather than different things spread out on your system".

You confirmed my understanding that Rack "system" (i.e. runtime files generated from the build) are all stored in the same directory.

This is compatible with a `make install`. Implementing that would only standardise a mechanism for extracting the runtime files from the messy source/build directory. The default prefix path is /use/local, but if you haven't noticed, when you install software through a package manager, none of it gets installed to a subdirectory of /usr/local, because the package uses the freedom that `make install` provides (and you apparently wish to provide) by letting the packager choose the DESTDIR prefix (about the only class of user who will be using `make install`, or a similarly named make directive).
