### ISSUE TITLE
Total CPU usage meter

### ISSUE THREAD

**Issue by calslate** [VCVRack/Rack#1716]
### Summary
The CPU usage meters are incredibly useful, especially with crazy splitting and merging patches, but sometimes my fan starts whirring and I wonder _'How much CPU is Rack **as a whole** using?'_
I think that an added total CPU meter would make sense, rather than opening `htop` every time.

### Proposed design
There is a precedent for such a feature in music software: Ableton Live definitely has one in the top right corner by default, having never used Cubase or FL etc. I don't know about those. It would of course be up to you and your UX designer to decide where it would go, but I think that the bottom left of the screen could work nicely, as it conceptually tethers the meter to the virtual rack (rather than the menu bar).

Thanks Andrew, waiting eagerly for Rack 2: This Time it's Personal

**Comment by AndrewBelt** [comment]
In Rack v2, only VCV Audio (and any other "primary module" such as VCV Recorder) can compute the ratio between idle time and total time. Rack's engine can't compute this.

**Comment by calslate** [comment]
I assume I can close the issue, then?

**Comment by AndrewBelt** [comment]
I suppose. If the feature was added, it would need to be added to VCV Audio, VCV Recorder, etc *individually*. And I don't see that happening because it would require a redesign to offer this UI.
