### ISSUE TITLE
Discussion: how to best debug plugins

### ISSUE THREAD

**Issue by martin-lueders** [VCVRack/Rack#172]
OS (if applicable):
Version (or "dev" if compiling from source):

What are you guys using to debug your plugins if something goes wrong? 
Did anybody manage to set up a Xcode project or VisualStudio project, as these environments are very nice for debugging?

Cheers,
Martin

**Comment by antoniotuzzi** [comment]
I was trying in my free (small free) time to setup an Xcode platform to do debugging

**Comment by AndrewBelt** [comment]
I use gdb/lldb and sometimes valgrind and Dr Memory, and it works just fine.

**Comment by antoniograzioli** [comment]
nope, at the moment I am using SublimeText on Mac, Visual Studio on PC but only to write code, no debugger so far...I simply launch terminal/Mwing32 and wait for the errors to show up;-)

**Comment by AndrewBelt** [comment]
You can always printf debug and see the result scroll by in the terminal.

**Comment by Flowstoner** [comment]
in Visual Studio attach the gdb debugger found in the MinGW-w64 binaries:
launch your MSYS2 MinGW shell
`$ gdbserver host:YOURPORT /YUOR_LOCATION/Rack/dist/Rack/Rack.exe`

this is the my result shell:

> $ gdbserver host:9000 /d/Rack/dist/Rack/Rack.exe
> Process D:/Rack/dist/Rack/Rack.exe created; pid = 14280
> Listening on port 9000

after:
from Visual Studio 2017 ther is an option in the project proprierties  from the executable’s context menu in the Solution Explorer “Debug and Launch Settings”:
select Attach for MinGW or  Lauch for MinGW to produce an launch.vs.json and configure it.

so compile with the make file and attach the debugger, but it have some limit, seem you can chose only the main breakpoint and after that you can step to other breakpoint.

**Comment by AndrewBelt** [comment]
Oh cool, nice tip.

Another favorite is Xcode's debugger on MacOS, and especially the Instruments app for performance, rendering, and memory monitoring.

**Comment by antoniotuzzi** [comment]
Currently I have a working Xcode project able to compile and run RACK + able to recompile and RUN Fundamental pack.

but plugins CORE are working (midi and audio)
Fundamental ones are crashing on this ASSERT

>         ModuleWidget *module = dynamic_cast<ModuleWidget*>(child);

the child exists, and is of the correct type (VCOWidget), but the dynamic_cast is returning NULL

(probably don't like the object declared in an another context ? )

**Comment by KarateSnoopy** [comment]
btw, if you use printf consider also doing fflush(stdout) or your won't see your debug output till there's enough to auto flush.

**Comment by AndrewBelt** [comment]
Linux and Mac flush on newline. Windows/MSYS2 flush after the buffer is full, so you'll need a fflush(stdout) there.

**Comment by Strum** [comment]
So far all i've needed is the environment and the scope module.

I'd had in mind to build a display module that will give you a read out of levels of incoming signals that i thought would be useful in nutting out unexpected behaviour as well

Is there a way for modules to communicate data between them?

**Comment by Strum** [comment]
If modules had some sort of standardised way of sharing not just signals through jacks but to communicate other information to each on some sort of digital bus if could be useful and add another dimension to the way modules can be put together.

**Comment by AndrewBelt** [comment]
>If modules had some sort of standardised way of sharing not just signals through jacks but to communicate other information to and from each other on some sort of digital bus if could be useful and add another dimension to the way modules can be put together.

This will never happen. Modules can only communicate through voltages and nothing else. Anything else breaks the simple sandbox and makes Rack 10x more complex to develop and understand as a user.

**Comment by Strum** [comment]
No worries , just a thought, I can see how it would add another whole layer of complexity to the whole project.

Perhaps some sort of serial data transmission might be possible with an audio signal.

you could use quatrature encoding like a modem

lol.

that's actually a good application for a modular synth.

**Comment by AndrewBelt** [comment]
But why? The word "modular" itself means self-contained and interchangeable. If two modules talk to each other in their own "secret" way, they're not interchangeable and would be better off combined into a self-contained single module. Leave that stuff for traditional DAWs.

**Comment by Strum** [comment]
Well why not?

because it's possible, I guess, to see if I can and what I could do with it

It could be done in modules with no need for modification of the existing codebase, and I would try and make in open standard that other module developers could use if they wanted.

It would also enable communication between rack running on different host machines over audio, which i think could be a very useful thing.

All without a single change to the existing codebase.

I'll have a go at it when i get some time.

**Comment by Strum** [comment]
MIDI is a modular serial communication standard for audio and other devices btw.

**Comment by AndrewBelt** [comment]
I mean, you can make your own protocol over voltages I guess, as long as it doesn't require a modification of the Rack engine.

I think there are higher priorities for plugin functions, but of course most people develop these for fun anyway.

**Comment by Strum** [comment]
Fun and the challenge of doing it, but I built the modules i have so i can make the sort of music i want to make with rack mostly.

**Comment by ClaudioLisa** [comment]
Hello everybody, my to cents on the subject:
use SysInternals DbgView 
[https://docs.microsoft.com/en-us/sysinternals/downloads/debugview](url)

**Example code:**

#include <debugapi.h>
.
.
.
int   stepCnt  = 0;
int   secCnt   = 0;
char  dbgBuffer[256];
.
.
.
void MyPlugin::step() {

   if(stepCnt++ >= engineGetSampleRate())  {
      stepCnt = 0;
      secCnt++;
      sprintf(dbgBuffer, "%06d) Sample Rate = %f\r\n", secCnt, engineGetSampleRate());
      OutputDebugStringA(dbgBuffer);
   }
.
.
.


**Example output in DbgView:**

00000001	0.00000000	[11084] 000001) Sample Rate = 44100.000000 	
00000002	0.99906880	[11084] 000002) Sample Rate = 44100.000000 	
00000003	2.00246429	[11084] 000003) Sample Rate = 44100.000000 	
00000004	3.00067186	[11084] 000004) Sample Rate = 44100.000000 	
00000005	3.99990702	[11084] 000005) Sample Rate = 44100.000000 	
00000006	4.99821901	[11084] 000006) Sample Rate = 44100.000000 	
00000007	6.00157213	[11084] 000007) Sample Rate = 44100.000000 	
00000008	7.00087595	[11084] 000008) Sample Rate = 44100.000000 	
00000009	7.99914885	[11084] 000009) Sample Rate = 44100.000000 	
00000010	9.00244808	[11084] 000010) Sample Rate = 44100.000000 	
00000011	10.00175095	[11084] 000011) Sample Rate = 44100.000000 	
00000012	10.99972820	[11084] 000012) Sample Rate = 44100.000000 	
00000013	11.99832058	[11084] 000013) Sample Rate = 44100.000000 	
00000014	13.00264359	[11084] 000014) Sample Rate = 44100.000000 	
00000015	14.00092888	[11084] 000015) Sample Rate = 44100.000000 	
00000016	15.00022602	[11084] 000016) Sample Rate = 44100.000000 	
00000017	15.99845314	[11084] 000017) Sample Rate = 44100.000000 	
00000018	17.00176430	[11084] 000018) Sample Rate = 44100.000000 	
00000019	18.00112724	[11084] 000019) Sample Rate = 44100.000000 	
00000020	18.99937630	[11084] 000020) Sample Rate = 44100.000000

**Comment by ClaudioLisa** [comment]
To make things a bit cleaner, we can define a function to incapsulate OutputDebugStringA() 

/*---------------------------------------------------*/
#define DEBUG
#ifdef DEBUG

int dbgprintf(const char *format, ...)
{
 static char buff[256];
 va_list args;
 int ret;

 va_start(args, format);
 ret = vsprintf(buff, format, args);
 va_end(args);

 OutputDebugStringA(buff);

 return(ret);
}

#else
int dbgprintf(const char *format, ...)
{
 return(0);
}

#endif
/*---------------------------------------------------*/

Then, we can use **dbgprintf()**  _almost_ like a normal **printf()** 
and switch off *ALL* the debug prints just by **#undef DEBUG**

**Comment by AndrewBelt** [comment]
@ClaudioLisa Please see #730

**Comment by JoakimLindbom** [comment]
Another option for debugging, at least when it goes to timing and sync, is to create outputs only for debug purposes. I'm my ongoing work, I have different 8 clocks that needs to be synced (but, ahem, right now they're behaving a bit strange...), so I've added these sections to the code and then I attach the outputs to oscilloscopes or volt meters.
``` 
enum OutputIds { 
    OUT_GATE,                                   // Gate out
    OUT_CV,                                     // CV Out
    #ifdef DEBUG
    ENUMS(OUT_DEBUG, NUM_CLOCKS),
    #endif
    NUM_OUTPUTS
  };
...
...
    #ifdef DEBUG
    // Connect clocks 0-7 to DEBUG outputs
    for (int i=0; i<NUM_CLOCKS; i++) {
        outputs[OUT_DEBUG+i].value = clock[i].isHigh(0.0, 0.5) ? 10.0f : 0.0f;
    }
    #endif
```

**Comment by izzyreal** [comment]
A [Conan](https://conan.io/) project or similar (buckaroo, vcpkg, etc.) would be nice. Or else a CMakeLists.txt.
