### ISSUE TITLE
Smart MIDI voicing.

### ISSUE THREAD

**Issue by SaccoSVD** [VCVRack/Rack#1724]
I would love to have effective ways to split a keyboard into multiple parts.

It would also be lovely to be able to have some sort of smart voicing system that takes the notes/gate from a MIDI CV and you can set voicing rules (such as octave transports under certain conditions), by using different rules you can set projects with say synth horns and piano and the horns will play one octave below after a certain note high in the keyboard so the horns can accompany better.

Think about a Chariots of fire realtime playable project. ;-)

**Comment by SaccoSVD** [comment]
This is the kind of thing I'm working on.

https://www.youtube.com/watch?v=lZyV7McJZV4&feature=youtu.be

**Comment by AndrewBelt** [comment]
I believe what you're describing can be done with a separate module using CV/gates signal pairs (not MIDI). I have added a suggestion to the Module Ideas thread on the forum. https://community.vcvrack.com/t/module-ideas/7175/231

**Comment by AndrewBelt** [comment]
https://library.vcvrack.com/ImpromptuModular/Part-Gate-Split is now released.
