### ISSUE TITLE
CHORDS - dim4 mislabeling?

### ISSUE THREAD

**Issue by MarcBoule** [VCVRack/Rack#1725]
**Module**: VCV CHORDS module.

**How to reproduce**: Initialize the module, set the second channel to F#, which is 6 semitones up.

**Problem**: the module shows "Cdim4" in the display, and if my understanding of intervals is correct, I think it should instead show "Cdim5".

**Comment by AndrewBelt** [comment]
This is the issue tracker for VCV Rack itself. Email contact@vcvrack.com for issues with premium VCV plugins.

I have fixed this typo and will be released in the next VCV Chords version.
