### ISSUE TITLE
Movable modules window

### ISSUE THREAD

**Issue by hwpfeil** [VCVRack/Rack#1728]
Linux, kde5/plasma5, 17" screen
### Summary
The modules window blocks access to the Rack window, unable to drag module onto the rack.
Would like to be able to move the module window, drag it aside to allow access to the Rack.
### Proposed design
Add a resize grabber to the lower right corner of the modules window. Allow resize and move.

**Comment by AndrewBelt** [comment]
>unable to drag module onto the rack

I'm not sure what this means. Simply click and drag the module from the Module Browser to the desired position in the rack.

**Comment by AndrewBelt** [comment]
I am rejecting this feature request. The Module Browser should always fill the screen.
