### ISSUE TITLE
Modules don't "autosave"

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/Rack#173]
OS (if applicable): OSX 10.12.6
Version (or "dev" if compiling from source): dev

I am porting my plugins from v. 0.32 to the latest source. They work OK, except my "Drums" and "Blank Panel" modules are not recalled when reopening rack using the autosave or any other patch. (my other modules all behave correctly)
In v. 0.32 I had no issue with this behaviour...
Should I call some "initialize" method by default? or what else has changed between v.032 and now regarding plugin inizialization?
maybe I forgot some important bit of code?

**Comment by martin-lueders** [comment]
Do you have any variables which are not parameters and which need saving? In this case, I guess, you need to implement the toJson and fromJson functions by yourself. Have a look at the SEQ3 code, which does that. 

After I included these functions to my Quantum, it does save the state correctly.

**Comment by antoniograzioli** [comment]
yes, they all implement from json and to json, and it is working in 0.32. In the new sources the whole module is not recalled...however the values are in the autosave file as follows:

` "data": {
        "autodafeDrumMixerMutes": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      }`

**Comment by AndrewBelt** [comment]
Post your `fromJson` function

**Comment by antoniograzioli** [comment]
in the case of the single drum modules it's pretty straightforward:

`


    json_t *toJson() {
                json_t *rootJ = json_object();

                json_object_set_new(rootJ, "sampletype", json_integer(sampletype));

                return rootJ;
        }

        void fromJson(json_t *rootJ) {
                json_t *stateJ = json_object_get(rootJ, "sampletype");
                if (stateJ) {
                        sampletype = json_integer_value(stateJ);
                }
        }
`

**Comment by antoniograzioli** [comment]
in the case of the Mixer i need to save 8 variables corresponding to mixer mnute buttons:

`

json_t *toJson() {
		json_t *rootJm = json_object();

		json_t *mutesJ = json_array();
		
			json_t *muteJ1 = json_integer((int) ch1m);
			json_t *muteJ2 = json_integer((int) ch2m);
			json_t *muteJ3 = json_integer((int) ch3m);
			json_t *muteJ4 = json_integer((int) ch4m);
			json_t *muteJ5 = json_integer((int) ch5m);
			json_t *muteJ6 = json_integer((int) ch6m);
			json_t *muteJ7 = json_integer((int) ch7m);
			json_t *muteJ8 = json_integer((int) ch8m);

			json_array_append_new(mutesJ, muteJ1);
			json_array_append_new(mutesJ, muteJ2);
			json_array_append_new(mutesJ, muteJ3);
			json_array_append_new(mutesJ, muteJ4);
			json_array_append_new(mutesJ, muteJ5);
			json_array_append_new(mutesJ, muteJ6);
			json_array_append_new(mutesJ, muteJ7);
			json_array_append_new(mutesJ, muteJ8);
		
		json_object_set_new(rootJm, "autodafeDrumMixerMutes", mutesJ);

		return rootJm;
	}



	void fromJson(json_t *rootJm) {
		json_t *mutesJ = json_object_get(rootJm, "autodafeDrumMixerMutes");
		
			json_t *muteJ1 = json_array_get(mutesJ, 0);
			json_t *muteJ2 = json_array_get(mutesJ, 1);
			json_t *muteJ3 = json_array_get(mutesJ, 2);
			json_t *muteJ4 = json_array_get(mutesJ, 3);
			json_t *muteJ5 = json_array_get(mutesJ, 4);
			json_t *muteJ6 = json_array_get(mutesJ, 5);
			json_t *muteJ7 = json_array_get(mutesJ, 6);
			json_t *muteJ8 = json_array_get(mutesJ, 7);



			ch1m = !!json_integer_value(muteJ1);
			ch2m = !!json_integer_value(muteJ2);
			ch3m = !!json_integer_value(muteJ3);
			ch4m = !!json_integer_value(muteJ4);
			ch5m = !!json_integer_value(muteJ5);
			ch6m = !!json_integer_value(muteJ6);
			ch7m = !!json_integer_value(muteJ7);
			ch8m = !!json_integer_value(muteJ8);

			



		
	}`

**Comment by AndrewBelt** [comment]
Looks fine to me. Can you printf-debug to make sure the variables are set correctly at the end of that function?

**Comment by antoniograzioli** [comment]
Ok I will try. But the problem is with the Whole module not loading, not only with the variables, and this didn't happen in v. 0.32...strange....

**Comment by antoniograzioli** [comment]
mmm...i tried 
` printf("%f\n", sampletype);` 
in the fromJson function, no output

if in the step() of course it works and repeats 0.00 forever

**Comment by AndrewBelt** [comment]
use "%d" for integers. What do you mean "no output"? It didn't print anything? If not, the fromJson function isn't being called at all.

**Comment by antoniograzioli** [comment]
yes, I got a warning about foat/int conversion but doesn't matter

yes, by "no output" I mean that nothing gets printed in the terminal window

my fromJson is:

`  void fromJson(json_t *rootJ) {
                json_t *stateJ = json_object_get(rootJ, "sampletype");
                if (stateJ) {
                        sampletype = json_integer_value(stateJ);
                }

printf("%d\n", sampletype);
                
        }`

should I call it directly or is it called by default on module loading?

**Comment by AndrewBelt** [comment]
It should be called whenever the module loads from a patch file or autosave, or when cloned. It isn't called when created with "Add Module".

I honestly can't think of why it wouldn't be called. Run a quick `make` in the Rack directory to make sure there are no ABI oddities?

**Comment by antoniograzioli** [comment]
yeah, I meant "loaded" form autosave or any other patch...
it looks weird because all my other modules load up correctly and recall params correctly (8 and 16 steps, trigger sequencer also make use of fromJson and toJson)...

**Comment by AndrewBelt** [comment]
Post your entire source file, or a link to the repo

**Comment by antoniograzioli** [comment]
OK in the meantime i am trying a git pull followed by a make clean just to make sure I am suing the latest sources...

**Comment by antoniograzioli** [comment]
ok here's the code for my Kick module, and its additional  files:
http://www.autodafe.net/tmp/kick-temp-sources.zip

**Comment by antoniograzioli** [comment]
what's VERY strange is that it happens also with my "Balnk Panel" module that...does NOTHING!!!

if you add to the GUI, close and restart, it is not recalled...
see the code here: http://www.autodafe.net/tmp/Autodafe-BlankPanel.zip

could it be because I have more than one folders of plugins that maybe refer to, or redeclare the same stuff twice? what else could it be?

**Comment by antoniograzioli** [comment]
mmmm...I still have some good diagnostic skills ;-)

Removing other folders revert back to normal racalling behaviour

If I have only one of my "modules pack" installed, everything is ok. But if I add the others, only the first one of the list gets recalled, the others won't be recalled.
I tried leaving only the **Autodafe-Drums** folder and they open and recall correctly, if I add back the **Autodafe** folder, then the drums are not recalled, since the other folder is the first in the list....

**Comment by AndrewBelt** [comment]
I've noticed in some of your screenshots, there is a blank space in the "Add Modules" menu. That shouldn't be there unless there's a "null" plugin somewhere. Maybe that's messing things up on your end.

I see nothing wrong with your kick-temp-sources file.

**Comment by AndrewBelt** [comment]
Try removing all plugins except the one you're working on, and see if it recalls its state.

**Comment by antoniograzioli** [comment]
yes, that's what I did, see my previous comments, that made it recall again

**Comment by AndrewBelt** [comment]
Okay, not sure if that's what you meant.
There's definitely something strange going on. Could you paste the `init()` functions of the Autodafe and Autodafe-Drums projects?

**Comment by antoniograzioli** [comment]
I suspect the culprit is they both create a "plugin" object

**Comment by antoniograzioli** [comment]
**## Autodafe-Drums.cpp**

```
#include "Autodafe.hpp"
#include <math.h>
#include "dsp.hpp"

Plugin *plugin;

void init(rack::Plugin *p) {
	plugin = p;
	plugin->slug = "Autodafe - Drum Kit";
	plugin->name = "Autodafe - Drum Kit";
	plugin->homepageUrl = "https:www.autodafe.net";
		
        createModel<DrumsKickWidget>(plugin, "Drums - Kick", "Drums - Kick");
        createModel<DrumsSnareWidget>(plugin, "Drums - Snare", "Drums - Snare");
        createModel<DrumsHiHatClosedWidget>(plugin, "Drums - Closed Hats", "Drums - Closed Hats");
        createModel<DrumsHiHatOpenWidget>(plugin, "Drums - Open Hats", "Drums - Open Hats");
        createModel<DrumsClapsWidget>(plugin, "Drums - Claps", "Drums - Claps");
        createModel<DrumsCymbalsWidget>(plugin, "Drums - Cymbals", "Drums - Cymbals");
        createModel<DrumsRideWidget>(plugin, "Drums - Ride", "Drums - Ride");
        createModel<DrumsRimClavesWidget>(plugin, "Drums - Rim/Claves", "Drums - Rim/Claves");
     createModel<DrumsMixerWidget>(plugin, "Drums - 8-Channel Mixer", "Drums - 8-Channel Mixer");
}
```



**## Autodafe.cpp**

```
#include "Autodafe.hpp"
#include <math.h>
#include "dsp.hpp"

Plugin *plugin;

void init(rack::Plugin *p) {
	plugin = p;
	plugin->slug = "Autodafe";
	plugin->name = "Autodafe";
	plugin->homepageUrl = "https:www.autodafe.net";
		createModel<LFOWidget>(plugin, "LFO", "LFO");
		createModel<ClockDividerWidget>(plugin, "Clock Divider", "Clock Divider");
		createModel<Multiple18Widget>(plugin, "Multiple 1x8", "Multiple 1x8");
		createModel<Multiple28Widget>(plugin, "Multiple 2x8", "Multiple 2x8");
		createModel<SEQ8Widget>(plugin, "8-Steps Sequencer", "8-Steps Sequencer");
		createModel<SEQ16Widget>(plugin, "16-Steps Sequencer", "16-Steps Sequencer");
		createModel<TriggerSeqWidget>(plugin, "8x16 Trigger Sequencer", "8x16 Trigger Sequencer");
		createModel<FixedFilterWidget>(plugin, "Fixed Filter Bank", "Fixed Filter Bank");
		createModel<MultiModeFilterWidget>(plugin, "MultiMode Filter", "MultiMode Filter ");
		createModel<FormantFilterWidget>(plugin, "Formant Filter", "Formant Filter");
		createModel<FoldBackWidget>(plugin, "Foldback Distortion", "Foldback Distortion");
		createModel<BitCrusherWidget>(plugin, "BitCrusher", "BitCrusher");
		createModel<PhaserFxWidget>(plugin, "Phaser", "Phaser");
		createModel<SpeakSpellWidget>(plugin, "SpeakSpell", "SpeakSpell");
		
}
```

**Comment by AndrewBelt** [comment]
Looks fine to me. (Your URL looks funny though.)

Since they're compiled to different plugin.{so,dylib,dll} files, the `Plugin*` instances exist in different memory, but *just* to make sure, you could add `printf("%p %p\n", plugin, &plugin);` at the end of both `init()` functions to print the address of the plugin, and the address of the plugin global variable. They should all be different.

**Comment by antoniograzioli** [comment]
yesh I just relized I messed up the https:// ;-)

Output of the printf in terminal:

> iMacdiAGrazioli:rack antonio_grazioli$ make run
> DYLD_FALLBACK_LIBRARY_PATH=dep/lib ./Rack
> Current working directory is /Users/antonio_grazioli/Desktop/VCV/Rack
> Loaded plugin ./plugins/AudibleInstruments/plugin.dylib
> 0x7f9f2a501eb0 0x103468548
> Loaded plugin ./plugins/Autodafe/plugin.dylib
> 0x7f9f2a6001a0 0x103707208
> Loaded plugin ./plugins/Autodafe-Drums/plugin.dylib
> Loaded plugin ./plugins/Befaco/plugin.dylib
> Loaded plugin ./plugins/ESeries/plugin.dylib
> Loaded plugin ./plugins/Fundamental/plugin.dylib
> Loaded plugin ./plugins/VultModules/plugin.dylib
> Loaded font ./res/DejaVuSans.ttf
> Loading settings ./settings.json
> Loading patch ./autosave.vcv

**Comment by AndrewBelt** [comment]
Well, that looks good as well, so you are in fact creating two distinct plugins, and Rack is not confusing the two. Does your "Add Modules" have a weird blank entry in it?

**Comment by antoniograzioli** [comment]
I think I got it!
While debugging/posting here I zipped some of my folders to upload. Look like that a zipped folder with the same contents gets loaded anyway, and possibly causes conflicts?. At least I see this in terminal now:


> iMacdiAGrazioli:rack antonio_grazioli$ make run
> DYLD_FALLBACK_LIBRARY_PATH=dep/lib ./Rack
> Current working directory is /Users/antonio_grazioli/Desktop/VCV/Rack
> Loaded plugin ./plugins/AudibleInstruments/plugin.dylib
> 0x7fb22d700fb0 0x1100f3548
> Loaded plugin ./plugins/Autodafe/plugin.dylib
> Loaded plugin ./plugins/Autodafe-BlankPanel/plugin.dylib
> Failed to load library ./plugins/Autodafe-BlankPanel.zip/plugin.dylib: dlopen(./plugins/Autodafe-BlankPanel.zip/plugin.dylib, 2): no suitable image found.  Did find:
> 	./plugins/Autodafe-BlankPanel.zip/plugin.dylib: stat() failed with errno=20
> 0x7fb22d7016c0 0x11039f208


and some more blah blah...
deleting the zipped cotent from the "plugins" folder reverted back to normal behaviour. Or so it seems....

**Comment by antoniograzioli** [comment]
no, it was a quick asumption on my part.
it looks like the issue is related to the two Autodafe.cpp having the same **plugin->slug** 
Blank Panel shared the same "slug" with my Module Pack...

if **plugin->slug**  is the same then the module is not recalled
if **plugin->slug**  is different, normal behaviour

**Comment by AndrewBelt** [comment]
Aha! That's it!

I will add a check to the plugin loader...

**Comment by AndrewBelt** [comment]
Committed 223719d which makes it crash on a slug collision. I'll fix this later when I write a crash handler with nice error messages.

**Comment by antoniograzioli** [comment]
very good, we spotted it in the end ;-)
