### ISSUE TITLE
Comments in Tag.cpp are offset by a line

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#1733]
It looks like when "Apreggiator" was added all the comments didn't stay attached to their tags:
![image](https://user-images.githubusercontent.com/16314838/77832271-0d8d9300-70f2-11ea-851c-aa2e2235ebd9.png)

**Comment by AndrewBelt** [comment]
Avoid posting screenshots of code on this issue tracker. Surround code with ``` instead.

Now, the documentation is the reference for tag descriptions. https://vcvrack.com/manual/Manifest#modules-tags

Duplicate of #1697
