### ISSUE TITLE
Segfault on exit if a plugin loads a custom MIDI driver

### ISSUE THREAD

**Issue by stoermelder** [VCVRack/Rack#1735]
### Details

Operating system: Windows 10 1909
Rack version: v1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): none

### Summary

Rack crashes on exit if a plugin registers a custom MIDI driver.

### Steps to reproduce

Create a plugin, write a custom MIDI driver inherited from`midi::Driver` and register it with `midi::addDriver()` in the plugin's `init()`. Closing Rack segfaults at this line:
https://github.com/VCVRack/Rack/blob/476a49b33b0539b825f53a51bfa7758558433ecc/src/midi.cpp#L278

The segfault is caused by unloading the plugin before the MIDI driver is destructed. Reording the calls in `main()` fixes the problem.

https://github.com/VCVRack/Rack/blob/476a49b33b0539b825f53a51bfa7758558433ecc/src/main.cpp#L223

```
bridgeDestroy();
midi::destroy();
plugin::destroy();
```

**Comment by AndrewBelt** [comment]
Thanks, fixed in Rack v2. Reordering destruction is the correct way to do it, and there are no negative side effects.
