### ISSUE TITLE
Kernel panic on Windows caused by Open Broadcaster Software when using Rack

### ISSUE THREAD

**Issue by SaccoSVD** [VCVRack/Rack#1736]
I did look in the forums first.

### Details

Operating system:
Rack version: v1.1.6

3900X / 64GB RAM / X470 Taichi MOBO / 1080ti

2x Presonus Firestudio Project / 1x Presonus iTwo

USB Breath controller
USB Presonus Faderport
USB Keystation 88

### Summary
The System will BSOD and reboot at random times. Either after a few hours or several minutes. I already had no less than 6 BSODs and they all occurred while working in Rack. 

### Steps to reproduce
Load this patch:
https://patchstorage.com/mm-realtime-chariots/

Play with it for long, hopefully Rack will crash.

**Comment by AndrewBelt** [comment]
It might be worth getting a stack trace (see https://stackoverflow.com/a/1321103/272642 for instructions) to see whose code is causing the kernel panic. If it's happening in Presonus driver code, send a bug report to Presonus.

**Comment by SaccoSVD** [comment]
Here's the analysis from WinDbg. I hope ´is the correct info (or I need to set something in WinDbg)

I can see only "obs64.,exe" referenced,  but all previous BSODs occurred without OBS running so I rule that one out.

[WinDbg Dump analysis.txt](https://github.com/VCVRack/Rack/files/4412227/WinDbg.Dump.analysis.txt)

**Comment by SaccoSVD** [comment]
One Thing I find interesting is the thread / CPU usage. It makes no sense. :)

With 2 threads audio doesn't dropout, usage is mild. If I enable 4 or more threads the usage seems to come out of nowhere.

![14 threads](https://user-images.githubusercontent.com/30452813/78090185-b590ae00-73c9-11ea-937f-6aa016ce63aa.jpg)
![2 threads](https://user-images.githubusercontent.com/30452813/78090186-b6294480-73c9-11ea-919a-5113222aa804.jpg)

**Comment by SaccoSVD** [comment]
All crashes occurred while using 8 or more threads. Maybe that's the cause.

I just found now 2 threads is the best amount. Never tried before as I though it wasn't gonna be good.

**Comment by AndrewBelt** [comment]
You are correct, obs64.exe (OBS) is the process that caused your kernel crash.

The thread usage is behaving as expected. See https://vcvrack.com/manual/MenuBar#threads.

**Comment by SaccoSVD** [comment]
Ok. I found the problem.

I had CPPC Mask and CPPC Preferred cores disabled on my 3900X

Enabling both cured the issue.

And no, OBS had nothing to do with the BSOD, I already stated that.

I love Rack, and bought almost all extra modules. Great software.

Good day.
