### ISSUE TITLE
Providing an API to enumerate modules

### ISSUE THREAD

**Issue by jcelerier** [VCVRack/Rack#1737]
### Summary
Rationale given in https://github.com/VCVRack/Rack/issues/389#issuecomment-607469076

### Proposed design
Something like passing a callback that would be iterated on all modules would be nice as it would not make allocations nor give access to internal details and allow atomic operation wrt the internal lock. e.g. something such as 

    void Engine::forEachModule(std::function<void(Module&)>& func) {
      if(!func) 
       return;

      VIPLock vipLock(internal->vipMutex);
      std::lock_guard<std::recursive_mutex> lock(internal->mutex);

      for (Module* module : internal->modules) 
        func(*module);
    }

**Comment by jcelerier** [comment]
(can also be C-style `forEachModule(void(*)(void* context, Module&), void* context);` if no `std::` types are to be in the API for a reason or another... but there's already an unused `#include <vector>` in there so...

**Comment by AndrewBelt** [comment]
What do you think about
```cpp
size_t Engine::getNumModules();
void Engine::getModuleIds(int* moduleIds, int len);
std::vector<int> Engine::getModuleIds();
```
If you use the first method, no allocations are needed on your part.
I believe this is enough for you to enumerate modules, process their metadata, and send them over OSC as needed.

**Comment by jcelerier** [comment]
sure, that would be good too but I'm just wondering : (I don't know the codebase at all) - since there is a mutex guarding things, are we assured that it's safe to do : 

```
    auto ids = engine->getModuleIds();
    for(int id : ids) {
        engine->module(id)->doStuff();
    }
``` 
?

as, since there's a mutex protecting internal->module, I'm assuming that there could be changes after the call to `getModuleIds` and before the for loop which would make the module ids invalids. Or is this case safe ? (and won't the mutex locking N time take too much time, if there are, say, 500 modules or so?)

**Comment by AndrewBelt** [comment]
I've reworked the Engine threading model for Rack v2, so now all Engine methods are thread-safe.

Yes, your code snippet will be safe code provided it's in `Module::process()` because modules cannot be added or removed from the Engine simultaneously when modules are processing. However, you will have to wait until Rack v2 releases.
