### ISSUE TITLE
JACK 'virtual port' support in VCVRack MIDI modules

### ISSUE THREAD

**Issue by s-ol** [VCVRack/Rack#1740]
# Summary
When using JACK as the MIDI driver, no JACK MIDI in/output is currently created until a *device* is chosen. However under JACK, it is possible to create unconnected in/outputs, that can be manually connected and routed by JACK users using an application like Catia, qJackctl etc. This allows greater flexibility and routing between software devices independently of the startup order. This is especially frustrating when communicating with another application that treats MIDI the same way as VCVRack currently does: if neither application supports creating an unconnected port, than the applications cannot communicate at all! There needs to be someone to make 'the first move'.

Here there is no port allocated with the device set to `[no device]`:
![image](https://user-images.githubusercontent.com/1731279/78339488-d8bb8900-7594-11ea-81e5-589861951e21.png)

Here the port is connected to a system MIDI input (USB MIDI controller):
![image](https://user-images.githubusercontent.com/1731279/78339792-597a8500-7595-11ea-9476-ba3f82060b67.png)

This is what the proposal should look like. This was achieved by first connecting to the controller, then deleting the connection in qJackCTL. Note that with this hack VCVRack misrepresents the connection state, and a dummy MIDI device is required to make the connection.
![image](https://user-images.githubusercontent.com/1731279/78339917-89c22380-7595-11ea-9f49-d017eb0be659.png)

### Proposed design
Either an unconnected ('virtual input' in RtMidi terms) could be created whenever the `[no device]` option is selected, or an extra 'virtual input' option could be added to the device list, no matter whether any devices are available or not.

**Comment by AndrewBelt** [comment]
JACK is unsupported in Rack but enabled as-is in the RtAudio/RtMidi build (the audio driver wrapper library used by Rack). Anyone is welcome to create a third-party plugin that registers a better JACK audio/MIDI driver with Rack's audio/MIDI API.

**Comment by s-ol** [comment]
@AndrewBelt can I submit a PR for this anyhow? Since you do have JACK specific code in here.

**Comment by s-ol** [comment]
In fact this has nothing to do with JACK, it just happens to be what I use and how I know about this issue.
