### ISSUE TITLE
This project is crashing VCV - replicable

### ISSUE THREAD

**Issue by SaccoSVD** [VCVRack/Rack#1747]
[MM Realtime Chariots 1.46.zip](https://github.com/VCVRack/Rack/files/4458103/MM.Realtime.Chariots.1.46.zip)

### Details

Operating system and version: win10 pro 1909

Rack version (vX.Y.Z): 1.1.6

Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):
3900X - 64GB RAM - 1080ti
Presonus iTwo interface.

### Summary

VCV Crashes recalling or loading this project. I can eventually make it work but is happening 5 out of 10 times.

VCV is set to use 2 threads. Which seems the best option as seen in the Task Manager.

### Steps to reproduce.

- Open the project.
- VCV should crash.
- If VCV didn't crash, close VCV and launch it again.
- VCV should crash.

If you manage to load it, it would be a good chance to load the Piano and Timpani on the VST modules as well as the samples.

I seriously doubt there is a problem on the modules or how the patch is set because when I manage to load the project it works fine, I rather believe I'm reaching the limits on the current VCV 1.1.6 version.

Thank you and have a nice day :)

**Comment by AndrewBelt** [comment]
Please post the log.txt file after the crash like the issue template recommended to do.
I cannot reproduce this, but I don't have any of the VST plugins. Can you specify the names and companies of all VST plugins used in this patch?

**Comment by SaccoSVD** [comment]
Oh, sorry.

Here is the log file.
[log.txt](https://github.com/VCVRack/Rack/files/4458504/log.txt)

The VSTs are both Kontakt 6 and the libs are one grand piano and one timpani, both from Komplete 11

I don't think is related to the plugins, as I said, I can open the project eventually and when it loads fine is rock solid.

I'm looking forward to try the new ASIO implementation and the plugin in the future. Will buy the plugin as soon as is released.

**Comment by AndrewBelt** [comment]
The log file suggests that Rack shut down cleanly. Can you send the log file when Rack crashes?

**Comment by SaccoSVD** [comment]
Here is a fresh log with a crash.

[log.txt](https://github.com/VCVRack/Rack/files/4458620/log.txt)

**Comment by AndrewBelt** [comment]
This is crashing in `PolyScopeDisplay::draw()`. https://library.vcvrack.com/AmalgamatedHarmonics/PolyScope

**Comment by SaccoSVD** [comment]
Hmm... ok I'll remove that one and report the programmer for PolyScope.

Thank you. :)

**Comment by AndrewBelt** [comment]
Comment if issue is discovered to be on VCV's end and I'll reopen.
