### ISSUE TITLE
Helper.py not seeing my "circles" 

### ISSUE THREAD

**Issue by Bill-Bain** [VCVRack/Rack#1754]
when I create a faceplate helper does not find any input / output (etc) circles.  I copied an output from MyModule and it was found. I replicated it and changed its color to red and green and they were found. I changed the size of the circle and it was no longer found.  any thoughts?

**Comment by AndrewBelt** [comment]
Please post the panel so I can reproduce this issue. You may remove the other layers to conceal the panel design if you wish.

**Comment by Bill-Bain** [comment]
someone on facebook posted that they need to be perfect circles and that
would explain the problem

**Comment by AndrewBelt** [comment]
Okay, glad it's resolved.
