### ISSUE TITLE
Cable colors presets

### ISSUE THREAD

**Issue by modman2019** [VCVRack/Rack#1759]
Perhaps even allowing us to select a color using a hotkey command or maybe even a settings feature that applies certain cable colors depending on what the output or input is going to.  Omri Cohen applied a color scheme RED = audio,  BLUE = clock triggers gates. YELLOW voltage oct,  GREEN Modulation.   

Although I also would like to see some other colors taking advantage of computers millions of color possibilities but only utilizing so many at once within a patch.   

Maybe something like a cables settings menu where we have 6 cable possibilities (or the existing 4) and we can assign colors to those from the color wheel matrix.  also with the ability to lock colors to the certain tasks as mentioned above.

**Comment by stoermelder** [comment]
There is a module in SubmarineFree for that, called Wire Manager.
https://github.com/david-c14/SubmarineFree/blob/master/manual/WM.md

**Comment by AndrewBelt** [comment]
There are already several "cable color"-related feature requests and I don't see this feature request offering much anything novel.

**Comment by modman2019** [comment]
Yeah Ill start using that module. thanks Stoermelder.
