### ISSUE TITLE
Work with two screens

### ISSUE THREAD

**Issue by Johnnatannobre** [VCVRack/Rack#1765]

**Comment by AndrewBelt** [comment]
Please fill out the issue template and I'll reopen.

**Comment by Johnnatannobre** [comment]
sorry, I didn't see that it was commented. Thanks!

**Comment by AndrewBelt** [comment]
Okay? I'm not sure what you're requesting.

**Comment by Johnnatannobre** [comment]
I think when I use two screens, the module that is between them should be reorganized between one of the screens.
See that in the image, the delay module is cut in half.

In full screen mode the same happens

**Comment by AndrewBelt** [comment]
Can you maybe draw a diagram of what you think should happen?

**Comment by Johnnatannobre** [comment]
done!

**Comment by AndrewBelt** [comment]
If it did that, scrolling would be discrete instead of smooth, which the user most expects.

**Comment by Johnnatannobre** [comment]
I as a user would like to at least choose, because as shown in the picture, in my case the organization of modules gets bad to use with two screens, but ok thanks.

**Comment by AndrewBelt** [comment]
What you're asking for is impossible. The diagram you drew doesn't show what would happen with multiple rows of modules.

**Comment by Johnnatannobre** [comment]
Consider the same behavior for all lines, if the module is in the middle of the two screens it should be allocated a little more to the right/left or the nearest to the edge of one of the monitors but never being cut in the middle as it occurred.

**Comment by AndrewBelt** [comment]
That would feel extremely clunky. You're welcome to fork Rack and add the feature yourself.
