### ISSUE TITLE
Chords - Microtonal Mode

### ISSUE THREAD

**Issue by z-plane** [VCVRack/Rack#1766]
Not sure on the practicalities of this for the GUI, but would it be possible to have an option to have a mode to support microtonal chords? I imagine this would mean the chord wheel would need to have changeable divisions, however GUI might not like it if you're trying 53EDO...

It would be nice to be able to use this module more accurately to construct microtonal chords.

**Comment by AndrewBelt** [comment]
This is the issue tracker for VCV Rack itself. Email contact@vcvrack.com for feature requests and bug reports for premium VCV products.

You're right that the UI can't really offer something like this without major changes. (e.g. how would the tuning be specified? There's no knob for that.)
For 12-tone tunings, you can pass the 1V/oct signal through https://vcvrack.com/Scalar. But for 53EDO, one option is to attenuate the signal by a factor of 12/53=0.22641509433962265, but of course the display of VCV Chords would not represent a meaningful 53EDO tone.
