### ISSUE TITLE
unable to compile from last version

### ISSUE THREAD

**Issue by HoRaMusic** [VCVRack/Rack#177]
OS (if applicable):win7

I reClone the sources from guthyb to get last features to dev my modules. build plugins that was perfectly working (i test mine and befaco series) give me this error  :

cannot convert'__gnu_cxx::__alloc_traits<std::allocator<rack::Param> >::value_type {aka rack::Param}' to 'float' in initialization

Any idea why?

**Comment by AndrewBelt** [comment]
Here's a list of some API changes between v0.3.2 and the dev branch.
https://github.com/VCVRack/Rack/issues/166

**Comment by rafzael** [comment]
Thank you

**Comment by modlfo** [comment]
Closing because the issue was fixed.
