### ISSUE TITLE
Chords, disable duplicate voltages option

### ISSUE THREAD

**Issue by infamedavid** [VCVRack/Rack#1770]
### Summary

I m using chords beside the host module, hosting Redux vst, Redux is a kind of Sampler/Tracker , it use the CV to control the pitch of  the samples and  with a polyphonic input it work very  well ,  except when it revive the same voltage in different polyphonic channels, when it happens the signal is triggered as duplicated   

here you can see the issue in video

https://youtu.be/dTSN78ImXq0 
 

### Proposed design

it could be solved, adding a option for momentarily disable the channel with  duplicated voltage or allowing disable keys for certain chords 

thanks!

**Comment by AndrewBelt** [comment]
With modular synthesizers, there is no way to turn off a note using just CV. You'll need to use a gate signal to achieve this. If you want VCV Chords to generate a 3-note chord, you can use the following trick. Set the 4th note of a chord to a very low pitch/voltage, such as -5V. Then, use a polyphonic comparator (I'm not sure of the best one, but [Impromptu Part](https://library.vcvrack.com/ImpromptuModular/Part-Gate-Split) should work.) to enable a gate signal only when the note is higher than -5V. Then, send this gate signal to the gate input of VCV Host.

This is the issue tracker for VCV Rack itself. Email contact@vcvrack.com for feature requests and bug reports for commercial VCV products. I'll close this issue, so if you have any further questions, reply to that email address.
