### ISSUE TITLE
Unsubscribing from modules doesnt remove them from VCV

### ISSUE THREAD

**Issue by modman2019** [VCVRack/Rack#1776]
Windows PC. 
I went to the new library site and clicked Unsubscribe (sorry Frozen Wasteland) and the modules are still in VCV.

**Comment by Petervos2018** [comment]
You need to remove the folder from the plugins-v1 folder yourself in order to definitely remove a (set of) modules.

**Comment by modman2019** [comment]
Thanks for the tip

**Comment by AndrewBelt** [comment]
This is solved with https://github.com/VCVRack/Rack/issues/1619

For Rack v1, see the VCV Library Instructions at https://library.vcvrack.com/
