### ISSUE TITLE
createLight & lights[] cause Rack to crash with no log

### ISSUE THREAD

**Issue by mikeallisonJS** [VCVRack/Rack#1777]
### Details
Win 10, Msys2 Mingw 64, gcc v.9.3
Rack & SDK v.1.1.6
Built with both, crashes exactly the same in both

### Summary
Created a VCO, works great, but I've attempted adding lights. as soon as I set the lights in the module or add the createLight child.. boom, instant crash, 

Created with helper.py, even trimmed the project down to the bare minimum files for the VCO.

### Steps to reproduce
`enum LightIds {
	MODE_LIGHT,
	NUM_LIGHTS
};`	
add:
`lights[MODE_LIGHT].value = (hardTune);`
to process()

and/or:
`addChild(createLight<MediumLight<GreenLight>>(Vec(64.4f, 81.4f), module, VCO::MODE_LIGHT));`
to the Widget struct

**Comment by stoermelder** [comment]
Please post the full code or a link to your repository. Also, the correct usage in Rack v1 is `lights[MODE_LIGHT].setBrightness((hardTune))` or `lights[MODE_LIGHT].setBrightnessSmooth((hardTune), args.sampleTime)`.

**Comment by AndrewBelt** [comment]
Cannot reproduce. Your code is how you should normally use lights, and of course they work in normal use.
