### ISSUE TITLE
cannot get my modules or befaco in th elist

### ISSUE THREAD

**Issue by rafzael** [VCVRack/Rack#178]
OS (if applicable): win7
Version (or "dev" if compiling from source): last dev version

I modfy my code to be worj-king with the last dev version, now my plugins build correctly but dosn't appear in the modules list. I change my hpp et cpp files like this:

**#include "Treasure.hpp"
Plugin *plugin;
void init(rack::Plugin *p) {
    plugin = p;
    plugin->slug = _"Treasure";_
	plugin->name = "Treasure";
    createModel<FrequencyDividerWidget>(plugin, "FrequencyDivider", "FrequencyDivider");
    createModel<HiHatWidget>(plugin, "HiHat", "HiHat");
    createModel<BassDrumWidget>(plugin, "BassDrum", "BassDrum");
    createModel<SnareDrumWidget>(plugin, "SnareDrum", "SnareDrum");
    createModel<HandClapWidget>(plugin, "HandClap", "HandClap");

}**

**#include "rack.hpp"
using namespace rack;
extern Plugin *plugin;

struct FrequencyDividerWidget : ModuleWidget {
	FrequencyDividerWidget();
};
struct HiHatWidget : ModuleWidget {
	HiHatWidget();
};

struct BassDrumWidget : ModuleWidget {
	BassDrumWidget();
};
struct SnareDrumWidget : ModuleWidget {
	SnareDrumWidget();
};
struct HandClapWidget : ModuleWidget {
	HandClapWidget();
	Menu *createContextMenu();
};**

I also change some code in my plugins for widget and module like this:

**HandClapWidget::HandClapWidget() {
	HandClap *module = new HandClap();
	setModule(module);
	box.size = Vec(15*8, 380);

	{
		SVGPanel *panel = new SVGPanel();
		panel->box.size = box.size;
		panel->setBackground(SVG::load(assetPlugin(plugin, "res/HandClap.svg")));
		addChild(panel);
	}**

**HandClap() : Module(NUM_PARAMS, NUM_INPUTS, NUM_OUTPUTS) {}**

Thanks

**Comment by AndrewBelt** [comment]
You can paste code by surrounding it with ```.

What does the terminal in Rack say after "Failed to load plugin"?

**Comment by rafzael** [comment]
It says nothing, the problem is that the plugins doesn't appear in the new sub menu system. I can choose a module from core or fundamental but no treasure(name of my plugins series) menu appears.

**Comment by AndrewBelt** [comment]
Does it say "Loaded plugin ... Treasure"? If not, is the plugin.* file at `plugins/Treasure/plugin.*`?

**Comment by rafzael** [comment]
Ho sorry it says this when runmake the rack : 

Failed to load library ./plugins/Treasure/plugin.dll: 126
Loaded font ./res/DejaVuSans.ttf

**Comment by rafzael** [comment]
what is this "DejaVuSans.tff" file? do I need to add this to the res file of my plugins ?

**Comment by rafzael** [comment]
By checking once more I than I get this error message when i build the plugins 

g++ -o plugin.dll build/src/Treasure.cpp.o build/src/HiHat.cpp.o build/src/BassDrum.cpp.o build/src/SnareDrum.cpp.o build/src/FrequencyDivider.cpp.o build/src/HandClap.cpp.o build/pffft/pffft.c.o -shared -L../../ -lRack
build/src/HandClap.cpp.o:HandClap.cpp:(.rdata$.refptr._ZTV14HandClapWidget[.refptr._ZTV14HandClapWidget]+0x0): undefined reference to `vtable for HandClapWidget'
build/src/HandClap.cpp.o:HandClap.cpp:(.rdata$.refptr._ZTT14HandClapWidget[.refptr._ZTT14HandClapWidget]+0x0): undefined reference to `VTT for HandClapWidget'
collect2.exe: error: ld returned 1 exit status
make: *** [../../compile.mk:38: plugin.dll] Error 1

**Comment by AndrewBelt** [comment]
That's the font Rack uses. No, you don't need to add it.

Ah, yes, that's the reason. ^

**Comment by rafzael** [comment]
Ok it sounded strange to me because do not use the font for my modules.

**Comment by rafzael** [comment]
Ok it works, sorry for time wasting and thank you

**Comment by AndrewBelt** [comment]
Great!
