### ISSUE TITLE
Error message: "Could not query updates"

### ISSUE THREAD

**Issue by anlexmatos** [VCVRack/Rack#1782]
### Details

Operating system and version: Windows 7
Rack version (vX.Y.Z): 1.1.6

### Summary
Under the Library menu, the message "Could not query updates" is displayed at the bottom. I am not sure when this started happening; judging by Date Modified in my Rack/plugins-v1 folder, the last update I received was for the Frozen Wasteland plugin on May 3. As far as I am aware, there has been no change to my internet connection or local network.

![couldnotquery](https://user-images.githubusercontent.com/12039110/82610960-69721680-9b8d-11ea-80d9-90ab16a2302a.PNG)

**Comment by anlexmatos** [comment]
The only unusual line in the log file is this one after app initialization:

```
[0.208 info src/main.cpp:171] Initializing app
[0.408 warn src/plugin.cpp:322] Request for user's plugins returned an error: Token was not given or is invalid
```

**Comment by AndrewBelt** [comment]
Could you try logging out and back in again?

**Comment by anlexmatos** [comment]
That did the trick.
