### ISSUE TITLE
100% CPU usage Ubuntu Studio 20.04

### ISSUE THREAD

**Issue by ciliehub** [VCVRack/Rack#1787]
### Details

Operating system and version: Ubuntu Studio 20.04
Rack version (vX.Y.Z): 1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): Intel i7 type laptop with NVIDIA GTX 860M, built-in audio.

### Summary

After installing Ubuntu Studio 20.04, and without altering anything of its settings or configuration, VCV Racks CPU usage is 100% when using 1 thread, 200% using 2 threads etc. Also, Realtime Mode crashes VCV

### Steps to reproduce

Install Ubuntu Studio 20.04. Unzip/install VCV Rack. Start Jack. Start Rack.

**Comment by stoermelder** [comment]
Did you select an audio device in the Audio module?

**Comment by ciliehub** [comment]
Yes, jack, and then the HW device which points to my built-in soundcard. But in the end, alsa or jack makes no difference in CPU usage

**Comment by AndrewBelt** [comment]
There are several duplicates of "soft" issues like these. Closing.
