### ISSUE TITLE
New Install Windows 7 Initial Run Crash

### ISSUE THREAD

**Issue by en2393** [VCVRack/Rack#1789]
### Details

Operating system and version: Windows 7
Rack version (vX.Y.Z) :v1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):
Graphic:Mobile Intel(R) 965 Express Chipset
CPU:Intel(R) Pentium(R) Dual CPU T2390 @1.86Ghz

### Summary

Initial Install Run Crash

### Steps to reproduce

[log.txt](https://github.com/VCVRack/Rack/files/4717638/log.txt)

**Comment by stoermelder** [comment]
Your processor is from 2008 and almost 13 years old. Please check the system requirements for running VCV Rack:
https://vcvrack.com/manual/Installing#system-requirements

**Comment by en2393** [comment]
Thanks
