### ISSUE TITLE
Multi-threading does not seem to allow more modules, AMD Ryzen 9 3900X, Linux

### ISSUE THREAD

**Issue by gwatcha** [VCVRack/Rack#1795]
### Details

Operating system and version: Manjaro Linux, Kernel: 5.6.15-1
Rack version (vX.Y.Z): 1.1.6

Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): 
AMD Ryzen 9 3900X, Scarlett 2i2

Here is a picture of my JACK config and the log output
![image](https://user-images.githubusercontent.com/31526638/84607255-1aa05f80-ae61-11ea-9cc3-6232cd1a4a72.png)

Here's a snippet from the log
```
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = VCV Rack was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:04:37.232 XRUN callback (12 skipped).
JackEngine::XRun: client = VCV Rack was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
... continues at like 10/second
```

### Summary
When the engine is set to run with one thread, it runs pretty well. When I enable multiple threads the performance seems to go down. By performance decreasing, I mean the rate of 'VCV Rack was not finished' messages from JACK increases as well as increased clipping sounds. 

I have tried using ALSA instead of JACK
I have tried increasing the buffer.

Here's a video: https://imgur.com/a/aK79Owd
Unfortunately the audio didn't record, but each one of those messages come with an audio distortion / gap / clipping

### Steps to reproduce

Load up modules until VCV Rack running on 1 threads hits it's limit. 
Increase number of threads.
Hear more distortion then before.

**Comment by gwatcha** [comment]
I installed windows and there is no such issue.

**Comment by infamedavid** [comment]
same issue here Xubuntu 18 04
AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx

**Comment by gwatcha** [comment]
It works with realtime checked on! yay i can vcv rack again
