### ISSUE TITLE
Host FX: generic UI for plugins that dont have their own

### ISSUE THREAD

**Issue by persywho** [VCVRack/Rack#1796]
Basic UI control window in Host FX for plugins such as Airwindows which do not have their own UI and rely on the host software to provide the UI controls. As is you cannot click the UI button on Host FX to display a parameter UI. this would allow a generic UI interface.

simple sliders with parameter labels similar to other DAWS like reaper, renoise, ect.

**Comment by AndrewBelt** [comment]
This is the issue tracker for VCV Rack itself. Email contact@vcvrack.com for feature requests and bug reports for premium VCV products.
