### ISSUE TITLE
dsp::timer time does not scale with args.sampletime as expected

### ISSUE THREAD

**Issue by ValleyAudio** [VCVRack/Rack#1799]
dsp::Timer does not update for the expected length of time when supplying args.sampleTime as an argument to dsp::Timer.process(). If I want to use it to have an event occur after 1 second, I'm correct in doing this?:

```
// In module definition
dsp::Timer myTimer;

// In process function

myTimer.process(args.sampleTime);
if (myTimer.time >= 1.f) {
    // do something
    myTimer.reset();
}
```

This does not run for the expected 1 second when using sample rates higher than 44.1 kHz, but instead runs slower and scales with sample rate, i.e. at 88.2 kHz it takes dsp::timer 2 seconds to reach 1.f, and at 176.4 kHz it takes 4 seconds.

Is process() running at 44.1 kHz regardless of the engine sample rate, or am I just doing something dumb? I have got an Audio 8 module in my patch with a valid sound card selected (Gen 1 Focusrite Scarlett 18i20).

**Comment by AndrewBelt** [comment]
That is the correct usage, but since `Time::process()` returns the time, you could write it as
```cpp
if (myTimer.process(args.sampleTime) >= 1.f) {
    myTimer.reset();
}
```

The definition of `Timer` is trivial, so it is not the problem.
At 88.2 kHz, can you confirm that `args.sampleTime` is equal to `1/88.2e3`? If not, have you set Rack's engine sample rate to 88.2 kHz and not just VCV Audio's?

**Comment by ValleyAudio** [comment]
Cheers for the tip. I can confirm that the sampleTime is the expected value, and no I'm not changing Audio 8 sample rate, but just the engine rate. Changing Audio 8 samplerate has no effect as expected.

**Comment by AndrewBelt** [comment]
In that case, I don't know. Not enough information to identify the problem.

**Comment by ValleyAudio** [comment]
@AndrewBelt Actually I think the issue is computing power and sound card related, as when testing on other computers the issue does not appear until higher samplerates, e.g 192 kHz where dropouts occur, which then must cause timing to go out of sync and timers appear to slow down. Does this sound right to you?

**Comment by AndrewBelt** [comment]
I'm not sure. If Rack is able to play the patch without missing the audio buffer deadlines, and if VCV Audio is set to 44.1 kHz and Rack's engine to 192 kHz, then your module's `process()` method will be called 192e3 times a second as expected.
