### ISSUE TITLE
Rack fails to open instead giving an error message 

### ISSUE THREAD

**Issue by MylesDeacon** [VCVRack/Rack#18]
I'm sure this is probably something I'm doing wrong but just in case...
Every time I open the application I get an error message titled 'MinGW Runtime Assertion'

It reads:

Program: C:\ Program Files (x86)\Rack\Rack.exe
File: src/gui.cpp, line 233

Expression: window

[End of message]

I can Abort, Retry or Ignore. Retry and Ignore ends with a runtime error of its own and Abort just, well aborts the programme...

I've tried downloading the files a couple of times and opening it from different parts of the drive but the issue persists.

**Comment by QrchackOfficial** [comment]
Related method:

```cpp
void guiInit() {
	int err;

	// Set up GLFW
	glfwSetErrorCallback(errorCallback);
	err = glfwInit();
	assert(err);

	glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 2);
	glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 0);
	// glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
	// glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2);
	// glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
	// glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
	glfwWindowHint(GLFW_MAXIMIZED, GLFW_TRUE);
	std::string title = gApplicationName + " " + gApplicationVersion;
	window = glfwCreateWindow(1000, 750, title.c_str(), NULL, NULL);
	assert(window);
}
```

It fails on `assert(window)`

**Comment by AndrewBelt** [comment]
@QrchackOfficial is right. Are you able to run OpenGL 2.1 applications or higher? I'm not aware of any tools on Windows to test this, but if you can't play 3D video games, that would be a sign.

I'll close this issue when I add a more informative error message.

**Comment by davesamuels** [comment]
Same issue here.

I used [GLEW](http://glew.sourceforge.net/) to test which OpenGL extensions my system supports - it says everything up to OpenGL 3.0 (and some random bits beyond) are all working.

**Comment by MylesDeacon** [comment]
@davesamuels @AndrewBelt 
Yes that's got it working!

Ok, opening it on my laptop's built in screen worked because I can use the high performance GPU but when I'm using a dock and two external monitors I have to use the integrated GPU, thanks to a Windows 10 update last year. I know of other people who have this problem so you might want to include it as a work around in your error message. 

Thanks guys!

**Comment by sambeard** [comment]
hi,
i'm getting the same error however for a different file/ funcion:

error message reads :

Title: MinGW Runtime assertion
Content:
"
Assertion Failed! 
Program c:\program files\vcv\rack\rack.exe
File: src/asset.cpp line 69
"
any ideas how to fix this? 
working with a dell laptop with intel intergrated graphics (520 or 620 not sure)

**Comment by AndrewBelt** [comment]
Closing as possibly obsolete.
