### ISSUE TITLE
Undo last command option?

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/Rack#180]
OS (if applicable):
Version (or "dev" if compiling from source): dev

I accidentally deleted a Mixer with lots of wires connected and had to reconnect everything...
Would an "Undo last command" (or last X commands) or simply "Undo Delete" be useful in your opinion?

**Comment by antoniograzioli** [comment]
ooops sorry I believe it's a duplicate of https://github.com/VCVRack/Rack/issues/153

**Comment by AndrewBelt** [comment]
Duplicate of #153  Requires a restructure of how the main thread (UI thread) interacts with the audio engine thread. It would make the code a lot cleaner and fault tolerant, and would allow for a headless Rack to exist via a future libRack library. The engine thread could even exist on it's own process.
