### ISSUE TITLE
FrequencyDomain plugin not downloading/installing correctly

### ISSUE THREAD

**Issue by danhphotos** [VCVRack/Rack#1803]
As of today June 23 FrequencyDomain plugin v 1.6.0 is not updating, although the red light in the VCV Library menu says an update is available. After updating via Library menu and restarting VCV, the red light is still on in the Library menu, Frequency Domain still shows up in the Library menu, the dates on the files in my plugins-v1/FrequencyDomain folders have been updated to today, but none of the FrequencyDomain modules appear in the browser, and even FrequencyDomain name is missing from Brands in the browser. Loading existing patches that use these modules fails with the standard error message:

     Could not find module "FreudianSlip" of plugin "FrequencyDomain"

I am using Windows 10, FrequencyDomain plugin has been working fine up until today, other plugins appear fine, I have changed nothing else in my system, and this happens repeatedly. 

I also exited Rack, deleted FrequencyDomain files & folders in my plugins-v1/FrequencyDomain folder, restarted VCV, still no FrequencyDomain modules in VCV, but the files have re-appeared in my plugins-v1/FrequencyDomain folder.
I emailed developer, he replied it is a VCV issue and to file an issue with Andrew.

**Comment by AndrewBelt** [comment]
This is the issue tracker for VCV Rack. For VCV Library support, email VCV with the contact information at https://vcvrack.com/support.
