### ISSUE TITLE
"audio interface supporting CV signals (coming soon)"question

### ISSUE THREAD

**Issue by inubata** [VCVRack/Rack#181]
Hi,

I saw the word "audio interface supporting CV signals (coming soon)".
As a user of the Softube modular, I tested the CV signal control using the audio interface loopback.
There is no problem with the gate signal.
But the 1V/oct signal is mysterious.

Test results

Softube Modular to VCV Rack
Softube Modular :C4 D4 E4 F4 G4
VCV Rack:B2 D#3 G3 A3 C#4

VCV Rack to Softube Modular
VCV Rack:C3 D3 E3 F3 G3
Softube Modular:C1 E1 G#1 A#1 D2

Is this because VCV Rack is not completed?
Since I don't have hardware, I do not know whether Softube Modular is correct.
I hope to be able to control from VCV Rack to Softube Modular or from Softube Modular to VCV Rack with CV signal in the future.

**Comment by AndrewBelt** [comment]
How are you converting voltage to pitch? An oscillator? What oscillator are you using?

**Comment by inubata** [comment]
Softube Modular to VCV Rack
Softube Modular:MIDI to CV module Note Outputs>AUX OUTPUT(BLOCK DC ON AUX OUT On)
Audio interface analog outputs (internal loopback).
VCV Rack:Audio device module inputs>Fundamental VCO module V/OCT(Default value)

VCV Rack to Softube Modular
VCV Rack:MIDI device 1V/oct Outputs>Audio device module Outputs
Audio interface analog inputs (internal loopback).
Softube Modular:INPUTS>A-110 VCO module CV1 inputs(Default value)

Values are different even if you look at VCV Rack SCOPE module .

**Comment by AndrewBelt** [comment]
>Values are different even if you look at VCV Rack SCOPE module .

This is what you should be comparing, not oscillator offsets, since there is no standard in Eurorack what pitch an oscillator should play with its knob at the "default value". (What does that mean anyway?)

What is the scaling and offset between Softube Modular and VCV Rack? Testing 0V and 1V should suffice.

**Comment by jpshea** [comment]
https://learningmodular.com/matching-octaves-in-your-modular/

**Comment by AndrewBelt** [comment]
^ Haha, that's a good source for my claim "there is no standard in Eurorack."

My only concern here is really just the scaling of the voltages. Both Softube Modular and VCV Rack map 0V to the value 0.0 on an audio interface, but it might differ how 1V would map. Should you expect it to map [-10V, 10V] to the range [-1.0, 1.0], or [-5V, 5V], or [-12V, 12V]? Those are pretty much the only reasonable options.

Rack v0.3.2 maps [-5V, 5V] to the full range, but I've given it more headroom in Rack dev (future v0.4.0) to cover [-10V, 10V] instead.

**Comment by inubata** [comment]
Thanks for the answer AndrewBelt & jpshea.

Ok, I'm sorry.
I didn't understand the world of Eurorack modules.
Apparently, Softube Modular seems to require the keyboard to double.
And 2 octave higher(Voltage for MIDI Note 60 at 2V?).

There seems to be no problem with VCV Rack.
It is a great software.


> Rack v0.3.2 maps [-5V, 5V] to the full range, but I've given it more headroom in Rack dev (future v0.4.0) to use [-10V, 10V] instead.

I am looking forward to it.

**Comment by AndrewBelt** [comment]
This issue is old and likely obsolete. Comment if issue is still present. Closing.
