### ISSUE TITLE
please add 32 khz sample rate as well

### ISSUE THREAD

**Issue by hexdump0815** [VCVRack/Rack#1812]
### Summary

please add 32 khz sample rate as well

### Proposed design

add 32khz to the existing sample rates in vcvrack 2.0, as according to https://community.vcvrack.com/t/rack-development-blog/5864/54 22.05 khz and 24 khz have been added at the lower end but not 32 khz - it is a very common sample rate as well, has (at least for adult people) still a very good frequency range up to around 15 khz and reduces the cpu usage of vcvrack quite a bit compared to 44.1 khz ... i'm using it for quite a while in my sonaremin project and did not see any negative side effects and it allows larger patches due to the reduced cpu usage.

i guess adding it should be very simple.

a lot of thanks in advance and best wishes - hexdump

**Comment by AndrewBelt** [comment]
32 kHz isn't a power of two factor of 48 or 44.1 kHz, so it shouldn't be added to the sample rate. However, you can change the sample rate manually in `settings.json`.
