### ISSUE TITLE
Audio-16 using ReaRoute (ASIO) + Audio-8 using Headset (WASAPI) crashes when removing Audio-16

### ISSUE THREAD

**Issue by bret-2600** [VCVRack/Rack#1813]
### Details

Operating system and version: 10.0.18362 Build 18362
Rack version (vX.Y.Z): v1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): none

### Summary

When using both an Audio-16 using ReaRack plus an Audio-8 using a headset, VCV Rack crashes when removing the Audio-16 or when shutting down.

### Steps to reproduce
1. Open a clean VCV Rack patch
2. Add an Audio-16 to the patch using the ASIO driver and selecting ReaRoute as the device
3. Add an Audio-8 to the patch using WASAPI as the driver and a select a headset device (this may be different for you)
4. Attempt to delete the Audio-16 or close rack.  It should crash.  

My log (also attached in full) shows the last line as: `[156.434 info src/audio.cpp:302] Stopping RtAudio stream 0`
Full log file: [log.txt](https://github.com/VCVRack/Rack/files/4870799/log.txt)

![image](https://user-images.githubusercontent.com/19557854/86488875-4a7fac00-bd17-11ea-9627-9a9ee128b01f.png)

Thanks!
Bret

**Comment by AndrewBelt** [comment]
Multiple audio devices is not supported in Rack v1.
