### ISSUE TITLE
Asio Problem

### ISSUE THREAD

**Issue by rizacab2001** [VCVRack/Rack#1814]
Whenever I select an asio driver.( Asio scope, aio4all. vb.) It crashes
-->

### Details

Operating system and version:. Windows7wheneevere
Rack version (1.1.6):
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):
Soniccore  Scope card

**Comment by AndrewBelt** [comment]
No steps to reproduce the issue.

**Comment by rizacab2001** [comment]
> No steps to reproduce the issue, closing.

If you don't have  my system how you can reproduce?. When you try to select asio driver, it freeses.
