### ISSUE TITLE
modules[].manualUrl are being ignored by Rack and library

### ISSUE THREAD

**Issue by Kautenja** [VCVRack/Rack#1817]
### Details

Operating system and version: MacOS 10.14, Ubuntu 19.04
Rack version (vX.Y.Z): v1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): NA

### Summary

The plugin.json schema allows for individual [module manual URLs](https://vcvrack.com/manual/Manifest#modules-manualurl) in addition to, or in replacement of, a plugin manual. For instance, the JSON snippet below describes a plugin that has no plugin manual, but does have a manual for the module(s) in the plugin. When this is the case, one would expect two things two occur for two separate use cases related to Rack:

1. the manual URL for the individual modules is displayed on the VCV Rack library website where the URL for a plugin-level module would be, and
2. Rack host shows the "Manual" context menu when a module in the plugin is right clicked that redirects to the module's manual.

Neither of these two expectations appear to be upheld by the current version of Rack / Rack library.

```json
{
  "slug": "KautenjaDSP-PotatoChips",
  "version": "1.2.1",
  "license": "GPL-3.0-or-later",
  "name": "KautenjaDSP Potato Chips",
  "brand": "KautenjaDSP",
  "author": "Christian Kauten",
  "authorEmail": "KautenjaDSP@gmail.com",
  "authorUrl": "https://kautenja.github.io/",
  "sourceUrl": "https://github.com/Kautenja/PotatoChips",
  "changelogUrl": "https://github.com/Kautenja/PotatoChips/blob/master/CHANGELOG.md",
  "modules": [
    {
      "slug": "2A03",
      "name": "2A03",
      "description": "An emulation of the Ricoh 2A03 audio processing unit.",
      "manualUrl": "https://github.com/Kautenja/PotatoChips/releases/download/1.2.0/2A03.pdf",
      "tags": [
        "Oscillator",
        "Noise"
      ]
    },
...
```

### Steps to reproduce

1. https://library.vcvrack.com/KautenjaDSP-PotatoChips/2A03 exhibits the first issue for the KautenjaDSP-PotatoChips plugin at version 1.2.1 on the VCV rack library. Although `modules[].manualUrl` are specified in the plugin.json, they are not shown on the library pages for the modules in the plugin. (the plugin.json is the same as is pasted above, but with data for the additional modules in the plugin).

2. To reproduce the second issue, KautenjaDSP-PotatoChips may be cloned from https://github.com/Kautenja/PotatoChips. The problem should be version dependent for the plugin, but checkout tag 1.2.1 just for the sake of consistency. Placing a module and right clicking is all that is necessary to confirm that there is no "Manual" context to click, despite one being specified in the plugin.json

### N.B.

It is worth noting that when I do add a plugin-level manual URL to KautenjaDSP-PotatoChips plugin.json, all modules within Rack use this plugin-level manual URL for their context menu and ignore the module-specific URLs. I don't have a development branch of Rack library up and running to test how adding the plugin-level manual affects that side of the issue.

**Comment by AndrewBelt** [comment]
Fixed for the VCV Library. It was not displaying because of a bug. The logic was basically
```
if plugin.manualUrl
    show link to module.manualUrl if it exists, otherwise plugin.manualUrl
```
As you can see, if `plugin.manualUrl` doesn't exist, it wouldn't show the module manual. This has been fixed.

`modules[].manualUrl` was added after the latest version of Rack v1. There will be no more versions of v1, but Rack v2 correctly displays the module manual.
