### ISSUE TITLE
Chang tag / classifier to be hierarchical

### ISSUE THREAD

**Issue by Kautenja** [VCVRack/Rack#1820]
### Summary

In PyPy, tags (classifiers) are hierarchical to support nuanced classification schemes. For instance, a project has a development status that sub classifies into 7 categories based on the quality of the development status. This hierarchical classification scheme is notated using C++ namespace notation (dual colon delimiter):

```
Development Status :: 1 - Planning   
Development Status :: 2 - Pre-Alpha   
Development Status :: 3 - Alpha   
Development Status :: 4 - Beta   
Development Status :: 5 - Production/Stable   
Development Status :: 6 - Mature   
Development Status :: 7 - Inactive  
```

### Proposed design

In the context of VCV Rack, some of the current tags have potential subclassifications that could be useful. For instance, an oscillator can be a wavetable oscillator, an additive oscillator, a subtractive oscillator, etc. The table below describes how the syntax might look for this example. Some additional conceptual modeling would be necessary to identify all of the appropriate sub-classifications for current tags.

```shell
Oscillator :: Wavetable
Oscillator :: Additive
Oscillator :: Subtractive
```

This would be useful for searching when someone wants to search, for instance "Additive" or "Wavetable", to find those specific kinds of oscillators. Currently authors have to place those keywords in the description of their modules for search-ability which produces an inconsistent search experience for the end-user in these cases.

**Comment by AndrewBelt** [comment]
Anything more specific than "oscillator" is too approximate for tags and should go in the description, where you have full flexibility.
