### ISSUE TITLE
Linux: Conform to $XDG standard and use ~/.config/Rack over the legacy ~/.Rack 

### ISSUE THREAD

**Issue by mxa** [VCVRack/Rack#1821]
Current applications should store
Config files in `$XDG_CONFIG_HOME` (if it is not set, default to: `~/.config`)
Data in `$XDG_DATA_HOME` (if it is not set, default to: `~/.local/share`)
Temp/Non-Essential files in `$XDG_CACHE_HOME` (if it is not set, default to: `~/.cache`).
according to https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by AndrewBelt** [comment]
`~./Rack/` is fine for the default user folder. Easy to type and access.

**Comment by mxa** [comment]
Additionally this would also allow to separate user settings from user data.

[A blog post regarding the issue](https://ploum.net/207-modify-your-application-to-use-xdg-folders/)

**Comment by ycollet** [comment]
I vote for this one. If somebody propose a pull request, will it be OK for you  @AndrewBelt  ?
