### ISSUE TITLE
Unable to run in MacOs version 10.7.5

### ISSUE THREAD

**Issue by cmayorga** [VCVRack/Rack#1823]
I am getting this error when try tu run:

[1.710 info src/main.cpp:171] Initializing app
[1.734 info src/bridge.cpp:384] Bridge server started
[7.833 fatal src/main.cpp:45] Fatal signal 6. Stack trace:
21: 1   Rack                                0x0000000101c4d3cd _ZL18fatalSignalHandleri + 45
20: 2   libsystem_c.dylib                   0x00007fff8cc56cfa _sigtramp + 26
19: 3   ???                                 0x0000000000000001 0x0 + 1
18: 4   libsystem_c.dylib                   0x00007fff8cbf5a7a abort + 143
17: 5   libc++abi.dylib                     0x00007fff8e9417bc abort_message + 214
16: 6   libc++abi.dylib                     0x00007fff8e93efcf _Z17default_terminatev + 28
15: 7   libobjc.A.dylib                     0x00007fff8ee981b9 _objc_terminate + 94
14: 8   libc++abi.dylib                     0x00007fff8e93f001 _Z19safe_handler_callerPFvvE + 11
13: 9   libc++abi.dylib                     0x00007fff8e93f05c __cxa_bad_typeid + 0
12: 10  libc++abi.dylib                     0x00007fff8e940152 _Z23__gxx_exception_cleanup19_Unwind_Reason_CodeP17_Unwind_Exception + 0
11: 11  libobjc.A.dylib                     0x00007fff8ee97e7a _objc_exception_destructor + 0
10: 12  CoreFoundation                      0x00007fff85d441be -[NSObject doesNotRecognizeSelector:] + 190
9: 13  CoreFoundation                      0x00007fff85ca4e23 ___forwarding___ + 371
8: 14  CoreFoundation                      0x00007fff85ca4c38 _CF_forwarding_prep_0 + 232
7: 15  Rack                                0x0000000101d277d8 _glfwCreateContextNSGL + 1352
6: 16  Rack                                0x0000000101d245b5 _glfwPlatformCreateWindow + 1413
5: 17  Rack                                0x0000000101d1d7ef glfwCreateWindow + 495
4: 18  Rack                                0x0000000101c6434d _ZN4rack6WindowC2Ev + 333
3: 19  Rack                                0x0000000101c28ebb _ZN4rack3App4initEv + 203
2: 20  Rack                                0x0000000101c4cd8e main + 1070
1: 21  Rack                                0x0000000101be6034 start + 52
0: 22  ???                                 0x0000000000000001 0x0 + 1

**Comment by AndrewBelt** [comment]
Template not filled out, closing.
