### ISSUE TITLE
Big delay on output

### ISSUE THREAD

**Issue by titos-carrasco** [VCVRack/Rack#1825]
Linux Debian Testing
Rack 1.1.6
FX12 mixer with USB (4 channels in/out) as system
AM240 mixer with behringer UCA200 via alsa_in
Skrylar Jack audio (8 JACK-> RACK, 8 RACK-JACK)
VCV Recorder

After recording a mpg file, any sound from the external mixers get delayed from Rack to jackd

See the gif: the scope is inside Rack, the analyzer is outside Rack

Before recording, all is normal

![delay](https://user-images.githubusercontent.com/4842986/88593121-15702c00-d02d-11ea-85f1-ab12a27b10e9.gif)

**Comment by titos-carrasco** [comment]
I detect the problem in the @Skrylar Jack Output mode. When the delay appears i remove the output module and insert it again..:-)

**Comment by AndrewBelt** [comment]
This is an issue with a plugin for VCV Rack, not Rack itself. Report the issue in the corresponding plugin's support channel.
