### ISSUE TITLE
Rack segfaults after some time when using Skrylar Jack

### ISSUE THREAD

**Issue by titos-carrasco** [VCVRack/Rack#1826]
Linux Debian Testing
FX12 mixer with USB (4 ports) interface
AM240 mixer with Behringer UCA200 USB (2 ports) interface
Jackd running
Chrome running

Crash crash unexpectedly (at least once in a day)

```
$ sudo dmesg | grep Rack
[ 1389.753916] Rack[5517]: segfault at 7fac968f17e0 ip 00007facbcd7a730 sp 00007fac96852d30 error 4 in libgcc_s.so.1[7facbcd6e000+11000]
```

On restart, there are missing cable connections

![VCV Rack](https://user-images.githubusercontent.com/4842986/88826536-de1d8e80-d196-11ea-803d-bd3535e78826.png)

[log.txt](https://github.com/VCVRack/Rack/files/4996133/log.txt)

**Comment by AndrewBelt** [comment]
Bug report looks good, but
- Use a descriptive title that best explains the bug in one sentence.
- Surround code and terminal output with ``` on separate lines.
- "Testing" is a moving target version. Specify the exact version of your distro.

**Comment by stoermelder** [comment]
I don’t see any „Audio“ module as you are using Jack. Is running Rack without audio driver for synchronization even supported?

**Comment by titos-carrasco** [comment]
> Bug report looks good, but
> 
> * Use a descriptive title that best explains the bug in one sentence.
> * Surround code and terminal output with ``` on separate lines.
> * "Testing" is a moving target version. Specify the exact version of your distro.

- Unexpectdly is the best word that define what happened. Screensaver running, i move the mouse and a Rack show a message for the crash
- Debian Bullseye: Linux Titos-Notebook 5.7.0-1-amd64 #1 SMP Debian 5.7.6-1 (2020-06-24) x86_64 GNU/Linux¨

**Comment by titos-carrasco** [comment]
> I don’t see any „Audio“ module as you are using Jack. Is running Rack v1 without audio driver for synchronization even supported?
I'm using Skrylar Jack Audio

![MyConfig](https://user-images.githubusercontent.com/4842986/88842571-ae2db580-d1ad-11ea-96e9-9de331254fdb.png)

**Comment by titos-carrasco** [comment]
The problem is the @Skrylar Jack output module...
