### ISSUE TITLE
Modify VCV Audio 8 to create a jackd client with selectable number of ports

### ISSUE THREAD

**Issue by titos-carrasco** [VCVRack/Rack#1827]
I' working in Linux with Jackd and 2 USB audio interfaces, the 1st one is a FX12 mixer as the jackd device, the 2nd via alsa_in. All works like a charm

In Rack (VCV Audio 8 module) I have to choose one of the device not both. Whatever I choose, Rack create a client in jack with the same number of ports of the device selected 

To work in Rack using both devices I have to run x42-matrixmixer8x8  (Linux) and choose that in Rack, getting 8 input/output ports. Then, in qjackctl, I connect the devices (x42-matrixmixer8x8 is not used) needed

So, why not modify audio 8 module to just choose (with jack audio driver selected) the number of ports for the client?

![Rack](https://user-images.githubusercontent.com/4842986/88875174-c96ce500-d1ee-11ea-9dc5-b4f502c43af3.png)

See Skrylar Jack Audio Input/Output as an example

**Comment by AndrewBelt** [comment]
The feature request template was not filled out. Edit the first post to use the template https://github.com/VCVRack/Rack/issues/new?template=feature_request.md and reply, and I will reopen.
