### ISSUE TITLE
save groups of modules (nested modules)

### ISSUE THREAD

**Issue by D0IP** [VCVRack/Rack#1830]
Hi, I'm not exactly new to DAWs but I am new to VCV rack and one thing I have noticed it is difficult/impossible to do in the rack AFAIK is the ability save/recall a specific group of modules (including their settings and cable patches) separately from the rest of the rack(kind of like saving a software instrument as a preset but with multiple groups of modules). this would allow a user to focus on sound design when creating instruments and recall them later into other projects when needed. this would be IMHO an extremely powerful feature.

I think this could be implemented in a couple of different ways:
- a feature that allows individual rows on the rack to be saved and recalled similarly to the module presets but on a whole row.
- a module that acts sort of like grouped tracks in DAWs like Ableton, with the modules you want to be saved nested inside of itself and with the ability to be saved like any other module preset.

(Also I'm not a developer/coder I'm just a guy who likes making music I hope I did this feature request right lol)

**Comment by D0IP** [comment]
on second glance I was able to find a feature request similar to what I'm asking for here: https://github.com/VCVRack/Rack/issues/129

I think having it work as a nested group would work a little bit better from a workflow point of view but having the ability to merge/import existing patches into the patch would let you do the same thing with one extra step(deleting modules you don't need)

**Comment by stoermelder** [comment]
You can try this module:
https://library.vcvrack.com/Stoermelder-P1/Strip

**Comment by D0IP** [comment]
that is EXACTLY what I was looking for! thank you!
