### ISSUE TITLE
Blue/magenta leds and strange glow

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/Rack#184]
OS (if applicable):OSX
Version (or "dev" if compiling from source):dev

Just want to let you know this strange things that happened today.
I just made a "git pull" of the Rack Sources and all my buttons/light turned blue/magenta instead of gree/red, and lights had a strange exaggerateg glow around them

make ckean on all my plugs, and git pull + make on the fundamentals too resolved the problem. Maybe it's just related to some last-minute edits in code, maybe a bug or something?

![blue led](https://user-images.githubusercontent.com/16060683/31228949-7efb5dce-a9df-11e7-8887-cef937bd56b8.png)

**Comment by antoniograzioli** [comment]
probably referred/consequence to this? https://github.com/VCVRack/Rack/commit/223719dcd9ebf33a7b8f304c54891eb24a758d6f

**Comment by AndrewBelt** [comment]
Weird. There are three commits around that one which change the alpha and glow radius of lights, but that's all that was changed.
I don't see why it would make the lights weird colors though. What if you checkout this commit (27229b674bfc98c81e97f2f3ee17557578a5d7a8) and rebuild?

**Comment by antoniograzioli** [comment]
as I said, rebuilt everything and it was back to normal...

**Comment by AndrewBelt** [comment]
Works for me with Fundamental in the latest code. Have you done `make clean; make` in Fundamentals? Maybe `color.a` is outside of the range [0.0, 1.0], and your graphics card is handling that undefined case differently than mine.

**Comment by antoniograzioli** [comment]
yes, as I said in the first report.
make ckean on all my plugs, and git pull + make on the fundamentals too resolved the problem

**Comment by AndrewBelt** [comment]
It looks like `color.a` values are properly clamped. Could you comment out the line 

	nvgGlobalCompositeOperation(vg, NVG_LIGHTER);

in Lights.cpp of Rack and see if the problem still exists?
