### ISSUE TITLE
Lambda function to supply random sampling procedure for parameters as data

### ISSUE THREAD

**Issue by Kautenja** [VCVRack/Rack#1846]
### Summary

#205 talked about preventing randomization to certain parameters. I'd like to be able to arbitrarily specify the random sampling process in the `Module::configParam` function.

### Proposed design

Currently, the function bears this signature:

```
void configParam(int paramId, float minValue, float maxValue, float defaultValue, std::string label = "", std::string unit = "", float displayBase = 0.f, float displayMultiplier = 1.f, float displayOffset = 0.f)
```

Changing it to accept an additional functional parameter that takes as input three floats (`minValue`, `maxValue`, `defaultValue`), i.e., `std::function<void(float, float, float)>` would allow the developer to arbitrarily supply the `randomize` function of the `ParamWidget` without needing to introduce unnecessary subclasses, nor locking the developer in to using something like the `<random>` header for random sampling. The function could default to the current behavior of a uniform distribution `U(minValue, maxValue)`. As data, the function would seemingly need to be stored by `ParamQuantity`, and the associated `randomize` class member function calls would need to be removed. It seems that additionally, classes like `Knob` would need some refactoring as the `randomize` function does some extra work to snap the parameter to the discrete values if `snap = true`.

**Comment by AndrewBelt** [comment]
Rack v2 adds
```cpp
	struct RandomizeEvent {};
	/** Called when the user randomizes the module.
	The default implementation randomizes all parameters by default, so you must call `Module::onRandomize(e)` in your overridden method if you want to keep this behavior.
	*/
	virtual void onRandomize(const RandomizeEvent& e);
```
This should allow you to randomize parameters and Module state any way you wish.

**Comment by Kautenja** [comment]
Oh neat! I wasn't aware of this, but you're right it's exactly what I'm looking for.
