### ISSUE TITLE
Please publish a new tag.

### ISSUE THREAD

**Issue by zfjagann** [VCVRack/Rack#1847]
Version 1.1.6 no longer builds successfully due to the pffft issue fixed by 2db08f15a00f6792bb3a45db31dd13f94966beed.

Please publish a new tag which includes this fix so users have a working tag to build against.

NOTE: the branch `1` does build, but I'd prefer a tag so the version is consistent. `1.1.6` is also 10 months old now (published November 4th, 2019).

### Details

Operating system and version: N/A
Rack version (vX.Y.Z): 1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): N/A

### Summary

The latest tag (1.1.6) is old and no longer builds.

### Steps to reproduce

Attempt to build v1.1.6 (unsuccessfully)

**Comment by AndrewBelt** [comment]
I only tag commits that I release on https://vcvrack.com/Rack. Since I haven't released a new version since Rack v1.1.6, there is no need for a commit to be tagged. To build Rack from source, using the latest `v1` commit is fine.

**Comment by zfjagann** [comment]
Linux distros require a tag in order to have a reproducible build and for the software to not change each time a new commit is published.

At this point, linux distros are packaging software that's 10 months old and no longer builds from source.

Short of installing this directly from source (which I am capable of doing, but would prefer not to) there's no way to install this package on my computers.

Please reconsider and issue a new tag.
