### ISSUE TITLE
protection for audio interface

### ISSUE THREAD

**Issue by nay-seven** [VCVRack/Rack#185]
OS :Mac High Sierra
Version : 0.3.2

Hello, here a simple patch where i use the clouds as fx, input is Wavtap audio from a DAW, works fine
![2 audio interface](https://user-images.githubusercontent.com/13808201/31238992-ee783354-a9fb-11e7-9b03-9acf05d0c1f3.png)

Now if i switch the first audio interface to my sound card saffire ( so same as second one)  Rack don't answer anymore ( which is quiet logic in a way) 
So i force Rack to quit
But now i can't restart Rack except if if i delete the autosave.vcv file
so maybe Rack need a kind of protection for such an manipulation error ?

**Comment by AndrewBelt** [comment]
The Audio Interface rework might fix this because all thread blocking will be given timers and failure modes.

**Comment by nay-seven** [comment]
cool !

**Comment by Strum** [comment]
you are trying to create 2 instances of the same audio device so that might cause a problem

why don't you just swap the inputs to clouds from the interface on the left to the interface on the right and delete the left audio device

**Comment by nay-seven** [comment]
hello, no at first i use 2 different audio interface, wavtap as input, and my soundcard saffire as output, works fine this way, 
here i just say that if **by error** i switch first one to saffire, this cause of course a problem, so i suggest that maybe VCVRack need a kind of protection for this kind of users errors, and andrew have the solution yet

**Comment by AndrewBelt** [comment]
Since Rack v0.6 or so, a dialog appears if Rack detects that it has crashed, asking the user to reset their patch.
