### ISSUE TITLE
Unable to build due to 404 error

### ISSUE THREAD

**Issue by DanBiscotti** [VCVRack/Rack#1850]
Operating system and version: Arch Linux
Rack version (vX.Y.Z): 1.1.6-2
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): Lenovo Thinkpad

### Summary
Whilst building the package from the arch linux AUR repositories, I am encountering a 404 error shown here:
```
make -C dep
make[1]: Entering directory '/home/dan/.cache/yay/vcvrack/src/vcvrack-1.1.6/dep'
mkdir -p include
cp nanovg/src/fontstash.h nanovg/src/nanovg_gl.h nanovg/src/nanovg_gl_utils.h nanovg/src/nanovg.h nanovg/src/stb_image.h nanovg/src/s
tb_truetype.h nanovg/example/stb_image_write.h include/
mkdir -p include
cp nanosvg/src/nanosvg.h nanosvg/src/nanosvgrast.h include/
mkdir -p include
cp oui-blendish/blendish.h oui-blendish/oui.h include/
mkdir -p include
cp osdialog/osdialog.h include/
wget -c "https://bitbucket.org/jpommier/pffft/get/29e4f76ac53b.zip"
--2020-10-05 13:12:57--  https://bitbucket.org/jpommier/pffft/get/29e4f76ac53b.zip
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving bitbucket.org (bitbucket.org)... 18.205.93.1, 18.205.93.2, 18.205.93.0, ...
Connecting to bitbucket.org (bitbucket.org)|18.205.93.1|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-05 13:12:58 ERROR 404: Not Found.
```

### Steps to reproduce

Build the package from the AUR
https://aur.archlinux.org/packages/vcvrack/

**Comment by AndrewBelt** [comment]
This was fixed in 2db08f15a00f6792bb3a45db31dd13f94966beed. Use latest git commit of Rack.

**Comment by DanBiscotti** [comment]
Thanks for your quick response. I am trying it now, but now there is a problem building from git due to this URL timing out:
http://www.music.mcgill.ca/~gary/rtmidi/release/rtmidi-4.0.0.tar.gz
Is there anywhere else I can get this package?

**Comment by DanBiscotti** [comment]
Ah nevermind, I was able to use the github repo
Thanks

**Comment by AndrewBelt** [comment]
That URL works for me. Are you using a firewall, antivirus, or extension that is blocking that server?

**Comment by DanBiscotti** [comment]
Ah strange, it works now! Must have been a brief outage somewhere along the line. I managed to get it working from the github repo anyway. Thanks for your help
