### ISSUE TITLE
Quantizers not working on VCV Rack

### ISSUE THREAD

**Issue by egochimp** [VCVRack/Rack#1851]
### Details

Operating system and version:
Rack version (vX.Y.Z):
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

I've just recently started using VCV Rack and after a few sessions the VCV quantizer started going nuts, not quantizing anything and ruining the sound of the vco. I tried other third party quantizers but these don't work either.

**Comment by stoermelder** [comment]
Please post a screenshot of your patch. You are almost certainly doing something wrong if no quantizer works how you would expect it.

**Comment by AndrewBelt** [comment]
You're likely sending audio to VCV Quantizer. Modular quantizers process 1V/octave CV signals.

**Comment by egochimp** [comment]
Yeah, just like Andrew pointed out I was sending audio to the quantizer. Thanks for the heads up and sorry for wasting your time.
