### ISSUE TITLE
Moving knobs when cursor lock is disabled is too slow

### ISSUE THREAD

**Issue by wallindaniel** [VCVRack/Rack#1853]
### Details

Operating system and version: Mac Osx 10.15.6
Rack version (1.1.6):
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): MacBook Pro

### Summary
Turning the knobs of modules without having mouse position locked causes my mouse
cursor to be far away from the knob to even turn it a little.

### Steps to reproduce
Choose not to have mouse position locked in the vcv menu.
Turn knob on module of your choice
In order to turn it just a little you have to drag across half the screen.

**Comment by neurator** [comment]
Similar Issue, fresh install Ubuntu Studio 20.10.  Mouse cursor disappears while holding the knob, control of knob requires much dragging and is erratic.  I can let go of the mouse click and the knob will still be catching up to the dragging for up to a second later. No options in the menus for adjusting this, is there a config file that can be altered?

**Comment by AndrewBelt** [comment]
Rack v2 will allow you to change the knob sensitivity in `settings.json`. The feature has already been added, so I will close this issue.

**Comment by wallindaniel** [comment]
Thanks, when is v.2 planned?

Den tors 12 nov. 2020 10:29Andrew Belt <notifications@github.com> skrev:
