### ISSUE TITLE
RingBuffer - shouldn't push() end's index incremented later?

### ISSUE THREAD

**Issue by Nowhk** [VCVRack/Rack#1854]
I was watching this code: https://github.com/VCVRack/Rack/blob/v1/include/dsp/ringbuffer.hpp#L24

shouldn't be:

```
size_t i = end + 1;
data[i] = t;
end = i;
```
? because to increments end++ before copying the T object could be not thread safe (if the consumer, for example, start to read from [end] when data has not been copied).

**Comment by Nowhk** [comment]
its exaclty what it does, sorry! thanks

**Comment by AndrewBelt** [comment]
`end` points to the *next* element slot, not the last (valid) one. This is similar to C++'s `vector::end`. Here's a diagram https://en.cppreference.com/w/cpp/container/vector/end

**Comment by Nowhk** [comment]
I know. but still there could be concurrency problem. 
example: two threads are trying to read/write the T value from the last (valid) one.

let say the situation is with start = end = 0.

consumer will check with size() > 0 if there are stuff. in that case there aren't (do nothing).

now a producer do a push(). it will start to write to the position 0 and put end at 1: `size_t i = mask(end++);`
if meanwhile a consumer (another thread) does size() > 0 (which now is true) and than shift() (so it happens between `size_t i = mask(end++);` and the end of  `data[i] = t;) it will read rubbish...

**Comment by AndrewBelt** [comment]
Oh, I misread your first post. This was fixed a few months ago in Rack v2.

**Comment by Nowhk** [comment]
Is this code available? so i can fix directly also on v1. Also because I'd like to extend it, in a way that consumer will shift to the recent "value" (i.e shift to end-1), skipping items in the middle if any. Not sure if its possible with the actual code...

**Comment by AndrewBelt** [comment]
Rack v2 source code is not yet publicly available at this time.

**Comment by RareBreeds** [comment]
If you've already looked into lock free ring buffers / C++11 atomics / memory order etc for the v2 ring buffer you can skip the rest of this comment.

Moving the increment to after the data is written in the source code isn't enough, the compiler and hardware is free to reorder the instructions. This will be a bigger problem on ARM as the architecture doesn't guarantee to maintain the order of stores to memory like x86 does.

**Comment by Nowhk** [comment]
> If you've already looked into lock free ring buffers / C++11 atomics / memory order etc for the v2 ring buffer you can skip the rest of this comment.
> 
> Moving the increment to after the data is written in the source code isn't enough, the compiler and hardware is free to reorder the instructions. This will be a bigger problem on ARM as the architecture doesn't guarantee to maintain the order of stores to memory like x86 does.
If you use std::atomic variables, this would be enough to keep the order of execution I think. Isn't?

**Comment by RareBreeds** [comment]
I've not done much programming with std::atomic, but from what I've read yes that's enough.

The std::atomic default memory order is sequential consistency which is overkill, especially on ARM, but easier to reason about and likely fast enough. I think you do just need the offsets as std::atomic and that'll guarantee that loads / stores won't be reordered around them. i.e. you don't need the data buffer to be an atomic type too.
