### ISSUE TITLE
Show placeholder when module is not found

### ISSUE THREAD

**Issue by dfkettle** [VCVRack/Rack#1856]
### Summary

When I download a patch and try to open it in VCV Rack, if a module isn't found, I get an error message. That's understandable, but the reference to the missing module also seems to be deleted from the patch. So even after installing the missing module, the reference to the module is gone, and I have to delete the file and download it again.

### Proposed design

Instead of deleting the reference when a module isn't found, could it be replaced by a dummy place-holder or maybe a "Notes" module with the name of the missing module? The ideal solution would just be to deactivate the reference in some way, so after installing the missing module, it would automatically be re-activated, with any connections to other modules still intact.

**Comment by dfkettle** [comment]
Or alternatively, flag the entire patch as invalid and prevent it from running until the missing module can be found.

**Comment by dfkettle** [comment]
Actually, I realize now that the original patch isn't modified unless you save it. It's only the temporary copy that's modified. I was confused because even though I hadn't done a save, when I restarted VCV Rack, it opened the temporary copy, not the original. A little confusing to newbies like myself, maybe, but not a problem. So I'll close this issue.

**Comment by AndrewBelt** [comment]
>when I restarted VCV Rack, it opened the temporary copy

VCV Rack autosaves on quit, so re-opening it continues where you last left off.

**Comment by dfkettle** [comment]
> > when I restarted VCV Rack, it opened the temporary copy
> 
> VCV Rack autosaves on quit, so re-opening it continues where you last left off.

Yeah, I realize that now. Thanks.
