### ISSUE TITLE
Mac: open in fullscreen

### ISSUE THREAD

**Issue by nnbveh** [VCVRack/Rack#1860]

**Comment by AndrewBelt** [comment]
You can switch to fullscreen mode by pressing F11 or selecting "View > Fullscreen".

**Comment by nnbveh** [comment]
I don't want to SWITCH, i want to be able to OPEN it in fullscreen mode...

**Comment by AndrewBelt** [comment]
You need to fill out the issue template and follow the issue guidelines for your feature request to be considered.

**Comment by nnbveh** [comment]
i DID fill it out, if i press edit i can see my text, but somehow it doesn't show up here...
