### ISSUE TITLE
i can't add plugins

### ISSUE THREAD

**Issue by vcvrackcuenta** [VCVRack/Rack#1862]
Hi, i cant add modules in VCV, some time ago I could, but not now.
I have audible instruments, Befaco and Hamptom armonics.

And I have Windows 10.

When i open VCV , this message appears:

![dfgdfgdfg](https://user-images.githubusercontent.com/74027517/98314241-52e13f80-1fb4-11eb-872e-6cb98d1caab5.png)

I left my account and came back in, uninstalled VCV and reinstalled it, but the problem remains.

When I update, this appears:

![sdfsdf](https://user-images.githubusercontent.com/74027517/98314453-c97e3d00-1fb4-11eb-8f9e-1776f5560a7e.png)

but the new plugins do not appear.

I install the plugins like this:
-I subscribe to the plugin
-center to VCV and update

I also tried to download the zipp file of each plugin pack:
![dfgdfgdfgd](https://user-images.githubusercontent.com/74027517/98314673-3e517700-1fb5-11eb-967a-5f213dd88ec5.png)
I didn't use VCV a while ago, I don't remember very well how to install it correctly.

thanks for reading and any help, bye!

**Comment by AndrewBelt** [comment]
See the instructions at the bottom of https://library.vcvrack.com/ for installing plugins from the VCV Library.

If you want to install plugins from source for whatever reason, see https://vcvrack.com/manual/Installing#installing-plugins-not-available-on-the-vcv-library.

**Comment by vcvrackcuenta** [comment]
> See the instructions at the bottom of https://library.vcvrack.com/ for installing plugins from the VCV Library.
> 
> If you want to install plugins from third-party locations for whatever reason, see https://vcvrack.com/manual/Installing#installing-plugins-not-available-on-the-vcv-library.

I follow all the instructions, and read a lot in other sites, and I still can't add plugins.

**Comment by vcvrackcuenta** [comment]
I was able to make it work!, I don't know how but it started updating, my computer is crazy.
thanks for your time 👍
