### ISSUE TITLE
VCVRack Crashes upon opening project file

### ISSUE THREAD

**Issue by FloSoNa** [VCVRack/Rack#1870]
Rack crashes upon opening old project file, fiddled around with an old project file, saved and recorded it but now the project won't open.

Unsure what could be causing it, I had a previous problem with midi but the midi controller is connected and on when I open it but I still get the crash.

Here is the log.txt
[log.txt](https://github.com/VCVRack/Rack/files/5570942/log.txt)

**Comment by AndrewBelt** [comment]
Please fill out the bug report at https://github.com/VCVRack/Rack/issues/new?template=bug_report.md.
