### ISSUE TITLE
AVI files made with VCV Recorder not importable to Resolve or iMovie

### ISSUE THREAD

**Issue by jjdeprisco** [VCVRack/Rack#1871]
### Details

Rack 1.1.6 on High Sierra

### Summary

When recording AVI (lossless) video output using VCV recorder, the files look/sound great. However, the codec being used is preventing them from my ability to import them into Davinci Resolve or even iMovie. There is some literature out there about Resolve in particular not liking certain AVI codecs, but this seems to be a basic compatibility issue that could be overcome by using standard codecs.

https://www.easefab.com/topic-avi/davinci-resolve-avi-incompatibility.html

"Conclusion: Though each potential reason might result in AVI not importing to DaVinci Resolve issue, the major culprit is the incompatible codec. Thus, the most practical approach to fix DaVinci Resolve not importing AVI problem is to convert AVI codec or format."

### Steps to reproduce

Create an AVI in Rack using VCV Recorder.
Open Resolve or iMovie
Try dragging the AVI file into the video editor.

**Comment by AndrewBelt** [comment]
AVI is the container, FFV1 or HuffYUV are the codecs. The only software I'm aware of that can decode those codecs are ffmpeg and VLC. If you want to load the files in another program, encode them to the format the program can read with ffmpeg. Or use MPEG-2 which most programs support, but the quality is lossy.

**Comment by jjdeprisco** [comment]
VLC conversions were not very good. I ended up using Handbrake to make the conversions, and the resulting files were good and could be brought into Resolve.

As for MPEG-2, the quality is pretty bad (at least when rendered on my system) so I decided not to use it.

**Comment by AndrewBelt** [comment]
Handbrake uses ffmpeg (or its fork avconv) for decoding and encoding, so that should work.
