### ISSUE TITLE
On Mac OS, F11 allows to enter Full Screen mode, but not to leave it

### ISSUE THREAD

**Issue by pixelrust** [VCVRack/Rack#1872]
### Details

Operating system and version: Mac OS 10.14.6
Rack version: v. 1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): -

### Steps to reproduce

* open View, check that shortcut for Full Screen is F11
* press F11 and enter Full Screen
* press again F11

It's expected that Rack leaves Full screen, but it doesn't

Additional note:
* Fn+F11 works correctly to enter and leave Full Screen, but it's not reported in the UI
* discussion on https://community.vcvrack.com/t/mac-os-how-to-exit-full-screen/11640

**Comment by AndrewBelt** [comment]
Rack v2 allows you to exit fullscreen by choosing "View > Fullscreen" in the menu, pressing F11, or pressing Escape.

**Comment by bvrp** [comment]
Why was this closed. This is still an issue. It apparently not possible to exit full screen on a Mac after selecting fullscreen via VCV rack's own menu.

**Comment by AndrewBelt** [comment]
@bvrp It was closed because it was fixed in the Rack v2 branch, which will be released in the future. There is nothing left to do for this issue.
