### ISSUE TITLE
Undo shortcut doesn't function in Windows 10

### ISSUE THREAD

**Issue by nesdnuma** [VCVRack/Rack#1874]
Hello,

I've encountered this issue on at least two computers: the ctrl+Z keyboard shortcut doesn't function in Rack 1.1.6/Windows 10. I must go to the "Edit" dropdown menu to undo.

I am surprised no one has raised the issue before. Is it only on my computers?

**Comment by AndrewBelt** [comment]
What language and layout is your keyboard?
Do other Ctrl key commands work, such as Ctrl+O for "File > Open"?

**Comment by nesdnuma** [comment]
Hello Andrew, sorry for the delay to answer. I use French language with a [Belgian](https://en.wikipedia.org/wiki/AZERTY#Differences_between_the_Belgian_and_French_layouts_of_the_AZERTY_keyboard) keyboard layout.

Ctrl+O works flawlessly, as well as Ctrl+N for instance.

**Comment by AndrewBelt** [comment]
That's probably it. Rack v1 technically only supports QWERTY. Rack v2 switched to `keyNames` which makes key commands work a bit better across all keyboard layouts, so I'll close this issue.

**Comment by nesdnuma** [comment]
I don't get it. Does it mean I should use a QWERTY keyboard? Or is there another solution?

**Comment by nesdnuma** [comment]
Haa, I think I get it.  What you mean is that it will be solved in v2 (I still didn't happen to know it was in the pipeline a few minutes ago!).
