### ISSUE TITLE
Well. Make it just vaguely possible to make ANY sound at all!

### ISSUE THREAD

**Issue by blaasvaer** [VCVRack/Rack#1876]
### Summary

Installing the bugger on Mac makes me just sit and stare ... tapping my MIDI interface, tapping my keyboard ... fiddling with the (what I think is the UI for the interface controller) ... and just not possible to make ANY sound coming out of the bugger.

### Proposed design
Well, if you know ANYTHING that I don't about what is missing for this thing to make ANY sound (No MIDI? Tell me, no keyboard? Tell me etc), then SHOW HINTS IN THE INTERFACE!

Uninstalling and moving on with my life now ... instead of spending my sunday with a useless interface.

**Comment by AndrewBelt** [comment]
There are modules that allow you to record your patches, such as [VCV Recorder](https://vcvrack.com/Recorder).

This is the issue tracker for reporting bugs and requesting features with VCV Rack itself, so I will close this issue. Visit the [VCV Community](https://community.vcvrack.com/) to ask questions with the VCV Rack user community.
