### ISSUE TITLE
[Feature request] Add support for multiple templates

### ISSUE THREAD

**Issue by dfkettle** [VCVRack/Rack#1878]
### Summary

IMHO, I think that having only one template is too limiting. By allowing multiple templates, users could create different templates for different scenarios. For example, you could create a template with MIDI support for when you need it, and one without, for occasions in which you don't intend to use MIDI.

### Proposed design

There are many applications that allow users to create templates. I think they all work in more or less the same way. Instead of having "Save template" in the File menu, you could have "Save as template" and "Load template". The "New" option in the File menu would just create an empty patch.

**Comment by AndrewBelt** [comment]
Why not load patches with "File > Open"?

**Comment by dfkettle** [comment]
> Why not load patches with "File > Open"?

That would work, of course, and that's essentially what I do now. But the problem is that I usually have to go through the patch and delete the stuff I don't need. Plus sometimes it's hard to remember which patch would be best to start with. Having multiple templates would make it easier, I think. That's probably why most other software applications that have templates allow you to create more than one. I don't think I've ever seen an application that allowed you to create only one template.

**Comment by AndrewBelt** [comment]
> I usually have to go through the patch and delete the stuff I don't need

Then why not make a patch with the modules you don't need? That's the point of templates, right? Your proposal doesn't solve the problem of your patches having too many modules.

**Comment by dfkettle** [comment]
> Then why not make a patch with the modules you don't need? That's the point of templates, right? Your proposal doesn't solve the problem of your patches having too many modules.

Make a patch with the modules you don't need? Interesting idea, I'll think about it. But it's not really a question of my patches having too many modules.  I guess I'll just set up some patches and call them "template-1", "template-2", etc., (or maybe something more meaningful). Why bother with templates at all then?

**Comment by AndrewBelt** [comment]
>Why bother with templates at all then?

Right, that's my point. Most users prefer having a single starting point containing modules they always need, such as VCV Audio and VCV MIDI-CV, that is easily accessible with "File > New". If there's another step of selecting which starting patch they want, they should just load a patch from a folder of their choice.

**Comment by dfkettle** [comment]
OK, I was just making a suggestion. Obviously, you don't like my suggestion, which is why I closed the issue. But have you ever used any other software that supported templates? MS Office? Open Office? Max/MSP? Cubase? MS Visual Studio? Any software I've ever seen that supported templates allowed the user to create more than one. What's the point of having just one template? Am I really the only user that's ever asked for this feature?
