### ISSUE TITLE
VCV Crashing, fatal signal 11, I think it has to do with Mutable Instruments' plug-in.

### ISSUE THREAD

**Issue by BabakAthteshamipour** [VCVRack/Rack#1879]
Hi guys, 

 I am new to VCV Rack, although I am not new to synthesizers. I started working on patch ideas and downloaded Mutable Instruments plug-ins but since then VCV Crashes saying Fatal Signal 11 on logs. I have looked up for it and can't find anything about it to fix it, I have uninstalled and re-installed several times but still the same. Here is what the log file says: 

```
[327.882 fatal src/main.cpp:45] Fatal signal 11. Stack trace:
30: ZN4rack10appDestroyEv 0x456435
29: gai_strerrorW 0x739800
28: _C_specific_handler 0x2bd7f60
27: _chkstk 0x3910fe0
26: RtlRaiseException 0x38bb040
25: KiUserExceptionDispatcher 0x390fc00
24: DumpRegistryKeyDefinitions 0xa11750c0
23: RegisterProcTableCallback 0xa11be8d0
22: RegisterProcTableCallback 0xa11be8d0
21: RegisterProcTableCallback 0xa11be8d0
20: RegisterProcTableCallback 0xa11be8d0
19: DumpRegistryKeyDefinitions 0xa11750c0
18: RegisterProcTableCallback 0xa11be8d0
17: RegisterProcTableCallback 0xa11be8d0
16: RegisterProcTableCallback 0xa11be8d0
15: RegisterProcTableCallback 0xa11be8d0
14: RegisterProcTableCallback 0xa11be8d0
13: RegisterProcTableCallback 0xa11be8d0
12: RegisterProcTableCallback 0xa11be8d0
11: RegisterProcTableCallback 0xa11be8d0
10: RegisterProcTableCallback 0xa11be8d0
9: RegisterProcTableCallback 0xa11be8d0
8: RegisterProcTableCallback 0xa11be8d0
7: ZN4rack3Svg4loadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE 0x45bd7c
6: nvgEndFrame 0x42f618
5: ZN4rack6Window3runEv 0x4594ea
4: main 0x781840
3: main 0x781840
2: main 0x781840
1: BaseThreadInitThunk 0x2fe7020
0: RtlUserThreadStart 0x38bcea0
```
Can anybody help me? I can't understand a thing, although I found this article: https://community.vcvrack.com/t/vcv-1-1-4-crash/5520/2 which they say about a Mutable Instruments VCO (Plaits) causing it.  I hope it will fix since I need VCV for my work. :( 

Thank you!

**Comment by AndrewBelt** [comment]
Did the bug report template not show for you? Fill out https://github.com/VCVRack/Rack/issues/new?template=bug_report.md in a new issue.
