### ISSUE TITLE
discussion: changing samplerate

### ISSUE THREAD

**Issue by martin-lueders** [VCVRack/Rack#188]
OS (if applicable): all
Version (or "dev" if compiling from source): all

As it seems possible to change the internal sampling rate at any time, I was wondering whether there is any function of the plugins, which the host calls to inform the plugin of the change.

I see that gSampleRate always has the correct value, but in some cases I don't want to do some calculations in every step, but only if the rate changes.

One example is when I use some internal audio buffer with a length which should correspond to real time. At a change of sample rate I would have to re-size the buffer, possibly requiring malloc or new type calls. Furthermore, I cannot resize the buffer at every sample as I would obviously loose it.

What's the best way to deal with that?

Thanks,
Martin

**Comment by AndrewBelt** [comment]
Yes! Let's add an `onSampleRateChange()` event to Module. `gSampleRate` will still be accessible as a global.

**Comment by antoniograzioli** [comment]
while we are on the subject, gSamplerate is a global variable ALWAYS containing the chosen sample rate, am I right?

**Comment by AndrewBelt** [comment]
Yes, correct. While we're at it, let's replace it with a function called `engineGetSampleRate()`.

**Comment by martin-lueders** [comment]
as this `engineGetSampleRate()`  might be called at every sample, a function might have too much overhead, unless mane inline. What would be the advantage of a function over a global variable?

**Comment by antoniograzioli** [comment]
yes, right, why call a function on every sample? better use a "standard variable...

**Comment by antoniograzioli** [comment]
@martin-lueders well the function might always report the chosen SampeRate at any given moment..but frankly, it's not something a user would change every minute...most people would probably never touch it...

**Comment by AndrewBelt** [comment]
https://godbolt.org/g/Qv5dGA Not much overhead, especially compared to calling `powf()` every frame for example which is used everywhere for something as simple as parameter scaling.

**Comment by jackokring** [comment]
engineGetInverseSampleRate() as I've found this more often in DSP code.

**Comment by modlfo** [comment]
I usually use a brute force approach. All my plugins have pre-calculated values for all the sample rates available in Rack, including a default function, in case a more exotic sample rate is used. This is a feature of [Vult](https://github.com/modlfo/vult) that I abuse.

For example in this [code](https://github.com/modlfo/VultModules/blob/master/src/lateralus.vult) I have a bunch of `tune_*` functions, that at compile time generate optimized interpolating tables. This gives me a very nice speedup compared to calculating sample rate dependent variables every sample.

**Comment by AndrewBelt** [comment]
Added with e270040
