### ISSUE TITLE
MIDI modules: Data choking, clock drifts, unusable...

### ISSUE THREAD

**Issue by nnbveh** [VCVRack/Rack#1881]
Hi.

Already for some time i was trying to make use of an external midi data with VCV rack to no avail, but i've always assumed that the problems arise from instability in the software i've used to generate that date. I've tried a few sequencers on the same machine(macbook pro 16), such as Ableton and Bitwig, and some apps on Ipad(Drambo etc). I've used IAC driver on mac as a virtual cable and used IDAM to connect ipad. I've tried wireless connections too.

In each case, clock was drifting too much to be usable. Same story with Ableton Link using the module from the library(i know it's not part of the fundamentals but might be that these issues are related). And when it comes to the note gates, there's a lot of choking and missing notes. I am not doing anything complex really, just sending few midi notes at the same time(on the same channel polyphonically or on different channels, same result) to sequence my drums and VCV can't handle that. If i send sixteenth notes to the hi-hat at 130 bpm let's say, it will choke so much that you will hear only very few steps...

So, i really thought that was an issue of those virtual midi cables and such, but yesterday i've got a hardware midi controller with a built-in sequencer(Novation Launchpad pro mk3) which can send clock and midi data both through usb cable and DIN midi cable. When transmitting midi by the usb cable results are the same basically. Maybe clock is more stable, but choking is very bad. I've tested this hardware sequencer with other software, both on mac and ipad, and it works wonders, clock is very stable, not a single not lost...Given that, i have to assume that there's something seriously wrong with how VCV handles incoming midi data(i guess midi cc's are working OK, but timing is not so critical in this case).

Sorry for the long rant, i'm just trying to bring the patches i've created in VCV to the external world, and so far i've had no success...

**Comment by AndrewBelt** [comment]
Moved to Rack repository since Fundamental modules don't deal with MIDI.

You're probably referring to Core modules sending MIDI messages and processing received messages as soon as they are processed in the Engine loop rather than being consistently delayed. This has been fixed in the (currently unreleased) Rack v2 branch by delaying MIDI messages based the audio sample timestamp when they are sent/received, so I will close this issue.
