### ISSUE TITLE
VCV Scalar: add polyphonic CV

### ISSUE THREAD

**Issue by z-plane** [VCVRack/Rack#1885]
### Summary

Allow VCV scalar module to support polyphonic CV

### Proposed design

Simplest would be same as chords with 1 poly in/out. A more complex approach would be for all 4 in/out connectors to control up to 4 separate polyphonic voices with 1 instance of Scalar.

**Comment by AndrewBelt** [comment]
This is the issue tracker for VCV Rack itself. Feature requests and bug reports for commercial VCV products can be sent to contact@vcvrack.com. I will close this issue, so reply via email for follow-up questions.
