### ISSUE TITLE
Build failed due to CMake not putting files in glfw/build, but just glfw

### ISSUE THREAD

**Issue by alanbarnett** [VCVRack/Rack#1889]
### Details

Operating system and version: Arch Linux
Rack version (vX.Y.Z): tip of v1 branch
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

### Summary
`make dep` fails because the CMake command for glfw doesn't put build files in the build folder, but the root glfw folder.
### Steps to reproduce
```
git clone https://github.com/vcvrack/rack
cd rack
git submodule update --init --recursive
make dep
```
To fix, in the file dep/Makefile, change the glfw section from
```
$(glfw): glfw
	cd glfw && mkdir -p build
	cd glfw/build && $(CMAKE) .. \
		-DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF
	$(MAKE) -C glfw/build
	$(MAKE) -C glfw/build install
```
to
```
$(glfw): glfw
	cd glfw && $(CMAKE) \
		-DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF
	$(MAKE) -C glfw
	$(MAKE) -C glfw install
```
This builds glfw in it's root directory instead of the build directory. I'm no good with CMake so I'm not sure how to make it use the build directory, but by making this change I was able to build the dependencies with the normal `make dep` rule.

**Comment by AndrewBelt** [comment]
I can't reproduce the behavior you're describing. glfw is correctly installed to `dep/lib/libglfw3.a` when running `make dep`.
Can you post the terminal output when building glfw. Remove `dep/lib/libglfw3.a` to re-trigger a build if it already exists.

**Comment by alanbarnett** [comment]
What the heck. I tried again with a fresh clone and it's working now. I can only assume that something to do with my folder or make variables was causing cmake to dump the build files in the wrong directory, but everything works now. Closing.
