### ISSUE TITLE
Cannot compile "copy" of Fundamental

### ISSUE THREAD

**Issue by SidLipovits** [VCVRack/Rack#189]
OS (if applicable): OS X 12.6
Version (or "dev" if compiling from source): dev

Trying to get started with this. I have a background in DSP and C++, but for some reason, this is not working as easily as I suspected it would.

I replaced the word "Fundamental" with "Fun" in each of the files in the Fundamental source & compiled.  It worked just fine & I moved the files into the Application Rack/plugins folder.

However, I do not see any of the "Fun" plugs in the menu when I run Rack (they are in the folder). 

Any idea if there is another (likely obvious) step that I am missing?

Thank you very much!

~ Sidney

**Comment by AndrewBelt** [comment]
The name and slug of the plugin is defined in Fundamental.cpp.

**Comment by SidLipovits** [comment]
I changed those as well (and the name of the .cpp and .hpp, though that should not cause trouble).

**Comment by AndrewBelt** [comment]
When running Rack from the command line, does it say "Failed to load plugin" or "Loaded plugin"?

**Comment by SidLipovits** [comment]
I am not getting either message when running with "open /Applications/Rack/Rack.app"

**Comment by AndrewBelt** [comment]
Ah, the Rack binary on the website is v0.3.2, and you're compiling your plugin for the master branch on the website, which is not ABI compatible. You can compile for the old Rack version if you `git checkout v0.3.2` in the Rack directory (and do a full rebuild, since so much has changed.)

**Comment by SidLipovits** [comment]
Ok.  Thank you Andrew.  This is a great project!
