### ISSUE TITLE
VCV Host breaks VST's GUI

### ISSUE THREAD

**Issue by luc9nt** [VCVRack/Rack#1893]
Rack version: 1.1.6
OS: macOS 10.15.7
Platform: i7 10700k, ASUS PRIME Z490-P, GTX780

Having an issue with NI Replika XT, screenshot below. When i open plugin window, everything seems normal until i touch anything, then it becomes like this. Doesnt happen to another plugins i have, also another DAW works correctly with Replika.
![Screenshot 2021-02-17 at 15 44 02](https://user-images.githubusercontent.com/70663409/108489619-d0eefb00-72b2-11eb-9322-f12a78d45afa.png)

After that happens, VCV's GUI starts to be kinda messed up too.
![Screenshot 2021-02-17 at 15 43 47](https://user-images.githubusercontent.com/70663409/108490170-7dc97800-72b3-11eb-9472-ef81f933dbb2.png)

**Comment by AndrewBelt** [comment]
This is the issue tracker for VCV Rack itself. Feature requests and bug reports for commercial VCV products can be sent to contact@vcvrack.com. I will close this issue, so reply via email for follow-up questions.

**Comment by AndrewBelt** [comment]
I don't see an email address I can follow up on, so I'll comment here.

Because Apple doesn't support that GPU, CPU, or chipset, we can't support our software on it.

I can grant you a refund if you email contact@vcvrack.com. Send your order number and VCV account email address.
