### ISSUE TITLE
An option to disable the MIDI-CC module's value filtering

### ISSUE THREAD

**Issue by nickfeisst** [VCVRack/Rack#1894]
### Summary

I've noticed an issue tracking one of my MIDI controllers (the crossfader of a DJ mixer - a control which can be opened and closed, by just a small amount, rapidly) and believe that the issue is the smoothing introduced by the ExponentialFilter applied to the signal.

### Proposed design

I propose an option (possibly in the pop-up menu) to disable this smoothing/filtering. This would created a stepped output, but for the purposes that I want to use this (as a trigger/gate) it would work well.

**Comment by AndrewBelt** [comment]
Rack v2 will include this feature. https://community.vcvrack.com/t/rack-development-blog/5864/56
