### ISSUE TITLE
Real-time priority fix for macOS, better QoL and audio performance for macOS

### ISSUE THREAD

**Issue by diimdeep** [VCVRack/Rack#1901]
### Details

Operating system and version: macOS (affects all versions)
Rack version (v1.1.6):
Hardware relevant to your issue: affects all macs, but severely affect macs with a few CPU cores.

### Summary

Real-time priority menu option is available in macOS, but there is no implementation in code, in other OS it is implemented. This inconsistency in macOS [might misguide](https://old.reddit.com/r/vcvrack/comments/m6iyg5/vcv_rack_slow_on_2018_mac_mini_32_ghz_32_gb_ram/gr7fuaw/) users to believe that it changes something. Additionally this missing implementation reduces quality of life for users in macOS compared to other OS, with degraded performance or audio crackles even with very simple .patch. Large .patch might not be able to function in macOS even if it can be ran on the same hardware under different OS.

### Steps to reproduce

- Using Rack or running Rack in background while there other Apps running is not feasible because of audio crackles.
- Use medium to large .patch results in degraded performance on macOS compared to other OS.

### Fix

[Implemented in fork](https://github.com/diimdeep/Rack/commit/359bfc138819bb5c7caec5c26b0d3176a9d83777) and Rack version for macOS [posted in community forums](https://community.vcvrack.com/t/rack-v1-builds-with-improvements/6073/22?u=diimdeep) with good feedback from users.

**Comment by AndrewBelt** [comment]
Rack v2 doesn't use an engine thread at all. All engine processing is done on the audio thread which is realtime by default. It works better because no thread communication is needed between the audio drivers and graph processing of modules.
