### ISSUE TITLE
MIDI module proposition 

### ISSUE THREAD

**Issue by KinneticSlammer** [VCVRack/Rack#1905]
## Summary ##
The motivation of this project is to allow .mid files to be outputted as notes as if they were notes being played from a midi device. Moreover, it will allow MIDI files to be outputted as MIDI notes (via MIDI out). This is a basic functionality in many DAWs and is a great utility to have. It would also

## Proposed design ##
The proposed design would be a modified MIDI-CV module, with capabilities such as opening MIDI files, outputting them via normal MIDI-CV outputs, and through physical MIDI cables.

### Possible implementation
One possible implementation would be to use commonplace MIDI files on the internet, or simply ones created by any given person, and play them back in RACK. The MIDI output proposition is a side idea that isn't as important. 
### What would change in the UI?
The first thing that would change would be the two boxes where you select the MIDI driver and the MIDI device. The driver section would be replaced by the file opener for the MIDI file. 
The MIDI device section could be changed to something such as if the MIDI file is outputting through a (physical) MIDI cable (via a toggle?)
###  Why this, and what are the alternatives? Why shouldn't external software be used instead?
The proposed design would allow MIDI playback inside of RACK, without any clunky external software (or in extreme cases, hardware). An alternative would be a MIDI playback program, such as [MIDIEditor](https://www.midieditor.org/), for example. While external software _could be relatively simple to use,_ the proposed module would simply be something inside RACK without any external complications. Moreover, it would remove (the possibility of) complicated driver setups any given alternative.
### Layout concept
![midiidea](https://user-images.githubusercontent.com/53013684/113420398-42809580-9397-11eb-81c3-2404ec59b3bf.png)
(I've put numbers next to each feature, the key is below)
#### Key 
1) This is what you click on to open the file selector built into windows. You select a midi file in the file selector that pops up.
2) The controls for the midi file. Clicking stop twice will rewind it back to the start. 
3) Panel for selecting MIDI driver, device, and a toggle. The toggle controls whether  **_PHYSICAL MIDI OUTPUT_** is enabled, not output to other modules inside of RACK (which is always turned on).

### Thank you!
This is my first contribution to *the entirety of Github*, so feel free to contact me if you want clarification or anything. Thank you for reading this!

**Comment by KinneticSlammer** [comment]
I hope I formatted this page correctly...

**Comment by AndrewBelt** [comment]
There's no reason this should be in VCV Rack itself. Anyone can create a MIDI player module in a third-party plugin. https://vcvrack.com/manual/PluginDevelopmentTutorial

**Comment by Petervos2018** [comment]
@KinneticSlammer  there are already midi player modules available : 

![afbeelding](https://user-images.githubusercontent.com/46076474/113453579-95ddfc80-9406-11eb-9439-0520f86faceb.png)

In case you didn't know.

**Comment by KinneticSlammer** [comment]
Crap, and no. I didn't.
