### ISSUE TITLE
Selection of multiple tags in module selector 

### ISSUE THREAD

**Issue by KinneticSlammer** [VCVRack/Rack#1908]
### Summary
The given feature would allow users to select multiple tags in the module selector. 
## What is the motivation for this feature? What does the feature achieve?
This feature would allow people to select multiple tags, i.e. Oscillator and Low-frequency Oscillator, and get results from each tag. The motivation for this is sheer convenience.
## Proposed design
Allow shift-clicking to add multiple tags in the module selector. Click on a given tag again to remove it from the search.
### What is one possible implementation or design of this feature?
n/a (read above)
### If visual, explain how the user interface should be changed. If interactive, explain the steps needed for a user to use the feature.
n/a (read above)
### Are there any corner cases where your implementation would fail?
No, there are not.
### Are there alternative implementations?
No.

**Comment by AndrewBelt** [comment]
This will be available in Rack v2.
