### ISSUE TITLE
approxExp2_taylor5 doesn't work with scalar code

### ISSUE THREAD

**Issue by Nowhk** [VCVRack/Rack#1909]
Here's the code I'm using for scalar code:

```
float baseFreq = 200.0f;
float pitch = 1.0f;
float result = baseFreq * rack::dsp::approxExp2_taylor5<float>(pitch + 30) / 1073741824;
DEBUG("scalar %.5f", result);
```
which outputs `scalar -399.99908` (obviously wrong).

Here's the same code I'm using for vectorized code:

```
rack::simd::float_4 baseFreq4 = 200.0f;
rack::simd::float_4 pitch4 = 1.0f;
rack::simd::float_4 result4 = baseFreq4 * rack::dsp::approxExp2_taylor5<rack::simd::float_4>(pitch4 + 30) / 1073741824;
DEBUG("vector %.5f %.5f %.5f %.5f", result4[0], result4[1], result4[2], result4[3]);
```
which correctly outputs `vector 399.99908 399.99908 399.99908 399.99908`.

Not sure why its wrong on scalar one (the difference seems just a template).
Can this be fixed for scalar code?

Thanks

**Comment by AndrewBelt** [comment]
Looks like `float approxExp2Floor(float x, float* xf)` only works with values `0 <= x < 30`. As a workaround, you can use `pitch + 15` and allow pitch to be -15 to 15. Or, you could use the `float_4` version for one float. It should have roughly the same performance.

Fixed in Rack v2.
