### ISSUE TITLE
Building from master - confusing compilation error

### ISSUE THREAD

**Issue by SidLipovits** [VCVRack/Rack#191]
OS (if applicable): OS X 12.6
Version (or "dev" if compiling from source): dev

Hopefully not too dumb a question; trying to learn something...

Dyld Error Message:
  Library not loaded: /usr/local/lib/libGLEW.2.1.0.dylib
  Referenced from: /Applications/Rack/Rack.app/Contents/MacOS/Rack
  Reason: image not found

The line (102) below in Makefile seems to be the culprit, but I don't know enough to tell why. 

install_name_tool -change /usr/local/lib/libGLEW.2.1.0.dylib @executable_path/libGLEW.2.1.0.dylib $(BUNDLE)/Contents/MacOS/Rack

The bundle I built matches the bundle contents in the 0.3.2 build available for download.  The contents also line up with Makefile with the exception of libglfw.3.dylib, which compiles as libglfw.3.2.dylib in the dep folder.

**Comment by AndrewBelt** [comment]
Hmm, I must be linking to my local glfw copy for some reason instead of the dep/ copy. I will fix this shortly. 

I'm curious why you're wanting to compile the bundle.

**Comment by SidLipovits** [comment]
I am really just trying to understand Mac...most of my experience has been with Windows.
