### ISSUE TITLE
Unable to exit fullscreen mode on Mac after selecting show fullscreen in VCV Rack's menu.

### ISSUE THREAD

**Issue by bvrp** [VCVRack/Rack#1913]
This issue was reported previously an improperly closed.

### Details

Operating system and version:
Rack version (vX.Y.Z):
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

**Comment by AndrewBelt** [comment]
Duplicate of https://github.com/VCVRack/Rack/issues/1872. Please do not purposely open duplicate issues. Comment on the original issue instead.
