### ISSUE TITLE
(feature request) Module Documentation in VCV Rack

### ISSUE THREAD

**Issue by maxp-hover** [VCVRack/Rack#1914]
### Summary

It would be great if module documentation could be found in VCV Rack. It probably wouldn't be that technically difficult to make a UI window that shows up from a right click option on the module. The more difficult part would be to get all the existing modules to send their documentation in an accepted format.

The motivation is to make it easier to learn new modules. Currently, module documentation in VCV Rack is next to none. It's required to go to the Github pages, where usually there are many modules on the same page.

### Proposed design

Introduce a new specification for how modules should give their documentation. Each module should get a markdown file which contains its docs. VCV Rack can add a right click option which will display that markdown in a UI window. 

The nice thing about the markdown format is that most of the documentation already lives on Github, which uses markdown. So in many cases it would just be a matter of copy-pasting.

**Comment by AndrewBelt** [comment]
I think it's easier to read a manual on a webpage. Browsers are familiar, can display rich text with hyperlinks, and it's just as easy to select "Info > Manual" (in Rack v2) to open a module's manual in your browser.
