### ISSUE TITLE
Why the csv format?

### ISSUE THREAD

**Issue by rafzael** [VCVRack/Rack#192]
Hello, I wonder why did you choose (tim) csv files for graphics elements (and if it is a definitive choice)? Is this allows less cpu/gpu load than png or others ?
The csv seems to not display transparency correctly (I use inkscape to edit these).
I plan to use png for next customs graphics I ll create, any recomendations/advices about it?

Thanks

**Comment by AndrewBelt** [comment]
You mean SVG format.

SVG and PNG are not comparable. One is a vector graphics format, the other is raster. SVG allows for rescaling (zoom #76) and support for high-DPI displays, while PNG does not unless you export multiple resolutions.

**Comment by rafzael** [comment]
heu, yes sorry svg, I use many csv files for an other project on yersterday... makes me confused..
Thanks for the answer
