### ISSUE TITLE
Audio-8/Audio-16 support for ASIO non-2^n block sizes

### ISSUE THREAD

**Issue by jpnielsen** [VCVRack/Rack#1926]
When using VoiceMeeter Potato with Focusrite Scarlett 2i2, one I/O setting that works without crackling from timing errors is 48000Hz/192bit (tested with Ableton to Voicemeeter virtual ASIO port)

The voicemeeter info page can be found [here ](https://forum.vb-audio.com/viewtopic.php?f=11&t=506)

However, VCVRack 1.1.6 currently only lists 2^n block sizes - not 48, 96, 160 and 192 in this case.

![image](https://user-images.githubusercontent.com/27916597/127483839-f3739348-853c-424d-b00e-11feb3b4a1a2.png)
![image](https://user-images.githubusercontent.com/27916597/127486124-07014ea8-47bc-4638-b5a0-81a96e84247e.png)
![image](https://user-images.githubusercontent.com/27916597/127486169-1ecc0691-c9e7-4e6e-876e-b7e57b13f657.png)
![image](https://user-images.githubusercontent.com/27916597/127486235-21bffcc9-6927-421c-b2d3-760f9018e2a2.png)

### Proposed design

Please make available all buffer/block sizes supported by the ASIO driver.

regards,
Jens Peter Nielsen

**Comment by AndrewBelt** [comment]
You can edit the .vcv patch file or .vcvm module preset file to set the block size to any integer. An easy method is to copy the preset, paste it into a text editor, copy the edited text, and paste it onto the module.

The difference between e.g. 128 and 256 is too subtle to be worth adding it to the UI.

**Comment by jpnielsen** [comment]
Thank you.
samples not bits !
