### ISSUE TITLE
Problem with SchmittTrigger?

### ISSUE THREAD

**Issue by martin-lueders** [VCVRack/Rack#193]
OS (if applicable): all
Version (or "dev" if compiling from source): all

As I understand, the SchmittTrigger should stay HIGH as long as the signal is above the threshold, and go LOW if the signal falls below.

However, the code seems to return false, even if the input signal is HIGH and the internal state is HIGH:

`
bool process(float in) {
		switch (state) {
			case LOW:
				if (in >= high) {
					state = HIGH;
					return true;
				}
				break;
			case HIGH:
				if (in <= low) {
					state = LOW;
				}
				break;
			default:
				if (in >= high) {
					state = HIGH;
				}
				else if (in <= low) {
					state = LOW;
				}
				break;
		}
		return false;
	}
`

I guess the return line should read:

`return state==HIGH;`

or something equivalent. Otherwise, as at the moment, it only gives a one-sample 'true' when the signal goes above the threshold.

**Comment by AndrewBelt** [comment]
This is intended behavior. Use

    trigger.process(value);
    trigger.state == SchmittTrigger::HIGH

If you want to get the current state.

**Comment by martin-lueders** [comment]
OK. Thanks. 

That does the trick. I guess it still is some learning curve and reading the sources to fully understand the functionality of the API.

Cheers,
Martin

**Comment by AndrewBelt** [comment]
Also, no documentation doesn't help!
