### ISSUE TITLE
'jansson.h' file not found

### ISSUE THREAD

**Issue by chanteurchauve** [VCVRack/Rack#196]
OS: macOS 10.12.6
Version: dev

I downloaded the whole rep. When trying to compile it gives me this error: 

c++ -Iinclude -Idep/include -Idep/lib/libzip/include -DVERSION=dev -MMD -O3 -march=nocona -ffast-math -g -Wall -DARCH_MAC -mmacosx-version-min=10.7 -DAPPLE -stdlib=libc++ -std=c++11 -stdlib=libc++ -c -o build/src/app.cpp.o src/app.cpp
In file included from src/app.cpp:1:
include/app.hpp:3:10: fatal error: 'jansson.h' file not found
#include <jansson.h>
         ^~~~~~~~~~~
1 error generated.
make: *** [build/src/app.cpp.o] Error 1

**Comment by AndrewBelt** [comment]
Did you run `make dep` from the [instructions](https://github.com/VCVRack/Rack#building)?

**Comment by chanteurchauve** [comment]
Yes I did and I get this: 

configure: error: Could not find 10.5 to 10.12 SDK.
make[1]: *** [lib/libportaudio.dylib] Error 64
make: *** [dep] Error 2

**Comment by AndrewBelt** [comment]
Known issue #122

**Comment by rdwiv** [comment]
I'm having the same issue with make. No errors with make dep .
macOS 10.10.5
$ make
c++ -Iinclude -Idep/include -Idep/lib/libzip/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7 -DAPPLE -stdlib=libc++ -std=c++11 -stdlib=libc++ -c -o build/src/app.cpp.o src/app.cpp
In file included from src/app.cpp:1:
include/app.hpp:3:10: fatal error: 'jansson.h' file not found
#include <jansson.h>
         ^
1 error generated.
make: *** [build/src/app.cpp.o] Error 1

**Comment by kellyvigil** [comment]
I'm also having the same issue as @rdwiv with jansson.h

macOS 10.12.6

$make dep worked fine
$ make reads:
c++ -Iinclude -Idep/include -Idep/lib/libzip/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7 -DAPPLE -stdlib=libc++ -std=c++11 -stdlib=libc++ -c -o build/src/app.cpp.o src/app.cpp
In file included from src/app.cpp:1:
include/app.hpp:3:10: fatal error: 'jansson.h' file not found
#include <jansson.h>
         ^~~~~~~~~~~
1 error generated.
make: *** [build/src/app.cpp.o] Error 1

**Comment by AndrewBelt** [comment]
Did you run `make dep` from the instructions, yes or no?

**Comment by kellyvigil** [comment]
Yes I followed the instructions step by step

**Comment by AndrewBelt** [comment]
Is the dep/include/jansson.h file present? What about dep/lib/libjansson.*?

**Comment by ortenheim** [comment]
I have similar issue. followed instructions step by step after git checkout v0.5.

`Oceanhubs-iMac:Rack 0.5 ohimacmikael$ make
c++ -Iinclude -Idep/include -Idep/lib/libzip/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7 -DAPPLE -stdlib=libc++ -std=c++11 -stdlib=libc++ -c -o build/src/app.cpp.o src/app.cpp
In file included from src/app.cpp:1:
include/app.hpp:3:10: fatal error: 'jansson.h' file not found
#include <jansson.h>`

- dep/include/jansson.h is not present http://take.ms/pQVnH
- dep/lib/libjansson.*  is not present either http://take.ms/VSYNc

here is a log from terminal. https://pastebin.com/iKUyn75M

@AndrewBelt

**Comment by AndrewBelt** [comment]
Don't use spaces in directory names.I *believe* the "++" shouldn't give you an issue, but the space definitely will.

**Comment by JP01** [comment]
This is happening for me when I try to build the dependencies in the "Fundamental" repo with just downloading the SDK and pointing the dir at that.

Only samplerate.h gets built
