### ISSUE TITLE
No rule to make target 'build/ext/noc/noc_file_dialog.c.o'

### ISSUE THREAD

**Issue by DepreTux** [VCVRack/Rack#2]
Hi!

I'm trying to compile under debian jessie, and I'm getting the aforementioned error. 

The Makefile mentions a file by the name noc_file_dialog.c which seems not to be part of the noc distributed files. I only have a header by that name.

Am I doing something wrong?

Anyway, thanks a lot for this, I'm anxious to try it out.

Cheers

**Comment by AndrewBelt** [comment]
I'll fix the build system some time after Knobcon.

**Comment by AndrewBelt** [comment]
But if you're anxious, it's just a file that contains something like

`#define NOC_FILE_DIALOG_IMPLEMENTATION
#include "noc_file_dialog.h"
`

There are probably other issues with the build system that depend on modified versions of the dependencies. I'll create a script that goes through all these changes.

**Comment by falkTX** [comment]
Why did you close the bug, if the issue itself is not resolved yet?

**Comment by AndrewBelt** [comment]
Fixed. Actually, I wrote my own replacement called [osdialog](https://github.com/AndrewBelt/osdialog). Hopefully this library becomes a bit better than noc_file_dialog.
