### ISSUE TITLE
Control click background doesn't work

### ISSUE THREAD

**Issue by nickysick** [VCVRack/Rack#20]
Control Click doesn't work on mac

**Comment by billvanloo** [comment]
I'm having the same issue. I've installed Rack and downloaded plugins, but using CTRL+click (the equivalent of right click on Mac OS X) doesn't bring up any menu.

I'm on Mac OS X 10.12.6, running on a MacBook Pro. Rack shows Version 0.0 (0.0.0) from the Rack -> "About Rack" menu.

**Comment by oblivionratula** [comment]
FYI, Ctrl-Click does nothign for me, bout two-finger click on trackpad opens Add menu.

**Comment by billvanloo** [comment]
Good call - two-finger click on trackpad does work for me as well. Thanks!

**Comment by AndrewBelt** [comment]
Fixed with f6b4c90e55db9d1646c90c691f04d78e571b519f
