### ISSUE TITLE
Mouse-over Text for Core Audio Device Pull-Down

### ISSUE THREAD

**Issue by djpeterso23662** [VCVRack/Rack#202]
OS (if applicable):  Windows 10
Version (or "dev" if compiling from source):  0.3.2

After you select an audio device using the Audio Device pull-down on the Core Audio Interface, the device name is truncated on the module.  It is hard to remember which device is which after that.  With my MOTU 828 the Audio Interface sees each pair, so I create an Audio Interface for each pair I need.  A mouse-over event for the Audio Device pull-down could show the non-truncated name.  This would make it easier when there are lots of channels in the patch.  

As a side issue, under Windows 10 if I go back to the Audio Device pull-down I cannot tell which option was selected.  

As another side issue, it would be great if the unused jacks were shown darkened or disabled after the Audio Device is selected, matching the 0 in, 2 out or whatever the config is.  

It would be very cool if the jacks lit up in two colors like the jacks on the Expert Sleepers Disting Mk4 (one color positive, one negative).  However, I worry that this will drive the CPU load up so it would be good to turn off the jack colors after you complete your setup using a contextual menu.  As of v 0.3.2 Rack is much lighter on the CPU than other Eurorack emulations and I would like it to stay that way if possible.  

Thanks for reading!

**Comment by AndrewBelt** [comment]
Not enough space in the current design to display the entire driver name.

Your second issue is fixed with the LEDs below.
![2019-10-22-142746_367x433_scrot](https://user-images.githubusercontent.com/338179/67317496-27d69b80-f4d8-11e9-8038-842b20516b17.png)
