### ISSUE TITLE
Plugins don't compile with v0.3.2

### ISSUE THREAD

**Issue by lvets** [VCVRack/Rack#204]
OS (if applicable): Ubuntu 16 LTS
Version (or "dev" if compiling from source): v0.3.2

Compiling the plugins with Rack version v0.3.2 in the repo doesn't work, you have to be on Master. Also, the plugins themselves have no tags.

Not so much a bug, just warning folks who might have the same 'problem' :)

**Comment by AndrewBelt** [comment]
Yes, I've forgotten to tag all the plugins. I'll do that starting with v0.4.0.

**Comment by lvets** [comment]
Thanks!
