### ISSUE TITLE
Protect parameters when randomizing a module

### ISSUE THREAD

**Issue by Euphorbium** [VCVRack/Rack#205]
It would be nice to be able to protect some parameters of a module from change, when randomizing.

**Comment by AndrewBelt** [comment]
By the plugin developer, or by the UI?

**Comment by Euphorbium** [comment]
UI

**Comment by AndrewBelt** [comment]
Not done yet, but 03795e3 is progress. To finish, the onHoverKey() method would need to be restructured somehow.

**Comment by AndrewBelt** [comment]
`ParamWidget::randomizable` was added a while ago, so closing this.

I don't think there should be a way to do this from the UI, since I can't think of a non-tedious way to do this.

**Comment by Euphorbium** [comment]
@AndrewBelt There are a few ways to add this. Modifier key click on a knob, for example alt click, should visually add some surrounding ring around the knob to visually show it as protected. Or this could be in the right click menu on the knob, but I do not think that is elegant, unless some more things were added to that menu. I really want this to happen.

**Comment by LKHSogpit** [comment]
Hopefully this can be done a future update it would be a great feature. Middle mouse button might be the easiest way to protect imo from a UI standpoint.

Would there be a way to do it for plug-ins. I do not write code so honestly asking for others! The likes of enable/bypass and master level to be excluded.

**Comment by AndrewBelt** [comment]
Middle mouse button is reserved for scrolling.

**Comment by LKHSogpit** [comment]
Ah didn't even realise that, sweet. I was going to request a grab hand tool  at some point, If the cursor changed to a grab hand when middle mouse was pressed that'd be that sorted!

Bigger things to worry about probably no worries. It would be widely used!

**Comment by LKHSogpit** [comment]
Ah just realised if you Hold a parameter with the mouse it wont get randomised. That'll do!
