### ISSUE TITLE
Possible bug when connecting 2 MIDI outs to the same input port

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/Rack#206]
OS (if applicable): MAC OSX 10.12.6
Version (or "dev" if compiling from source): dev

Not sure if a bug...but I have MIDI 1V/Oct connected to 1V/Oct of the standard VCO.
When I try to connect another MIDI Source (the pitch wheel) to the same input, Rack Crashes...
IF interested I can copy/paste the report here or postit somewhere

see: https://youtu.be/zuGZdkLKn8k

**Comment by AndrewBelt** [comment]
Full plugin rebuild? `make allplugins`

**Comment by antoniograzioli** [comment]
I'll try but I have rebuilt everything 20 minutes ago. Another won't hurt ;-)

**Comment by antoniograzioli** [comment]
nope. terminal says:

Assertion failed: (!(wire2->inputModule == wire->inputModule && wire2->inputId == wire->inputId)), function engineAddWire, file src/engine.cpp, line 184.
make: *** [run] Abort trap: 6

**Comment by AndrewBelt** [comment]
I am a fool a599b33
