### ISSUE TITLE
Windows 10 Sometimes Paints Modules without Bitmaps

### ISSUE THREAD

**Issue by djpeterso23662** [VCVRack/Rack#21]
I hope I am describing this accurately.  In version 0.3 and on Windows 10 64-bit, sometimes right-clicking and adding a module will result in the new module being drawn without its face plate bitmap.  Closing the entire application and re-opening it restored the image, as long as the setup was the patch in autosave.  Re-opening the patch's json file sometimes resulted in incomplete module images, and sometimes in correct module images.  

I also thought that the auto-download of the four groups of modules by the application resulted in the same missing-bitmap problem.  I downloaded the zip files and copied them in by hand, and things worked correctly, up to the point where I started seeing the problem described above.  Maybe it was just the same problem as above.

**Comment by highvoltaged** [comment]
Same here. Win 10. Version 0.3

**Comment by AndrewBelt** [comment]
Fixed with 56f6d31d9ae5e753cb9534a7d2d10ac667380862
