### ISSUE TITLE
Last commit breaks rack on Mac OSX 10.10.5

### ISSUE THREAD

**Issue by martin-lueders** [VCVRack/Rack#213]
OS (if applicable): Mac OSX 10.10.5
Version (or "dev" if compiling from source): dev

the last commit [a80b05a440ab8425b56045b231f2ee3e4bb8e200](a80b05a440ab8425b56045b231f2ee3e4bb8e200) seems to break something on Mac. When trying to start rack with `make run` I get a popup windows saying "Could not initialize GLFW'.

I see that you are now checking for some error, so possibly the problem was present also before but ignored.

Cheers,
Martin

**Comment by AndrewBelt** [comment]
I inverted the error checking logic, fixed in 1590085

**Comment by martin-lueders** [comment]
Thanks. Works again.
