### ISSUE TITLE
Could not initialize GLFW

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/Rack#214]
OS (if applicable): Win 10
Version (or "dev" if compiling from source): dev

Just made a "gt pull" and updated ny Rack SOurces.
run "make allplugins"

When running Rack I now get a "Could Not initialize GLFW" error box.

A few hours ago everyhthing went smooth...

**Comment by AndrewBelt** [comment]
Duplicate of #213  Pull the latest source

**Comment by antoniograzioli** [comment]
OK I confirm it's working again.
