### ISSUE TITLE
Problems with ReaRoute ASIO driver

### ISSUE THREAD

**Issue by martin-lueders** [VCVRack/Rack#215]
OS (if applicable): Windows 7 (64)
Version (or "dev" if compiling from source): dev

The latest build [1590085520b040f39d515e97b7fa9e686d37e156](1590085520b040f39d515e97b7fa9e686d37e156) seems to have an issue with the ReaRoute ASIO driver.

In previous builds I could easily route Audio from and to reaper using the ReaRoute driver. In the latest build, I don't get sound in reaper. My normal ASIO driver (Presonus) still works.

Has anything changed?

**Comment by martin-lueders** [comment]
I am trying to identify which commit broke it. [d0c8521458172e74ef8e58b882d97bc0119f7bc9](d0c8521458172e74ef8e58b882d97bc0119f7bc9) is still working.

**Comment by bontric** [comment]
This commit  should be unrelated to the audio. 

Did you check out earlier builds and tried again, to make sure this is an issue with 1590085520b040f39d515e97b7fa9e686d37e156 ? 

The last commit affecting the audio interface would be: f9cf502a7946a0958f2398b05534e2c2a7220e96 (from 2. October)

Try to build that commit:
```bash
git checkout f9cf502a7946a0958f2398b05534e2c2a7220e96
make clean && make
```

If it still doesn't work, maybe double check whether this is actually related to rack.

**Comment by martin-lueders** [comment]
I am currently going backwards through the commits. The one you mentioned also does not work, and even throws a segmentation fault. 

It is not the rearoute, as it does definitely work with the 0.3.2 version. 

I will let you know when I find the last "good" one.

**Comment by AndrewBelt** [comment]
Some earlier commits have nonperfect build systems, so make sure to `make clean` before each `make`

**Comment by martin-lueders** [comment]
Thanks, I know. My problem at the moment is that the plugins are not working (and not even compiling) for the older rack commits. I need to find a commit which I can build for that.

**Comment by bontric** [comment]
For commits before 26/9 (where the api changed) you can use this to get Fundamental running:

```bash
$ cd plugins/Fundamental
$ git reset --hard 0115b024fbcd134cd3481a09adcc9201c0ea5806
$ make clean
$ make
```

**Comment by martin-lueders** [comment]
I guess I will go back to my latest 0.3.2 build, and then try to apply every commit, one by one.
It will be time consuming, but the procedure will have to reveal the problem at some point.

Any idea whether portaudio itself has changed in that time, or are we using the same version in all Rack versions?

**Comment by AndrewBelt** [comment]
The only time portaudio has changed was in commit 4ded7b174815595c047f1d0375f4ac174ff65d7c.

**Comment by martin-lueders** [comment]
OK. Here is a weird thing:

The binary v0.3.2 which I downloaded form the vcvrack.com webpage does work well with ReaRoute.

Now I went into a fresh emptydirectory, cloned Rack.git, checked out v0.3.2 and then followed the usual build instructions. The binary created from that build does not work with ReaRoute.

I assume that the `git submodule update --init --recursive` gets a different version of the `dep/` packages
than it would have at that time?

Or, was the binary distribution built with a different version? If so, do you remember which changes happened inbetween (the binary distribution build and the tagging v0.3.2)?

**Comment by AndrewBelt** [comment]
I compiled Rack with that exact git tag for all platforms. Can you confirm that the portaudio_x64.dll file (or whatever it's called) is the same between the Rack distrubtion and your source?

**Comment by martin-lueders** [comment]
I just checked it with WinDiff and the portaudio_x64.dll are identical.
However, the Rack.exe in my build differes form the one of the binary distribution.

**Comment by AndrewBelt** [comment]
The last point is no surprise since not even equal version numbers of gcc will produce the same binary due to minor system differences.
Rack v0.5.0 will use RtAudio so you will have more success with that.

**Comment by martin-lueders** [comment]
OK. Let's not waste too much time on that for now, as the problem also should get obsolete once the VST bridge comes out. In case I still find some solution, I will let you know.

**Comment by martin-lueders** [comment]
Guess what? With your binary, ReaRoute works again. When I compile your sources, it does not.

I need to check which other libraries or system resources are used when compiling...

**Comment by antoniotuzzi** [comment]
did you clean "by hands" completely your DERIVED DATA folders (modules included)
for "Rack" "ML-Modules" and generic "modules"

**Comment by martin-lueders** [comment]
Yes, I build in a completely fresh directory into which I cloned again. Must be some part of my MSYS installation. Anyway, for now the problem is sorted as long as I use the "official" binary.

**Comment by AndrewBelt** [comment]
This issue is old and likely obsolete. Comment if issue is still present. Closing.
