### ISSUE TITLE
Input stacking

### ISSUE THREAD

**Issue by Euphorbium** [VCVRack/Rack#216]
Version: dev

Would it be possible to make the inputs stackable? Currently only the outputs are stackable.

**Comment by AndrewBelt** [comment]
It would be possible by unity-mixing, but we've decided against it.

**Comment by Euphorbium** [comment]
What is the reasoning for that? It would pretty much eliminate the need for multiples modules and free up space.

**Comment by AndrewBelt** [comment]
Multiples can't unity-mix. (Well, Links can, because they've included unity-mixers.) It *would* be useful, but it teaches bad habits, doesn't give you any flexibility of attenuation, and gets confusing and makes cables hard to reach with the current implementation of output stacking.

**Comment by antoniotuzzi** [comment]
for electrical reason you can't do in a real world system, so I think is the correct choice (to maintain the real world - virtual world relations stable)
