### ISSUE TITLE
"Tidal" not working

### ISSUE THREAD

**Issue by tildebyte** [VCVRack/Rack#219]
OS (if applicable): Fedora 26
Version (or "dev" if compiling from source): dev, current master
"Tidal" should begin cycling as soon as it's instantiated. Currently, with a fresh build, it simply does nothing. No errors are printed to stdout.

**Comment by AndrewBelt** [comment]
Run `git submodule sync` and `git submodule update --recursive ` to update the eurorack repo.

**Comment by tildebyte** [comment]
Oops. I had pulled `eurorack`, but I was on the wrong branch...

**Comment by gentleclockdivider** [comment]
THe mode switch set to 'A' should cycle trough 3 banks of waves .
When mode switch  led is 'green'  , there should be additive harmonics .
THis is not the case.

**Comment by AndrewBelt** [comment]
Could you open a new issue for that in the correct repository? 

https://github.com/VCVRack/AudibleInstruments
