### ISSUE TITLE
Knob Goes to 100% or 0% with Wacom Tablet

### ISSUE THREAD

**Issue by djpeterso23662** [VCVRack/Rack#22]
When using a Wacom INTUOS2 tablet and pen on Windows 10 64-bit, the knobs snap to 100% or 0% with no in-between.  Switching to the Wacom mouse and tablet, the knob behavior is normal.  

If this issue can be worked, I will provide a Wacom tablet and pen for testing, if a loaner unit is not available locally.  Thanks!

**Comment by AndrewBelt** [comment]
I'm sure a simple solution exists, but yes, I would need to test it. Email me at contact@vcvrack.com if you'd be willing to let me borrow it for a few days.

**Comment by oblivionratula** [comment]
FYI, in the brief moments I had a Debian build of this running, I saw this same behavior with a standard mouse.  If you think there's any use, I can try getting it going again. Not sure what I broke (mainly use Mac, but build on Debian 'for fun.')

**Comment by rncar** [comment]
I am testing this too.
Seems like the pen _y_ position is the value of the knob,
but only using a small range of the screen.

In ableton live, we need to use `-absoluteMouseMode` param in `Options.txt`
[[ableton.com](https://www.ableton.com/answers/how-can-i-use-a-wacom-tablet-with-live)] to fix it.

Great project, by the way.

_Compiled in arch linux._

**Comment by tildebyte** [comment]
I may have mentioned this elsewhere, but I'm seeing the same using the pen on my Surface Pro 4 (Windows 10).

**Comment by AndrewBelt** [comment]
I think 52d41865ef08740c490932b59ed0462b524d5d85 fixes this. You have to edit your settings.json though to change "allowCursorLock" to `true`.

**Comment by djpeterso23662** [comment]
Hi Andrew!  Thanks for working this issue.  I am not sure what to make of "You have to edit your settings.json to change allowCursorLock to false."  allowCursorLock is not in my settings.json.  When I add it, I am not sure of the format, and rack.exe blows away my edits with the next load.  I must be missing something.  So far I can report that I have not made the allowCursorLock  edit correctly, and my know behavior is still zero or 100%.  Any suggestions?  Thanks for your time-- I realize you have a lot of requests and this one may not be a priority.

**Comment by AndrewBelt** [comment]
It should be in the master branch. You're probably using one of the versioned releases, which are all older than a day since I added that feature.

**Comment by djpeterso23662** [comment]
Thanks for your quick reply, Andrew!  I apologize but I have never used MSYS2 before, and with a clean MSYS2 I could not get through the build.  I would rather you spent your time on VCVRACK than hand-holding with me, so I will wait for the next release.  If you know anyone who could scrub the README build instructions for Windows 10 64-bit (Creators), that would probably help a bunch of people.  

My MSYS2 setup was straight from http://www.msys2.org/.  I tinkered with it for four hours, but no luck. I know my way around Cygwin and Linux but I am a sysadmin rather than a developer most days.  

Thanks for the great work you are doing on VCVRACK!

**Comment by AndrewBelt** [comment]
The instructions in the readme should suffice, and if they don't, open an issue.

**Comment by djpeterso23662** [comment]
Hi Andrew! If you think it would help, I will give it a try.  Thanks!

**Comment by rncar** [comment]
Works great Andrew, thanks for the fix.

**Comment by djpeterso23662** [comment]
Hi @AndrewBelt!  Using Rack 0.6.0dev pulled 2/25/18.  I use a Wacom tablet, and Rack functions correctly with allowCursorLock set to false, as it has in versions 0.4.0, 0.5.0, and 0.5.1.  I happened to noticed today that WITHOUT allowCursorLock set to false, Rack goes from zero to 100% on the zoom control, and exhibits runaway behavior on the vertical and horizontal scrollbars.  No fixes needed; with the correct allowCursorLock setting everything behaves as it should.  I just wanted to log the observation, in the hope that it might save someone a little time in the future.  Thanks!
