### ISSUE TITLE
Please add my modules to the list of 3rd party plugins

### ISSUE THREAD

**Issue by Strum** [VCVRack/Rack#220]
I've just made a repo and uploaded the modules I have built.

https://github.com/Strum/Strums_Mental_VCV_Modules

some of them are still in development but the basic utility modules are pretty much working and ready to go.

so far the plugin contains:
Mults
Control Buttons
A/B switches
Muxes
Logic Gates
 A 4 channel stereo mixer with pan
Gates
A chord maker similar to the Q-Bit chord eurorack module
A quantiser/pitch reference that doesn't quite work right yet.
A master mixer with 2 auxiliary sends and returns, only 5 channels atm but I'll redo it with 12 channels in the next week or so.
A simple wave clipper and a similar wave folder, will add a gain control hopefully within the next week as well

I hope people find some of them useful.

I've had fun making them and for the types of things i want to do with modular these kinds of modules are essential even if simple.

in the works are:
control knobs
radio buttons
Adder/Summing mixer
Pitch shifter
counters 
euclidean rhythm generator

**Comment by antoniograzioli** [comment]
the wiki page is editable, you can do it yourself... :-)

**Comment by antoniograzioli** [comment]
BTW they don't compile with the actual version of rack in this moment (have a look at the removal of include "dsp.cpp")

**Comment by AndrewBelt** [comment]
^ Yup, you can add it yourself, no need to create an issue.

**Comment by Strum** [comment]
ok thanks guys.

done.

sorry for being such a noob.
