### ISSUE TITLE
Change knob position from the code

### ISSUE THREAD

**Issue by rafzael** [VCVRack/Rack#221]
Hello, Is it possible to change the knob position from the code (the instrest is to be able to recall presets and get automatically the knob in the good position) ? Please don't tell me to try params[NAME_PARAM].value = yourValue; It obviously won't work :) Thanks

**Comment by antoniograzioli** [comment]
have a look at the **fromJson** and **toJson** in some of the modules (SEQ3 for example) if I understand what you need...they will save/load params values in a json fashion

**Comment by AndrewBelt** [comment]
It will require a restructure to do this, and I don't really want to do it. I like the strict master / slave relationship between the GUI / audio engine.

You could of course save the ParamWidget (Knob superclass) instance somewhere and use `knob.setValue(float value)`

**Comment by rafzael** [comment]
@antoniograzioli 
NO it's not exactly what i want, I already use Json for saving some my modules parameters, what I want was to get someting like motorise poteniometer

**Comment by AndrewBelt** [comment]
Motorized parameters seems a bit invasive to the user, but if you'd like to do it, you have the option of modifying the ParamWidgets as demonstrated above.

**Comment by rafzael** [comment]
@AndrewBelt OK, Maybe it's better to not make this type of function that are never availables on a real modular and keep something intuitive a near the real modular world. I will reconsider my module design from it :) Thanks a lot (and sorry for my to bad english)

**Comment by AndrewBelt** [comment]
Decided to not support "motorized parameters". They should be implemented through LEDs or other widgets if possible, or not at all.
