### ISSUE TITLE
modules distribution

### ISSUE THREAD

**Issue by HoRaMusic** [VCVRack/Rack#222]
@AndrewBelt Hello I have developed tr 808 inspired modules series, it includes all the sounds of the 808 but with much more tweaking possibilities, a funny to use sequencer very closed to the 808 one, a clock divider and an 11 voices mixer. All is based on analog modeling and inspired by my real circuits prototyping of roland analog drum sounds. 
I will clean up all these (codes and graphics), compare the sound with a friend's real 808 to change a bit some sounds if necessary, make sure all is compatible with the next version 0.4.0 of vcv,  and share with some of my contact to test it on win, mac and linux.

You can see the modules here: 

[https://snag.gy/Aml392.jpg](url) 

I would like to ditributef for free the hi hat and the kick modules and sell the complete series for a very afordable price. 
Then I wonder:
- If all the modules that will be host on the vcv site will be free? and if it's not, what are the conditions for  payant modules?
- If the project seems interesting enough to be on vcv website?

Thank you

**Comment by AndrewBelt** [comment]
Really cool plugin!

For hosting on the vcvrack.com website, I will design a protocol/system to support third party plugins around the v1.0 release in November / December. Remind me again when the time is closer. Meanwhile, you can host them on your own website and sell them however you like.

**Comment by rafzael** [comment]
Thank you, they seems to interest many people on social network, i get very positive reactions (I share images on some facebook group).
Yes, I remind you. 
You did a realy fantastic job on VCV, it's realy funny to use and it's a real pleasure to develop modules. I believe with the DAW integration and a big choice of modules it could became a classical tool for electronic music producers. have a good day

**Comment by AndrewBelt** [comment]
Much thanks, I'm glad you like it!
