### ISSUE TITLE
Audible Instruments plugin compilation fails

### ISSUE THREAD

**Issue by Strum** [VCVRack/Rack#224]
OS: Win7
Version : Dev

src/Clouds.cpp:5:10: fatal error: clouds/dsp/granular_processor.h: No such file or directory
 #include "clouds/dsp/granular_processor.h"

**Comment by AndrewBelt** [comment]
Have you been able to compile the Audible Instruments plugin before? Try

    git submodule init --recursive

**Comment by Strum** [comment]
yes have compiled them a couple of times before

when i try 

git submodule update --init --recursive

i get 

': not a valid identifierline 88: export: `dashless

and nothing seems to happen

which directory should i be in when i do it?

**Comment by AndrewBelt** [comment]
I switched the remote url of the eurorack repo, so try a `git submodule sync` or remove the repo entirely.

**Comment by Strum** [comment]
i just cloned the other sets of modules and they all compiled ok with using the submodule update thing

remove which repo entirely? and then what?

tried

git submodule sync 

no change

**Comment by AndrewBelt** [comment]
The eurorack repo within the AudibleInstruments plugin.

**Comment by Strum** [comment]
it's an empty folder

**Comment by AndrewBelt** [comment]
Some git incantations that might help:

	git submodule sync
	git submodule update --init --recursive
	git reset --hard HEAD

**Comment by Strum** [comment]
from where?

**Comment by AndrewBelt** [comment]
In the AudibleInstruments repo, which is what this issue is about.

**Comment by Strum** [comment]
well that is not clearly stated  anywhere in the instructions i'm sorry.

**Comment by Strum** [comment]
works now

**Comment by Strum** [comment]
thanks

sorry to be a noob again 

and thanks for your time

**Comment by AndrewBelt** [comment]
It is stated here
https://github.com/VCVRack/Rack#building-plugins
and here, although this was added in response to your issue
https://github.com/VCVRack/AudibleInstruments#building

**Comment by Strum** [comment]
thanks

i guess having an idiot test it helps make it idiot proof.

:)
