### ISSUE TITLE
Suggestion : selectively loading 3rd party plugins

### ISSUE THREAD

**Issue by Strum** [VCVRack/Rack#225]
Just a thought.

Given the likely explosion of 3rd party modules available in the future perhaps having some means of selecting which modules to load for a session at start up might be a good idea.

**Comment by AndrewBelt** [comment]
I don't see a good reason. Do you?

**Comment by Strum** [comment]
Well the module list might get very long, it might also save some memory not having all available modules loaded all the time as well.

Most DAW software seems to have a way to selectively load plugins.

**Comment by martin-lueders** [comment]
That long module list will be resolved in 0.4.0. As for the memory, I don't think that the modules do need a lot of memory. Possible exceptions would be sampler modules with built-in samples.

**Comment by AndrewBelt** [comment]
Plugins are recommended to lazily compute/load all assets and lookup tables, so simply loading a plugin might be <10KB of memory. If there are 100 plugins, it would still be usable with the hierarchical menus. More than that, maybe, but you could always just move them outside of the `plugins/` folder.

**Comment by Strum** [comment]
no worries.

perhaps you might rethink it when there are 150 or more 3rd party plugins available.

moving them in and out of the plugin folder seems like a bit of a hack and not as efficient though effective.

i'm not phased either way really ,was just a thought.

**Comment by AndrewBelt** [comment]
Wow, imagine that. 150 times about ~8 plugins per pack is probably more VSTs than anyone here owns. And the interesting thing is, it might actually happen, and it might be in less than 6 months. I guess that's what happens when you open the API up...

**Comment by Strum** [comment]
You've created a monster.
:)
I've looked at softtube modular, which seems to be the popular commercial offering and personally i think your rack is superior quite apart from all the benefits of it being open source.

I  really can't thank you enough.

Your code is also so well written it's a real pleasure working with it unlike so much other code i've tried working with which always seems opaque and bloated up with so many unnecessary layers of abstraction and complexity.

You've also been very helpful when you must be very busy and you are obviously very actively developing the project and a rapid pace, so many projects seem to move glacially slowly. big props for that as well.

keep it up, it's inspiring me.
