### ISSUE TITLE
Gate output LED SEQ3 does not work when set to Trigger

### ISSUE THREAD

**Issue by sanderbaan** [VCVRack/Rack#230]
OS (if applicable): OSX 10.12.6
Version (or "dev" if compiling from source): 0.40 release

The gate output LED on the SEQ3 does not work anymore when set to trigger...

**Comment by Strum** [comment]
I have noticed this as well.

It seems like the gate pulses are so short the ui refresh misses them.

my logic modules don't seem to respond to the pulses either.

**Comment by AndrewBelt** [comment]
The triggers are 1ms long which is less than the graphics refresh rate, so you're lucky to get one frame of feedback.

You can set the gate mode of SEQ3 by right clicking on the panel. Have you noticed that?

I'm mystified that the gates are too short for your logic modules. How are they implemented? 1ms = 44 samples, which should be way more than enough for a logic module to respond. Do the triggers trigger Audible Resonator or Fundamental ADSR with attack turned all the way down?

**Comment by Strum** [comment]
it could just be the lights aren't flashing, I haven't tested it thoroughly with seq-3  yet

**Comment by AndrewBelt** [comment]
#210 will fix the feedback problem anyway.

**Comment by Strum** [comment]
yeah, it's working just the lights aren't flashing because the pulses are so short

**Comment by Strum** [comment]
as you said somewhere the plug lights remove the need for display leds anyway
