### ISSUE TITLE
json parsing error

### ISSUE THREAD

**Issue by nay-seven** [VCVRack/Rack#232]
OS:High Sierra last beta version 10.13.1  (17B35a)
Version O.4

I try several time to refresh factory plug-ins but refresh button has a quick activity but no success
so i download and drag the folders manually.
When i restart Rack i've this message:
![error message](https://user-images.githubusercontent.com/13808201/31574792-c9c59f2e-b0d6-11e7-9fbb-06196b34bd14.png)
i click on OK, and all seems to work fine ( thanks a lot for the pause engine option and the new mutable plugin btw)

**Comment by nay-seven** [comment]
For info, the refresh plugin works fine on my mac book /yosemite

**Comment by bontric** [comment]
Make sure to update and rebuilt all your plugins. I think I encountered the same probblem at some point, but a quick `make && make clean` + removing the `autosave.vcv` fixed it for me

**Comment by nay-seven** [comment]
Thanks , but this happen when i add the official plugins manually, but I've also some third party plug-in so maybe it's the answer. I can't compile myself, so will wait to see if some of them updates their plug-in . Ive at least an issue with nysthi ones.

**Comment by bontric** [comment]
Oh, yeah could be a problem with 3rd party plugins. See if they already officially updated to v0.4.0 compatibility.

**Comment by nay-seven** [comment]
yes, it's an 0.4 official release, but he can't test on High Sierra so maybe the problem, 
Deleting his plug-in folder solve the error message.

**Comment by antoniotuzzi** [comment]
my plugins won't do any json writing/reading  and are compiled with release 
23d347279a448b93a9567ed88e9ff2ffb455eb86 (tag v0.4.0)

all the input, output, param should be saved automagically by the engine

**Comment by nay-seven** [comment]
ok, no problem, maybe the issue is elsewhere
but when i reintroduce your plug-in folder , i've the error, when i delete it, no issue, so i just give my feedback ;-)

**Comment by antoniotuzzi** [comment]
@nay-seven scratching my head :)

**Comment by AndrewBelt** [comment]
If it happens again, could you upload your "autosave.vcv" file here?

**Comment by nay-seven** [comment]
ok, so i've create a patch, save it, close and reopen Rack , all is ok
now, close Rack, add the nysthi plug-in folder, open Rack add the reverb module to my patch, save it, close and reopen and have the same message, only difference is the number:
it's now <stream>165:4 ']'
here the autosave ( vcv files are not supported so i zip it)
[autosave.zip](https://github.com/VCVRack/Rack/files/1384706/autosave.zip)

**Comment by AndrewBelt** [comment]
Very strange, since the file looks 100% okay. My only guess is that there is an ABI incompatibility with nsynthi which is messing with the stack, but who knows.

**Comment by antoniotuzzi** [comment]
I have no customized json  IN OUT params, are all flats
did you test with JUST the "nysthi" folder ?

**Comment by nay-seven** [comment]
yes i've also an error if i use only your folder. ( and still the 2 bugs i notice on your github)
For info, i can't reproduce this on my Yosemite machine, all works fine

**Comment by antoniotuzzi** [comment]
so could be a problem of linking against the OSX 13 libraries

**Comment by AndrewBelt** [comment]
Could be! Rack is untested on High Sierra.

**Comment by nay-seven** [comment]
Ok, so i've switch to another partition with Sierra and all works fine, no more errors and Antonio, no more bugs for your modules. 
For info andrew, except this, Rack works perfectly on High Sierrra beta for me.

Now, tell me if you're still interested in beta report for this OS, or i can wait a bit maybe ?

**Comment by antoniotuzzi** [comment]
VERY STRANGE!
maybe related to the new file system ?

**Comment by AndrewBelt** [comment]
The recent change to `RackWidget::savePatch()` probably solved this.
