### ISSUE TITLE
Display tooltip with value and unit when hoving ParamWidget

### ISSUE THREAD

**Issue by soulbridge** [VCVRack/Rack#233]
an info box on the top displaying the value of parameters would be useful (i.e. intonation or wave form)
also an out R normalized on the L, thank u for your work.

**Comment by AndrewBelt** [comment]
Do you mean a tooltip that displays the value of the knob/button you're using when hovering it?

For your second issue, I won't normalize the Audio Interface inputs---just use stackable cables.

**Comment by soulbridge** [comment]
yeah, its what i meant! No problem.

**Comment by odahan** [comment]
The fact there is no display at all for knobs and selectors values is a bit a problem. I personally don't like tooltips they are disturbing and don't give a good UX (mostly on such UI with cables everywhere), it's a bit old-fashioned (why not the return of Clippy :-) )
The best will be to reserve a little area for example in the top bar that will display the value of the modified / hovered knob/selector. In a glance and at the same place you will have the information.
The next level will be this area will work also as an Input... you want a value of 122 you enter 122+return and the knob is set at the right place.
I think value display is very important, and for the future a mean to set precise values is also important.

what are you thinking of this enhancements ?

**Comment by AndrewBelt** [comment]
I like the "122+return" idea, reminds me of vim (but in a good way). Perhaps just hover the value, type "122", and the knob will go to values "1", "12", and then "122". This conflicts with #109 though, so I'll have to find a compromise, unless I make the MIDI keyboard only one octave, which might be better anyway.

I think I'll go with tooltips for display, but I'll add a toggle button on the toolbar. This should be done at the same time as converting the toolbar buttons to icon buttons because it's getting too crowded.

**Comment by odahan** [comment]
Of course the functionalities themselves are important but there are many ways to implement them. I like the idea of an input box that will also display the current value, but your idea seems ok too, programming is making compromises !

**Comment by jonheal** [comment]
I like the idea of a tooltip briefly describing what a control does. I'm not sure if I like the idea of it displaying the control's relative value. Yes, it would make a repeatable setup easier, but it would also diminish the ephemeral experience that kind of defines at least one aspect of the hardware modular experience. I am anal enough as it is. I don't think I want the opportunity to fixate on numbers like I do in other environments. The lack of numerical values forces you to **listen** and let instinct and chance play a prominent role.

**Comment by AndrewBelt** [comment]
^ That's exactly my opinion and why this isn't a huge priority. Although I think it's fair to allow the user a choice. I think they can control themselves by not enabling the feature if they're like you and want the artist experience rather than the scientist's.

**Comment by danamcc** [comment]
I agree that tool tips are helpful, and that some users may want an option
to display values, which could be turned off for those who prefer a little
mystery. As someone who started out with modular and semi-modular synths
back in the 70's (ARP 2500 & 2600) I can say that the lack of repeatability
was sometimes very frustrating (particularly at live gigs!). Although I
wouldn't mind having a big analog rig of my own, I'm quite happy with some
of the improvements and conveniences that virtual systems offer.

So, I vote for giving users choices in a case like this.

**Comment by ruudvanbuul** [comment]
I agree that tooltips (or another way to show current value) and a way to input current values would be handy. I do agree that the user should be able to enable/disable this feature. I was also thinking about the ability for developers to add a description of a knob or in-/output, I have some experience with modular gear but not a lot, and am very new to VCV Rack, it would help a lot if developers could add a description to a knob, in-/output etc. This desciption could be shown in a box somewhere in the UI and this box could be enabled/disabled by the user, similar to ableton. This would help people that are new to modular understand a lot better what is going on and it's easier to see what certain things do exactly. I don't know if this fits into this topic or if I should open a separate topic for this, I just thought this would very useful feature for new comers to modular systems especially with all the different plugins.

**Comment by LKHSogpit** [comment]
Would a floating window be out of the question? Hover over a parameter press F1 to display the value it sticks there! Hover over a LFO press F2 Hz is displayed. Press Esc it clears all displayed press TAB shows those you've set. Could be just 1 Fn and the default set in the file for the module, i.e. frequency "Hz" delay "time" Threshold "dB" Compressor "Ratio" etc. Nothing worse when developers don't name such parameters!

There is a delay from AS that displays the delay time. A counter that exact size would be sweet. Really need a Hz counter of some kind!

With a grab tool you could move the floating window around but not too far away from the parameter just so it is around it. Setting other parameters to match or indeed be a multiple of the other would be easier with something to go off.

**Comment by NikolaiVChr** [comment]
Tooltips or something displayed in Toolbar when hoovering over a control or port would be a very nice addition.
Maybe something dynamic so the text can be updated while the user hovers over it, that can also help users debug their patches when something sounds off. For example a plugin maker could add to a output port of a VCO that it currently outputs -4 to +5V or/and the current frequency.

**Comment by AndrewBelt** [comment]
Added with 4ef58cb
