### ISSUE TITLE
A few feature requests

### ISSUE THREAD

**Issue by davephillips** [VCVRack/Rack#234]
Some feature requests for the UI, probably obvious stuff :

Undo/redo
Files menu: Previously Opened
Files menu: Quit (with Save/Don't Save/Cancel)
Copy/paste modules
Import/export module layouts (for merging material from different projects)
Cancel all lights (dark running mode)
Randomize all/selected modules (with one click)

I'm sure I'll think of other things as I go along. :)

**Comment by AndrewBelt** [comment]
Mind if you spread these out into separate issues? Many of them are duplicates so please search before posting.

Is there a reason to implement copy/paste modules when you can duplicate them (Ctrl/Cmd+D or the context menu)?

How is import/export modules layouts different from saving a patch with disconnected cables?

You can randomize a single module with Ctrl/Cmd+R, and I think holding this button down and "swiping" your mouse over a bunch of modules is faster than any other method.

**Comment by AndrewBelt** [comment]
Good point on the Quit menu item. Fixed in 3fc2a12
