### ISSUE TITLE
(v 0.4.0) In Rack refresh plugins doesn't work properly anymore

### ISSUE THREAD

**Issue by Suitundo** [VCVRack/Rack#235]
OS (if applicable): Win 10, x64, build 1703
Version (or "dev" if compiling from source): 0.4.0

In Rack the refresh plugins option doesn't work properly any more.
When I now press the option the additional plugins on your site are downloaded and show three 1KB zip files in the plugins folder. Starting with a fresh Rack install doesn't help.
For now I've manually downloaded the plugins and installed them.

**Comment by AndrewBelt** [comment]
Can you upload the 1KB .zip file here, email it to contact@vcvrack.com, or upload it through https://send.firefox.com/ and paste the link here?

**Comment by Suitundo** [comment]
They are even less I see now, 25 bytes per file.

[AudibleInstruments.zip](https://github.com/VCVRack/Rack/files/1384727/AudibleInstruments.zip)
[Befaco.zip](https://github.com/VCVRack/Rack/files/1384728/Befaco.zip)
[ESeries.zip](https://github.com/VCVRack/Rack/files/1384729/ESeries.zip)

**Comment by AndrewBelt** [comment]
Looks like a problem with your login token.
A solution would be to log out and back in again.
BUT BEFORE you do that, email me in private your `settings.json` file so I can see what's up with your account. It contains your login token key, so don't post it here.

**Comment by Suitundo** [comment]
Logging out and back in again also didn't help, tried that already.

I tried sending it useless or now, and got this back from your mailserver: 
550 We do not accept .zip attachments here.

**Comment by AndrewBelt** [comment]
You could either open the file with a text editor and copy/paste the contents of the email, or use https://send.firefox.com/ and email me the URL.

**Comment by odahan** [comment]
I have a similar problem (W10 up to date). But zip file are correctly downloaded in the plugins folder. But they are not installed. I just unzipped each one and it was ok.
But there is a problem in the download/setup of modules for sure.

**Comment by AndrewBelt** [comment]
Fixed on the server's end a few days ago.
