### ISSUE TITLE
(v 0.4.0) Saved patches from previous version can't find updated modules when loaded

### ISSUE THREAD

**Issue by Suitundo** [VCVRack/Rack#236]
OS (if applicable): Win 10, x64, build 1703
Version (or "dev" if compiling from source): 0.4.0

When I load my 0.3.2 patches in the new version, it can't find several modules that are available and updated to 0.4.0. After a couple of attempts and loading up a big patch ( Mattix.vcv, see zip file ) I downloaded from a patchsite, Rack crashes now when I try to load up my patches.
So I can't make a screenshot of the message I get anymore.

[patches.zip](https://github.com/VCVRack/Rack/files/1384736/patches.zip)

**Comment by AndrewBelt** [comment]
Delete your autosave.vcv to recover from a crash-on-boot.

**Comment by Suitundo** [comment]
That doesn't work when I try loading up a patch. It still hangs Rack.
I'll reinstall Rack to get the screenshot then.

**Comment by AndrewBelt** [comment]
This issue is old and likely obsolete. Comment if issue is still present. Closing.
