### ISSUE TITLE
Plug LEDs for stacked cables

### ISSUE THREAD

**Issue by martin-lueders** [VCVRack/Rack#237]
OS (if applicable): all
Version (or "dev" if compiling from source): 0.4.0

I noticed that when cables are stacked together, the halos of the plug LEDs all seem to add up.
In one case I had about cables stacked from one output, and the LED halo looks weirdly and unnaturally bright. For only few cables, it is hardly visible.

I guess only one LED (or at least only one halo) should be active.

Cheers,
Martin

**Comment by AndrewBelt** [comment]
This was fixed in v1, and v2 will have no light glow/halo at all.
