### ISSUE TITLE
Crash when selecting same MIDI interface

### ISSUE THREAD

**Issue by eres-j** [VCVRack/Rack#238]
OS (if applicable): Windows 7
Version (or "dev" if compiling from source): 0.4.0
Steps to reproduce:
  - Add Midi to CV module and select a MIDI interface.
  - Add CC to CV module and select the same MIDI interface as previous step.
  - Crash

**Comment by bontric** [comment]
I currently working on this. If you want you can test my updated branch.
See #223

**Comment by eres-j** [comment]
Tested and approved :+1: 
Not sure if I should close this ticket now or after the merge of your branch.

**Comment by asbaklm** [comment]
I am seeing a similar error, when selecting MIDI interface in Jack, rack crashes

**Comment by bontric** [comment]
@eres-j  Cool, I think it's a good idea to live this issue open so other people can see that we are working on this

@asbaklm Yeah, there are some things that will not work properly on this branch. I'm working on making this work properly, I think I'll have an update ready later tonight

**Comment by asbaklm** [comment]
Thanks a lot!

**Comment by bontric** [comment]
@asbaklm , @eres-j , @Strum This should be fixed on my branch. If you find the time, would be good if you could test it. There should also be no more problems with loading save files etc.

**Comment by eres-j** [comment]
@bontric Got some errors while compiling.
`
In file included from src/core/MidiInterface.cpp:5:0:
src/core/MidiInterface.hpp:16:21: error: 'uint' was not declared in this scope
  std::unordered_map<uint, std::list<std::vector<unsigned char>>> idMessagesMap;
                     ^~~~
src/core/MidiInterface.hpp:16:21: note: suggested alternative: 'rint'
  std::unordered_map<uint, std::list<std::vector<unsigned char>>> idMessagesMap;
                     ^~~~
                     rint
src/core/MidiInterface.hpp:16:64: error: template argument 1 is invalid
  std::unordered_map<uint, std::list<std::vector<unsigned char>>> idMessagesMap;
                                                                ^
src/core/MidiInterface.hpp:16:64: error: template argument 3 is invalid
src/core/MidiInterface.hpp:16:64: error: template argument 4 is invalid
src/core/MidiInterface.hpp:16:64: error: template argument 5 is invalid
src/core/MidiInterface.hpp:17:21: error: 'uint' was not declared in this scope
  std::unordered_map<uint, std::list<double>> idStampsMap;
                     ^~~~
src/core/MidiInterface.hpp:17:21: note: suggested alternative: 'rint'
  std::unordered_map<uint, std::list<double>> idStampsMap;
                     ^~~~
                     rint
src/core/MidiInterface.hpp:17:43: error: template argument 1 is invalid
  std::unordered_map<uint, std::list<double>> idStampsMap;
                                           ^~
src/core/MidiInterface.hpp:17:43: error: template argument 3 is invalid
src/core/MidiInterface.hpp:17:43: error: template argument 4 is invalid
src/core/MidiInterface.hpp:17:43: error: template argument 5 is invalid
src/core/MidiInterface.hpp:18:2: error: 'uint' does not name a type; did you mean 'rint'?
  uint uuid_c = 0;
  ^~~~
  rint
src/core/MidiInterface.hpp:19:2: error: 'uint' does not name a type; did you mean 'rint'?
  uint subscribers = 0;
  ^~~~
  rint
src/core/MidiInterface.hpp:26:2: error: 'uint' does not name a type; did you mean 'rint'?
  uint add() {
  ^~~~
  rint
src/core/MidiInterface.hpp:34:13: error: 'uint' has not been declared
  void erase(uint id) {
             ^~~~
src/core/MidiInterface.hpp: In member function 'void MidiInWrapper::erase(int)':
src/core/MidiInterface.hpp:35:3: error: 'subscribers' was not declared in this scope
   subscribers--;
   ^~~~~~~~~~~
src/core/MidiInterface.hpp:36:17: error: request for member 'erase' in '((MidiInWrapper*)this)->MidiInWrapper::idMessagesMap', which is of non-class type 'int'
   idMessagesMap.erase(id);
                 ^~~~~
src/core/MidiInterface.hpp:37:15: error: request for member 'erase' in '((MidiInWrapper*)this)->MidiInWrapper::idStampsMap', which is of non-class type 'int'
   idStampsMap.erase(id);
               ^~~~~
src/core/MidiInterface.cpp: In member function 'std::vector<std::__cxx11::basic_string<char> > MidiIO::getDevices()':
src/core/MidiInterface.cpp:58:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (int i = 0; i < m->getPortCount(); i++) {
                  ~~^~~~~~~~~~~~~~~~~~~
src/core/MidiInterface.cpp: In member function 'void MidiIO::openDevice(std::__cxx11::string)':
src/core/MidiInterface.cpp:79:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    for (int i = 0; i < mw->getPortCount(); i++) {
                    ~~^~~~~~~~~~~~~~~~~~~~
src/core/MidiInterface.cpp:96:30: error: 'struct MidiInWrapper' has no member named 'add'
  id = midiInMap[deviceName]->add();
                              ^~~
src/core/MidiInterface.cpp: In member function 'double MidiIO::getMessage(std::vector<unsigned char>*)':
src/core/MidiInterface.cpp:116:22: error: 'begin' was not declared in this scope
   for (auto kv : mw->idMessagesMap) {
                      ^~~~~~~~~~~~~
src/core/MidiInterface.cpp:116:22: note: suggested alternative:
In file included from F:/msys64/mingw64/include/c++/7.2.0/list:62:0,
                 from src/core/MidiInterface.cpp:1:
F:/msys64/mingw64/include/c++/7.2.0/bits/range_access.h:87:5: note:   'std::begin'
     begin(_Tp (&__arr)[_Nm])
     ^~~~~
src/core/MidiInterface.cpp:116:22: error: 'end' was not declared in this scope
   for (auto kv : mw->idMessagesMap) {
                      ^~~~~~~~~~~~~
src/core/MidiInterface.cpp:116:22: note: suggested alternative:
In file included from F:/msys64/mingw64/include/c++/7.2.0/list:62:0,
                 from src/core/MidiInterface.cpp:1:
F:/msys64/mingw64/include/c++/7.2.0/bits/range_access.h:97:5: note:   'std::end'
     end(_Tp (&__arr)[_Nm])
     ^~~
src/core/MidiInterface.cpp:122:26: error: invalid types 'int[int]' for array subscript
  if (mw->idMessagesMap[id].size() <= 0) {
                          ^
src/core/MidiInterface.cpp:127:29: error: invalid types 'int[int]' for array subscript
  *msg = mw->idMessagesMap[id].front();
                             ^
src/core/MidiInterface.cpp:128:28: error: invalid types 'int[int]' for array subscript
  stamp = mw->idStampsMap[id].front();
                            ^
src/core/MidiInterface.cpp:129:22: error: invalid types 'int[int]' for array subscript
  mw->idMessagesMap[id].pop_front();
                      ^
src/core/MidiInterface.cpp: In member function 'void MidiIO::close()':
src/core/MidiInterface.cpp:148:10: error: 'struct MidiInWrapper' has no member named 'subscribers'
  if (mw->subscribers == 0) {
          ^~~~~~~~~~~
src/core/MidiInterface.cpp: In member function 'virtual void MidiChoice::onAction()':
src/core/MidiInterface.cpp:176:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (int i = 0; i < deviceNames.size(); i++) {
                  ~~^~~~~~~~~~~~~~~~~~~~
make: *** [compile.mk:51: build/src/core/MidiInterface.cpp.o] Error 1
`

**Comment by asbaklm** [comment]
@bontric 

Issue: In my particular case, it is on OS Linux & Rack master crashing when selecting MIDI interface (w. jack2 using MIDI Xraw)

On your branch this ^ issue appears to be resolved, Rack does not crash any longer when selecting MIDI interface.

**Comment by bontric** [comment]
@eres-j oh.. I'll simply use int's instead of uint, that should fix it. Apparently uint is not a standard type.

@asbaklm Great to hear it works on the new branch. It would be good to know what's going on however. 
If you can find the time it would be great if you could navigate to the master branch in a terminal an do a

```bash
make debug
```
(Note: Assuming you have `gdb` installed if not: `sudo apt-get gdb`)

This will run rack with gdb. Select a midi device and once it crashes, switch to the terminal and
type `bt` and post the output. This gives me the call history and makes it easy to find the actual problem which could be related to [#17](https://github.com/VCVRack/AudibleInstruments/issues/17)

**Comment by eres-j** [comment]
@bontric I didn't read the code but if it make sense to use unsigned, it should be preferable to include [cstdint](http://www.cplusplus.com/reference/cstdint/) and use uint32_t type.

**Comment by bontric** [comment]
Thanks, but it doesn't matter actually. Assuming 32bit integers, someone would need to connect 2^16 midi modules to a single midi device in one session to cause an overflow :octopus:

**Comment by eres-j** [comment]
I confirm all my issues has been fixed :)

**Comment by asbaklm** [comment]
@bontric 

Hi there, here's the gdb output from yesterday's Rack master build. (and jackdmp running with Xraw MIDI).
PS, when running jackdmp with Xseq, it does not crash when selecting MIDI device.


`LD_LIBRARY_PATH=dep/lib gdb -ex run ./Rack
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./Rack...done.
Starting program: /opt/Rack/Rack 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Current working directory is /opt/Rack
Loading plugins from ./plugins
Failed to load library ./plugins/nysthi/plugin.so: ./plugins/nysthi/plugin.so: cannot open shared object file: No such file or directory
Loaded plugin ./plugins/VCVRack-Simple/plugin.so
Loaded plugin ./plugins/ML_modules/plugin.so
Failed to load library ./plugins/vcvrackplugins_dekstop/plugin.so: ./plugins/vcvrackplugins_dekstop/plugin.so: cannot open shared object file: No such file or directory
Failed to load library ./plugins/av500/plugin.so: ./plugins/av500/plugin.so: cannot open shared object file: No such file or directory
Loaded plugin ./plugins/Strums_Mental_VCV_Modules/plugin.so
0x7128f0 0x7fffed49adf0
Loaded plugin ./plugins/Autodafe-Drums/plugin.so
Loaded plugin ./plugins/ESeries/plugin.so
Loaded plugin ./plugins/AudibleInstruments/plugin.so
Loaded plugin ./plugins/Fundamental/plugin.so
Loaded plugin ./plugins/vcv_luckyxxl/plugin.so
Loaded plugin ./plugins/MS_modules/plugin.so
Loaded plugin ./plugins/VultModules/plugin.so
Loaded plugin ./plugins/Autodafe/plugin.so
Loaded plugin ./plugins/Befaco/plugin.so
Loaded plugin ./plugins/sonusmodular/plugin.so
Loading plugins from ./plugins
Loaded font ./res/DejaVuSans.ttf
Loading settings ./settings.json
Loading patch ./autosave.vcv
[New Thread 0x7fffe9290700 (LWP 6248)]
Loaded SVG ./res/ComponentLibrary/ScrewSilver.svg
Loaded SVG ./res/ComponentLibrary/LEDButton.svg
Loaded SVG ./res/ComponentLibrary/PJ3410.svg

MidiInAlsa::openPort: ALSA error making port connection.

terminate called after throwing an instance of 'RtMidiError'
  what():  MidiInAlsa::openPort: ALSA error making port connection.

Thread 1 "Rack" received signal SIGABRT, Aborted.
0x00007ffff4f97428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
`

**Comment by bontric** [comment]
@asbaklm Thank you very much! This actually makes sense. I suppose Xraw does not support multiple connections to one device () which causes the crash.  This is resolved on the new branch since I don't open the device multiple times.

**Comment by asbaklm** [comment]
Super! Thank you so much sir, glad it was useful.
