### ISSUE TITLE
Crash when selecting MIDI Interface in MIDI to CV module under Jack in Linux

### ISSUE THREAD

**Issue by asbaklm** [VCVRack/Rack#239]
OS (if applicable): Linux
Version (or "dev" if compiling from source): dev

To reproduce:  Start jack on Linux, run vcvrack, add MIDI to CV module, select MIDI hardware interface and vcvrack crashes.

Crash does not occur when running under ALSA.

**Comment by bontric** [comment]
Strange, I'm using jack and (arch) linux and I have not encountered this. Which branch are you on ?

**Comment by asbaklm** [comment]
Master branch

**Comment by bontric** [comment]
Can you test this on my branch (See #223). I just want to know whether this is related.

Which linux distro/version are you using?

**Comment by asbaklm** [comment]
I did some more digging and it looks like the crashing occurs when jackd MIDI driver is set is set to run with Xraw. It doesn't crash when set to Xseq

I am using Mint 18 aka Ubuntu 16.04 but I think the problem may be related to Xraw ^

**Comment by bontric** [comment]
Hmm.. I can't reproduce this. Are you using jack or jack2. 
And can you post the output of:

```bash
jackd --version
```

**Comment by asbaklm** [comment]
I am using jack2.  jackdmp 1.9.11
I tried it with your branch (2017-10-bontric-midi-interface-revamp) and it does not crash any longer when using Xraw and adding the MIDI device. I haven't tested any further at this stage.

Rack (at least, the version from a 3 hours ago) crashes when adding the MIDI device.

**Comment by LKHSogpit** [comment]
Same crashes on windows 7 Runtime error. Not using Jack just selecting midi device causes crash. On 0.3.0 had 4 midi devices only have 1 now midi keyboard with a 0 at the end of the name.
