### ISSUE TITLE
Order of params and wire inputs/outputs should refer to Module ids, not ModuleWidget ids

### ISSUE THREAD

**Issue by antoniotuzzi** [VCVRack/Rack#240]
@AndrewBelt 
OS (if applicable): any
Version (or "dev" if compiling from source): 0.4.0

I've just noticed that the wires ID for the connections are positional ?

let's say I have these **INPUTS** in a module **ALPHA**
> 	enum InputIds {
>         IN_INPUT_A,
>         IN_INPUT_B,
>         IN_INPUT_C,
>
> 		NUM_INPUTS
> 	};
> 

and I connect a wire from module **ID0** to module ALPHA with **ID1** and wire is connected to **IN_INPUT_C**

in the json appears

>   "wires": [
>     {
>       "outputModuleId": 0,
>       "outputId": 0,
>       "inputModuleId": 1,
>       "inputId": 2
>     }

the file is saved...
now let's say I decide to include a NEW input in my new release

so I'll have
> 	enum InputIds {
>         IN_INPUT_A,
>         IN_INPUT_B,
>         IN_INPUT_C,
>
>         IN_INPUT_NEW,
>
> 		NUM_INPUTS
> 	};
> 

but in the UI I insert visually the new INPUT after the **IN_INPUT_A**
(the inputPort **IN_INPUT_NEW** is create before the **IN_INPUT_B** )

when I reopen the saved file, the connection is not anymoreto **IN_INPUT_C** but to **IN_INPUT_B**
like there was a shift in the UI due to the new INPUT

am I wrong ?

**Comment by AndrewBelt** [comment]
The numbers in the JSON file correspond to the order you call `addInput()` when constructing the GUI. It has nothing to do with the enums. If you want to add an input without breaking patch files, call `addInput()` after the existing ones.

**Comment by antoniotuzzi** [comment]
wouldn't be better to respect the list of inputs ?

So developer knowings it and adding new INPUTS at the end of their list will never break the connections

but I know it's too late... :)

**Comment by AndrewBelt** [comment]
It's not too late. What's your proposal for keeping connection lists constant?

**Comment by antoniotuzzi** [comment]
as the **createInput** contains the **inputId** and is stored in
**port->portId**
 couldn't we use this ? (that is directly dependent of the plugin developer declarations

**Comment by AndrewBelt** [comment]
Hmm, sure.
Ideally I should probably do some version checking on old patches to convert them to the new port IDs.
I should also do this to parameters as well.

**Comment by antoniotuzzi** [comment]
2 👍  up ! :)

**Comment by AndrewBelt** [comment]
Okay, so I can hard-code some logic to test for v0.5 or earlier and then use an old version of `RackWidget::fromJson`, *but* patches made on "dev" versions will break because there's no way to be able to tell the difference. Maybe I could add version anyway and put the build hash or something.

**Comment by AndrewBelt** [comment]
My current plan is to do a patch version check for all previous public versions "0.3.*", "0.4.*", "0.5.*" and if matched, use the old loader method. This will break old patches made with the development version of Rack, which either reports its version as "dev" or an empty string.

**Comment by AndrewBelt** [comment]
Fixed in 3a8dc0e0e3a0442bfd89461600fa9db8fdc5f4c3
