### ISSUE TITLE
Missing library error in linux (lubuntu 17.04)

### ISSUE THREAD

**Issue by builddroid** [VCVRack/Rack#242]
OS (if applicable): lubuntu 17.04
Version (or "dev" if compiling from source): 0.4

When trying to run from command line (either wrapper shell script or executable file) I get the following error:

"error while loading shared libraries: librtmidi.so.4: cannot open shared object file: No such file or directory"

The zip file has librtmidi.so, but the error is that librtmidi.so.4 cannnot be found.

**Comment by AndrewBelt** [comment]
Did you rebuild dependencies with `cd dep; make`? Did you launch rack with `make run`?

**Comment by builddroid** [comment]
I didn't build it - I downloaded the zip from the website as the previous precompiled version worked out of the box, so I assumed this one would.

**Comment by AndrewBelt** [comment]
In that case, did you use `./Rack.sh` to launch instead of `./Rack`?

**Comment by builddroid** [comment]
Yes, I tried the shell script both from file manager and from the command line

**Comment by AndrewBelt** [comment]
Oh, my mistake! I included the shared library with an incorrect filename! I'm surprised no one has mentioned this before. Fix my renaming the file:

    mv librtmidi.so librtmidi.so.4

**Comment by builddroid** [comment]
Yep, that was it, and no version errors once it's up and running.

Thanks!

**Comment by AndrewBelt** [comment]
I've updated the .zip file on the website. Thanks for the notification
