### ISSUE TITLE
Make sure the unzipper overwrites files and directories

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/Rack#243]
Especially on Windows. It doesn't look like this is being done, resulting in a lot of people with old v0.3.2 plugins.

**Comment by TronicLabs** [comment]
zip file need special permission to unzip and modify existent file in non user data folder

**Comment by AndrewBelt** [comment]
Rack uses it's own unzipper, not the operating system's, so this doesn't apply here.

**Comment by TronicLabs** [comment]
still the permission needed in windows folder for non user data, like /programs file/

**Comment by AndrewBelt** [comment]
Oh sure. But if the user unzipped the Rack distribution in a folder and launches Rack, isn't it guaranteed that Rack will have write permission to that folder?

**Comment by TronicLabs** [comment]
unfortunately in windows no, the application needs to acquire permissions through internalapp manifest configuration or invoked by the user, and it depends on the current user level how the behavior will work as default action

**Comment by AndrewBelt** [comment]
It is planned for v0.5.0 to put Rack plugins and settings in My Documents/Rack. Everything in Program Files (the new install location) may be read-only and that's fine. Is My Documents always writable? Is there a better directory choice?

**Comment by TronicLabs** [comment]
the better directory is the %appdata% environment folder

**Comment by AndrewBelt** [comment]
Isn't that not easily accessible by the average Windows user?

**Comment by TronicLabs** [comment]
mmm, in windows 10 just paste %appdata% in the search bar an hit enter

**Comment by TronicLabs** [comment]
however, you do not have much choice, using this folder is almost mandatory if you want to have access from every level user

**Comment by AndrewBelt** [comment]
Doesn't Native Instruments use My Documents? I guess it's still a bit invasive to put it in that folder.

**Comment by AndrewBelt** [comment]
Oh yes, I forgot about multi user. I suppose I'll use appdata then and a button on the Rack interface to open the folder.

**Comment by TronicLabs** [comment]
Native Instruments use an Installer Application, and with it you can do much things.

**Comment by AndrewBelt** [comment]
I guess by this logic, I should move the local Rack folder on Mac from `~/Documents/Rack/` to `~/Library/Application Support/Rack/`. Not sure if I want to do that either. In response to the multi-user point, 1) essentially no one shares a computer with other people using OS multi-user, and 2) it's okay if they have different Rack local folders. So I ask again: is `My Documents/` always writable by the user?

**Comment by antoniotuzzi** [comment]
what happen if plugins, example, ALPHA are in both folder ?
there will be a clash of symbols ? (I know that now, the loading is excluded for with an error)
(at least to give a gentle message: "duplicated plugins ALPHA" in both "position A", "position B" ect.)
or both can be loaded, with a PREFIX in the names

>  positionA/ALPHA
>  positionB/ALPHA

**Comment by antoniotuzzi** [comment]
(anyway, I never shared my computer.... 👍  )

**Comment by AndrewBelt** [comment]
Yes, now it fails with an error. For v0.5.0, the Whatever.cpp and Whatever.hpp plugins will be replaced with a JSON file with metadata like urls and the slug. plugin.dll/dylib/so can be named anything you like, and you can have multiple of these dynamic libraries in a plugin folder, one for each module if you like. 
Ill document these changes for plugin developers. Still need to think about the details.

**Comment by AndrewBelt** [comment]
Fixed with 33e8973bf17ff35f014118dae1bd158a7785956f
