### ISSUE TITLE
Suggestion : How about being able to run Rack on multiple machines and have them communicate via networking

### ISSUE THREAD

**Issue by Strum** [VCVRack/Rack#244]
Just a thought but for complex patches it would be cool to be able to run rack on several machines and have them share audio and control signals between them.

**Comment by AndrewBelt** [comment]
A commercial plugin is planned for that. It will use a different protocol than the VCV Bridge (which is a protocol over TCP, bound to localhost) and will support low-latency mode and high-latency low bandwidth mode. Still pretty early to say anything else for certain though.

**Comment by Strum** [comment]
cool, look forward to seeing that.
