### ISSUE TITLE
How do I initialise a module when an instance of it is created?

### ISSUE THREAD

**Issue by Strum** [VCVRack/Rack#249]
I've been trying to make a module initialise when it's created but can't understand how other modules do it.

I find an initialisation function but can't find where it's called from, the function name only occurs once in the file in most of the modules I've looked at.

i tried copying initialise function code from modules into my module but it doesn't work.

what am I missing here?

**Comment by AndrewBelt** [comment]
I agree this is confusing, so this prompts me to finally rename that method to `reset()`  

To answer your question, do initialization in the constructor of your Module subclass.

**Comment by AndrewBelt** [comment]
`initialize()` is only called when the user hits Ctrl+I or "Initialize" from the context menu.

**Comment by Strum** [comment]
Thanks Andrew, I think I get it now , I wasn't thinking clearly, just do it in the constructor of course. I had worked that out after making my post.

those functions are called from the context menu or by events occurring in the gui right?

thanks for your time again.

**Comment by AndrewBelt** [comment]
Right, that's the only place they're called. In ModuleWidget.cpp

**Comment by Strum** [comment]
Hmmm, so I have tried to use a for loop to initialise an array in the constructor but now i am getting this

error: expected unqualified-id before 'for'
