### ISSUE TITLE
Subreddit

### ISSUE THREAD

**Issue by cbrpnk** [VCVRack/Rack#251]
I've created a subreddit for Rack https://www.reddit.com/r/vcvrack/
Andrew, what is your username so I can invite you to be a moderator?

**Comment by AndrewBelt** [comment]
Cool, I'm Vortico!

**Comment by cbrpnk** [comment]
Done. I really hope this could be a thing.

**Comment by Strum** [comment]
@cbrpnk there is a freenode irc channel if you are interested

#VCVRack

**Comment by cbrpnk** [comment]
Awesome, I'll make sure to check it out!

**Comment by Atavic** [comment]
Maybe this [video](https://www.youtube.com/watch?v=EPeV-R4YORY) can be handy as a demo?
