### ISSUE TITLE
Feature request : VCO/SEQ3 should display note/volt/Hz

### ISSUE THREAD

**Issue by odahan** [VCVRack/Rack#255]
OS (if applicable): ALL
Version (or "dev" if compiling from source): ALL

Apart the need for tuner, it is a pain in the ass to create sequences or to tune VCOs because they all have a "blind display". When moving the main knob of a VCO how to know how much semi-tones are added or subtracted ? The same for the SEQ3. But this problem is general for all units producing frequencies or voltage.

Proposed solution :
Perhaps a switch on these modules should offer "no display" (as currently) "Hz display" "Volt display" "Note display". This switch as not to modify the current UI of modules and can be placed as options in the local menu of these modules.
The display itself, when switched on, could appear just below the knob.
This parameter should be local for each module and not global because a VCO can be used to generated a given frequence (display in Hz) or a given note (display Note). Volt display is not for VCO but more for SEQ3 (and all other sequencer) as a knob can be used to generate a given voltage or a given note (but not a given frequency). 
So theses options should be available only when they make sense of course.
(frequency can have sense for a filter for example).
This will concern all "official" modules, but all other module authors should follow this rule.

Well, knowing what we are doing can help much and seeing in a glance which note or frequency is generated by a VCO, a sequencer, etc, could be very helpful.

**Comment by bontric** [comment]
I also think this would be a great feature. Just a tip:

https://github.com/luckyxxl/vcv_luckyxxl

Gives you a "Quantize" module which should help you tune your VCO's

**Comment by AndrewBelt** [comment]
Yes, this issue will be solved when #233 is completed.

**Comment by odahan** [comment]
It is near from #233 but it is not exactly the same thing.
#233 is speaking about tooltips showing all values or any parameter when the latter is under the mouse.
Here I'm speaking about a constant display of the values but as an option, and with special units (Hz, Volt, Note name) that can be read in a glance for all modules (with a choice module by module).
This feature does not need to display all values, just mostly the ones allowing to tune VCO or Sequencers. VCF frenquency for example can be left for the #233 solution.
The two features are not the same and are not exclusive, in a wonderful world both will be implemented :-)
I'm using the luckyxxl plugins but it is not so easy. You still l don't know which note you're programming / playing.
Knowing the notes is not important for producing blips & beeps but when it comes to play music notes have at least a little importance... :-)

**Comment by odahan** [comment]
Is see #233 as a very cool and light way to display all values of any setting just flying the mouse over the controls.
In the current request I'm more speaking about a permanent display of note name / voltage for modules where it is _relevant_ such as VCO main frequency knob and Sequencer knobs.
This is a very simple thinh but it can become a mess if all values or all knobs are displayed, for sure. So VCO's and Sequencers will be the main target of such a feature. #233 will cover all other needs.
When you create a sequence or look at a multiple sequencers in a rack it will be really cool to see note names to compare, check etc.
The unit should be selected by the user (note name, Hz or Volt).
But you will have the same problem when implementing #233 If the tooltip is just showing a value in 0..255 range for example (or 0.65535) I'm not sure this will help anyone. Sometime you need to know the number of Volt, or the frequency in Hz .. or the note name.
How this will be addressed in  #233 ?

**Comment by AndrewBelt** [comment]
Tooltips will display customized information.

I really think your issue would be solved with a tuner module, since the only example you've given is tuning VCOs.

**Comment by odahan** [comment]
A tuner is just displaying one value at a time, the one of its input. This can be perfect in most situations (mainly with VCOs).
What I was speaking about is a permanent display of note names in SEQ3 for example. You can see immediately the 3rd knob is a C# without connecting the sequencer to a tuner, making it running until it hits the 3rd note to read the tuner and see it is a C#...
But perhaps a tuner and #233 will address most needs. And the problem of note names is just something specific to sequencers. In this case this is a SEQ3 feature and not a global VCV one.
As for the need to save a sequence and reload it. This can be solved for all settings of all modules if you can save under a given name the settings of each module, it will be cool (Ableton Live, Bitwing are doing this) but perhaps at least in the first times this can be just a simple feature of SEQ3 only.

So if a tuner and solution #233 will certainly cover most of the needs, there is just something to do to enhance SEQ3 : note names display, load/save row values. And perhaps extending some of its functionalities (random read, 3x8 or 16+8 or 24 snake walk mode).
Must I modify this entry or create a new issue to target specifically SEQ3 ?

**Comment by AndrewBelt** [comment]
SEQ3 generates voltages, not "note names".

Closing this, since adding to SEQ3 would be "wrong", and adding to VCO would make the panel ugly.

**Comment by odahan** [comment]
You're right. However sequencers are very often used to generate note sequences, melodies, and to tell the truth there is a direct relationship between notes and voltages , 1V/octave, so note names and voltages are (almost) the same information in a eurorack context. Giving the note name will not be something so astonishing in a environment that precisely defines the relationship between these two concepts.
I think that even In VCO-1 for example there is room to write "Bb3" or "C3" under the knob without messing all the UI. And this will be very useful in a lot of common situations.
Well, it is just a proposal, but working a lot on VCV not just to make bleeps and beeps I know I'm very frustrated when it come to create a melodic sequence on SEQ3 or the set a VCO to a given note. Too much a "blind mode" currently. I don't have the chance to have absolute pitch, ok, it's my bad :-)
