### ISSUE TITLE
Trying to compile

### ISSUE THREAD

**Issue by Retroperra** [VCVRack/Rack#256]
OS-X 10.9.5
Rack version 0.40

I'm trying to compile some plugins but also Rack itself.
After 'make dep' and waiting a while I got:
```
#######################################
# Built all dependencies successfully #
#######################################
```

That felt nice, I messed up with cmake earlier.

So I do  'make'  - to compile Rack - and this is where it fails.

I got:
```
include/widgets.hpp:5:10: fatal error: '../ext/nanovg/src/nanovg.h' file not found
```

All four folders inside ext are empty. The folders 'nanovg' for instance are there but empty.

While trying to compile any plugin I get the same error.

Any clues as where to start digging?

**Comment by bontric** [comment]
Looks like you forgot
```bash
git submodule update --init --recursive
```
before 
```bash
make dep
```

Hope this helps.

**Comment by Retroperra** [comment]
Thanks!

**Comment by Retroperra** [comment]
I'm feeling like a three year old... or one of my students...

**Comment by bontric** [comment]
Hmm did you do a `git clone` or copy the folder? This looks like the folder you are using does not contain a `.git` folder and is therefore not recognized as a git repository

> I'm feeling like a three year old... or one of my students...

Git can be confusing if you don't use it a lot. Don 't worry. (And if it makes you feel better.. others are doing the same mistakes e.g. #246 :wink: )

**Comment by AndrewBelt** [comment]
Follow the instructions in the README, and if you have another question, reopen this issue.
