### ISSUE TITLE
unknown warning option '-Wsuggest-override'

### ISSUE THREAD

**Issue by srizzi88** [VCVRack/Rack#257]
OS (if applicable): OS X 10.11.6
Version (or "dev" if compiling from source): dev
Xcode 8.0 (8A218a)

After pulling the latest commit and rebuilding the project I am getting:
"warning: unknown warning option '-Wsuggest-override'; did you mean '-Wshift-overflow'? [-Wunknown-warning-option]"
for every source file that make tries to compile

**Comment by AndrewBelt** [comment]
It's intentional. Using GCC (which actually supports this warning), I will make sure all the overriding methods are marked `override` with #252, and once I'm done I'll make the option conditional when clang is used.
