### ISSUE TITLE
Can not paste in password field.

### ISSUE THREAD

**Issue by oblivionratula** [VCVRack/Rack#26]
On Mac OS 10.10.5 - don't know if it's a universal problem. 

I use a password manager and create complex passwords. I had to manually type it in (which took 3 tries because I'm apparently an idiot) because paste did not work. Obviously minor, but annoying.

**Comment by eshy** [comment]
It's the same on Windows 10, had the same problem for the same reason. 

When fixing this low priority issue it would be nice to add a little checkbox to remember the account details

**Comment by AndrewBelt** [comment]
I'll add paste, and account remembering will be the default. I should generate a `settings.json` file along with the `autosave.json` file with cable settings, etc.

**Comment by AndrewBelt** [comment]
Fixed with 45d90342f931f313b5f22d61e1327425eed2556a

**Comment by AndrewBelt** [comment]
Also, added auth token to settings.json, so it will be autosaved when logging in. bf2032c3e0ff53ce7afccaa64b3296c9055fad84

**Comment by oblivionratula** [comment]
Thx.

**Comment by oblivionratula** [comment]
FYI, a build of a fresh git pull is now failing, it seems related to this fix (OSX 10.10.5):

` make > make.txt
In file included from src/app.cpp:1:
include/app.hpp:138:7: warning: 'rack::ParamWidget::onMouseDown' hides
      overloaded virtual function [-Woverloaded-virtual]
        void onMouseDown(int button);
             ^
include/widgets.hpp:92:18: note: hidden overloaded virtual function
      'rack::Widget::onMouseDown' declared here: different number of parameters
      (2 vs 1)
        virtual Widget *onMouseDown(Vec pos, int button);
                        ^
1 warning generated.
src/engine.cpp:101:8: warning: unused variable 'duration' [-Wunused-variable]
                auto duration = std::chrono::nanoseconds((long) (0.10 * ...
                     ^
1 warning generated.
In file included from src/gui.cpp:3:
In file included from include/gui.hpp:2:
include/app.hpp:138:7: warning: 'rack::ParamWidget::onMouseDown' hides
      overloaded virtual function [-Woverloaded-virtual]
        void onMouseDown(int button);
             ^
include/widgets.hpp:92:18: note: hidden overloaded virtual function
      'rack::Widget::onMouseDown' declared here: different number of parameters
      (2 vs 1)
        virtual Widget *onMouseDown(Vec pos, int button);
                        ^
src/gui.cpp:39:7: error: use of undeclared identifier 'guiIsKeyPressed'
                if (guiIsKeyPressed(GLFW_KEY_LEFT_CONTROL) || guiIsKeyPr...
                    ^
src/gui.cpp:39:49: error: use of undeclared identifier 'guiIsKeyPressed'
                if (guiIsKeyPressed(GLFW_KEY_LEFT_CONTROL) || guiIsKeyPr...
                                                              ^
1 warning and 2 errors generated.
make: *** [build/src/gui.cpp.o] Error 1`

**Comment by AndrewBelt** [comment]
Fixed in 323234edc4fd953f329468054cb6a624f9bb6b65
