### ISSUE TITLE
As soon any "Audible Instruments" knob is touched, the application crashes

### ISSUE THREAD

**Issue by killkrt** [VCVRack/Rack#260]
OS (if applicable): Arch Linux (4.13.7-1-ARCH #1 SMP PREEMPT Sat Oct 14 20:13:26 CEST 2017 x86_64 GNU/Linux)
Version (or "dev" if compiling from source): revision 275204c378c0e4c0b935acb4ed8ecb88ae883c1c

Every time that I try to just "touch" (click with mouse) on a knob of any of "Audible Instruments" module, the application crashes.

Core dump file is pretty huge (about 10M when zipped), not sure if it could help.

**Comment by AndrewBelt** [comment]
Sounds like ABI incompatibility. Are the builds up to date? `make` on both Rack and plugins?

**Comment by killkrt** [comment]
Ok, I've tried to install plugins via git and run `make` and it works.
Yesterday I've used the "Refresh plugins" functionality from the UI.

So it's solved, but anyway I cannot understand how to use "Refresh plugins" since it seems not to lunch the `make` command.

**Comment by AndrewBelt** [comment]
Great!

Refresh plugins re-downloads official plugins that you have added to your vcvrack.com account.
