### ISSUE TITLE
Feature request: Mono mode for audio interfaces

### ISSUE THREAD

**Issue by mcclure** [VCVRack/Rack#262]
OS (if applicable): OS X
Version (or "dev" if compiling from source): v0.4.0

Say I open Rack and create a sound source (a VCO, say) and a Core->Audio Interface. I select "Core Audio: Built In Output" as my device. I connect the VCO to output "1". Right now, on my mac, when I do this, it plays audio out of the left speaker only. Experimenting, it appears that out of the 8 listed "outputs" on the Core Audio audio interface, output 1 is left speaker and output 2 is right speaker. The other outputs do nothing. I assume if my default audio interface were surround sound, outputs 3 and 4 would become enabled.

I understand that this feature is so that I can address the channels of my audio interfaces separately and therefore do stereo effects. Okay, that is neat. However it is not my normal use case and it is not the "simple" case. When I am doing simple things, I do not want to address channels separately, I just want to play a sound. Right now, in order to get the "simple" case (I have one output and it plays to all channels) I must create a Audible Instruments->Multiples and feed the output through it to branch my audio to outputs 1 and 2. Multiples is not even installed by default in Rack.

My suggestion: For both "outputs" and "inputs" on audio interfaces, create a separate "mono" jack. Pumping audio into the Outputs "mono" jack should send all bytes equally to all channels. Drawing audio out of the Inputs "mono" channel should mix all inputs together and emit the mixed result.

An alternate way to achieve this would be to create a "Mono Audio Device" module which has only the mono jack(s) instead of having all individual channels.

**Comment by AndrewBelt** [comment]
Just use stackable cables after a mixer. Also some of this is mentioned in #82 for the Master Audio Interface.
