### ISSUE TITLE
Begin using semantic versioning

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/Rack#266]
Starting with Rack v1.0, versions of Rack and its plugins should use the [semantic versioning](https://semver.org/) scheme.

Until Rack v1.0, the above scheme is used, except MINOR version numbers are not backwards compatible. This is roughly equivalent to using semantic versioning except prepended with "v0.".

### Before Rack v1.0

In the vMAJOR.MINOR.REVISION scheme, vMAJOR.MINOR is the compatibility verison with Rack and REVISION is the revision of your plugin. For example, v0.5.* plugins are all compatible with Rack v0.5.*.

### After Rack v1.0

In the vMAJOR.MINOR.REVISION scheme, vMAJOR is the compatibility verison with Rack and MINOR.REVISION is the revision of your plugin. For example, v1.* plugins are all compatible with Rack v1.*.

**Comment by Strum** [comment]
Do you envision many major changes to the API in the future?

**Comment by AndrewBelt** [comment]
A complete ballpark answer is about 5-10 major releases in the first year after v1.0.

**Comment by jeremywen** [comment]
Is this just a recommendation for the zipped plugin file name and the git tag to help users and devs?  You aren't referring to the internal values, right?

**Comment by AndrewBelt** [comment]
Yes, this refers to the zip file, the git tag, and the plugin metadata #254 which is not yet added. After #254 is completed, your plugin should add

    plugin->version = TOSTRING(VERSION);

in the `init()` function, and when finalizing builds, do

    git tag v0.4.0
    git push --tags
    make VERSION=0.4.0 dist

**Comment by AndrewBelt** [comment]
I've tagged v0.4.0 in each official plugin in the VCVRack Github organization.

**Comment by antoniograzioli** [comment]
where do we define plugin VERSION to be used in "plugin->version = TOSTRING(VERSION)" ??
Should "Version" reflect our "Internal" version or Rack Version?

**Comment by AndrewBelt** [comment]
Yes, it's internal. `make VERSION=0.4.0` and `make VERSION=0.4.0 dist` when you build.

**Comment by antoniograzioli** [comment]
OK, maybe I am just dumb...but is the version displayed anywhere on modules list once we build using "make VERSION=0.4.0" ?

**Comment by AndrewBelt** [comment]
Not anymore, but it'll be readded. It'll always be optional but recommended.

**Comment by antoniograzioli** [comment]
OK good then. In the meantime I have added it to my plugins, just because ;-)

**Comment by AndrewBelt** [comment]
Semantic versioning is fully implemented now in Rack v1.
