### ISSUE TITLE
Bug - Store GUI preferences

### ISSUE THREAD

**Issue by Nowhk** [VCVRack/Rack#268]
OS (if applicable): Windows 10 Professional 64bit
Version (or "dev" if compiling from source): 0.4.0

When I start Rack, its not able to "save" my custom preferences from previous session.
For example: if I set Cable tension 1.0, when I restart Rack, it returns to 0.5. The same with opacity and sample rate.

**Comment by AndrewBelt** [comment]
Where have you installed Rack?

**Comment by Nowhk** [comment]
C:\Program Files\Rack

**Comment by AndrewBelt** [comment]
Rack is unable to write to that location. Move the application to Downloads in your user directory or something for now, where Rack has write access. This will be fixed in #265 with a global installer.
