### ISSUE TITLE
override warning incompatible with older GCC

### ISSUE THREAD

**Issue by davephillips** [VCVRack/Rack#269]
Linux Fedora 21 GCC 4.9.2

The -Wsuggest-override warning is not compatible with older versions of GCC. The compiler throws an error, commenting out the warning corrects the error.

**Comment by AndrewBelt** [comment]
That version of GCC is from October 30, 2014. I don't want to support anything on Linux more than two years old.

**Comment by davephillips** [comment]
Understood, not a problem. I have to upgrade this system soon anyway.
