### ISSUE TITLE
Needed to edit Rack.sh

### ISSUE THREAD

**Issue by oblivionratula** [VCVRack/Rack#27]
Finally got this to build on Debian linux (I'll work on compiling all the pre-req packages I ran across), but to actually run, I had to edit Rack.sh to point to the proper lib location after making:

#!/bin/bash
LD_LIBRARY_PATH=./dep/lib/ ./Rack

Not sure if this is a problem with my build or an oversight in the docs.

**Comment by AndrewBelt** [comment]
Use `make run` for the dev branch. The Rack.sh script is for building distributables.

**Comment by oblivionratula** [comment]
OK, then maybe update README.txt instructions?  Also needed in there - how to build the modules? I only show audio and midi . . . .  Thanks.  This is awesome.
