### ISSUE TITLE
Feature request: click cable to highlight

### ISSUE THREAD

**Issue by jpshea** [VCVRack/Rack#270]
Click a cable to highlight
Shift-click to add another cable to the highlighted group
Click anywhere else to de-highlight all

Would be quite handy for "tracing" complex patches. Note that this is just for display purposes only - no other functionality implied.

**Comment by AndrewBelt** [comment]
Groups of cables are too complicated of a UI. 
What you can do instead is turn the cable opacity down and then pick up a cable. It will show as 100% opacity while every other one is dimmed.
