### ISSUE TITLE
Bug - file name not displayed upon first open

### ISSUE THREAD

**Issue by jpshea** [VCVRack/Rack#271]
OS (if applicable): MacOS Sierra 10.12.6
Version (or "dev" if compiling from source): 0.4

When VCVRack is opened (and the previously used file is opened), the file name is not displayed in the title bar.

If another file is loaded, the file name is correctly displayed.

**Comment by AndrewBelt** [comment]
Thanks for pointing that out! Fixed in 7c31edd
