### ISSUE TITLE
0.4.0 compatibility of current builds

### ISSUE THREAD

**Issue by martin-lueders** [VCVRack/Rack#273]
OS (if applicable): Win7
Version (or "dev" if compiling from source): dev

I just recompiled my plugins against the dev sources, and tried to use them in the 0.4.0 binary release.
See the attached error popup. What am I doing wrong? Are the plugins supposed to be compatible with the 0.4.0 binary release?

![2017-10-19_20-08-10](https://user-images.githubusercontent.com/31972064/31789242-65fc3f70-b509-11e7-9958-e4f9e192a1e9.png)

**Comment by AndrewBelt** [comment]
No. dev != v0.4.*
