### ISSUE TITLE
Macbook Fans on full

### ISSUE THREAD

**Issue by bluecameron76** [VCVRack/Rack#274]
OS (if applicable): Sierra 10.12.6
Version (or "dev" if compiling from source): 0.40

Seems to shoot up the fans everytime I use the software.

**Comment by AndrewBelt** [comment]
I'm aware of CPU usage, thanks.

**Comment by gridsystem** [comment]
I have this issue too. My MacBook Pro 2017 actually shuts down most times I have tried to use Rack with it due to overheating.

**Comment by AndrewBelt** [comment]
Follow the #441 thread. However, I'm only interested in technical suggestions/proposals for this problem, not "it happens to me too" or "+1".
