### ISSUE TITLE
build fail with latest git pull

### ISSUE THREAD

**Issue by davephillips** [VCVRack/Rack#275]
Linux
dev version

g++ -Iinclude -Idep/include -Idep/lib/libzip/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -std=c++11 -c -o build/src/core/MidiIO.cpp.o src/core/MidiIO.cpp
src/core/MidiIO.cpp:29:71: error: converting to ‘std::unordered_map<std::basic_string<char>, MidiInWrapper*>’ from initializer list would use explicit constructor ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = std::basic_string<char>; _Tp = MidiInWrapper*; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, MidiInWrapper*> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const std::basic_string<char>, MidiInWrapper*> >]’
 std::unordered_map<std::string, MidiInWrapper *> MidiIO::midiInMap = {};
                                                                       ^
compile.mk:54: recipe for target 'build/src/core/MidiIO.cpp.o' failed
make: *** [build/src/core/MidiIO.cpp.o] Error 1

I realize you're not supporting older compilers. However, I'm not sure if this is a compiler issue, so I've posted the error. Please advise if a fix is do-able for my GCC. If not, it looks like it's time to upgrade the system here at last. Can't live without the latest Rack. :)

**Comment by AndrewBelt** [comment]
Yes, your compiler is out of date. Rack uses C++11, but your compiler does not support the whole C++11 standard it appears.
You might be able to upgrade gcc through a backports repo.

**Comment by davephillips** [comment]
Thanks, Andrew. No, I won't bother trying to upgrade the compiler, it's well past time to upgrade the system, and I have a free weekend. :) Soon I'll be running VCV Rack on something more up-to-date.
And as always, thanks for the wonderful software !
