### ISSUE TITLE
Module presets

### ISSUE THREAD

**Issue by odahan** [VCVRack/Rack#276]
OS (if applicable): all
Version (or "dev" if compiling from source): next..

1/
It will be cool and simple to allow saving any patch as default one. This patch will be open by default any time VCV is launched. It is certainly more efficient than loading the last autosave. If no default patch is set the behavior will stay the same as now (autosave is loaded).

2/
It is very common to use some modules in the same way (at least at start), it should be possible to save a module configuration as default one. Every time a module of the same type is added into the rack it will load the default settings.

3/
Multiple "models" for a module : as in preceding case it is possible to save the current configuration of a module. But instead of a just a default setting, user can give a name to the setting. So using the local menu of a module one can reload immediately a particular setting. Can be very useful to store sequences for example and be able to recall them easily (but one can think about any settings of any module).

Just some ideas... someone else interested in this features ?

**Comment by AndrewBelt** [comment]
1. Solved with 5f311e7e154bed085653e196e4256a32f6c2581a a while ago.
2. I can't think of a clean UX for this.
3. The best UX I can think of it to put "presets" in the right click menu. But with each module having only ~10 knobs max, is it really worth it to learn and use that feature?

**Comment by odahan** [comment]
I was inspired by the way Ableton Live is working for this proposal.
You can set a project as default one when Ableton Live is launched, very useful.
Each module of Ableton (EQ's, reverb, ...) can have a default state saved as default. For example is it useful to get an EQ with frequencies below 40Hz being cut by default. UX is very simple, just use the local menu to save the current state that becomes the default one.
For "named" presets, if we look at how Ableton is doing it, it just creates new entries in the list of modules, these entry are just presets. 

I know there are not a log of knobs on most modules but you know like me that with a modular system (even a normal hardware synth) a little change in a setting can have a huge impact on the resulting sound so the interest to save states. And for Sequencer modules, this is super useful to be able to save 3x8 settings and recall them easily instead of program again the 24 knobs with the same melody / settings.

Just for my information, how to save a set as the default one using the fix  5f311e7 ?

**Comment by AndrewBelt** [comment]
1. Using the source from at most 7 days ago, save a file as `template.vcv` in the same location as `autosave.vcv` and Rack will load it when clicking File > New, instead of clearing the rack.

**Comment by odahan** [comment]
thanks, it's cool to get a default template (midi input and outputs mostly, a mixer... the things you need each time).

**Comment by AndrewBelt** [comment]
Although I'm still not convinced because I can't think of a clean way to save/manage these module-specific settings, I'll call them "presets" for the future. 
Where would presets be saved on disk? Maybe `presets.json`, or maybe it should be plugin-specific.  I imagine there'd be a submenu of the module context menu called "Presets", with items "Save...", "Save default", and one for each preset. I don't know how you would delete presets.

**Comment by Strum** [comment]
You could use a daw and send MIDI control messages to Rack to set modules to presets.

**Comment by AndrewBelt** [comment]
Added module presets in v1 over a year ago.
