### ISSUE TITLE
App Icon difficult to see using Mac Dark theme

### ISSUE THREAD

**Issue by mhetrick** [VCVRack/Rack#28]
The application icon is difficult to see on OS X using the Dark theme.
<img width="205" alt="screenshot 2017-09-11 15 27 49" src="https://user-images.githubusercontent.com/416077/30295355-ee54e984-9705-11e7-973a-1883412e17a0.png">
Perhaps the more vibrant color seen at https://github.com/VCVRack should be used?

**Comment by sbcook0** [comment]
Same problem in the taskbar using default Win10 setup.

**Comment by AndrewBelt** [comment]
Fixed with 4ba58b829d728319bf12b08546455c09388f88a4
