### ISSUE TITLE
Plugin feature request: A pre-draw callback would be nice

### ISSUE THREAD

**Issue by mcclure** [VCVRack/Rack#282]
The struct Widget has a `step` as well as a

     virtual void draw(NVGcontext *vg);

The struct Module, however, has only `step`. This is inconvenient if you have some kind of module operation you want to do only when a frame is about to be drawn. For example say you have a Label widget, and the Module code ought to alter its `text` field. The module is not notified that a frame is about to drawn.

It is in principle possible to subclass a widget and get calls at that time, but it would be more convenient if Module had a `virtual void willDraw();` which is called before draw is performed.

**Comment by mcclure** [comment]
Wait, sorry, i can just use the ModuleWidget for this purpose.

**Comment by AndrewBelt** [comment]
Yes, Module is the audio engine's. ModuleWidget is the GUI for it.
