### ISSUE TITLE
rotary switch: "stops between steps"

### ISSUE THREAD

**Issue by rafzael** [VCVRack/Rack#284]
@AndrewBelt I wonder if you plan to add stop between step of rotary switch (snap knob)

I explain: I saw they are automatically set to particulars positions. What I mean is: do you plan to make it jump from a step to an other witheout sliding move between the  positions.
A friend that test my plugins tells me that it seems that this should make selection easier. 
 I hesitate to do this for my plugins series, but if you believe it's better too, it's simpler to modify this for the next VCV version.

**Comment by AndrewBelt** [comment]
Yup, already fixed this about 2-4 days ago. Subclass a Knob and set snap to true. It will visually and functionally snap to the nearest integer.

**Comment by Strum** [comment]
@AndrewBelt  can you change that on the fly so a knob can be switched between integer and float? or is it set when you instantiate the gui?

**Comment by AndrewBelt** [comment]
Yes, you can change it on the fly with the `step` boolean field.

**Comment by Strum** [comment]
cool i was going to make a knobs module for control and that feature will save a bit of code.
