### ISSUE TITLE
Warning (fontstash.h) in mac build

### ISSUE THREAD

**Issue by lnikj** [VCVRack/Rack#285]
OS (if applicable): 10.11.6
Version (or "dev" if compiling from source): dev

In file included from ext/nanovg/src/nanovg.c:26:
ext/nanovg/src/fontstash.h:891:13: warning: comparison of integers of
      different signs: 'size_t' (aka 'unsigned long') and 'int'
      [-Wsign-compare]
        if (readed != dataSize) goto error;
            ~~~~~~ ^  ~~~~~~~~

**Comment by AndrewBelt** [comment]
It's fine, just ignore.
