### ISSUE TITLE
make dep installation issue

### ISSUE THREAD

**Issue by mschack** [VCVRack/Rack#286]
Windows 10
make dep seems to work fine until it gets to portaudio then I get this...

mv portaudio-r1891-build portaudio
mv: cannot move 'portaudio-r1891-build' to 'portaudio': Permission denied

Any ideas?

**Comment by AndrewBelt** [comment]
Why can't it move the folder? Is there already a folder in place of `portaudio`?

**Comment by mschack** [comment]
I have no idea.  If I manually type the command in the shell it works fine.

**Comment by AndrewBelt** [comment]
You have no idea if there is already a folder in place of `portaudio`? Could you `ls` in that directory?

**Comment by mschack** [comment]
![install issue](https://user-images.githubusercontent.com/32986033/31854082-df915f9c-b661-11e7-92b6-9298e1fa45f0.JPG)

**Comment by mschack** [comment]
I have tried a clean installation three times now, always stops there.  Very strange.

**Comment by mschack** [comment]
Nevermind, just noticed I was doing the make dep from /c/vcv/rack/dep.  Strange that the rest of it worked.  Perhaps the folder changed at some point during installation and I didn't notice.

**Comment by mschack** [comment]
everything seems ok now, thanks.
