### ISSUE TITLE
Feature Request : Keyboard Shortcuts

### ISSUE THREAD

**Issue by Strum** [VCVRack/Rack#287]
Some Keyboard shortcuts for save, plug lights on/off, bringing up modules list and a few other things might be useful

**Comment by AndrewBelt** [comment]
Save is Ctrl+S. Plug Lights seems too obscure to have a key command, but I might reconsider. A key command for "Add Modules" would take longer than just right clicking IMO, and the right click actually specifies the location of the added module.

**Comment by Strum** [comment]
Cool, just a key to bring up the module list would be useful even if you could select from it with keys.

A mute key might be useful as well so that you can just turn the output off and on with a keystroke.

**Comment by Strum** [comment]
@AndrewBelt, I just had a thought then that you could set up a way to use key combinations to move around between modules and then use tab and the arrow keys to control module parameters from the keyboard in much the same way you tab through form fields.

I'm a big fan of keyboard shortcuts, it can make things much faster, mouse is so limited when it comes to controlling things.

Anyway just an idea.

**Comment by AndrewBelt** [comment]
Nice idea, but might be 2 years before it's worth it.

**Comment by Strum** [comment]
@AndrewBelt 

Thanks, maybe put it in your list for possible features in the long term.

At the rate you are going currently it might take less time than you think though.

I'm massively impressed with the rate of progress and how on the ball you are with user feedback.
