### ISSUE TITLE
Fuzzy search for modules

### ISSUE THREAD

**Issue by Euphorbium** [VCVRack/Rack#288]
There are a lot of modules now, and much more is definitely on the way. Navigating through menus is not fast enough. Fuzzy search would be the fastest way to find a module.

**Comment by AndrewBelt** [comment]
It's been mentioned before, but for some reason nobody created an issue for it! So this will track progress on that.

**Comment by AndrewBelt** [comment]
What should be the key command for triggering the dialog? `Enter` might be nice, since it doesn't collide with the upcoming MIDI keyboard and is symmetric (`Enter` also selects the bank.)

Anyone want to contribute a C++ snippet that computes the fitness of a fuzzy search? There are many bad ones but only a few good ones. For example, when searching `osc`, `OSCillator` should be higher than `OStriCh`, and when searching for `808`, `tr808` should be higher than `tr808 expansion` because it's shorter.

**Comment by Euphorbium** [comment]
I think this should work: https://github.com/wincent/command-t/blob/c62079dcce43bbfadba39cf0b7280cd71e34ad3f/ruby/command-t/ext/command-t/match.c

**Comment by Euphorbium** [comment]
Wait, this is much better: https://github.com/forrestthewoods/lib_fts

**Comment by odahan** [comment]
a quick search for modules will be perfect, menus are too slow with a lot of modules.. and we still all have a lot of modules... and it's just the beginning of the story. In one or two years we'll need a true database to search modules !
So anything done to accelerate module search is a good idea.

**Comment by AndrewBelt** [comment]
@Euphorbium Thanks, I hadn't seen the fts implementation. I'll use that.

**Comment by AndrewBelt** [comment]
I'm liking this one. It's configurable. https://github.com/hansonw/fuzzy-native/blob/master/src/score_match.h

**Comment by AndrewBelt** [comment]
I was considering using Enter to open a popup, but I think a better way is to put a search box on the Add Module menu. So you right click, start typing, and hit enter or click the item in the menu that appears.

**Comment by modlfo** [comment]
One suggestion to the current implementation in v0.5 is, when there's only one hit in the search, the module is selected and can be added by pressing enter.

**Comment by MichaelPilyavskiy** [comment]
It can slightly better is plugins will be shown by just navigating to developer name (v0,4 behaviour), so:

current behaviour: rightclick > navigate developer name > click on developer name > click on plugin name to insert
expected: rightclick (or enter) > navigate developer name > after very small time like 0.4 seconds see its plugin list > click on plugin name to insert

Less clicking is good, thanks.

**Comment by mkruselj** [comment]
Right now it seems like right-click add module only filters manufacturers, but not module names. This is not cool at all... How do I get it to search module names, not manufacturer names?

**Comment by AndrewBelt** [comment]
@mkruselj It filters by manufacturer, module name, module slug, and tags. It just categorizes the search results by manufacturer.

**Comment by mkruselj** [comment]
OK so this is confusing to me then: say I type "osc", I **only** get a list of manufacturers.

I would expect ALL modules matching "osc" to be shown in the right side of the browser, regardless of the manufacturer! Then clicking on the manufacturer would filter the list further down. Right now it definitely is fiddly...

**Comment by alitan** [comment]
I would like to propose a favorites tag function. What if we can add the modules we want to the favorites tag and recall them by clicking on the favorites tag (listed at the top of the tags list). This way we can access our goto modules very fast.

**Comment by Shadowhenge** [comment]
I like this idea.  Would expand upon it by allowing for sub-racks.  A group
of pre-wired modules you can place in like a single module.

**Comment by AndrewBelt** [comment]
Searching will switch to a "tokenized substring" search in Rack v2, so "fuzzy search" is no longer needed.

**Comment by alitan** [comment]
I know this feature request is closed but, my proposal for favorites tag is still valid. Should open up another feature request for that. I also love the idea of pre-wired modules to be added to the favorites.
