### ISSUE TITLE
(v 0.4.0 ) No audio devices available ( again )

### ISSUE THREAD

**Issue by Suitundo** [VCVRack/Rack#289]
OS (if applicable): Windows 10, x64, build 1703
Version (or "dev" if compiling from source): 0.4.0

Sadly all my audio devices are gone again in VCVrack when I boot up the program..
Not sure what happened that caused them to disappear, I only installed a few VST plugins.

What dependencies are exactly required for VCVrack?

I installed the Visual C++ 2013 x86 and now the x64 runtimes, but that didn't help.

**Comment by AndrewBelt** [comment]
No dependencies are required for Rack besides the ones bundled with the zip file.

Unfortunately I can't remotely debug audio issues, so I'm closing this. Cross your fingers and hope the migration in #82 to RtAudio inadvertently fixes this.
