### ISSUE TITLE
dep/Makefile targets should be the built library files in dep/lib/

### ISSUE THREAD

**Issue by giuliomoro** [VCVRack/Rack#29]
Currently, if one of the dependencies downloads but fails to build, the `dep/Makefile` will think it is up to date because its targets are the `dep/[libname]` folders while they should be  `dep/lib/[libraryfile]` instead.

**Comment by AndrewBelt** [comment]
Agreed! Only one target file is allowed though, so in the case of packages that produce multiple library files and headers, one representative file should be chosen. Also, this introduces platform-dependent target names, so the `glfw` etc variables should be in ARCH blocks.

**Comment by lazzarello** [comment]
I think this has happened to me but I don't yet know how to back out without a complete make clean in `dep`.

**Comment by AndrewBelt** [comment]
Fixed with f65013cd9ba7b0a21d4cb201e300d673f6202e11.
