### ISSUE TITLE
File->New does not overwrite the 'latPatch' in settings.json

### ISSUE THREAD

**Issue by bontric** [VCVRack/Rack#294]
OS (if applicable) : any
Version (or "dev" if compiling from source): dev

Creating a new patch should (whether saved or not) reset the "lastPatch" value in settings.json. Otherwise, pressing ctrl + s will overwrite the lastPatch which can lead to accidentally overwriting a patch with an empty one.

**Comment by AndrewBelt** [comment]
I can't replicate. Ctrl+N sets `lastPath` to "" and saves the empty string to settings.json on my end.

**Comment by bontric** [comment]
Hmm. I can't reproduce this now either. Maybe I didn't observe this properly. I guess you can close this for now. If I encounter something similar I'll come back here

**Comment by AndrewBelt** [comment]
Okay, reopen if you see it again
