### ISSUE TITLE
Error Entry point not found

### ISSUE THREAD

**Issue by mschack** [VCVRack/Rack#295]
When I build a plugin in a development folder my plugin works when I execute VCV with 'make run' but when I then copy the same plugin to my 'real' VCV installation folder and run it I get "Entry Point Not Found" when it tries to load my plugin.  _ZN4rack12ModuleWidget5resetEv could not be located.

Should this just work or have I missed something?

**Comment by AndrewBelt** [comment]
That's because Rack from source, "dev", is not ABI compatible with Rack v0.4.

**Comment by mschack** [comment]
So the source dev is newer?

**Comment by AndrewBelt** [comment]
Yes, it's always the most bleeding-edge code.

**Comment by mschack** [comment]
Thank you and nice work.
