### ISSUE TITLE
Audibles  modules all cause a segfault in 0.4

### ISSUE THREAD

**Issue by Malifick** [VCVRack/Rack#296]
OS (if applicable):Arch Linux
Version (or "dev" if compiling from source):dev

make: *** [Makefile:49: run] Segmentation fault (core dumped)
 every module giving me this , and I couldn't compile source either. not sure what to do , this is a fresh install after repairing my lappy  and trying 0.4foo

 when I load a module from audibles up I can click and make random but if I touch a button or click anything it crashes Rck

**Comment by AndrewBelt** [comment]
Have you checked out both Rack 0.4.0 and Audible Instruments 0.4.0?

**Comment by Malifick** [comment]
yes all from 0.4.0

**Comment by Malifick** [comment]
yeh I did   but  retrying that just in case.

**Comment by Malifick** [comment]
now they work but the eseries  has no sound.. going to recompile that one i guess

**Comment by Malifick** [comment]
All work now just had to recompile ..  perhaps just a wierd glitch.
