### ISSUE TITLE
Build fails on "make" with missing nanovg

### ISSUE THREAD

**Issue by metaphorz** [VCVRack/Rack#297]
OS (if applicable): OSX 10.12.6 (Sierra)
Version (or "dev" if compiling from source): dev

Following the README file for compiling...
Downloaded the rack-master from github and after creating a cmake command line (since brew install cmake installed an old one that didn't work), I get "make dep" successfully.

However, the build fails on "make" with nanovg. I see that there is a separate source tree for this package - should we install it since it is not listed in the README?

Here is the error:

Rack-master paul$ make
c++ -Iinclude -Idep/include -Idep/lib/libzip/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7 -DAPPLE -stdlib=libc++ -std=c++11 -stdlib=libc++ -c -o build/src/app.cpp.o src/app.cpp
In file included from src/app.cpp:1:
In file included from include/app.hpp:4:
include/widgets.hpp:5:10: fatal error: '../ext/nanovg/src/nanovg.h' file not
      found
#include "../ext/nanovg/src/nanovg.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [build/src/app.cpp.o] Error 1

**Comment by AndrewBelt** [comment]
>Clone submodules.

    git submodule update --init --recursive

**Comment by antoniotuzzi** [comment]
Saint Andrew 😄

**Comment by metaphorz** [comment]
Probably my weakness on using git, but when I cd to the Rack-master directory and enter that, I get: 
fatal: Not a git repository (or any of the parent directories): .git

The directory contains the usual git things:  .github, .gitignore, .gitmodules

**Comment by antoniotuzzi** [comment]
probably you started with a zip file
you should clone the full repo

**Comment by metaphorz** [comment]
yeah - I did. Ok I will clone the full repo and then start over.

**Comment by AndrewBelt** [comment]
Yup, the submodule information isn't stored in the zip files Github offers.

**Comment by metaphorz** [comment]
Thanks to both of you for walking me through this. I built it and can run.
When trying to make Strums_Mental_VCV_Modules after cloning and following 
the instructions in README for making plugins, I am getting:

src/MentalClockDivider.cpp:180:43: error: use of undeclared identifier
      'gSampleRate'
                        lights[0] -= lights[0] / lightLambda / gSampleRate;
                                                               ^
Maybe I've screwed something up. I followed these instructions but replacing the example Fundamentals with Strums_Mental_VCV_Modules.

Clone your favorite plugin in the plugins/ directory. e.g.:

cd plugins
git clone https://github.com/VCVRack/Fundamental.git
Clone submodules.

cd Fundamental
git submodule update --init --recursive
Build plugin.

make

**Comment by antoniotuzzi** [comment]
if you know how to use git, you should checkout the v0.4.0 tag for Rack, if you want to compile plugins "0.4.0"
(this is the case)

and of course, the instruction on building the Fundamental plugin, are valid only for Fundamental!
Other developer maybe not perfectly aligned with code !
Happy debugging! 😄

**Comment by metaphorz** [comment]
OK

**Comment by AndrewBelt** [comment]
Thanks @antoniotuzzi

**Comment by probonopd** [comment]
I am also getting `../../include/window.hpp:10:20: fatal error: nanovg.h: No such file or directory`.

What am I doing wrong?

* Build log: https://travis-ci.com/probonopd/Rack/builds/121872161#L967
* My build script: https://github.com/probonopd/Rack/blob/patch-1/.travis.yml
