### ISSUE TITLE
Module tags

### ISSUE THREAD

**Issue by johnfolkesson** [VCVRack/Rack#298]
It would be nice to have the ability to tag modules and search for them based on those tags. Both tags from devs and own custom user tags. Eg: Osc, LFO, VCF, seq etc etc.

**Comment by AndrewBelt** [comment]
Thanks, we've been talking about this internally, but since you beat us to make an Issue, this will be the one to track for progress.

**Comment by AndrewBelt** [comment]
We can close this now, since tags are fully implemented.
