### ISSUE TITLE
Resource dir 'res' is missing

### ISSUE THREAD

**Issue by falkTX** [VCVRack/Rack#3]
Hi there, very nice project you have here!

I was able to build it after doing some small changes, I can run the application but some files are missing.
I got a binary download from somewhere else and was able to place the files manually, but it would be nice if they were added directly into the git repo.
Thanks.

**Comment by AndrewBelt** [comment]
Thanks! These will be added before September 7. Updated README that this repo is unsupported until then.

**Comment by AndrewBelt** [comment]
Added /res
