### ISSUE TITLE
Increase audio thread priority

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/Rack#302]

**Comment by Strum** [comment]
Is this a high priority?

Should we increase the priority of the increase audio thread priority thread?

Excuse me, I couldn't resist.

**Comment by AndrewBelt** [comment]
Lol, since it's scheduled for the next release, I would say that yes, it is very high priority to schedule the scheduler to be high priority.

**Comment by AndrewBelt** [comment]
I'm going to avoid this due to the pitfalls. If someone can convince me they're an expert on this, let me know.
