### ISSUE TITLE
make fails with latest sources

### ISSUE THREAD

**Issue by dBiz** [VCVRack/Rack#303]
OS (if applicable): Win 10
Version (or "dev" if compiling from source): dev

After complete make dep and make 
on make run i've got this error

TODO get rid of the mingw64 path
env PATH=dep/bin:/mingw64/bin ./Rack.exe
make: *** [Makefile:56: run] Error 127

**Comment by AndrewBelt** [comment]
Could you run it with a debugger with `make debug`?

**Comment by dBiz** [comment]
i've got this :
LD_LIBRARY_PATH=dep/lib gdb -ex run ./Rack
/bin/sh: gdb: command not found
make: *** [Makefile:63: debug] Error 127

**Comment by AndrewBelt** [comment]
Install the mingw64 version of gdb and try again

**Comment by dBiz** [comment]
i'm already using the 64bit version

**Comment by AndrewBelt** [comment]
Then why can't it find gdb?

**Comment by dBiz** [comment]
opz my fault, installed gdb and got this 

Starting program: O:\Rack\Rack.exe
[New Thread 3124.0x3474]
[New Thread 3124.0x858]
[New Thread 3124.0x2f68]
[New Thread 3124.0x1be4]
[New Thread 3124.0x2e1c]
warning: Critical error detected c0000374

Thread 1 received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffeb810771f in ntdll!RtlIsNonEmptyDirectoryReparsePointAllowed ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll

**Comment by AndrewBelt** [comment]
Looks like the stack is garbage. Have you checked out and recompiled all plugins?

**Comment by bontric** [comment]
@AndrewBelt Could [this](https://stackoverflow.com/questions/1621059/breakpoints-out-of-nowhere-when-debugging-with-gdb-inside-ntdll) be related?

@dBiz Could you try to type `where` in the gdb shell after the program crashes and post the output? According to the link above, you could also try to use `windbg` to get a better stack trace.

**Comment by dBiz** [comment]
where
#0  0x00007ffeb810771f in ntdll!RtlIsNonEmptyDirectoryReparsePointAllowed ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x00007ffeb810df0a in ntdll!RtlpNtSetValueKey ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#2  0x00007ffeb80b4f22 in wcstok_s () from C:\WINDOWS\SYSTEM32\ntdll.dll
#3  0x00007ffeb80c9048 in ntdll!memset () from C:\WINDOWS\SYSTEM32\ntdll.dll
#4  0x00007ffeb758995c in msvcrt!free () from C:\WINDOWS\System32\msvcrt.dll
#5  0x000000006fce45be in ?? () from O:\Rack\libstdc++-6.dll
#6  0x000000006fce26a0 in ?? () from O:\Rack\libstdc++-6.dll
#7  0x00000000042eaba0 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign (__s=0x4300200 "dBiz", this=0x88668)
    at O:/msys64/mingw64/include/c++/6.2.0/bits/basic_string.h:1254
#8  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator= (__s=0x4300200 "dBiz", this=0x88668)
    at O:/msys64/mingw64/include/c++/6.2.0/bits/basic_string.h:590
#9  init (p=p@entry=0x88660) at src/dBiz.cpp:9
#10 0x0000000000417609 in rack::loadPlugin (path=...) at src/plugin.cpp:97
#11 0x0000000000417913 in rack::loadPlugins (path=...) at src/plugin.cpp:112
#12 0x0000000000417bb6 in rack::pluginInit () at src/plugin.cpp:235
#13 0x00000000005339b9 in main (argc=1, argv=0x84b10) at src/main.cpp:17

**Comment by dBiz** [comment]
=) yep it's a plugin issue, resolved by changing the .cpp and correct the widget creation param. ;)

**Comment by AndrewBelt** [comment]
Nowhere in your original post did you mention that you were developing your own plugin. That would have helped solved this issue instead of bouncing around basic commands for 5 minutes.
