### ISSUE TITLE
Midi Modules Guide

### ISSUE THREAD

**Issue by bontric** [VCVRack/Rack#310]
Hey Folks,
Just wanted to make you aware of this: https://github.com/VCVRack/Rack/wiki/MIDI-Modules

I typed together a small guide for the MIDI modules, might be helpful for some.

**Comment by AndrewBelt** [comment]
Nice, I'm working on a polished documentation website for Rack, and this is a great start for the Core section. I like the animations.

**Comment by Strum** [comment]
Nice work @bontric

**Comment by flatlandsynthesist** [comment]
Hello Ben (@bontric),
thanks for the very comprehensive guide!

I was wondering, I installed VCV's last version yesterday (having tons of fun with it) but I can not find these modules you discuss: 'MIDI Clock to CV', 'MIDI Trigger to CV' and 'Quad MIDI to CV' 

When I navigate to 'core' in the rack it will only give me the basic 'Midi to CV' interface for monophonic signals and the 'Midi CC to CV' module for modulation articulations.

Could you enlighten me where I can find the missing midi modules and how to install these? 

Many thanks!
Robin

**Comment by bontric** [comment]
Hey Robin,
the new modules will only be available with the next release. You can test them if you are able to compile the sources by yourself.

Cheers

**Comment by AndrewBelt** [comment]
Closing, since this was replaced by https://vcvrack.com/manual/Core.html a while ago.
