### ISSUE TITLE
Feature: Support alternate panels for modules, a la Modular Grid

### ISSUE THREAD

**Issue by tildebyte** [VCVRack/Rack#311]
Modular Grid has a pair of arrows at the bottom left of each module which allows the user to select different panel versions.
This feature would dovetail nicely with a system for allowing end users to spin their own panels more easily ;)  (I'll not open that one yet; I feel like it's too far out in the future).

**Comment by Strum** [comment]
This would also make module development easier.

There has been some discussion about importing control locations from inkscape.

https://github.com/VCVRack/Rack/issues/261#issuecomment-337953776

**Comment by lnikj** [comment]
It would be great, especially for boring old conservatives like me who fear being inflicted with psychedelic panels :)  Give me monotones every time !

**Comment by AndrewBelt** [comment]
I think the current method "Replace panel files" is the best. It's simple, allows for the most hacking ability, and gets people into plugin development.

Not interested in adding it as a Rack feature.
