### ISSUE TITLE
White back after updating source

### ISSUE THREAD

**Issue by dBiz** [VCVRack/Rack#313]
OS (if applicable): win 10
Version (or "dev" if compiling from source): dev

After updating to new source rack launch but without background,
i've tried with and without plugs installed 
![untitled](https://user-images.githubusercontent.com/12683589/31960140-12c8e0fa-b8f7-11e7-8b15-3a8fdee0295e.png)

**Comment by jwmatthys** [comment]
Same on Linux

**Comment by davephillips** [comment]
Confirmed on Linux Fedora 23.

**Comment by AndrewBelt** [comment]
Yes, I know. No need to notify me further.

**Comment by AndrewBelt** [comment]
Fixed with 684c783d41af4d62acc3c9c7be03691dced2c975
