### ISSUE TITLE
Implementation: Event callbacks

### ISSUE THREAD

**Issue by mschack** [VCVRack/Rack#314]
Have you had any thoughts on implementing event callbacks?  The reason I ask is that I am working on a rack that has >200 buttons and I poll all of those in the step() function.  I don't see a performance hit but I imagine it would just increase the overall performance by getting a callback instead of everybody spinning in the step function checking for hits.

In case you were wondering:
![snapshotjpg](https://user-images.githubusercontent.com/32986033/31970962-f186c696-b8e7-11e7-8b9c-4d40cadfd41d.JPG)

**Comment by AndrewBelt** [comment]
>I don't see a performance hit but I imagine it would just increase the overall performance

I don't understand this logic. If you don't see a performance hit, how can it get better?

Anyway, you can do this by overriding the `onChange()` event method.

```cpp
struct MyMomentarySwitch : MomentarySwitch {
	void onChange() override {
		// Do stuff here
		// Remember to call superclass method
		ParamWidget::onChange();
	}
}```

**Comment by mschack** [comment]
Just making sure you understood it wasn't causing a big issue, the logic is sound. (pun?)
Thanks.
