### ISSUE TITLE
Wiring Diagram View of Modules

### ISSUE THREAD

**Issue by metaphorz** [VCVRack/Rack#315]
OS (if applicable): N/A
Version (or "dev" if compiling from source): # ANY

[Feature Request]

Similar to what NI has for Reaktor where there are modules but also a structure window,
or Max/Msp has both presentation and patch views, it would be useful to the user to
be able to see a directed graph of the modules as a different window or view. This graph
would be similar to the Reaktor structure view or the Max patch view. Such a graph would
ease viewing the graph topology and module inter-connectivities.

**Comment by AndrewBelt** [comment]
I don't know if someone's opened an issue for it, but I'd prefer a button "Arrange Modules" that runs some clever algorithm that tries to optmize total cable length.

But definitely "no" to a different view of your patch.

**Comment by metaphorz** [comment]
Optimizing total cable length is done by letting the modules float, thus achieving the other view.

**Comment by AndrewBelt** [comment]
>letting the modules float

What?

**Comment by metaphorz** [comment]
If one lets the modules float (meaning that you allow the module blocks to organize themselves positionally), an optimization of cable length will yield a readable, communicable, organization of connected modules in graph form -- meaning that instead of spaghetti, one obtains a clear understanding of how modules connect to one another. Consider force layout as in: https://en.wikipedia.org/wiki/Graph_drawing

This is why NI and Cycling do this: this offers a clearer way of comprehending graph structure.

**Comment by AndrewBelt** [comment]
Okay, that's what I thought.

I don't want to spend an entire day or two doing this, and even if someone contributed this feature, I'd instead prefer the software to have a "reorganize modules" function which doesn't show a different "view" but actually sets the modules' positions to minimize total cable length.

**Comment by odahan** [comment]
The problem here is the skeuomorphism. it is bias. VCV Rack is a Eurorack, not another Max or Reaktor soft synth.
Such biais can be changed of course but it will change the way people will perceived VCV.
Perhaps it is possible to create a secondary view showing modules and cables like a graph without the full layout (no knob or any settings, so just showing the relationships between modules).
There is a real interest in a graph view, whatever it can be. But this will change the perception of what is VCV and I can understand there can be some reluctance.

**Comment by metaphorz** [comment]
I agree odahan - VCV Rack is maintaining the skeumorph from the physical rack and this is nice aesthetic to boot. I realized the request for a separate view would be controversial. I am happy to use this excellent software and for separate graph viewing, I can use other software.
