### ISSUE TITLE
Versioning inside a Patch / save different Versions / States of a Patch

### ISSUE THREAD

**Issue by w3stgaard** [VCVRack/Rack#316]
This Feature would makes it possible to save only 1 Patch with an unlimited number of Sub-Patches / Versions in it (for later use or a possible upcomming session scenario) .

Simple Example on Windows:

STRG + S saves the Patch amd the current Sub Patch
STRG + N for Examples saves a new Version inside the current patch

There should be an editable and recallable list of all Patch Versions, where the user can choose from to work  with or even rename it / tag it.

**Comment by AndrewBelt** [comment]
Any reason you can't or don't want to use versioned files? `mypatch.vcv`, `mypatch-2017-10-25.vcv`, etc

**Comment by w3stgaard** [comment]
* simple switching and managing between/of states without open dialogs etc. 
* sometimes we work on 50-250 different versions of only 1 patch - too much files on harddisks makes it impossible to work on music instead of searching for the right version ... because often it is neccesary to save an explicite state, if it gets complex aso.
* momentarily with Jack under Windows we have to reload the Jack Session Cable Settings outside VCV everytime, we want to load a patch - followed by reselecting the ASIO JackRouter als Audio Output - ok, it is a normal behaviour, but I think of all those maniacs like us, that creates hundreds of variations to find the right patch-way ^^ think of it as a scratchpad in the same environment too
* a lot of instruments use performance knobs or use diferent settings for one patch inside the same patch as so called subsettings or even performance settings
* take a look into a "Modular Patch" by Richard Devine - Millions of ways to tweak one Patch - why creating a mass of Files instead of versioning ? In my opinion one patch can be a complex world.


Perhaps there are more reasons that will come to mind during these days.

**Comment by AndrewBelt** [comment]
>reload the Jack Session Cable Settings outside VCV everytime

implementing this would not solve this problem, because whenever a new patch, or "subpatch" as you're describing, is loaded, the rack is cleared and rebuilt again, which would close and reopen the Jack connection.

Besides this, I don't see how "Ctrl+O, click on file" is any faster than "click on dropdown on toolbar, click on subpatch." It's the same number of clicks.

If you're talking about macros, there's an issue for that #129 and

**Comment by w3stgaard** [comment]
> implementing this would not solve this problem, because whenever a new patch

Yeah - as soon as the VCV VST Bridge works Jack will be not needed anymore. See Jack as a temp.

> Besides this, I don't see how "Ctrl+O

You haven't seen our 25TB HD Rig an the mass of files from Hard and Software Synthesizers up to the versioning in Ableton Live and other DAW-projects  ^^ It was not about the time for selecting a menu item or being fast. It was an idea for getting a comfortable DAW Environment without thousands of external Files (with mostly the same content). 

Whren I create a Lead and a Pad I would save them in seperate .vcv files. If I create a complex Ambient structure I would save states or versions inside the same .vcv file.

 See the Version saving in Presonus Studio One - it is simply the question of organizing things, versions of the same project. VCV Rack is a complex DAW Project.

"mypatch.vcv" should be used as a patchcontainer for 1 or more versions. At the moment we produce about 20-30 different ongoing states of one patch per hour to check things out. When I save a patch an name it with an additional date or time, things are going to become ugly while managing them inside a backup / file system.

But again, it is just an idea.

**Comment by AndrewBelt** [comment]
Regardless of how many files are on your computer, creating a folder to store versioned patches is easy. Thus I think this issue would only cater to people who 1) version their patches and 2) don't like the file save/open dialog for some reason. That's a very small subset of the whole userbase, so adding this feature, which would appear to ALL users, would increase the complexity, bloat, and learning curve on average per user, more than it would decrease it the complexity.

**Comment by w3stgaard** [comment]
I will rethink this as soon as the vst bridge is released. Maybe the workflow inside a daw will change my view.
