### ISSUE TITLE
Building dep glew fails

### ISSUE THREAD

**Issue by temrix** [VCVRack/Rack#317]
OS (if applicable): Ubuntu 17.10
Version (or "dev" if compiling from source): dev

I have installed all deps that are listed for Rack: `gcc`, `make`, `cmake`, `tar`, and `unzip`.
When trying to `make dep` the build fails. As Ubuntu now ships with Wayland as default and I see X11 libs, I guess that this is the problem. Also, when trying to open the precompiled v0.4.0 I get visual bugs which may be related to this issue. If not, I will open a new issue for this.

```
tar xf glew-2.1.0.tgz
make -C glew-2.1.0 glew.lib
make[1]: Opening folder „/home/temrix/Dokumente/git/Rack/dep/glew-2.1.0“
cc -DGLEW_NO_GLU -DGLEW_BUILD -O2 -Wall -W -Iinclude -fPIC -Wcast-qual -ansi -pedantic -fno-stack-protector  -o tmp/linux/default/shared/glew.o -c src/glew.c
cc -shared -Wl,-soname=libGLEW.so.2.1 -o lib/libGLEW.so.2.1.0 tmp/linux/default/shared/glew.o -L/usr/X11R6/lib64 -L/usr/lib64 -lGL -lX11 
/usr/bin/ld: -lGL cannot be found
collect2: error: ld returned 1 exit status
Makefile:122: the rule for target „lib/libGLEW.so.2.1.0“ failed
make[1]: *** [lib/libGLEW.so.2.1.0] Error 1
make[1]: Folder „/home/temrix/Dokumente/git/Rack/dep/glew-2.1.0“ closed
Makefile:69: the rule for target „lib/libGLEW.so“ failed
make: *** [lib/libGLEW.so] Error 2
```

**Comment by AndrewBelt** [comment]
It's not a problem with Wayland but because you don't have an OpenGL driver installed. I don't know what you graphics card is, but the most popular generic open source driver is Mesa.

Screenshot of visual bugs?

**Comment by temrix** [comment]
I have checked whether mesa is installed:
```
$ glxinfo | grep "OpenGL version"
OpenGL version string: 3.0 Mesa 17.2.2
```

The visual bugs for the precompiled version disappeared and I don’t know why.

**Comment by AndrewBelt** [comment]
Do you have /lib/libGL.so on your computer?

**Comment by temrix** [comment]
Yes, but it is located under `/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0` with `/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1` being the link to it.

**Comment by AndrewBelt** [comment]
If that's in your normal library search path, I don't know why `ld` is not finding it.

**Comment by temrix** [comment]
I tried it with a fresh install on a virtual machine and it seems to be an Ubuntu-specific problem. The following is all on a fresh install of Ubuntu 17.10.

I needed to install `libx11-dev`.

libGL needs to be correctly linked with:
```
sudo ln -s /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 /usr/lib/libGL.so
```

Then by installing `libglfw3-dev` the following dependencies are installed:
```
libdrm-dev libegl1-mesa-dev libgl1-mesa-dev libglfw3 libglfw3-dev
  libmirclient-dev libmircommon-dev libmircookie-dev libmircookie2
  libmircore-dev libprotobuf-dev libvulkan-dev libvulkan1 libwayland-bin
  libwayland-dev libx11-xcb-dev libxcb-dri2-0-dev libxcb-dri3-dev
  libxcb-glx0-dev libxcb-present-dev libxcb-randr0-dev libxcb-render0-dev
  libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxdamage-dev
  libxext-dev libxfixes-dev libxkbcommon-dev libxrandr-dev libxrender-dev
  libxshmfence-dev libxxf86vm-dev mesa-common-dev x11proto-damage-dev
  x11proto-dri2-dev x11proto-fixes-dev x11proto-gl-dev x11proto-randr-dev
  x11proto-render-dev x11proto-xext-dev x11proto-xf86vidmode-dev zlib1g-dev
```

Additionally, these need to be installed too:
`libxinerama-dev`, `libxcursor-dev`, `freeglut3-dev`, `libasound2-dev`

After these steps all dependencies are built successfully.

Now, are these packages needed by the application itself or by some dependency of it: `libx11-dev`, `libglfw3-dev`, `libxinerama-dev`, `libxcursor-dev`, `freeglut3-dev`, `libasound2-dev` ?
They probably should be mentioned explicitly as deps for Ubuntu in the README.md as they are not installed by default for 17.10.
The linking seems to be a bug in Ubuntu as it was the same on the virtual machine.

**Comment by samhain13** [comment]
I would also like to contribute my solution to building on Ubuntu 16.04 LTS:

Install dependencies: `libx11-dev libgl1-mesa-dev libglu1-mesa-dev libjack0 libjack-dev libasound2-dev librtaudio4v5 librtmiti-dev libgtk2.0-dev xorg-dev`

I also had to download the Jansson source from http://www.digip.org/jansson/ because `wget` was being denied access that the time (not sure if it is a permanent issue). The downloaded `jansson-2.10.tar.gz` was saved to the `dep` folder.

**Comment by AndrewBelt** [comment]
Does wget complain about certificates? Someone else was having an issue with that, so maybe I should use a mirror.

**Comment by modlfo** [comment]
I'm closing this one because seems to me that the issue was solved.
