### ISSUE TITLE
build failure with new core MIDI modules, pt.2

### ISSUE THREAD

**Issue by davephillips** [VCVRack/Rack#319]
Linux Fedora 23 GCC 5.3.1
dev Rack

This error occurs after I "fixed" the isfinite problem :

src/core/QuadMidiToCV.cpp: In member function ‘void QuadMIDIToCVInterface::processMidi(std::vector<unsigned char>)’:
src/core/QuadMidiToCV.cpp:188:46: error: no matching function for call to ‘find(std::__cxx11::list<int>::iterator, std::__cxx11::list<int>::iterator, int&)’
     if (std::find(open.begin(), open.end(), i) != open.end()) {
                                              ^
In file included from /usr/include/c++/5.3.1/bits/locale_facets.h:48:0,
                 from /usr/include/c++/5.3.1/bits/basic_ios.h:37,
                 from /usr/include/c++/5.3.1/ios:44,
                 from /usr/include/c++/5.3.1/ostream:38,
                 from /usr/include/c++/5.3.1/iostream:39,
                 from dep/include/rtmidi/RtMidi.h:49,
                 from src/core/QuadMidiToCV.cpp:3:
/usr/include/c++/5.3.1/bits/streambuf_iterator.h:369:5: note: candidate: template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)
     find(istreambuf_iterator<_CharT> __first,
     ^
/usr/include/c++/5.3.1/bits/streambuf_iterator.h:369:5: note:   template argument deduction/substitution failed:
src/core/QuadMidiToCV.cpp:188:46: note:   ‘std::_List_iterator<int>’ is not derived from ‘std::istreambuf_iterator<_CharT>’
     if (std::find(open.begin(), open.end(), i) != open.end()) {

**Comment by bontric** [comment]
@AndrewBelt You can close this issue ( #318 )
