### ISSUE TITLE
dep/Makefile should allow for parallel building of each target

### ISSUE THREAD

**Issue by giuliomoro** [VCVRack/Rack#32]
I guess compile time of the dependencies could be speeded up if each of the targets was allowed to be built in parallel (even without allow parallel building of the targets). Now, in case the above is difficult to parse, what I mean is that if you do
`cd dep && make -j6`
you would want each of `make` sub-commands to be passed the `-j6` flag, e.g.:
```
 $(MAKE) -C $@ glew.lib -j6
```

**Comment by AndrewBelt** [comment]
Flags recurse down with `$(MAKE)`, so `make -j$(nproc)` should already work. I have disabled parallelization in `dep/Makefile` since building multiple packages simultaniously would be silly, but its descendants should parallelize. Let me know if this doesn't actually work for you.
