### ISSUE TITLE
what happened to DaviesSmallBlackKnob?

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/Rack#322]
it wasn't so ugly, poor knob...
why has it been deprecated? and what will happen to its bigger sister?

**Comment by AndrewBelt** [comment]
Use RoundBlackSmallKnob instead.

**Comment by Strum** [comment]
Why can't you leave it there and have both?

**Comment by AndrewBelt** [comment]
It's redundant and incorrect.
