### ISSUE TITLE
Rails not visible

### ISSUE THREAD

**Issue by srizzi88** [VCVRack/Rack#323]
OS (if applicable): OS X 10.11.6 El Capitan
Version (or "dev" if compiling from source): dev

Rails are no longer visible on Mac after building latest commit. I only get a black background

**Comment by AndrewBelt** [comment]
Can you verify it's the latest?

**Comment by srizzi88** [comment]
commit 265cd9b7da229b0b306a668b74b3ab3888d9a59c

**Comment by AndrewBelt** [comment]
That's an issue. Do the rails render at any zoom level? What is your Mac model?

**Comment by srizzi88** [comment]
rails appear when reducing zoom to under 64%. This is a MBP Retina Early 2013

**Comment by AndrewBelt** [comment]
I can sort of reproduce this on my Macbook Pro Late 2012. It doesn't disappear, but VRAM usage is high.

**Comment by srizzi88** [comment]
interestingly enough, if I move the Rack window to another desktop on an external monitor the rails render at any zoom level

**Comment by srizzi88** [comment]
FWIW, my built-in display is set at 2880x1800, whereas the external monitor is set at 2560x1440. Again, rails render fine at all zoom levels on my external monitor

**Comment by srizzi88** [comment]
just built 99ad658694691c60bf39af8d3ee790911c51d3e7 and it seems to be fixed now. Will keep testing and report if I find anything

**Comment by AndrewBelt** [comment]
I think all I did was turn off 2x oversampling on Retina. That reduced VRAM usage by about 4x, which makes everything fit in normal-sized framebuffers again. I'll close this. Reopen if it happens again.

**Comment by srizzi88** [comment]
reoccurring issue as of fd0d2232acb9d1b71879b93e934ce4623745d405.

Same OS and build environment.

**Comment by srizzi88** [comment]
FWIW, did a fresh clone (which for some reason brings branch v0.5 rather than master by default). Built 862d9ed5758f2aba65663100c6c69ed814f5a239 from scratch including dependencies and everything works.

Did another fresh clone, checked out master, built fd0d2232acb9d1b71879b93e934ce4623745d405 from scratch including dependencies, and this one has the old issues with non visible rails

**Comment by srizzi88** [comment]
experimented a bit more. External monitor works fine. On the retina display, resizing window or  scale sometimes brings the rails back. However, it also causes an occasional crash.

This is what I think might be relevant from one of those crashes:

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
abort() called

Application Specific Signatures:
Graphics hardware encountered an error and was reset: 0x0000001f


Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff8cfbdf06 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff8eb4e4ec pthread_kill + 90
2   libsystem_c.dylib             	0x00007fff9121e6df abort + 129
3   libGPUSupportMercury.dylib    	0x00007fff8a725e5c gpusGenerateCrashLog + 158
4   com.apple.GeForceGLDriver     	0x00007fff94bfddc7 0x7fff949dd000 + 2231751
5   libGPUSupportMercury.dylib    	0x00007fff8a727361 gpusSubmitDataBuffers + 511
6   com.apple.GeForceGLDriver     	0x00007fff94cf1f0c 0x7fff949dd000 + 3231500
7   com.apple.GeForceGLDriver     	0x00007fff94cf2290 gldPresentFramebufferData + 417
8   GLEngine                      	0x00007fff98990c81 glSwap_Exec + 97
9   com.apple.opengl              	0x00007fff9a8cdffe CGLFlushDrawable + 66
10  com.apple.AppKit              	0x00007fff93a4b09f -[NSOpenGLContext flushBuffer] + 27
11  libglfw.3.3.dylib             	0x000000010e8620d3 swapBuffersNSGL + 35
12  libglfw.3.3.dylib             	0x000000010e84c4a0 glfwSwapBuffers + 176
13  com.vcvrack.rack              	0x000000010e6776e3 rack::renderGui() + 195 (gui.cpp:305)
14  com.vcvrack.rack              	0x000000010e678306 rack::guiRun() + 1190 (gui.cpp:477)
15  com.vcvrack.rack              	0x000000010e6805c9 main + 537 (main.cpp:43)
16  com.vcvrack.rack              	0x000000010e661f14 start + 52
```

**Comment by AndrewBelt** [comment]
Closing as obsolete issue.
