### ISSUE TITLE
Feature Request: Offline/Freeze/Render > WAV file

### ISSUE THREAD

**Issue by jpshea** [VCVRack/Rack#324]
Eventually, one will run out of real time CPU.

Are there any plans for an offline render to a file?

Maybe one file per audio output port? (or stereo pair?)

Being able to specify a record duration and possibly a number of clock ticks would be very helpful.

Same for default record path. File naming can simply be <patch_name>_<audio_port>.wav or similar.

(note that this is different to the real time WAV recorder mentioned by one of the third party plugin devs)

**Comment by AndrewBelt** [comment]
There will be two ways to achieve this in the future:
- Offline rendering in your DAW via VCV Bridge
- Record live using a recording/playback module

However, recording from an Audio Interface will not be one of them. That is not the purpose of the Audio Interface.
