### ISSUE TITLE
error: no matching function for call to 'createInput'

### ISSUE THREAD

**Issue by gianlnicc** [VCVRack/Rack#326]
OS Mac osx El Capitan:
Version 41c66f1d8a392d8ea11d3b2e5790d4e58b062299:

I have this error on 80% of third party plugin since last version, there's a deprecated function that doesn't exist anymore?

**Comment by AndrewBelt** [comment]
No, it isn't removed, and all plugins that I use build successfully. Post the surrounding build error?

**Comment by gianlnicc** [comment]
For example Autodafe

src/Autodafe.cpp:23:3: error: no matching function for call to 'createModel'
                createModel<LFOWidget>(plugin, "LFO", "LFO");
                ^~~~~~~~~~~~~~~~~~~~~~
../../include/rack.hpp:21:8: note: candidate function template not viable:
      requires 4 arguments, but 3 were provided
Model *createModel(std::string manufacturerSlug, std::string manufacture...

**Comment by AndrewBelt** [comment]
See https://github.com/VCVRack/Rack/issues/258#issuecomment-338620033
and https://github.com/VCVRack/Tutorial/blob/master/src/Tutorial.cpp for an example of how to implement this.

**Comment by gianlnicc** [comment]
Ok, clear. Mh I'll wait...

**Comment by gianlnicc** [comment]
Think most third party plugins source are aligned to released vcv rack version.
