### ISSUE TITLE
Remember window size between restarts, don't force full screen at startup

### ISSUE THREAD

**Issue by av500** [VCVRack/Rack#327]
especially when developing it would help not to be forced to resize/move the window each time VCV starts up.

**Comment by jeremywen** [comment]
@av500 In development I have been commenting out this line https://github.com/VCVRack/Rack/blob/master/src/gui.cpp#L253

**Comment by w3stgaard** [comment]
explicit:
* remember last size 
* remember last position 
* rememebr last monitor used

**Comment by av500** [comment]
@jeremywen yes, but then you have a fixed size of 640x480 - and this feature might have a use outside of development I think

**Comment by jeremywen** [comment]
@av500 I *only* do this while developing one module so it doesn't cover up my text editor and terminal every time I run it.

**Comment by av500** [comment]
@jeremywen but could you imagine somebody wanting this when not developing? or working on a set of modules that is larger than 640x480?

**Comment by jeremywen** [comment]
no @av500 I was just trying to help because you said "especially when developing"

**Comment by av500** [comment]
@jeremywen understood, thanks for that :)

**Comment by AndrewBelt** [comment]
Fixed in b31d4fb5ed873a0763fc4a451838603780db4e45
