### ISSUE TITLE
Tab key does not traverse username, password and login button. Seen on Mac OSX 10.9.5

### ISSUE THREAD

**Issue by PixelBulb** [VCVRack/Rack#33]
Minor issue.
Just a usability suggestion.

**Comment by giuliomoro** [comment]
Also 10.11.5

**Comment by JoshuaStorm** [comment]
Win10 as well

**Comment by AndrewBelt** [comment]
Also enter to login should be added

**Comment by jonheal** [comment]
Bonus points if it can be made possible for the tab key to cycle through edit fields of modules, like the **MIDI CC to CV** module.

**Comment by Coirt** [comment]
And white space on the Notes module! With space making a list looks messy tab to space would align text down a list if its centre or right aligned.

**Comment by Coirt** [comment]
This seems resolved in v1.x.x `tab` navigates fields and `enter` log's user in.
