### ISSUE TITLE
Dedicated TriggerGenerator Struct in digital.hpp

### ISSUE THREAD

**Issue by mhetrick** [VCVRack/Rack#330]
OS (if applicable): Any
Version (or "dev" if compiling from source): Dev

It would be great to have a dedicated TriggerGenerator Struct that requires less management than the PulseGenerator Struct. It would always create a Trigger of length 1ms.

It should have `TriggerGenerator::process(_activateTrigger = false)`.

In a similar vein, a useful engine function and simple optimization for this and a lot of other DSP would be engineGetSampleLength(). It would return the reciprocal of the sample rate. This value should only be calculated once when the engine receives a sample rate change. Then, every usage of 
`/ engineGetSampleRate()` 
could be replaced by 
`* engineGetSampleLength()`.

**Comment by AndrewBelt** [comment]
How will `TriggerGenerator` know the samplerate? `dsp.hpp` should be decoupled from `engine.hpp`. Something like `TriggerGenerator::process(float deltaTime, bool activateTrigger)`?

I haven't seen your second point come up in the profiler yet, but I suppose it will allow people to satisfy their *inner preoptimization tendencies* when they choose to use that.

**Comment by AndrewBelt** [comment]
Added `engineGetSampletime()` in 149ecac9d3d8fc923ecb008b6749a82670907744

**Comment by mhetrick** [comment]
Awesome! I'll just roll my own class for the TriggerGen.
