### ISSUE TITLE
Idea: Sleep state for cables

### ISSUE THREAD

**Issue by martin-lueders** [VCVRack/Rack#332]
OS (if applicable): any
Version (or "dev" if compiling from source): any

Just an idea, which would be quite simple to implement..

In many cases, control voltages change very rarely on the scale of samples, so a lot of computations could be avoided, if the module knew whether the value of an input has actually changed.

My suggestion would be:

Add a boolean "sleep" to the cable, which can be set by the modules through the corresponding output.

`outputs[OUT_ID].sleep = true;`

On the output side, we should make sure, that once the sleep state is active, the last value is held, until sleep is released.

Any further

`outputs[OUT_ID].value = ...`

automatically sets sleep to false.

The sleep state of the cable is accessibly through:

`inputs[IN_ID].sleep`

So, for instance, if an input is in sleep mode, we could skip the (potentially expensive) cv-to-pitch conversion, or similar things, as we know that the value has not changed.

For compatibility and safety, the default should always be `sleep=false` unless explicitly set through the output statement.

What do you guys think about it?

**Comment by antoniotuzzi** [comment]
I like it and I agree, but better be explicit: I'd call it 

`inputs[IN_ID].unchanged`

can happen for modulation source that are very static, like a SEQ3 for example (or fixed voltage source like my **SURVEILLANCE**

I'd like to  use a 
`inputs[IN_ID].detached` 
too
where the the modulation source is temporarily deactivating the cable
but I don't know if this is possible 
in this case the signal receiver is acting like there is no cable attached to the CV IN

**Comment by AndrewBelt** [comment]
Use `float lastWhatever;` with
```cpp
	if (!nearf(whatever, lastWhatever)) {
		lastWhatever = whatever;
		// Do stuff
		...
	}
```
because it's more general and takes the same memory/processing. It allows you to check for changes at a "higher level", e.g. when the pitch changes, not just the 1V/oct, FM knob, or FM changes.

**Comment by AndrewBelt** [comment]
Closing because this should be up to the implementation of the particular module.
