### ISSUE TITLE
Open Plugin Folder Button

### ISSUE THREAD

**Issue by djpeterso23662** [VCVRack/Rack#333]
if it does not clutter the UI to much, it might be helpful to have an Open Plugin Folder button on the main Rack window. It could create the user plugins folder on Mac if it does not exist as well. There are probably lots of plugin folder options in Rack's future, but this might help as an interim solution. Thanks!

**Comment by AndrewBelt** [comment]
I added and then removed it with the new plugin restructure. Now manufacturers are not associated with plugins, so it doesn't make sense to have an Open Folder button under each manufacturer. Each *module* can have an Open Folder button though, but this adds a submenu for each plugin which might confuse users.

**Comment by djpeterso23662** [comment]
Thanks for taking time to put a note here, Andrew.  I thought you might already have a solution.  You are really good at design choices so I am sure it will be sorted out.

**Comment by AndrewBelt** [comment]
This is a tricky one so I'm open to suggestions.

**Comment by catronomix** [comment]
I see this has been implemented in the menu in v1:
![image](https://user-images.githubusercontent.com/42138122/58379801-d964b580-7fa8-11e9-8487-cbc106943213.png)
But clicking 'open plugin folder' does not do anything (Win 10)

**Comment by lnikj** [comment]
Clicking does nothing confirmed Win10 & OS X 10.14.5.

**Comment by AndrewBelt** [comment]
Fixed in bc06efd9ab14e48684f32e608b13a76ecb7367bd
