### ISSUE TITLE
Automatic Edge-scrolling when dragging

### ISSUE THREAD

**Issue by s-ol** [VCVRack/Rack#340]
On smaller screens its quite annoying that you cannot drag patch cords and modules further than the screen size because scrolling during doesn't work (on my touchpad at least).

When dragging it would be nice if the view shifted as you got close to the corners of the Rack. When dragging left and up, it could even extend (only when holding a module) but this is another feature.

**Comment by AndrewBelt** [comment]
Was already added, but this prompted me to check it, and I found a bug which has been fixed in a094a0c
