### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by crafter312** [VCVRack/Rack#341]
OS: Windows 10
Version: commit a094a0c

Just tried to run the most recent version of vcvrack. It made fine, but it gave a runtime error when I tried to `make run`. That is, the program opened, but then a window popped up that said something along the lines of "This application has requested the Runtime to terminate it in an unusual way."

Here's what it said in the terminal when I closed the window and the program:

```
Program: C:\msys64\home\Henry\Rack\Rack.exe
File: ./utils/FiniteStateMachine.hxx, Line 88

Expression: creatorIt != m_creators.end()
make: *** [Makefile:56: run] Error 3
```

**Comment by AndrewBelt** [comment]
Nowhere in the source or dependency tree is a file called FiniteStateMachine.hxx. Maybe it's in another plugin, and therefore not an issue with Rack?

**Comment by crafter312** [comment]
Ok, I figured out what the issue is. It's a problem with the VCVRack-Simple plugin, which is strange because the plugin was working before I updated to the a094a0c commit of vcv rack.

However, I noticed another issue when I started up vcv rack and it worked (with the plugin removed). The textures for some of the fundamental modules seem broken. when I create a module such as the vc mixer, the texture appears shrunken, smaller than the size of the actual module.

![image](https://user-images.githubusercontent.com/32717849/32152132-1f5762a4-bcf0-11e7-8c23-b6121ce75eaa.png)

**Comment by AndrewBelt** [comment]
Ah, I understand the confusion. VCVRack-Simple is not associated with the VCV project. If this is the cause, I will ask him to change it or add a disclaimer to prevent the confusion.

The second issue has been solved with a recent commit. Make sure you're working with the latest version of both Rack and its plugins.

**Comment by crafter312** [comment]
Sorry about that. I just had trouble finding where the file was that had caused the problem.
