### ISSUE TITLE
Tidal Modulator not outputting signal

### ISSUE THREAD

**Issue by kmkrebs** [VCVRack/Rack#343]
I see this was an issue previously #219 - but it seems to have returned.  I've attempted the fixes listed in the #219, but the problem persists.
OS (if applicable): Fedora 26
Version (or "dev" if compiling from source): dev

**Comment by AndrewBelt** [comment]
What's the remote URL for the eurorack repo? `cd eurorack; git remote -v`

**Comment by kmkrebs** [comment]
git remote -v gives me:
`origin	https://github.com/AndrewBelt/eurorack.git (fetch)`
`origin	https://github.com/AndrewBelt/eurorack.git (push)`

**Comment by AndrewBelt** [comment]
Have you done the usual incantations `git submodule update --init --recursive` and `make` in the AudibleInstruments and Rack directory?

**Comment by kmkrebs** [comment]
Ok, after some experimenting, I've discovered that it doesn't output anything when I first load it into Rack, but then when I exit and restart, Tidal works as expected....

**Comment by kmkrebs** [comment]
Actually -- all I have to do is cycle through the mode switch until it is black again and the output starts.

**Comment by AndrewBelt** [comment]
Thanks, that's the info I needed. It is indeed a bug and fixed with f4ba885
