### ISSUE TITLE
Build failed on linux

### ISSUE THREAD

**Issue by rafzael** [VCVRack/Rack#347]
OS (if applicable): ubuntu
Version (or "dev" if compiling from source): 0.4.0
I try to compile VCV on my ubuntu (under virtual box and have verify that all needed package was installed).
I get this error: 

 fatal error Xll Xlib.h aucun fichier ou dossier de ce type (that mean no files of this type in french )

Any idea or solution?
Thanks

**Comment by AndrewBelt** [comment]
You'll need to install the xlib dev version from apt. I forgot what the package name is, but if you can't find it maybe someone else will post here.

**Comment by rafzael** [comment]
thank you, sources built!! was pretty difficult for a linux noob like me :)

**Comment by AndrewBelt** [comment]
Cool, reopen if it breaks again.
