### ISSUE TITLE
Events can be modified?

### ISSUE THREAD

**Issue by IohannRabeson** [VCVRack/Rack#348]
https://github.com/VCVRack/Rack/blob/8e251c0ddbfc1f4a2e03a6123d8eda42218b76fe/include/widgets.hpp#L126
I thinks the events passed as parameters shouldn't be modified by the implementations of the methods on*.
Should not be rather
```c++
void onMousePressed(EventMouseDown const& e)
```
 to ensure no one will try to modify `e`?

Using const, it become explicit for all developers that `e` should not be modified.
More info about const here: https://stackoverflow.com/questions/455518/how-many-and-which-are-the-uses-of-const-in-c

**Comment by AndrewBelt** [comment]
Yes, you can modify events. It allows a Widget to pass on information to its parent, the root Widget, or younger siblings. For example, if you want to "consume" the event, set `e.consumed = true;`

**Comment by IohannRabeson** [comment]
Ok, thanks you.

**Comment by AndrewBelt** [comment]
Perhaps some other use cases of a non const event strict is the ability to count the number of widgets under your mouse by incrementing a counter, or to announce a request to delete `this`, or to check if another widget has committed a particular action. All sorts of fun hacky stuff. :)
