### ISSUE TITLE
Live osc messages 

### ISSUE THREAD

**Issue by rafzael** [VCVRack/Rack#349]
I plan to make some modules that will allow to communicate with ableton thru live Osc messages. It can be usefull to control ableton parameters with CV or receive a wide range of messages from ableton. 
Since OSC messages cannot send sound, I wonder if it's possible to deal with the sound of the tracks from ableton in C++. In other words: does a protocol to receive audio signal from ableton exists? and does a C++ library to use it exists? 
One of the goals is to have a module that receive sound from ableton track(s) and display the level of it.

**Comment by AndrewBelt** [comment]
No, that's the reason for #31 

I say go for it! But don't worry about audio, because VCV Bridge will handle that (plus MIDI, DAW parameters, and host transport clock/start/stop).

An OSC client would be nice to have to connect to hardware, so make it as generic as possible.

**Comment by rafzael** [comment]
OK, I will probably do a plugin oriented to live osc for ableton and a more generic plugin for hardware. It remind me when I was developping a reactable. I'll  begin to develop this within 2 or 3 weeks. Thanks

**Comment by AndrewBelt** [comment]
Well, what's your goal with binding to Ableton? I don't have much experience with OSC so I don't remember what it's capable of. What can it do that VCV Bridge can't?

**Comment by rafzael** [comment]
It can send the name of the AU or VST you are controlling, the name of each parameters, the name of each audio clip. You can, for exemple create a modules that display the live clip in VCV with their name and color and allow to control these. all that is done on Ipad-Android ableton controller app can be done.

**Comment by rafzael** [comment]
https://www.youtube.com/watch?v=FVxfx7tSrRo

It could make possible to use VCV with ableton and have to pass from VCV to ableton very rarely.

**Comment by rafzael** [comment]
I made it years ago by using OSC https://www.youtube.com/watch?v=V8z4z2cTEHw

**Comment by AndrewBelt** [comment]
Oh cool. Yeah, that will be a nice module.

**Comment by AndrewBelt** [comment]
Closing this issue, but post back on here when you've got something working
