### ISSUE TITLE
Suggest including a working .json patch file demonstrating basic setup

### ISSUE THREAD

**Issue by PixelBulb** [VCVRack/Rack#35]
Example file could encourage casual user to investigate the Rack capabilities.

Once the two finger right click, for Mac OSX, was mentioned it was easy to add the "Core: Audio Interface" and additional modules.
Was able to get it working with the binaries and plugins after reading through the issue comments.

**Comment by AndrewBelt** [comment]
In addition to a barebones template, I'd like a folder of patches that people can load before trying to make their own. I'm a horrible musician so I'd have to have someone else do it. This shouldn't be done now but in a few months when the API and sound gradually stabalizes.

**Comment by tomchiverton** [comment]
In the mean time, can we start gathering community contributions somehow ? 
I don't see a user mailing list, for instance. So I'll just leave this simple demo attached here...
[basic_seq.zip](https://github.com/VCVRack/Rack/files/1327441/basic_seq.zip)

**Comment by AndrewBelt** [comment]
I'll launch a forum around version v0.4.0 and ask for patches on there.

**Comment by Coirt** [comment]
@AndrewBelt 
added in v1.x.x with templates
