### ISSUE TITLE
blank modules

### ISSUE THREAD

**Issue by michalelektryk** [VCVRack/Rack#351]
OS (if applicable): Windows 7
Version (or "dev" if compiling from source): 0.4.0

I don't see rack mountings when i open app. I'm not able to use fundamental modules, because they don't display or display only few dots, however when i installed other modules i can used then. 

![image](https://user-images.githubusercontent.com/6285553/32375569-6458aa38-c0a2-11e7-97fc-bbdb4a9cae7f.png)

**Comment by AndrewBelt** [comment]
What is your graphics card? Try installing the latest drivers for your graphics card and operating system and report back whether that worked.

**Comment by michalelektryk** [comment]
Well I have nvidia quadro 2000M with driver wich supports openGL 4.0 at least.

**Comment by michalelektryk** [comment]
I tried to upgrade my driver, but there isn't any new graphic driver for my laptop since 2013. I'm playing with your's software and i really like it, but inability to use core functionality makes me feel bad

**Comment by AndrewBelt** [comment]
I am not sure of the reason for the issue. If I had time to make a test renderer that reports information about your opengl render I would, but I don't have time. Are you able to compile this project yourself?

**Comment by michalelektryk** [comment]
I understand that you don’t have time. I made few eksperiments and it turs out that you cant have any of this symbols “- “ in your path.

Thanks for help

Michael

**Comment by AndrewBelt** [comment]
This issue is old and likely obsolete. Comment if issue is still present. Closing.
