### ISSUE TITLE
In the official release and with git clone, the /ext library has four empty folders.

### ISSUE THREAD

**Issue by fenykep** [VCVRack/Rack#355]
Win7; 0.4.0
I've tried to manually clone the directories, but it still isn't compiling.

**Comment by bontric** [comment]
Did you do this:
```
git submodule update --init --recursive
```
?

**Comment by fenykep** [comment]
Yes, and it gives me the following error:
In file included from src/main.cpp:2:0:
include/gui.hpp:3:10: fatal error: GL/glew.h: No such file or directory
 #include <GL/glew.h>
          ^~~~~~~~~~~
compilation terminated.
make: *** [compile.mk:54: build/src/main.cpp.o] Error 1

**Comment by AndrewBelt** [comment]
Read the README
