### ISSUE TITLE
Cannot load fundamental, befaco, or eseries modules on most recent dev master branch. 

### ISSUE THREAD

**Issue by Mubali** [VCVRack/Rack#357]
OS (if applicable): Mac OS 10.10.5
Version (or "dev" if compiling from source): Dev 

So issue 301 has been fixed, and rack will now compile, however when I run the program and manage my plugins, I cannot load any plugins besides just the core modules (no fundamental, no audible, no befaco) 
Here's the error message I get in terminal:
Failed to load library ./plugins/AudibleInstruments/plugin.dylib: dlopen(./plugins/AudibleInstruments/plugin.dylib, 2): Symbol not found: __ZN4rack11ParamWidget17onMouseDownOpaqueEi
  Referenced from: ./plugins/AudibleInstruments/plugin.dylib
  Expected in: flat namespace
 in ./plugins/AudibleInstruments/plugin.dylib
Failed to load library ./plugins/Befaco/plugin.dylib: dlopen(./plugins/Befaco/plugin.dylib, 2): Symbol not found: __ZN4rack11ParamWidget17onMouseDownOpaqueEi
  Referenced from: ./plugins/Befaco/plugin.dylib
  Expected in: flat namespace
 in ./plugins/Befaco/plugin.dylib
Failed to load library ./plugins/ESeries/plugin.dylib: dlopen(./plugins/ESeries/plugin.dylib, 2): Symbol not found: __ZN4rack11ParamWidget17onMouseDownOpaqueEi
  Referenced from: ./plugins/ESeries/plugin.dylib
  Expected in: flat namespace
 in ./plugins/ESeries/plugin.dylib
Loaded font ./res/DejaVuSans.ttf
Loading patch ./autosave.vcv
Loading settings ./settings.json
Requesting http://api.vcvrack.com/purchases?token=XMbPQ1kNcCUsHx0cxYSf
Downloading http://api.vcvrack.com/download?product=AudibleInstruments&version=&token=XMbPQ1kNcCUsHx0cxYSf
Downloading http://api.vcvrack.com/download?product=Befaco&version=&token=XMbPQ1kNcCUsHx0cxYSf
Downloading http://api.vcvrack.com/download?product=ESeries&version=&token=XMbPQ1kNcCUsHx0cxYSf

**Comment by AndrewBelt** [comment]
If you use Rack dev, you need to use the dev versions of the plugins too. Plugins compiled for Rack v0.4 are not ABI compatible with Rack dev.

**Comment by Mubali** [comment]
Do you need to install from dev is you use the refresh plugins button inside of rack?

**Comment by AndrewBelt** [comment]
Follow the instructions in the Rack readme
