### ISSUE TITLE
drag position is offset when zoom != 100% (see gif)

### ISSUE THREAD

**Issue by jeremywen** [VCVRack/Rack#360]
I was working on updating my xypad module from 0.4 to 0.5 and noticed that the drag position was offset when zoomed in.  So I went to look at the Core:Blank module and noticed that it is also offset when dragging the right edge.  At 100% the mouse correctly follows the right edge.  

See GIF:
![drag](https://user-images.githubusercontent.com/408586/32473014-63ca32e2-c333-11e7-9f3f-098bd80db730.gif)

If I change this line https://github.com/VCVRack/Rack/blob/master/src/core/Blank.cpp#L27
to this `totalX += e.mouseRel.x / gRackScene->zoomWidget->zoom;` then it fixes the blank panel.  However, I am not sure if this is the place to do this or something else is wrong higher up maybe here? https://github.com/VCVRack/Rack/blob/master/src/gui.cpp#L147

OS (if applicable): macOS 10.12.6
Version (or "dev" if compiling from source): master a581412

**Comment by AndrewBelt** [comment]
Fixed with 4917b6a, although it was more nontrivial than your fix because it also handles resizing when scrolling at the same time.

**Comment by jeremywen** [comment]
Thank You for the quick fix!  Now I have a drag example to follow while updating my modules.
