### ISSUE TITLE
Plug Lights do not work

### ISSUE THREAD

**Issue by bontric** [VCVRack/Rack#361]
OS (if applicable): archlinux
Version (or "dev" if compiling from source): dev

For some reason the plug lights haven't been working for me for a while. I tried with a clean clone/build but can't get them to work. I haven't had the time to find the exact commit they stopped working, but I remember it was around  a22aac6493c27576886550e456490798c3ad1179 when the zooming feature was introduced. 

Hardware: Thinpad T530 Intel HD4000/NVIDIA  NVS 5400M

**Comment by antoniograzioli** [comment]
I was wondering the same question....In the last week or so plug lights have disappeared...

**Comment by AndrewBelt** [comment]
Fixed with 70bb8c7
