### ISSUE TITLE
Support different tunings in MIDI CC to CV and MIDI to CV

### ISSUE THREAD

**Issue by suhr** [VCVRack/Rack#366]
See http://www.mark-henning.de/files/am/Tuning_File_V2_Doc.pdf and http://www.huygens-fokker.org/scala/scl_format.html.

**Comment by AndrewBelt** [comment]
We definitely need a way to combine a lot of the code in the MIDI interfaces in a clean and non-redundant way.

**Comment by bontric** [comment]
> See http://www.mark-henning.de/files/am/Tuning_File_V2_Doc.pdf and http://www.huygens-fokker.org/scala/scl_format.html.

I think it would be better to do this in a separate module to keep the midi modules simple. It should also be pretty straight forward to do this is as well.

> We definitely need a way to combine a lot of the code in the MIDI interfaces in a clean and non-redundant way.

I'm not sure if I'm interpreting this correctly, but do you mean there is too much redundancy right now? I can see that the midi learn stuff for TextFields is basically a duplicate, but I can't see too much else. (Hope this doesn't sound like I'm offended, I'm sure there is much to improve)

**Comment by AndrewBelt** [comment]
My statement applies to the audio stuff as well, and I'm talking much more "big idea" than the current design allows, so it's not the fault of your MIDI interface code. The redundancy is mostly in the UI/panel, where we're laying out a lot of components which control the same thing, like MIDI panic, channel, device, and hypothetically tunings. All that stuff happens *before* conversion to CV, so maybe a consistent MIDI device panel would solve it. But let's wait until all this stuff is stable so Wes or I can redesign the appearance of it. Similarily block sizes, sample rate, and device for Audio Interface(s).

As for this tunings, Wes and I have a quantizer coming out soon that might allow scala files to be loaded. The MIDI interface gives you 1V/oct, and the quantizer retunes it, so I should close this issue in favor of what you said: "it would be better to do this in a separate module".

**Comment by bontric** [comment]
Thanks for your elaboration! If there is anything I can do, let me know. (Although I just started working on an independent midi sequencer which will drain my free time for another two weeks or so. I'll be taking on issues related to the midi modules though and Continue with the other modules after)
