### ISSUE TITLE
Save As/Open on Mac (10.10.5) Hangs UI

### ISSUE THREAD

**Issue by oblivionratula** [VCVRack/Rack#37]
I mentioned this in the Muffwiggler thread and left a screenshot there.  I have some additional information.

Either save or open works (on open, the sound changes), but the UI does not refresh and the the File pull-down menu persists.  I have to close the program.

Happens with both the pre-built binaries and self-built (with a fresh git pull).  Running from command line, it's throwing this error:
`2017-09-11 20:43:53.137 Rack[64802:1157963] --ImageKit Error: updateGLTextureWithBitmapData: glPixelStorei returned an error : 502 (subSize=[378.000000,378.000000] offset [1512.000000,1134.000000] glID:1, context:0x7f9b80b6ce00)`

subSize and offset numbers vary. context seems consistent.

**Comment by oblivionratula** [comment]
Possibly related to #25 but different symptoms for different OS?
(I hope I'm not overdoing it with my Issue submissions. Just excited to see this working and working well. So far so cool.)

**Comment by oblivionratula** [comment]
FYI, the workaround in Issue #42  did NOT help in this case.

**Comment by oblivionratula** [comment]
FYI, this is still happening on a fresh Mac build (evening 9/26/2017):

2017-09-27 07:26:01.565 Rack[71589:2284246] --ImageKit Error: updateGLTextureWithBitmapData: glPixelStorei returned an error : 502 (subSize=[756.000000,756.000000] offset [0.000000,756.000000] glID:1, context:0x7f9ddf414ed0)

**Comment by AndrewBelt** [comment]
Maybe your OpenGL impementation doesn't like when it frame-skips? Dialog boxes are blocking, so Rack doesn't do any OpenGL calls until the box is closed.

**Comment by oblivionratula** [comment]
So . . . I'm out of luck?  Any use in posting glxinfo output here?

`$ glxinfo  |grep version

server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL version string: 2.1 NVIDIA-10.4.3 310.41.35f01
OpenGL shading language version string: 1.20
`

**Comment by cmountvpr** [comment]
I think I'm having the same problem. Every time I open a patch, the UI doesn't refresh, though the sound does. I have to quit and reboot to see the new patch. Referred to issue #42, confirmed my json file is in the root directory of the application.

Using OSX 10.8.5.

**Comment by AndrewBelt** [comment]
This issue is old and likely obsolete. Comment if issue is still present. Closing.
