### ISSUE TITLE
gtk2.0

### ISSUE THREAD

**Issue by murraypatterson** [VCVRack/Rack#370]
OS (if applicable): Ubuntu 16.04.3 LTS
Version (or "dev" if compiling from source): dev

Just a small issue, I know that having `gtk2.0` is probably a given on most systems, but I was not on mine (building it for a friend of mine who's into music), and so it is necessary.  Specifically, I got

```
$ make
Package gtk+-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-2.0' found
cc -Iinclude -Idep/include -Idep/lib/libzip/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN  -c -o build/ext/osdialog/osdialog_gtk2.c.o ext/osdialog/osdialog_gtk2.c
ext/osdialog/osdialog_gtk2.c:3:21: fatal error: gtk/gtk.h: No such file or directory
compilation terminated.
compile.mk:49: recipe for target 'build/ext/osdialog/osdialog_gtk2.c.o' failed
make: *** [build/ext/osdialog/osdialog_gtk2.c.o] Error 1
```
and I resolved it with:

```
sudo apt install gtk2.0
```

I suppose this is immediately a closed issue, so this serves more as a note

**Comment by AndrewBelt** [comment]
Okay thanks.

**Comment by rg-net** [comment]
Do we still need a GTK dependency? Looking through the code the only thing I see is a cflag. The window is GLFW and everything else seems to be GL from there. So what's the point of depending on GTK?

**Comment by rg-net** [comment]
OH I see. It's for OSDialog... Quite a hefty dependency for something so trivial. Might be worth doing an ifdef that provides a NanoVG alternative for embedded use cases...

**Comment by AndrewBelt** [comment]
@rg-net You should start a new thread for this, preferrably at the osdialog issue tracker.

Feel free to suggest alternative backends to osdialog. The only decent ones I know are GTK+2, GTK+3, Qt, and KDE, and GTK+2 is the most commonly installed on Linux distros.
