### ISSUE TITLE
LFO Reset Not Functional?

### ISSUE THREAD

**Issue by Felnyrii** [VCVRack/Rack#371]
OS (if applicable): win7
Version (or "dev" if compiling from source): 0.4.0

Simply enough, it seems as though the "Reset" input on the Fundamental LFO-1 and LFO-2 are not functional. Having tried resetting with both a LFO-1 Square output and a SEQ-3 Gate output, neither LFO module resets.

Screen capture of Scope showing the LFO and the signal being sent to reset.

![lforeset_11092017](https://user-images.githubusercontent.com/33522416/32614500-0a2cb91a-c533-11e7-8aa3-58eb68fb92e4.png)

**Comment by AndrewBelt** [comment]
Fixed in 3429e835c808cbf1a5c146f247be59f90413788d of Fundamental repo
