### ISSUE TITLE
Cannot make dep on High Sierra

### ISSUE THREAD

**Issue by metaphorz** [VCVRack/Rack#372]
OS (if applicable):10.13.1
Version (or "dev" if compiling from source):dev (Nov 9, 2017)

After upgrading an iMac to High Sierra yesterday, and checking git cloning the current Rack as of today, I installed CMake and homebrew. Then I installed wget and cmake from brew (The Cmake app was downloaded but cmake command line was not but brew fixed this).

Tried doing sudo make clean when retrying, but that didn't help.

When I do a make dep, I am getting errors of this sort:

make dep
gcc: warning: couldn't understand kern.osversion '17.2.0
gcc: warning: couldn't understand kern.osversion '17.2.0
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C dep
gcc: warning: couldn't understand kern.osversion '17.2.0
gcc: warning: couldn't understand kern.osversion '17.2.0
wget -nc http://www.digip.org/jansson/releases/jansson-2.10.tar.gz
File 'jansson-2.10.tar.gz' already there; not retrieving.

tar xf jansson-2.10.tar.gz
jansson-2.10/: Can't update time for jansson-2.10
jansson-2.10/depcomp: Can't unlink already-existing object
jansson-2.10/config.sub: Can't unlink already-existing object
jansson-2.10/ltmain.sh: Can't unlink already-existing object
jansson-2.10/aclocal.m4: Can't unlink already-existing object
jansson-2.10/Makefile.am: Can't unlink already-existing object
jansson-2.10/CHANGES: Can't unlink already-existing object
jansson-2.10/test/: Can't update time for jansson-2.10/test

**Comment by AndrewBelt** [comment]
Are you and to compile anything? Write a hello works C program and compile with `cc hello.c`

**Comment by metaphorz** [comment]
It's been a while since coding, so a good exercise. Here is hello.cpp:

#include <iostream>
#include <string>
using namespace std;

int main() 
{
  cout << "Hello, World!";
  return 0;
}


then g++ hello.cpp generates:

g++: warning: couldn't understand kern.osversion '17.2.0
In file included from /opt/local/include/gcc48/c++/bits/postypes.h:40:0,
                 from /opt/local/include/gcc48/c++/iosfwd:40,
                 from /opt/local/include/gcc48/c++/ios:38,
                 from /opt/local/include/gcc48/c++/ostream:38,
                 from /opt/local/include/gcc48/c++/iostream:39,
                 from hello.cpp:1:
/opt/local/include/gcc48/c++/cwchar:44:19: fatal error: wchar.h: No such file or directory
 #include <wchar.h>
                   ^
compilation terminated.

**Comment by AndrewBelt** [comment]
Yup, your compiler is broken, so this isn't an issue with Rack.

However, it looks like you are actually using gcc instead of Apple's copy of clang aliased to "gcc". I believe it will still work when building Rack (assuming you can get it to work at all) but I haven't tried it. However, you probably need to recompile gcc with brew (or unbottle it) by using the normal brew incantations: `brew update`, `brew upgrade`?, `brew update gcc`, `brew doctor`.

**Comment by metaphorz** [comment]
I scrounged through some stackoverflow stuff and it suggested installing the xcode command tools like this: xcode-select --install . That made it so that basic compilation (e.g., hw) works.  I'll try recompile as you suggest and also re-clone to see what is going on

**Comment by Robb-Greathouse** [comment]
I did the xcode-select --install and still get the error on github.com/operator-framework/operator-sdk as well.

**Comment by rekcah78** [comment]
@Robb-Greathouse same problem, i solved it with go get -u github.com/golang/dep/cmd/dep
