### ISSUE TITLE
Script for converting SVG panels to C++ modules

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/Rack#374]
https://gist.github.com/AndrewBelt/303a4f2eedd0618bbacd10dd133c4b81

**Comment by gratrix** [comment]
I've gone the other way, In a special build I can make it write out the SVG when I add a module :)

**Comment by cschol** [comment]
Interesting approach.

I would like to have the `.cpp` file in `px` values (without the `mm2px` function). Is that possible with this approach? I create **90x380px** canvas, create a widgets layer and place a blue rectangle at the bottom. 

The coordinates seems to be off. The rectangle sits in the **upper left corner**.

```
 <g
     inkscape:label="widgets"
     inkscape:groupmode="layer"
     id="layer1"
     transform="translate(0,-196.45832)">
    <rect
       style="fill:#0000ff"
       id="FREQ"
       width="30"
       height="30"
       x="0"
       y="546.45831"
       inkscape:label="FREQ" />
  </g>
```

I read Inkscape defines (0,0) in the **lower left corner**, but the number (546.45831) is too big anyway. There is a `<translation>` tag in the `.xml` file that seems to be in the right range to get it to the expected value: 546.45-196.45 = 350. That seems right as a `y` coordinate with the height of the rectangle being 30 px.

The script above does not seem take into account the `<translation>` tag though.

What am I doing wrong?

**Comment by AndrewBelt** [comment]
>The script above does not seem take into account the <translation> tag though.

There's your problem.

**Comment by cschol** [comment]
Fair enough, but 546.45 does not seem correct in units of **mm** either, i.e. as input to `mm2px()`.

Is this setup correct in Inkscape?

![settings](https://user-images.githubusercontent.com/624427/34776899-aaa0319c-f5d5-11e7-8cac-de67853cb568.png)

What other setup is needed to make this script work in its original state, i.e. **with** `mm2px()`?

**Comment by AndrewBelt** [comment]
Well, that's because it's not 546.45, it's that plus the transformed value. I think you can "normalize" the translations by ungrouping/regrouping, or by hand with a text editor.

**Comment by michaelpalumbo** [comment]
> I've gone the other way, In a special build I can make it write out the SVG when I add a module :)

@gratrix could you share this script?

**Comment by AndrewBelt** [comment]
Closing as this script has been obsoleted by `helper.py`.
