### ISSUE TITLE
Audio/MIDI port widget

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/Rack#375]
Continuing the conversation from #366, I think it would be a good idea to include a universal audio/MIDI widget that combines the functionality of @bontric's MidiIO and my Audio stuff each into a context menu. I propose after v0.5 we merge all audio and MIDI dropdown boxes from our Audio/MIDI interface modules into one of these ports.

![2017-11-09-190028_1354x545_scrot](https://user-images.githubusercontent.com/338179/32635988-c274dd70-c580-11e7-8a91-f225870a8db5.png)
*@milholen, CC BY-NC 4.0*

To use them, simply left (or right?) click to display a dropdown menu. For audio:
- audio device
- block size
- sample rate

For MIDI:
- MIDI device, including computer keyboard
- MIDI channel
- octave transpose
- note transpose?
- panic

Just an idea, maybe VCV Bridge could use the "ADAT" analogy? Hopefully that doesn't confuse people.
- bridge channel

To represent an active interface, a green/red activity LED should be beside the port like most real audio/MIDI interfaces.

For v0.5, I'll just hack together something for the two audio interfaces I've planned in #82, using dropdown menus.

**Comment by synthi** [comment]
but still can use several of those modules at once??

**Comment by AndrewBelt** [comment]
Yes.

**Comment by AndrewBelt** [comment]
@bontric Working on this today or tomorrow. It will replace the MidiIO.{hpp,cpp} files.

**Comment by bontric** [comment]
@AndrewBelt great! looking forward to continue the work on #81

**Comment by AndrewBelt** [comment]
Closing since Core modules are fully redesigned now.
