### ISSUE TITLE
About VCV store

### ISSUE THREAD

**Issue by HoRaMusic** [VCVRack/Rack#376]
I have several questions about the VCV store:

When the store will be ready? I assume on VCV 1.0 but I m not sure.

If I sold modules before the store exists, will it be possible to give access to next versions host on VCV store for users who bought the modules previously?

Thank you

**Comment by AndrewBelt** [comment]
For commercial plugins, it will open Black Friday. For third party plugins, slightly after v1.0 (hopefully one week).

It won't automatically be possible. You will have to collect the users' VCV account email addresses so that you can give them to me later. I will merge them into my system for you for free, but only upon adding your plugins to the store.

**Comment by rafzael** [comment]
Ok, many thanks, I will collect the mail. 
I plan to launch a kick starter campain, the supporter will get 0.5.0 version of  bundle and all future updates (for the same price than on the store when available. The campain is made to fund the website creation and the updates on modules. The goal will be pretty low, between 100 and 200 euros. In this way I don't need to open on online shop for 2 month :)

**Comment by AndrewBelt** [comment]
You might consider Gumroad, since it's designed as a money-for-digital-goods platform. There would be virtually no manual work on your part and you could have customers enter a special note when purchasing if their VCV email is different from the one used for Gumroad.

**Comment by rafzael** [comment]
Ok, thank you, I gonna have a look on Gumroad, I didn't knew it.

**Comment by AndrewBelt** [comment]
Also, Kickstarter takes 10% or something, only lasts a month, you must go through an annoying approval process, and it takes about a month after ending to actually get your money.

**Comment by rafzael** [comment]
Hi, I wonder when it will be possible to add comercials plugins to VCV store and how these will be hosted?
Does the plugins will be put in a list witheout pictures like any others?
What will be the differences in the way to write the plugin manifest for these ?

Thanks

Raf

**Comment by AndrewBelt** [comment]
I can send you an offer today. Could you email contact@vcvrack.com so I can make sure I have your email address?

**Comment by phdsg** [comment]
is there a _pay-what-you-want_ option for selling on the vcv-store?

**Comment by AndrewBelt** [comment]
@phdsg No, and there likely won't ever be. "Pay what you want" is confusing to the customer and brings only a small fraction of the profit compared to an appropriately priced plugin.
