### ISSUE TITLE
vcv rack crash down

### ISSUE THREAD

**Issue by soundas** [VCVRack/Rack#377]
hey,

i cant start vcv on my system.

if i start a audio interface the software crash down.

if i choose a vco i only see a small black point.
please help me :-)

**Comment by martin-lueders** [comment]
Could you, please, provide some more information, such as:

What kind of computer (PC, Mac)?
What OS (Win7, Win10, OSX 10.??, what kind of Linux)?
Which version of Rack (0.4.0, or dev from sources)?
What audio interface do you use?

Without that information, it is impossible to guess what your problem could be.

**Comment by soundas** [comment]
Yes sure, windows 7, terratec phase 26 audio interface. I instaled the latesed version from the webside.

Thx

**Comment by modlfo** [comment]
I'm closing this one since no more information was provided about the problem.
