### ISSUE TITLE
Plugin installation Fail thread

### ISSUE THREAD

**Issue by Aggrodackel** [VCVRack/Rack#379]
OS (if applicable): Ubuntu
Version (or "dev" if compiling from source): 0.4.0
Ok so I thought since I am getting problems installing a few plugins I thougt I'd open a thread here.

First problem:
lucky xxl

make
g++ -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/Tick.cpp.o src/Tick.cpp
In file included from src/Tick.cpp:3:0:
src/SevenSegmentDisplay.hpp:4:7: warning: ‘virtual void SevenSegmentDisplay::draw(NVGcontext*)’ can be marked override [-Wsuggest-override]
  void draw(NVGcontext *vg);
       ^~~~
src/SevenSegmentDisplay.hpp:14:7: warning: ‘virtual void SevenSegmentDot::draw(NVGcontext*)’ can be marked override [-Wsuggest-override]
  void draw(NVGcontext *vg);
       ^~~~
src/Tick.cpp:26:7: warning: ‘virtual void Tick::step()’ can be marked override [-Wsuggest-override]
  void step();
       ^~~~
src/Tick.cpp: In member function ‘virtual void Tick::step()’:
src/Tick.cpp:44:32: error: ‘gSampleRate’ was not declared in this scope
  clock_phase += (bpm / 60.f) / gSampleRate * 12;
                                ^~~~~~~~~~~
src/Tick.cpp:44:32: note: suggested alternative: ‘glSampleMaski’
  clock_phase += (bpm / 60.f) / gSampleRate * 12;
                                ^~~~~~~~~~~
                                glSampleMaski
../../compile.mk:53: recipe for target 'build/src/Tick.cpp.o' failed
make: *** [build/src/Tick.cpp.o] Error 1

**Comment by Strum** [comment]
Quite a few of the 3rd party modules have yet to be updated for the latest api changes

**Comment by antoniograzioli** [comment]
**gSampleRate** was deprecated 2-3 weeks ago at least, the plugins haven't been updated since 

http://www.switchedonrack.com/replacing-code-in-your-plugins-automagically.html

**Comment by antoniograzioli** [comment]
BTW: my sources haven't been updated as well to reflect the new API, but I have them ready on my dev machine...could be the same for luckyxxl...

**Comment by AndrewBelt** [comment]
Closing since this issue is likely obsolete, otherwise it should be moved to the proper plugin's repo / support contact.
