### ISSUE TITLE
Run more Sequencer at the same time

### ISSUE THREAD

**Issue by tecnologiemusicali** [VCVRack/Rack#381]
Hi, I need to run more sequencer (SEQ-3 and Trigger Sequencer) at the same time by pressing just one button. How I can do that?
Thanks

OS (if applicable):
Version (or "dev" if compiling from source):

**Comment by Strum** [comment]
@tecnologiemusicali,  Use an external clock that has a run/stop button connected to both sequencers

**Comment by tecnologiemusicali** [comment]
I user and LFO ad external clock. Which module do you mean?

Il 12 nov 2017 12:20, "Strum" <notifications@github.com> ha scritto:

**Comment by tecnologiemusicali** [comment]
I used an LFO as external clock. Which module do you mean?

Il 12 nov 2017 12:20, "Strum" <notifications@github.com> ha scritto:

**Comment by Strum** [comment]
@tecnologiemusicali 

Try either the master clock in strum's mental modules or the clock in simple modules

**Comment by antoniograzioli** [comment]
or simply an LFO and connect it to all "Ext clock". To sync them connect step 1 of a sequencer to RESET of all others
