### ISSUE TITLE
Bi-pol option in Midi-CC-to-CV?

### ISSUE THREAD

**Issue by MarcBoule** [VCVRack/Rack#383]
Would it be possible to add an option so that Midi-CC-to-CV can output bi-polar levels (-5V to 5V) rather than 0V to 10V? Some of the modules (Clouds texture synth, for example), have CVs that are -5V to 5V, and right now require adding modules to offset the signals. For one or two midi CCs it's not too cumbersome, but when maping many buttons and knobs (LauchControl XL, for example in my case), it can get a bit ugly). 

Perhaps one easy way would be to add four items in the context menu (right click) of Midi-CC-to-CV as follows:
Row 1 bi-pol   [checkmark]
Row 2 bi-pol   [checkmark]
Row 3 bi-pol   [checkmark]
Row 4 bi-pol   [checkmark]
This way the interface is not burdened, neither is the context menu, and we still get a fair amount of control on polarities. 

Thanks to all the contributors, VCVRack is awesome!
(P.S. if it's relevant and welcome by the devs, I could add the code and submit it for approval)

**Comment by Strum** [comment]
@MarcBoule Mar I've been getting around this issue in 2 ways.

set the parameter you want to control to it's minimum then set  the controller in the middle of it's range that should give you a value somewhere near the middle of the range of the parameter you want to control.

The other way I have used is to use the pitch shifter module i made to subtract 4 (it's maximum octave shift) from the controller value.

I'll change the range of the pitch shifter from 8 to 10 so it can get a controller output  +/- 5
