### ISSUE TITLE
Widget draw() behaviour

### ISSUE THREAD

**Issue by mschack** [VCVRack/Rack#384]
I am implementing a widget for a piano keyboard (I found making a widget per key was a little taxing to the system...).  I wanted to draw the full keyboard only once and only change keys when they were hit but it only briefly appears when you load the plugin.  I assume then that you have to redraw the entire widget every time on draw()?  Is there a way to avoid having to do this?

Thanks

**Comment by AndrewBelt** [comment]
You can wrap all the widgets in a FramebufferWidget and mark `dirty = true` whenever you want it to re-render.

**Comment by mschack** [comment]
Ok thank you!
