### ISSUE TITLE
Retina resizing issues on changing screen (OS X) 

### ISSUE THREAD

**Issue by lnikj** [VCVRack/Rack#385]
OS (if applicable): 0S X 10.12.6
Version (or "dev" if compiling from source): dev
Hardware 27" late 2015 iMac + external HP 24" 1920*1200 screen

I don't think this is the same as #89. 

Open Rack on normal screen, move to Retina:

<img width="787" alt="screenshot_14" src="https://user-images.githubusercontent.com/24451110/32726179-ed4bb946-c86f-11e7-8482-3c3eb4d33241.png">

Open Rack on Retina, move to normal screen:

![screenshot_15](https://user-images.githubusercontent.com/24451110/32726195-ff4356cc-c86f-11e7-9233-69dd93d41515.png)

**Comment by AndrewBelt** [comment]
Hmm, does resetting the zoom solve it? (Right click on the Zoom slider)
If that works, Rack can propogate an `onZoom()` event when the DPI has changed, but it's tricky to know exactly when that happens with GLFW.

**Comment by lnikj** [comment]
I'm afraid not :(

**Comment by AndrewBelt** [comment]
So even if you change the zoom level, it is still proportionally incorrectly sized?

**Comment by lnikj** [comment]
Sorry, I'm eating and had to login over VNC to check that. Idiotically I didn't check moving the slider. 

So, right clicking doesn't work to reset but changing the zoom level does :)

**Comment by AndrewBelt** [comment]
Hmm, maybe I disabled the right click "refresh" feature somehow. Anyway, this means I can solve it using my proposed method above.

**Comment by lnikj** [comment]
Great.

**Comment by AndrewBelt** [comment]
Can you confirm that e76f3c8 fixes this?

**Comment by lnikj** [comment]
Fixed!

**Comment by AndrewBelt** [comment]
Thanks for testing!
