### ISSUE TITLE
Older patches open empty since "model change"

### ISSUE THREAD

**Issue by phdsg** [VCVRack/Rack#388]
OS (if applicable): Win7-64
Version (or "dev" if compiling from source): dev (latest)

rack loads patches that were saved before the "model change" with an empty rack.
patch is loaded though. as it shows the patch name in the title bar.

i fixed my patches by replacing `manufacturer` with `plugin` in the .vcv files,
but maybe the patch loader can be fixed to be compatible with older patches.

**Comment by AndrewBelt** [comment]
There was a short window where I changed the key from `plugin` to `manufacturer`, but it is now `plugin` again. Since no Rack release uses the key `manufacturer`, it is pointless to add compatibility for that key.
