### ISSUE TITLE
MIDI input limited to one 'use' of MIDI device.

### ISSUE THREAD

**Issue by oblivionratula** [VCVRack/Rack#39]
Mac OSX 10.10.5 prebuilt and compiled:

I'd like to bring in 2 different MIDI channels from one device (e.g. the 2 Beatstep Pro sequencers on Ch. 1 and Ch. 2).  I'd expect to be able to add two MIDI Devices, and set that one to channel 1, one to channel 2, and route each to different voices.  However when trying to set the second MIDI Device to the same input device (e.g. Arturia Beatstep Pro (input) ), the selection box is blank and the program throws:
`Failed to open MIDI port: PortMidi: 'Invalid device ID'`

**Comment by nofoto** [comment]
Same problem for me - I can only use each midi device once. Current workaround is to create a few different IAC Driver buses in the Mac system Audio MIDI Setup to route the midi through.

**Comment by DarSwede** [comment]
Mine simply crashes, but I can't find any area to upload crash reports.

**Comment by AndrewBelt** [comment]
This issue is obsolete due to PortMIDI being replaced with RtMidi. Closing.
