### ISSUE TITLE
submenu item doesn't fit menu box width and line-breaks at whitespace.

### ISSUE THREAD

**Issue by phdsg** [VCVRack/Rack#390]
OS: win7-64
Rack: dev

can't think of a proper headline.
just look at the attached screenshot.
![submenu_textwrap](https://user-images.githubusercontent.com/33329578/32811526-883fe432-c9a0-11e7-8f1c-474fc8514ff9.PNG)

this is AudibleInstruments/Frames. couldn't find any other module that uses submenus.

**Comment by AndrewBelt** [comment]
Are you using Retina?

The way to fix this is to dive into blendish code, and I assume I'll solve this along with #264

**Comment by phdsg** [comment]
windows machine (edited first post).

**Comment by AndrewBelt** [comment]
Fixed a while ago.
