### ISSUE TITLE
Error when importing official plugins

### ISSUE THREAD

**Issue by DJDaniel7777** [VCVRack/Rack#391]
I have a problem when I import the three oficial plugins. An error message appears and says that 
![sense titol](https://user-images.githubusercontent.com/33688357/32833230-7691d82c-c9fe-11e7-8cc3-3c84dee4ab81.jpg)
.
Can someone help me?
Thanks

**Comment by martin-lueders** [comment]
You need to make sure that plugins and rack are compatible. It looks like your plugins are still for Rack v 0.3.1. Download them again for 0.4.0 which I assume is your Rack version.

**Comment by DJDaniel7777** [comment]
Oh, thank you!
I had Rack v 0.3.1 and plugins were for 0.4.0. I downloaded Rack v 0.4.0 and now the plugins work perfectly!
Thank you very much!
