### ISSUE TITLE
Application hangs when opening some patches

### ISSUE THREAD

**Issue by michaelpalumbo** [VCVRack/Rack#395]
OS (if applicable): OSX Sierra
Version (or "dev" if compiling from source): 0.4

Hi there,

So the app has been non-responsive when I try to open a saved patch. This usually occurs when I attempt to open a larger patch (~15 modules), and then it continues to occur at the next launch, regardless of the patch size. 

Best,

Michael

**Comment by AndrewBelt** [comment]
Can you rule out the Audio Interface and MIDI modules? Come up with a patch which consistently hangs, remove those modules with a text editor, and see if it still crashes.

**Comment by michaelpalumbo** [comment]
Ah, I think that was it. I’m using JackRouter to pipe audio in/out of Ableton in some of my patches. So when I attempt to open a patch that uses a different audio device — including a blank new patch — this happens. Seems if I change the audio device before I switch patches there is no crash.

Best,

Michael

**Comment by AndrewBelt** [comment]
This issue is old and likely obsolete. Comment if issue is still present. Closing.
