### ISSUE TITLE
SEQ-3 Steps Do Not "Turn Off"

### ISSUE THREAD

**Issue by jonheal** [VCVRack/Rack#398]
OS (if applicable): Windows 10
Version (or "dev" if compiling from source): 0.4.0

Turning steps "off" in the SEQ-3 sequencer has almost no effect. Gates fire for every step, regardless, with the "impact" of the gate only slightly diminished for the steps that are "off."

**Comment by jonheal** [comment]
I withdraw my bug report as others have convinced me this is not entirely abnormal behavior for some hardware sequencers.

**Comment by milholen** [comment]
@jonheal you can close this ticket if the issue is resolved.

**Comment by AndrewBelt** [comment]
@jonheal What do you mean? If a gate is off, the gate output should be 0V during that entire step. If the gate is on, the gate will become 10V for a period of time depending on the gate mode found in the right-click context menu. There are no intermediary values.

**Comment by jonheal** [comment]
I think I simply did not understand how it worked. Disregard.

--
Jon Heal
Have a nice day!

**Comment by jonheal** [comment]
Disregard. User error.
