### ISSUE TITLE
Module tags requests

### ISSUE THREAD

**Issue by antoniotuzzi** [VCVRack/Rack#401]
can we add: 
RECORDER_TAG
RENDERER_TAG
TEACHING_TAG (or INSTRUCTIONAL_TAG)
CHORUS_TAG
PHASER_TAG
FLANGER_TAG (EFFECT_TAG is too  generic)

👍

**Comment by AndrewBelt** [comment]
I'll add RECORDER_TAG, and maybe expand the effects.

**Comment by alikins** [comment]
I sometimes look through the add module list looking for open source modules, so
maybe a OPEN_SOURCE_TAG?

A FREE tag could be useful as well, but FREE isn't really something that is determined at plugin build time (and can change at any time). For the most part, OPEN_SOURCE would be known at build time and not as likely to change for that particular build.

As a user, I sometimes want to have modules tagged as FREE or FREELY_DISTRIBUTABLE especially when planning to share a patch. 

(I suppose the tags could be more specific about the licensing (ie, BSD3, GPL2+, etc) but that is a long and controversial list to enumerate and not super useful at runtime. Maybe better as an additional piece of metadata on Plugin or Model if it's worthwhile at all?)

**Comment by AndrewBelt** [comment]
No, tags should be for functionality, not legal details. Put that in the plugin manifest that you submit to https://github.com/VCVRack/community

**Comment by alikins** [comment]
METER perhaps? 

Some existing modules that could use that tag:

CV voltage meters
- ML_modules Volt Meter, Alikins Specific Voltage, CF Variable, Computerscare Debug, Ohmer Metriks

Misc
- ML_modules BPM Tools, AS BPM/Delay tools, NSYSTHI Hot Tuna, (and 4Hands and Const Add Multi off label)

VU meters (though, maybe more VISUAL than METER...)
- AS Mono VU Meter, Stereo VU Meter, Bogaudio VU, NYSTHI Single VU Meter, Dual VU Meter, Single Slim VU Meter, Gratix VU


<img width="1486" alt="screen shot 2018-11-14 at 11 22 38 pm" src="https://user-images.githubusercontent.com/15162/48530207-aa84be80-e864-11e8-861f-6950a9ed4ea0.png">

**Comment by AndrewBelt** [comment]
Use "Visual" for all of the above.
