### ISSUE TITLE
audio core more unstable under windows

### ISSUE THREAD

**Issue by HoRaMusic** [VCVRack/Rack#405]
OS (if applicable): win7
Version (or "dev" if compiling from source): latest source, just before 0.5

When I run the rack from the lastest sources and test a small patch i noticed two things:

-I don't get the same audio interface choices, instead of a long list in wich I was selecting Asio for focusrite 18i20 I get only two choices that are "default device" and line out (8in 8 out) for focusrite.
-There is scratch in the sound even with small patches, much more than on previous 0.4.X I was using (that already has the zooming option) 

I notify than I m running on the native graphics chipset of my motherboard then maybe it's due to graphical computing.

**Comment by AndrewBelt** [comment]
Have you compiled ASIO into RtAudio during the make dep step? It's a bit more involved but I've chosen to not include it as default.

**Comment by modlfo** [comment]
Closing since there's no follow up by @HoRaMusic. Reopen if the issue still happens.
