### ISSUE TITLE
Make failing when following README guide

### ISSUE THREAD

**Issue by morga206** [VCVRack/Rack#408]
OS (if applicable): Win 10
Version (or "dev" if compiling from source): 0.4.0

I've been trying to follow the guide in the readme for hours, but when I get to the "make" command it fails with the following error:

g++ -Iinclude -Idep/include -Idep/lib/libzip/include -MMD -g -O3 -march=nocona -                            ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN                             -D_USE_MATH_DEFINES -Wsuggest-override -std=c++11 -c -o build/src/asset.cpp.o sr                            c/asset.cpp
g++ -Iinclude -Idep/include -Idep/lib/libzip/include -MMD -g -O3 -march=nocona -                            ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN                             -D_USE_MATH_DEFINES -Wsuggest-override -std=c++11 -c -o build/src/app.cpp.o src/                            app.cpp
g++ -Iinclude -Idep/include -Idep/lib/libzip/include -MMD -g -O3 -march=nocona -                            ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN                             -D_USE_MATH_DEFINES -Wsuggest-override -std=c++11 -c -o build/src/main.cpp.o src                            /main.cpp
In file included from src/main.cpp:2:0:
include/gui.hpp:3:10: fatal error: GL/glew.h: No such file or directory
 #include <GL/glew.h>
          ^~~~~~~~~~~
compilation terminated.
make: *** [compile.mk:54: build/src/main.cpp.o] Error 1

**Comment by morga206** [comment]
I also tried installing Rack on a virtual machine running Ubuntu 16.04, and got the same exact error.

**Comment by bontric** [comment]
This looks like you forgot:

git submodule update --init --recursive

**Comment by morga206** [comment]
Thanks, but I did run that command. It seemed to work okay and gather everything, but in MSYS2 the following did pop up:

`': not a valid identifierline 88: export: dashless

That message did not appear when I entered the same command in Ubuntu.

**Comment by AndrewBelt** [comment]
That message can be ignored. You should continue with the build as normal.

**Comment by morga206** [comment]
I did, and I got the error I posted about originally...

**Comment by AndrewBelt** [comment]
You're saying that when running `make dep`, the build can't find `dep/include/GL/glew.h`?

**Comment by morga206** [comment]
Yes, it can't find that. I'm definitely not missing a step, I've even uninstalled and reinstalled MSYS2 a few times.

**Comment by AndrewBelt** [comment]
Does `make dep` complete successfully?

**Comment by morga206** [comment]
It looks like that's where the problem is, I had to add a directory to my path for it to complete successfully. Thanks for the help!
