### ISSUE TITLE
no asio drivers on latest dev build

### ISSUE THREAD

**Issue by Phal-anx** [VCVRack/Rack#409]
OS (if applicable): Win7
Version (or "dev" if compiling from source): Dev

today i downloaded and build the latest rack dev... after "make run" i noticed that the choices in the audio device are pretty small now and all the asio drivers are gone..

**Comment by AndrewBelt** [comment]
Because a few people complained that they didn't have audio dependencies, I've removed extra audio APIs by default, so run `make RTAUDIO_ALL_APIS=1` in the `dep/` directory.

**Comment by djpeterso23662** [comment]
Hi Andrew!  I am not having any luck with this. I pulled a fresh git clone this morning.  

**make dep RTAUDIO_ALL_APIS=1**
```
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating rtaudio.pc
config.status: creating Makefile
config.status: creating tests/Makefile
config.status: creating doc/Makefile
config.status: creating doc/doxygen/Doxyfile
config.status: executing depfiles commands
config.status: executing libtool commands
make -C rtaudio-5.0.0
make[2]: Entering directory '/home/djpeter1/Rack.171119/dep/rtaudio-5.0.0'
Making all in .
make[3]: Entering directory '/home/djpeter1/Rack.171119/dep/rtaudio-5.0.0'
  CXX      RtAudio.lo
RtAudio.cpp:2694:10: fatal error: asiosys.h: No such file or directory
 #include "asiosys.h"
          ^~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:556: RtAudio.lo] Error 1
make[3]: Leaving directory '/home/djpeter1/Rack.171119/dep/rtaudio-5.0.0'
make[2]: *** [Makefile:621: all-recursive] Error 1
make[2]: Leaving directory '/home/djpeter1/Rack.171119/dep/rtaudio-5.0.0'
make[1]: *** [Makefile:142: bin/librtaudio-6.dll] Error 2
make[1]: Leaving directory '/home/djpeter1/Rack.171119/dep'
make: *** [Makefile:46: dep] Error 2
```

**Comment by AndrewBelt** [comment]
That's the reason I disabled it, because you have to "do stuff" to build it.
I don't yet know what all that stuff is, I just know that it works for me for the upcoming v0.5 build, so I'll tend to it later.

**Comment by djpeterso23662** [comment]
Thanks for the clarification.  I apologize for taking up your time on this, I know you are busy.

**Comment by dBiz** [comment]
I've tried too ( due to glitch and pop using default RTAUDIO from latest dev ) but I've got the same error: asiosys.h don't found ... I've tried copy in the main folder (rtaudio) all the other files in the include folder but doesn't work.

I'm on Windows 10 with RME UCX

**Comment by dBiz** [comment]
with latest dev works wiht RTAUDIO_ALL_APIS=1!

**Comment by modlfo** [comment]
Closing this issue looks like fixed/clarified. Feel free to comment if needed.
