### ISSUE TITLE
module delete causes crash

### ISSUE THREAD

**Issue by davephillips** [VCVRack/Rack#414]
Linux Fedora 23
dev Rack

Sometimes when I delete a module from a patch Rack will crash. The patch reloads all right, but I can't seem to find any predictability in the behavior, it doesn't seem to happen only to specific modules.

No error is reported, only a notice of the segfault. I'll run some 'make debug' sessions to see if I can catch the error there.

I'd like to nail this one down, it's difficult to work knowing that at any moment the work can crash when I remove a module.

**Comment by AndrewBelt** [comment]
If it makes you feel better, your file is autosaved every 15 seconds.

**Comment by AndrewBelt** [comment]
Duplicate of #378
