### ISSUE TITLE
Rack.exe Entry point not found error

### ISSUE THREAD

**Issue by jaroskamc** [VCVRack/Rack#415]
OS 0.4(Newest)):

I got error saining this:

![image](https://user-images.githubusercontent.com/33846253/33041523-47687aae-ce47-11e7-98e9-e499390ad374.png)

How to solve this, if it was solved before close and redirect me to soliution, thanks.
I have same error with Eseries.

**Comment by AndrewBelt** [comment]
Have you used an older version of Rack before this? You seem to be mixing the old plugins with the new Rack. Delete the plugins directory or all of the Rack directory and start over.

**Comment by jaroskamc** [comment]
It helped. Thanks.
