### ISSUE TITLE
Rack freezes on quit (Mac)

### ISSUE THREAD

**Issue by modlfo** [VCVRack/Rack#416]
OS (if applicable): MacOs
Version (or "dev" if compiling from source): dev

I'm getting random freezes of the app when exiting. I think it has something to do with the audio interface. To trigger add an "Audio Interface", select the output and quit. It takes a few repetitions for me to trigger it.

@jeremywen found a way of trigger it consistently: add an Audio Interface, duplicate it and quit the application.

**Comment by antoniotuzzi** [comment]
I'm experiment the same deadlock: it's at core audio level

**Comment by jeremywen** [comment]
Looks like he may have fixed something related here https://github.com/VCVRack/Rack/commit/4f703e394404c733e18d68d6cf5256a4e2bc561e

**Comment by modlfo** [comment]
It doesn't seem to freeze anymore, except when I duplicate the audio interface.

**Comment by AndrewBelt** [comment]
You may the correct that the bug is gone, since I am no longer using mutexes between the engine thread and audio driver thread. I'll close this for now. Re-open if it returns.
