### ISSUE TITLE
post-upgrade to 5.0, all community plugins gone

### ISSUE THREAD

**Issue by michaelpalumbo** [VCVRack/Rack#418]
OS (if applicable): Sierra
Version (or "dev" if compiling from source): 5.0

Just up'd from 4.0 to 5.0. Thanks for the update! 

However, all of the plugins from the community (from the wiki page) are no longer accessible, is there something I'm doing wrong?

**Comment by AndrewBelt** [comment]
You mean v0.5, etc, and plugins between minor versions are not compatible.

**Comment by michaelpalumbo** [comment]
Yep, and thanks. So how can I continue using the other plugins - could I use the dev version then?

**Comment by AndrewBelt** [comment]
Depends on the plugin's version. You can use dev if you want to compile everything, or v0.4 if you want to use v0.4 plugins.

**Comment by michaelpalumbo** [comment]
Ah, ok,

Thank you Andrew!

Best regards,

Michael
