### ISSUE TITLE
knobs jumping to maximum on touch, surface pro 3

### ISSUE THREAD

**Issue by Unpaid-Intern** [VCVRack/Rack#419]
OS: Windows 10
Version: 0.5.0

if I attempt to manipulate knobs on any module the knob jumps to maximum. I can occasionally get it to reverse direction after dragging my finger/pen around, but it will immediately go to minimum value and I have difficulty getting it to reverse direction a second time.

Mouse interaction is fine. The settings.json "allowCursorLock: false" fix from ver. 0.4.0 doesn't seem applicable in ver. 0.5.0 since I do not see a settings.json file in the rack directory.

**Comment by AndrewBelt** [comment]
The rack local directory is now My Documents/Rack. Edit the settings file there.

**Comment by Unpaid-Intern** [comment]
I can confirm it's there. This solved my issue. Thanks
