### ISSUE TITLE
Loading a json file, missing background, knob bitmaps

### ISSUE THREAD

**Issue by teotigraphix** [VCVRack/Rack#42]
Hey,

Windows 7, the app works great when creating things myself, eg bitmap, knobs are all drawn correctly. When I tried to load a json file created by another user, I get this.
![empty-racke](https://user-images.githubusercontent.com/226417/30321118-ef846cc6-9782-11e7-9466-52167511df0b.PNG)

The patch itself plays perfect.

**Comment by steveangstrom** [comment]
I also experienced this
![ndabhggmagieenli](https://user-images.githubusercontent.com/8482649/30337087-24cf8558-97df-11e7-89a4-ebd35fff5ae8.png)

**Comment by hwaki** [comment]
Got same problem when json files are loaded from directories outside of the Rack folder (where the application executable resides). Solved by moving the saved json file next to the application (same directory).

**Comment by teotigraphix** [comment]
Ah yeah then it's a resource directory problem where he is using the same structure as he has plugins laid out. Thanks.

**Comment by teotigraphix** [comment]
Confirmed, locating the json file in the app directory solves the issues for now.

![asdasd](https://user-images.githubusercontent.com/226417/30338277-1dd57a30-97b9-11e7-8823-d5a13934eefc.PNG)

**Comment by steveangstrom** [comment]
confirmed, loading a json from the root of the application directory  ( _/vcv-rack_ )  will work ...
but loading a json froma child directory such as _/vcv/rack/my-racks_   will not work

**Comment by AndrewBelt** [comment]
Should be fixed in 0.3.1. Reopen if not.
