### ISSUE TITLE
Metadata Menu Items Not Selectable on Windows 10

### ISSUE THREAD

**Issue by jonheal** [VCVRack/Rack#421]
OS (if applicable): Windows 10 ver. 1709
Version (or "dev" if compiling from source): 0.5.0

If you attempt to hover over metadata menu items in the third pane of the menu, they immediately vanish.

**Comment by Euphorbium** [comment]
Same on Mac

**Comment by AndrewBelt** [comment]
Solved in Rack 0.6 with the new Module Browser.
