### ISSUE TITLE
ALSA only now, Jack and Pulse gone again

### ISSUE THREAD

**Issue by davephillips** [VCVRack/Rack#423]
Linux Fedora 23
current dev (0.5.0) Rack

Now ALSA is the only audio driver that appears in the Audio Interface module. I've rebuilt rtaudio with Jack and Pulse support, using cmake and the autoconf tools, and I've rebuilt Rack, apparently to no avail. Can I specify the inclusion of Jack and PulseAudio during the build so Rack identifies them for use with the Audio Interface ?

EDIT: Never mind. The new-built librtaudio.so wasn't copied to dep/lib. A quick couple of links and I have ALSA, Jack, and Pulse available in the Audio Driver menu.

**Comment by AndrewBelt** [comment]
:+1:
