### ISSUE TITLE
[FEATURE REQUEST] onVoluntaryDelete and onClone messages are needed 

### ISSUE THREAD

**Issue by antoniotuzzi** [VCVRack/Rack#425]
OS (if applicable):any
Version (or "dev" if compiling from source):0.5.0

some of the modules store external data (for example my complexSimpler) in a cache folder
just to be not HEAVY on the VCV file

A)  **onVoluntaryDelete**  (less important, this waste only disk space)
we need to distinguish between a delete coming from the document destruction (closing a vcv file)
and a voluntary delete: in this case, I'd like to delete the connected data! (can't do it in the dtor because there will be no persistence!)

B) **onClone**  (THIS IS VERY IMPORTANT!)
when the user do a **duplicate** using menu, we need an event to do a DEEP duplicate of external data, otherwise 2 or more object will share same files/documents with catastrophic outcomes

thanks

**Comment by AndrewBelt** [comment]
Just to make sure you're aware, Rack duplicates modules simply by serializing them and then unserializing them, so internal state will be duplicated if and only if they are included in the serialization methods (`toJson`, `fromJson`). 

What does your module do, and how does it do it? It seems like it's a sampler which holds onto a file handle. What's to stop a user from telling your module to open the same file?

**Comment by antoniotuzzi** [comment]
no problem when just opening, but as every module have an unique id, 
and file saving is based on this unique id, and the persistence of the unique id is in the JSON
when I clone I'll get 2 modules with the same unique ID and no way to separated them.

So happens this
1) module A is cloned in B
2) modules B share same uniqueID (loaded from JSON)
3) user load a new sample in module B
4) module B saves automatically in cache area, using the uniqueID the new file
5) modules A will get a file changed too (because of the same ID)

**Comment by antoniotuzzi** [comment]
(of course, if I'd save samples in JSON there will be no problem, but would be crazy to save (example) 50mb of data in a JSON doc every 15 secs)

**Comment by AndrewBelt** [comment]
It seems that what you want is *not* `onClone()` but `onCreate()`.

I propose
- `onCreate()`
- `onDelete()`
- `onReset()` renamed from `reset()`
- `onRandomize()` renamed from `randomize()`

**Comment by antoniotuzzi** [comment]
**onCreate()** as it is, is the equivalent of using the CTOR
I need the special case of duplication so an

- onDuplicate() : called on a duplicated module after it has been cloned using the "duplicate" menu


> Where are you saving the cache by the way? 
currently cache is in  Documents/Rack/plugins/nysthi/cache
before was Documents/Rack/cache

> Does your plugin need to store caches after Rack closes at all?
yes because people wants to reopen the same samples in a patch

**Comment by antoniotuzzi** [comment]
or maybe we want to introduce a new concept: "NON CLONABLE MODULE" (with the menu item highlited and unusable)

**Comment by AndrewBelt** [comment]
No to non-clonable modules, that's absurd UI.

>onCreate() as it is, is the equivalent of using the CTOR
No, as I said, it is not called when Rack loads a patch. You could initialize your cache in this method, because it is called when the user creates a module explicitly.
I am not sure if it should be called before or after `fromJson()` when loading a patch, but either way you will be able to detect when you should create a new cache file.

**Comment by antoniotuzzi** [comment]
I need to understand better scenarios with onCreate but is not enough

**Add module, load sample and duplicate it:**

A) add module A
B) onCreate on A is called and uniqueID is generated
C) on A a sample is loaded and saved with uniqueID
D) toJson saves the unique ID

E) A duplicated in B using menu
F) onCreate is Called and uniqueID is generated for B
G) fromJSON is called and the uniqueID is substituted: now B have the same ID (and samples) as the module A !!!

at this point I'd like to receive the  **onDuplicate()**
H) onDuplicate received by module B
I) B generates a new uniqueID
J) B saves all the samples, cloning it with new uniqueID
K) toJson (every 15secs) saves the new uniqueID for module B (now is fully cloned)

**Comment by AndrewBelt** [comment]
It isn't difficult:

E) A duplicated in B using menu
F) onCreate is Called and uniqueID is generated for B
G) fromJSON is called and ~~the uniqueID is substituted~~ `if (!uniqueId) uniqueId = json_integer(...)`

**Comment by antoniotuzzi** [comment]
ok, maybe we are at the end
here 3 cases

1) open a patch  
A) module is created (onCreated not called)
B) fromJson is called and uniqueID is loaded and reassigned, if not loaded is generated a new one

2) add module
A) module is added
B) onCreate is called, uniqueID is generated
C) toJson saves uniqueID

3) module is duplicated
A) module is added
B) onCreate is Called, uniqueID is generated
C) fromJson is called and  uniqueID is loaded but uniqueIDfromJSON != uniqueID
D) duplicated all the files and reassing the uniqueID

seems you covered all ... 👍

**Comment by AndrewBelt** [comment]
Fixed with 36cd050ba428a7687bea3a60b115c6c03c56bbdb

**Comment by AndrewBelt** [comment]
I'm going to deprecate `onCreate()` and `onDelete()`. They're misleading (everyone thinks they're equivalent to constructors/destructors), and they create "file leaks" if you rely on them for file creation/deletion. Consider

- Create new patch
- Create module, `onCreate()` is called, creating a WAV file somewhere
- Save patch
- Delete module, `onDelete()` is called, deleting the WAV file
- Revert patch. Now it can't find the file.

Or

- Create new patch
- Create module, `onCreate()` is called, creating a WAV file somewhere
- Save patch
- Close Rack
- Delete patch file
- WAV file is still around, without an associated patch file

So either we have proper asset management or none at all.

**Comment by antoniotuzzi** [comment]
ouch, this is going to kill my samplers (I've changed them with 6.0 )
deprecated till version ? 0.8.0 ?

**Comment by AndrewBelt** [comment]
If you haven't noticed, `onCreate()` is not called at all in Rack 0.6.0 due to a mistake in the Module Browser. Since that method is "broken", I have removed both of them in 0.6.1dev. I'm willing to consider other solutions, but I'm restricted by not breaking ABI compatibility.
