### ISSUE TITLE
make problems

### ISSUE THREAD

**Issue by reverbrick** [VCVRack/Rack#428]
OS (if applicable): Linux odroid 3.8.13.30 #1 SMP PREEMPT Fri Feb 20 14:34:08 BRST 2015 armv7l armv7l armv7l GNU/Linux
Version (or "dev" if compiling from source): dev

Hi there,
I try to compile from source on Odroid U3.
After a small fight with deps (policy CMP0042 in rtaudio fixed by
https://github.com/slembcke/Chipmunk2D/commit/d2883f3edf95d329fea96ddf2d7e156afa4180fe)
I run into issues with make command:

g++ -Iinclude -Idep/include -Idep/lib/libzip/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/app.cpp.o src/app.cpp
g++-4.8.real: error: unrecognized argument in option ‘-march=nocona’
g++-4.8.real: note: valid arguments to ‘-march=’ are: armv2 armv2a armv3 armv3m armv4 armv4t armv5 armv5e armv5t armv5te armv6 armv6-m armv6j armv6k armv6s-m armv6t2 armv6z armv6zk armv7 armv7-a armv7-m armv7-r armv7e-m armv8-a armv8-a+crc iwmmxt iwmmxt2 native
g++-4.8.real: error: unrecognized command line option ‘-Wsuggest-override’
make: *** [build/src/app.cpp.o] Error 1

Pls help!

**Comment by AndrewBelt** [comment]
Your compiler is too old. Either upgrade or remove the `-Wsuggest-override` flag from compile.mk.

**Comment by reverbrick** [comment]
Hello Andrew, it is possible, but I was really hoping to compile. Will try to remove the flag. At least now I know where they are. Thanks!

**Comment by AndrewBelt** [comment]
ARM isn't supported by Rack, so closing.
