### ISSUE TITLE
Rack /w jack & alsa support: Error while loading shared libraries: librtaudio.so.6

### ISSUE THREAD

**Issue by Cordoha** [VCVRack/Rack#430]
Ubuntu 16.04
Rack 0.5.0 dev

Trying to build Rack with jack and alsa support as mentioned in the [wiki](https://github.com/VCVRack/Rack/wiki/Add-Support-for-Jack-on-Linux-(dev)).

When building Rack, I went from ``cloning`` the repo, to ``git submodule update --init --recursive``, to ``make dep``. **Building ``rtaudio``**, then building rack with ``make``.

Is that how I'm supposed to build both rtaudio and rack to get jack support?

When doing this, Rack fails to run.
>./Rack: error while loading shared libraries: librtaudio.so.6: cannot open shared object file: No such file or directory
Makefile:50: recipe for target 'run' failed
make: *** [run] Error 127

What do I need to do to successfully get Rack to run with jack?

Thanks in advance.

**Comment by MarcBoule** [comment]
Exact same problem happening here (Rack dev, Ubuntu 17.10, low latency kernel).
I wanted to start /dep all over again to make sure it was fresh, so I:
* deleted the /dep folder
* from the main rack folder:  git checkout dep/Makefile
* make dep
* did the procedure for jack as described on the wiki
* make run
* here's the output I get:
```
LD_LIBRARY_PATH=dep/lib ./Rack
./Rack: error while loading shared libraries: librtaudio.so.6: cannot open shared object file: No such file or directory
Makefile:50: recipe for target 'run' failed
make: *** [run] Error 127
```

**Comment by MarcBoule** [comment]
I believe the fix would be to modify one of the lines in the wiki to be:
`cp .libs/librtaudio.so ../lib/librtaudio.so.6`
instead of
`cp .libs/librtaudio.so ../lib/`
I did this and it worked for me.
Not sure if the is the recommended solution though.

**Comment by Cordoha** [comment]
I did not recompile anything, just did as you suggested, and Rack starts up. Testing with a VCO, and an Audio Interface module works with JACK as a driver.

When closing Rack:  
>[info] Loading settings ./settings.json
[info] Saving settings ./settings.json
[info] Saving patch ./autosave.vcv
[debug] Aborting audio stream 2
[debug] Closing audio stream 2

I don't see any errors. Hopefully it's a proper solution. It works as suggested.
Thanks.

**Comment by bontric** [comment]
I updated the wiki. The solution is to replace 
```
cp .libs/librtaudio.so ../lib/
```

with

```bash
cp -a .libs/librtaudio.so* ../lib/
```

Which will copy all librtaudio.so file _links_ and `ibrtaudio.so.6` while preserving the links.

**Comment by Cordoha** [comment]
Awesome, it worked. Thanks a lot.
