### ISSUE TITLE
Touch Problem(s)

### ISSUE THREAD

**Issue by w3stgaard** [VCVRack/Rack#431]
OS (if applicable): Win10 
Version (or "dev" if compiling from source): 0.5.0

Touching a knob causes a full "gain / 100%" within miliseconds. I am not able to adjust that knob afterwards anymore. Is there a specific adjustment that I missed ? 

(BTW: the rest works fine, as far we have tested it: drag and drop, cable adjustment, submenu on modules, top adjustments, menu)

**Comment by AndrewBelt** [comment]
In `settings.json` file,  change "lockCursorPosition" to false.

**Comment by w3stgaard** [comment]
There is no settings.json file after installing. When I create one with the content 

{
  "lockCursorPosition": false
}

nothing happens.

**Comment by AndrewBelt** [comment]
You have to run Rack once to generate it. It's in `My Documents/Rack/`

**Comment by w3stgaard** [comment]
Thx, found it and updated our internal wiki. Is there a simple way to use the program/install dir only instead of "...My Documents/Rack/ " ?

**Comment by AndrewBelt** [comment]
No, not without changing the source and compiling a custom build.

**Comment by w3stgaard** [comment]
ok, thank you. maybe this is possible setting for the future to keep a specific rack version and its plugins in jail/on the same place to be able to use more than 1 vcv rack version and its plugins on the same machine or thru lan networking without problems.

Via mklink you are able to relocate a directory on windows to another place, but this is not the best solution. We and other Studios use Backup-Systems / Servers, were all Software is located. We do not use documents directories and keep all the data and libraries safe from windows :)

**Comment by AndrewBelt** [comment]
This is off topic, so move the discussion to this thread #265
