### ISSUE TITLE
[FEATURE REQUEST] Limit Zoom to Integer Values

### ISSUE THREAD

**Issue by jonheal** [VCVRack/Rack#432]
OS (if applicable):
Version (or "dev" if compiling from source): 0.5.0

 Limit zoom to integer values.

**Comment by AndrewBelt** [comment]
Why?

**Comment by MarcBoule** [comment]
I assume it might be because the decimals in the zoom factor are not really needed nor relevant (from my point of view at least), and removing them might make it look cleaner.

**Comment by AndrewBelt** [comment]
Okay, I can buy that.

**Comment by jonheal** [comment]
I see you responded later, but to answer your question, the zoom never seems to settle on an integer and zooming to 125.05% feels unsettling. 😊

--
Jon Heal
Have a nice day!

**Comment by AndrewBelt** [comment]
Fixed in 264c040
