### ISSUE TITLE
[FEATURE REQUEST] Eliminate Gray Wire

### ISSUE THREAD

**Issue by jonheal** [VCVRack/Rack#433]
OS (if applicable):
Version (or "dev" if compiling from source): 0.5.0

The gray wire against the gray background is difficult to see, especially when dimmed.

**Comment by milholen** [comment]
@jonheal currently the patch cable colors are red, yellow, green, blue, and black (I guess you could call the black a very dark gray).

If you're compiling Rack from source, you can edit the patch cable colors in WireWidget.cpp (see lines 73-81), they are specified as hexadecimal color codes:
https://github.com/VCVRack/Rack/blob/v0.5/src/app/WireWidget.cpp

We may offer customizable patch cable colors in a future revision, but there's no single color that will work well on all panel backgrounds.

**Comment by jonheal** [comment]
I guess I would humbly suggest changing the Black wire to purple. Also Red and Green are going to be problematic for color blind users. Maybe Orange and Teal?

In any case, this is a minor issue. :-)

**Comment by jph-wacheski** [comment]
Could have a little cable color selector/editor in the top bar,. color coding could be useful for organizing large patches,. 6 or 10 little boxes you click to select cable color,.  RMB to choose color of boxes,. perhaps it sounds frivolous however would be very useful.

**Comment by AndrewBelt** [comment]
Removed black cable in b2f4d2c
