### ISSUE TITLE
Disable plug lights

### ISSUE THREAD

**Issue by djhyperspace** [VCVRack/Rack#439]
OS (if applicable):
Version (or "dev" if compiling from source): normal
 
is there any way to turn the plug lights off?? wheres the button gone? its a bit distracting. on a big patch, how much cpu is it using?

**Comment by AndrewBelt** [comment]
I'll put it behind a `settings.json` property.

**Comment by djhyperspace** [comment]
not entirely sure what that means. I probably shouldn't be on GitHub....... but thanks I think. thanks again for your work on this.

**Comment by VSpellbound** [comment]
> on a big patch, how much cpu is it using?

when you are running a big patch open task manager or smth, where you can see cpu load. then in vcv rack press "File - open - ..."  while this window is open lights are off. Im my case when whole patch is - 50% CPU, without lights - 30%.

**Comment by AndrewBelt** [comment]
You're pausing the entire main thread when you do that, not just the plug lights.

**Comment by VSpellbound** [comment]
> You're pausing the entire main thread 

I don't know what main thread really is in this case, but patch is still playing when i do that, if it is unusual behavior i can film it

**Comment by AndrewBelt** [comment]
@VSpellbound The patch DSP runs on the *engine* thread, and each Audio Interface module launches its own *audio* thread, so the main thread does not effect these.

**Comment by AndrewBelt** [comment]
Rejecting feature request since it serves no purpose.
