### ISSUE TITLE
Logic question about the Mutes module

### ISSUE THREAD

**Issue by nay-seven** [VCVRack/Rack#440]
Hello,
just a question about this module
Generally the green color mean Ok or On , here for this module to have the Mute ON, the switch must be Off ( black)  ?
for example on the module SEQ-3, the RUN switch is green when ON and black when Off ? idem for Scope mode selction
What do you think ?

**Comment by AndrewBelt** [comment]
Don't think of the button's function as "mute". Think of it as "passthrough". If passthrough is disabled, it mutes it. If enabled, the light is lit.

**Comment by nay-seven** [comment]
Of course , i can understand that, but the module is named a mute module...  ;-) 
on most of DAW's, the M is light when Mute is ON, so can be confused.

ok, forget it,  not really important...was just a thought ;-)

**Comment by AndrewBelt** [comment]
If I negated the name of the module, it'd have really boring names like "Passthrough" or "Buffer".

**Comment by Strum** [comment]
I called the module i built that does the same thing gates.

Mute would seem to imply it is used on audio signals where as gate would imply turning a signal on or off

my 2 cents worth.

**Comment by AndrewBelt** [comment]
https://en.wiktionary.org/wiki/bikeshedding
