### ISSUE TITLE
feature request: quad midi priority channels

### ISSUE THREAD

**Issue by robertocolabene** [VCVRack/Rack#443]
hi, a sort of priority to the lowest channel on the quad midi module would be useful and i think also a logic behavior.

i mean: if i'm playing the first note a want the second one always on the second channel
if i left the first note i want the next on the first channel also if i'm still playing the second one

what do u think?
should the reset mode work this way?

**Comment by AndrewBelt** [comment]
The quad MIDI interface was removed and replaced with MIDI-CV (with polyphonic support) in Rack v1. MIDI-CV includes several voice mapping modes, and I think the one you're describing is "Reset".
