### ISSUE TITLE
Case Insensitive Manufacturers Sort in Add Module Dialog

### ISSUE THREAD

**Issue by djpeterso23662** [VCVRack/Rack#446]
OS (if applicable): all
Version (or "dev" if compiling from source): 0.5.0

The order of Manufacturers in the Add Module dialog is A-Z, a-z.  Non-Linux users might expect the sort to be case insensitive.  Could the Manufacturers sort be case-insensitive in the next release?  Thanks for reading!

**Comment by sbcook0** [comment]
That would be useful

**Comment by AndrewBelt** [comment]
Merging with #861

**Comment by almostEric** [comment]
sorry about duplicate issue - I searched for Case Sensitive before creating, didn't return Case Insensitivity :)
