### ISSUE TITLE
Menus and mouse clicks

### ISSUE THREAD

**Issue by sebastien-bouffier** [VCVRack/Rack#448]
OS (if applicable): W10
Version (or "dev" if compiling from source): "dev"

When I right click on empty rack it opens the add module menu -> fine
When I right click on a module it opens the menu of the module -> fine again
But when I click on the wrong target I need to left click out of the menu to close the menu before right clicking on the good one..
The left click should be avoided, no ?

I tested that code that seems to work fine in MenuOverlay.cpp

```cpp
void MenuOverlay::onMouseDown(EventMouseDown &e) {
	if (!getChildrenBoundingBox().contains(e.pos)) {
		 gScene->setOverlay(NULL);
	}
	else
		OpaqueWidget::onMouseDown(e);
}

with the declaration of overriding in Widgets.hpp

struct MenuOverlay : OpaqueWidget {
	void step() override;
	void onDragDrop(EventDragDrop &e) override;
	void onHoverKey(EventHoverKey &e) override;
	void onMouseDown(EventMouseDown &e) override;
};
```

I didn't read all the source so I hope it is not a big hack
Best,

**Comment by AndrewBelt** [comment]
I am interpreting this as "right click should close menus", so I've fixed this in c336e67. Look at the diff if you're curious of the "right way" to do this. You were close.

**Comment by sebastien-bouffier** [comment]
Thanks for your quick reply Andrew and yes I am curious to learn and to be more efficient on your project.
In terms of usability (not the code) I think that my solution was better. If I right click on the wrong item I expect that the next click will close the bad menu and open the good one. With c336e67 we still need 2 clicks.

**Comment by AndrewBelt** [comment]
I believe it had a bug where right clicking and clicking-and-dragging on a module would teleport it somewhere unpredictable.

**Comment by sebastien-bouffier** [comment]
I will test but I believe you :) Maybe I will come back with another proposal in terms of code. Don't want to bother you but "I am an anti click I am an ....".
Best

**Comment by AndrewBelt** [comment]
Don't worry about it. The issue is closed, and we're done here. Time to spend time on other more important things.
