### ISSUE TITLE
LFO?

### ISSUE THREAD

**Issue by Skeyelab** [VCVRack/Rack#45]
Is an LFO module planned?

**Comment by oblivionratula** [comment]
I can't speak to what's planned (would be cool to have one in the Fundamentals for sure, especially once stuff goes for-pay), but for now, I'm using the Tidal Modulator from the AudibleInstruments pack. HTH.

**Comment by teotigraphix** [comment]
You could use a simple VCO for LFO as well. Use the waveform outs.

**Comment by oblivionratula** [comment]
Well, yeah, that too. A negative CV may (or may not, I can't test right now) get you even slower than the bottom of the dial if needed.

**Comment by CFelipe** [comment]
@teotigraphix I've found these to be not slow enough even at the slowest available frequency. Maybe I'm doing it wrong?

**Comment by jackokring** [comment]
Not sure if virtual CV saturates.

**Comment by teotigraphix** [comment]
If you look at the code it seems to be slewing the pitch. (If that is what you are talking about)

**Comment by teotigraphix** [comment]
In the https://github.com/VCVRack/AudibleInstruments repo Andrew has it stated that he is going to implement this;

This module has massive LFO functionality.

https://mutable-instruments.net/modules/peaks/

**Comment by simonvanderveldt** [comment]
@teotigraphix A simple LFO as part of Fundamentals would imho still be useful, especially for people who are (relatively) new to modular synths.

**Comment by teotigraphix** [comment]
@simonvanderveldt Agreed for sure. :) I guess that is what this thread is about. I am actually just discovering this stuff, so I posted what I am reading.

**Comment by Skeyelab** [comment]
@teotigraphix - the Fundamental VCO's lowest speed isnt very low.

**Comment by AndrewBelt** [comment]
I've requested Grayscale to design an LFO to Fundamental. Meanwhile, Audible Instruments Tidal Modulator is what you should use! It's a great LFO / function generator.

**Comment by antoniograzioli** [comment]
I have develooed an LFO. Look in blog section on www.autodafe.net

Still beta I have a new release coming as soon as Rack 0.32 is released...

**Comment by AndrewBelt** [comment]
Closing because this is an issue with Fundamental, not Rack. Regardless, two LFOs will be added to Fundamental for the v0.4.0 release.
