### ISSUE TITLE
MIDI Trigger to CV: Receives MIDI notes but gate goes high and stays high

### ISSUE THREAD

**Issue by chrisbeckstrom** [VCVRack/Rack#450]
OS (if applicable): Mac OS Sierra 10.12.6
Version (or "dev" if compiling from source): 0.5.0

Steps to recreate:
- create "MIDI Trigger to CV" module
- set to listen to IAC Driver
- send MIDI note such as note 0 from elsewhere (Bitwig, etc.)
- connect the output of "0" on the "MIDI trigger to cv" module and connect to scope

Expected behavior:
- when the MIDI note 0 is "on" (after "note on" message and before "note off") the output of "0" in the "MIDI trigger to cv" module should be high (+10V?), but it should go to 0V when the note is released (i.e. "note off" message)

Actual behavior:
- As soon as one MIDI note 0 "note on" message is sent to Rack, the output of "0" stays high (10V?)

Am I missing something here?

I also have the dev version of rack on my linux machine, I'll try there too.

**Comment by chrisbeckstrom** [comment]
Ah! maybe this pull request is related: https://github.com/VCVRack/Rack/pull/434/commits

**Comment by bontric** [comment]
Yes, the pull request #434 should fix this ;)

**Comment by chrisbeckstrom** [comment]
thanks @bontric ! mostly just to learn, I got the dev version on mac, changed that one file (per https://github.com/VCVRack/Rack/pull/434/files ) and compiled myself... Works great!
