### ISSUE TITLE
Simple Idea for adding multiple modules at once

### ISSUE THREAD

**Issue by jeremywen** [VCVRack/Rack#451]
Would be nice if you could right click to open the module popup, and then *Option/Alt+Click* a module in the popup menu to make it add the module and keep the popup open.  For example, then you could add a VCA and and ADSR with less clicks.

**Comment by sebastien-bouffier** [comment]
+1 good idea

**Comment by pixelrust** [comment]
_Alt+Click_ is usually taken on Linux.
Maybe _Ctrl+Click_, since it's a "multiple selection" (of modules to be added)?

**Comment by AndrewBelt** [comment]
This issue was created around Rack v0.3 when the Module Browser lost its state when closed. In Rack v1, the Module Browser keeps its selection state, so it's easy to add modules, reopen the Module Browser, and repeat.
