### ISSUE TITLE
Addition of Keystrokes

### ISSUE THREAD

**Issue by nstottlemyer** [VCVRack/Rack#453]
OS (if applicable): macOS 10.12
Version (or "dev" if compiling from source):

To increase workflow, utilization of system keystrokes would be helpful.

**Comment by AndrewBelt** [comment]
Closing, not a concrete feature request

**Comment by nstottlemyer** [comment]
Thanks, Andrew. Specifically, I'm asking for ctrl/cmd+z and shift+ctrl/cmd+z for undo and redo, respectively, allowing the user undo/redo last actions.

**Comment by AndrewBelt** [comment]
Then, duplicate of #153

**Comment by nstottlemyer** [comment]
Yes, thanks. Sorry for the repeat.
