### ISSUE TITLE
"Do you want to go to the VCV plugin manager website to download missing plugins?" message

### ISSUE THREAD

**Issue by Miserlou** [VCVRack/Rack#454]
[Tag for discussion?]

The scenario is this: a new user wants to play with a rack from a community website like [patchstorage.com](https://patchstorage.com/synthikat-drumbass-drums/). Upon opening that patch, the user receives a message like this:

<img width="532" alt="screen shot 2017-11-25 at 12 11 54 pm" src="https://user-images.githubusercontent.com/139987/33232809-9936ab6c-d1da-11e7-83f9-6a078ff7a7fa.png">

I don't have those modules on my system, so I can't play with the patch. Makes sense.

So, the optimal solution here is for Rack to be able to contact the server and automatically download install the packages I need to play with this Rack. Great!

Unfortunately, there's another problem. From what I can tell, .vcv files do not have any information about which versions of the modules are required. So, if the rack was build for `PluginXYZ 0.2.0`, but the current "head" in the store is `0.3.0`, then the rack might not work as intended, if at all. Not good for the publisher or the user.

But, if the `.vcv` spec contained this information, then when Rack fetches and installs the plugins from the store or other repo, it can install the correct version for the custom rack, and everything just works out of the box as intended. Everybody is happy!

Please consider this! Music software has always been plagued with issues around plugin compatibility that have been solved in other programming domains through good package management design, which led the creation of services like Splice. Now that we have an awesome open source modular softsynth, it'd be awesome if we could have awesome package/dependency resolution to go along with it as well to avoid constant fighting with manual plugin version maintenance.

**Comment by heavydetail** [comment]
I was asking yesterday about some form of package management on facebook. Super glad to see this happening and I just wanted to say that if dependancy resolution and automatic download could be done, we could truly try every patch out there in such a simple way that the Rack ecosystem would be unstoppable! The possibilities are huge!
It could be the only synth you'll ever need. Would love to see this happening, its like a revolution for audio production tools, it would open up the truly explorative world of modular synthesis and get rid of all the BS VSTs! Im stoked, hope I can help out along the way

**Comment by milholen** [comment]
This is probably handled (and superseded) by #444 – @Miserlou you can close this issue if you agree.

**Comment by AndrewBelt** [comment]
I'll leave this open and add a "Do you want to go to the VCV plugin manager website to download missing plugins?" question to the dialog box.

**Comment by Miserlou** [comment]
Are you saying that it won't have the ability to resolve dependencies automatically, and will require the user to use the website? Why not just have 'Do you want Rack to install the missing plugins now'?

This ticket should also be used to track the change to `vcv` files themselves to include the necessary information to make that happen.

**Comment by AndrewBelt** [comment]
>This ticket should also be used to track the change to vcv files themselves to include the necessary information to make that happen.

There should be no backward in-compatible changes to .vcv files, and if there were, this would not be the appropriate thread to discuss them.

**Comment by Miserlou** [comment]
>  In other words, while it would be trivial to add this as a feature since the server API endpoint already exists, forcing users to click "Add" on the website for each plugin they wish to have allows them to appreciate the plugins, learn about their author, learn where to find the manuals, and remember their names.

I think that seems a bit bizarre. I get that you want to drive traffic to the website, but for a larger rack, this is going to be extremely inconvenient. Could you at least bring it up to a page that has all of the required modules pre-selected?

The `vcv` file format also doesn't contain the necessary information about module versions to properly resolve dependencies. That's why I made this ticket.

**Comment by AndrewBelt** [comment]
No. I've explained my reasons.

I'm also not adding plugin versions to the .vcv format. Everyone should always use the latest version of plugins they use, not the ones 3 weeks ago. What if they want to use a plugin version from 6 months ago? They can't, because it won't be compatible with their version of Rack anyway. So we're talking about a wiggle room of 1 month worth of versions per plugin, not enough for plugins to have frequent differences. Not enough to be worth for the system to juggle multiple versions of plugins. What if you open a patch with old Audible Instruments modules and want to add another module from Audible Instruments of 2 versions ago? A total UI nightmare.

If that's what the point of this ticket is, I'm closing it and reopening one for the "Do you want to go to the VCV plugin manager website to download missing plugins?" message.

**Comment by Miserlou** [comment]
The problem with that is that means that any kind of rack-repository like patchstorage.com will never be any use - racks hosted there would all become immediately useless within a period of weeks if any of the underlying modules change their interfaces.

Literally every package manager in history has this ability. When I run a python utility, it is able to use the proper versions of each dependency for that program, so I know it will always work. If it installed whatever was the latest version for each underlying module, then it would break if any single dependency has an API change. 

If the rack contains all of the version information, the repo contains all of the builds, and the API can provide all of the locations.. why not do it?

It's a trivial difference to the file format, and it means the difference between "I can now re-open my racks from two years ago" and "it is literally impossible for me to ever open this rack again because I don't have the information about the module versions it was built for."

**Comment by AndrewBelt** [comment]
>any kind of rack-repository like patchstorage.com will never be any use

That is assuming developers make frequent breaking changes to modules. In practice, this doesn't happen much because the modules are quick to write and stablize very quickly. A module simply doesn't change that often.

Why don't VST plugins have this problem? Because VST developers don't change their parameters after first release. VCV developers do the same. There might be sound quality improvements, but once released, developers move on to another module.

Before continuing, answer this question: how do I load a plugin compiled for Rack v0.3.2 into Rack v2.0? Your entire premise is that this is possible.

**Comment by Miserlou** [comment]
Developers should be allowed to update their modules, and users should be able to use their favorite racks without worrying about a developer breaking it for them. It seems like an un-optimal design choice to remove critical functionality because the problem it enables "doesn't happen very much". Especially when the fix is really trivial. 

It doesn't require 0.3.2 modules work on 2.0.0 - that would be impossible. It just means that I have a favorite Rack that I made a year ago, that I should have all of of the necessary information to be able to re-create that exact combination of Rack and the underlying modules. Otherwise, we're just throwing information away so that people can't open old files, either from 3rd party websites or from their own archives. 

I make a rack. I use whatever is currently on my system. I love it, I save it. I keep jamming, install new modules, update old models, make new racks. Six months later, I want to re-open that first rack I made and loved. But I've updated one of the modules since, I'll need to downgrade to reopen that rack again. But which version was I using before, I can't remember, and I can never find out because we threw that information away for.. some reason.

**Comment by AndrewBelt** [comment]
So you're just proposing that the version of a plugin is stored in the .vcv file, and that's it? Just for human reference? I can add that, but that's all I'll add and it'll be write-only. I'm closing any future "avalance" issues regarding doing anything with that information.

**Comment by Miserlou** [comment]
Yep, that's all I'm asking for here. Whatever you want to do with the website or whatever is up to you. I'd suggest that you use this information for resolution, but if you don't want to that's fine, at least if the information is available it will be _possible_ for people to do it themselves.

**Comment by AndrewBelt** [comment]
Fixed in 892d476. Note that the release cycle of Rack for at least the next year will be about 1 major version per two months. This is faster than Firefox.

**Comment by Miserlou** [comment]
Awesome! Thank you very much Andrew! VCV Rack forever! \m/

**Comment by AndrewBelt** [comment]
Now fix your own plugin's version. :) I don't know what v0.5.0+ means. https://github.com/VCVRack/Rack/wiki/List-of-plugins

**Comment by Miserlou** [comment]
That column is for the version of Rack it works for, not the module's version, right? My modules are currently being built against HEAD in the master source tree, so I guess it should be v0.5.*?

**Comment by AndrewBelt** [comment]
Uh, if those are the official binaries, leave the version blank, since they are "unversioned".

**Comment by heavydetail** [comment]
I would prefer a simple manager dialog in Rack (like eg. in the arduino or processing IDE) from where you can "download&install all" which gives you the option to click through to each of the modules on the website, if there are non-free modules in the patch present an option to buy them in bulk and install via the website.

For versioning I suggest that rack 1.0 pulls modules that are made for 1.0 and a future 1.5 pulls those that work with 1.5, keeping intermittent versions of modules makes it possible to open any patch made in 1.0 in rack 1.0 and patches for 1.5 in rack 1.5 etc.

**Comment by AndrewBelt** [comment]
Trying to implement a browser in C++/nanovg/blendish would suck and the UX will never be as good as a website.

v1.5 and v1.0 are ABI/API compatible, based on the guidelines at #266.

**Comment by AndrewBelt** [comment]
Closing since the current dialog box contains enough information for users to go to the [VCV Library](https://library.vcvrack.com/) and add/purchase the correct modules/plugins to their VCV account.
