### ISSUE TITLE
no pulse audio support in 0.5

### ISSUE THREAD

**Issue by karlyan17** [VCVRack/Rack#457]
OS (if applicable): arch linux
after instalation on version 0.5.0 pulseaudio options in the "core/audio interface" module disappeared and none of the other options produce any sound with error:
`RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (default), Device or resource busy.

ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave

RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (default), Device or resource busy.
`

Edit:
On a setup without pulseaudio (just using alsa) works initially but produces the same error after manually muting/unmuting the channel in alsamixer

**Comment by bontric** [comment]
The Audio library we are using (RtAudio) was not compiled with pulse support for version 0.5 . If you want to use pulse you need to manually compile RtAudio with pulse enabled. To archive this you can follow the instructions here:

https://github.com/VCVRack/Rack/wiki/Add-Support-for-Jack-on-Linux-(dev)

and simply add `-with-pulse` to the `./configure` command.

**Comment by karlyan17** [comment]
Thanks for the quick response,

recompiling Rack and RtAudio with the above flags fixed the problem :)

The other setup had indeed jack installed
