### ISSUE TITLE
Knob with snap=true => randomize => wrong widget position 

### ISSUE THREAD

**Issue by sebastien-bouffier** [VCVRack/Rack#459]
OS (if applicable): W10
Version (or "dev" if compiling from source): dev

I have sliders that inherit from SVGSlider with snap=true to mimic BefacoBigSnapKnob's jumps from units to units.
When randomizing, the handles where not correctly positioned. I did a check with the Befaco osc and the behavior is the same, 
I made a change in Knob.cpp 
```
void Knob::randomize() {
    if (randomizable) {
        if (snap)
            setValue(roundf(rescalef(randomf(), 0.0, 1.0, minValue, maxValue)));
        else
            setValue(rescalef(randomf(), 0.0, 1.0, minValue, maxValue));
    }
}
```
The issue on sliders has been solved but unfortunately the BefacoBigSnapKnob is still reluctant to snap on the value after randomize.

BTW nothing really important regarding Rack's road map,  but just to share.

**Comment by AndrewBelt** [comment]
This issue has been fixed around v0.5 or v0.6.
