### ISSUE TITLE
Rack.app hanging on second start

### ISSUE THREAD

**Issue by tekknovator** [VCVRack/Rack#46]
Started it once, enjoyed playing around with it closing the app to do something else, can't resist and try to open Rack again, no response.

**Comment by oblivionratula** [comment]
I'd try removing/renaming the autosave.json file (where that gets saved on your system) as that seems to get auto-loaded on start. If I/O setup changed, maybe it's hanging on that. I've had to do this when I botched a MIDI setup.

**Comment by AndrewBelt** [comment]
Looks like this is caused by #10

**Comment by tekknovator** [comment]
Yea, might be like #10.
Gonna check out that json file and see if I can edit it in a way to remove the io stuff. I suspect presence of PT aggregate devices or soundflower messing this up.

**Comment by tekknovator** [comment]
I commented the core plugin in the autosave.json and it works. So this is very likely a duplicate of #10
