### ISSUE TITLE
Osx 10.13.1 crash report whilst using Rack v0.5 kernel panic

### ISSUE THREAD

**Issue by mattfourmat** [VCVRack/Rack#462]
This is my crash report from osx 10.13.1 if anyone can help at all.

Anonymous UUID:       54509B11-DE6C-C9AE-0F2C-E63ED5CF29CE

Sun Nov 26 18:55:40 2017

*** Panic Report ***
panic(cpu 2 caller 0xffffff800c2a3835): "Graphics firmware encountered an exception: 0xd, from EIP = 0x3c\n"@/Library/Caches/com.apple.xbs/Sources/GPUDriversIntel/GPUDriversIntel-10.28.29/Common/GLKernel/Intel/skl/sched3/IGGuC.cpp:826
Backtrace (CPU 2), Frame : Return Address
0xffffff81193d3c10 : 0xffffff800bc6b6f6 
0xffffff81193d3c60 : 0xffffff800bd96f54 
0xffffff81193d3ca0 : 0xffffff800bd88c39 
0xffffff81193d3d20 : 0xffffff800bc1d190 
0xffffff81193d3d40 : 0xffffff800bc6b1cc 
0xffffff81193d3e70 : 0xffffff800bc6af4c 
0xffffff81193d3ed0 : 0xffffff800c2a3835 
0xffffff81193d3f30 : 0xffffff800c2a2042 
0xffffff81193d3f70 : 0xffffff800c2a167c 
0xffffff81193d3fa0 : 0xffffff800bc1a4f7 

BSD process name corresponding to current thread: kernel_task

Mac OS version:
17B48

Kernel version:
Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64
Kernel UUID: 4B214D53-883B-3E5F-A115-9FDA17E68BA8
Kernel slide:     0x000000000ba00000
Kernel text base: 0xffffff800bc00000
__HIB  text base: 0xffffff800bb00000
System model name: MacBookPro13,2 (Mac-66E35819EE2D0D05)

System uptime in nanoseconds: 12094270855610
last loaded kext at 246104709488: com.apple.filesystems.msdosfs	1.10 (addr 0xffffff7f8cdd3000, size 69632)
last unloaded kext at 513597012663: com.apple.driver.AppleFileSystemDriver	3.0.1 (addr 0xffffff7f8c9cf000, size 8192)
loaded kexts:
com.paceap.kext.pacesupport.snowleopard	5.7.2
com.Cycling74.driver.Soundflower	2
tc.tctechnologies.driver.AllenAndHeathFW	4.2.1 40723
com.apple.driver.AudioAUUC	1.70
com.apple.driver.AGPM	110.23.24
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.driver.X86PlatformShim	1.0.0
com.apple.driver.AppleGraphicsDevicePolicy	3.16.19
com.apple.AGDCPluginDisplayMetrics	3.16.19
com.apple.filesystems.autofs	3.0
com.apple.driver.AppleUpstreamUserClient	3.6.4
com.apple.driver.AppleHDA	280.12
com.apple.driver.AppleHV	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	6.0.1f1
com.apple.driver.pmtelemetry	1
com.apple.driver.AppleHIDALSService	1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleEmbeddedOSSupportHost	1
com.apple.driver.AppleIntelSKLGraphics	10.2.8
com.apple.driver.AppleOSXWatchdog	1
com.apple.AVEBridge	1.0.0
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleIntelPCHPMC	2.0.1
com.apple.driver.AppleBacklight	170.10.1
com.apple.driver.AppleMCCSControl	1.5.3
com.apple.driver.AppleIntelSKLGraphicsFramebuffer	10.2.8
com.apple.driver.eficheck	1
com.apple.driver.AppleThunderboltIP	3.1.0
com.apple.filesystems.apfs	748.21.6
com.apple.filesystems.hfs.kext	407.1.3
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.driver.AppleTopCaseHIDEventDriver	127
com.apple.driver.AirPort.BrcmNIC	1200.26.1a3
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	183
com.apple.security.TMSafetyNet	8
com.apple.security.quarantine	3
com.apple.IOBufferCopyEngineTest	1
com.apple.driver.AppleGraphicsControl	3.16.19
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	280.12
com.apple.kext.OSvKernDSPLib	526
com.apple.iokit.IOFireWireFamily	4.6.8
com.apple.iokit.IOTimeSyncFamily	600.15
com.apple.driver.AppleSSE	1.0
com.apple.iokit.IOBluetoothHostControllerUARTTransport	6.0.1f1
com.apple.iokit.IOBluetoothHostControllerTransport	6.0.1f1
com.apple.AppleGPUWrangler	3.16.19
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleHDAController	280.12
com.apple.iokit.IOHDAFamily	280.12
com.apple.iokit.IOAudioFamily	206.5
com.apple.vecLib.kext	1.2.0
com.apple.driver.usb.IOUSBHostHIDDevice	1.2
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	517.17
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.driver.AppleIntelLpssUARTv1	3.0.60
com.apple.driver.AppleIntelLpssUARTCommon	3.0.60
com.apple.driver.AppleOnboardSerial	1.0
com.apple.iokit.IOSkywalkFamily	1
com.apple.iokit.IOSerialFamily	11
com.apple.AppleGraphicsDeviceControl	3.16.19
com.apple.iokit.IOAcceleratorFamily2	374.1
com.apple.iokit.IOGraphicsFamily	517.17
com.apple.iokit.IOSurface	209
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.driver.usb.cdc.ncm	5.0.0
com.apple.driver.usb.AppleUSBiBridge	1.0
com.apple.driver.usb.cdc	5.0.0
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.AppleActuatorDriver	1004.1
com.apple.driver.AppleHIDKeyboard	203
com.apple.driver.AppleHSBluetoothDriver	127
com.apple.driver.IOBluetoothHIDDriver	6.0.1f1
com.apple.iokit.IOBluetoothFamily	6.0.1f1
com.apple.driver.AppleMultitouchDriver	1004.1
com.apple.driver.AppleInputDeviceSupport	1000
com.apple.driver.AppleHSSPIHIDDriver	52
com.apple.driver.AppleThunderboltDPInAdapter	5.0.2
com.apple.driver.AppleThunderboltDPAdapterFamily	5.0.2
com.apple.driver.AppleThunderboltPCIDownAdapter	2.1.3
com.apple.driver.AppleHPM	3.1.3
com.apple.driver.AppleIntelLpssI2CController	3.0.60
com.apple.driver.AppleHSSPISupport	52
com.apple.driver.AppleThunderboltNHI	4.5.6
com.apple.iokit.IOThunderboltFamily	6.5.8
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleIntelLpssSpiController	3.0.60
com.apple.driver.AppleIntelLpssDmac	3.0.60
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.driver.AppleIntelLpssI2C	3.0.60
com.apple.driver.AppleIntelLpssGspi	3.0.60
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.iokit.IOBufferCopyEngineFamily	1
com.apple.driver.DiskImages	480.1.2
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	439.20.7
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.IOUSBMassStorageDriver	140
com.apple.iokit.IOSCSIBlockCommandsDevice	404.20.1
com.apple.iokit.IOSCSIArchitectureModelFamily	404.20.1
com.apple.iokit.IOStorageFamily	2.1
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMCRTC	1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0
com.apple.kec.Libm	1

EOF
Model: MacBookPro13,2, BootROM MBP132.0233.B00, 2 processors, Intel Core i7, 3.3 GHz, 8 GB, SMC 2.37f20
Graphics: Intel Iris Graphics 550, Intel Iris Graphics 550, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C3531324D3332443250462D3039
Memory Module: BANK 1/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C3531324D3332443250462D3039
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x157), Broadcom BCM43xx 1.0 (7.77.37.2.1a3)
Bluetooth: Version 6.0.0f1, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: USB2.0 Hub
USB Device: MPK mini
USB Device: Portable
USB Device: iBridge
Thunderbolt Bus: MacBook Pro, Apple Inc., 22.2
Thunderbolt Bus: MacBook Pro, Apple Inc., 22.2

**Comment by mattfourmat** [comment]
For an update and for anyone getting similar problems. I now run rack in low resolution mode and it runs with out problems at all. Applications > Rack (right click > get info) tick low resolution mode.

**Comment by modlfo** [comment]
@mattfourmat Have you tried a more recent version of Rack? Rack works fine in MacBook computers like yours, with a recent OS, processor and graphics. Since many things have been improved since the creation of this issue, I'm closing it for now. Feel free to comment if the issue still happens in a newer version of Rack.

**Comment by mattfourmat** [comment]
Hi I still use Vcv in low resolution mode and have no issues... I will try
it normal mode later tonight see what happens but thanks !!
