### ISSUE TITLE
Compiling 0.5.0 unter Linux doesn't work out of the box

### ISSUE THREAD

**Issue by fhars** [VCVRack/Rack#463]
OS (if applicable): Ubuntu 17.04
Version (or "dev" if compiling from source): v0.5.0

The list of required dependencies is incomplete, I had to install libxcursor-dev, libasound2-dev and libgtk2-dev (and it may be that there are more dependencies I happened to have installed before).

make dep installs RtAudio.h in dep/include, the Rack build process expects it in dep/include/rtaudio

Checking out the tag v0.5.0 and building that state does not give me a version of Rack that is fully compatible with v0.5.0. It complains every time I open a patch created with v0.5.0 and displays a garbled patch. I have to close and restart it, then the autosaved patch works.

**Comment by AndrewBelt** [comment]
>make dep installs RtAudio.h in dep/include, the Rack build process expects it in dep/include/rtaudio

Check out the *branch* v0.5, not the tag v0.5.0.

**Comment by Djack13** [comment]
Version Branch v0.5 compiled on Mint 18.02 (Ubuntu 16.04)
Hello,

I have the same problem:
""It complains every time I open a patch created with v0.5.0 and displays a garbled patch. I have to close and restart it, then the autosaved patch works.""

Some plug-ins "compatible v0.5" does not compile, Autodafe use some widgets not listed in components.hpp !!  

Best wishes and thank you for your wonderful Rack  :)

**Comment by AndrewBelt** [comment]
Noo, emscripted is not what you need. I don't know the package name off the top of my head, but it probably looks like "xlib-dev" or something. Also, it would help if you stated your distro and version.

**Comment by ebunders** [comment]
yeah that's right. I use Ubuntu version 17.10, running Wayland. Is there any way to establish what the dependencies actually are with c++ programs, or is it a 'need to know' type of deal?
I am a java dev myself, and of course we have things like 'maven' that will both tell us what our deps are, and fetch them for us (which is a great joy)

**Comment by mdemanett** [comment]
In case it helps, here is the list of dev packages I had to install just now to build Rack on a clean Ubuntu Studio 17 install:

```
libx11.dev
libgl1-mesa-dev
libxrandr-dev
libxinerama-dev
libxcursor-dev
libzip-dev
libasound-dev
freeglut3-dev
mesa-common-dev
libgtk2.0-dev
```

**Comment by ebunders** [comment]
Nice. I will try it out. If I get it to work, I will update the Rack README.md, and create a pull request.
I would also like to build a version with wine support enabled, for obvious reasons

thanks!

**Comment by AndrewBelt** [comment]
@ebunders Just post the list of required dev packages on here, to make sure they agree with @mdemanett's list. I'm willing to post Ubuntu's list for convenience, but not every distro under the sun. And I don't believe some of them, like freeglut3-dev and libzip-dev.

**Comment by ebunders** [comment]
@AndrewBelt I have just been able to build Rack, as well as the Fundamentals plugins with the list provided by @mdemanett . Maybe it would be a good idea to create a wiki page for build instructions, and point to that in the readme? Then individual platform users can translate the general instructions to something that works for them and document it themself...

**Comment by AndrewBelt** [comment]
Sure, feel free to make a "Building on Linux" or "Building on Ubuntu" wiki page.

**Comment by mdemanett** [comment]
I checked my work and  got the list down to:
```                                                                                                                                                                   
libx11-dev
libxrandr-dev
libxinerama-dev
libxcursor-dev
libgl1-mesa-dev
libglu1-mesa-dev
zlib1g-dev
libasound2-dev
libgtk2.0-dev
```

Without zlib1g-dev, configuration of the libzip in dep fails on:
```                                                                                                                                                              
configure: error: ZLIB version too old, please install at least v1.1.2
```

**Comment by AndrewBelt** [comment]
Okay, that's more believable, except for perhaps glu.

**Comment by ebunders** [comment]
If I have a bit more time, I will try it out and confirm it on a clean install in virtualbox, for now it'll have to do...

**Comment by ebunders** [comment]
I have create this page https://github.com/VCVRack/Rack/wiki/Extended-build-instructions. @AndrewBelt perhaps it's a swell idea to link to this in the README?

**Comment by 573** [comment]
The list @ebunders provided worked for me:

    $ lsb_release -a
    LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:printing-   9.20160110ubuntu0.2-amd64:printing-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
    Distributor ID:	Ubuntu
    Description:	Ubuntu 16.04.3 LTS
    Release:	16.04
    Codename:	xenial

Only when start using make run I get:

   Cannot open window with OpenGL 2.0 renderer. Does your graphics card support OpenGL 2.0 or greater? If so, make sure you have the latest graphics drivers installed.

But this is an issue of missing runtime libs only.

**Comment by Djack13** [comment]
Hello
My graphic card is using NVIDIA 384.90 driver with openGL 4.5.0

The autosave file opens without any problem. Rack and modules graphics are
ok.
The problem arise only when i open a file.vcv, Rack graphic is ok, all
modules graphics are messy
When i close Rack and re-open it, all become ok (because file.vcv becomes
autosave.vcv !)

Very stange








Le 7 janv. 2018 17:24, "Daniel Kahlenberg" <notifications@github.com> a
écrit :

The list @ebunders <https://github.com/ebunders> provided worked for me:

$ lsb_release -a
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:printing-
  9.20160110ubuntu0.2-amd64:printing-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

Only when start using make run I get:

Cannot open window with OpenGL 2.0 renderer. Does your graphics card
support OpenGL 2.0 or greater? If so, make sure you have the latest
graphics drivers installed.

But this is an issue of missing runtime libs only.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/VCVRack/Rack/issues/463#issuecomment-355834108>, or mute
the thread

**Comment by modlfo** [comment]
I'm closing this one since the information provided in the Rack Manual https://vcvrack.com/manual/Building.html describes all the packages necessary and the steps to compile in Linux.
