### ISSUE TITLE
Redundant Pulse Matrix entries added in Add module dialog when refreshing plugins multiple times

### ISSUE THREAD

**Issue by MarcBoule** [VCVRack/Rack#464]
OS (if applicable): Win7
Version (or "dev" if compiling from source): v.0.5.0

When clicking _Refresh plugins_ more than once, a bunch of redundant entries are made in the _Add Module_ dialog.
![image](https://user-images.githubusercontent.com/33604154/33287423-9bb33d9e-d386-11e7-9437-de870623adcf.png)
If I look closely, it also re-downloads the Pulse Matrix plugin everytime the Refresh button is clicked. This was tested in a 5 minute time span.

**Comment by AndrewBelt** [comment]
Fixed in master but not in v0.5
