### ISSUE TITLE
Add RTAUDIO_ALL_APIS env variable to build instructions for dependencies

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#465]
OS: Windows 10
Version: branch v0.5, a17ae2c6cc80882ed3ef7ff926dfa685786b03dc

Compiling on Windows 10 with msys2 per the instructions in the README.

`DirectSound` and `ASIO` support was missing, but the officially released v0.5 supported it.

After some digging I found the `RTAUDIO_ALL_APIS` environment variable in the `dep` Makefile.

The following invocation should be added to the build instructions:
```
RTAUDIO_ALL_APIS=true make dep
```

**Comment by AndrewBelt** [comment]
Fixed with 79ac79f

**Comment by alfonso73** [comment]
Thanks! In wich file should i add the "RTAUDIO_ALL_APIS=true make dep" line?

**Comment by Flowstoner** [comment]
@alfonso73 when you run the command `make dep` you have to add the `RTAUDIO_ALL_APIS=true` define in the command line : `make dep RTAUDIO_ALL_APIS=true`
