### ISSUE TITLE
Allow changing of mouse polling method

### ISSUE THREAD

**Issue by mwpher** [VCVRack/Rack#466]
Hey there. I’m running the latest version, and using it through Splashtop on an iPad for chronic pain reasons. I’m finding that turning knobs results in the knob instantly snapping from one extreme to the other.

I believe this is because Splashtop is constantly resetting the mouse pointer to the position on the client, while Rack itself is measuring knob movement by attempting to set the mouse pointer to the center of the screen and then measuring how far its been moved. But it fails to set it to the center, so instead it looks like huge mouse movement jumps.

I’ve found apps before that had the infinite scrolling/dragging but didn’t reset the mouse pointer like that, so I know its definitely possible.

Sorry to bother you, I’m sure this isn’t important at all to 99% of your users.

**Comment by AndrewBelt** [comment]
You are correct. Change   "allowCursorLock" to true, in settings.json
