### ISSUE TITLE
Feature Request: Cable ties.

### ISSUE THREAD

**Issue by Strum** [VCVRack/Rack#468]
It would be handy to be able to group cables as you would with velcro cable wraps in a real modular so you can keep them organised and out of the way of controls.

**Comment by AndrewBelt** [comment]
It would actually help with those 6-polyphony modules...
But closing since there's no (proposed) realistic implementation of this UI.

**Comment by Strum** [comment]
No worries @AndrewBelt, I'll have a think about how it might work and see what I can come up with.
