### ISSUE TITLE
Multiplex Signal

### ISSUE THREAD

**Issue by gkhasel1** [VCVRack/Rack#469]
OS (if applicable): OSX
Version (or "dev" if compiling from source): v0.5.0

Is it possible to multiplex a signal? 

For example, If I want an LFOs output to go to multiple inputs in some other modules is there some special cable I can use to do that?

Thanks for making this, I'm hoping to contribute in the near future!

**Comment by AndrewBelt** [comment]
Hold Ctrl while clicking the output port, or drag from the input to output.

**Comment by gkhasel1** [comment]
Speedy response! Thank you :)

**Comment by gkhasel1** [comment]
It'll be easy to figure out from here, just wanted to make sure it was possible. Will test it out later.
