### ISSUE TITLE
Rack.exe won't run in Win10

### ISSUE THREAD

**Issue by Plsmakeitwork** [VCVRack/Rack#47]
Hello, I am having an issue using Rack, whenever I run it I get the following message: 
![default](https://user-images.githubusercontent.com/31893598/30331655-1070f108-97e1-11e7-9bf9-424df40ba79c.png)

Could you please help me to fix this?

**Comment by tedpallas** [comment]
Same error, windows 7

**Comment by vukovinski** [comment]
Same error, W10

**Comment by tractuspk** [comment]
Same issue persists in v31 for me, but now it says gWindow.

**Comment by tedpallas** [comment]
Error has gone away for me with v31!

**Comment by AndrewBelt** [comment]
Duplicate of #18
