### ISSUE TITLE
Audio problems ALSA PulseAudio RtAudio

### ISSUE THREAD

**Issue by spktkpkt** [VCVRack/Rack#479]
OS (if applicable): Ubuntu 17.10 Linux
Version (or "dev" if compiling from source): 7c2312f (HEAD, tag: v0.5.0) Use dev build library for rtaudio on Linux

*RTAudio* with pure *ALSA*:
- *VCVRack* shows my usb sound card (*Steinberg UR22*), but i cannot select it and there is no audio at all.
- *VCVRack* show 2 inputs and 2 output, which is correct.

Output from *VCVRack*:

    RtApiAlsa::getDeviceInfo: pcm device (hw:1,0) data format not supported by RtAudio.
    RtApiAlsa::getDeviceInfo: pcm device (hw:1,0) data format not supported by RtAudio.
    [debug] Opening audio stream 0
    RtApiAlsa::getDeviceInfo: pcm device (hw:1,0) data format not supported by RtAudio.
    [warning] Failed to open audio stream: RtApiAlsa::probeDeviceOpen: pcm device 0 data format not supported by RtAudio.
    RtApiAlsa::getDeviceInfo: pcm device (hw:1,0) data format not supported by RtAudio.

Output from *rtaudio_test*:

    [debug] deviceCount: 1
    RtApiAlsa::getDeviceInfo: pcm device (hw:1,0) data format not supported by RtAudio.
    [debug] Stream 0: probed: 0, name:  outputs: 2, inputs: 2, duplex: 2
    RtApiAlsa::getDeviceInfo: pcm device (hw:1,0) data format not supported by RtAudio.
    [debug] RtApiAlsa::probeDeviceOpen: pcm device 0 data format not supported by RtAudio.
    terminate called after throwing an instance of 'RtAudioError'
      what():  RtApi:: a stream is not open!
    Aborted (core dumped)
    Makefile:15: recipe for target 'run' failed
    make: *** [run] Error 134

*RTAudio* with *PulseAudio* and *ALSA*:

- *VCVRack* shows my usb sound card (*Steinberg UR22*) with 32 inputs and 32 outputs, which is not correct.
- Audio playback is poor/unusable.
- Audio recording is poor/unusable.
- Changing sample rate and/or block size doesn't fix or improve the quality.

Output from *VCVRack*:

	...
	[debug] Opening audio stream 1
	RtApiAlsa::getDeviceInfo: pcm device (hw:1,0) data format not supported by RtAudio.
	RtApiAlsa::probeDeviceOpen: unable to synchronize input and output devices.
	[debug] Starting audio stream 1
	...
	RtApiAlsa::callbackEvent: audio write error, underrun.
	RtApiAlsa::callbackEvent: audio write error, underrun.
	RtApiAlsa::callbackEvent: audio write error, underrun.
	...
	RtApiAlsa::callbackEvent: audio write error, underrun.
	RtApiAlsa::callbackEvent: audio write error, underrun.
	RtApiAlsa::callbackEvent: audio write error, underrun.
	...
	RtApiAlsa::callbackEvent: audio write error, underrun.
	...
	[debug] Aborting audio stream 1
	RtApiAlsa::callbackEvent: audio write error, underrun.
	[debug] Closing audio stream 1

`aplay -l`:

    **** List of PLAYBACK Hardware Devices ****
    card 1: UR22 [Steinberg UR22], device 0: USB Audio [USB Audio]
      Subdevices: 1/1
      Subdevice #0: subdevice #0

`lsusb -v` for the *UR22*:

    Bus 003 Device 006: ID 0499:1509 Yamaha Corp. 
    Device Descriptor:
      bLength                18
      bDescriptorType         1
      bcdUSB               2.00
      bDeviceClass          255 Vendor Specific Class
      bDeviceSubClass         0 
      bDeviceProtocol       255 
      bMaxPacketSize0        64
      idVendor           0x0499 Yamaha Corp.
      idProduct          0x1509 
      bcdDevice            1.00
      iManufacturer           1 Yamaha Corporation
      iProduct                2 Steinberg UR22
      iSerial                 0 
      bNumConfigurations      1
      Configuration Descriptor:
        bLength                 9
        bDescriptorType         2
        wTotalLength          442
        bNumInterfaces          5
        bConfigurationValue     1
        iConfiguration          0 
        bmAttributes         0xc0
          Self Powered
        MaxPower              500mA
        Interface Descriptor:
          bLength                 9
          bDescriptorType         4
          bInterfaceNumber        0
          bAlternateSetting       0
          bNumEndpoints           0
          bInterfaceClass       255 Vendor Specific Class
          bInterfaceSubClass      1 
          bInterfaceProtocol      0 
          iInterface              0 
          ** UNRECOGNIZED:  0a 24 01 00 01 34 00 02 01 02
          ** UNRECOGNIZED:  0c 24 02 01 01 01 00 02 03 00 00 00
          ** UNRECOGNIZED:  09 24 03 02 01 03 00 01 00
          ** UNRECOGNIZED:  0c 24 02 03 03 06 00 02 03 00 00 00
          ** UNRECOGNIZED:  09 24 03 04 01 01 00 03 00
        Interface Descriptor:
          bLength                 9
          bDescriptorType         4
          bInterfaceNumber        1
          bAlternateSetting       0
          bNumEndpoints           0
          bInterfaceClass       255 Vendor Specific Class
          bInterfaceSubClass      2 
          bInterfaceProtocol      0 
          iInterface              0 
        Interface Descriptor:
          bLength                 9
          bDescriptorType         4
          bInterfaceNumber        1
          bAlternateSetting       1
          bNumEndpoints           1
          bInterfaceClass       255 Vendor Specific Class
          bInterfaceSubClass      2 
          bInterfaceProtocol      0 
          iInterface              0 
          ** UNRECOGNIZED:  07 24 01 01 01 01 00
          ** UNRECOGNIZED:  0e 24 02 01 02 03 18 02 44 ac 00 80 bb 00
          Endpoint Descriptor:
            bLength                 7
            bDescriptorType         5
            bEndpointAddress     0x07  EP 7 OUT
            bmAttributes            5
              Transfer Type            Isochronous
              Synch Type               Asynchronous
              Usage Type               Data
            wMaxPacketSize     0x002a  1x 42 bytes
            bInterval               1
        Interface Descriptor:
          bLength                 9
          bDescriptorType         4
          bInterfaceNumber        1
          bAlternateSetting       2
          bNumEndpoints           1
          bInterfaceClass       255 Vendor Specific Class
          bInterfaceSubClass      2 
          bInterfaceProtocol      0 
          iInterface              0 
          ** UNRECOGNIZED:  07 24 01 01 01 01 00
          ** UNRECOGNIZED:  0e 24 02 01 02 03 18 02 88 58 01 00 77 01
          Endpoint Descriptor:
            bLength                 7
            bDescriptorType         5
            bEndpointAddress     0x07  EP 7 OUT
            bmAttributes            5
              Transfer Type            Isochronous
              Synch Type               Asynchronous
              Usage Type               Data
            wMaxPacketSize     0x004e  1x 78 bytes
            bInterval               1
        Interface Descriptor:
          bLength                 9
          bDescriptorType         4
          bInterfaceNumber        1
          bAlternateSetting       3
          bNumEndpoints           1
          bInterfaceClass       255 Vendor Specific Class
          bInterfaceSubClass      2 
          bInterfaceProtocol      0 
          iInterface              0 
          ** UNRECOGNIZED:  07 24 01 01 01 01 00
          ** UNRECOGNIZED:  0e 24 02 01 02 03 18 02 10 b1 02 00 ee 02
          Endpoint Descriptor:
            bLength                 7
            bDescriptorType         5
            bEndpointAddress     0x07  EP 7 OUT
            bmAttributes            5
              Transfer Type            Isochronous
              Synch Type               Asynchronous
              Usage Type               Data
            wMaxPacketSize     0x0096  1x 150 bytes
            bInterval               1
        Interface Descriptor:
          bLength                 9
          bDescriptorType         4
          bInterfaceNumber        2
          bAlternateSetting       0
          bNumEndpoints           0
          bInterfaceClass       255 Vendor Specific Class
          bInterfaceSubClass      2 
          bInterfaceProtocol      0 
          iInterface              0 
        Interface Descriptor:
          bLength                 9
          bDescriptorType         4
          bInterfaceNumber        2
          bAlternateSetting       1
          bNumEndpoints           1
          bInterfaceClass       255 Vendor Specific Class
          bInterfaceSubClass      2 
          bInterfaceProtocol      0 
          iInterface              0 
          ** UNRECOGNIZED:  07 24 01 04 01 01 00
          ** UNRECOGNIZED:  0e 24 02 01 02 03 18 02 44 ac 00 80 bb 00
          Endpoint Descriptor:
            bLength                 7
            bDescriptorType         5
            bEndpointAddress     0x86  EP 6 IN
            bmAttributes            5
              Transfer Type            Isochronous
              Synch Type               Asynchronous
              Usage Type               Data
            wMaxPacketSize     0x002a  1x 42 bytes
            bInterval               1
        Interface Descriptor:
          bLength                 9
          bDescriptorType         4
          bInterfaceNumber        2
          bAlternateSetting       2
          bNumEndpoints           1
          bInterfaceClass       255 Vendor Specific Class
          bInterfaceSubClass      2 
          bInterfaceProtocol      0 
          iInterface              0 
          ** UNRECOGNIZED:  07 24 01 04 01 01 00
          ** UNRECOGNIZED:  0e 24 02 01 02 03 18 02 88 58 01 00 77 01
          Endpoint Descriptor:
            bLength                 7
            bDescriptorType         5
            bEndpointAddress     0x86  EP 6 IN
            bmAttributes            5
              Transfer Type            Isochronous
              Synch Type               Asynchronous
              Usage Type               Data
            wMaxPacketSize     0x004e  1x 78 bytes
            bInterval               1
        Interface Descriptor:
          bLength                 9
          bDescriptorType         4
          bInterfaceNumber        2
          bAlternateSetting       3
          bNumEndpoints           1
          bInterfaceClass       255 Vendor Specific Class
          bInterfaceSubClass      2 
          bInterfaceProtocol      0 
          iInterface              0 
          ** UNRECOGNIZED:  07 24 01 04 01 01 00
          ** UNRECOGNIZED:  0e 24 02 01 02 03 18 02 10 b1 02 00 ee 02
          Endpoint Descriptor:
            bLength                 7
            bDescriptorType         5
            bEndpointAddress     0x86  EP 6 IN
            bmAttributes            5
              Transfer Type            Isochronous
              Synch Type               Asynchronous
              Usage Type               Data
            wMaxPacketSize     0x0096  1x 150 bytes
            bInterval               1
        Interface Descriptor:
          bLength                 9
          bDescriptorType         4
          bInterfaceNumber        3
          bAlternateSetting       0
          bNumEndpoints           2
          bInterfaceClass       255 Vendor Specific Class
          bInterfaceSubClass      3 
          bInterfaceProtocol    255 
          iInterface              0 
          ** UNRECOGNIZED:  07 24 01 00 01 24 00
          ** UNRECOGNIZED:  06 24 02 02 01 00
          ** UNRECOGNIZED:  09 24 03 02 01 01 01 01 00
          Endpoint Descriptor:
            bLength                 7
            bDescriptorType         5
            bEndpointAddress     0x01  EP 1 OUT
            bmAttributes            2
              Transfer Type            Bulk
              Synch Type               None
              Usage Type               Data
            wMaxPacketSize     0x0200  1x 512 bytes
            bInterval               0
          Endpoint Descriptor:
            bLength                 7
            bDescriptorType         5
            bEndpointAddress     0x82  EP 2 IN
            bmAttributes            2
              Transfer Type            Bulk
              Synch Type               None
              Usage Type               Data
            wMaxPacketSize     0x0200  1x 512 bytes
            bInterval               0
        Interface Descriptor:
          bLength                 9
          bDescriptorType         4
          bInterfaceNumber        4
          bAlternateSetting       0
          bNumEndpoints           2
          bInterfaceClass       255 Vendor Specific Class
          bInterfaceSubClass    255 Vendor Specific Subclass
          bInterfaceProtocol    255 Vendor Specific Protocol
          iInterface              0 
          ** UNRECOGNIZED:  07 24 01 00 01 24 00
          ** UNRECOGNIZED:  06 24 02 02 01 00
          ** UNRECOGNIZED:  09 24 03 02 01 01 01 01 00
          Endpoint Descriptor:
            bLength                 7
            bDescriptorType         5
            bEndpointAddress     0x03  EP 3 OUT
            bmAttributes            2
              Transfer Type            Bulk
              Synch Type               None
              Usage Type               Data
            wMaxPacketSize     0x0200  1x 512 bytes
            bInterval               0
          Endpoint Descriptor:
            bLength                 7
            bDescriptorType         5
            bEndpointAddress     0x84  EP 4 IN
            bmAttributes            2
              Transfer Type            Bulk
              Synch Type               None
              Usage Type               Data
            wMaxPacketSize     0x0200  1x 512 bytes
            bInterval               0
    Device Qualifier (for other device speed):
      bLength                10
      bDescriptorType         6
      bcdUSB               2.00
      bDeviceClass            0 (Defined at Interface level)
      bDeviceSubClass         0 
      bDeviceProtocol         0 
      bMaxPacketSize0        64
      bNumConfigurations      1
    Device Status:     0x0000
      (Bus Powered)

I guess it's not *VCVRack's* fault, but maybe someone has a hint to solve the problem.

**Comment by bontric** [comment]
From what I can see here:

```
RtApiAlsa::getDeviceInfo: pcm device (hw:1,0) data format not supported by RtAudio.
RtApiAlsa::getDeviceInfo: pcm device (hw:1,0) data format not supported by RtAudio.
[debug] Opening audio stream 0
RtApiAlsa::getDeviceInfo: pcm device (hw:1,0) data format not supported by RtAudio.
[warning] Failed to open audio stream: RtApiAlsa::probeDeviceOpen: pcm device 0 data format not supported by RtAudio.
RtApiAlsa::getDeviceInfo: pcm device (hw:1,0) data format not supported by RtAudio.
```

It looks like either the audio library (RtAudio) or alsa is causing the problem. I don't have your device so It'd be a lot of workto look into this, but if you or someone else can I can point you towards:


https://github.com/thestk/rtaudio/blob/master/RtAudio.cpp#L7310

and

https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m.html#gaa14b7f26877a812acbb39811364177f8

(We'd need to figure out which sample format is used by the UR22 and check why RtAudio isn't supporting the format. If it's just lacking the implementation we could create a PR and fix this ourselves)

Regarding the problems with pulseaudio: I would not recommend using pulse with Rack. I know that's not exactly helpful but you should rather consider installing and running [Jack audio](https://help.ubuntu.com/community/What%20is%20JACK). Using jack might also magically fix your other problems since it provides better and more production oriented support for audio devices.

**Comment by MarcBoule** [comment]
I'm also having UR22 problems in Linux with ALSA, and since I noticed some (albeit minor) similarities between my case and the issue over here, I thought I would add a reference to an issue I raised in the RtAudio github, just in case it might be relevant: 
https://github.com/thestk/rtaudio/issues/118

@bontric : agreed with the Jack suggestion, that will be my next step, but still a bit unsettling to see some fundamental audio drivers (i.e. RtAudio) not woking well with the UR22.

@spktkpkt : perhaps trying the test programs that come with rtaudio might help you in your troubleshooting. If you want to collaborate for some testing and comparing, feel free to respond below, but after extensive testing on my end, I'm pretty much stuck. I'm also seeing a device with 32in/32out by the way, but it doesn't look like it's my UR22.

**Comment by spktkpkt** [comment]
@bontric and @MarcBoule, thanks for getting in touch.

@bontric 

> It looks like either the audio library (RtAudio) or alsa is causing the problem. I don't have your device so It'd be a lot of workto look into this, but if you or someone else can I can point you towards:
>
>https://github.com/thestk/rtaudio/blob/master/RtAudio.cpp#L7310
>

I'm not sure if i can help here, but the pcm sample format should be Unsigned 24bit Little Endian in 3bytes format:

    $ arecord -f S16_LE -c 2 -r 192000 -D hw:1,0 -d 5 test.wav
    Recording WAVE 'test.wav' : Signed 16 bit Little Endian, Rate 192000 Hz, Stereo
    arecord: set_params:1299: Sample format non available
    Available formats:
    - S24_3LE

Works:

    $ arecord -f S24_3LE -c 2 -r 192000 -D hw:1,0 -d 5 test.wav
    Recording WAVE 'test.wav' : Signed 24 bit Little Endian in 3bytes, Rate 192000 Hz, Stereo

I've done some further investigations. I found [this Steinberg forum thread](https://www.steinberg.net/forums/viewtopic.php?t=62290) and checked the Kernel source for the quirks patch. The patch is already integrated in the Kernel, which explains why audio works with Jack, PulseAudio and other applications.

After installing Jack, the sound card works with other applications like SunVox (which uses libSDL2), i am able to playback or/and record without any issues. VCVRack on the other hand doesn't work. VCVRack shows only "*No device*" or "*(0 in, 0 out)*" in the Audio device selection and `RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy.` in the terminal.

If i install PulseAudio and set the configuration profile with pavucontrol to "*Analog Stereo Output*" instead of "*Analog Stereo Duplex*", playback in VCVRack seems to works flawless with the "*(32 in, 32 out)*" device, but recording isn't possible. I do still get some errors:

    RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy.
    RtApiAlsa::getDeviceInfo: pcm device (hw:1,0) data format not supported by RtAudio.
    RtApiAlsa::probeDeviceOpen: unable to synchronize input and output devices.
    RtApiAlsa::callbackEvent: audio write error, underrun.

i've started VCVRack while running PulseAudio and Jack at the same time (just to see what happens), VCVRack shows both interfaces "*(0 in, 0 out)*" and "*(32 in, 32 out)*", but either of those work. Errors are as expected:

    RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy.
    RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy.
    RtApiAlsa::probeDeviceOpen: unable to synchronize input and output devices.
    RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy.
    RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy.

**Comment by bontric** [comment]
```
RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy.
RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy.
RtApiAlsa::probeDeviceOpen: unable to synchronize input and output devices.
RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy.
RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy.
```

Seeing this I'd suggest that you need to select `Jack` at the audio interface `Audio Driver` selection. You are trying to open a device with `Alsa` but it is used by another audio driver (e.g. Pulse or Jack).

As far as I know, using Pulse and Jack simultaneously requires a specific setup, so you should deactivate Pulse before starting Jack. (I think there is something like`pasuspend` to temporarily disable Pulse)

**Comment by spktkpkt** [comment]
@bontric I don't see the option to select Jack as driver, either in qjackctl or in VCVRack. qjackctl offers me a lot (alsa, oss, pulse...) except Jack, VCVRack only offers me "*alsa*".

**Comment by bontric** [comment]
1) qjackctl allows you to control `jack' and using jack as a driver for itself doesn't work. (I'd suggest to use alsa as the driver for jack, which means that jack will interface with alsa)

2) You probably need to recompile RtAudio with jack support (see [here](https://github.com/VCVRack/Rack/wiki/Add-Support-for-Jack-on-Linux-(dev)))

Hope this helps!

**Comment by MarcBoule** [comment]
Quick question regarding point 2 above, if I can jump in: I followed the procedure as stated to build Rack and rtaudio with Jack support, and when I choose Jack as a driver in Rack, the list right under it (devices if memory serves), is empty. I start Jack before running Rack, so that Rack can instantiate the correct "plug" to link up with Jack, but no choices show up in Rack's list of devices. Any ideas what I could be doing wrong?
Sidenote: funny how @spktkpkt and I are interleaving our messages in both this issue and the one over in https://github.com/thestk/rtaudio/issues/118 :-)
Thanks for the pointers, all the help is really appreciated.

**Comment by spktkpkt** [comment]
@bontric Regarding 1.: That's what I've thought. I use alsa.
2.: I'll try this tomorrow and report back, it looks definitely like the solution to me.

Thank you!
