### ISSUE TITLE
Use .vcv extension for patches rather than .json

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/Rack#48]
Good idea, or no?

**Comment by mhetrick** [comment]
I think it's a great idea. That way, we can safely associate the extension with the application. Right now, .json files are opened by my text editor.

**Comment by oblivionratula** [comment]
*nods*

**Comment by AndrewBelt** [comment]
This way I can associate .vcv files to open with Rack when double clicked on Windows (maybe) and Mac.

**Comment by teotigraphix** [comment]
good idea

**Comment by JPenuchot** [comment]
Supporting both would be nice. I prefer the json extension because it makes the format obvious, I wouldn't have tried editing save files manually if I didn't see it.

**Comment by AndrewBelt** [comment]
That's true. Renaming it to .vcv removes the _notion_ of openness, although it's no less open.

**Comment by teotigraphix** [comment]
If you are passing them around with weird names, vcv is obvious but then again, NP++ just opens them if json. So it's 50/50 both ways.

One option would be to "save" in vcv, and have an "save as json" in the menu. The the app will obviously load either vcv or json extension.

But you are always going to get this one or the other, you have to make a choice what the name is either way of the primary save file. :)

**Comment by AndrewBelt** [comment]
Fixed with c4178ef8a3c03443bc4a27b046a686c3b144768c

The user is entirely able to save and load as .json though.
