### ISSUE TITLE
Midi Trigger to CV note off problem

### ISSUE THREAD

**Issue by ebunders** [VCVRack/Rack#481]
OS both windows and linux (ubuntu)
Version 0.5

the Midi Trigger to CV module gives me problems. Note on is ok, but once it received a note, the signal stays high. I use a beatstep pro to send the midi. Beatstep sends a note-off event with velocity 64. perhaps that could be the problem?

On windows I also tried my Keylab49, with same result. Not off is not recognized (alas)

**Comment by bontric** [comment]
This has been fixed upstream already (https://github.com/VCVRack/Rack/pull/434 , See #450 )

If you need a fix now, you need to compile the latest version from sources

**Comment by ebunders** [comment]
First: sorry for creating an issue that was already there. I looked, bug apparently not hard enough.
Second: that is good news. I will build a new version for myself.

Thanks you for the swift reply

**Comment by bontric** [comment]
No worries! You probably only searched the `open` issues (There is a default filter when using the search function on issues).

Hope you can get Rack to work!
