### ISSUE TITLE
Suggestion: `ESC` key should close `Add module` window

### ISSUE THREAD

**Issue by fracturedface** [VCVRack/Rack#484]
OS (if applicable): all
Version (or "dev" if compiling from source): dev
![image](https://user-images.githubusercontent.com/33377021/33580240-61d3f28c-d91a-11e7-916d-ba21ade1f580.png)
I think that this window should be able to be closed by pressing `esc` on your keyboard.

**EDIT:** I also think that mousing over a manufacturer in the `Manufacturers` tab should automatically open their name on the right side clicking should make it "stick" though, if that makes sense.

**EDIT 2:** There should be a button to switch between the old layout and new one in my opinion.

**EDIT 3:** The window should expand as much as possible to fit each plugin manufacturer and plugin in, versus having to scroll and having the menu as a set size.
![image](https://user-images.githubusercontent.com/33377021/33585075-6a09c056-d930-11e7-8952-f968003e2b4a.png)

**Comment by g-elfling** [comment]
Good suggestion :)!

**Comment by AndrewBelt** [comment]
Should be fixed with the Module Browser in Rack v0.6
