### ISSUE TITLE
Problem with building

### ISSUE THREAD

**Issue by drcrotato** [VCVRack/Rack#486]
OS (if applicable): Windows (Edition: Windows 10 home, Version: 1709, OS build: 16299.98)

I want to develop plugins but I'm getting these errors when building:

```
hrovn@DESKTOP-JIHG441 MINGW32 ~
$ git clone https://github.com/VCVRack/Rack.git
Cloning into 'Rack'...
remote: Counting objects: 3789, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 3789 (delta 1), reused 3 (delta 1), pack-reused 3779
Receiving objects: 100% (3789/3789), 1.92 MiB | 1.25 MiB/s, done.
Resolving deltas: 100% (2909/2909), done.

hrovn@DESKTOP-JIHG441 MINGW32 ~
$ git submodule update --init --recursive
fatal: Not a git repository (or any of the parent directories): .git

hrovn@DESKTOP-JIHG441 MINGW32 ~
$ make dep
make: *** No rule to make target 'dep'.  Stop.
```

**Comment by AndrewBelt** [comment]
`cd Rack`

**Comment by drcrotato** [comment]
ok, Ill try it. Thanks!

**Comment by drcrotato** [comment]
It made this error 3 times after make dep

`make: gcc: Command not found
`
then,
`arch.mk:16: *** recipe commences before first target.  Stop.
`

**Comment by AndrewBelt** [comment]
Why are you wanting to build Rack from source. You can download an installer for Rack v0.5 from https://vcvrack.com/

**Comment by drcrotato** [comment]
I've already installed VCV Rack. Do I not need to do that part of the instructions?

**Comment by AndrewBelt** [comment]
I was just wondering why you wanted to build Rack from source, since the reason is to write code for it or develop your own plugins, and you don't seem to have a compiler. But if you'd still like to proceed, read https://github.com/VCVRack/Rack#windows
