### ISSUE TITLE
Loading a patch from another directory fails to load panel GUI

### ISSUE THREAD

**Issue by JoshuaStorm** [VCVRack/Rack#49]
The below occurs when loading a rack saved outside of the install directory. Worse-so, if I make a new rack after loading the below rack, it continues to fail to load the panel GUIs. 

If I had to guess, I'd say this is a filepath issue but I haven't had a chance to dive into the source yet.

![image](https://user-images.githubusercontent.com/12414183/30341333-a97edb1c-97c3-11e7-9fa7-c4e60622f43b.png)

**Comment by teotigraphix** [comment]
Same Issue as #42

**Comment by JoshuaStorm** [comment]
Woops, my bad
