### ISSUE TITLE
issue compiling Dev Rack on Mac

### ISSUE THREAD

**Issue by tedpallas** [VCVRack/Rack#490]
OS (if applicable): 10.12.6

Version (or "dev" if compiling from source): dev

attempting make gives the following error:

Savages:Rack Ted$ make
c++ -Iinclude -Idep/include -Idep/lib/libzip/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7 -DAPPLE -stdlib=libc++ -std=c++11 -stdlib=libc++ -c -o build/src/app.cpp.o src/app.cpp
In file included from src/app.cpp:1:
In file included from include/app.hpp:4:
include/widgets.hpp:5:10: fatal error: '../ext/nanovg/src/nanovg.h' file not
      found
#include "../ext/nanovg/src/nanovg.h"
         ^
1 error generated.
make: *** [build/src/app.cpp.o] Error 1

**Comment by cschol** [comment]
Did you run `make dep` first?

**Comment by tedpallas** [comment]
yup! i followed the instrux in the readme, and make dep specifically tells me it's all installed properly

#######################################
# Built all dependencies successfully #
#######################################

**Comment by AndrewBelt** [comment]
No, this is an issue with not doing

>Clone submodules.

>git submodule update --init --recursive

successfully from the README.

**Comment by tedpallas** [comment]
I am very new to this, redoing 
git submodule update --init --recursive
made everything work out 👍
