### ISSUE TITLE
Lock mode

### ISSUE THREAD

**Issue by g-elfling** [VCVRack/Rack#492]
Yeah an option to tighten a module or all modules at once with imaginary screws so it won't move :D I always accidentally move modules when I am just trying to rotate a knob. Cheers! :)

**Comment by AndrewBelt** [comment]
Perhaps a Lock Modules feature from the toolbar. There's too much in the toolbar right now, so we'd need to use icons, and tooltips would need to be implemented (using Blendish) so you know what each icon does.

**Comment by g-elfling** [comment]
Mate I can see the screws on VCV Rack but they aren't screwing on anything ;) just kidding lolol :P Skeuomorphism

**Comment by Strum** [comment]
Maybe an option could be added to the right mouse menu to lock a module in place.

**Comment by AndrewBelt** [comment]
No, this should be a global setting. Individual locking is too tedious.

**Comment by jph-wacheski** [comment]
needed feature for live uses,. .  dragging whole modules when missing a control is jarring.

**Comment by Dultzo** [comment]
Just started using Vcv rack yesterday and after first session googled to see if a 'lock modules in place' setting existed... Shame it doesn't exist atm but good to see a bunch of requests for it. Hopefully it appears in a future build. On surface Pro when using touchscreen it's especially easy to accidently start moving a module instead of a knob.

**Comment by martin-lueders** [comment]
What about requiring a modulator key (ALT, or CMD) for moving modules, or right click and drag? Something which distinguishes it from normal left click, used for knobs, etc.?

**Comment by AndrewBelt** [comment]
One of the fundamentally nice things about Rack is the ease of moving modules around, so that default behavior won't change.

**Comment by martin-lueders** [comment]
OK, but then such modulator key could be used to override the optional lock. Would be faster to move a module then having to unlock all, move it, and lock them again.

Anyway, it was just an idea....

**Comment by AndrewBelt** [comment]
Oh, I see. Yeah, that's a good idea when in lock mode.

**Comment by Dultzo** [comment]
Yeah it's great being able to fly modules around the rack so easily. A well implemented 'Lock' option needn't interfere with that unless people choose for it to tho... Options are good :)

**Comment by LKHSogpit** [comment]
Always find that moving all modules to fit a module in takes very long. Perhaps if you could slide all modules left or right, to the direction you want to move them would be great. Also an auto fit when moving a module to a space could be very useful.

**Comment by AndrewBelt** [comment]
@LKHSogpit Here's the issue for that. https://github.com/VCVRack/Rack/issues/307

**Comment by alectron** [comment]
In addition - the more I play with this and really wish I would have a way to lock things (for touch screen usage as well as 'playing'/twiddling...), imo a lock mechanism should be 2-fold:
- lock modules - the aforementiond/OP's 'tighten a module or all modules at once with imaginary screws so it won't move'
- lock cables (same as for the above - globally as well as locking all in/out patch-cables  'of a single module')
Churs.

**Comment by AndrewBelt** [comment]
Marking #565 as a dependency of this issue.

**Comment by JWhiteUX** [comment]
Do users have to toggle individual screws to lock a module?

How do they know if the screw is locked, or if they locked some and not all?

I think there is a point where staying true to skeuomorphism goes overboard, wouldn't you agree?

**Comment by AndrewBelt** [comment]
No, I think the screws were tongue-in-cheek. The action will have a toggle button on the toolbar and a key command.

**Comment by JWhiteUX** [comment]
@AndrewBelt 
Ah ok, I was a bit worried there for a minute. Couldn't tell. 

> No, this should be a global setting. Individual locking is too tedious.

Would multi-select resolve this? Locking would only apply to position, not selection in this case.

**Comment by AndrewBelt** [comment]
As I mentioned in #307, Rack has no concept of selection.

**Comment by alectron** [comment]
Now that locking modules is possible in the 0.6.1 Rack release from the looks - would be grand if the icon would have 2 states to show if it is in a locked/unlocked state as well.

I think you had someone to help with graphic bits ? If not and you need icon edits, let me know, happy to help there.

**Comment by AndrewBelt** [comment]
I'll clean the icon states up later.

Thanks, forgot to close this.
