### ISSUE TITLE
Pinning dependency versions that use git repos

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#493]
OS (if applicable): all
Version (or "dev" if compiling from source): dev

`glfw` and `rtaudio` pull the dependency code as a clone from a `git` repo. From my experience that can lead to hard-to-track bugs coming in from people building from source since a fresh `Rack` clone will always pull the `HEAD` instead of a known, good version.

- Option 1: use `git submodules` for those dependencies that come from a repo clone
- Option 2: do a `git checkout` to a specific SHA after the clone (also check if the repo has been cloned already, and don't clone it again, otherwise `make dep` will fail when rerun).

**Comment by AndrewBelt** [comment]
`ext/` holds all the submodules, but I want to reserve that directory for small libraries that get "adopted" into Rack's build system, unlike the stuff in `dep/`. I suppose the best is to just use `git submodules` in `ext/` as well and remove the `git clone` commands from the dep Makefile.

**Comment by cschol** [comment]
That would be the most robust solution, I agree.

**Comment by AndrewBelt** [comment]
Fixed in f7ea40f
