### ISSUE TITLE
[Compilation]  error: use of undeclared identifier 'glfwGetWindowContentScale'

### ISSUE THREAD

**Issue by ffucci** [VCVRack/Rack#494]
OS (if applicable): Mac OS X 10.13.1
Version (or "dev" if compiling from source): dev

It seems that something is missing when compiling from commit f7ea40f677a73671463728ef47d5410888b72b7f 

c++ -Iinclude -Idep/include -Idep/lib/libzip/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7 -DAPPLE -stdlib=libc++ -std=c++11 -stdlib=libc++ -c -o build/src/gui.cpp.o src/gui.cpp

src/gui.cpp:444:3: error: use of undeclared identifier 'glfwGetWindowContentScale'
                glfwGetWindowContentScale(gWindow, &pixelRatio, NULL);

**Comment by cschol** [comment]
You need to update `glfw` to use the `master` branch. Code was updated to need that last night.

Remove `glfw` artifacts from `deps` directory. Run `git submodule update --init --recursive`, then `make dep`.

**Comment by ffucci** [comment]
Thanks, apparently deleting all the artifacts and running "make dep" again fixed my issue.
