### ISSUE TITLE
Missing asound when running make dep 

### ISSUE THREAD

**Issue by alexanalogue** [VCVRack/Rack#499]
OS (if applicable): Linux Mint Cinnamon 3.4.6
Version (or "dev" if compiling from source): 0.5.0

Hi, I'm new to Linux but trying to compile from source on my machine. I get the following error when running make dep. Any help will be appreciated. Libasound2 1.1.0 appears to be installed on my machine.

`checking for sem_init in -lpthread... yes
checking whether to compile debug version... no
checking for doxygen... no
checking for MIDI API... using ALSA
checking for snd_seq_open in -lasound... no
configure: error: ALSA sequencer support requires the asound library!
Makefile:132: recipe for target 'lib/librtmidi.so' failed
make[1]: *** [lib/librtmidi.so] Error 1
make[1]: Leaving directory '/home/alex/development/Rack/dep'
Makefile:46: recipe for target 'dep' failed
make: *** [dep] Error 2`

**Comment by cschol** [comment]
You most likely will need the `libasound` **development libraries.** The package is called `libasound2-dev`. Check if that one is installed also.

**Comment by alexanalogue** [comment]
Thanks cschol. That did the trick!

**Comment by cschol** [comment]
@AndrewBelt This issue can be closed.
