### ISSUE TITLE
Double-click zoom toggle on individual Module (feature request) 

### ISSUE THREAD

**Issue by Dultzo** [VCVRack/Rack#501]
OS (if applicable):
Version (or "dev" if compiling from source):

Sorry can't see the option to label this a 'feature request' and not an 'issue'. 

Double click module zoom would be great. Is a very fast/convenient UI workflow function for Model 15 on iPad.

Blown away by VCV after first session. Incredible instrument and 'taster' for anyone toying with the idea of copping modular hardware. Excited to see it unfold. Great job!

**Comment by AndrewBelt** [comment]
Could you describe your feature request in more detail? It sounds to me that by double clicking, you want the height and width of the double clicked module to fill the screen. Why would you want this?

**Comment by Dultzo** [comment]
No, that'd be kind of overkill to strech a module fullscreen ;) I was suggesting Double-click (or double-tap on touchscreen) on un-used space on a module = zoom to the VCV max zoom setting and centred on the module you double tap. And double-tap again reverts it to the users previous zoom setting. The moog model 15 ios app is great in terms of making a large UI manageable on a relatively small screen and this is one of its most useful general workflow functions.

**Comment by AndrewBelt** [comment]
I can see why this might be wanted for touch screens, but Rack is not tuned for touch yet, so closing. If it ever does, I'll rely on my UX design instead of issues.

**Comment by Dultzo** [comment]
How is it a touchscreen thing? Small laptop screen is just the same.... Mouse or laptop touch pad double click to zoom and focus on a module is way faster and more fluid than faffing with the zoom slider...

**Comment by AndrewBelt** [comment]
It makes more sense to use #502 using a mouse.

**Comment by Dultzo** [comment]
Yeah for sure :) Not always convenient tho. Laptop on lap for example. Been using the mouse touch pad on laptop and it can often just feel a little clunky without a 'zoom to module' function.

**Comment by AndrewBelt** [comment]
Okay, then Ctrl+plus/minus key commands as well, added to issue

**Comment by Dultzo** [comment]
Not sure how 'select module with mouse > key command > tweak params using mouse > back to key command to zoom back out' is quicker/more fluid than simple double click with mouse? Much more focused considering you'll be using the mouse to tweak param etc? Other options seem unnecessarily scattered to me when it could be ultra simple..

**Comment by bontric** [comment]
> Not sure how 'select module with mouse > key command > tweak params using mouse > back to key command to zoom back out' is quicker/more fluid than simple double click with mouse? Much more focused considering you'll be using the mouse to tweak param etc? Other options seem unnecessarily scattered to me when it could be ultra simple..

It seems to me that you are missing the point here. Implementing a "Zoom to module" is more effort than using the already existing zoom feature. What @AndrewBelt is describing  allows you to use the zoom feature not only by selecting the zoom factor in the top bar but also using `ctrl + scroll` or `ctrl + +/-`. This is easier to implement and is preferred since adding a "zoom to module" is a rather small improvement compared to the already existing zoom feature.

**Comment by Dultzo** [comment]
I understand that it would possibly be more difficult to implement. But think of it this way, when you're using hardware modular do you slide it left/right/up/down and strech/shrink it? Or just reach for the module you wanna tweak? Double click to focus a module seems like it would far closer to that vibe and more fluid to me than scroll bar and zoom +/- etc. Props to VCV rack devs and all 3rd party module devs, it's all super impressive/promising.. But Moog are pretty clever dudes too.... they probably implemented the function I'm describing after significant trial and error in making things feel 'right' on a UI that is often too big for the screen real estate etc... That isn't a problem exclusive to touchscreen devices ;)
