### ISSUE TITLE
Ctrl+scroll and ctrl++/- to zoom

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/Rack#502]
When ctrl is released, the zoom will actually occur, to avoid lag when scrolling.

**Comment by andrewbest** [comment]
I'm personally used to alt+wheel for zooming when using Adobe software.

**Comment by AndrewBelt** [comment]
Added in 6e6aa6e

**Comment by Coirt** [comment]
I don't find the ctrl + scroll to zoom extremely useful at the moment. Each increment is about 19% for me just wish this could be a setting. My optimum zoom level is 133% to 200% but once I hit 200% and try yo zoom out again I'll end up back at 119% and have to manually reset to 133%. 

Perhaps if your optimum zoom level could be set and based on that it increments to that value respectively to modulo, i.e. if you set it manually to 101% it will increment based on `increment = 101 % 100` `increment = 1;` or `133 % 100 = 33` and `increment = 33;` 

of course still able reach min/max zoom with the original increment held as an int.
