### ISSUE TITLE
Console not appearing in dev build

### ISSUE THREAD

**Issue by 2johjoh2** [VCVRack/Rack#507]
OS (if applicable): OS X Sierra
Version (or "dev" if compiling from source): dev

Even after a "make clean", recursively cloning the submodules, building dependencies, and make and make run , the module doesn't appear ...

**Comment by AndrewBelt** [comment]
1. Make sure you're building the `v0.5` branch.
2. Post the "Failed to load plugin" message

**Comment by 2johjoh2** [comment]
Andrew, I just copied over the directory from the official plugin directory - that solved the problem. (Don't know if it is supposed to be available automatically)
