### ISSUE TITLE
FEATURE REQUEST: Scalable menu font

### ISSUE THREAD

**Issue by Thihi** [VCVRack/Rack#508]
OS (if applicable): I use Windows 10, but this would be useful across the operating systems
Version (or "dev" if compiling from source): 0.5.0

I use VCV Rack mainly in my living room from my 4K television that is 2.5 meters away from my face. The small font in the menu where you select racks from means that I can't make the text out and have so far gone by memorizing where the modules are what I want to use. It's been a blast, but now that I've got about 20 plugins installed it's getting really hard.

I would love a slider for changing the menu / font zoom level like there is one for the rack itself. Or maybe make the menu responsively scale to size and let me choose a font and a font size directly.

As a side note, font selection would also make it easier for some dyslexics to use the software.

**Comment by AndrewBelt** [comment]
The master branch now uses the correct DPI from the OS on Windows and Linux.

You can replace the DejaVu TTF file in `res/` if you need a different font.
