### ISSUE TITLE
VCF frequency low range

### ISSUE THREAD

**Issue by synthi** [VCVRack/Rack#51]
I noticed the VCF can´t go low enough for bass sounds or bassdrum when using high resonance (self oscillation) or when "pinging" the filter. Tried sending a negative voltage to the CV input but seem to be limiting the low range and don´t respond to neg. volyages when the cutoff freq knob is at "0". Please extend the range or even better put a hi/lo switch like the serge VCFQ.

**Comment by AndrewBelt** [comment]
Will be adding dedicated LFO to Fundamental if Grayscale gets around to it. See #45.

Meanwhile use Audible Instruments Tidal Modulator.

**Comment by synthi** [comment]
Andrew, this s about the filter not the VCO!!!

**Comment by AndrewBelt** [comment]
Oh, whoops

**Comment by AndrewBelt** [comment]
Fixed in the Fundamental repo
