### ISSUE TITLE
Global scenes/morph (feature request) 

### ISSUE THREAD

**Issue by Dultzo** [VCVRack/Rack#511]
OS (if applicable):
Version (or "dev" if compiling from source):

Having a 'scenes' module based on the Octatrack 'a>b slider and 16 scene buttons' would be amazing in VCV! Don't know if this is even possible without 3rd party devs also having to write code. But would be incredible to save  global param snapshots and morph between them..Guessing you'd have to exclude patch connection switching and only store/morph knobs etc. That would still be killer though. 

Sorry if this has already been mentioned.

**Comment by AndrewBelt** [comment]
Not worth it at any point in the future IMO. It'd be better to simply wire up a crossfader with two sections of a patch.

**Comment by Dultzo** [comment]
How on EARTH is that a better solution? Way more time consuming. Way less convenience/functionality in terms of having access to multiple saved scenes. Way more screen space needed. Ugh...  Anyone familiar with octatrack would surely see how scenes could be AMAZING in vcv? Be great to see it become more than just a faithful hardware modular rig clone... Obvs not as priority, but long term. Weird for you to say 'never!' on this one imo....

**Comment by Dultzo** [comment]
The scene module I was suggesting wouldn't even involve needing to patch any cables or add modules. It's a far more elegant/convenient way to get that functionality imho..

**Comment by Dultzo** [comment]
Basically just global macros built in to VCV... The octatrack slant on it could be optional/possibly refined to better suit the environment...

Seems like a solid suggestion to me considering mouse can only live tweak one knob at a time and there are often hundreds of knobs on screen and often the wish to tweak multiple simultaneously.. but fair enough...

**Comment by nay-seven** [comment]
Check the Moire module from Bidoo, let you morph 16 parameters with one  knob ;-)

**Comment by Dultzo** [comment]
Thanks for heads up! Sounds good, will take a look :)

**Comment by antoniotuzzi** [comment]
Also Surveillance from NYSTHI: 10 params with one knob (or CV)

**Comment by Dultzo** [comment]
Cool, thanks!

**Comment by Dultzo** [comment]
@nay-seven

Had a quick look at Moire. Definitely useful with interstitial possibilities, thanks again for heads up, but not really comparable to the convenience/flexibility that having a scene morph module built in to VCV could potentially be. Would be insanely quick to just be able to hit 'save ALL current VCV settings to scene' and and then morph between different scenes and find random param sweet spots during transitions etc. And modulate the scene fader etc.. Bummed to hear dev isn't interested to consider it for future :(

**Comment by Dultzo** [comment]
Tbh the Moire module basically nailed the module that I had in mind in terms of layout etc. The fader, the 16 snapshots, the modulation options for fader etc... Just would be next level if it was able to simply 'save current vcv global to snapshot'....Moire looks great, very creative/useful module as it is, but kind of a different tool to what I was suggesting/hoping might come in future..

**Comment by AndrewBelt** [comment]
>How on EARTH is that a better solution?
I'm not saying it's a solution, I'm saying that there's no reason to solve the problem since it's arbitrary and non-physical.
I try to avoid "global control" in Rack because I want the Rack engine to be as lightweight as possible with nearly all features done by modules instead. Adding MIDI learn is bad enough, since it requires that Rack "knows" about the feature.

**Comment by Dultzo** [comment]
Fair enough, she's your baby ;) Missing a trick tho imho....  Can appreciate the desire to keep the rack engine trim :)  Just bit of a shame when it's at the expense of ruling out some interesting functionality/convenience that 3rd party modules won't be able to offer to anywhere near the same depth/fluidity as if it was built-in under the hood (unless I'm mistaken?). Great job with VCV either way tho dude. Been getting lost in it tonight and it's spitting out some incredible stuff. Thanks!

**Comment by AndrewBelt** [comment]
It's not a "my baby" issues. It's a code liability/maintainance issue when weighed against the benefit of having such a feature.

**Comment by Dultzo** [comment]
I'm assuming when the vst and Midi Learn arrive that Host Daw will be able to automate all parameters? So I'm not sure how its too much different in terms of code-liability/maintenance etc? And I meant the suggestion as s a long term possibility. After the basic stuff is all smoothed out. Seems you just don't like the idea ;) Hence my saying 'fair enough, it's your baby'. I didn't mean that as a dig. I have zero idea about coding etc and pitfalls that something like this feature request might open VCV up to. You clearly have a vision for VCV to first and foremost remain faithful to Hardware Modular, nothing wrong with that :) Was just saying it's a shame that some of the potential benefits of taking eurorack inside computers  appear to not be on the cards in VCV. Hardly a dealbreaker tho! Amazing software :)
