### ISSUE TITLE
win 10 build err

### ISSUE THREAD

**Issue by jph-wacheski** [VCVRack/Rack#513]
OS (if applicable): win 10
Version (or "dev" if compiling from source): dev

this is a fresh win10 install so perhaps I am missing something needed? 

 Configuring done
-- Generating done
-- Build files have been written to: C:/msys64/home/Jeffrey M Wacheski/Rack/dep/glfw-3.2.1
make -C glfw-3.2.1
make[2]: Entering directory '/home/Jeffrey M Wacheski/Rack/dep/glfw-3.2.1'
make[3]: Entering directory '/home/Jeffrey M Wacheski/Rack/dep/glfw-3.2.1'
make[4]: Entering directory '/home/Jeffrey M Wacheski/Rack/dep/glfw-3.2.1'
make[4]: Leaving directory '/home/Jeffrey M Wacheski/Rack/dep/glfw-3.2.1'
[ 14%] Built target glfw
make[4]: Entering directory '/home/Jeffrey M Wacheski/Rack/dep/glfw-3.2.1'
make[4]: Leaving directory '/home/Jeffrey M Wacheski/Rack/dep/glfw-3.2.1'
make[4]: Entering directory '/home/Jeffrey M Wacheski/Rack/dep/glfw-3.2.1'
[ 15%] Building RC object examples/CMakeFiles/wave.dir/glfw.rc.obj
gcc: error: M\: No such file or directory
gcc: error: Wacheski/Rack/dep/glfw-3.2.1/deps: No such file or directory
gcc: error: M\: No such file or directory
gcc: error: Wacheski/Rack/dep/glfw-3.2.1/include: No such file or directory
C:\msys64\mingw64\bin\windres.exe: preprocessing failed.
make[4]: *** [examples/CMakeFiles/wave.dir/build.make:87: examples/CMakeFiles/wave.dir/glfw.rc.obj] Error 1
make[4]: Leaving directory '/home/Jeffrey M Wacheski/Rack/dep/glfw-3.2.1'
make[3]: *** [CMakeFiles/Makefile2:185: examples/CMakeFiles/wave.dir/all] Error 2
make[3]: Leaving directory '/home/Jeffrey M Wacheski/Rack/dep/glfw-3.2.1'
make[2]: *** [Makefile:130: all] Error 2
make[2]: Leaving directory '/home/Jeffrey M Wacheski/Rack/dep/glfw-3.2.1'
make[1]: *** [Makefile:92: bin/glfw3.dll] Error 2
make[1]: Leaving directory '/home/Jeffrey M Wacheski/Rack/dep'
make: *** [Makefile:46: dep] Error 2

Jeffrey M Wacheski@CastleNode1 MINGW64 ~/Rack

and 

g++ -Iinclude -Idep/include -Idep/lib/libzip/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -Wsuggest-override -std=c++11 -c -o build/src/main.cpp.o src/main.cpp
In file included from src/main.cpp:2:0:
include/gui.hpp:4:10: fatal error: GLFW/glfw3.h: No such file or directory
 #include <GLFW/glfw3.h>
          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [compile.mk:54: build/src/main.cpp.o] Error 1

**Comment by AndrewBelt** [comment]
You can't have spaces in your path when building some of the dependencies. Move the repo somewhere else or start over in path having no spaces, and try again.
