### ISSUE TITLE
Raspberry Pi3 Make isyou - - label - build system - -

### ISSUE THREAD

**Issue by Doray** [VCVRack/Rack#516]
OS (Rasbian stretch):
Version (dev): gcc version 6.3.0
Hi i read "make problems" , same -march=nocona error.
I retrieved from "RPI3 default compiler flags might need -funsafe-math-optimizations #1385" from RetroPi here on Github these flags > -O3 -march=armv8-a -mfloat-abi=hard -mfpu=neon-fp-armv8 -funsafe-math-optimizations -o whetstonePiA8-neon-fp-armv8.
But alas these did not work.
I would like very much to run vcvrack on Raspberry Pi3

**Comment by bontric** [comment]
> But alas these did not work.

You need to provide some logs/error outputs since it's impossible to guess what exactly is "not working". 

**Also:** As of now, the Raspberry Pi is not officially supported and (I'm almost certain) will not have enough performance to run Rack in it's current state. This might change in the future once some Optimizations are done (e.g. See #441).

**Comment by Doray** [comment]
Thnx for the reply,
i was hoping to later improve performance with a openMPI Bramble (a stack of RaspberryPi's)
D.

**Comment by AndrewBelt** [comment]
...Why not just get a normal computer instead of a cluster of RPis?

**Comment by Doray** [comment]
Ahh i just want to make a pocket mainframe called snowwhite and the seven dwarfs, a Pi3 with 7 Pi zeroes it easy to transport. As of now it has 16 channels audio through HDMI.

The error at compiling is (First is original, Second is derived from Retro-Pi)
/Rack-0.5 $ make
g++ -Iinclude -Idep/include -Idep/lib/libzip/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/util.cpp.o src/util.cpp
g++: error: unrecognized argument in option ‘-march=nocona’
g++: note: valid arguments to ‘-march=’ are: armv2 armv2a armv3 armv3m armv4 armv4t armv5 armv5e armv5t armv5te armv6 armv6-m armv6j armv6k armv6kz armv6s-m armv6t2 armv6z armv6zk armv7 armv7-a armv7-m armv7-r armv7e-m armv7ve armv8-a armv8-a+crc armv8.1-a armv8.1-a+crc iwmmxt iwmmxt2 native
compile.mk:53: recipe for target 'build/src/util.cpp.o' failed
make: *** [build/src/util.cpp.o] Error 1

/Rack-0.5 $ make
g++ -Iinclude -Idep/include -Idep/lib/libzip/include -MMD -g -O3 -march=armv8-a -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/engine.cpp.o src/engine.cpp
src/engine.cpp:9:23: fatal error: xmmintrin.h: No such file or directory
 #include <xmmintrin.h>
                       ^
compilation terminated.
compile.mk:53: recipe for target 'build/src/engine.cpp.o' failed
make: *** [build/src/engine.cpp.o] Error 1

Thanks in advance,
D.

**Comment by AndrewBelt** [comment]
Let's organize RPi build steps in https://github.com/VCVRack/Rack/issues/534
