### ISSUE TITLE
Dev Lifecycle and Test Suites

### ISSUE THREAD

**Issue by baconpaul** [VCVRack/Rack#517]
Hi!

I'm playing around with VCVRack after reading the CDM article, and it's really pretty cool. Thanks for writing such a useful bit of software. 

I wanted to try and develop a plugin myself, and it is as easy as you advertised. My dumb little first plugin actually works, builds on mac and linux, and does what it says it does. (http://github.com/baconpaul/BaconPlugs if you are interested, but it's really not an exciting unit).

But in writing it two questions popped into my mind. I did search the issues but didn't find a great answer. Apologies if this has been asked before. So here goes

1. Is there some well defined way to write a test for a module? I don't need to test the stuff provided by the framework, like serialization and what not, but if my module takes a signal and outputs signal + 1 (which my very first version did), it would be great if I could write a test which actually asserts that on some sample data.

2. When developing my UI I found I had a workflow which looked a lot like "change my SVG, shift a pixel in my module constructor, build, start the whole rack, look at it, stop the rack, adjust". That's fine. I mean I was able to make the UI I wanted. But I was left wanting something like "renderModule" which starts a teensy subset of the engine and just draws the module on screen as it would appear so that feedback cycle could drop some.

I'm happy to hear any thoughts on these topics - including a simple "here's the answer; search better!" Also happy to chip in if someone has a start on any such things and there's interest.

And again: thanks. What a neat bit of open source software. Fun stuff!

  Paul

**Comment by AndrewBelt** [comment]
I don't see the point of (1). If you want quality control, take 15 minutes to play with a release candidate before releasing. You'll find more issues than just "make sure it adds 1 to the input": usability issues, ideas for improvements to the panel design, ideas for more features, you might find that adding 1 isn't what you wanted in the first place, etc. Automated tests are not the way to improve quality control. Doing actual quality control is.

For (2), you might be interested in #374

**Comment by baconpaul** [comment]
Thanks for taking the time to answer!

On #1: I’ve seen projects a bit bigger than VCVRack which have been really helped by automated testing, so it’s become part of my dev habits. Agree it is distinct from QC, and it’s certainly not my place to convince you that it’s useful. If I end up writing more modules (which I think I might) I may add some harnessing to my plugin set to let me do it, but that’s what’s great about OpenSource - I can! If I do develop something, I’ll add a note to this issue.

374 is interesting yeah. I ended up when I went from one to 4 modules abandoning SVG and so on and just laying it out procedurally anyway, which was easy enough. nanovg was a great choice! I was more thinking “wouldn’t it be great if I could render a module from the command line without the entire engine”. Sort of a little test exe which loads the .so and renders. But again, not super high priority, and if I end up wanting to do that, I can also!

So with that, perhaps we should close this issue? Again, I’ll drop a note in here if I end up doing any of these things, and link to the repo where I do. Or, perhaps, maybe I also won’t do that and will just play with my modules for a few minutes before I release :)

And thanks again for writing a cool bit of software. It’s easy to extend and fun to use!

Happy new year

- Paul


On Dec 27, 2017, at 09:38, Andrew Belt <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't see the point of (1). If you want quality control, take 15 minutes to play with a release candidate before releasing. You'll find more issues than just "make sure it adds 1 to the input": usability issues, ideas for improvements to the panel design, ideas for more features, you might find that adding 1 isn't what you wanted in the first place, etc. Automated tests are not the way to improve quality control. Doing actual quality control is.

For (2), you might be interested in #374<https://github.com/VCVRack/Rack/issues/374>

**Comment by AndrewBelt** [comment]
>I’ve seen projects a bit bigger than VCVRack which have been really helped by automated testing

I have not, assuming we're talking about desktop software with graphics, sound, and input. Automated testing in this field would take an extra 25% effort to develop something with 0.1% problem coverage. Completely useless IMO. Scroll through the list of ~100 open bugs on this issue tracker or on any of the VCV plugins' repos, and find a single one that would have been avoided with a test that I could have written. Should you write tests for the stability of your filters, reverbs, and IIRs? It's a must. Anything else? No.

Interesting that you're programmatically generating panels. You should consider putting them in a FramebufferWidget (as a child) so they are not redrawn on every frame.

In order to be able to draw widgets, the "lightweight renderer" would need to have every dependency that Rack has, obviously including nanovg, glfw, glew, etc, but non-obviously jansson, rtmidi, rtaudio, and libspeexdsp, since your plugin needs to link to audio stuff too. Since your plugin includes every header file of Rack, it should link to the symbols as well, so nearly all of Rack's implementation needs to be linkable. So, the only application that can load Rack plugins is Rack.

**Comment by baconpaul** [comment]
Thanks for the FramebufferWidget tip. That may resolve a Linux drawing problem someone reported about my widgets. Appreciate it! When I’m back after the holidays I’ll implement that.

And yup, there’s no magic path to software that works. Testing some things makes sense - like filters and DSP stability as you mention. Testing something like ‘replay mouse events to hook up a pair of wires’ sort of never works (or ends up super fragile and expensive to maintain). I was thinking more the former than the latter also. Basically “if you have an interesting DSP core inside your step() how do you test it to make sure it does what you expect” was my thought.

Best wishes, and thanks again for reading/responding.
