### ISSUE TITLE
Module Developer Guide

### ISSUE THREAD

**Issue by JoshuaStorm** [VCVRack/Rack#52]
I was wondering if a module dev guide might be released at any point? E.g. We have source for one of our digital modules, how would we go about building to VCVRack?

Would love one if it would be possible 😄 

Thanks! I love this project, keep it up!

**Comment by AndrewBelt** [comment]
I've opened up the [Github Wiki page](https://github.com/VCVRack/Rack/wiki) for public editing, so have at it.

**Comment by AndrewBelt** [comment]
Essentially solved with https://github.com/VCVRack/Tutorial
