### ISSUE TITLE
SEQ3, Mutes, Unity, Scope, VCF override - compilation errors

### ISSUE THREAD

**Issue by SidLipovits** [VCVRack/Rack#524]
OS (if applicable): OS X
Version (or "dev" if compiling from source): dev

src/SEQ3.cpp:109:15: error: only virtual member functions can be marked 'override'
        void reset() override {
                     ^~~~~~~~~
src/SEQ3.cpp:115:19: error: only virtual member functions can be marked 'override'
        void randomize() override {
                         ^~~~~~~~~
src/Mutes.cpp:34:15: error: only virtual member functions can be marked 'override'
        void reset() override {
                     ^~~~~~~~~
src/Mutes.cpp:39:19: error: only virtual member functions can be marked 'override'
        void randomize() override {
                         ^~~~~~~~~
src/Unity.cpp:34:15: error: only virtual member functions can be marked 'override'
        void reset() override {
                     ^~~~~~~~~
src/Scope.cpp:68:15: error: only virtual member functions can be marked 'override'
        void reset() override {
                     ^~~~~~~~~
src/VCF.cpp:112:15: error: only virtual member functions can be marked 'override'
        void reset() override {
                     ^~~~~~~~~

**Comment by AndrewBelt** [comment]
Should I make a v0.5 branch for Fundamental? I have to keep it v0.5 compatible until Rack v0.6 releases.

**Comment by SidLipovits** [comment]
Sorry if that was already known.  For me, I would say there is no need for that as I don't compile Fundamental normally unless there is an update of Rack.  I hadn't commented it out in my script and noticed this, which led to the post.

**Comment by AndrewBelt** [comment]
Closing since Rack and all VCV plugins are now branched by their "compatibility version", with no master branch. There should no longer be confusion about which plugins compile against which versions of Rack.
