### ISSUE TITLE
[Feature Request] Basic Numerical Text Entry

### ISSUE THREAD

**Issue by xerophile** [VCVRack/Rack#526]
I did a cursory search and haven't seen this brought up yet, apologies if it has. Besides Undo/Redo and Midi-Learn (both already discussed it seems), my only other somewhat significant request would be the ability to double-click to enter contextual numerical values - I imagine this could be complicated for anything beyond the zoom levels etc at the top, but would be very useful with certain modules (although the ones I am thinking of are mostly third party,  incorporating the possibility would be wonderful IMHO).

**Comment by AndrewBelt** [comment]
Give an example of why you would want this and how it improves your musical performance experience. I'm not convinced, so convince me.

**Comment by xerophile** [comment]
I suppose part of me is rooted in the realm of DAWs and the 0-127 MIDI control value scale, yet I can't help imagining how that might be implemented in virtual modular. I've also noticed that some modules (again third party, such as a master BPM clock that goes to two decimal places) are difficult or impossible to dial in precisely. I suppose an alternate solution could be the implementation of a "fine tuning" hotkey, such as holding a key which causes the mouse input sensitivity to be significantly decreased when adjusting a knob or fader, such as is found in a number of DAWs and virtual instruments. It's still a bit out of my range of knowledge and research as to what units such numerical values might be scaled with, perhaps it could be incorporated into MIDI/CV conversion, but with more precision (like 0-127 but to two decimal places, or what have you). Some ideas relating to this are still rather nebulous in my mind, and perhaps there are ways of achieving such precision using the modular platform itself in ways I've yet to discover (and in that sense being part of the point of VCV itself, and an argument against my idea), but I don't fully know - it seemed intuitive to simply raise the possibility, and intuition is a big part of my musical and creative process and its evolution. I will continue experimenting and see if any other uses/potentially convincing reasons come up. Cheers for the reply and thought-provocation.

**Comment by AlexanderMotylev** [comment]
When you are doing something in stereo using 2 or more modules with almost identical settings, and you want to make certain changes to all modules, it will be nice to type in specific values. And in console it will be nice to link some channels, or type values to make balanced panning and precisely control volume of several channels

**Comment by a1laserboy** [comment]
xerophile - you can hold CTRL/CMD and you have finer control.

Alex, I found this yesterday, might be handy to be able to CMD click more than one knob to adjust them all at the same time

**Comment by AndrewBelt** [comment]
Okay, I'll add it once I add a toggleable hover tooltip to ParamWidgets. Shift+click will turn the tooltip into a text box, and Enter or clicking somewhere else will commit the value. Requires logarithmic support for QuantityWidget.

**Comment by infamedavid** [comment]
I want contribute with this threat giving my experience with another software, the graded mode and the precision mode
The graded mode can be enabled just pressing  Ctrl+click over a knob or slider, it allow to you move the control over a graded scale (the value of the base number to the scale could be configured on  the settings) ej: 5,10,15,20... or 20,18,16 or simply 3,4,5,6
THe precision mode can be enabled pressing shift+click over a knob or slide it allow  you to move through the decimal numbers between two integers ej: 1.25, 1.26 , 1.27 , 1.28 
this idea has been taken from the blender workflow and  modes can work nicely beside Numerical Text Entry

**Comment by AndrewBelt** [comment]
Added with 4c23dc9
