### ISSUE TITLE
Rack crashes when I try to enter a search string in the right click modules menu

### ISSUE THREAD

**Issue by NikalMight** [VCVRack/Rack#527]
OS (if applicable): Windows 10
Version (or "dev" if compiling from source):0.5

It only happens when none of the submenus are selected when Rack first opens up. If you select a submenu before trying to enter a search string, the crash doesn't happen.

**Comment by modlfo** [comment]
@NikalMight Do this problem happens for you in a more recent version of Rack? I'm closing the issue for now. If this happens feel free to comment and provide more information about your system.
