### ISSUE TITLE
Ability to blacklist a module

### ISSUE THREAD

**Issue by Euphorbium** [VCVRack/Rack#528]
Sometimes people implement modules that overlap or completely duplicate functionality. There should be a way to blacklist nonpreferred modules, so they do not show up in search.

**Comment by AlexanderMotylev** [comment]
+1, Module Manager is a good idea, so you can turn on and off individual modules

**Comment by AndrewBelt** [comment]
Disabling modules makes no sense and is pointlessly complicated.
