### ISSUE TITLE
compile.mk c++ version

### ISSUE THREAD

**Issue by SidLipovits** [VCVRack/Rack#529]
OS (if applicable): OS X
Version (or "dev" if compiling from source): dev

Any chance you would consider changing "CXXFLAGS" in compile.mk from c++11 to c++14?

**Comment by AndrewBelt** [comment]
Not globally. Are you looking for a way to compile your own plugin with `-std=c++14`?

**Comment by SidLipovits** [comment]
Not necessarily; I replaced compile.mk for plugin builds but was wondering about your plans for the project overall.  Thank you for responding.
