### ISSUE TITLE
UI hanging, Unable to load plugs, Tab key unresponsive to login, CPU Usage non-functional

### ISSUE THREAD

**Issue by g3nology** [VCVRack/Rack#53]
System:

Mid-2011iMac running 10.10.5.

•Right-clicking bg does nothing. I can't load any plugs (or anything period for that matter).

•As another user reported yesterday, selecting new/open causes UI to hang. I have to close rack and reopen. 

•Tab key does not move cursor from login to password box.

•Clicking cpu usage bar causes it to turn blue but doesn't display anything (rather when grey or blue).

**Comment by AndrewBelt** [comment]
One issue per post please. Also, all of these are duplicates of other issues.

**Comment by g3nology** [comment]
Noted. Thanks.
