### ISSUE TITLE
randomSeedTime - where and why we need this?

### ISSUE THREAD

**Issue by Flowstoner** [VCVRack/Rack#533]
https://github.com/VCVRack/Rack/blob/v0.5/src/main.cpp#L13
Sorry, if I have not found the real application of this function...

**Comment by AndrewBelt** [comment]
That should be called once from Rack's `main()` function and never again. You should not use it in plugins.

**Comment by Flowstoner** [comment]
Yes I know, sorry, but where do you use this generated RNG?
For what purpose? I have not been able to find where you use it yet.

**Comment by AndrewBelt** [comment]
It's used in hundreds of places in various plugins, official and third-party. Here's an example. https://github.com/VCVRack/AudibleInstruments/blob/master/src/Kinks.cpp#L46

**Comment by Flowstoner** [comment]
Excellent I had not realized that it was used in plugins.
THX and sorry again, for the stupid question.
