### ISSUE TITLE
Red dot on Update Plugins button won't go away after updating

### ISSUE THREAD

**Issue by jph-wacheski** [VCVRack/Rack#536]
OS (if applicable): win10
Version (or "dev" if compiling from source): 0.5.1

Update Plugins button always has red dot and downloads all the plugs when pressed,. 
close Rack and same result.  

Noticed it leaves zipped folders in the plugins folder,. and one dev is loose in that folder Strum's Mental  it seems??   I tried deleating everything in the folder and letting Rack rebuild it,. but ends the same.

**Comment by AndrewBelt** [comment]
This is an issue with developers' plugins, not Rack. There are four ways a plugin and its manifest can "lie to Rack", making it think that there is a new plugin available but there is not.

1. **The plugin slug is different than the manifest slug.** Rack requests to download plugin "MyPlugin", and upon downloading "MyPlugin", the plugin reports that it is called "YourPlugin" instead. Rack sees this and thinks "MyPlugin" still has not downloaded yet, so it tries to download "MyPlugin" again when clicking on Update Plugins.

2. **The plugin version is different than the manifest version.** Same as above, except Rack requests a version "0.5.42" but the download URL gives Rack version "0.5.41".

3. **The download link doesn't work.** Rack still believes it can download a plugin at the URL if it tries again, so it keeps trying when you click Update Plugins.

4. **The SHA256 does not match the downloaded ZIP.** Rack refuses to unzip a file for which the checksum is incorrect. As above, Rack believes that if it downloads it again, it may be correct, so it keeps trying when you click Update Plugins.

Leaving this open for a week or so, just so people see it.

**Comment by martin-lueders** [comment]
I have the problem that my ML_modules.zip does not get unzipped. I checked the SHA256, and it agrees, apart from the letters being displayed as upper case in one SHA256 checker, and lower case in another.

Is Rack case sensitive there? If not, what else could lead to unsuccessful unzipping?

**Comment by AndrewBelt** [comment]
Yes, the SHA256s should be lowercase. (I've never seen uppercase hex used for hashes, but I guess I could support that in a future Rack release.)

**Comment by martin-lueders** [comment]
Is there any way we can test the successful unzipping of the downloaded file before pushing it onto our repo and before updating the community *.json file? This would save you some work from always accepting the changes before it actually works, and keeps users from the pain of having broken plugins distributions.

**Comment by AndrewBelt** [comment]
No, but we're able to tell whether it will work or not if you ask us to test the download and checksum.

**Comment by jph-wacheski** [comment]
so if the dev need to fix somthing,. i can just toggle them off on the web page and manually install those.
I'll try this..,

**Comment by martin-lueders** [comment]
I just uploaded a new version of my plugin, including the correct VERSION number, but now the pull request for my ML_modules.json to VCVRACK/community fails in the travis tests. What is the best way to go about that? I never used that system before and cant make any sense out of the generated error message (rake fails somehow).

**Comment by martin-lueders** [comment]
Hi Andrew,

would you be able to check why my zip file does not extract correctly. As far as I can tell now, the slug, version number and sha256 key should be ok now. I can't find any problem. Any help would be appreciated.

**Comment by AndrewBelt** [comment]
Just merged.
Ignore the TravisCI "errors". @jeremywen is doing something with that...

**Comment by AndrewBelt** [comment]
Working on the unzip issue...

**Comment by AndrewBelt** [comment]
@martin-lueders Rack (or actually a combination of Rack and libzip) thinks your ZIP file is non-standard. How are you making the ZIP? If the command line `zip` utility, what version?

**Comment by martin-lueders** [comment]
@AndrewBelt I still used an old Makefile from the times before your Tutorial existed. I made the zip files on my Win7 machine by "send to compressed folder".  I will now switch to the new Makefile system.

Thanks for investigating this.

**Comment by AndrewBelt** [comment]
Yeah, that's probably the reason. Who knows what mess Windows makes with their built-in ZIP implementation.

**Comment by martin-lueders** [comment]
OK. All fine now for me. Thanks very much for your patient help!
