### ISSUE TITLE
rtaudio with Jack support

### ISSUE THREAD

**Issue by spktkpkt** [VCVRack/Rack#538]
OS (if applicable): Linux
Version (or "dev" if compiling from source):

Please precompile rtaudio with Jack support for the Linux binary version. At the moment i have the option to:

* use the Linux binary version and have very very poor sound
* compile myself with Jack support, have good sound but no plugin manager

Would be great to have both. :-)

**Comment by bontric** [comment]
There is a reason why Jack support is currently not included in the binary version. It will come back in the future, see #82.

**Comment by maricn** [comment]
That's where my plugin manager disappeared :D

**Comment by AndrewBelt** [comment]
Merging discussion into #82
