### ISSUE TITLE
Post 0.5.1 release version (i.e. on 0.5.0 branch) unusually poor performance.

### ISSUE THREAD

**Issue by Chaircrusher** [VCVRack/Rack#540]
OS (if applicable): Linux (Centos7 x86_64) 
Version (or "dev" if compiling from source): 0.5.0  either with VERSION=0.5.1 or without

Rack's audio breaks up with a single oscillator patched to the audio output. Buffer size doesn't matter.

**Comment by AndrewBelt** [comment]
Closing as it's impossible to reproduce without the provided information

**Comment by Chaircrusher** [comment]
FYI apparently I had a kernel version that messed with CPU allocation ;-(
