### ISSUE TITLE
Segmentation Fault when removing a Module

### ISSUE THREAD

**Issue by Nowhk** [VCVRack/Rack#541]
OS (if applicable): Windows 10 64Bit
Version (or "dev" if compiling from source): 0.5.1

When I debug using GDB, I open my Module (which is "Tutorial" at this moment). 
If I hover with mouse and I click Delete (to remove it), it invokes a segmentation fault at https://github.com/VCVRack/Rack/blob/v0.5/src/gui.cpp#L205

Thanks

**Comment by AndrewBelt** [comment]
Duplicate of #403
