### ISSUE TITLE
VCV Console direct outs pre/post fader

### ISSUE THREAD

**Issue by AlexanderMotylev** [VCVRack/Rack#542]
I would like to have an option to make direct outs post fader and react to mutes (x), so I can use it as a performance mixer controlling mutes via MIDI and record correct multitrack. It can be an option in right click menu.

**Comment by quicklyplz** [comment]
I would also like to see this feature added. The sends already have a pre-fader option in the right-click menu, so I think having a post-fader option for the direct outs would be fine there as well.

I work in VCV rack by itself when composing, and then once I'm satisfied with the patch I use the direct outs -> Bridge Module to record into my DAW. Being able to have my mix carry over would save a lot of time.

**Comment by AndrewBelt** [comment]
Send bug reports and feature requests of VCV plugins to contact@vcvrack.com.
Added to internal issue tracker.
