### ISSUE TITLE
some deps build without optimizations on OSX

### ISSUE THREAD

**Issue by mdemanett** [VCVRack/Rack#544]
OS (if applicable): OSX
Version (or "dev" if compiling from source): dev

On OSX, some deps build without optimizations.

E.g. libsamplerate configures itself to build with these CFLAGS in deps:

```
~/music-dev/vcv/Rack-dev $ egrep '^CFLAGS=' dep/libsamplerate-0.1.9/config.status
CFLAGS='-mmacosx-version-min=10.7 -stdlib=libc++ -std=gnu99 -W -Wstrict-prototypes -Wmissing-prototypes  -Waggregate-return -Wcast-align -Wcast-qual -Wnested-externs -Wshadow -Wpointer-arith -pipe'
```

Where if configured without a CFLAGS in the env it will give itself "-g -O2":

```
~/music-dev/resample $ egrep '^CFLAGS' libsamplerate-0.1.9/config.status
CFLAGS='-g -O2 -std=gnu99 -W -Wstrict-prototypes -Wmissing-prototypes  -Waggregate-return -Wcast-align -Wcast-qual -Wnested-externs -Wshadow -Wpointer-arith -pipe'
```

This is due to these lines in dep/Makefile:

```
ifeq ($(ARCH),mac)
	MACOS_FLAGS = -mmacosx-version-min=10.7 -stdlib=libc++
	export CFLAGS = $(MACOS_FLAGS)
	export CXXFLAGS = $(MACOS_FLAGS)
	export CPPFLAGS = $(MACOS_FLAGS)
	export LDFLAGS = $(MACOS_FLAGS)
endif
```

And one way to fix it is this:

```
diff --git a/dep/Makefile b/dep/Makefile
index 59fb18f..7d0afa7 100755
--- a/dep/Makefile
+++ b/dep/Makefile
@@ -4,7 +4,7 @@ LOCAL = $(shell pwd)
 include ../arch.mk

 ifeq ($(ARCH),mac)
-       MACOS_FLAGS = -mmacosx-version-min=10.7 -stdlib=libc++
+       MACOS_FLAGS = -g -O2 -mmacosx-version-min=10.7 -stdlib=libc++
        export CFLAGS = $(MACOS_FLAGS)
        export CXXFLAGS = $(MACOS_FLAGS)
        export CPPFLAGS = $(MACOS_FLAGS)
```

I rebuilt my deps with that change, and Rack seems to work fine, and the optimizations are in effect.  Some other libs that will get optimized are curl, jannson, libzip and rtmidi (others have different configure setups and seem to be unaffected by all this).
 
Profiling it both ways, resampling overhead is about 3x more without the optimizations.  

(Obvs I've been fiddling with the resampling, which is how I turned this up.)

**Comment by AndrewBelt** [comment]
Since we're no longer using libsamplerate, I'm closing this. But in case another dependency's CFLAGS are overwritten, I've added defaults to f4834d816389e0fbb8c238c69add3afa383b962a
