### ISSUE TITLE
Trying to download rtmidi from an unavailable URL

### ISSUE THREAD

**Issue by Ardakaniz** [VCVRack/Rack#546]
OS (if applicable): ArchLinux
Version (or "dev" if compiling from source): dev

I compiled from source, and when make is trying to download rtmidi, with command `wget -nc http://www.music.mcgill.ca/~gary/rtmidi/release/rtmidi-3.0.0.tar.gz`, I get:
```
--2017-12-23 00:42:38--  http://www.music.mcgill.ca/~gary/rtmidi/release/rtmidi-3.0.0.tar.gz
Resolving www.music.mcgill.ca… 132.206.143.14
Connecting to www.music.mcgill.ca|132.206.143.14|:80… connected.
HTTP request sent, waiting for response… 404 Not Found
2017-12-23 00:42:40 error 404 : Not Found.
```
When trying to download the file from a Web Browser (Firefox), I get `The requested URL /~gary/rtmidi/release/rtmidi-3.0.0.tar.gz was not found on this server.`

=> This URL seems to be broken

**Comment by AndrewBelt** [comment]
Is Gray okay?? His website's down. http://www.music.mcgill.ca/~gary/rtmidi/

**Comment by Ardakaniz** [comment]
(Updated post, I submitted it too quickly, misclick)

**Comment by Uriel-A** [comment]
The git repository is still there but I have no idea how to successfully compile it.
https://github.com/thestk/rtmidi

Or does anyone has a copy of it sitting in their Rack/dep folder? I regretting wiping my VM last night now.

**Comment by Ardakaniz** [comment]
I realize I already had rtmidi installed on my computer, I just skipped its compilation in the deps Makefile and it works

**Comment by AndrewBelt** [comment]
Mirror at https://github.com/VCVRack/Rack/issues/551#issuecomment-353785236
