### ISSUE TITLE
Windows make dep fails on libspeexdsp

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#547]
OS (if applicable): Windows 10
Version (or "dev" if compiling from source): dev (master)

Trying to compile the latest `master` 2527975693fafc04f37f93396f8bee1cc734009d.

`make dep` fails with missing dependencies on Windows for `libspeexdsp` library: 

```
./configure: line 13471: syntax error near unexpected token `FFT,'
./configure: line 13471: `  PKG_CHECK_MODULES(FFT, fftw3f)'
make[1]: *** [Makefile:105: bin/libspeexdsp.dll] Error 2
```

I have installed the following package via `pacman`:
``` mingw-w64-x86_64-fftw```

`make dep` is still failing with the same error above.

Has anyone successfully compiled this latest code on the Windows platform with `mingw`?

**Comment by cschol** [comment]
Turns out, the latest version of `libspeexdsp` is already available pre-built on the `mingw` platfom.

Install it with:
```
pacman -S mingw-w64-x86_64-speexdsp
```

In general, could `make dep` just call `pacman` on Windows where pre-built packages are available instead of compiling from source? Obviously, only in cases where there are no Rack-specific modifications to the build or newer versions of the package are required.

The Makefile's `dist` target would need to be updated to grab the library from `/mingw64/bin` (like, for example, `zlib`).

**Comment by antoniograzioli** [comment]
I get a similar error on Mac related to speex, when trying to "make" Rack from latest sources...

```
In file included from src/core/AudioInterface.cpp:6:
include/dsp/samplerate.hpp:5:10: fatal error: 'speex/speex_resampler.h'
      file not found
#include <speex/speex_resampler.h>
```

tried "make dep" but I get this: 

```
Updating build configuration files, please wait....
Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory
make[1]: *** [lib/libspeexdsp.dylib] Error 1
make: *** [dep] Error 2

```

**Comment by AndrewBelt** [comment]
You need to install `automake` and `libtool` to run that `./autogen.sh` script. Maybe I'll upload a mirror with the package pre-automaked.

**Comment by cschol** [comment]
I still haven't been able to figure out how to build the `libspeexdsp` package via `make dep` on Windows, i.e. which package will satisfy the `fftw3f` dependency.

I needed the `automake`, `autoconf`, and `libtool` packages to get started, but it is still failing the `configure` step.

**Comment by cschol** [comment]
OK. The key was to install the `pkgconfig` package. After installing it, `configure` runs and `libspeexdsp` builds with `make dep`.

In summary, the following packages are required for successfully running `make dep` and building the dependencies on Windows with `mingw`:

```
automake
autoconf
libtool
pkgconfig
mingw-w64-x86_64-fftw
```

**Comment by AndrewBelt** [comment]
Hasn't been resolved yet.

**Comment by antoniograzioli** [comment]
I solved the issue on MAC by installing automake and libtool as suggested by @AndrewBelt 


(brew install automake, brew install libtool)

I had another issure regarding linking libtool:  "/usr/local/bin" was not writeble by admin, I simply changed permissions and then run again"brew link libtool"

**Comment by cschol** [comment]
@AndrewBelt 2642d093e1642b604c78b3f12de5632ee1ae88cf should close this issue, right?

**Comment by AndrewBelt** [comment]
Yup. Reopen if still having problems.
