### ISSUE TITLE
Quad MIDI to CV CC64 Sustain release bug

### ISSUE THREAD

**Issue by Uriel-A** [VCVRack/Rack#549]
OS (if applicable): WIndows 10
Version (or "dev" if compiling from source): Both dev and v0.5.1

The current implementation of the CC64 Sustain pedal release in the Quad MIDI to CV (line 166):

```
				if (!pedal) {
					open.clear();
					for (int i = 0; i < 4; i++) {
						activeKeys[i].gate = false;
						open.push_back(i);
```
Results in **ALL** notes stopping, even if some notes are still being pressed down physically while the sustain pedal is being released. That is not the correct behavior. Note(s) that remain pressed should continue playing.

This issue does not happen in the monophonic MIDI to CV module.

**Comment by AndrewBelt** [comment]
@bontric

**Comment by bontric** [comment]
@AndrewBelt I'm going to add a fix in the open PR

**Comment by bontric** [comment]
@Uriel-A I think this should fix it:

 (Based on v0.5)

```bash
git pull https://github.com/bontric/Rack-MIDI v0.5-bontric-midi-fixes 
```

Could you please test this for me?

**Comment by Uriel-A** [comment]
> Could you please test this for me?

Just did. The notes just keeps sustaining forever. 😆 

You're half way there. If I press a key, sustain it and let go, then press another key and release sustain, the 1st note turns off and the 2nd still pressed note remains. The problem is any notes released after the sustain is off remains in sustain.

**Comment by bontric** [comment]
> You're half way there. If I press a key, sustain it and let go, then press another key and release sustain, the 1st note turns off and the 2nd still pressed note remains. The problem is any notes released after the sustain is off remains in sustain. The only way to turn them off is to trigger them again without sustain.

Thanks. I pushed so you can pull and try again :)

**Comment by Uriel-A** [comment]
@bontric Ok. The new changes pretty much fixes it, tested all 3 modes and it seems to be functioning correctly until I started encountering a weird bug that some of the gates could no longer output notes. i.e. max polyphony starts to drop until in some cases only gate 1 would respond.

Maybe something to do with the open list getting corrupted in the new code?

**Comment by Uriel-A** [comment]
I think I've be able to reproduce the new bug consistently in this manner:

1. Play a note. (gate 1 lights up)
2. Sustain on.
3. Release note.
4. Play the SAME note again. (gate 1 turns off and gate 2 lights up)
5. Release note.
5. Sustain off. (note is now stuck sustaining)
6. Hit the same note again to "unstuck" it.
7. Now only gate 1 and 2 will play. 3 and 4 is no longer accessible. (polyphony is down to 2)

Only way to "reset" the bug away is to:

8. Stop playing any notes and make sure none is stuck on sustain. (all gates off)
9. Sustain on.
10. Sustain off.
11. Now all 4 gates is operational again.

**Comment by Uriel-A** [comment]
@bontric @AndrewBelt 
Merry Christmas!
I'm done for the day. Will resume any further testing day after tomorrow. You guys should take a break enjoy yourselves too!

**Comment by bontric** [comment]
@Uriel-A Merry Christmas to you too!

The bug should be fixed now. Thanks for the testing. I now have a pedal emulator so I can at least test a bit before getting back to you :) 

> Play the SAME note again. (gate 1 turns off and gate 2 lights up)

Just a question: Is this behavior okay? I did this intentionally to emulate the behavior of a piano when the sustain pedal is pressed.

**Comment by Uriel-A** [comment]
> Is this behavior okay?

I thought this is the normal expected behavior of the Quad MIDI to CV module polyphony modes implementation of your open queue, regardless of pedal or not? I merely described the LED lights to clarify that the queue is working correct until that point.

Btw, I don't have a pedal either, nor do I use a keyboard controller. I'm using a touchscreen and Xotopad. 😄

**Comment by Uriel-A** [comment]
>  I did this intentionally to emulate the behavior of a piano when the sustain pedal is pressed.

Well yeah. It would be physically impossible for a piano to play the same note twice at the same time! But heh, I've ever came across some VSTi and DAWs that allows that, it was weird.

**Comment by bontric** [comment]
> Well yeah. It would be physically impossible for a piano to play the same note twice at the same time! But heh, I've ever came across some VSTi and DAWs that allows that, it was weird.

Okay good, just wanted to make sure this is the expected behavior :+1:

**Comment by bontric** [comment]
@Uriel-A Did you play around with the new fix? If it works I can finish the PR today :wink:

**Comment by Uriel-A** [comment]
Ah, didn't know you have update your code with newer fixes. Will compile and test in a while. In the midst of something. Give me a few hours to get back to you. 😅

**Comment by Uriel-A** [comment]
@bontric Your fix is perfect. 👍
Tested extensively in all 3 modes. Even did the legato playback test again with sustain on.

Btw, what do I do with the prev issue thread? Do I "Close and comment" or leave that to you or @AndrewBelt to handle it because I really have no idea what am I suppose to do. 😆

**Comment by bontric** [comment]
> @bontric Your fix is perfect. :+1:
Tested extensively in all 3 modes. Even did the legato playback test again with sustain on.

Thanks, I'll add the fix to the PR and clean everything up so we can merge it 

> Btw, what do I do with the prev issue thread? Do I "Close and comment" or leave that to you or @AndrewBelt to handle it because I really have no idea what am I suppose to do. :laughing:

The issues will be closed automatically once the PR is accepted, so you don't have to worry about it :)

**Comment by Uriel-A** [comment]
Thank you for fixing all these!!
