### ISSUE TITLE
Extremely Quiet

### ISSUE THREAD

**Issue by andrewr1234** [VCVRack/Rack#550]
OS: Windows 10
Version: 0.5.1

Trying out VCV Rack again and I'm having an issue with the volume. Here's a screenshot of my setup.
<img width="418" alt="setup" src="https://user-images.githubusercontent.com/29827641/34323740-5352cad2-e81d-11e7-8da0-69ec4d972855.png">

I began using VCV Rack when it was at 0.4.0 and didn't have this issue at all. The sound is barely audible even with level and my system's audio turned up as much as possible. The sound gets much louder when unplugging the ASDR from the VCA entirely. Switching to linear gain doesn't seem to change anything.

**Comment by AndrewBelt** [comment]
You're sending a 1ms trigger into the gate input of an envelope generator. Think about it: the envelope generator doesn't have much time to rise with the attack that high.
