### ISSUE TITLE
Make dep fails librtmidi

### ISSUE THREAD

**Issue by dyskonnekt** [VCVRack/Rack#551]
OS (if applicable): MacOS Sierra 10.12.6
Version (or "dev" if compiling from source):0.5.1

When trying to compile from the current sources, I get this

Resolving www.music.mcgill.ca... 132.206.143.14
Connecting to www.music.mcgill.ca|132.206.143.14|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-12-23 23:53:33 ERROR 404: Not Found.

make[1]: *** [lib/librtmidi.dylib] Error 8
make: *** [dep] Error 2

**Comment by dshr** [comment]
Looks like the source page for rtmidi (https://www.music.mcgill.ca/~gary/) has been removed. Is there any difference between the McGill version and the [version available on GitHub](https://github.com/thestk/rtmidi)?

**Comment by AndrewBelt** [comment]
I should probably switch to a git submodule instead of a release package for rtmidi.
Until then, use my mirror https://andrewbelt.name/files/VCV/rtmidi-3.0.0.tar.gz

**Comment by MaxRusse11** [comment]
I also encounter this issue building on Windows 7, with mingw gcc 7.2:

make[1]: *** [Makefile:145: bin/librtmidi-4.dll] Error 1
make[1]: Leaving directory '/c/Source/VCVRack/Rack/dep'
make: *** [Makefile:46: dep] Error 2

C:\Source\VCVRack\Rack>

I've tried swapping to the downloaded tarball, but encounter the same issue.

**Comment by AndrewBelt** [comment]
@MaxRusse11 You've ommitted the part of the error message which tells you what went wrong.

**Comment by MaxRusse11** [comment]
The error is 
checking for MIDI API... configure: error: Unknown system type for MIDI support!
