### ISSUE TITLE
Zoom settings (feature request)

### ISSUE THREAD

**Issue by LasseMunk** [VCVRack/Rack#552]
OS (if applicable): Windows 10

Hi VCV 

First of all - this is amazing!! Thank you so much for spending time on creating this software! :)

Second: I'm on a 4K  15" touchscreen laptop. When applying the 'false' fix in settings.json the touch works great, but the dials are still a bit small for live-use.

Is it possible to have the zoom setting extended to e.g. 300%?

Also when I max-out the zoom setting, the menu items when adding new modules are still very small. It would be great to also being able to set the font size of these :)

No other problems - just lots of fun! :)

Thanks!

**Comment by AndrewBelt** [comment]
DPI will be fixed in Rack 0.6.0, so the 300% zoom will become 150% zoom for you.

**Comment by LasseMunk** [comment]
Okay ! That sounds great - thanks a lot :)

w: www.spektrogram.dk

w: www.vimeo.com/lassemunk

m: lasse@spektrogram.dk
p:  0045 26 84 44 41 (DK)

2017-12-24 14:11 GMT+01:00 Andrew Belt <notifications@github.com>:
