### ISSUE TITLE
Makefile:115: *** missing separator.  Stop.

### ISSUE THREAD

**Issue by SidLipovits** [VCVRack/Rack#553]
OS (if applicable): OS X 10.13
Version (or "dev" if compiling from source): dev

Just downloaded current source for Rack (12/24 @ 9:50 AM EST) and got this message when compiling (script causes clean first)....
-------------------------------------------------------------------------------
Would remove the following items:
  build/                          dep/include/                    dep/libzip-1.2.0.tar.gz
  dep/bin/                        dep/jansson-2.10.tar.gz         dep/libzip-1.2.0/
  dep/curl-7.56.0.tar.gz          dep/jansson-2.10/               dep/share/
  dep/curl-7.56.0/                dep/lib/                        plugins/MyRack/
  dep/glew-2.1.0.tgz              dep/libsamplerate-0.1.9.tar.gz
  dep/glew-2.1.0/                 dep/libsamplerate-0.1.9/
*** Commands ***
    1: clean                2: filter by pattern    3: select by numbers    4: ask each
    5: quit                 6: help
What now> 1
Removing build/
Removing dep/bin/
Removing dep/curl-7.56.0.tar.gz
Removing dep/curl-7.56.0/
Removing dep/glew-2.1.0.tgz
Removing dep/glew-2.1.0/
Removing dep/include/
Removing dep/jansson-2.10.tar.gz
Removing dep/jansson-2.10/
Removing dep/lib/
Removing dep/libsamplerate-0.1.9.tar.gz
Removing dep/libsamplerate-0.1.9/
Removing dep/libzip-1.2.0.tar.gz
Removing dep/libzip-1.2.0/
Removing dep/share/
Removing plugins/MyRack/
M	dep/glfw
M	dep/rtaudio
Already on 'master'
Your branch is up-to-date with 'origin/master'.

Building dependencies for VCVRack
Makefile:115: *** missing separator.  Stop.

**Comment by AndrewBelt** [comment]
Fixed in 6a9bf01

**Comment by SidLipovits** [comment]
Thank you Andrew :)
