### ISSUE TITLE
Some suggestions/requests

### ISSUE THREAD

**Issue by LKHSogpit** [VCVRack/Rack#557]
OS (if applicable): Win 7 + All Platforms
Version (or "dev" if compiling from source): v0.5.1

Would absolutely love there to be a value tooltip when setting knobs. Also not too sure if there is any plans for a midi protocol but being able to use a midi controller with VCVrack would be great maybe there is a way but I have not seen. That said the tooltip value would make sense for it to be 0-127 but why limit it there I think a mouse can fine tune a lot smoother 0-1023 can be scaled to 0-127 perfectly (divided by 8)

Would love to use VCVrack with my Panorama P1. When the VST bridge comes out will that have midi? Currently using Reason 10 as a sequencer gates/note/pitch/lfo

Also what is really needed is an undo or panic button. A few times I hit backspace too early and deleted the wrong device. I think I would be fine not having undo for parameter values but for any mistaken deletes on devices it really would be great to have that panic button that could save the state of a device, it could be initialised when you mouse over a device, as you only use one mouse only one save for the project could be useful, like how the rack is saved when you press close even if the patch is not saved. A backup...

Just to comment on the v0.5.1: nice job love how VCV is progressing keep up the good work guys I have no doubt there will be great success for you in the future.

**Comment by AndrewBelt** [comment]
Thanks, but you need to split issues into separate requests. And actually, all of these are duplicates of existing requests.

**Comment by LKHSogpit** [comment]
Well there is demand for them so have not seen those requests...

**Comment by AndrewBelt** [comment]
If you can't find them and I'm wrong about them being a duplicate, you can repost them but in separate issues.
