### ISSUE TITLE
Request: Label

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Rack#558]
OS (if applicable): All
Version (or "dev" if compiling from source): v0.5.1

It would be extremely useful to have a piece of tape on the side bottom or top of modules to help organise things. Just need to name a module with tape! Sub/Kick/Bass/Hat etc small space!

**Comment by AndrewBelt** [comment]
Maybe a 2U module with 90 degree rotated text?

**Comment by LKHSogpit** [comment]
Insertable would be sweet any angle any rotation!

![tape on module](https://user-images.githubusercontent.com/12150421/34370295-c2b78062-eaba-11e7-8a96-fe4be10d3143.png)
![tape](https://user-images.githubusercontent.com/12150421/34370300-c7e54240-eaba-11e7-8d01-f05045ade304.png)

**Comment by AndrewBelt** [comment]
If you're gonna go with the photorealistic look, why not put some masking tape on your computer monitor?

(There's no way my graphic designer would let me do this.)

**Comment by LKHSogpit** [comment]
Well show him/her how it would be useful so!

 "Open-source **virtual** modular synthesizer"

**Comment by odahan** [comment]
The need is real, but there is also plenty of space (generally) between the top screws, it can be a good place to add a free label that will work on most modules (not the tiniest) without changing things a lot.

**Comment by inventhouse** [comment]
I really _really_ want something like this; it doesn't have to be skeuomorphic virtual masking tape, but some way to put free-form short labels where I would find them useful would be, well, super-useful.

The Core Notes module is good in its own way, and a 2U rotated version would be helpful, but I'd really like to be able to "stick" labels to any module.

**Comment by AndrewBelt** [comment]
I just don't imagine this proposal passing. If my designer brings it up, I'll reopen.
