### ISSUE TITLE
Fundamental Modules not appearing.

### ISSUE THREAD

**Issue by cgameing** [VCVRack/Rack#560]
Im using arch linux and installed via the AUR resources.
Version: 0.5.0

When I right click there is no fundamental plugin listed and when I search for seq I can't find that basic module. I also tried downloading the plugin and unziping it into the plugins directory but no such luck.
This is probably a noob mistake so sorry if thats the case.

Cheers.

**Comment by AndrewBelt** [comment]
If I recall, the AUR version is not Rack v0.5.* but the master branch of this repo. You'll need to compile the v0.5 branch, or use the official builds on https://vcvrack.com/ if you want to use v0.5.* plugins.

Find Rack's directory and verify that Fundamental exists in `plugins/`. If so, look at `log.txt` to determine why it's not being loaded.

**Comment by cgameing** [comment]
I think I just added the source for the fundamental plugin as there apears to be no plugin.so file. I will compile a newer version of the program and see if that fixes my issue.

**Comment by cgameing** [comment]
I tried installing the aur resource https://aur.archlinux.org/packages/vcvrack-fundamental-git/ which appeared to fix my issue, but it wouldent compile.

I ended out fixing this issue in a wierd way, by downloading the origonal source, and noticed it had a plugins folder in it, draging that and the res folder allowed me to access the fundamental plugins.
