### ISSUE TITLE
SVG rendering issue on OSX

### ISSUE THREAD

**Issue by ndonald2** [VCVRack/Rack#562]
OS (if applicable): OSX 10.10.5
Version (or "dev" if compiling from source): v0.5 compiled from source

![screen shot 2017-12-27 at 14 26 43](https://user-images.githubusercontent.com/1433497/34391247-6fa69a22-eb12-11e7-9400-03d4ce2d711a.png)

As you can see, something is broken in SVG rendering for me. I'm running OSX 10.10.5 on a hackintosh with an NVIDIA GTX 970. I know it's not an official Mac system so it's totally fair to say "all bets are off" but I've never encountered an issue like this after several years of using this system.

I tried both the pre-built version and building it from source, with the same issue either way. PNG-based modules seem to render fine, so it's pretty clear that it's just an issue with SVG.

**What I have tried**

* Checking the SVG assets _(they render fine in any other application)_
* Disabling NVIDIA driver and using OSX driver _(performance slows to crawl, doesn't support openGL properly so Rack won't even open)_
* Updating to latest `nanovg` _(no change)_
* Trying `nanovg` repo examples _(they all work fine)_

I'd appreciate any help you can provide. Thanks!

**Comment by AndrewBelt** [comment]
This issue is old and likely obsolete. Comment if issue is still present. Closing.

**Comment by ndonald2** [comment]
This still affects my hackintosh build running OSX 10.11 but I've written it off as something unlikely to be fixed. If it's not widespread then absolutely not a big deal.

**Comment by AndrewBelt** [comment]
With what Rack version?

**Comment by ndonald2** [comment]
I haven't checked in awhile, probably about 6 months. But last time I was using a version >1.0 and ran into the same issue. I'll try the latest version when I have a moment and report back.
