### ISSUE TITLE
"Randomize All" CV Inputs

### ISSUE THREAD

**Issue by positivecentre** [VCVRack/Rack#564]
OS (if applicable): N/A
Version (or "dev" if compiling from source): N/A

Just a request that more developers add a cv input for the 'randomize all' function to their modules (like on squonk). Easily one of my favourite features in Rack is randomizing the modules. To be able to setup sequences and trigger the randomization on more of the modules would be fantastic. Thank  you.

**Comment by AndrewBelt** [comment]
Randomizing parameters from a plugin is unsupported, so if any plugins are writing to `params[...].value`, it will break in a future update.

**Comment by positivecentre** [comment]
Thanks for the fast reply Andrew but I might not have been clear enough. On NYSTHI Squonk you have a CV input for the Randomize function. I usually attach a trigger from the last step of the sequence to randomize on after every cycle. I'd like to see it added on more modules if possible. Thanks.

**Comment by AndrewBelt** [comment]
Yes, I understand what you mean, and my reply addresses that.

**Comment by antoniotuzzi** [comment]
OOPS! Thanks for the heads up !

**Comment by AndrewBelt** [comment]
I'll try to make the migration easy with an example LEDRingKnob class, but it will require adding some code to your `step()` function to keep track of its internal value.
