### ISSUE TITLE
Add icons to toolbar

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/Rack#565]
Requires adding tooltips and a tooltip overlay so you can see what each icon does. Tooltips should be displayed immediately on hover. I don't think we need a way to disable tooltips, since I don't imagine they'd ever be annoying.

Example from Blender:
![2018-05-13-072718_182x41_scrot](https://user-images.githubusercontent.com/338179/39966835-41d1e262-5680-11e8-8f23-2b267030b9ac.png)
Except I think Rack icons should be monochrome and SVG format.

Growing list of icons. I'll try to order them as will appear on the toolbar:
- [New](https://fontawesome.com/icons/file?style=regular)
- [Open](https://fontawesome.com/icons/folder-open?style=regular)
- [Save](https://fontawesome.com/icons/save?style=regular)
- [Save as](https://fontawesome.com/icons/save?style=solid)
- [Revert to last saved patch](https://fontawesome.com/icons/sync-alt?style=solid)
- Disconnect cables
- Set internal sample rate
- [Toggle CPU meters](https://fontawesome.com/icons/tachometer-alt?style=solid)

Since Rack 1 will be at least 8 months or a year or more and Rack 0.6 is the last minor beta release, these can be added in a 0.6.* version.

**Comment by milholen** [comment]
Could I see the original feature request? The nice thing about the text buttons you have is that they are unambiguous (as long as one can read English).

**Comment by AndrewBelt** [comment]
It's my own feature request, in an attempt to make room in the toolbar for additional functions like my proposal for #307, module-position-lock mode, and toggle touch scrolling.

**Comment by milholen** [comment]
OK, got it. You can see what's out there but I'd be glad to help design some more specific icons too.

Along with the two new features you just mentioned, are there other icons required? Do you want to keep the existing text buttons or convert them to icons as well?

I would suggest a small delay on tooltips, since once the initial learning curve (what does that icon mean?) has passed, the tooltip becomes obtrusive.

**Comment by AndrewBelt** [comment]
That was three new features, including the multiselect mode. I'd also like to collapse the File menu into icons. Not sure about Login, Register, Log Out, and Manage, since you would only click them once ever. I can't think of anything right now but I imagine it could grow 2x in size.

That's true about the tooltip delay.

**Comment by milholen** [comment]
OK, what's the timeline for adding these icons? Would the new features be part of 1.0?

**Comment by AndrewBelt** [comment]
Yes, 1.0 sounds good, or a "v0.7.0", whichever is after v0.6.

**Comment by AndrewBelt** [comment]
Some clarification on tooltips: On mouse enter, the tooltip would display directly below it, unobscuring and static position, and on mouse leave, they'd disappear with no timeout.

**Comment by AndrewBelt** [comment]
Since I use Font Awesome Free 5 on the website, I might as well use them for Rack icons. The free ones are CC BY 4.0, which is great. The Pro version for $60/year might also be an option, but I'll have to ask about their license because my use case falls in a gray area, and I'd rather not pay a subscription for a project that could technically still exist for decades.

The reason I like this idea is because unlike the [Noun Project](https://thenounproject.com/), these icons are created with a common design language, perhaps even by a single designer. This allows us to use Font Awesome for 75% of our icons and clone their design language for other niche stuff like patch cables and CPU meters.

Updated main post with my favorite candidates for each icon.

**Comment by milholen** [comment]
Good plan... or at least a good start for making our own custom icons.

Some additional recs:
Revert: https://fontawesome.com/icons/sync-alt?style=regular
Disconnect cables: https://fontawesome.com/icons/times-circle?style=regular
Sample rate: https://fontawesome.com/icons/signal?style=regular

Those icons for Save and Save As icons lack an inherent semantic distinction but if we end up doing custom icons based on these (which I'd be glad to do) we can do something different.

**Comment by AndrewBelt** [comment]
![2018-06-06-114700_83x59_scrot](https://user-images.githubusercontent.com/338179/41049623-58bda63e-697f-11e8-9bfe-22213319ca69.png)
I might want to find a source of icons other than Font Awesome, but I think the general idea is reasonable. Haven't added the tooltip yet.

**Comment by AndrewBelt** [comment]
Switched to IcoMoon. https://icomoon.io/app/#/select/library There are also several freely licensed icons there.
![2018-06-06-121040_110x66_scrot](https://user-images.githubusercontent.com/338179/41050899-a401cb7c-6982-11e8-9ced-48626f49b053.png)

**Comment by cunabula27** [comment]
@AndrewBelt Is that a Meter symbol doing double duty as Midi Bridge? If so I like it very much.

**Comment by AndrewBelt** [comment]
@cunabula27 Not sure what you mean, but it enables the CPU meter.

**Comment by AndrewBelt** [comment]
Switching again to https://thenounproject.com/. I'm realizing that a "common design language" is meaningless for 12x12 icons. It's more valuable to have a resource with a million icons than 1000 designed by a single person.

**Comment by AndrewBelt** [comment]
<img width="683" alt="screen shot 2018-06-06 at 11 32 13 pm" src="https://user-images.githubusercontent.com/338179/41077002-5773f414-69e2-11e8-841b-83cc09c60430.png">
Final product

**Comment by AndrewBelt** [comment]
Switched back to dropdown menus in recent commits. Icons are difficult to learn compared to having descriptive text in a hierarchy.
