### ISSUE TITLE
make dep fails on macOS

### ISSUE THREAD

**Issue by diemonster** [VCVRack/Rack#566]
OS (if applicable): macOS 10.13.3
Version (or "dev" if compiling from source): dev

I've followed build instructions in other macOS issues in this repo; I installed `libtool` and `automake` and got fairly far into `make dep` until hitting the following:
https://gist.github.com/diemonster/82acf955957fa0afd056723de9ee0161

I have both `openssl` and `openssl@1.1` installed via `brew`, FWIW.

**Comment by AndrewBelt** [comment]
Wow, MacOS 10.13 sure breaks a lot. I might get a new computer soon and will be able to solve these. Don't want to upgrade my 10.12 Macbook.

**Comment by diemonster** [comment]
@AndrewBelt I can take a stab at fixing this, I'll open a PR if I get anywhere with it.

**Comment by diemonster** [comment]
I can confirm `make dep` runs successfully on another laptop running 10.13.2, so this is likely a misconfiguration issue.

**Comment by Chondrules** [comment]
Hi - This may or may not be of help.  Just found your project.  But I checked out the source and built it on my 10.13 mac and hit runtime issues after build.  I simply changed the Rack.sh script to start like this:

#!/bin/bash
unamestr="$(uname)"

if [[ "$unamestr" == 'Linux' ]]; then
    LD_LIBRARY_PATH=dep/lib ./Rack
elif [[ "$unamestr" == 'Darwin' ]]; then
    DYLD_LIBRARY_PATH=dep/lib ./Rack
fi 

This lets the UI load for me.  There are better ways to make this work I'm sure.   Nice Project.

**Comment by AndrewBelt** [comment]
Don't use Rack.sh to launch Rack from a source build. Use `make run`.

**Comment by diemonster** [comment]
Fixed in `v0.6` branch using instructions in `README.md`.
