### ISSUE TITLE
0.5.1 Linux binary install can't find libraries or 3rd party plugs 

### ISSUE THREAD

**Issue by CJunit** [VCVRack/Rack#568]
KDE neon 5.11.0

I tried running it from both my home directory, as well as /opt, which is where I prefer it to be. Going by the instructions here: https://vcvrack.com/manual/Installing.html
I type "./Rack.sh" and get the error that "./Rack: error while loading shared libraries: libGLEW.so.2.1: cannot open shared object file: No such file or directory". I did try adding symlinks for those libraries to /usr/lib/ and that seemed to work, but I removed the links in case they interfere with anything else. Maybe I should just install Rack's library files to /usr/local/lib/. Anyway, I imagine some of the less-experienced Linux users will find that it doesn't quite work out of the box, as it were. I have been able to compile Rack 0.5.0 and it finds its libraries just fine when I "make run".

Also, the installing.html page says to install 3rd-party modules in ~/.Rack/, but Rack does not create this directory, nor does Rack search it when I create it manually. My temporary fix for this was to place a symlink of this user folder in the Rack folder instead of its own plugin folder.

So, I am guessing that some kind of script will be needed so that the Rack program can find its associated files.

**Comment by briansorahan** [comment]
@CJunit Rack.sh sets `LD_LIBRARY_PATH` so that Rack can find the shared libs in the directory you unzipped. You shouldn't have to create symlinks.

I'm on Arch and I've never seen the error you're describing.

Here is what I see in the Rack directory:

```
➜  Rack ls
libcrypto.so.1.1  libGLEW.so.2.1  libjansson.so.4  librtmidi.so.4      libssl.so.1.1  LICENSE-dist.txt  plugins  Rack.sh  snd
libcurl.so.4      libglfw.so.3    librtaudio.so    libsamplerate.so.0  libzip.so.5    LICENSE.txt       Rack     res
```

Do you have libGLEW.so.2.1?

**Comment by AndrewBelt** [comment]
>Do you have libGLEW.so.2.1?

Seconding this question.

**Comment by CJunit** [comment]
With the download version, libGLEW.so.2.1 and other libraries are there in the program's main folder. I tried running it both with and without the script:

> cjunit@cjunit-Studio-XPS:/opt/Rack$ ls
> libcrypto.so.1.1  libGLEW.so.2.1  libjansson.so.4  librtmidi.so.4      libssl.so.1.1  LICENSE-dist.txt  plugins  Rack.sh
> libcurl.so.4      libglfw.so.3    librtaudio.so    libsamplerate.so.0  libzip.so.5    LICENSE.txt       Rack     res
> cjunit@cjunit-Studio-XPS:/opt/Rack$ ./Rack
> ./Rack: error while loading shared libraries: libGLEW.so.2.1: cannot open shared object file: No such file or directory
> cjunit@cjunit-Studio-XPS:/opt/Rack$ ./Rack.sh
> ./Rack.sh: line 2: 16081 Segmentation fault      LD_LIBRARY_PATH=. ./Rack
> cjunit@cjunit-Studio-XPS:/opt/Rack$ 

I just figured out a couple of fundamental mistakes I was making. Yes, it needs the script. Also, because I installed it in /opt I needed to sudo run it, then it worked.

And for the version I compiled, the script was the same, except the compiled libraries were in Rack/dep/lib, so I guess I would need to either change the script, or move the libraries.

So thank you for your help and patience, I have basically gotten it running. Also, Rack is now seeing the plugins in my home folder.
