### ISSUE TITLE
Add module: filter by module category (tag cloud)

### ISSUE THREAD

**Issue by mkruselj** [VCVRack/Rack#572]
It would be great if we could just select the type of module we want to insert, and all available modules of that type show up. Then we could filter that list again with text input if needed.

Using a tag cloud for this seems like common sense.

Current sorting by manufacturers is not good, IMHO.

**Comment by AndrewBelt** [comment]
Already works, as described in #288

**Comment by mkruselj** [comment]
Right, but this suggestion is for adding physical buttons to click in the browser, instead of requiring you to type the category name :)

**Comment by AndrewBelt** [comment]
The Add Module popup will be trashed and replaced with a module browser, designed all at once, so I won't be tacking on incremental changes to the current implementation.

**Comment by mkruselj** [comment]
That sounds good to me as long as there are lots of ways to easily filter the list. Alrighty!
