### ISSUE TITLE
Mac Build fails on portmidi.h not found

### ISSUE THREAD

**Issue by oblivionratula** [VCVRack/Rack#58]
Failing section:
```
c++ -Iinclude -Idep/include -Idep/lib/libzip/include -DVERSION=dev -MMD -O3 -march=core2 -ffast-math -g -Wall -DARCH_MAC -DAPPLE -stdlib=libc++ -std=c++11 -stdlib=libc++ -c -o build/src/core/MidiInterface.cpp.o src/core/MidiInterface.cpp
src/core/MidiInterface.cpp:4:10: fatal error: 'portmidi.h' file not found
#include <portmidi.h>
         ^
1 error generated.
make: *** [build/src/core/MidiInterface.cpp.o] Error 1

```

Tried to copy:
`cp dep/portmidi/pm_common/portmidi.h ./dep/include/`

and build proceeds, but then fails on:
```
cc -Iinclude -Idep/include -Idep/lib/libzip/include -DVERSION=dev -MMD -O3 -march=core2 -ffast-math -g -Wall -DARCH_MAC  -c -o build/ext/osdialog/osdialog_mac.m.o ext/osdialog/osdialog_mac.m
c++ -o Rack build/src/app.cpp.o build/src/dsp.cpp.o build/src/engine.cpp.o build/src/gui.cpp.o build/src/main.cpp.o build/src/plugin.cpp.o build/src/settings.cpp.o build/src/util.cpp.o build/src/widgets.cpp.o build/src/app/CircularShadow.cpp.o build/src/app/Knob.cpp.o build/src/app/Light.cpp.o build/src/app/ModuleWidget.cpp.o build/src/app/Panel.cpp.o build/src/app/ParamWidget.cpp.o build/src/app/PluginManagerWidget.cpp.o build/src/app/Port.cpp.o build/src/app/RackRail.cpp.o build/src/app/RackScene.cpp.o build/src/app/RackWidget.cpp.o build/src/app/SVGKnob.cpp.o build/src/app/SVGPort.cpp.o build/src/app/SVGScrew.cpp.o build/src/app/SVGSlider.cpp.o build/src/app/SVGSwitch.cpp.o build/src/app/SpriteKnob.cpp.o build/src/app/Toolbar.cpp.o build/src/app/WireWidget.cpp.o build/src/core/AudioInterface.cpp.o build/src/core/MidiInterface.cpp.o build/src/core/core.cpp.o build/src/util/request.cpp.o build/src/widgets/Button.cpp.o build/src/widgets/ChoiceButton.cpp.o build/src/widgets/FramebufferWidget.cpp.o build/src/widgets/Label.cpp.o build/src/widgets/Menu.cpp.o build/src/widgets/MenuEntry.cpp.o build/src/widgets/MenuItem.cpp.o build/src/widgets/MenuLabel.cpp.o build/src/widgets/MenuOverlay.cpp.o build/src/widgets/PasswordField.cpp.o build/src/widgets/ProgressBar.cpp.o build/src/widgets/QuantityWidget.cpp.o build/src/widgets/RadioButton.cpp.o build/src/widgets/SVGWidget.cpp.o build/src/widgets/Scene.cpp.o build/src/widgets/ScrollBar.cpp.o build/src/widgets/ScrollWidget.cpp.o build/src/widgets/Slider.cpp.o build/src/widgets/SpriteWidget.cpp.o build/src/widgets/TextField.cpp.o build/src/widgets/Tooltip.cpp.o build/src/widgets/TransformWidget.cpp.o build/src/widgets/Widget.cpp.o build/ext/nanovg/src/nanovg.c.o build/ext/osdialog/osdialog_mac.m.o -stdlib=libc++ -lpthread -ldl -framework Cocoa -framework OpenGL -framework IOKit -framework CoreVideo -Ldep/lib -lGLEW -lglfw -ljansson -lsamplerate -lcurl -lzip -lportaudio -lportmidi -stdlib=libc++
ld: library not found for -lportmidi
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Rack] Error 1
```

Don't have time to track down further at the time.

**Comment by oblivionratula** [comment]
BTW: this is after a git pull this morning and also rebuilt /dep first.

**Comment by AndrewBelt** [comment]
Delete the portmidi folder, rerun `make` in the directory, and make sure the build succeeds. #29 would prevent this confusion.

**Comment by oblivionratula** [comment]
Got it.  Sorry I missed that.  I hadn't had the problem the first time I built so thought it was a recently introduced issue.

**Comment by danballance** [comment]
I appeared to be having the same kind of issue with portmidi on Ubuntu 16.04, but portmidi was building successfully. I.e.:

`
[100%] Built target test_qtest
make[2]: Leaving directory '/home/dan/Code/cpp/Rack/dep/portmidi'
Install the project...
-- Install configuration: ""
-- Installing: /home/dan/Code/cpp/Rack/dep/lib/libportmidi.a
-- Installing: /home/dan/Code/cpp/Rack/dep/lib/libportmidi.so
-- Installing: /home/dan/Code/cpp/Rack/dep/include/portmidi.h
-- Installing: /home/dan/Code/cpp/Rack/dep/include/porttime.h
make[1]: Leaving directory '/home/dan/Code/cpp/Rack/dep/portmidi'
`
But then when I then build rack and try to run it I'd get:

`
error while loading shared libraries: libportmidi.so: cannot open shared object file: No such file or directory
`
So after running:
`
sudo updatedb
sudo locate libportmidi.so
`
I worked out that I needed to add a directory to my ldconfig configuration. For me on Ubuntu 16.04 this was to create a file: /etc/ld.so.conf.d/rack.conf
`
/home/dan/Code/cpp/Rack/dep/portmidi/pm_common
`
Then I ran sudo ldconfig and then the app starts! :)

Not sure how to patch the Makefile to make this work reliably for others, but I thought I'd share this here in case it helps anyone else.

**Comment by AndrewBelt** [comment]
Closing since I've made a number of changes to the dep build system since this was posted. It should work by now.
