### ISSUE TITLE
Win 10 - Assertion failed

### ISSUE THREAD

**Issue by Manicstarseed1** [VCVRack/Rack#581]
OS Win10
Version :0.5.1
I get this dialog on startup.
I can ignore for a few seconds before it pops back up. I can not open functioning files.

![assertion failed](https://user-images.githubusercontent.com/35086742/34547951-9da3b62a-f0b3-11e7-99ab-c23421983e7b.PNG)

**Comment by AndrewBelt** [comment]
Do you have a My Documents folder? The `SHGetFolderPath()` function seems to not be able to find it.

**Comment by Manicstarseed1** [comment]
Hi:
I checked -  There was no “My Documents” folder. I created on the root drive of c:\.
Problem persists.

Thanks;
Glenn

**Comment by Uriel-A** [comment]
Just to clarify, he meant do you have a "C:\Users\<YourUsername>\Documents" folder.

**Comment by Manicstarseed1** [comment]
Thank you for the clarification.

I will double check that.

Complicating things, I re-mapped my system's "Documents" Favorite to a separate drive that has since crashed. This gives me two places to look for it.


I actually think I have the "C:\Users<YourUsername>\Documents" folder - its just not mapped at the Favorite level.


Glenn

________________________________

**Comment by AndrewBelt** [comment]
That would be the reason.

**Comment by Uriel-A** [comment]
My own Documents folder isn't in the default location either, it's somewhere on D:\

You said that yours on another drive that has crashed, you might want to either revert to the default location or remap to another valid location until you fix that secondary drive.

**Comment by Manicstarseed1** [comment]
The Remap worked.
Error resolved.
