### ISSUE TITLE
v0.5.1 won't run after compile

### ISSUE THREAD

**Issue by tonalic** [VCVRack/Rack#582]
OS (if applicable):OSX 10.13.2
Version (or "dev" if compiling from source):V0.5.1 dev

Cant make it work after compiling
DYLD_FALLBACK_LIBRARY_PATH=dep/lib ./Rack
make: *** [run] Segmentation fault: 11

**Comment by AndrewBelt** [comment]
Too little information. Run it through a debugger (with `make debug` for example) and post stack traces, and re-open.
