### ISSUE TITLE
[FEATURE REQUEST] Saving color of the patch cords

### ISSUE THREAD

**Issue by VSpellbound** [VCVRack/Rack#583]
OS (if applicable): Win10
Version (or "dev" if compiling from source):0.5.1

Hi, thanx for developing this amazing thing.

I've made a huge patch and "color codes" of cords were really helping to navigate (example: all modules with red are related to vco 1, green - vco 2 etc.)
After save/load it was gone and i immediately got lost in patch.

So is it possible in the future to  save thees colors.

Thanks

**Comment by AndrewBelt** [comment]
Duplicate of #159
