### ISSUE TITLE
Packages required for debian install

### ISSUE THREAD

**Issue by stannous** [VCVRack/Rack#585]
OS (debian stretch):
Version (or "dev" if compiling from source):

Debian users will likely need the following packages before make dep will work:

apt-get instal build-essential libx11-dev libx11-dev libgl1-mesa-dev cmake xorg-dev libglu1-mesa-dev libasound2-dev

You might want to mention this in your README

**Comment by 573** [comment]
OS (ubuntu xenial):
I have these in my deps but am getting:

    src/core/AudioInterface.cpp:11:29: fatal error: rtaudio/RtAudio.h: No such file or directory

**Comment by primaveraentalca** [comment]
@573 that file belongs to librtaudio-dev package.

**Comment by modlfo** [comment]
The information in the Rack Manual https://vcvrack.com/manual/Building.html provides an updated list of the necessary packages (for Ubuntu and Arch). I'm closing the issue. If the packages needed for Ubuntu are not enough or the same to build on Debian, feel free to comment and provide the missing ones.
