### ISSUE TITLE
compiling plugins, Ubuntu16.04

### ISSUE THREAD

**Issue by rorywalsh** [VCVRack/Rack#586]
OS (if applicable): Ubuntu 16.04
Version (or "dev" if compiling from source): dev: v.05 and master branches..

I'm having some issues with compiling the plugins. Namely:

```
src/Mutes.cpp:34:7: error: ‘void Mutes::onReset()’ marked ‘override’, but does not override
  void onReset() override {
       ^
src/Mutes.cpp:39:7: error: ‘void Mutes::onRandomize()’ marked ‘override’, but does not override
  void onRandomize() override {

```
I've tried with the the two branches available and both give me the same error. Any ideas how best to proceed? The main Rack app builds fine straight out of the box.

**Comment by AndrewBelt** [comment]
Hint: read the README of the Fundamental branch. You need to check out the v0.5.1 tag of Fundamental.

**Comment by rorywalsh** [comment]
Thanks Andrew. All good now.
