### ISSUE TITLE
Rack 'Update plugins' Loop

### ISSUE THREAD

**Issue by aeuae** [VCVRack/Rack#588]
OS (if applicable): Mac OS 10.13.2
Version (or "dev" if compiling from source): 0.5.1

After installing (successfully) KarateSnoopy's 2D Grid Seq repeatedly downloads the plugin. After the restart prompt and restarting it will ask to update it again. An Infinite Loop. 

_Also: The Plugin is working fine but it seems (I'll probably open another issue for that at the plugins' repo) like the (plugin specific) randomize functions don't work on it. Which I have before seen working on video a demo by the dev._

**Comment by aeuae** [comment]
OK after looking I've realized that somebody noticed over at KS's repo: https://github.com/KarateSnoopy/vcv-karatesnoopy/issues/5 .

possibly resolved soon.

**Comment by AndrewBelt** [comment]
Yup, this is an issue with the plugin.
