### ISSUE TITLE
Update Plugin Show Details

### ISSUE THREAD

**Issue by djpeterso23662** [VCVRack/Rack#589]
OS (if applicable): all
Version (or "dev" if compiling from source): 0.5.1

I am wondering if there is an easy and elegant way to show which plugins need updating when the red indicator light is on. Maybe in the add plugins dialog, or maybe as a mouse-over to the update button? Or maybe somewhere else. I understand the add plugins dialog will be reworked, so it may or may not be a good venue. 

I hope this thread will be a good place to gather thoughts on the subject, if it represents a small enough investment for a big enough benefit. Thanks for reading!

**Comment by AndrewBelt** [comment]
Fixed in v1.
