### ISSUE TITLE
repo.msys2.org down unreachable in MSYS2/mingw-w64

### ISSUE THREAD

**Issue by laurenanyever** [VCVRack/Rack#591]
OS (if applicable): Windows 10 
Version (or "dev" if compiling from source): 5.1

In the initial MSYS2 installation,  Mingw-w64 attempts to update from repo.msys2.org which is down or unavailable to my IP because of my internet provider? That seems strange considering that I nearly live in downtown Los Angeles. 

I've tried pinging and building but every time it can't update anything from repo.msys2.org because it is unavailable to me. Is there a way I can point it to update everything from a mirror site?

This has been a known issue with people but it seems like there's no resolution really. 
[repo.msys2.org down unreachable] (https://github.com/Alexpux/MSYS2-packages/issues/849)

[here's the gist]( https://gist.github.com/laurenanyever/8b2c65f3daba4f4be810368d67c4010f)

Thanks!

**Comment by AndrewBelt** [comment]
This has nothing to do with Rack.
