### ISSUE TITLE
No sound/hang on Windows with new AudioWidget

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#594]
OS (if applicable): Windows 10
Version (or "dev" if compiling from source): master/HEAD (092fb60b5753f6dbf3b4b8c386a59c5ba8f203d0)

Not sure what the state of the new `AudioWidget` is in terms functionality, but there is no sound on Windows after tonight's pull. All the drivers/sample rates show up in the context menu, but selecting DirectSound and a device causes Rack to hang with no sound. No updates in the GUI thread at that time, eg. scope is frozen, no blinking lights. The app does respond to a window close and shuts down.

Relevant debug output at the time of hang:
```
[debug] Opening audio stream 0
[debug] Starting audio stream 0
```

Anything I can do to help troubleshoot?

**Comment by AndrewBelt** [comment]
It's a WIP.

**Comment by AndrewBelt** [comment]
Finished.
