### ISSUE TITLE
C++ idiom for creating and configuring Widget subclasses

### ISSUE THREAD

**Issue by baconpaul** [VCVRack/Rack#595]
Hi!

createParam has this signature:

    template <class TParamWidget>
    ParamWidget *createParam(Vec pos, Module *module, int paramId, float minValue, float maxValue, float defaultValue);

I was wondering if you'd consider changing that return type to `TParamWidget*` as opposed to `ParamWidget *`. 

The reason I'm interested in this is because it would allow me to add a bunch of state setters to my components which would mock up having a constructor. 

    addChild( createParam< MyWidgetType> (...)->
                  setFeature( )->
                  setFeature2() );

rather than adding the variations as type specifications (like you do with the BlueColor and so on template params to lights).  I guess it would also let you have other 'optional' param features (like adding a setTitle to param which then #389 could let people opt into without changing the createParam args).

I sort of hate the "return this so I can do chains" style in C++ but in this case it seems handy.

Of course it's easy enough for me if you don't make that change. And I suppose it is, in one sense, weakening the type requirement (as stated, you require TParamWidget : ParamWidget). So if you like this signature, I can just stick with my cast, which is fine. 

But thought I'd add this comment in case it's a change you like.

Thanks again for a nice bit of software and a well run dev community!

  Paul

**Comment by AndrewBelt** [comment]
Sounds reasonable, fixed in e616e12.

I would suggest an alternative method though. Define a templated class and use template arguments to define behavior.

```cpp
template <int FOO>
struct MyParam : Param {
	MyParam() {
		doSomething(FOO);
	}
};

createParam<MyParam<12>>(...);
```

**Comment by baconpaul** [comment]
Yeah the thing that made me write this comment was that I had a slider class which was templated on the height of the slider, and that just seemed super odd. When changing that to something a bit less like Slider< 270 > (as I was double buffering by background so I needed a lot of implemntation details in my header) I set I ended up with this request.

And I could go both ways. The int-as-template-idiom and return-this-in-a-chain-idiom are both ones which make me a little itchy. Also so much code ends up in headers when you parameterize on an int, not that that really matters.

I guess I could also have written my question as: "Any reason you chose to have us go down the lots-of-templates-arg-route rather than the lots-of-small-functions or lots-of-constructors route for hand rolled widgets"? I'm happy with any idiom and plugins are well isolated anyway (which is a really nice part of the architecture, btw!) 

Thanks again for a quick response and quick fix!

**Comment by AndrewBelt** [comment]
>Any reason you chose to have us go down the lots-of-templates-arg-route rather than the lots-of-small-functions or lots-of-constructors route for hand rolled widgets?

Chained setters are okay but hard to memorize because there's one level of indirection. If you make your own classes with templates, you're directly modifying fields, which is nicer. Another alternative (which you can use with Rack) is

```cpp
construct<MyParamWidget>(&Widget::box, Rect(...), &ParamWidget::foo, ...);
```

"lots-of-constructors" would mean "***lots***-of-constructors", since I'd need to forward dozens of arguments every time I need to subclass Widget and add a new constructor argument.

**Comment by baconpaul** [comment]
Yeah thanks. Lots of constructors is always a bad idea, I agree.  There's also a mutability thing which made me sort of dislike allowing someone to "reset the height of my slider" when i swapped. You are now convincing me to swap back and just accept the header file has implementation details growth, which is really no big deal. So I'll go back to template, but the diff on return type still seems handy.

thanks again!

**Comment by AndrewBelt** [comment]
Modified my above post with a short chain example.

**Comment by baconpaul** [comment]
Yeah exactly. That was the sort of thing I was thinking about. But again, then you get the mutability problem. Also there's the question of default management vs specificity (but that's ugly with templates also in another way), that if you require a user to set a default your only option if they don't is a runtime error as opposed to a compile time error. So you would do

    createParam< MyThingy >( vec, mod, My::Name, 0, 2, 1 ) ->
         chainBackground( COLOR_PINK ) ->
         chainWidth( 12 )

but of course, then someone later can nefariously call chainWidth again and muck with your class.

Ugh. Patterns, Mutations, and Constructons. Is there any morning they can't ruin! Chuckle.

Thanks for the back and forth. Glad to follow your lead on the idiom you'd like for your software.

**Comment by AndrewBelt** [comment]
My policy for Rack is that everything should be mutable, so that's not an issue. (i.e. if a programmer wants to do something, they should be able to. No sense treating them like babies.) Also, no arguments allowed in constructors. These two things make complex class structures a breeze. So the only issue with chaining is the prefix. `chain` still looks weird. Maybe just `set` as usual and let people figure out which ones are chained?

**Comment by baconpaul** [comment]
That's one of the only two policies that make sense, and we're in C++, not clojure, so handing out sharp knives is the way of the world, yup. 

So the smalltalk folks would be super expecting the setters to return `this' but it is less idiomatic in C++ agreed. Reading the wiki on method chaining quickly, they make a good point that in C++ people often use streams for chaining. But that seems kinda insane here and no-one would bother to do it. (I mean, can you really imagine all that operator<< overloading and silly little subclasses). clojure has the cool "doto" construct which does this for you automatically but that's probably more trouble to implement than its worth also.

Perhaps the word you are looking for, though, is 'with'  So then you get

    createParam< MyThingy >( v, m, m::y, 0, 2, 1 ) ->
        withBackground( COLOR_PINK ) ->
        withWidth( 12 )

and then the default implementation of `withFoo' is

     T *withFoo( const T2& v) { setFoo( v ); return this; }

I dunno. C++ is, again, such a lovely loose language that it's hard to figure out which of the so many wonderful features to use here. 

Hope this helps some?

**Comment by AndrewBelt** [comment]
I've found that the following idiom works very well and solves some of the problems above.

```cpp
struct LEDBezelButton : OpaqueWidget {
	...

	template <typename T>
	static T *create(Vec pos, Module *module, int firstLightId) {
		LEDBezelButton *o = new T();
		o->box.pos = pos;
		o->light->module = module;
		o->light->firstLightId = firstLightId;
		return o;
	}
}


LEDBezelButton::create<FurtherSpecializedLEDBezelButton>(Vec(0, 0), module, 0);
```

Compare this to "every class has a constructor with arguments", and you'll find that you need to implement *much fewer* of these `create()` functions. It looks nice when you call it too.

**Comment by squinkylabs** [comment]
@AndrewBelt back in the old days we called your create function a "class factory". And static class factories are definitely way better than "a bunch of different constructors". Well, better in the sense that it's more readable and less error prone. This programmer like to be protected from sharp things.

**Comment by baconpaul** [comment]
Yes that’s definitely a smart pattern to use! Thanks.

**Comment by AndrewBelt** [comment]
Closing since #692 has been resolved.
