### ISSUE TITLE
Polyphony through virtual MIDI jacks/cables

### ISSUE THREAD

**Issue by tilmankamp** [VCVRack/Rack#597]
How about having polyphony support by adding virtual MIDI jacks and cables? Internally, the MIDI input to a module could for example be represented as an array (of constant size?) of GATE and V/Oct `Input` structures. This approach would just require some special widget support.
An actual design could also work totally different - I just want to start this conversation. If there is an agreement on some clean and straight-forward polyphony approach, I'm also willing to implement it.

**Comment by AndrewBelt** [comment]
With the new MIDIWidget, it would be possible to make a plugin that receives MIDI and does whatever it wants with the incoming MIDI messages.
But that's as far as I want to go. Only one type of cable will ever exist: single voltages.
