### ISSUE TITLE
Canonical way of architecture detection in Plugin Tutorial

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#598]
OS (if applicable): all
Version (or "dev" if compiling from source): dev

I have seen a few plugins (including my own ;)) that in their own unique way determine the platform in their `Makefile`.

Perhaps the `Tutorial` `Makefile` example should contain something like this:

```
include ../../arch.mk

ifeq ($(ARCH), lin)
	# Linux
endif

ifeq ($(ARCH), mac)
	# Mac
endif

ifeq ($(ARCH), win)
	# Windows
endif
```

**Comment by AndrewBelt** [comment]
95% of plugins don't need it, so I'd rather handle it by giving a note to the developers. Could you collect a list?

**Comment by cschol** [comment]
Will do. 

`vcv-link` (Ableton Link integration from Stellare Modular) was one of them, but I just submitted a PR adding native Windows build support with MinGW for them and included the change using `arch.mk` in it.
