### ISSUE TITLE
Runtime Error when disconnecting bluetooth headphones

### ISSUE THREAD

**Issue by GnomeTek** [VCVRack/Rack#599]
I started the program, connected my BLT headphones and selected them as the output. In either engine pause, or engine run state when the headphones are turned off, the program crashes. 
System does not crash if output devices is not set to BLT headphones when headphones turned off. 

Probably not that common of an issue, but given the popularity of BLT headphones/devices and the lack of save-ability in this scenario it's probably worth a look. 

OS Win 10:
Version 0.51:
*I'm running the self installed full version from the web, not a self compiled program. 
But I did run a debug within VS2017 to see if i could gleam any more information. Below is the exception. 
Unhandled exception at 0x00007FFA551C3FB8 (KernelBase.dll) in Rack.exe: 0x20474343 (parameters: 0x0000000012C6AA30). occurred

**Comment by LKHSogpit** [comment]
Runtime error also when I choose ASIO4All in my DAW when VCV is open and using a different soundcard. VCV becomes unresponsive and is forced to close. Looks like the same error.

**Comment by AndrewBelt** [comment]
This issue is old and likely obsolete. Comment if issue is still present. Closing.
