### ISSUE TITLE
Small fixes for building on OSX 10.12.3

### ISSUE THREAD

**Issue by sinneb** [VCVRack/Rack#6]
On osx 10.12.3 I needed the following fixes to succesfully compile Rack following the instructions:

- In /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/ a symbolic link to MacOSX.sdk from MacOSX10.7.sdk was needed (sudo ln -s MacOSX.sdk MacOSX10.7.sdk)
- carbon.h was not findable so an extra CPPFLAGS export was needed: export CPPFLAGS='-I/Applications/Xcode.app/Contents/Developer//Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Carbon.framework/Versions/A/Headers/' (see: https://stackoverflow.com/a/26757386)

Compilation ran fine after these small fixes. Then upon running Rack, the following fixes were needed: 

- libglew was called from /usr/local/lib so a copy or a symbolic link was needed: install -m 0644 dep/glew-2.1.0/lib/libGLEW.2.1.0.dylib "/usr/local/lib"
- Rack is looking for libraries in ./lib so a symbolic link from ./dep/lib to ./lib is needed: ln -s dep/lib lib

Then it runs and looks promising, although only the audio and midi modules are available ;)

**Comment by AndrewBelt** [comment]
Ideally you should download and copy the MacOS 10.7 SDK instead of link it to the current SDK. Use https://github.com/devernay/xcodelegacy to obtain that version of the SDK. Ideally the Rack Makefile should have a flag to support either the current SDK or an older one.

**Comment by AndrewBelt** [comment]
For the runtime issue, perhaps `make dist` would solve these. Or `make run` to set the correct library search path.

**Comment by sinneb** [comment]
removed libglew from /usr/local/lib and upon a clean checkout, `make run` is launching Rack succesfully now.

**Comment by mhetrick** [comment]
> libglew was called from /usr/local/lib so a copy or a symbolic link was needed: install -m 0644 dep/glew-2.1.0/lib/libGLEW.2.1.0.dylib "/usr/local/lib"

This would be an issue for people like me that have libglew installed via homebrew. It looks like that wasn't the issue, but I thought I would mention this to prevent troublesome symlinks.

**Comment by giuliomoro** [comment]
I also had to manually add the includes from the `dep/` subfolders:
```
make CXXFLAGS="-I dep/jansson-2.10/src/ -std=c++11 -I dep/libsamplerate-0.1.9/src/ -I dep/glfw-3.2.1/include/ -Idep/libzip-1.2.0/lib/ -Idep/portmidi/pm_common/ -Idep/portaudio/include"
```

**Comment by AndrewBelt** [comment]
@giuliomoro Why aren't all those headers in the `dep/include` directory?

**Comment by AndrewBelt** [comment]
@mhetrick Yes, `make dep` should never touch anything outside `dir/`.

**Comment by giuliomoro** [comment]
hmmm let me guess: considering the way I built it, it is because

- `cd dep && make` failed multiple times, then I kept running it, and it would indicate to have nothing to do.
- most importantly, the above skipped the step of copying the includes to `dep/include`
- I then tried to `make` Rack and it was failing at build time, so I added those in manually
- Once it compiled, it failed at link time, so I realized that not all the `deps` were built (because of #29), so I built them one by one.

So I tried now with a clean build and it builds cleanly without the `CXXFLAGS`, so please scrap the above.

**Comment by AndrewBelt** [comment]
I believe this has been fixed. If not, let me know.
