### ISSUE TITLE
Cannot choose correct audio interface

### ISSUE THREAD

**Issue by VisionEEG** [VCVRack/Rack#60]
Hi,
I have an Edirol FA-101 sound card under Windows 10 64 bits.  When I try to choose the audio interface, a long list blinks with 2 different offset.  The blink alternates between these 2 screenshots.  To the human eye, it seems as if 2 rows are selected.  The mouse position is in the middle of the 2 rows.

![vcvrack_bug_audiointerfaceselection1](https://user-images.githubusercontent.com/29256980/30375767-d31db8e6-9857-11e7-933c-e9d6d330058a.jpg)
![vcvrack_bug_audiointerfaceselection0](https://user-images.githubusercontent.com/29256980/30375768-d328cda8-9857-11e7-9437-511e00d3c9e8.jpg)

**Comment by synthi** [comment]
Same issue here, windows7 x64

**Comment by ModeratelyModular** [comment]
I get this long list too. When starting VCVRack for the first time, my audio-interface shows up as Windows WASAPI Loudspeakers UX-2 (as well as with prefixes MME, DirectSound and WDM-KS). And that does the job. However, when I start it up for a third time (second went wrong), I find ASIO: UX-2, that wasn't there before. Happened yesterday like this, and now again. No big issue, both work, but the ASIO is the 'regular' setting. The first time an ASIO4all is found immediately, but the ASIO UX-2 is not.

**Comment by AndrewBelt** [comment]
Fixed with df62f6fc80f72a818c809b0710f8c148e44b4402
