### ISSUE TITLE
Error building plugins/Fundamentals

### ISSUE THREAD

**Issue by PabloTassi** [VCVRack/Rack#600]
OS (if applicable): Ubuntu 16.04
Version (or "dev" if compiling from source): v0.5

make
g++ -fPIC -I../../include -I../../dep/include -DVERSION=0.5.1 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/Mutes.cpp.o src/Mutes.cpp
src/Mutes.cpp:34:7: error: ‘void Mutes::onReset()’ marked ‘override’, but does not override
  void onReset() override {
       ^
src/Mutes.cpp:39:7: error: ‘void Mutes::onRandomize()’ marked ‘override’, but does not override
  void onRandomize() override {
       ^
../../compile.mk:53: recipe for target 'build/src/Mutes.cpp.o' failed
make: *** [build/src/Mutes.cpp.o] Error 1

**Comment by AndrewBelt** [comment]
https://github.com/VCVRack/Fundamental#building
