### ISSUE TITLE
Plugin settings

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#602]
I am working on a plugin module that has a fair amount of "settings"-type stuff besides the user-tweakable components on the front-panel (e.g. algorithm parameters) that I would like to store in some form of recallable preset.

Are plugins supposed to handle this themselves within their plugin directory or is a more global approach preferred, that aligns with Rack's own settings better?

I can serialize everything to a `.json` file inside the plugin directory (or the global settings directory?) using the `jansson` library. I'll deal with upgrade/compatibility issues, etc. from version to version.

On that note, do plugins have access to the UI framework, e.g. dialog boxes to communicate to the user? E.g. "Your settings version is not compatible with the current plugin version."

Sorry if this has been discussed before, I couldn't find anything in the Issues.

**Comment by AndrewBelt** [comment]
Plugin-level (not module level) settings seems like a bad idea. The user is supposed to assume that adding a module will initialize it the same way on every computer.
What settings do you have in mind?

**Comment by cschol** [comment]
The module is providing "chaos" based on parameters of equations, that are initially randomly generated without user interaction. I'd like to be able to save off a set of parameters (if I like the "chaos" generated) and be able to re-use those specific parameters once the app restarts. Reproducible "chaos" if you will.

Reading your reply again, maybe there is misunderstanding though because I misspoke. I **am** talking about **module level** settings that in **form** are the same on every computer, but in **value**, will not be.

**Comment by AndrewBelt** [comment]
Why is `toJson()` not sufficient?

**Comment by cschol** [comment]
Does `toJson()` write the parameters to a global file and persist them?

**Comment by AndrewBelt** [comment]
It saves it to the patch file.

**Comment by cschol** [comment]
Duh! Sorry, of course that works (and makes a lot of sense). Thanks for the clarification.

Maybe that information could be added to the plugin `README.md` (for slow people like me ;)).

**Comment by AndrewBelt** [comment]
No, it's fine. Most will figure it out from the docstring in the header file.
