### ISSUE TITLE
addChild and addParam

### ISSUE THREAD

**Issue by baconpaul** [VCVRack/Rack#604]
Hi!

So I spent a good hour this afternoon trying to figure out why one of my params wasn't saving in a module. I figured it out, of course, and got to read some more of the Rack source while I was at it. So not all bad.

My problem was I was accidentally doing

    addChild( createParam< RoundSmallBlackKnob >( ... ) );

So you see the problem right? The knob shows up. The knob adjusts the data in the application. The runtime tests all work. Then you quit and restart and the knob setting is gone. And the reason it is gone, of course, is because the save-to-vcv does a foreach( params ); params is a list modified by addParam( ParamWidget * ); and addChild( Widget * ) basically does everything addParam does except for a params.push_back.

OK so cool now I know that and I'll never do it again. Probably. Or at least will find it more quickly when I do.

But I was thinking, addChild and addParam are called very infrequently. They are constructor-time only function really. So we have some time. How would you feel about something like (in pseudo-code)

    void addChild( Widget * w )
    {
      if( dynamic_cast< ParamWidget *>( w ) != NULL )
         log.warn( "Hey you are adding a ParamWidget with AddChild, which means it won't save. Sure?" )
      ... (rest of the code )

You get the idea.  And I guess similarly for inputs and outputs and (maybe) lights? I didn't actually read those 3 branches since I was just debugging params.

Anyway I understand if you don't want this. It is a very dev-focused message; there may be a reason you want to addChild a param (but I can't quite think of one); maybe there's some place you want to put dev-time error messages that you don't want prod time and that's not ready yet; etc... but thought I'd share.

Thanks again. My set of modules should be ready for release this week. Wouldn't have happened without answers to issues here and clearly written software and doc.

**Comment by AndrewBelt** [comment]
No, `Widget` shouldn't know anything about `ParamWidget`. I'm not interested in protecting stupid programming mistakes like these. Why not add a warning for doing X if a programmer wants to do Y for all X != Y? Because that would take infinite time.

**Comment by baconpaul** [comment]
Oh duh yeah that cycle makes this an obviously bad idea. Sorry I didn't think of that. Thanks!
