### ISSUE TITLE
Feature request: Lemur type of interface builder with custom values sent.

### ISSUE THREAD

**Issue by paradiddle16** [VCVRack/Rack#605]
OS (if applicable):any
Version (or "dev" if compiling from source):

Some sort of interface builder where you specify how wide your module is for the interface and then add knobs/sliders/triggers/on-off with the types of value that you wanna send (midi, hertz,ect).  It could also be something like putting an input and output and then using something similar to expr in pure data (formulas), you could manipulate the input data and send it out. I guess it's not really a small thing but the idea sort of came to me when I would have liked to have a rows of buttons that would send the value that I specify to trigger which pattern on a sequencer module to play next. It could be buttons that triggers slices in a sample player for example.

**Comment by catronomix** [comment]
To me this seems more appropriate for a module thanthan a feature built-in to rack.
Either simple modules to combine, with some slider/knob/button grids in different useful layouts, or one module that has the features you describe. 
But for all these things there are seperate modules that can you can already build this with.

**Comment by AndrewBelt** [comment]
I'm not interested in building a VCV Rack module builder. The `helper.py` script makes it convenient for plugin developers to place components in Inkscape and generate a boilerplate C++ file with all components placed correctly.
See https://vcvrack.com/manual/Panel#adding-components for instructions.
