### ISSUE TITLE
settings.json documentation

### ISSUE THREAD

**Issue by nanoplink** [VCVRack/Rack#606]
OS (if applicable): any
Version (or "dev" if compiling from source): v0.5.1

Hi! I'm one of those users who own a tablet and would like to use it to control Rack.

After a quick search in the issues and commits of the projects, I found you added the `allowCursorLock` entry in settings.json and it works properly. However from what I saw it seems this feature is not documented besides in the changelog. Nor the existence of the settings.json, where it is located or what values are allowed.

Explicitly stating in the documentation and/or the FAQ that settings.json exists and you can edit values there would definitively help newcomers. That could also reduce the number of issues where editing `allowCursorLock` is the solution and therefore take less of your time.

I'm willing to contribute the project so if you don't have time for that I can edit the proper files.

I hope my issue is well formatted. In any case I'm open for further discussion. Have a nice day!

**Comment by AndrewBelt** [comment]
It's an undocumented feature and is not supported. I'll add a supported way of enabling touch mode with #565

**Comment by nanoplink** [comment]
Noted, thanks :)
