### ISSUE TITLE
Request: Same type button Swipe on input

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Rack#607]
OS (if applicable): All
Version (or "dev" if compiling from source): Future

It would be great to be able to hold the mouse button and swipe across the likes of gate to quickly set that column/row. I currently have this set up with X-Mouse Button Control (button 5 on mouse repeating every 200ms) Heres an example of what I mean.
![shift drag bottons](https://user-images.githubusercontent.com/12150421/34736780-fbe48dec-f56b-11e7-8136-bd8d612061e7.gif)

Would be useful for other settings also mixer mutes and solo's perhaps holding shift while dragging could toggle the repeat once for the first selected control type. Hard to get a smooth transition in the example. Other useful things you could do with this repeat is setting clocks or resetting LFO to be exact, Recording a button trigger for a Buffer Module perhaps some chained modules DIY LFO sync'd min/max value to time of repeat. Can be done as I said with X-Mouse Button Control but it would be very useful if there was a menu option for this or a tool built into VCV

**Comment by AndrewBelt** [comment]
You can do this already using some simply hackery.

```cpp
virtual void onDragStart(EventDragStart &e) {
	// Enable `this`
}

virtual void onDragEnter(EventDragEnter &e) {
	MyButton *origin = dynamic_cast<MyButton*>(e.origin);
	if (origin) {
		// Enable `this`
	}
}
```

**Comment by LKHSogpit** [comment]
Cool good to know if I every figure out how to add it I'll try it out! Will it make it into a release version this would be something that would save a lot time. Suppose one could save the template for the patterns but Starting from scratch is how I have always produced more inspiring I find.
