### ISSUE TITLE
Rack Build on Windows 7 

### ISSUE THREAD

**Issue by furioncycle** [VCVRack/Rack#608]
OS (if applicable): Windows 7
Version (or "dev" if compiling from source): dev

Hello all this is an amazing project and would love to try to help out!!

I built the Rack from the v0.5 branch using mingw in Windows 7.

I was following the guide to build the rack and noticed some things when building the dependencies:

The openssl-1.1.0g failed on compiling saying it does not give a valid preprocessing token.

Also the libsamplerate-0.1.9 will fail a checking for a build system this was said to be due to an older version of config.guess and config.sub (Did see this in another issue that you will not be using it anymore??)

**Comment by AndrewBelt** [comment]
Can you post the whole build error, surrounded by triple ```?

**Comment by furioncycle** [comment]
Nevermind, it was my build environment that was off!
