### ISSUE TITLE
Failing to build dependencies automatically.

### ISSUE THREAD

**Issue by saphire-lattice** [VCVRack/Rack#609]
OS (if applicable): ArchLinux
Version (or "dev" if compiling from source): dev, master branch

Failing to build via `makepkg` after editing a `vcvrack-git`'s PKGBUILD to checkout master and init all modules recursively, and then do `make dep`.
Build fails on `make dep` step, when jansson is trying to get built, with a `libtool:   error: cannot determine absolute directory name of 'dep/lib'` error.

**Comment by AndrewBelt** [comment]
Can you post the whole build error, surrounded by ```?

**Comment by dangranos** [comment]
```
../libtool: line 7472: cd: dep/lib: No such file or directory
libtool:   error: cannot determine absolute directory name of 'dep/lib'
make[4]: *** [Makefile:427: libjansson.la] Error 1
make[4]: Leaving directory '/home/saphire/sources/aur/vcvrack-git/src/vcvrack/dep/jansson-2.10/src'
make[3]: *** [Makefile:450: all-recursive] Error 1
make[3]: Leaving directory '/home/saphire/sources/aur/vcvrack-git/src/vcvrack/dep/jansson-2.10'
make[2]: *** [Makefile:359: all] Error 2
make[2]: Leaving directory '/home/saphire/sources/aur/vcvrack-git/src/vcvrack/dep/jansson-2.10'
make[1]: *** [Makefile:108: lib/libjansson.so] Error 2
make[1]: Leaving directory '/home/saphire/sources/aur/vcvrack-git/src/vcvrack/dep'
make: *** [Makefile:46: dep] Error 2
```

**Comment by AndrewBelt** [comment]
I'm able to build jansson just fine. Can you solve this yourself by trying to build and install jansson outside the build directory (with some local `--prefix`)?

**Comment by dangranos** [comment]
Archlinux has jansson package, but because build process of Rack requires building each dependency with `make dep` and not rely on any of already libraries installed on the system, it is a bit problematic without manually choosing which libraries of Rack to build.

**Comment by AndrewBelt** [comment]
That's correct, but the system installation of jansson has nothing to do with this issue.
