### ISSUE TITLE
Tweak for CLang 3.2 on Linux

### ISSUE THREAD

**Issue by Chaircrusher** [VCVRack/Rack#612]
OS (if applicable): Linux
Version (or "dev" if compiling from source): v0.5.1

Clang didn't like the way this was initialized. It's a forward-compatible change -- works with GCC
diff --git a/src/core/MidiIO.cpp b/src/core/MidiIO.cpp
index 2ca166e..5569398 100644
--- a/src/core/MidiIO.cpp
+++ b/src/core/MidiIO.cpp
@@ -26,7 +26,7 @@ void MidiIO::setChannel(int channel) {
 	this->channel = channel;
 }
 
-std::unordered_map<std::string, MidiInWrapper *> MidiIO::midiInMap = {};
+std::unordered_map<std::string, MidiInWrapper *> MidiIO::midiInMap = std::unordered_map<std::string, MidiInWrapper *>{};
 
 json_t *MidiIO::addBaseJson(json_t *rootJ) {
 	if (deviceName != "") {

**Comment by AndrewBelt** [comment]
Thanks. I'm deleting that code soon anyway.

**Comment by Chaircrusher** [comment]
LOL fine.  IT LIVES ON in v0.5.1!!!

**Comment by AndrewBelt** [comment]
File was removed in Rack 0.6, closing.
