### ISSUE TITLE
Feature Request: A 'cheat sheet' for each module.

### ISSUE THREAD

**Issue by ZuluEchoRomeOscar** [VCVRack/Rack#613]
OS (if applicable): Any
Version (or "dev" if compiling from source): 0.5.1

Future plugin manifest to include a simple cheat sheet reminding the user of the use of each part: A graphical format would be favourite, in the style of the attached (from the recently released BalisticENV by Non Linear Instruments).
![canvas](https://user-images.githubusercontent.com/35383875/34896684-a3c74c98-f7e2-11e7-9d87-622fff33d4d9.png)
To be accessed from the right-click menu of each module in a fly-out window.

**Comment by AndrewBelt** [comment]
This should be done by adding a "manual" URL to https://github.com/VCVRack/community so the link appears in the Plugin Manager. https://vcvrack.com/plugins.html

**Comment by ZuluEchoRomeOscar** [comment]
I've been using the 'Manage Plugins' button to open a browser window at the plugin page, then scrolling down to the dev's entry, clicking 'manual', and hoping there's some useful info at the other end. But the cheat sheet appeals as a quick reference. One would assume that if there's some in-depth study needed, then more time could be devoted, but for a quick reminder a quick peeking feature would be useful - trying to not interrupt the 'creative flow'...
I see this as one for the future - v1?

**Comment by AndrewBelt** [comment]
The "quick reference" should be the panel of the module. Anything more "interrupts the creative flow".
