### ISSUE TITLE
Copy modules WITH their cables

### ISSUE THREAD

**Issue by NonLinearInstruments** [VCVRack/Rack#615]
Feture request : to be able to duplicate selected modules on a patch including their connections.
Real life case: one has designed a nice chain with -say- three modules interconected. May be a mono synth voice into which we may want to experiment with different modulation schemas, but preserving the different options. Now you need to instantiate all the modules again and repeat the connections, that may be tedious.
UI Suggestion: some keystroke click for multiple select, right click mouse "duplicate selected with connections"

**Comment by n6smith** [comment]
I'd just like to lend my support to such a feature. I'd also suggest that the copy/paste might be additionally useful if you could copy selections from one patch and paste into another patch and not just within the same patch.  This would allow for example, 'favorite' combinations of modules and their respective interconnecting cables.. to be easily transferred from one project to another.

**Comment by Uriel-A** [comment]
It was discussed at https://github.com/VCVRack/Rack/issues/307

**Comment by NonLinearInstruments** [comment]
OK, so I just close this issue
