### ISSUE TITLE
Build error on ubuntu 17.10 (include/GL/glxew.h:98:10: fatal error: X11/Xlib.h no found)

### ISSUE THREAD

**Issue by Luraktinus** [VCVRack/Rack#617]
OS (if applicable):Ubuntu 17.10
Version (or "dev" if compiling from source): dev (following the build intruction in the readme)

i wanted to compile Rack and I was running in an error, see screenshot.
I followed the build instructions in the readme and i am sure i entered all commands.

![2018-01-14-204319_1024x600_scrot](https://user-images.githubusercontent.com/33608674/34920192-1a1343a6-f96f-11e7-9e8b-c708328e0c01.png)

**Comment by AndrewBelt** [comment]
You need a few development libraries on Ubuntu. See https://github.com/VCVRack/Rack/wiki/Extended-build-instructions#ubuntu-1710

**Comment by Luraktinus** [comment]
you should link that in the readme then, 
it doesn't make much sense to separate build instructions on various documents.

**Comment by Luraktinus** [comment]
i mean, how the heck should i have known that there is even a wiki and that it is containing the (real?) building instructions...

**Comment by Luraktinus** [comment]
i understand keeping the Readme clean, then my recommendation is completely removing the build instructions from README.md and create a file called BUILDING.md and include ALL instructions there...

the problem with the wiki is that it is its own branch and if someone clones the main repo the build instructions are missing...

so yeah, I am kinda new to git but i might do that.

**Comment by AndrewBelt** [comment]
Sorry, I don't have time to write it now, and I don't necessarily trust any information on the wiki until I test it, which is time consuming.

The wiki is not attached to any source code branch. It's in its own "repo", but you can edit it using your web browser.

**Comment by Luraktinus** [comment]
i am testing it right now

**Comment by Luraktinus** [comment]
compiling was successful with the new instructions,
no problems at all
