### ISSUE TITLE
Show which cables are connected to the port you're fond of 

### ISSUE THREAD

**Issue by g-elfling** [VCVRack/Rack#618]
Yes so let's say like if you hold some modifier or anything down...and then click the mouse on some output/input port and Rack would show which cables (all of the cables) are connected to this port.

Like if you got opacity set 0.20.... then it would change the opacity for those cables (that are connected to the port you are looking at) to 1.00 for a moment (the moment you hold the modifier+mouse or whatever you decide (i'm not a GUI/UI designer))

Because at this moment you can only see the most top cable which is connected to the port. But it would be nice to figure out all the cables if it's a patch you made drunk last night and can't remember a Jack.

Have a nice developers! piece

**Comment by AndrewBelt** [comment]
That's a good idea. I could set to 100% opacity on mouse hover.

**Comment by g-elfling** [comment]
Thank yaw

**Comment by AndrewBelt** [comment]
Fixed in b51e380e3684076229725c83d70e93f25bad16c8

**Comment by g-elfling** [comment]
omg that was quick!!! Thanks a lot! I built Rack but I can't figure out how this works :D Do you mind explaining a bit :D
