### ISSUE TITLE
Auto start behavior for VCV Pulse Matrix Modules

### ISSUE THREAD

**Issue by n6smith** [VCVRack/Rack#619]
Most, if not all Sequencer modules retain their run status when a patch is saved so when you reload the patch all the sequencers start to play automatically. However Pulse Matrix does not apparently do this. Upon loading they remain in the 'stopped' mode no matter if they were running when saved or not. 

Can this be adjusted or an option provided to allow this behavior?

**Comment by MarcBoule** [comment]
I would like to second this request.

**Comment by AndrewBelt** [comment]
Sure. An additional feature: Should it be running upon initialization?

**Comment by n6smith** [comment]
If running when saved then yes,  running upon initialization would be great

Thanks!

**Comment by LKHSogpit** [comment]
I usually use a button to activate a global reset and a run if the sequencer has an input for one. Have not seen any buttons that have a latch mode (press once stays in gate on mode press again gate off)

It would be dead handy having a module that would detect and latch onto keyboard input to do this. Run on spacebar toggle. Such a module would enable your keyboard to all kinds of things. Reset LFO's, set different keys to v/oct with a cv knob beside the output, lots of possibilities. That's not to say your midi can't do this. Having keyboard input would just add to the usability. If there is any Keyboard to midi software out there this could be done with the MIDI to CV modules though.

**Comment by AndrewBelt** [comment]
Okay, I've made it run by default and save the run state to the patch. Will provide build when Rack v0.6 releases.

**Comment by MarcBoule** [comment]
Many thanks!

**Comment by DomiKamu** [comment]
Hi, I've noticed the same behavior about "OUT" button: its current state isn't saved into .vcv file.
