### ISSUE TITLE
Refresh MIDI Device list without restart

### ISSUE THREAD

**Issue by oblivionratula** [VCVRack/Rack#62]
1) Opened rack with MIDI Device - No devices listed.
2) Launched CV Toolkit which provides a virtual MIDI Divice
3) MIDI Device in Rack device list is still empty.
4) Restart Rack
5) CoreMIDI: from CV Toolkit 1 (input) (. . .) now shows. 

Would like to refresh without restart.  Removing/re-adding the MIDI Device did not refresh list either.

**Comment by AndrewBelt** [comment]
Looks like the only way to do this with portmidi is to call Pm_Terminate() and Pm_Initialize() upon opening the dropdown box. I wonder if that would mess up current streams.

**Comment by oblivionratula** [comment]
Forgive my ignorance*, but can you make a 'refresh' button or menu item to make the call? 

* I'm not a developer, just a hack and able to do builds, so I'd be happy to test a branch out.

**Comment by AndrewBelt** [comment]
A refresh button wouldn't solve anything that a dropdown trigger couldn't. I just need to check if terminating PortMIDI is possible while MIDI ports are connected. If not, then I'd have to use a different library.

**Comment by oblivionratula** [comment]
I just meant to avoid 'needless' refreshes (if they caused problems), but I guess if you're checking the pulldown, you'd likely want it refreshed.  Sorry, should think more quietly instead of so much out loud. ;)

**Comment by MaurizioB** [comment]
As for my (little) experience with PortMidi, you'll need to detach the connected port(s) and terminate/reinitialize it everytime, but I might be wrong on this.
By the way, after struggling a bit with cross-platform MIDI libraries for a [project](https://github.com/MaurizioB/Bigglesworth) of mine, I decided to use [rtmidi](https://www.music.mcgill.ca/~gary/rtmidi/) which, to me, provides slightly better flexibility than PortMidi.

**Comment by AndrewBelt** [comment]
Hmm, how do you get RtMidi to refresh?
