### ISSUE TITLE
Feature request: Record output sound to file.

### ISSUE THREAD

**Issue by NikolaiVChr** [VCVRack/Rack#620]
Record output sound to file, would enable to record a song or sound.
Or for debugging modules, analyse the sound with more fidelity that the real-time spectrum analysers does.

Could be wav file format.

Just an idea. Thanks for making awesome Rack.

**Comment by NikolaiVChr** [comment]
Nevermind, just found out its already there as 3rd party plug-in.

Was interesting though; when I recorded there was lots of cracking in the sound especially when moving the mouse. But in the recorded sound it sounded perfect.

**Comment by AndrewBelt** [comment]
It would be nice, so I might release one in the future. But I don't take module requests because we design at our own pace.
