### ISSUE TITLE
Disable randomize for certain parameters

### ISSUE THREAD

**Issue by andrewbest** [VCVRack/Rack#622]
Version: 0.5.1

I don't know of a way to disable randomization for an enable/bypass switch. This would be a nice feature.

**Comment by LKHSogpit** [comment]
If you hold a parameter with the mouse it protects it from randomization although it does not work with buttons.

**Comment by AndrewBelt** [comment]
Override `ParamWidget::randomize()` to do nothing.

```cpp
void randomize() override {}
```

**Comment by LKHSogpit** [comment]
I know asked the same thing a while ago, actually not coincidental!
