### ISSUE TITLE
CV pitch standard?

### ISSUE THREAD

**Issue by NikolaiVChr** [VCVRack/Rack#623]
0 Volt CV = 440Hz or 261.626Hz?

The oscillator in Fundamentals and [VoltageStandards](https://vcvrack.com/manual/VoltageStandards.html) indicates one, while the tutorial seems to indicate the other..

Just want to be 100% sure.

**Comment by phdsg** [comment]
although there's no general agreement on which octave maps to 0..1 its almost always a "C" that's at zero. so fundamental and the manual are "correct" in that way.

**Comment by LKHSogpit** [comment]
the documentation says C3 but 261.63 is actually middle C, C4

**Comment by AndrewBelt** [comment]
There is no hardware standard because in hardware, you're always arbitrarily offset by a frequency knob. C3 or A4 is fine. I prefer C3 on mine.
