### ISSUE TITLE
Pulse Matrix external clock response

### ISSUE THREAD

**Issue by MarcBoule** [VCVRack/Rack#624]
Pulse Matrix doesn't seem to respond to certain external clocks, for example Autodafe BPM Clock and Luckyxxl Tick; however, it does respond to RJ's BMP clock. Is there something in the way they implement their clock signals that is incorrect, or is the problem with Pulse Matrix? I suspect it could be the latter, as SEQ3 responds to all clocks named above, hence the issue posted here.
OS (if applicable): Win10
Version (or "dev" if compiling from source): 0.5.1

**Comment by AndrewBelt** [comment]
What is the pulse height of Autodafe BPM Clock and Luckyxxl Tick? Their trigger threshold needs to be 1-2V, so tell them to fix their plugins to be standard-compliant (https://vcvrack.com/manual/VoltageStandards.html). The user can amplify the clock as a workaround.

**Comment by MarcBoule** [comment]
The pulse height of Autodafe BPM Clock and Luckyxxl Tick seems to be 1V. The amplify workaround worked, and from what I was able to determine, Pulse Matrix starts working at 2V. SEQ3 works at 1V though, and if I understand correctly, from the voltage standards linked above, acceptable trigger outputs can be anywhere in the 1V to 2V range (and both SEQ3 and Pulse Matrix are in spec). It would then follow that any clock output should be 2V, such that it can be detected properly anywhere else. If this is correct, I will point them to this issue, so they can make their clocks 2V instead of 1V. Thanks AB!

**Comment by AndrewBelt** [comment]
Your edit is correct. According to the standard, it should be 5-10V high. 1V is too low. Most Eurorack wouldn't be triggered by that (unless they use slope detectors, which doesn't work in Rack).
