### ISSUE TITLE
Feature Request: Copy/Paste Parameters

### ISSUE THREAD

**Issue by GiveMeAnthony** [VCVRack/Rack#625]
Sometimes I find that I want to copy and paste the knob positions of a module to a duplicate module which is already patched in. I know that I could duplicate the module and then repatch it but it's a weird workflow. I imagine this feature as a copy and paste between like modules where you would, for example, right click one VCF and click "Copy parameters" and then right click another and click "Paste parameters" and then the knob positions would ramp up to their intended position as if they were being turned by hands (so there are no sudden jumps if connected to output).

**Comment by AndrewBelt** [comment]
As of Rack v1, right-click on the module, choose "Preset > Copy", right-click on the second module, and choose "Preset > Paste".
