### ISSUE TITLE
Suggestion: Tune Nano_VG graphics library for performance improvement

### ISSUE THREAD

**Issue by Chaircrusher** [VCVRack/Rack#629]
OS (if applicable): ALL (tested on Linux)
Version (or "dev" if compiling from source): 0.5 git label.

I built Rack using the -pg flag with GCC and had a look at where the program spends its time.  The nvg and glnvg libraries are where the GUI spends most of its time -- which is to be expected.

But one thing I noticed is that the glnvg library does something that is really bad: The #1 place the program spends its time (at least the GUI thread) is glnvg__findTexture, at 11.21% 

When I looked at that code, the problem is that glnvg stores all of its different objects (textures, calls, paths, vertices, etc) in flat arrays, and it looks them up with sequential search.

This is kind of bad for Rack, since Rack uses a TON of textures to build its UI.  And the more complicated the patch, the more time it's going to spend looking up textures.

Now, nvg is a C library, but it is also header-only. As a first step a std::map could be maintained in parallel to the array, to make lookups more efficient. The next step might be to use a STL data structure to replace the array.

I think that profiling could help overall performance a lot; exposing and encouraging the use of fast trig functions would really cut the CPU cost of some plugins. Another thing I saw during profiling is a lot of calls to the standard library sin and cosine functions. There are open source implementations out there that could be a real help.

**Comment by AndrewBelt** [comment]
Just a note: it might be 3-4 months before I can focus on performance.

If you're willing to help, memononen would likely be thrilled to receive contributions to nanovg that improves general performance for drawing lots of textures.

As for the sine/cosine, where are you finding those? Fundamental VCO by chance?

**Comment by Chaircrusher** [comment]
where I saw sin calls was in Verbos oscillator, which happened to be in the patch I profiled.

The Fundamental VCO only uses sinf for digital.  The 'analog' version uses the Decimator which is going to be more efficient.

Performance optimization is a whole huge thing, but the first step will be to do some profiling to see where the code spends its time.  I'll have a look at the texture lookup and see if I can come up with something more efficent without breaking anything ;-)

**Comment by AndrewBelt** [comment]
I'd suggest telling the author of the "Verbos oscillator" for that issue then.

If you research a good solution and implementation of the nanovg texture issue, I'll make sure it finds its way into nanovg.

**Comment by pronvit** [comment]
@Chaircrusher Are you sure your profiling is correct? Rack doesn't use so many textures that a linear search in an array of several dozens items would make any performance impact. NanoVG is a bad library performance-wise and there's a lot of much heavier stuff there. Besides, talking about this particular piece of code, there's no need for a map at all - the `textures` array is never shrunk, so a texture id can simply be its index in the array.

**Comment by Chaircrusher** [comment]
> Are you sure your profiling is correct? 
Profiling is a deterministic process so it is 'correct' with the proviso that it is different with every run.  The results will look different depending on what patch is running and how the user interacts, but this is a pretty consistent result.

I logged an issue with the NanoVG people and went a couple of round on how to fix this, and the solution they ended up with is exactly what you're suggesting.

I also think you aren't taking into account the very large number of textures Rack uses, and the fact that as a default, Rack has a very high refresh rate.  Running an O(N^2) search thousands of times a second is a bad idea.

**Comment by cunabula27** [comment]
@Chaircrusher out of interest what is the graphics refresh rate in Rack?

**Comment by AndrewBelt** [comment]
@cunabula27 Vsync, which is 60 or 70 or 75Hz, depending on your monitor.

**Comment by Walther** [comment]
A screenshot confirming that indeed one of the larger chunks of processing goes to the nanovg calls
<img width="995" alt="screen shot 2019-02-19 at 21 44 47" src="https://user-images.githubusercontent.com/2943750/53069454-eb5a2800-3490-11e9-8825-50caadfdc7e5.png">


Two possibly relevant issues here
https://github.com/memononen/nanovg/issues/371
https://github.com/memononen/nanovg/issues/451

**Comment by AndrewBelt** [comment]
This issue is old and likely obsolete. Comment if issue is still present. Closing.
