### ISSUE TITLE
Mac lockup on boot

### ISSUE THREAD

**Issue by mcclure** [VCVRack/Rack#63]
I am using Mac OS X 10.12.6 (16G29) with Rack-0.3.0 downloaded from the website. I used it several times yesterday and it worked well. Today I tried opening it and it hangs on boot. I have tried closing and reopening several times and I get the same results. I tried rebooting and got the same results.

Attached are two stack recordings made with the os x /usr/bin/sample tool. At a glance they seem indicative of some kind of deadlock. I can gather other information or attach a debugger if helpful.

Thanks!

[test.txt](https://github.com/VCVRack/Rack/files/1300161/test.txt)
[test2.txt](https://github.com/VCVRack/Rack/files/1300162/test2.txt)

**Comment by mcclure** [comment]
Duplicate of #46. Editing autosave.json fixed it (although deleting autosave.json did not, somehow?)

**Comment by oblivionratula** [comment]
It's also using a settings.json, now, so maybe something in there was still hanging in the absence of the autosave.json?  Wild guessing and not knowing what build you're using.

**Comment by mcclure** [comment]
Where does settings.json live?

**Comment by oblivionratula** [comment]
My bad, I missed where you said you were on 0.3.0 - I don't think the settings.json was in that build.  In fresh builds, it gets saved in the same directory as autosave.json.
