### ISSUE TITLE
noise

### ISSUE THREAD

**Issue by WizardMate** [VCVRack/Rack#632]
I have installed Rack and plugins on mac (10.12.6) and when I connect things up, say a kick going straight into audio interface, I hear is glitches. every sound is a glitch. Ive installed VCV rack on another mac a few weeks ago and it worked fine. The audio device Im using is the Apple Inc Built in Output. Does anyone have any suggestions.

**Comment by AndrewBelt** [comment]
Are you hitting CPU limits?
