### ISSUE TITLE
Coding Conventions?

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#633]
I realize that writing my own modules I'm free to use whatever coding conventions I like. On the other hand it's nice to be like everyone else, if possible.

I notice that VCVRack seems to mostly use tabs in the source instead of spaces, is that what most people here do?

Rack also calls c++ header files ".hpp", rather than the more common ".h". Do most people do that, too?

Are there any public coding conventions that are encouraged here (for example, use the webkit conventions is a common one).

tx!

**Comment by AndrewBelt** [comment]
1. Follow all of Rack's conventions when developing on Rack (although I don't accept PRs except in abnormal circumstances, so this information likely won't be needed by anyone else)
2. Follow whatever you please for your own plugins. I have exactly 0 guidelines. If you *want* guidelines, just follow Rack's conventions.

**Comment by TheSlowGrowth** [comment]
I'm also wondering why I see only "structs" and no "classes" in the source code. I know about the differences between both (or rather: the lack of differences) but I've not seen this style anywhere else. 
Are there any reasons for this (apart from the convenience of leaving out the "public:" keyword and the risk of having things public that should better be private)?

**Comment by AndrewBelt** [comment]
@TheSlowGrowth In Rack, no encapsulation is used, so it's simply a matter of saving the extra `public:`.
