### ISSUE TITLE
feature request - sorting of modules

### ISSUE THREAD

**Issue by JerrySievert** [VCVRack/Rack#635]
there are tags on modules, it would be awesome to be able to sort by tag, or other things - would make dealing with a ton of modules much easier.

**Comment by AndrewBelt** [comment]
Add Module window will be trashed and redesigned in v0.6, so I'm closing this since it builds off of the existing implementation.

**Comment by JerrySievert** [comment]
I actually don't use the add module window, I install everything manually.

**Comment by AndrewBelt** [comment]
When you right click on the Rack, that's the "Add Module" window.

**Comment by LKHSogpit** [comment]
@AndrewBelt 
I like the way it is currently the search is great. A custom list would be the only thing that is missing looking forward to seeing how the next design will be though.

**Comment by JerrySievert** [comment]
might I recommend the x audio protocol?  amusingly I worked at ncd when it was created.

**Comment by AndrewBelt** [comment]
@JerrySievert  I'm not sure what you mean and how it related to this issue, but could you post a link to "x audio protocol"?

**Comment by JerrySievert** [comment]
ha, I had two issues open, one was the network audio one, sorry about that.

looking for specs on the audio protocol - it's been over 20 years since I last worked there.
