### ISSUE TITLE
Fixes for Makefiles for linux builds

### ISSUE THREAD

**Issue by therealkitman** [VCVRack/Rack#636]
OS (if applicable): openSUSE 42.2
Version (or "dev" if compiling from source):v0.5.1

With regards to issue #614 I have gone through today what went wrong with the build in a bit more detail. Basically I believe two Makefiles need editing.

1. root Makefile.
There seems to be a mix up where libraries get stored ie dep/lib or dep/lib64. The zipconf.h file is also included in this lib or lib64 problem.

1a. I have added `-Idep/lib64/libzip/include`
```
FLAGS += \
	-Iinclude \
	-Idep/include -Idep/lib/libzip/include -Idep/lib64/libzip/include
```
1b. I have split the LDFLAGS for the shared libraries into their correct lib or lib64 path.
```
ifeq ($(ARCH), lin)
	SOURCES += ext/osdialog/osdialog_gtk2.c
	CFLAGS += $(shell pkg-config --cflags gtk+-2.0)
	LDFLAGS += -rdynamic \
		-lpthread -lGL -ldl \
		$(shell pkg-config --libs gtk+-2.0) \
		-Ldep/lib -lGLEW -lglfw -lrtaudio \
		-Ldep/lib64 -ljansson -lsamplerate -lcurl -lzip -lrtmidi -lcrypto -lssl
	TARGET = Rack
endif
```

1c. For the LD_LIBRARY_PATH I have added dep/lib64
```
run: $(TARGET)
ifeq ($(ARCH), lin)
	LD_LIBRARY_PATH=dep/lib:dep/lib64 ./$<
endif
```

2. dep/Makefile
From what I can read curl-7_56 **cannot** be built against openssl-1.1.0. I have edited the Makefile to get the older openssl-1.0.2 instead.
```
$(openssl):
	$(WGET) https://www.openssl.org/source/openssl-1.0.2n.tar.gz
	$(UNTAR) openssl-1.0.2n.tar.gz
	cd openssl-1.0.2n && ./config --prefix="$(LOCAL)"
	$(MAKE) -C openssl-1.0.2n
	$(MAKE) -C openssl-1.0.2n install
```

3. I have followed the wiki [here](https://github.com/VCVRack/Rack/wiki/Add-Support-for-Jack-on-Linux-(dev)) to build jack support. This works but the wiki needs to mention that you need Automake version 1.14 or better.

Having made these edits to the two Makefiles I can build and compile without problems and VCVRack runs ok so far (I don't get the Login buttons in the title bar but I don't care at the moment).

This is turning into a great app for me.
Hope this helps.
Chris.

**Comment by AndrewBelt** [comment]
1. I would prefer to fix the dep build so that libzip gets installed to `dep/lib`. But it already does on my computer. Could you suggest a change to the `dep/Makefile` that fixes this on your computer. Do you know why it's installing to the wrong directory on your machine but the correct one on my machines?

2. Just tested it, curl 7.56 seems to build just fine against openssl-1.1.0. What issue are you having with it?

**Comment by therealkitman** [comment]
Hm. Very odd. I compiled libzip-1.2.0 separately in a test folder and the `/lib64` folder was created. 

I built a clean opensuse in Virtualbox and compiledlibzip-1.2.0.  That `zipconf.h` header gets installed to `/lib/libzip/include`. I'm at a bit of a loss to understand why the difference between the two opensuses.

Will test further as well as the curl/openssl issue.

But I ask again, if my system repos already provide curl, rtmidi, rtaudio etc (standard /usr/include and /usr/lib contents), is there a need to do the `make dep` step at all?

**Comment by AndrewBelt** [comment]
You can use your system libraries, but I offer no support. It just takes some `Makefile` and `dep/Makefile` modifications.

**Comment by therealkitman** [comment]
I have tried to debug this issue with my very limited experience in compiling and building. All I can find at the `./configure` stage is that libdir gets assigned to lib64 but I cannot determine why.
```
libdir='${exec_prefix}/lib64'
libexecdir='${exec_prefix}/lib'
```
Since this seems to be a localized issue with my OS - as a Virtualbox guest openSUSE builds libzip as expected - I'm closing this issue since it's not related to VCVRack. I will seek help on the openSUSE forum a little later.

**Comment by AndrewBelt** [comment]
What's your ENV? (Don't just post the whole thing, as it may have personal information.)

**Comment by therealkitman** [comment]
Output from `env` below. No personal data :)
Funny thing, I jumped backed into my VirtualBox opensuse installation and it started creating the `/lib64` folder. I am mighty confused now and can't make excuses for what happened.

Out of curiosity I visited the https://nih.at/ web site for information that lead me to https://libzip.org which in turn lead me to github now hosting libzip. 

I pulled v1.4.0 from github as a laugh. But it compiles as needed to `/lib` without any `-m32` flag settings being passed to it.

```
chris@linux-c4x2:[~]$>ls -alR ~/AudioSoftware/zip
/home/chris/AudioSoftware/zip:
total 24
drwxr-xr-x  6 chris users 4096 Jan 25 10:14 .
drwxr-xr-x 18 chris users 4096 Jan 25 10:13 ..
drwxr-xr-x  2 chris users 4096 Jan 25 10:14 bin
drwxr-xr-x  2 chris users 4096 Jan 25 10:14 include
drwxr-xr-x  3 chris users 4096 Jan 25 10:14 lib
drwxr-xr-x  3 chris users 4096 Jan 25 10:14 share

/home/chris/AudioSoftware/zip/bin:
total 108
drwxr-xr-x 2 chris users  4096 Jan 25 10:14 .
drwxr-xr-x 6 chris users  4096 Jan 25 10:14 ..
-rwxr-xr-x 1 chris users 29752 Jan 25 10:13 zipcmp
-rwxr-xr-x 1 chris users 22672 Jan 25 10:13 zipmerge
-rwxr-xr-x 1 chris users 42816 Jan 25 10:13 ziptool

/home/chris/AudioSoftware/zip/include:
total 36
drwxr-xr-x 2 chris users  4096 Jan 25 10:14 .
drwxr-xr-x 6 chris users  4096 Jan 25 10:14 ..
-rw-r--r-- 1 chris users  3604 Jan 25 10:13 zipconf.h
-rw-r--r-- 1 chris users 22619 Dec 29 20:37 zip.h

/home/chris/AudioSoftware/zip/lib:
total 208
drwxr-xr-x 3 chris users   4096 Jan 25 10:14 .
drwxr-xr-x 6 chris users   4096 Jan 25 10:14 ..
lrwxrwxrwx 1 chris users     11 Jan 25 10:14 libzip.so -> libzip.so.5
lrwxrwxrwx 1 chris users     13 Jan 25 10:14 libzip.so.5 -> libzip.so.5.0
-rwxr-xr-x 1 chris users 200056 Jan 25 10:13 libzip.so.5.0
drwxr-xr-x 2 chris users   4096 Jan 25 10:14 pkgconfig
```
I wouldn't blame you to put this one in the "too hard/user setup" basket.

```
chris@linux-c4x2:[~]$>printenv|sort|nl
     1	ALSA_CONFIG_PATH=/etc/alsa-pulse.conf
     2	AUDIODRIVER=pulseaudio
     3	COLORTERM=1
     4	CONFIG_SITE=/usr/share/site/x86_64-unknown-linux-gnu
     5	CPU=x86_64
     6	CSHEDIT=emacs
     7	CVS_RSH=ssh
     8	DBUS_SESSION_BUS_ADDRESS=
     9	DESKTOP_SESSION=LXDE
    10	DISPLAY=:0.0
    11	DSSI_PATH=/home/chris/.dssi
    12	FROM_HEADER=
    13	FSTMENU_GTK=2
    14	G_BROKEN_FILENAMES=1
    15	G_FILENAME_ENCODING=@locale,UTF-8,ISO-8859-15,CP1252
    16	GPG_TTY=/dev/pts/0
    17	GTK_IM_MODULE=cedilla
    18	GTK_MODULES=canberra-gtk-module
    19	HISTSIZE=1000
    20	HOME=/home/chris
    21	HOST=linux-c4x2.suse
    22	HOSTNAME=linux-c4x2.suse
    23	HOSTTYPE=x86_64
    24	INPUTRC=/home/chris/.inputrc
    25	JAVA_BINDIR=/usr/lib64/jvm/jre/bin
    26	JAVA_HOME=/usr/lib64/jvm/jre
    27	JAVA_ROOT=/usr/lib64/jvm/jre
    28	JRE_HOME=/usr/lib64/jvm/jre
    29	LADSPA_PATH=/usr/lib64/ladspa:/usr/lib/ladspa
    30	LADSPA_RDF_PATH=/usr/share/ladspa/rdf
    31	LANG=en_US.UTF-8
    32	LESS_ADVANCED_PREPROCESSOR=no
    33	LESSCLOSE=lessclose.sh %s %s
    34	LESSKEY=/etc/lesskey.bin
    35	LESS=-M -I -R
    36	LESSOPEN=lessopen.sh %s
    37	LOGNAME=chris
    38	LS_COLORS=no=00:fi=00:di=01;34:ln=00;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=41;33;01:ex=00;32:*.cmd=00;32:*.exe=01;32:*.com=01;32:*.bat=01;32:*.btm=01;32:*.dll=01;32:*.tar=00;31:*.tbz=00;31:*.tgz=00;31:*.rpm=00;31:*.deb=00;31:*.arj=00;31:*.taz=00;31:*.lzh=00;31:*.lzma=00;31:*.zip=00;31:*.zoo=00;31:*.z=00;31:*.Z=00;31:*.gz=00;31:*.bz2=00;31:*.tb2=00;31:*.tz2=00;31:*.tbz2=00;31:*.xz=00;31:*.avi=01;35:*.bmp=01;35:*.fli=01;35:*.gif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mng=01;35:*.mov=01;35:*.mpg=01;35:*.pcx=01;35:*.pbm=01;35:*.pgm=01;35:*.png=01;35:*.ppm=01;35:*.tga=01;35:*.tif=01;35:*.xbm=01;35:*.xpm=01;35:*.dl=01;35:*.gl=01;35:*.wmv=01;35:*.aiff=00;32:*.au=00;32:*.mid=00;32:*.mp3=00;32:*.ogg=00;32:*.voc=00;32:*.wav=00;32:
    39	LS_OPTIONS=-N --color=tty -T 0
    40	LV2_PATH=/home/chris/.lv2:/usr/lib64/lv2:/usr/lib/lv2:/usr/local/lib64/lv2:/usr/local/lib/lv2
    41	_LXSESSION_PID=2449
    42	MACHTYPE=x86_64-suse-linux
    43	MAIL=/var/spool/mail/chris
    44	MANPATH=/home/chris/bin/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man
    45	MINICOM=-c on
    46	MORE=-sl
    47	NNTPSERVER=news
    48	OLDPWD=/home/chris/AudioSoftware/libzip-1.4.0/build
    49	OSTYPE=linux
    50	PAGER=less
    51	PATH=/home/chris/perl5/bin:/home/chris/perl5/bin:/home/chris/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games
    52	PERL5LIB=/home/chris/perl5/lib/perl5:/home/chris/perl5/lib/perl5
    53	PERL_LOCAL_LIB_ROOT=/home/chris/perl5:/home/chris/perl5
    54	PERL_MB_OPT=--install_base "/home/chris/perl5"
    55	PERL_MM_OPT=INSTALL_BASE=/home/chris/perl5
    56	PILOTPORT=usb:
    57	PROFILEREAD=true
    58	PS1=\e[1;33m\u@\h:[\w]\$>\e[m
    59	PWD=/home/chris
    60	PYTHONSTARTUP=/etc/pythonstart
    61	QEMU_AUDIO_DRV=pa
    62	QT_IM_MODULE=xim
    63	QT_IM_SWITCHER=imsw-multi
    64	QT_PLATFORM_PLUGIN=lxqt
    65	QT_QPA_PLATFORMTHEME=lxqt
    66	QT_SYSTEM_DIR=/usr/share/desktop-data
    67	RAWWAVE_PATH=/home/chris/Downloads/git/stk/rawwaves
    68	SAL_USE_VCLPLUGIN=gtk
    69	SDL_AUDIODRIVER=pulse
    70	SHELL=/bin/bash
    71	SHLVL=1
    72	SSH_AGENT_PID=2498
    73	SSH_ASKPASS=/usr/lib/ssh/ssh-askpass
    74	SSH_AUTH_SOCK=/tmp/ssh
    75	TERM=xterm
    76	USER=chris
    77	_=/usr/bin/printenv
    78	VDPAU_DRIVER=va_gl
    79	VST_PATH=/home/chris/.vst
    80	VSTSDK_DIR=/home/chris/MusicSoftware/VST3_SDK
    81	WINDOWMANAGER=/usr/bin/startlxde
    82	XAUTHLOCALHOSTNAME=linux-c4x2.suse
    83	XAUTHORITY=/home/chris/.Xauthority
    84	XCURSOR_THEME=DMZ
    85	XDG_CONFIG_DIRS=/etc/xdg
    86	XDG_CONFIG_HOME=/home/chris/.config
    87	XDG_CURRENT_DESKTOP=LXDE
    88	XDG_DATA_DIRS=/usr/share/gdm:/var/lib/menu-xdg:/usr/local/share:/usr/share
    89	XDG_MENU_PREFIX=lxde-
    90	XDG_RUNTIME_DIR=/run/user/1000
    91	XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
    92	XDG_SEAT=seat0
    93	XDG_SESSION_CLASS=user
    94	XDG_SESSION_DESKTOP=
    95	XDG_SESSION_ID=1
    96	XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
    97	XDG_SESSION_TYPE=x11
    98	XDG_VTNR=7
    99	XKEYSYMDB=/usr/X11R6/lib/X11/XKeysymDB
   100	XMODIFIERS=@im=local
   101	XNLSPATH=/usr/share/X11/nls
   102	XSESSION_IS_UP=yes
```

**Comment by therealkitman** [comment]
Hi Andrew,
I spent a few days looking at this (mostly becoming familiar with things). To answer your previous question about why x86_64 / lib64 builds are being created on my system - it's because my system in 64bit. And I assume most systems these days are 64bit so I would be scratching my head as how anyone could build the dependencies without some tinkering.

But I got a clue from your own comment and fix at lines 88 and 89 in `/dep/Makefile`.
```
87	$(MAKE) -C glew-2.1.0 glew.lib
88	# On Linux, default lib path is lib64, so change it back to lib.
89	$(MAKE) -C glew-2.1.0 GLEW_DEST="$(LOCAL)" LIBDIR="$(LOCAL)/lib" install
```
I repeated this process for the other dependencies - but building as default 64bit but using libdir parameter to store the resultant libraries in `/dep/lib`

With these libdir changes to `/dep/Makefile` VCVRack builds for me without issue as per your guide.

I don't know how to push changes to github but I have pasted the makefile here at [dep/Makefile](https://pastebin.com/7PeHnDci).

And that curl issue was due to libdirs as well. In your dep/Makefile you had the build for curl looking for the ssl at `--with-ssl="$(LOCAL)"` when it should have been `--with-ssl="$(LOCAL)/lib"`.

Now I can move forward twiddling knobs :)

**Comment by AndrewBelt** [comment]
>curl-7_56 cannot be built against openssl-1.1.0.

Can you provide a source of this claim?

**Comment by therealkitman** [comment]
The curl building is a bit of a non issue now that the --libdirs have been sorted in my `dep/MakeFile` for the libraries and headers. This was a mix up of having system installed libraries and the mish mash of 32/64bit dependency libraries built by `dep/MakeFile`.

But the original claim for it was [here](https://github.com/curl/curl/issues/1501) but is now irrelevant.

**Comment by AndrewBelt** [comment]
Closing since this issue is out of date. The dep Makefile has been rewritten in the `v0.6` branch.
