### ISSUE TITLE
PulseMatrix sequencers: minimum trigger voltage (CLK input)

### ISSUE THREAD

**Issue by DomiKamu** [VCVRack/Rack#637]
OS (if applicable): Windows 7 Pro SP1 x64 - French (not OS related)
Version (or "dev" if compiling from source): 0.5.1

Hi Andrew, I'm not sure it's the right place... Recently I've bought your PulseMatrix sequencers, and really I love them! (major weapons in my arsenal ;)

But for clock, I've used firstly "BPM Clock" module, by Autodafe: the sequence doesn't move. After short investigations, using Scope and another BPM Clock (AS) and an VCA (to control voltage of clock pulses), I've understood the **minimal** voltage to trigger (via CLK input) is **2.01 V**. But in VCV Voltage Standards page, it's mentioned "For example, Audible Instruments modules are triggered once the input reaches 1.7V..." but PulseMatrix sequencers are triggered at 2.01+ V, it's not clear in my mind to be honest.

If you've a little time (I can imagine you're very busy), you'll can check [this issue reported to Autodafe](https://github.com/antoniograzioli/Autodafe/issues/16) because his BPM Clock module sends only +1 V it's not enough - but he've replied this will to be fixed for next Rack release (good news).

**Comment by AndrewBelt** [comment]
This is the right place.

Pulse Matrix is triggered at 2V, so it is within the range specified by the Voltage Standard document. All trigger sources should be at least 5V, so this should be changed by the noncompliant modules.

**Comment by DomiKamu** [comment]
Not at 2 V (the sequencer doesn't run at 2.00V) but it runs at... 2.01 V. 
I've used Fundamentals VCA (to control voltage, because AS BPM Clock sends 10 V) and Scope (to check the voltage behind the VCA and to find the threshold). 
I'll can post a video on YT if you want a proof. 

----- Mail original -----

De: "Andrew Belt" <notifications@github.com> 
À: "VCVRack/Rack" <Rack@noreply.github.com> 
Cc: "DomiKamu" <docam@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Lundi 22 Janvier 2018 21:03:50 
Objet: Re: [VCVRack/Rack] PulseMatrix sequencers: minimum trigger voltage (CLK input) (#637) 


This is the right place. 
Pulse Matrix is triggered at 2V, so it is within the range specified by the Voltage Standard document. All trigger sources should be at least 5V, so this should be changed by the noncompliant modules.

**Comment by AndrewBelt** [comment]
You might be trying to send a 1.9999V signal for example into the Pulse Matrix, which would not trigger but display as "2.00V" after rounding on the Fundamental Scope.

Regardless of whether it's 2V or 2.01V, it should still be triggered by a 5V trigger source.

**Comment by AScustomWorks** [comment]
"AS BPM Clock sends 10 V)", indeed, JW clock does the same if I recall correctly. I made it this way because someone pointed out exactly this issue and it's easier to send 10V than trying to find out which modules don't play play the book and tell the developers. I bet by V1 most of the modules will be compliant to the standard though.

**Comment by DomiKamu** [comment]
Of course, I understand it's displayed 2.00 V on Scope but real value can be 1.99999 V (before rounded) => nice explanation! 

Also, I agree the module developers must stay into Voltage Standards (as I've said to Autodafe). 

Sorry also, I've wrote "PulseMatrix" instead of... "Pulse Matrix" ;) 

Thanks a million about your stuff around your fantastic VCV Rack and modules such Pulse Matrix! 

Regards, 
Dominique CAMUS 
Chartres, France 

----- Mail original -----

De: "Andrew Belt" <notifications@github.com> 
À: "VCVRack/Rack" <Rack@noreply.github.com> 
Cc: "DomiKamu" <docam@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mardi 23 Janvier 2018 00:06:33 
Objet: Re: [VCVRack/Rack] PulseMatrix sequencers: minimum trigger voltage (CLK input) (#637) 


You might be trying to send a 1.9999V signal for example into the Pulse Matrix, which would not trigger but display as "2.00V" after rounding on the Fundamental Scope. 
Regardless of whether it's 2V or 2.01V, it should still be triggered by a 5V trigger source.

**Comment by DomiKamu** [comment]
@AScustomWorks Freddy, I confirm JW's Simple Clock sends 10 V, too, you're right! Bravo for your modules, loving them!
