### ISSUE TITLE
Assertion Failed! File: src/gui.cpp, Line: 358

### ISSUE THREAD

**Issue by markireland** [VCVRack/Rack#640]
OS (if applicable): win 7 64bit
Version (or "dev" if compiling from source): 0.5.1
![vcv_dead](https://user-images.githubusercontent.com/39683/35259404-784ee090-0051-11e8-82ca-8d864ac585b8.png)

**Comment by LKHSogpit** [comment]
Do you have openGL 2. Try updating your GPU which should include the latest openGL.

**Comment by AndrewBelt** [comment]
Hmm, it's unusual that the renderer got past the OpenGL version check but failed when creating the NanoVG context. No idea what would cause that.

**Comment by squinkylabs** [comment]
Are assertions enabled in all builds of VCVRack?

**Comment by AndrewBelt** [comment]
@squinkylabs Yes.

**Comment by buddard** [comment]
I'm getting exactly this error when trying to run VCVRack on Windows 7 in Virtualbox on macOS Sierra. According to GLView, I have OpenGL 2.1 Chromium 1 installed. Is something more required to run Rack?

**Comment by markireland** [comment]
This same error is causing other problems with my laptop. My card is an old Radeon HD 6770M. When some other programs check for OpenGL version they crash (Steam) AndrewBelt

**Comment by squinkylabs** [comment]
tx! unfortunately I googled the info, and hit the wiki. I'll use the manual ;-)

**Comment by AndrewBelt** [comment]
Closing as obsolete issue.
