### ISSUE TITLE
trivial omission in readme

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#641]
OS (if applicable): Debian 16

"With your distro's package manager, make sure you have installed gcc, make, cmake, tar, and unzip"

(obviously you need git, too)

**Comment by GiveMeAnthony** [comment]
I'm not sure that git is technically necessary since users could download the repository and any submodules in a zip file.

**Comment by squinkylabs** [comment]
not to be pedantic, but git is absolutely necessary if you want to follow the posted instructions.

**Comment by AndrewBelt** [comment]
Added a while ago, closing.
