### ISSUE TITLE
my vcv rack is giving me this error on only one of my devices

### ISSUE THREAD

**Issue by vcvrackproblem** [VCVRack/Rack#643]
![image](https://user-images.githubusercontent.com/35747029/35304202-4d62ac28-005a-11e8-94f1-7ab6f493626e.png)
i have tried the program on multiple devices and functioned properly

**Comment by AndrewBelt** [comment]
I responded to your email, no need to double-post.

**Comment by AndrewBelt** [comment]
Hmm, the mailserver rejected my email... weird.

What is your GPU?

**Comment by vcvrackproblem** [comment]
how do i check that

**Comment by vcvrackproblem** [comment]
probs because its a school email

**Comment by AndrewBelt** [comment]
One of these methods would work. http://www.rushinformation.com/how-to-find-your-graphics-card-details-windows-78xpvista/
Or, you can perhaps use the System Information in Control Panel (forgot what it's called.)

**Comment by vcvrackproblem** [comment]
![image](https://user-images.githubusercontent.com/35747029/35304924-0dd9b850-005d-11e8-8cdc-aa64b9cf41ff.png)

**Comment by AndrewBelt** [comment]
Intel HD does have some problems (especially if it's HD 3000). But if it was a GPU problem, you'd probably see a different message, so I'm going to guess it's some restriction imposed by software running on the OS.

**Comment by vcvrackproblem** [comment]
and that means
?

**Comment by AndrewBelt** [comment]
Not sure. You're probably out of luck for now unless you have a different computer.

**Comment by vcvrackproblem** [comment]
it was working before

**Comment by AndrewBelt** [comment]
Oh, didn't realize that. Try deleting the autosave.vcv file in `My Documents/Rack/`

**Comment by vcvrackproblem** [comment]
i have it on a usb stick

**Comment by AndrewBelt** [comment]
Yup, and it creates a file in the location I specified on launch.

**Comment by vcvrackproblem** [comment]
![image](https://user-images.githubusercontent.com/35747029/35305389-c25d56b4-005e-11e8-99cc-18304f55ec88.png)

**Comment by AndrewBelt** [comment]
Did you delete the file in `My Documents/Rack/`?

**Comment by vcvrackproblem** [comment]
now i did

**Comment by vcvrackproblem** [comment]
thank you it is working now

**Comment by vcvrackproblem** [comment]
but when i tried to open a saved rack it failed

**Comment by vcvrackproblem** [comment]
and when i try to hook my speakers up via the audio interface

**Comment by vcvrackproblem** [comment]
now it is giving me the error when ever it opens

**Comment by vcvrackproblem** [comment]
it recreated the file

**Comment by Uriel-A** [comment]
Try opening the problematic patch using notepad and modify all the "device" field to:
`        "device": -1,`
Save it and then try opening the patch in VCV again.

**Comment by Cris--** [comment]
Here an OpenGL fix for old Intel HD cards with black windows (eg Ueberschall Elastik 3) or an error here on Rack. For me with a HD3000 in a Thinkpad L520 with original Intel driver version 9.17.10.4459 the patch do the job and i can start Rack or other OpenGL apps now! Some driver file gets patched, some not but it works. YEAH!

**Comment by vcvrackproblem** [comment]
It’s working for me now

**Comment by 4lph4i** [comment]
yo guys i found a solution just follow the steps in the video... https://www.youtube.com/watch?v=Yqe5cgthZH4
