### ISSUE TITLE
Feature request: shortcut to load same developer modules on module contextual menu

### ISSUE THREAD

**Issue by AScustomWorks** [VCVRack/Rack#645]
Thought about this when tried to add a new module to the rack but clicked over a module instead of an  empty space:

Say you have  some modules from developers A (module 1), B (module 5) and M (module 3) already open.
You are working on module 1 from developer A, and now you want to add module 2 from developer M.

So, how about adding a shortcut list (same dev modules) on the module contextual menu, something like this:
![add-module](https://user-images.githubusercontent.com/34798768/35322616-83f27902-00b0-11e8-82b7-2d55608115e5.jpg)

An alternative and fast way to add modules from the same developers you already have on the rack.

**Comment by LKHSogpit** [comment]
Although a nice idea I think it is unnecessary to show this in the context menu. But It might make a nice custom menu if ever that was available. You can search for Fundamental in the add context menu or fund and it will show the fundamental folder. Context on a device should be for that device having a long list is not needed but perhaps just the fundamental folder where you mouse over and then it show would be a better idea.

**Comment by AndrewBelt** [comment]
This doesn't belong in the module context menu.
