### ISSUE TITLE
Bug: Window size should not depend on screen density

### ISSUE THREAD

**Issue by MovGP0** [VCVRack/Rack#646]
OS (if applicable): Windows 10
Version (or "dev" if compiling from source): 0.5.1

The size of the VCV Rack Window highly depends on the screen density, but should be device independent. 

Ie. when there are two monitors of the same (diagonal) size, one with a higher resolution than the other, the application will render in a different size on each monitor. That is because VCV Rack renders everything by the number of pixels, but that method doesn't work with modern high-res displays. 

Instead of rendering everything as pixels, the rendering should be based on DIP (device independent pixels), which are not only based on the DPI of the monitor, but also on the distance the monitor is away from the user (ie. an image from a beamer is typically farther away than a notebook screen). 

See also: 
* [MSDN reference on DIPs](https://msdn.microsoft.com/en-us/library/windows/desktop/ff684173(v=vs.85).aspx).

**Comment by AndrewBelt** [comment]
I believe this is fixed in master. Reopen if I'm wrong.
