### ISSUE TITLE
no such fle direcory error when runnng "make dep"

### ISSUE THREAD

**Issue by tommyryan20000** [VCVRack/Rack#648]
OS (if applicable): OSX 10.12.6
Version (or "dev" if compiling from source): dev
when ran code it says 
```
/Library/Developer/CommandLineTools/usr/bin/make -C dep
wget -nc https://github.com/nigels-com/glew/releases/download/glew-2.1.0/glew-2.1.0.tgz
make[1]: wget: No such file or directory
make[1]: *** [lib/libGLEW.dylib] Error 1
make: *** [dep] Error 2

```

**Comment by AndrewBelt** [comment]
Install `wget` with brew. I think I was going to switch to curl, but I must have forgotten.

**Comment by tommyryan20000** [comment]
i managed to fix it by installing wget with brew, then linking wget with `brew link wget`, but first i had to `brew link libidn2` and `brew link libunistring`. then i reinstalled cmake with  `brew install cmake`, worked fine after that.
