### ISSUE TITLE
Better Blendish UI theme

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/Rack#649]
Ste Holmes​ has contributed a Blendish theme which I like better than the current Blender UI theme and could inspire a three-color theme system.

![text10467](https://user-images.githubusercontent.com/338179/35465874-4833d57c-02cd-11e8-8f2f-6861a5b5eb35.png)

Requires
- Color functions #included by widget.hpp and gui.hpp
- `guiSetTheme(NVGcolor shadow, NVGcolor midtone, NVGcolor highlight)` function which builds a BNDtheme
- #565 for selecting them
- settings serialize/deserialize three colors

**Comment by squinkylabs** [comment]
I'm wondering how modules relate to the theme. It looks like maybe some of the stock widgets (text fields and menu items) follow the theme? Any plans to expose the theme directly to plugins? Don't know how many people would care about that. For me I'd just as soon have my UI look more or less like the stock stuff.

**Comment by AndrewBelt** [comment]
The theme is global and will be set by a toolbar icon+dropdown. It will also change the rack and rail background color.
There is no purpose to expose them to plugins (although because of the "open" nature of the Rack API, plugins *do* have access to changing the global theme).

**Comment by squinkylabs** [comment]
How do plugins get access to code in rack? I didn't think a dll could link back to an executable.

**Comment by squinkylabs** [comment]
oh - and why would there be no purpose to expose to plugs? I'd like to use the same shade of grey on my background as everyone else. I know that's not how physical modules work, of course.

**Comment by AndrewBelt** [comment]
>I didn't think a dll could link back to an executable.

I don't think it's possible for a DLL *not* to link back to an executable when it's `dlopen()`d or `LoadLibrary()`d. That's how everything works in Rack. Your plugin is loaded, and Rack searches and calls one function, `init()`, and everything that follows are calls to the Rack API.

Since the Rack API is fully open to plugins with no encapsulation, you can call something like `bndGetTheme()->backgroundColor` to get access to the current theme's background color. However, for consistency with other plugins, I would encourage you to only use one of the two colors defined at the bottom of `componentlibrary.hpp`: `LightPanel` or `DarkPanel`.

**Comment by squinkylabs** [comment]
ah, tx. well, I'll hack around and try it. tx!

**Comment by AndrewBelt** [comment]
New color scheme implemented in Rack 0.6. Closing.
