### ISSUE TITLE
slowdowns on win7

### ISSUE THREAD

**Issue by gagaexmachina** [VCVRack/Rack#656]
OS (if applicable): win 7
Version (or "dev" if compiling from source): master

I encountered  many glitches with the official release, so I build vcv from master branch following instructions on readme.md to try latest changes. 

With this version Audio output is smoother, but I still have the same slowdowns affecting all the system (eg task manager freezes with cpu spikes).
Troubles are appearing when I put more than approximately 20 modules, CPU average is about 20% with many spikes to 100% on every cores (i7 4930K).

Troubles could disappear if vcv window is minimized, so it feels like it could be related to display and that is why I am posting this issue, even if I know you are already working on CPU issues...

**Comment by gagaexmachina** [comment]
I tried latest build for an hour with one of my biggest files, without any glitch or slowdown.

No more spikes, CPU usage seems stable. I can open Firefox or a 3d software and audio keeps running perfectly.

I tried only an hour, and I'm going to do more tests. But I think this issue could be closed.
Thank you, thank you, and thank you!

**Comment by AndrewBelt** [comment]
Unfortunately I only accept concrete performance issues on this forum. This is quite abstract. See https://vcvrack.com/manual/FAQ.html
