### ISSUE TITLE
Can't record Rack output on Ubuntu 16.04

### ISSUE THREAD

**Issue by CaesuraMedia** [VCVRack/Rack#657]
OS (if applicable): Ubuntu 16.04 64bit
Version (or "dev" if compiling from source): 0.5.1 / dev and .zip

Hello : does anyone know how to record Rack in Ardour, Audacity or the sound recorder that comes with Ubuntu?  Or anything else?

I have done it before (there were Ardour outputs on the Audio Device selection of the Core Audio Interface when Ardour was running), but that no longer works, and I haven't keep older versions of Rack, doh.

If I try to select an audio interface on Rack and the same one on other apps then i get conflict errors, not surprisingly I suppose.

Any ideas?
Cheers,
Andy

**Comment by CaesuraMedia** [comment]
Hello - in case anyone is wondering - on Ubuntu 16.04 I did this : https://github.com/VCVRack/Rack/wiki/Add-Support-for-Jack-on-Linux-(dev) and I can now see i/o from Rack, Jack and Ardour.

`cd dep/rtaudio
make clean
./autogen.sh
./configure --with-jack --with-alsa
make
cp -a .libs/librtaudio.so* ../lib/
cd ../../
make`

All good.
~a~

**Comment by modlfo** [comment]
Closing this issue. Audio related problems in Linux will be covered in #1317
