### ISSUE TITLE
Is there a way to quit without saving?

### ISSUE THREAD

**Issue by pjc123** [VCVRack/Rack#658]
OS (if applicable): Windows 10 Pro 64 bit
Version (or "dev" if compiling from source): 0.5.1

Maybe I am missing something.  How the heck do I exit the program without saving my changes? Both the "Quit" and "X" exit the program and auto-save my current setup, but many times I am just experimenting or I made a mistake and don't want to save what I did.  The only workaround I have come up with is to save it as a new file, then go into the file system and then delete it, which is pretty ridiculous.  Thanks.

**Comment by AndrewBelt** [comment]
Just hit Ctrl+N or File > New when you want to start from scratch.

**Comment by pjc123** [comment]
I kinda figured that was the only other way.  Thanks.
