### ISSUE TITLE
glfw problem in ubuntustudio 

### ISSUE THREAD

**Issue by Malifick** [VCVRack/Rack#66]
make
g++ -Iinclude -Idep/include -Idep/lib/libzip/include -DVERSION=dev -MMD -O3 -march=core2 -ffast-math -g -Wall -DARCH_LIN -std=c++11 -c -o build/src/gui.cpp.o src/gui.cpp
src/gui.cpp: In function ‘void rack::guiInit()’:
src/gui.cpp:237:17: error: ‘GLFW_MAXIMIZED’ was not declared in this scope
  glfwWindowHint(GLFW_MAXIMIZED, GLFW_TRUE);
                 ^
src/gui.cpp:237:33: error: ‘GLFW_TRUE’ was not declared in this scope
  glfwWindowHint(GLFW_MAXIMIZED, GLFW_TRUE);
                                 ^
src/gui.cpp:264:75: error: ‘glfwSetWindowSizeLimits’ was not declared in this scope
  glfwSetWindowSizeLimits(gWindow, 640, 480, GLFW_DONT_CARE, GLFW_DONT_CARE);
                                                                           ^
compile.mk:46: recipe for target 'build/src/gui.cpp.o' failed
make: *** [build/src/gui.cpp.o] Error 1

**Comment by AndrewBelt** [comment]
Maybe you're using an old version of GLFW. Build the correct one with `cd dep; make`.

**Comment by Malifick** [comment]
Ok, fixed that issue. now I have another one  with dsp . 
make
g++ -Iinclude -Idep/include -Idep/lib/libzip/include -DVERSION=dev -MMD -O3 -march=core2 -ffast-math -g -Wall -DARCH_LIN -std=c++11 -c -o build/src/dsp.cpp.o src/dsp.cpp
In file included from include/dsp.hpp:7:0,
                 from src/dsp.cpp:1:
include/math.hpp: In member function ‘bool rack::Vec::isFinite()’:
include/math.hpp:185:20: error: ‘isfinite’ was not declared in this scope
   return isfinite(x) && isfinite(y);
                    ^
include/math.hpp:185:20: note: suggested alternative:
In file included from /usr/include/c++/5/complex:44:0,
                 from include/dsp.hpp:6,
                 from src/dsp.cpp:1:
/usr/include/c++/5/cmath:601:5: note:   ‘std::isfinite’
     isfinite(_Tp __x)
     ^
compile.mk:46: recipe for target 'build/src/dsp.cpp.o' failed
make: *** [build/src/dsp.cpp.o] Error 1

**Comment by Malifick** [comment]
Running Ubuntustudio 4.10.0-33-lowlatency

**Comment by AndrewBelt** [comment]
Should be fixed now.
