### ISSUE TITLE
[Feature Request] Shove edit / sliding nuts

### ISSUE THREAD

**Issue by gbrandt1** [VCVRack/Rack#661]
sorry if this was already rejected ... but i would like to bring shove edit up again.
have a menu item for "threaded strips" (current behaviour when moving modules with skipping
existing ones when moving another) 
vs. "sliding nuts" (shove ) - move modules as much as possible out of the way 
instead of skipping them.

**Comment by AndrewBelt** [comment]
Duplicate of https://github.com/VCVRack/Rack/issues/307?

**Comment by gbrandt1** [comment]
yes. i found that thread but what unsure what the conclusion was?

**Comment by AndrewBelt** [comment]
No conclusion yet, still in the design phase.

**Comment by gbrandt1** [comment]
cool. closing
