### ISSUE TITLE
fresh compile off of master having issues with gfx

### ISSUE THREAD

**Issue by JerrySievert** [VCVRack/Rack#662]
OS (if applicable): 10.13.4
Version (or "dev" if compiling from source): master

after working through other dependency download and compilation issues, rack and other visual glitches occur:

<img width="466" alt="screen shot 2018-01-30 at 12 08 31 pm" src="https://user-images.githubusercontent.com/471270/35588804-93a5c740-05b6-11e8-9c15-f59c81f00626.png">

run occurred via `make run`

**Comment by modlfo** [comment]
Closing this issue since it has been most likely fixed since this issue was created.
