### ISSUE TITLE
Chord generator

### ISSUE THREAD

**Issue by tecnologiemusicali** [VCVRack/Rack#663]
OS (if applicable): 10.13
Version (or "dev" if compiling from source): 0.5.1

Hi everybody, I need help to create a patch with a sequence of chords. Can someone help with an example patch? I have installed almost all the plugin libraries.
Many thanks,
G

**Comment by antoniotuzzi** [comment]
you should ask into the FB user group (is more an "how to patch" question)

you need a sequencer able to send more voltages for every single step (many SQUONK for example)
or use more sequencer with single CV, but all in sync

**Comment by gbrandt1** [comment]
yeah move to the fb group. other than that Amalgamated Harmonics Progress does chord progressions.

**Comment by tecnologiemusicali** [comment]
Now I have a good reason to create a Facebook account! 😀

Il 31 gen 2018 17:22, "gbrandt1" <notifications@github.com> ha scritto:
