### ISSUE TITLE
Names, units, and display types for ParamWidgets

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/Rack#664]
Will be used in a tooltip when hovering over a knob with tooltips enabled, or in #349.

The actual label data should be owned by the knob, not the Module's Param (since the data accessed by the Rack engine thread should only be low-level data, not human readable information).

Some examples of labels made available by this feature:

- Fundamental VCO Coarse Pitch: 440.00 Hz
- Fundamental SEQ3 Row 1 Step 7: 5.500 V
- Audible Instruments Modal Synthesizer Reverb: 0.123
- Fundamental LFO Pulse Width: 50.00%

Display types would include hard-coded modes that process the number and have known inverses:
- Identity/none
- Log
- Percent: would append '%' before the unit

**Comment by squinkylabs** [comment]
It's a great idea. 

This isn't as compelling, but how about tooltips for inputs and outputs, too?

**Comment by AndrewBelt** [comment]
Could also be possible, I'll add that.

**Comment by BBasile** [comment]
This is a must have. Also maybe an input box to set a knob to a particular value when the mouse isn't accurate enough to reach this value (or maybe CTRL + mouse as seen sometimes to get more accurate control).

**Comment by squinkylabs** [comment]
Would the input box be on screen all the time? If so, devs can (and do) already do this themselves. If just in the tooltip it sounds very difficult to use.

**Comment by BBasile** [comment]
No not related to the tooltip , the idea is more right click, `set Value ...` menu item, then dialog, ok / cancel. Maybe this should go in a separate issue.

**Comment by AndrewBelt** [comment]
Added to `Param` in the last few commits.
