### ISSUE TITLE
Steps at double-speed if no audio device selected

### ISSUE THREAD

**Issue by dhemery** [VCVRack/Rack#665]
OS (if applicable): MacOS 10.13.3 (iMac Retina 5K Late 2015 AND MacBook Retina 12" Early 2015)
Version (or "dev" if compiling from source): v0.5.1 (both downloaded binaries AND dev)

The engine appears to step at double the specified rate if no audio device is attached.

To reproduce this:

1. In a new Rack, add a Fundamental LFO-1, a Fundamental Scope, and a Core Audio Interface.
1. Select an Audio Device in the Audio Interface.
1. Connect the LFO-1 saw output to the scope. Leave all LFO-1 parameters at their initial settings.
1. Observe the cycle frequency in the scope.
1. Select "No Device" in the Audio Interface.
1. Observe that the cycle frequency has doubled.
 
Admittedly, "No Device" is **spectacularly atypical usage.** But while I was developing my first module (an envelope generator), I tested it without an audio device, using only the scope. The timing seemed off by a factor of two. I was certain that I had done the math wrong, and added a fudge factor to divide my durations by two (or multiply them by two—I forget which).

Later, when I attached my envelope generator to a filter to make some sounds, all of the durations were half of what I had come to expect.

On further investigation, I discovered that the reported engine step time was correct when an audio device is selected, and off by a factor of two when no audio device is selected.

**Comment by AndrewBelt** [comment]
That is correct, it steps at exactly 2.0x speed when nothing in the engine loop is blocking. There is no way to determine if a blocking module exists in the rack, so Rack uses the logic "if the loop is going too fast for 1 second, block for 0.5s."

I could experiment with a block time of 1.0s if I remember this issue, but I'm nervous about stability.

**Comment by LKHSogpit** [comment]
@AndrewBelt If it ain't broke don't fix it!

**Comment by dhemery** [comment]
@AndrewBelt Lacking the technical understanding of the engine, I can’t follow your explanation. The gist seems to be: It’s deliberate (for now).

S’okay.

I can’t think of a reasonable way to alert the very few people this will affect. (Perhaps only one person will be affected, and he’s now been alerted.)
