### ISSUE TITLE
Sound card presented as many incomplete soundscards

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#668]
OS (if applicable): Windows 7
Version (or "dev" if compiling from source): dev

I have an older sound card - maudio delta 66. It shows up in the Audio Interface module as a bunch of separate cards, some with two inputs, some with two outputs. In reality it's a 6 in 6 out device, I think the illustration will show this better:
![image](https://user-images.githubusercontent.com/16314838/35688305-bb915920-0725-11e8-8472-716ee923c771.png)

**Comment by AndrewBelt** [comment]
Can't fix. This is what WASAPI reports, so this is an issue with Windows.

**Comment by squinkylabs** [comment]
Interestingly, the pre-build one that I downloaded (.51) works fine, and shows a single multi-channel sound card. But the one I built from source (which otherwise works fine) does have this issue.
