### ISSUE TITLE
better assert behavior

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#669]
OS (if applicable): Windows
Version (or "dev" if compiling from source): Dev

I've seen screen shots on the user's group of asserts that pop up a modal dialog on top of VCVRack. My asserts just print to the console and exit.

My question - did someone do something special to make asserts show the user a dialog? Or is that perhaps just a platform thing? I thought maybe VCVRack had its own version of assert, but I looked around and see that #include <assert.h> is what everyone does.

**Comment by AndrewBelt** [comment]
No, when compiled with `-mwindows` and launched outside of a terminal, Windows handles `assert()` by opening a dialog box with the message. Mac does something similar, by trapping the signal, closing the application, and opening a "Report to Apple" dialog box which allows you to see the stack trace.
