### ISSUE TITLE
Add text position coordinates to widgets

### ISSUE THREAD

**Issue by LKHSogpit** [VCVRack/Rack#672]
OS (if applicable):all
Version (or "dev" if compiling from source):dev

x + y positions on modules to deduct Inkscape co-ordinates when adding parameters and ports. the y position is easy to get >(Vec(_x_, 380 - _y_) but the x position if you have any rotation on imperfect squares e.g. hex ports will be off. If the positions were displayed in the dev version you could offset the x and y easily. If the x is off but you just mouse to the part of the module where you want the port/knob button whatever to be. >(Vec(x ±offset, 380 -y). (+ if its more - if less) or >(Vec(90! - x, 380 -y) !6HP

Niche but will save a lot time for everyone.

**Comment by AndrewBelt** [comment]
Rack is open source, so you can add this to SVGKnob or whatever you need yourself. I don't want this feature in Rack though, since there are better ways to do it.
