### ISSUE TITLE
Request: Clock Modulator

### ISSUE THREAD

**Issue by Phal-anx** [VCVRack/Rack#673]
OS (if applicable): all
Version (or "dev" if compiling from source):dev

there is no proper TAG for all the existing clock multipliers/dividers beside of the CLOCK_TAG. I saw on modulargrid that we could make use of an additional tag called CLOCK_MODULATOR_TAG

@AndrewBelt  what are your thoughts on that?

**Comment by AndrewBelt** [comment]
Added in 450b255
