### ISSUE TITLE
WASAPI works in .51 download, not in dev

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#677]
OS (if applicable): Window 7
Version (or "dev" if compiling from source): .51 vs. dev

You quite reasonably closed this one before as "it's windows, not me". Quite reasonable, but I just discovered that it works fine in the downloaded on, but the one I build (which otherwise works fine) has the crazy driver list. I've enclosed two screen shots, one good and one bad. 
![audio](https://user-images.githubusercontent.com/16314838/35769127-33768406-08bb-11e8-9784-f41625e3aebf.png)
![audio_51](https://user-images.githubusercontent.com/16314838/35769129-3c4704a2-08bb-11e8-9039-984c6129f805.png)

**Comment by AndrewBelt** [comment]
WASAPI and ASIO devices may be different.

**Comment by squinkylabs** [comment]
Good point. Didn't notice that because the dev one has no ASIO! But you are correct - in .51 the WASAPI drivers show the same "whack" behavior. Here's my driver list in dev:
![no_asio](https://user-images.githubusercontent.com/16314838/35769260-14dc0226-08bd-11e8-90df-4009b10f6ea7.png)

**Comment by squinkylabs** [comment]
maybe running it with `make run` loads some dlls differently?

**Comment by AndrewBelt** [comment]
rtaudio must be compiled with `make RTAUDIO_ALL_APIS=1` in the dep/ directory if you want the APIs which I do not support for source-builds. The fact that ASIO is included in rtaudio at all is legally sketchy.

**Comment by squinkylabs** [comment]
ah, ok. tx!
