### ISSUE TITLE
Accessibility: Using VCV Rack with a Screen Reader

### ISSUE THREAD

**Issue by jcourt01** [VCVRack/Rack#679]
Hello,
    just wanted to provide some feedback.  I'm a visually impaired developer who is most comfortable using a screen reader. (VoiceOver on Mac.)  I downloaded VCV rack to try it out and none of the UI components are accessible.  It is impossible for a blind person to use this project.  It looks like VCV rack uses a cross-platform GUI toolkit.  I di  a little searching but I found references to gluw which looks like it is for rendering the graphics.  Which toolkit does VCV rack use?  There are some like wxWidgets or Qt which have accessibility support.  I saw another issue where text labels are being added.  This sounds good!  Maybe there is a way VCV rack can make its UI aware to screen readers?

Thanks, this projects sounds pretty cool.

**Comment by AndrewBelt** [comment]
VCV Rack is like a video game and thus has the same screen reader support as any other video game using OpenGL, i.e. none.
