### ISSUE TITLE
Feature Request: "Preset or "Patch" Manager (versions of racks)

### ISSUE THREAD

**Issue by glitched01** [VCVRack/Rack#684]
I love this program! I can't tell you how many hours I've lost inside it.

Anyway, I have lots and lots of .VCV files which are usually versions of a main rack configuration (same modules, just different connections or parameter values.)

It might make sense to have a "patches" or "presets" manager, so we don't end up having 15 VCV files named like, "CloudsGlitchFun01_ChangedLFO1a remix."

A "patch" would be defined as the set of parameters, patch-connections, module layout (locations); basically, everything that could change in a rack, without adding or removing modules. These patches should be able to be named by the user and appear in a dropdown box.

(Perhaps the "notes" module could be considered one of the only modules that could be added/removed from a "patch" preset.)

As far as back-end specifications, this could be achieved in a number of ways; perhaps the versions could be integrated into the main .VCV file or maybe each rack has a companion "patches" file. 

There seems to be enough room on the menu bar for another dropdown box, which is where this feature could go.

Thanks!

-d

**Comment by AndrewBelt** [comment]
I'll vote no to your exact suggestion.
Multiple versions embedded in the same patch file have been recommended, but I don't think I'll go with that either, although it will be more likely than this.
I will also add a feature after #565 to clear all cables from the rack, leaving you with an unpatched modular. (The least fun thing about Eurorack is clearing your patch by carefully ripping out all the cables IMO.)
