### ISSUE TITLE
Continuous encoder

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/Rack#687]
Need to fix `initialize()`, `reset()`, and `randomize()` methods of a knob when the bounds are set to infinity.

**Comment by DomiKamu** [comment]
Be sure this feature will be great for v0.6.0.

**Comment by MarcBoule** [comment]
Referencing #522 here for completion and to avoid posting my question in two different places (since I believe it is the same topic)

**Comment by AndrewBelt** [comment]
Fixed with ac0ed65
