### ISSUE TITLE
VCV(0.3.1)  Audio device menu jitter Win 7 

### ISSUE THREAD

**Issue by JoeSleaze** [VCVRack/Rack#69]

**Comment by AndrewBelt** [comment]
Last night I uploaded a hotfix since the build was incorrect on Windows. Could you try downloading it again and reporting if it's fixed?

**Comment by JoeSleaze** [comment]
The hotfix works like a charm, i still can´t choose more than 1 output for my soundcard though, while i supposed to have 4 of them only one output generates sound at the moment.
