### ISSUE TITLE
Discussion: Hook for module initialization

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#690]
My module has an `init()` function that initializes internal state from the settings saved to the patch file before the step function runs. It is only run once at module startup (or when the module is reinitialized).

Currently, I have put a one-shot at the top of the `step()` function to make this work. 

Something like this:
```
void step() {
    if (!inited_) {
        init();
        inited_ = true;
    }
[...]
```

If I put `init()` in the module constructor, the parameters have not been read from the patch file yet.
For the re-init, I can use the `onReset()` hook to set `inited_` to `false` and reinitialized on the next step.

Am I missing a hook that I could use for the initialization on startup that is executed after the parameters are available? Would a hook like `onInit()` make sense? 

Timing-wise, I would think for it to be called right after `moduleWidget->fromJson(moduleJ)` in `RackWidget()` (l.273).

**Comment by AndrewBelt** [comment]
Initialization *after* JSON is unserialized is not initialization. The procedure is to initialize your module and then modify its state if needed by the fromJson() module. If you state your use case, I can suggest how to make it fit into this procedure.

**Comment by squinkylabs** [comment]
If you do it all on the first call to step() you are almost guaranteed to generate a big "pop".

**Comment by cschol** [comment]
OK. I defined "initialization" to be everything up until right before `step()`. I added my `init()` call at the end of the `fromJson()` hook and it works as expected. I knew I was missing something here. 

It may be worth it to add a few sentences about the procedure and serialization in the [Plugin Development Tutorial](https://vcvrack.com/manual/PluginDevelopmentTutorial.html). 

@squinkylabs Because it might blow the sample rate? I tested that and it didn't seem to be causing any issues, but definitely a good point and something to look out for.

**Comment by AndrewBelt** [comment]
Depends on how long the initialization takes. If much less than 1ms, you're fine.

**Comment by squinkylabs** [comment]
I agree it would be nice to document the processing model as far as threads and deadlines go. I have a follow up question to this post - which non-engine threads might get interrupted by the engine thread? Is it possible that a call to step can occur before fromJson completes?

@cschol Yeah, thinking if your first step call took tens or hundreds of milliseconds it would definitely cause an audio buffer underflow, and presumably a pop.

**Comment by AndrewBelt** [comment]
>which non-engine threads might get interrupted by the engine thread?

No threads interrupt any other thread.

>Is it possible that a call to step can occur before fromJson completes?

No. Even when cloning for example, `fromJson()` is called by the main thread before the module is added to the rack, which causes `step()` to be called.

**Comment by squinkylabs** [comment]
well, that makes things easier! nice.

**Comment by AndrewBelt** [comment]
I'm not sure of a use case for this feature. If you need to run code upon module initialization, do it in the constructor. If you need to run code when deserializing JSON, do it in `dataFromJson()`.
