### ISSUE TITLE
Add `create()` static methods to various Widget subclasses

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/Rack#692]
For convenience when creating Widgets. Ref https://github.com/VCVRack/Rack/issues/595#issuecomment-364364347

**Comment by squinkylabs** [comment]
Great idea. Will there be a guarantee that no other threads enter a module for the duration? Either way is fine with me.

**Comment by AndrewBelt** [comment]
Did you mean to post that question to a different issue? Calling this function just creates an object from scratch, no need to worry about thread safety.

**Comment by squinkylabs** [comment]
oh - I misunderstood! I misread this as a new entry point to the module, where VCVRack would call plugin->create(). Where this call would mean "ok, plugin, you've been instantiated, your json has been parsed. The next call to you is going to be step(), so finish all your setup now".

**Comment by AndrewBelt** [comment]
See my comment ref.

**Comment by AndrewBelt** [comment]
Fixed in 2873f35e72781629426ca9b922bdc9991167bbaa
