### ISSUE TITLE
unable to compile from source on windows 10

### ISSUE THREAD

**Issue by adsmz** [VCVRack/Rack#693]
OS (if applicable):Windows 10
Version (or "dev" if compiling from source): dev

Following the directions [here](https://github.com/VCVRack/Rack#building) I installed MSYS2, launced the MINGW 64 bit shell, and installed the build tools and dependancies. when I try to run `make`, I get this output:

`MINGW64 ~/Rack
$ make
g++ -Iinclude -Idep/include -Idep/lib/libzip/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -Wsuggest-override -std=c++11 -c -o build/src/asset.cpp.o src/asset.cpp
src/asset.cpp:5:10: fatal error: ../ext/osdialog/osdialog.h: No such file or directory
 #include "../ext/osdialog/osdialog.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [compile.mk:54: build/src/asset.cpp.o] Error 1
`

**Comment by AndrewBelt** [comment]
Did you forget to initialize the submodules? See README

**Comment by squinkylabs** [comment]
what he said ^. Also, did you run "make dep" first, and did it succeed?

**Comment by adsmz** [comment]
I had run `make dep` successfully first, yeah. I'd somehow completely missed the submodules though, even when checking my work. thanks!
