### ISSUE TITLE
Cloned my repo fails to build on make

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Rack#694]
OS (if applicable):Win7
Version (or "dev" if compiling from source):dev

I'm probably missing something very obvious here. Just don't know what.

Uploaded the modules that make on my side, cloning my repo in Ming and making they fail to make.
```
g++ -o plugin.dll   -shared -L../../ -lRack
```

**Comment by Coirt** [comment]
v0.5.0 I think. [Source](https://github.com/Coirt/Bark)

**Comment by AndrewBelt** [comment]
Not sure if this is the issue, but your `src` directory is spelled `scr`

**Comment by Coirt** [comment]
Ah completely blind to that. Had it v0.5.1 thought that was the problem so changed it. src will most likely fix i'd say.

**Comment by AndrewBelt** [comment]
Also, make sure you've checked out the latest source in the Rack v0.5 branch, *not* tag v0.5.0. That's an old version which might not build correctly.

**Comment by Coirt** [comment]
Cheers that did it Andrew that was a basic error!
