### ISSUE TITLE
Custom led shapes

### ISSUE THREAD

**Issue by AScustomWorks** [VCVRack/Rack#695]
Not an issue but a question:
I want to make a custom look for a led bezel and corresponding light. Led bezel is easy, but what/where do I need to modify for the custom shaped led light? I'm aiming at rounded corners square light.
Thanks!

**Comment by AndrewBelt** [comment]
I would override the drawLight method of LightWidget but keep the drawGlow method. Those are in the master branch only.

**Comment by AScustomWorks** [comment]
Oh, I guess that's the reason I couldn't find the relevant code. If I use that feature now to build a module, will it work fine on the public released rack app?

**Comment by AndrewBelt** [comment]
Yeah, it's BSD licensed. 
For the v0.5 branch, you'd have to override the whole draw() method, but you can just copy paste code.

**Comment by AScustomWorks** [comment]
Thanks a lot!, closing now ;)
