### ISSUE TITLE
Are the installing plugins directions correct?

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#696]
Your wiki says to unzip to the Rack/plugins folder, except on Mac. But I believe on Windows they also go into a special folder, don't they? ~\MyDocuments\Rack\plugins? I want to link to instructions, but only if they work ;-)

**Comment by cschol** [comment]
On Windows 10 (not sure about older versions):
`C:\Users\<username>\Documents\Rack\plugins`

**Comment by AndrewBelt** [comment]
The wiki is open, unofficial, and may contain complete garbage, so I wouldn't link to it.  Use https://vcvrack.com/manual/Installing.html
