### ISSUE TITLE
Pulse Matrix 8 / 16: early first step on RUN is ignored

### ISSUE THREAD

**Issue by DomiKamu** [VCVRack/Rack#698]
OS (if applicable): Windows 7 Pro SP1 64-bit, Windows 10 Pro "Redstone 3" 64-bit.
Version (or "dev" if compiling from source): 0.5.1

Hi,

When I use a row to trigger a drum module (for example), the step 1 (after reset, then run) is ignored (aka no trigger on output) - "Forward" mode. However, it's okay for any other step including step 1 on next loops.

Same behavior occurs on last step but in "Reverse" mode (step 8 or 16, depending Pulse Matrix model).

Regards.

![sans titre-1](https://user-images.githubusercontent.com/24851960/36061256-4442b29e-0e58-11e8-9438-d618eb11af89.png)

**Comment by AndrewBelt** [comment]
@n6smith You are correct.

**Comment by AndrewBelt** [comment]
Fixed along with #619. Will provide build when Rack v0.6 releases.

**Comment by DomiKamu** [comment]
But for now Rack 0.6 isn't released, delayed again, and this issue is closed. It's the twilight zone!

**Comment by AndrewBelt** [comment]
Feel free to re-open, but I'll probably forget to close it.

**Comment by DomiKamu** [comment]
From my GitHub account, I'm not able to reopen this issue, having "Comment" button, but not "Reopen and comment".
