### ISSUE TITLE
plugLight on one particular port doesn't light

### ISSUE THREAD

**Issue by WIZARDISHUNGRY** [VCVRack/Rack#700]
OS (if applicable): Mac
Version (or "dev" if compiling from source): dev

<img width="395" alt="pluglight" src="https://user-images.githubusercontent.com/15206/36066695-6b4b25b4-0e7c-11e8-9c6f-57e630170625.png">

The code sees the correct value at the inlet but the light doesn't light. I'll investigate this more myself.

**Comment by AndrewBelt** [comment]
What am I looking at here?

**Comment by WIZARDISHUNGRY** [comment]
<img width="395" alt="pluglight" src="https://user-images.githubusercontent.com/15206/36066752-7068cdb6-0e7d-11e8-86a1-ac9610c6725c.png">

The pluglight on the red cable isn't lit but it should be. It only occurs on this particular port.

**Comment by AndrewBelt** [comment]
Edited my above comment.

**Comment by WIZARDISHUNGRY** [comment]
Looks like there's a bounds problem arising from using inputIds that exceeded NUM_INPUTS e.g.
```C++
enum InputIds {
  CV_INPUT,
  CLOCK_INPUT,
  CV2_INPUT,
  WIDTH_INPUT,
  CENTER_INPUT = WIDTH_INPUT+2,
  NUM_INPUTS
};
```
instead of:
```C++
enum InputIds {
  CV_INPUT,
  CLOCK_INPUT,
  CV2_INPUT,
  WIDTH_INPUT,
  CENTER_INPUT = WIDTH_INPUT+2,
  NUM_INPUTS = CENTER_INPUT+2
};
```

(mea culpa)
