### ISSUE TITLE
lastPath variable not set correctly on startup

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#701]
OS (if applicable): Win
Version (or "dev" if compiling from source): 979e44f650f3aafef207ebbdc1e9dbfe0d9b96ba

The last used patch file is not restored correctly in the `lastPath` member of `gRackWidget`. You notice that patch itself is loaded correctly, but the window title does not show the file name.

If you hit "Save", it will pull up the "Save As" dialog. The other effect is that on the next autosave, the `lastPath` entry in `settings.json` will replaced with an empty string. 

I think it has to do with the order of `loadSettings()` and `loadPatch()` in `main.cpp`.

In `v0.5` the order is as follows:

```
gRackWidget->loadPatch(assetLocal("autosave.vcv"));
settingsLoad(assetLocal("settings.json"));
```

In `master` the order is:

```
settingsLoad(assetLocal("settings.json"));

[...]

else {
    gRackWidget->loadPatch(assetLocal("autosave.vcv"));
}
```

If I restore the order of functions from `v0.5`, the behavior is correct, but that order does not serve the intent with the "crash detection" code. Maybe that's helpful though to determine how to fix it.

**Comment by AndrewBelt** [comment]
Fixed in e51ce445881303b9a0d1f84c9aa663d4f464cdb3
