### ISSUE TITLE
Clearing patch does not reset rack to upper left corner

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#704]
OS (if applicable): Windows
Version (or "dev" if compiling from source): 979e44f650f3aafef207ebbdc1e9dbfe0d9b96ba

When clearing a patch, the "origin" of the rack is not set back to the upper left corner, i.e. scrollbars are not reset. If I then build a patch and restart Rack, it might look like there is no patch there, but in fact it is off of the screen.

Steps to reproduce:
- Scroll down and right for a little while using scrollbars
- File -> New -> Confirm clearing patch
- Place module in the middle of screen
- Restart Rack
- Observe that module is off screen, as Rack starts with "origin" in the upper left corner of the rack

Expected behavior is that "origin" and scroll bars are reset on clearing rack for a new patch.

**Comment by AndrewBelt** [comment]
Fixed in f4da514
