### ISSUE TITLE
use of undeclared identifier 'quadraticBipolar'

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/Rack#708]
Version (or "dev" if compiling from source): dev

I was recompiling my plugins against the latest dev version, i get a **use of undeclared identifier 'quadraticBipolar'** in some modules.
It doesn't appear to be deprecatedm and a quick loot to the Fundamental VCO code still has it. 

Any hint?

**Comment by AndrewBelt** [comment]
It has been moved to `dsp/functions.hpp`. I'll add a note in #258

**Comment by antoniograzioli** [comment]
lk, thanks, I read the note about deprecated functions but couldn't find anything related to quadraticBipolar

**Comment by AndrewBelt** [comment]
Just added it
