### ISSUE TITLE
Merch Store

### ISSUE THREAD

**Issue by almostEric** [VCVRack/Rack#709]
Hey,

I was thinking it would be cool if there was a VCV merch store. I know there are companies that can put designs on pretty much any product. My thought was besides official VCV merch (think t shirts, hoodies, coffee mugs), plug-in developers could contribute their own designs, and for those there would be a 50-50 split of the profits

**Comment by AndrewBelt** [comment]
Grayscale does my merch. https://grayscale.threadless.com/
Currently only tshirts.
