### ISSUE TITLE
Grey / black cables significantly less visible

### ISSUE THREAD

**Issue by darloth** [VCVRack/Rack#712]
The grey or black cable colour is significantly less visible than the others, especially when cable opacity is 50% (the default) or lower.  I personally find it difficult to see when a cable is even plugged in using this colour at times, if the module panel is already a similar grey.

While there are various others issues and/or feature requests about cable management, this one is much simpler - If there is not a specific reason to have this dark grey colour of cable, can it please be removed or changed?

If five separate colours are required, I suggest purple or orange.

**Comment by AndrewBelt** [comment]
Fixed in master
