### ISSUE TITLE
Feature Request, New and New from template in File Menu

### ISSUE THREAD

**Issue by Strum** [VCVRack/Rack#715]
If would be handy to be able to create either a new blank patch or a new patch from the template file.

Can that be added to the menu?

**Comment by AndrewBelt** [comment]
That kind of defeats the purpose of the template.vcv file.

**Comment by Strum** [comment]
I don't think so, 

Sometimes i want to start from scratch, other times i want to use a template, it's seems a bit of a pain to have to overwrite the template to create a new blank patch.

**Comment by AndrewBelt** [comment]
Sounds like a better workflow than a template file for you is to save a few .vcv files in a folder as starting points, and work with those when you need them.

**Comment by Strum** [comment]
@AndrewBelt then what is the point of having the template at all then?

**Comment by AndrewBelt** [comment]
>@AndrewBelt then what is the point of having the template at all then?


None, in your case.

**Comment by Strum** [comment]
@AndrewBelt 

Yes well I expect there are other users who also find it an issue, wasn't already raised once before?

**Comment by Coirt** [comment]
Have a couple of templates saved in a folder but in fairness it would be handy to have less clicks to open different types of patch starers but its trivial really.

**Comment by AndrewBelt** [comment]
It's just feature creep at this point.
- Add **New** and **New from template** menu items
- People are confused why there are two
- Enable **New from template** only when a template is available
- Select it with Ctrl+N instead of **New** when available
- People are still not satisfied, need multiple templates
- Add submenu for multiple templates in templates/ folder
- People still want the single template.vcv file to load
- Add entry to submenu to support root-level template.vcv
- etc

I just really don't feel like maintaining all this crap.

**Comment by Strum** [comment]
@AndrewBelt 

I don't want multiple templates, one is sufficient 

It would seem a trivial thing to implement.
I wouldn't have thought it would be more than a couple of dozens lines of code that probably already exists in the app init somewhere.

I understand your concerns about feature creep and extra maintenance, but I'd humbly suggest that users are always going to want more features, most pro DAWs have multiple templating and I imagine users migrating to Rack from them will continue to request it and other things that they are used to having in DAWs.

Is there a features request thread on the issue tracker?

Maybe if there was a list of feature requests that have been rejected and why it might help.

Maybe if you could give users some guidance as to what is practically possible and what is outside that users might be able to think about requests before making them and save you time dealing with them as a result.

Sorry to be a pain, thanks for your time.

It might be worth bearing in mind that if eventually enough users and contributors are denied enough requests they might make their own fork.

**Comment by AndrewBelt** [comment]
>I don't want multiple templates, one is sufficient

You draw the line at my fifth bullet point, others will have different opinions.

>I wouldn't have thought it would be more than a couple of dozens lines of code that probably already exists in the app init somewhere.

It's not code, it's consistency and organization of UI.

>Is there a features request thread on the issue tracker?

Yes, the issue tracker itself.

>Maybe if there was a list of feature requests that have been rejected and why it might help.

Search the issue tracker.

>Maybe if you could give users some guidance as to what is practically possible

I will do that on a case-by-case basis.

>It might be worth bearing in mind that if eventually enough users and contributors are denied enough requests they might make their own fork.

And then they will immediately discover the cost of maintaining such features when larger, more important features are added.

Locking.
