### ISSUE TITLE
why is the recommended schmitt trigger low voltage zero?

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#716]
I'm sure it's fine, but what if the input is a lowpass filtered edge? As you point out, gibbs may make it ring, but if it doesn't ring it will often take an infinite amount of time to reach <= 0.

In the past, we used a high value of three and a low value of one with the ES Disting module (which does have a lot of gibbs, by the way.

**Comment by AndrewBelt** [comment]
Changed in https://vcvrack.com/manual/VoltageStandards.html

**Comment by squinkylabs** [comment]
Totally agree with your guidelines. 0.1 and 1.0 sounds line fine values. thanks! presumably the SchmittTrigger in 0.6.0 will have these new values?

**Comment by AndrewBelt** [comment]
No, the `SchmittTrigger` class will always be 0 and 1. It is up to you to rescale it, with

```cpp
trigger.process(rescale(in, low, high, 0.1f, 1.f))
```

**Comment by Coirt** [comment]
Is gibbs somewhat like phase. The scope looks like it has phase issues with most signals except LFO/Env audio waves are strange not sure if they are to be believed.

![scope phase](https://user-images.githubusercontent.com/12150421/36352393-21dbee6a-14b0-11e8-95a9-eb105887fbaa.JPG)

**Comment by squinkylabs** [comment]
No, gibbs is a ringing on sharp transitions in a waveform. It's not caused by phase shift, it's due to band-limiting (low pass filtering).

**Comment by AndrewBelt** [comment]
@Coirt I don't understand your question.
