### ISSUE TITLE
v0.6dev?

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#719]
For some reason I'm having a hard time with the migration instructions.

Some threads refer to a v0.6dev branch, but there does not seem to be a branch with that name in Rack.

Presumably the new stuff is in the master branch of rack?

The only thing I can figure is that we are being instructed to:
* Clone a new repo of rack and checkout master.
* Make a new branch in our plugins called v0.6dev.
* Port the code in our v0.6dev branches to the new APIs documented in the threads.

Then we are supposed to submit PR's for our 0.6 plugins? Will those PR's be merged into a different branch of community?

I get the general idea - port you plugins now. And I'm ready to do it. but the nuts and bolts of how this relates to different git branches is not yet clear to me.

thanks in advance for the help.

**Comment by Coirt** [comment]
Thought the version# in the slug just has to match the build for v1. Is it a bit more complicated than that?

**Comment by AScustomWorks** [comment]
I'm interested in this too, plain and simple instructions to download vcv rack source code that will compile 0.6 plugins, thanks!

**Comment by AndrewBelt** [comment]
Instructions:

`git checkout master`

That's it.

**Comment by squinkylabs** [comment]
Tx, actually, I phrased my second question incorrectly. How about "are we being encouraged to submit out 0.6 plugins to the manager asap, and if so does that mean our 0.5 version will not be available there?"

**Comment by AndrewBelt** [comment]
@squinkylabs You don't need to submit anything, but if you update your code in either master or some other branch, like `v0.6`, the VCV Community Review team will be able to add a working commit to a submodule in the community repo.

**Comment by squinkylabs** [comment]
That's great, and I want to do that. My question is about how to submit 0.6 compatible plugin manifests, while still keeping our 0.5.0 compatible plugins available. I don't see any obvious branches in the community repo for this.

I guess we were wondering if plugin manager was suddenly going  to "throw the switch for us" when 0.6 is released?

Or is it best for us to put .6 and .5 versions in our own release repos, and then submit new manifests on the day we want plugin manager to start distributing 0.6 compatible versions.

**Comment by AScustomWorks** [comment]
git checkout master alone isn't working for me, I posted a new issue abut it

**Comment by AndrewBelt** [comment]
@squinkylabs Oh, I see. We're not accepting 0.6 manifests yet until about a week before release. If you're active on https://github.com/VCVRack/community/issues/248, you'll see the announcement to start doing accepting manifests with a new format and procedure, and if not, someone will reach out to you and build the manifest for you.

**Comment by AndrewBelt** [comment]
I think the confusion should be cleared up now, since I have removed all `master` branches of VCVRack repos. The branch now always specifies the compatibility version of Rack.
