### ISSUE TITLE
Move/Reduce dependencies on the glfw library

### ISSUE THREAD

**Issue by luckyxxl** [VCVRack/Rack#721]
Hello,

I did a [port](https://github.com/luckyxxl/Rack/tree/sdl2) of Rack to SDL2 as an experiment to support more platforms. It is very rough mainly due many dependencies on the glfw API throughout the Rack code. I suggest moving glfw dependencies to a single source file: `window.cpp`. [This PR](https://github.com/VCVRack/Rack/pull/720) is a minor start in this direction. More debatable changes I would suggest and I'm willing to implement:

- add `windowGet/SetClipboardText()` functions and remove `extern GLFWWindow *gWindow;`
- add two Rack-specific `enum class` for mouse button and keyboard key constants

The first will break plugins that use gWindow (are there any?). The second breaks plugins that do their own event handling, thought the fix would be easy (replace GLFW_KEY_A with Key::A or something like that). Additionally, the second could be used to make the plugin ABI independent of the glfw ABI or any other system Rack is ported to.

What do you think about that? I'm willing to implement those changes, but is there any chance this will be merged in the (near) future? Thanks for your comments :)

**Comment by AndrewBelt** [comment]
What platforms are you interested in?

**Comment by luckyxxl** [comment]
My main platform of interest is Android. I already got a somewhat working version, though the code is pretty horrible also due to the reasons described above.
While I'm at it I would also like to test compiling Rack with emscripten...

**Comment by AndrewBelt** [comment]
Closing since it's fine for now to consider the GLFW API to be part of the Rack SDK.
