### ISSUE TITLE
possible error in the instructions for 0.6 porting in Plugin API Updates Thread #258

### ISSUE THREAD

**Issue by alikins** [VCVRack/Rack#722]
OS (if applicable):
Version (or "dev" if compiling from source): dev

In https://github.com/VCVRack/Rack/issues/258#issuecomment-365657954

for step 3:

> 
> ``` cpp
> Model *modelMyModule = Model::create<MyModule, MyModuleWidget>(
> 	"Template", "MyModule", "My Module", OSCILLATOR_TAG);
> ```
> 
> Note: For blank panels with no Module, simply use the base class Module in place of MyModule.
> 
> Finally, returning to Template.cpp, add
> ``` cpp
> 	p->addModel(modelMyModule);
> ```

in the place of the moved line for each module.

I think the `modelMyModule` should be `modelMyModuleWidget` ?  The changes to Fundamental seem to match the latter. The latter style was also what I had to change to get my plugin to load without a 
load failure and `undefined symbol: modelMomentaryOnButtonsWidget` warning on startup.

Should that be something like this?:

``` cpp

Model *modelMyModuleWidget = Model::create<MyModule, MyModuleWidget>(
	"Template", "MyModule", "My Module", OSCILLATOR_TAG);
```
and

``` cpp

	p->addModel(modelMyModuleWidget);
```

**Comment by AndrewBelt** [comment]
Whooops, I was automating the change for Fundamental and used the old class name as part of the variable name. I've updated Fundamental. The variable name should be `modelVCO` for example, where `VCO` is the name of your module.

A more accurate name for Model would be `ModuleFactory`, or `ModuleAndModuleWidgetFactory`, but this would scare everyone away.
