### ISSUE TITLE
rack v.06 make run error

### ISSUE THREAD

**Issue by AScustomWorks** [VCVRack/Rack#725]
OS (if applicable):10.12.6
Version (or "dev" if compiling from source):dev
So, I did git checkout master (on my then running fine rack installation), then make run, and I'm getting this error(after lots of stuff got compiled again):

src/gui.cpp:448:3: error: use of undeclared identifier 'glfwGetWindowContentScale'
                glfwGetWindowContentScale(gWindow, &pixelRatio, NULL);

I thought I had to run make dep again, got this error:

make: *** [build/src/gui.cpp.o] Error 1
iMac5K:Rack Freddy$ make dep
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C dep
curl -O https://github.com/xiph/speexdsp/archive/SpeexDSP-1.2rc3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   130    0   130    0     0    237      0 --:--:-- --:--:-- --:--:--   237
tar xf SpeexDSP-1.2rc3.tar.gz
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
make[1]: *** [lib/libspeexdsp.dylib] Error 1
make: *** [dep] Error 2

Now I can't get rack running no matter which checkout version I set.

Also tried to do a fresh rack install on another folder starting from zero, there, after running make dep I get this errors:
make[4]: *** [install-libLTLIBRARIES] Error 64
make[3]: *** [install-am] Error 2
make[2]: *** [install-recursive] Error 1
make[1]: *** [lib/libjansson.dylib] Error 2
make: *** [dep] Error 2

So, how can I fix my previously working version, or make a completely clean install (seems like the previous install is giving the new one troubles but not sure).

Meanwhile, I can't run rack dev or update my plugins to 0.6, thanks for all the help!

**Comment by AndrewBelt** [comment]
It'd be good to `make clean` in the dep/ directory before building dependencies for master. Does this fix it?

**Comment by AScustomWorks** [comment]
Ran make clean at dep folder, ran make dep again, got stuck at the same error:
tar xf SpeexDSP-1.2rc3.tar.gz
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
make[1]: *** [lib/libspeexdsp.dylib] Error 1
make: *** [dep] Error 2

After a bit of internet searching, got past that error by changing this line in dep/Makefile:
WGET = curl -O to WGET = curl -OL

Now I got this error:

tar xf SpeexDSP-1.2rc3.tar.gz
cd speexdsp-SpeexDSP-1.2rc3 && ./autogen.sh && ./configure --prefix="/Users/Freddy/Rack-0.5.1/Rack/dep"
Updating build configuration files, please wait....
./autogen.sh: line 13: autoreconf: command not found
make[1]: *** [lib/libspeexdsp.dylib] Error 127
make: *** [dep] Error 2

Any ideas?

**Comment by AndrewBelt** [comment]
Are you sure you have the latest master branch? This stuff was fixed a while ago, including `curl -OL`

**Comment by AScustomWorks** [comment]
Did a checkout master again, here's the result:
iMac5K:Rack Freddy$ git checkout master
M	dep/Makefile
M	dep/glfw
Already on 'master'
Your branch is up to date with 'origin/master'.

What can I look into to find out if it is the latest version?

btw. just kept searching, looks like sppexdsp needs brew install autoconf, and brew install automake

Installed those and now I get this error (am I deviating here?):

tar xf SpeexDSP-1.2rc3.tar.gz
cd speexdsp-SpeexDSP-1.2rc3 && ./autogen.sh && ./configure --prefix="/Users/Freddy/Rack-0.5.1/Rack/dep"
Updating build configuration files, please wait....
configure.ac:26: warning: macro 'AM_PROG_LIBTOOL' not found in library
configure.ac:25: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:26: error: possibly undefined macro: AM_PROG_LIBTOOL
autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1
make[1]: *** [lib/libspeexdsp.dylib] Error 1
make: *** [dep] Error 2

**Comment by AndrewBelt** [comment]
Still on the old version. You need to `git pull` to fetch the latest source from GitHub.

**Comment by AScustomWorks** [comment]
I was missing that, ran git pull and files got updated:
 84 files changed, 1458 insertions(+), 1276 deletions(-)
Ran make clean on dep, ran make dep again, had to install libtool, ran make dep again, got:
#######################################
# Built all dependencies successfully #
#######################################

Seems like I'm getting close, but now I got this:
make: *** No rule to make target `include/math.hpp', needed by `build/src/app.cpp.o'.  Stop.

**Comment by AndrewBelt** [comment]
`make clean`  in the Rack directory before building.

**Comment by AScustomWorks** [comment]
Ok, rack is running now!, but screen is looking like this:
![rackv0-6-0dev](https://user-images.githubusercontent.com/34798768/36326029-54f56246-131f-11e8-8345-194f895d0f0d.png)

**Comment by AScustomWorks** [comment]
I have now rack v0.6.0dev and also Fundamental and Template plugins running fine. Thanks for the help Andrew!
