### ISSUE TITLE
Built dependencies, then unrecognized command line option "-stdlib=libc++" under Yosemite

### ISSUE THREAD

**Issue by airwindows** [VCVRack/Rack#726]
OS (if applicable): MacOS 10.10.5 "Yosemite"
Version (or "dev" if compiling from source): dev

I've been trying to build this all day: I'm an audio DSP dev looking to port all my plugins to VCV Rack but I can't even get started (I'm good with sound code but miserable at this stuff)

I got it to build all dependencies successfully after hours of struggling in Terminal, but then (after a 'make clean'):

christopherjohnson@host2 Rack (v0.5) $ make
c++ -Iinclude -Idep/include -Idep/lib/libzip/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7 -DAPPLE -stdlib=libc++ -std=c++11 -stdlib=libc++ -c -o build/src/app.cpp.o src/app.cpp
cc1plus: error: unrecognized command line option "-stdlib=libc++"
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-stdlib=libc++"
make: *** [build/src/app.cpp.o] Error 1

I'm absolutely stuck. What on earth am I missing? I got so close, it was throwing all sorts of errors all afternoon (couldn't download 'glew', had all sorts of problems even making the dependencies). I had to "brew install gcc --enable-cxx -enable-fortran -use-llvm" even to get that far.

**Comment by AndrewBelt** [comment]
Nobody's ever tested this on Mac with GCC. Use clang.

**Comment by airwindows** [comment]
I do have xcode, and I'm just running the make scripts as told to in the instructions. If it's not using clang, how do I make it use clang, since I'm not asking it to use gcc? I'm on the last xcode that will run on my Yosemite machine. (which is running that because I'm nervous some older Adobe apps will die if I go beyond Yosemite)

Is there a way I can invoke the makefiles given to me by git-cloning Rack and trying to follow the instructions, that will not run gcc? Should I start over from scratch and do something else?

**Comment by AndrewBelt** [comment]
I assume it's because you ran `brew install gcc`, so if you undo that with `brew uninstall gcc`, you'll have better luck. "Start over" by running `make clean`, even in the dep/ directory, and post here if you hit an obstacle.

**Comment by airwindows** [comment]
Welp, I did brew uninstall gcc, which seemed to work. Ran make clean, and in the dep/ directory, and make dep worked (but still found a gcc somewhere! but also found clang!) and make did exactly what it did last time. I assume totally removing gcc is the intention, but using brew to uninstall it didn't work.

**Comment by AndrewBelt** [comment]
Great. Now proceed until you hit an obstacle and post the error.

**Comment by airwindows** [comment]
OK: make dep didn't fail, it was make that failed. So, this was the obstacle, and this is the same error:

c++ -Iinclude -Idep/include -Idep/lib/libzip/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7 -DAPPLE -stdlib=libc++ -std=c++11 -stdlib=libc++ -c -o build/src/app.cpp.o src/app.cpp
cc1plus: error: unrecognized command line option "-stdlib=libc++"
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-stdlib=libc++"
make: *** [build/src/app.cpp.o] Error 1

**Comment by AndrewBelt** [comment]
Strange, yosemite's clang should support that, and it looks like gcc wasn't being called at all.  What about `which c++`

**Comment by airwindows** [comment]
/usr/bin/c++

**Comment by AndrewBelt** [comment]
Post your environment with `env`? Be sure to filter personal information. 
Still not convinced it's calling Apple's clang.

**Comment by airwindows** [comment]
Sure. Don't feel there's any hurry: it's bedtime, I can pick this up another day. Here's env :)

env

TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/r7/245p3r0n639g9zz5jspzv7x80000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.gi7Midslt8/Render
TERM_PROGRAM_VERSION=343.7
TERM_SESSION_ID=D901CE43-0A25-49BB-BFF9-C96A10560AD2
USER=me
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.aXmbPOAd0C/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/Library/Frameworks/Python.framework/Versions/Current/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
PWD=/Users/me/VCVRackProjects/Rack
LANG=en_US.UTF-8
XPC_FLAGS=0x0
PS1=\u@\h \W\[\033[32m\]$(parse_git_branch)\[\033[00m\] $ 
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/me
LOGNAME=me
DISPLAY=/private/tmp/com.apple.launchd.HdSYxLUiBg/org.macosforge.xquartz:0
_=/usr/bin/env
OLDPWD=/Users/me/VCVRackProjects/Rack/dep

**Comment by airwindows** [comment]
Returning to the fray: I've been making plugins and couldn't get back to Rack for a while. I have redownloaded and installed a fresh copy of XCode, and I'm finding that I have several gcc variants from 2010 lurking in usr/bin: right now I'm doing the make dep/make thing again with a fresh copy of the Rack git repository, and I'm inclined to try and remove the extra 2010 gccs (g++-4.0, g++-4.2, gcc-4.0, gcc-4.2, gcov-4.0, gcov-4.2) before continuing my process. Each of these has a simple 'gcc, g++, gcov' that's from 2014 instead of 2010. Not sure how I got them.

…and got this:

/Applications/Xcode.app/Contents/Developer/usr/bin/make -C dep
make[1]: Nothing to be done for `dep'.
c++ -stdlib=libc++ -std=c++11 -stdlib=libc++ -Iinclude -Idep/include -Idep/lib/libzip/include -DVERSION=master -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7 -c -o build/src/asset.cpp.o src/asset.cpp
cc1plus: error: unrecognized command line option "-stdlib=libc++"
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-stdlib=libc++"
make: *** [build/src/asset.cpp.o] Error 1

hmm.

**Comment by airwindows** [comment]
On the bright side, with this removal of 2010 gcc binaries, now when I start over from scratch I'm seeing

checking if compiler is clang... yes
checking if compiler is GNU C... no

However, having done the entire thing over from scratch, I get exactly the same errors.

**Comment by AndrewBelt** [comment]
You should probably reinstall your operating system if you want to do any C++ development. Your environment is a mess.

**Comment by airwindows** [comment]
That's fair: I'll have to work that stuff out or simply not take part in VCV plugin development. Certainly your time is better spent developing VCV Rack. I'll close this issue.
