### ISSUE TITLE
Arrow Keys Behavior with Main Window

### ISSUE THREAD

**Issue by jonheal** [VCVRack/Rack#728]
OS (if applicable): Windows 10
Version (or "dev" if compiling from source): .5.1
In addition to the requests for arrow keys functionality in the module select dialog and the Notes module, it would also be intuitive to be able to scroll the main Rack window with the arrow keys.

Thanks for your hard work, Andrew.

**Comment by AndrewBelt** [comment]
It already does. Have you tried it?

**Comment by jonheal** [comment]
You know what? I actually posted the totally wrong request! I realize now the functionality I am was asking for is to be able to click in the empty portion of the scroll bar to move the scroll thumb.

My brain really scrambled that one. Sorry.

--
Jon Heal
http://www.theheals.org/
Have a nice day!

**Comment by AndrewBelt** [comment]
Unfortunately the scrollbar works in the same way as continuous encoder knobs. Since scrolling is infinite, the "empty space" in the scrollbar isn't a defined offset location of the viewport.
