### ISSUE TITLE
Cannot paste password (Mac OS X)

### ISSUE THREAD

**Issue by bilekt3** [VCVRack/Rack#73]
I am unable to paste value to password field in application on Mac.

I have very strong password uniquely generated for each login and this is little annoying.

Any other experiencing same issue?

**Comment by AndrewBelt** [comment]
Works for me in v0.3.1. I'm using Command-V

**Comment by bilekt3** [comment]
Thanks, I have missed v0.3.1 release, where Command-V works as expected.
