### ISSUE TITLE
v0.5.1 Windows -- Freezing trying to instantiate trowaSoft voltSeq

### ISSUE THREAD

**Issue by Chaircrusher** [VCVRack/Rack#732]
OS (if applicable): Windows
Version (or "dev" if compiling from source): v0.5.1

This happened after unpacking the beta Blamsoft Wavetable plugin, but not sure if it's related.

Instantiating any module was slow -- like 2 minutes to bring them up.  Everything worked fine before adding the XFX Wave beta plugin.

Is there a way to turn on logging, the way I see when I run the Linux version I built?

**Comment by AndrewBelt** [comment]
Could you look at your log.txt file and see if anything is strange? Could you confirm that the problem is that plugin be removing it and retesting?

**Comment by Chaircrusher** [comment]
Solved by A) deleting my plugins directory ( Documents\Rack\plugins ) and re-downloading everything and then B) blowing away Rack preferences and last autosave patch.

After that the Blamsoft XFX Wave (and everything else) worked as well as it ever did.

As far as I'm concerned, you can close this bug. I should have saved the log file for you but I glanced at it and it didn't look unusual.
