### ISSUE TITLE
Specify RACK_DIR in the 'plugin helpers' targets

### ISSUE THREAD

**Issue by dhemery** [VCVRack/Rack#733]
OS (if applicable): all
Version (or "dev" if compiling from source): dev

At the moment, the "plugin helper" targets (allplugins, cleanplugins, distplugins) build a plugin properly only if the plugin's `Makefile` either leaves `RACK_DIR` undefined or specifies `RACK_DIR=../..`.

I was quite excited by the new `RACK_DIR` variable, because it allows me to build my plugin code from somewhere other than `Rack/plugins`, and because (alas) there is nothing more exciting in my life at the moment. I prefer put Rack and my plugin under the same parent directory, so my `Makefile` specifies `RACK_DIR ?= ../Rack`. Much nicer.

For people who try to build my plugin the standard way, by cloning it under `Rack/plugins`, Rack's plugin helper targets don't work, because my `Makefile` assumes the plugin dir is beside the `Rack` dir. People *could* override my value by specifying `RACK_DIR=../..` when they run `make`, but not everyone knows about that, and it's mildly awkward even if you know about it.

Given that the plugin helpers build only the plugins that are in `Rack/plugins`, they would be easier for people to use if these targets specified `RACK_DIR` like so:

```
allplugins:
	for f in plugins/*; do $(MAKE) -C "$$f" RACK_DIR=../..; done

cleanplugins:
	for f in plugins/*; do $(MAKE) -C "$$f" clean RACK_DIR=../..; done

distplugins:
	for f in plugins/*; do $(MAKE) -C "$$f" dist RACK_DIR=../..; done
```

**Comment by AndrewBelt** [comment]
Each plugin's Makefile should define it as `../..` if not defined, so I'd recommend you change your Makefile back to that.
In your case, since you prefer your Rack directory to be a location other than `../..`, put `export RACK_DIR=<absolute path to Rack directory>` in your .bashrc (or whatever shell you use). Then all plugins you build, yours or otherwise, will refer to your Rack's location.

**Comment by dhemery** [comment]
Now I am sad.

**Comment by AndrewBelt** [comment]
It should solve your problem, just in a different way, without breaking conventions.
