### ISSUE TITLE
API changes for 0.6.0dev

### ISSUE THREAD

**Issue by Phal-anx** [VCVRack/Rack#735]
OS (if applicable): Win 7
Version (or "dev" if compiling from source):dev

I made all the changes and compiling works but I get this warnings about the changed 
"clampf(float x, float min, float max)" 

e.g.:
cutoffExp1 = clampf(cutoffExp1, 0.1f, 1.0f);
...gives me a warning

all modules work without any error as far as I can tell...
is this a warning because of the changes in Rack or because I made something wrong?

**Comment by AndrewBelt** [comment]
`clampf` is deprecated, use `clamp`
https://github.com/VCVRack/Rack/blob/master/include/util/math.hpp#L283

**Comment by Phal-anx** [comment]
ahh this was the error thanks ;)
