### ISSUE TITLE
using GPUs for physical modelling within Rack

### ISSUE THREAD

**Issue by Strum** [VCVRack/Rack#739]
Discussion on the irc channel has brought up what I think is an interesting idea and I was wondering what people's thoughts are on it.

Use GPU hardware to accelerate complex physical modelling modules.

is it possible to use GPU code within Rack as is stands already?

this project looks very interesting.

http://www.ness.music.ed.ac.uk/

Hope this isn't off topic for here.

**Comment by AndrewBelt** [comment]
It would only be useful for having fun while learning how to use CUDA/OpenCL, but it doesn't belong in audio DSP. Kernel launch latency, lack of need for performance enhancements if you already have a decent GPU, overcomplication, etc.

**Comment by w3stgaard** [comment]
Yes, VCV Rack needs to be as slim as possible - no modeling **at the moment.** Every CPU percentage is needed for creating sound.

**Comment by unfa** [comment]
From my experience (on Linux) CUDA is flaky. It breaks often and isn't very reliable. It all depends on the configuration, but getting it to work in production with Blender is often a stunt. Frequently you need to just reboot the machine to make the GPU "wake up" and work properly.
I would however be interested to hear if it's usable for realtime audio processing. That could spawn some interesting new possiblities in sound design.

**Comment by Strum** [comment]
I was just floating the idea and starting a discussion.

That a project that uses GPUs for audio already exists would seem to suggest that the idea has some merit.

@unfa, I would be inclined to use openCL but I know next to nothing about coding for GPUs.

@w3stgaard as far as i know the graphics in rack consume most of the computer's resources not the audio processing.

If such a thing was possible within rack i expect it would not be a trivial project to implement and would be something to add in the distant future not a current priority.

I am curious as to whether it might be possible to do it within the existing plugin architecture without modification to rack code though.

**Comment by AndrewBelt** [comment]
Using OpenCL or CUDA, you could parallelize plugin DSP code without relying on Rack since Rack doesn't sandbox plugins. However, this would have nothing to do with Rack because all the GPU code is contained in the plugin.

If you want to do this, it would be good to demonstrate that your plugin cannot just run on one or multiple cores, as there are many tradeoffs of GPU code.
