### ISSUE TITLE
Versioning of plugins directory

### ISSUE THREAD

**Issue by joemcmahon** [VCVRack/Rack#743]
OS (if applicable): All
Version (or "dev" if compiling from source): 0.5.0 and up

The plugin library directory is not versioned. If it were, then old and new versions of VCVRack and its plugins could be installed at the same time without interfering with each other. E.g., instead of just Plugins, the directories would be Plugins/0.5.0 & Plugins/0.6.0 instead of just Plugins -- the Plugins directory would only need to be renamed for revisions breaking backward compatibility. 

The user would be responsible for renaming previous versions of the Rack app to something like "Rack 0.5" or "Old Rack" so as to be able to keep multiple copies.

**Comment by AndrewBelt** [comment]
I'll start doing something to solve this problem when Rack 1 is released, but I'll keep it as-is for Rack beta versions.

**Comment by joemcmahon** [comment]
Great, @AndrewBelt , thanks!

**Comment by AndrewBelt** [comment]
The plugins directory is versioned as of Rack v1. e.g. `<Rack user dir>/plugins-v1`
