### ISSUE TITLE
engineSetParamSmooth deadlock

### ISSUE THREAD

**Issue by The-XOR** [VCVRack/Rack#747]
OS (if applicable): Windows 10
Version (or "dev" if compiling from source): dev

I'm updating my plugins (https://github.com/The-XOR/RackPlugins) so they can be controlled with OSC.
Inside the Module:;step() , if there is a pending OSC msg received, I call ParamWidget->setValue() with the desidered value. For knobs, (and apparently form knobs only) this crashes VCV because of this lock:

```
module: **engine.cpp**
void engineSetParamSmooth(Module *module, int paramId, float value) {
	VIPLock vipLock(vipMutex);
**--->>>>>>>	std::lock_guard<std::mutex> lock(mutex);**
```

If I comment out this line, everything works and I can't notice any side effect.
Is it a bug? Should I set a widget value in a different way?
Thanks for your attention;
X:

**Comment by AndrewBelt** [comment]
Since information should only travel from the GUI (main thread) to the audio engine (engine thread), I would only modify state in your `Module` subclass, and derive some sort of `ParamWidget` subclass which inspects the `Module` and changes its own value accordingly. Something like

```cpp
struct AutomaticParamWidget : WhateverKnob {
	void step() override {
		value = module->requestedParams[paramId].value;
	}
};
```

**Comment by The-XOR** [comment]
This was my first attempt, but sadly the GUI is not updated in this way.

Il giorno sab 24 feb 2018 alle 17:06 Andrew Belt <notifications@github.com>
ha scritto:

**Comment by AndrewBelt** [comment]
Try adding `dirty = true` in the step() function. Does that solve it?

**Comment by The-XOR** [comment]
kinda works for knobs, but not for switches. SVGframes are set in the SVGSwitch::onChange, so I ended up in patching my code: if the control is derived from SVGfader or SVGknob it goes with dirty = true, else use setValue.

**Comment by AndrewBelt** [comment]
Oh actually, wouldn't it be fine to just use `setValue` in step()? No deadlock since it's being requested from the main thread.

**Comment by The-XOR** [comment]
This is how my plugins are designd, setValue is called from step() and
there are not other threads.The knobs deadlock, switches and leds work.

Il giorno dom 25 feb 2018 alle 00:26 Andrew Belt <notifications@github.com>
ha scritto:

**Comment by AndrewBelt** [comment]
Oh sorry, I meant from `ParamWidget::step()` (actually an overwritten method), not `Module::step()`.

**Comment by AndrewBelt** [comment]
Closing since I believe this issue has been obsoleted.
