### ISSUE TITLE
strange readings of CPU usage in audio Interface module

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#748]
We were trying to measure the CPU usage of various plugins, including our own, by instrumenting engine.cpp with a crude “CPU meter”. Compared the time spent stepping modules with the sample rate to derive a crude cpu usage percentage.

Most measurements done on Windows7 with in old Core i5 cpu audio at 44.1k with 256 buffer size. Code base is 0.6.0 (although 0.5 is similar)

```bash
$ git rev-parse head
f7ec8e9fb0d0eb1554ca250f57334081f738f002
```
All the numbers seemed plausible. Out pretty minimal frequency shifter took .3% of the sample rate period . Various other modules seemed to take 1-2% of the sample rate. Big plugins like VCV Console seemed to take 7%.
But when a sound card module is added the numbers go through the ceiling, with the “cpu usage” averaging about 99%. A little tinkering suggested that one step() every hardware buffer size is taking an enormous amount of CPU.
Is this the infamous sample rate converter kicking in? Is our methodology unsound?
Here is how we instrumented engine::engineStep(). _test is a timer:
```
	// Step modules
	_test.start();
	for (Module *module : modules) {
		module->step();

		// TODO skip this step when plug lights are disabled
		// Step ports
		for (Input &input : module->inputs) {
			if (input.active) {
				float value = input.value / 10.0;
				input.plugLights[0].setBrightnessSmooth(value);
				input.plugLights[1].setBrightnessSmooth(-value);
			}
		}
		for (Output &output : module->outputs) {
			if (output.active) {
				float value = output.value / 10.0;
				output.plugLights[0].setBrightnessSmooth(value);
				output.plugLights[1].setBrightnessSmooth(-value);
			}
		}
	}
	_test.stop(1);
```

**Comment by AndrewBelt** [comment]
Audio Interface blocks for timing, so if you measure it by time, you'll get ~100%.

**Comment by squinkylabs** [comment]
Doh! thanks.
