### ISSUE TITLE
Question about LED (light) custom shapes (arrow)

### ISSUE THREAD

**Issue by DomiKamu** [VCVRack/Rack#750]
OS (if applicable): All
Version (or "dev" if compiling from source): 0.6.0dev

Hi, I'm using mainly stock rounded LEDs, but I'd like to know if it's possible to use for example a custom "arrow-shaped" LED, instead? I don't know if the engine is assuming pure black (RGB 0x00, 0x00, 0x00) as lit/unlit part of the LED. Hope my request is clear (English isn't my main language).

TIA for reply.
Dominique CAMUS

**Comment by AndrewBelt** [comment]
LEDs can only be round unless you override the `draw()` method. Look at the source for `LightWidget`, `MultiLightWidget`, and `ModuleLightWidget`.

**Comment by DomiKamu** [comment]
Thanks for your (quick) reply and tip, Andrew, merci!
