### ISSUE TITLE
reopening RACK all the modules are stacked in position 0, 0

### ISSUE THREAD

**Issue by antoniotuzzi** [VCVRack/Rack#751]
OS (if applicable): OSX 10.12
Version (or "dev" if compiling from source): 0.6 (master til 614c6d09883569563bc8a7c41513390babf2cabb)

how should be
![screen shot 2018-02-25 at 11 33 13](https://user-images.githubusercontent.com/62518/36640486-f8c283a2-1a1f-11e8-8e1e-8a035bd08cb3.png)

how is
![screen shot 2018-02-25 at 11 33 32](https://user-images.githubusercontent.com/62518/36640488-0714a1e2-1a20-11e8-8f03-982051f2519e.png)

this is the autosave

[autosave.vcv.zip](https://github.com/VCVRack/Rack/files/1755893/autosave.vcv.zip)

**Comment by AndrewBelt** [comment]
Why does your Rack version say "v0.4.0" but you're running the `master` branch?

**Comment by antoniotuzzi** [comment]
BINGO: I had an old include .mk file in the .gitignore that was setting the version to 0.4.0
