### ISSUE TITLE
core module notes text field issue

### ISSUE THREAD

**Issue by AScustomWorks** [VCVRack/Rack#752]
OS (if applicable):Os X 10.12.6
Version (or "dev" if compiling from source):0.6dev

There's a small issue with the notes module, text can go outside the box:
![notes](https://user-images.githubusercontent.com/34798768/36645667-e677e0ae-1a31-11e8-8f97-7f87241cf554.jpg)

**Comment by AndrewBelt** [comment]
Fixed in daa59fd
