### ISSUE TITLE
0.5.1 crash issue in Windows10 on 'new file'

### ISSUE THREAD

**Issue by Lugia909** [VCVRack/Rack#757]
OS: Windows 10 v.1709 (64-bit)
System: dual Xeon E5-2660 (8-core), 32 GB RAM

After moving from 0.5.0 some time back to 0.5.1, my build of Rack has become unusable. I keep crashing when attempting to open a blank rack with the 'New' command in the file menu. The program appears to freeze when doing this and becomes nonresponsive, with the OS eventually displaying the 'stop or continue to wait' prompt. I've attempted to uninstall and reinstall 0.5.1, but the crash issue persists. Problem doesn't appear to be related to sound drivers or any other external device or processes.

I realize that this is a bit late in 0.5.1's lifespan, and hopefully 0.6 will solve this when it's finally out. I felt that it would be worth making a note of this persistent issue, though, in case whatever's causing this might make the jump to the next beta version.

**Comment by cschol** [comment]
Have you tried removing your current Rack user settings in `C:\Users\<your user name>\Documents\Rack`, i.e. `autosave.vcv` and `settings.json`? Can you post the content of `log.txt` from that same folder?

**Comment by Lugia909** [comment]
Ahh, perfection...it's functional once more. However, it might be a thought to add a user control to do that settings purge as well as to implement it in uninstall, since I did do an uninstall and reinstall and apparently the reinstall was reading a still-existing autosave and settings file from the previous version. Granted, that would also involve losing patches, so some way of working around that might be a good idea.

**Comment by AndrewBelt** [comment]
A while ago I added autosave deletion if a crash was deteted on the last launch, so I'm closing now.
