### ISSUE TITLE
Avoid some unnecessary overhead during make dep

### ISSUE THREAD

**Issue by ndrspcfd** [VCVRack/Rack#758]
So I noticed while doing `make -j dep` there's a *lot* of time spent installing local copies of the openssl documentation inside the dep/openssl-1.1.0g dir that I guess is likely not much use to anyone.

This can be avoided inside dep/Makefile by changing the line

    $(MAKE) -C openssl-1.1.0g install

to these two lines instead:

    $(MAKE) -C openssl-1.1.0g install_sw
    $(MAKE) -C openssl-1.1.0g install_ssldirs

which builds everything required for Rack but avoids installing all the manpages and whatnot which takes quite a bit of the build time for openssl (on my machine anyhow.)

Please feel free to close and delete if you don't like this idea :)

**Comment by squinkylabs** [comment]
That sounds like a great improvement. That step really does take a LONG time. +1.

**Comment by AndrewBelt** [comment]
Do you have a source of what `install_ssldirs` does?

**Comment by AndrewBelt** [comment]
Fixed in 9eed9583912e48df008633745cdfb3043d0a6c9e
