### ISSUE TITLE
Add zoom

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/Rack#76]
Once full vector is finished (after switching panels from PNG to SVG/framebuffer), add zoom capability on the RackWidget, along with a zoom percent on the toolbar.

- [x] add RackRail widget back to RackWidget
- [ ] Fix dropdown position

**Comment by AndrewBelt** [comment]
### Subtasks
- getAbsolutePosition on ZoomWidget
- resizing with gRackWidget
- Framebuffer rescale, mark as dirty
- add Toolbar buttons, key commands

**Comment by AndrewBelt** [comment]
Scrubbing this for v0.5. I could add basic zoom, but I'd rather do it the right way and re-design the framebuffer renderer and widget framework to handle real-numbered positions and transformations properly.

**Comment by AndrewBelt** [comment]
Woohoo! I figured out how to mess with the render stack to correctly cache objects *with the correct zoom level* and then render them back with the correct position. This means *arbitrary* zoom levels will be possible, not just 50%, 25%, 200%, etc. Should only be about 100 lines of code to add the framebuffer stuff.

**Comment by Strum** [comment]
that's something i would like to see.

**Comment by AndrewBelt** [comment]
Fixed with f5e8ba0369685adc61afc9354d3606b877e758ce to caa1a57
