### ISSUE TITLE
 Make dep fails on linux

### ISSUE THREAD

**Issue by phdsg** [VCVRack/Rack#760]
os: debian9
branch: master

basically the same as  #755
```
$ make dep
make -C dep
make[1]: Entering directory '/home/src/Rack-newtry/dep'
cd rtaudio && mkdir -p build
cd rtaudio/build && cmake -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX="/home/src/Rack-newtry/dep" -DAUDIO_LINUX_ALSA=ON -DAUDIO_LINUX_PULSE=ON ..
-- Using Linux PulseAudio
-- Using Linux ALSA
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PULSESIMPLE_LIB
    linked by target "rtaudio" in directory /home/src/Rack-newtry/dep/rtaudio
    linked by target "record" in directory /home/src/Rack-newtry/dep/rtaudio/tests
    linked by target "duplex" in directory /home/src/Rack-newtry/dep/rtaudio/tests
    linked by target "playsaw" in directory /home/src/Rack-newtry/dep/rtaudio/tests
    linked by target "playraw" in directory /home/src/Rack-newtry/dep/rtaudio/tests
    linked by target "audioprobe" in directory /home/src/Rack-newtry/dep/rtaudio/tests
    linked by target "testall" in directory /home/src/Rack-newtry/dep/rtaudio/tests
    linked by target "teststops" in directory /home/src/Rack-newtry/dep/rtaudio/tests
PULSE_LIB
    linked by target "rtaudio" in directory /home/src/Rack-newtry/dep/rtaudio
    linked by target "record" in directory /home/src/Rack-newtry/dep/rtaudio/tests
    linked by target "duplex" in directory /home/src/Rack-newtry/dep/rtaudio/tests
    linked by target "playsaw" in directory /home/src/Rack-newtry/dep/rtaudio/tests
    linked by target "playraw" in directory /home/src/Rack-newtry/dep/rtaudio/tests
    linked by target "audioprobe" in directory /home/src/Rack-newtry/dep/rtaudio/tests
    linked by target "testall" in directory /home/src/Rack-newtry/dep/rtaudio/tests
    linked by target "teststops" in directory /home/src/Rack-newtry/dep/rtaudio/tests

-- Configuring incomplete, errors occurred!
See also "/home/src/Rack-newtry/dep/rtaudio/build/CMakeFiles/CMakeOutput.log".
See also "/home/src/Rack-newtry/dep/rtaudio/build/CMakeFiles/CMakeError.log".
Makefile:161: recipe for target 'lib/librtaudio.so' failed
make[1]: *** [lib/librtaudio.so] Error 1
make[1]: Leaving directory '/home/src/Rack-newtry/dep'
Makefile:52: recipe for target 'dep' failed
make: *** [dep] Error 2

```

**Comment by cschol** [comment]
You need to install the `libpulse-dev` library since PulseAudio is now enabled by default.

**Comment by AndrewBelt** [comment]
I nervous about enabling PulseAudio on the release builds by default, because it requires that you install libpulse.

But Firefox does this, so maybe it's okay.

**Comment by cschol** [comment]
I found that, on a stock Ubuntu 16.04, `pulseaudio` was the only sane way to get Rack running with an internal, on-board sound device. `alsa` was just stuttering, and `jack` was rather not intuitive to get set up (without the recently removed autoconnect).

@AndrewBelt What are your thoughts on using a package management format (e.g. `deb`, `rpm`) to help with runtime dependencies?

**Comment by phdsg** [comment]
@cschol thx. builds.

**Comment by AndrewBelt** [comment]
@cschol Package maintainer are welcome to make them, but I personally don't want to create distro-specific packages.

**Comment by cschol** [comment]
@AndrewBelt Fair enough. I removed `libpulse0` from my libs folder and tried to run Rack. It immediately errors out with a "shared library no found" error. Should be pretty self-explanatory what to do, and at least on Ubuntu it is installed by default.

**Comment by shreeswifty** [comment]
$(rtmidi):
    $(WGET) https://sources.voidlinux.eu/rtmidi-3.0.0/v3.0.0.tar.gz
    $(UNTAR) v3.0.0.tar.gz
    cd rtmidi-3.0.0 && ./autogen.sh && ./configure --prefix="$(LOCAL)"
    $(MAKE) -C rtmidi-3.0.0
    $(MAKE) -C rtmidi-3.0.0 install

**Comment by cschol** [comment]
@shreeswifty This issue is about `make dep` failing on `master`, **not** on the `v0.5` branch. The `rtmidi` issue (404 Error) is known (#551) and the workaround is documented in that issue.

**Comment by phdsg** [comment]
not an issue anymore.
