### ISSUE TITLE
Available devices with alsa on v0.5 vs master on Ubuntu 16.04

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#764]
In a different thread I wrote:
> I found that, on a stock Ubuntu 16.04, pulseaudio was the only sane way to get Rack running with an internal, on-board sound device. alsa was just stuttering, and jack was rather not intuitive to get set up (without the recently removed autoconnect).

The `alsa` issues I had were with Rack `master`. I also tried Rack `v0.5` and was suprised to find it worked fine with `alsa`.

Here the Audio Interface sources for the two branches of Rack:

`v0.5`
![rack v0 5](https://user-images.githubusercontent.com/624427/36825224-99be4912-1cc3-11e8-9dc3-7995898167c8.png)

`master`
![rack master](https://user-images.githubusercontent.com/624427/36825230-9c0c2bd0-1cc3-11e8-827e-7518cfe6710c.png)

Notice, that the internal sound card `Intel PCH` (marked red) only shows up in the Rack `v0.5` branch. If I select that device in Rack `v0.5` `alsa` works fine. On Rack `master`, this device does not show up and any of the other selections for `alsa` leads to just stuttering output. Only `pulseaudio` will work as expected and gives output without drop outs.

I have compiled both versions without any special flags (e.g. `RTAUDIO_ALL_APIS` on `v0.5`) on the same system (freshly installed, stock Ubuntu 16.04).

Why would there be a difference in the device selection in `master`?

**Comment by cschol** [comment]
UPDATE:

Turns out, that switching to `pulseaudio` will cause the internal sound card to be "locked up" and unusable for `alsa`. 

I select `alsa`, shut down Rack, start up Rack. All devices are available, `alsa` works fine:

![rack_master_alsa](https://user-images.githubusercontent.com/624427/36826480-d866898e-1cca-11e8-882e-42c9205c4e33.png)

I select `pulseaudio`, then switch back to `alsa`, I get the picture from the original post and my internal sound card is not available.

The log shows the following output:
```
RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:0,0), Device or resource busy.
RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:0,0), Device or resource busy.
```

I assume this means that `pulseaudio` is still holding on to the previously selected sound device. 
Only restarting Rack will release the sound device to be selectable by `alsa` again.

**Comment by AndrewBelt** [comment]
PulseAudio works fine, except when I shut down the pulseaudio server. Then it hangs when a pulseaudio device is selected.

**Comment by cschol** [comment]
Yeah, it does work fine. The only king is that it takes a few seconds to release when switching back to `alsa`. That can lead to suboptimal behavior, because the device that actually works is not available in the list to select. I am not convinced there is a real issue here, now that I understand better what it going on. I am good closing this.

**Comment by AndrewBelt** [comment]
>the device that actually works is not available in the list to select

That's because ALSA devices are exclusive, and the pulseaudio server you're running is taking hold of it.

**Comment by cschol** [comment]
Right, but the behavior can be confusing (it was to me), since it takes a few seconds for `pulseaudio` to release the device and the expected device is not available for `alsa`. 

No action required here, since my original issue resolved itself after understanding the behavior better. This can be closed.
