### ISSUE TITLE
Feature Request: File.Reload menu option (w/ MOD-R hotkey) to reload current patch

### ISSUE THREAD

**Issue by dirkleas** [VCVRack/Rack#768]
Add a File.Reload menu option to quickly reload the current patch without having to work through the File.Open dialog and reselect patch. If there's no current patch, it would trigger the standard File.Open dialog. I often hack patches wildly and often revert back to last saved version. I also regularly hack patches from the file system since they're quite intuitively crafted JSON. This would be a potentially significant workflow time saver.

I'd be happy to submit a pull request with necessary tweaks (e.g. Toolbar.cpp, RackWidget.cpp, RackScene.cpp -- GLFW_KEY_R looks available, and app.hpp).

Thanks for considering...

**Comment by AndrewBelt** [comment]
Good idea. Implemented with my working changes, will push in a couple of days.

**Comment by AndrewBelt** [comment]
Gah, Ctrl+R is taken by *Randomize Module*. :man_facepalming:  Removing key command for this.

**Comment by dirkleas** [comment]
how about CTRL-SHIFT-O?

**Comment by dirkleas** [comment]
GLFW_KEY_O, then if (windowIsModPressed() && windowIsShiftPressed()) seems like the appropriate combo and consistent with Save/SaveAs implementation

**Comment by dirkleas** [comment]
can you add CTRL-SHIFT-O as key command to enable instrumentation? I often use MIDI-to-keystroke in my toolchain to automate reopening externally transformed patches for such tasks as importing submodules, layout management, etc.. thanks in advance
