### ISSUE TITLE
Rack can't find my JACK server

### ISSUE THREAD

**Issue by jamshark70** [VCVRack/Rack#769]
Ubuntu Studio 16.04
Rack 0.5.1 (ZIP file downloaded from the main site)

1. Start the JACK server in qjackctl. JACK is working fine with SuperCollider, PD etc. The audio interface is a Scarlett 2i4.

2. `./Rack.sh` -- application window opens fine.

3. Add an audio interface module.

4. The only option is ALSA.

I might not mind that so much, except that I then stopped the JACK server (to free up the hardware), relaunched Rack, and tried to use Rack through ALSA. VCO -> VCF -> Interface. It glitches quite badly on each hardware buffer (I know it's the hardware buffer because the time between glitches changes depending on the buffer size).

I suppose it might work better with JACK, but for some unknown reason (and despite previous issues claiming that JACK should be working), I'm getting nothing.

One possible wrinkle is that I don't use DBus. Is that required for Rack -> Jack?

Thanks.

**Comment by ZuluEchoRomeOscar** [comment]
https://github.com/VCVRack/Rack/wiki/Add-Support-for-Jack-on-Linux-(dev)

**Comment by jamshark70** [comment]
I see.

I read the FAQ and the installation page in the manual, didn't find this. Would be worth noting in one or both of those places.

Thanks for the tip -- closing.

**Comment by JeffGreenlee42** [comment]
Hey,  I don't know if this applies to your setup,  but one limitation about Jack that I have learned:   When you setup JACK it will ONLY exchange signals within a specific TYPE of Port Audio driver.   I don't know the specfics of Linux,  but on Windows,  this can be a problem.  For example,  In Windows (10 at least)  you cannot Route an audio stream from a WDM driver to an ASIO driver.... At least in JACK   A really popular bus people use in Windows is "VB Audio".... but that is WDM driver .. not ASIO  .. JACK will work with both types.. buit will not combine..     I don't know, but I'm guessing that JACK might suffer a similar limitation on LINUX as well.  OSX  has built a workaround for this by using "aggregators" in CORE.   If you dig deep enough into the JACK documentation, there is mention of this limitation. 

Hope that helps!

**Comment by jamshark70** [comment]
I'm quite sure that's not an issue in Linux.

As far as I've seen, in Linux, JACK completely abstracts the audio driver away from the client software.

After I built it with JACK support, Rack is working fine.

I'm still of the opinion that the lack of official JACK support will cause a lot of Linux users to give up, quickly, especially when ALSA didn't deliver a clean signal at all. But that's not a discussion for this thread.

**Comment by JeffGreenlee42** [comment]
Yes. I have seen threads somewhere on a JACK forum where people complained
about issues with ALSA. I wonder (and hope) that there will be future
improvements and newer versions of JACK! I am also surprised this is an
issue in Linux! Correct me if I'm wrong, but my guess is the majority of
VCV rack developers work in Linux?

**Comment by jamshark70** [comment]
> I wonder (and hope) that there will be future improvements and newer versions of JACK!

To be precise, (in Linux) JACK isn't the problem here. Connecting Rack to JACK resolved the ALSA audio glitching 100% *and* with reasonable CPU usage (2-4% for a handful of modules -- by contrast, a couple of my students independently tried Rack on Mac and found the audio interface module alone uses 90%).

Others mileage may vary but my experience was pretty clear: Rack out of the box was unusable. Rack built with "unofficial" Jack support works beautifully. (As a plus, when I needed a spectrum analyzer, I could use Jack to patch Rack into SuperCollider, piece of cake.)

**Comment by JeffGreenlee42** [comment]
Similar experience for me.  My ASIO driver (Saffire Pro)  does not work well with Rack,  especially when other software (like DAWs) is also vying for the same resources.   JACK saved my ass!   I am hoping the situation will improve with the coming Bridge in v. 0.6  !!!

I do have a MAC Mini,  and yes,  I have noticed that there is a definite limitation on how many modules I can have running in Rack before I start having Audio and/or performance issues.  It's a CPU monster on OSX!     My PC has a beefy processor.. with 8 cores.. so I have not had those hit-the-ceiling performance  issues on Windows 10... The issues are much more about conflicts between multiple software instances, all competing for the same audio interface...  Focusrite, (At least the Saffire Firewire devices)   is only happy when it has just one customer.  :)  That's where JACK shines.

**Comment by Newk77** [comment]
Please reconsider to add Jack support by default in the linux build.... it's supposed to be a professional audio application, right?
