### ISSUE TITLE
Patch name in title bar or somewhere

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/Rack#77]
Very Minor issue and low-priority request (but I guess very easy to implement)

When you open a  patch, the name of the patch is not shown anywhere so when I got bak to it after some other work I don't know what I am working on...maybe simply add in the title bar or toolbar?

**Comment by AndrewBelt** [comment]
Great idea! I'll add this along with `Save` and `Save As` so it keeps track of the filename/path.

**Comment by AndrewBelt** [comment]
Added in 970e227c
