### ISSUE TITLE
Build failure "RandR library not found"

### ISSUE THREAD

**Issue by jamshark70** [VCVRack/Rack#771]
```
$ git clone https://github.com/VCVRack/Rack.git
$ cd Rack
$ git checkout v0.5.1
$ git submodule update --init --recursive
$ make dep

CMake Error at CMakeLists.txt:222 (message):
  The RandR library and headers were not found


-- Configuring incomplete, errors occurred!
See also "/home/dlm/share/Rack/dep/glfw-3.2.1/CMakeFiles/CMakeOutput.log".
See also "/home/dlm/share/Rack/dep/glfw-3.2.1/CMakeFiles/CMakeError.log".
Makefile:92: recipe for target 'lib/libglfw.so' failed
make[1]: *** [lib/libglfw.so] Error 1
make[1]: Leaving directory '/home/dlm/share/Rack/dep'
Makefile:46: recipe for target 'dep' failed
make: *** [dep] Error 2
```

This is setting myself up to build rtaudio with JACK support.

I found https://github.com/VCVRack/Rack/issues/317, which says:

> I would also like to contribute my solution to building on Ubuntu 16.04 LTS:
> 
> Install dependencies: libx11-dev libgl1-mesa-dev libglu1-mesa-dev libjack0 libjack-dev libasound2-dev librtaudio4v5 librtmiti-dev libgtk2.0-dev xorg-dev

OK...

```
$ sudo apt-get install libx11-dev libgl1-mesa-dev libglu1-mesa-dev libjack0 libjack-dev libasound2-dev librtaudio4v5 librtmiti-dev libgtk2.0-dev xorg-dev

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package librtmiti-dev
```

Now I've got other things to do.

What's the next step?

**Comment by svenkeidel** [comment]
Maybe you meant to install `librtmidi-dev` with and _d_.

**Comment by AndrewBelt** [comment]
If installing local dependencies doesn't work, system dependencies is an even sketchier solution.
Are you running Wayland or something? It would help to know a little about your system, which is the purpose of the bug report template which you deleted when creating this issue.

**Comment by jamshark70** [comment]
I don't even know what Wayland is. I'm a longtime SuperCollider user, exploring Rack as an interface for teaching synthesis. I've successfully built some software but I am not an expert on build systems, dependencies or graphics systems.

I'm running Ubuntu Studio 16.04.

**Comment by jamshark70** [comment]
OK, it's definitely getting further now. Thanks for the advice.

From mainland China, I needed a VPN to get http://www.mega-nerd.com/SRC/libsamplerate-0.1.9.tar.gz.

Letting it run, will report when it's finished.

**Comment by AndrewBelt** [comment]
Don't check out the tags directly. Just check out the branch if you install from source

**Comment by AndrewBelt** [comment]
Don't check out the tags directly. Just check out the branch if you install from source

**Comment by jamshark70** [comment]
Running successfully. Got a few other comments, but I'll close this and send them to the contact email later.

Thanks!
