### ISSUE TITLE
[FEATURE REQUEST] Keyboard shortcut to pull up Module Browser

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#774]
It would be handy to have a keyboard shortcut to pull up the Module Browser dialog (for example, Ctrl-B). Right now, it looks like the browser is only accessible via mouse right-click. I take my hand of the mouse to use the smart search typing the modules name, and/or use up/down arrows, which then allows me to hit Enter to place the module. I then use the mouse again to finalize placement in the Rack. 
From a workflow perspective, being able to use the keyboard exclusively for module SELECTION, would be more efficient.

**Comment by AndrewBelt** [comment]
`Enter` works.

**Comment by cschol** [comment]
Doh. I knew I was missing something...Thanks.
