### ISSUE TITLE
Float to Hz value: TransparentWidget

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Rack#775]
Win7... 0.6dev...

I remember reading up on this somewhere can't find the reference atm. Hopefully an easy enough solution. I want to display the Hz value of the Freq param on an LFO I'm working on as a Display widget. I Have the display widget all set up but the freq param is showing on the display as "-8.0 to 6.0". How would I go about displaying the Hz value for the frequency parameter. Its pretty much the last piece of the puzzle I need to dist.

I do not have the source up on my repo just yet. Is there piece of code in rack already that will do this or will I have to code each float to Hz value.  `-8.00f == 0.0625Hz` `6.0f == 3Hz` `-1.0f == 0.5Hz`

**Comment by AndrewBelt** [comment]
Well, how does your LFO convert voltage to frequency? Surely you compute the frequency from the parameters and CV to do the phase increment. Just use that value.

**Comment by Coirt** [comment]
Currently using -8 to 6 of the FREQ_PARAM and that is what is being displayed. It shows the knobs float value. Winging it tbh have no idea how it converts. Should I use the Delta phase?

**Comment by AndrewBelt** [comment]
Hint: https://github.com/VCVRack/Template/blob/master/src/MyModule.cpp#L40-L44

**Comment by Coirt** [comment]
Cheers Andrew that's where I read it.
