### ISSUE TITLE
Dev instructions for enabling JACK support on Linux

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#776]
Instructions for enabling `JACK` support on Linux were updated on the [wiki](https://github.com/VCVRack/Rack/wiki/Add-Support-for-Jack-on-Linux-(dev)).

Those instructions will not work for `v0.5`, since `RTAUDIO_ALL_APIS` only defines `-DAUDIO_LINUX_ALSA=ON` in the dep Makefile in `v0.5`.

Maybe adding a clarifying note about applicability of those instructions to `v0.6+` would help.

**Comment by AndrewBelt** [comment]
It's a public wiki, feel free

**Comment by cschol** [comment]
OK. Wasn't sure if you wanted people to edit. Thanks.
