### ISSUE TITLE
AUDIO_LINUX_JACK is not a valid rtaudio option?

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#777]
In dep `Makefile`, `RTAUDIO_ALL_APIS` defines `AUDIO_LINUX_JACK` for the Linux platform.

The `rtaudio` library does not seem to support this flag, see [CMakeLists.txt](https://github.com/thestk/rtaudio/blob/master/CMakeLists.txt).

`JACK` support is **not** enabled with the `RTAUDIO_ALL_APIS` option on Linux.

**Comment by AndrewBelt** [comment]
Fixed typo in b77274a, which is unusual because I never manually type those things, but oh well. Untested.

**Comment by cschol** [comment]
Tested on Ubuntu 16.04. Works now as expected. Thank you.
