### ISSUE TITLE
Commandline parameters, headless mode, multiple instances etc...

### ISSUE THREAD

**Issue by unfa** [VCVRack/Rack#779]
I'm thinking about options to use VCV Rack in in conjunction with a classic DAW, like Ardour or other sequencers possibly for live performance or just studio work.

I think  that in the hardware modular synthesis the lack of instant recall is considered a feature. VCV Rack however allows to save and load patches which to me is a huge plus, in comparison to the hardware side. It makes it possible to create more complex structures.

I'd love to be able to run VCV rack from commandline, tell it to load a specific .vcv file and expose audio/midi ports for JACK so that I can patch it with other ports (sequencers, DAWs, hardware) manually.

I did that with oteher softwre like Fluidsynth (Qsampler) for playing with SFZ files live.
I usually do all my patching with Carla for live setups.

Right now it seems that VCV Rack connects itself to audio or MIDI devices. I'd like to have a "floating" mode where it doesn't autoconnect, but just exposes named audio and MIDI ports to JACK so I can route it where I want, and not have it interfere with that.

That'd also allow to use multiple instances of Rack, each running a different patch - to make them play parts sequenced in a DAW for example. This could enable people to compose tracks using VCV Rack, and be able to change the patches and MIDI data, instead of just jamming, recording audio and trying to cut out something useful later :)

An additional headless mode could be great for running lots of VCV Rack instances  - for situations where all controls are routed in through MIDI CC and/or CV ports, and there's no need to rendering GUI, but saving on memory and CPU cycles could be handy.

What do you think?

**Comment by AndrewBelt** [comment]
This issues needs to be broken into multiple issues, so I'm closing this.

Rack is not designed to be run in multiple instances so I'll save you the time for that feature request.

**Comment by unfa** [comment]
I see. Thanks for the info!
