### ISSUE TITLE
[Tag Request] "Modulator"

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#783]
A tag for "modulation effect" would be nice. Typically these are things like phasers, flangers, chorus, auto-pan. Our "Frequency Shifter" might be a modulator (currently we list is as "effect" and "ring modulator". Our upcoming "vocal animator" will probably be "filter" and "effect"?

**Comment by AndrewBelt** [comment]
I'm not really sure what a "modulator" is. That's a vague term.

**Comment by squinkylabs** [comment]
Good point. I guess frequency shifter is its own thing. other than "effect" and "frequency shifter" I don't know... Although I think an pitch shifter (like autotune) would also have no obvious tag in the present schema - so perhaps there is a tag for pitch changing things? Don't know.

As far as the class of effects that are (basically) and LFO driving a filter, these are usually called modulation effects. Some you already have specific tags for (phaser, flanger), some are tagless (leslie/rotating speaker, our vocal animator).

Having super specific tags is great for common modules. We like to make things that haven't yet been put into VCV modules, so our first to modules are "tagless".

Here are some links to the first three google hits on "modulation effects":
[https://documentation.apple.com/en/logicstudio/effects/index.html#chapter=9%26section=0%26tasks=true]
[https://www.uaudio.com/blog/modulation-effects-basics/]

[http://www.gibson.com/News-Lifestyle/Features/en-us/effects-explained-modulation.aspx]

**Comment by AndrewBelt** [comment]
I'll just leave it at "effects" then. The quantity of modules with this tag are comparable to most of the other tags. The name and panel of the module will ultimately designate what it is.
