### ISSUE TITLE
Stop being so awesome.

### ISSUE THREAD

**Issue by ryan-allen** [VCVRack/Rack#784]
VCV rack is too awesome stop being so awesome.

**Comment by MarcBoule** [comment]
VCV rack is quite awesome continue being so awesome.
(Fixed that for you!) :-)

**Comment by AndrewBelt** [comment]
:laughing: :+1:

**Comment by MarcBoule** [comment]
I'm developping a module, and the architecture is a pleasure to code in. Well done!

**Comment by modlfo** [comment]
Closing as "Won't fix" since Rack will never stop being awesome.

**Comment by MarcBoule** [comment]
One of the best issues ever in this huge pile of issues! ;-)
