### ISSUE TITLE
Black Rack Bug#2

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Rack#786]
#782

https://www.youtube.com/watch?v=e9Fp0XvVq3U&feature=youtu.be

https://github.com/Coirt/Bark/tree/0.6dev

https://github.com/Coirt/Bark/blob/0.6dev/src/TrimLFO.cpp#L164

As before trying to display Hz value came across a bug with the screen turning black. Be great if two solutions came from this. Hz displaying on my LFO module and black screen associated with the above code fixed! The parameter calculation is causing the bug I think - (dodgy code)

**Comment by AndrewBelt** [comment]
Does it work if you remove the *DisplayWidgets? Just wanting you to narrow down your problem.

**Comment by Coirt** [comment]
No black screen with 

```
	float frq = params[FREQ_PARAM].value;
	frq = clamp(frq, -16.0f, 12.0f);
	// The default pitch is C4 // Default frequency is 0.25f
	freqHz = 0.25f * powf(2.0f, frq);
```
or 
```
	float frq = params[FREQ_PARAM].value;
	frq = clamp(frq, -16.0f, 12.0f);
	// The default pitch is C4 // Default frequency is 0.25f
	freqHz = 2.0f * powf(0.25f, frq);
```
Screen shifts as if zoomed, in video, ↑↑ no black screen

Get not a number `nan` display with
```
	float frq = params[FREQ_PARAM].value;
	frq = clamp(frq, -16.0f, 12.0f);
	// The default pitch is C4 // Default frequency is 0.25f
	freqHz = 0.25f * powf(-2.0f, frq);
```
No black screen with the widget commented out. https://github.com/Coirt/Bark/blob/0.6dev/src/TrimLFO.cpp#L390

**Comment by AndrewBelt** [comment]
I meant in your draw routines. Narrow down the line in your `draw()` methods.

**Comment by Coirt** [comment]
Its not going to make the display with the later so its related to the display. 

For the `nan` the values show for "0.0" "0.06" and "1024" in between values are `nan`

Narrowed it down to the array changed to `char display_string[24];`
https://github.com/Coirt/Bark/blob/0.6dev/src/TrimLFO.cpp#L239

No black screen

**Comment by AndrewBelt** [comment]
Not sure if this is the problem, but

```cpp
sprintf(display_string, "%5.2f", *freqHz);
```
is a really great way to segfault. Use
```cpp
snprintf(display_string, sizeof(display_string), ...
```

**Comment by Coirt** [comment]
`snprintf(display_string, sizeof(display_string), *freqHz;` ?

Get an error on that. 

Not really the issue trying to display the Hz value still. Honestly no clue how to do it, now 2 days at it! Limited coding knowledge.

Issue with calculating it is the minus and plus values of the parameters. Can divide 0.25 default Hz by 8 to get the -16.0 value but have to multiply by 96 to get the +12.0 value the in between values idk. Hinted earlier in #775 but that's as close as I came to a solution and there is no source I can look up to view help.

**Comment by AndrewBelt** [comment]
http://en.cppreference.com/w/c/io/fprintf You need to learn to avoid undefined behavior which can cause segfaults. You're probably corrupting the main thread stack which is killing the display.

**Comment by Coirt** [comment]
Okay gathered from that, the "%5.2" is a multiplier of freqHz which is calculated using `powf(base, exponent)` line#169 is that calculated correctly even. So it would be just the question of finding the right multiplier for the display.

Strangely only getting a warning in the console about that now.
```
src/TrimLFO.cpp: In member function 'virtual void FreqDisplayWidget::draw(NVGcontext*)':
src/TrimLFO.cpp:240:42: warning: conversion lacks type at end of format [-Wformat=]
   sprintf(display_string, "%5.2", *freqHz);
                                          ^
src/TrimLFO.cpp:240:42: warning: too many arguments for format [-Wformat-extra-args]

```
Not displaying anything in the display now also with same code as before this is after inputting the code from previous post `sprintf`.

**Comment by AndrewBelt** [comment]
I have no idea what you're talking about. All I know is that you're writing garbage to the stack and then passing that garbage to `nvgText`. If you still can't figure it out, the correct line is
```cpp
snprintf(display_string, sizeof(display_string), "%5.2f", *freqHz);
```

**Comment by Coirt** [comment]
Well what I'm talking about is displaying Hz as the value in the display. Got the "garbage" from you Andrew so are you pissed of with me or yourself can't tell. No need for the shitty attitude though. Hard enough trying to learn this with a limited background in coding on my own. We all start somewhere.

**Comment by AndrewBelt** [comment]
[Garbage](https://en.wikipedia.org/wiki/Garbage_(computer_science)) is a technical term for stack overrun data. Does my fix solve your issue?

**Comment by Coirt** [comment]
I understand that, its a tone of your text I'm talking about. I'm asking for help. It does but displaying the Hz value is what I'm looking to do. It has not been done yet in an open source module so everyone's modules will benefit from the solution.

**Comment by AndrewBelt** [comment]
My apologies. Since I am going overdrive for the Rack 0.6 deadline, I often try to distract myself with GitHub issues during breaks. Unfortunately this habit results in low amounts of patience with others, so I should adopt a policy to respond to much fewer GitHub issues and only save the critical ones for my free time. I still don't have time to help you at this point, but I should have known that at the beginning of this conversation.

**Comment by david-c14** [comment]
Coirt, if you still have trouble with this, I can try to help.

As I understand it, you have fixed your black screen issue, but you still have trouble converting your parameter to a Hz value.    If you can give me three or four examples of parameter float values and what the corresponding Hz value should be, I'll try to formulate the correct equation for you.

**Comment by Coirt** [comment]
Thanks very much @david-c14. I managed to wrestle it into submission. I'm nearly positive it is showing the correct Hz value now. Have it within 7 decimal places so working out quite nicely. Just a couple more things to do to wrap the module up. They will put the icing on the cake so to speak. Could very well update around or before April 1st with those features if anyone can manage to find them.
