### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Drmcallister** [VCVRack/Rack#787]
Ability to assign and use tags for controls for use in "live performances..." This would be user-defined keyboard keys.
A keystroke to set the cursor to a particular knob or button, jump-scrolling the screen if necessary.  The ability to set these to display as an option over the display would be nice, but perhaps a cpu hit?

Related, then upon jump, have preset keystrokes for 'increase', 'decrease', 'min', 'max', and maybe definable preset values ('cntl-c = 75%' for example.)

Having watched Nigel's vids, I'm surprised that he hasn't requested this.  LOL

**Comment by Atavic** [comment]
MiIDI Learn:https://github.com/VCVRack/Rack/issues/50

**Comment by modlfo** [comment]
Duplicate of #50
