### ISSUE TITLE
bridge.cpp undeclared identifier 'close'

### ISSUE THREAD

**Issue by AScustomWorks** [VCVRack/Rack#791]
Operating system(s): Os X 10.12.6
Version if official Rack release, commit hash and/or branch if from source: master

I guess you are still working on this file, but just in case:

Just checked out and pulled master, got this errors when doing  make:
`src/bridge.cpp:226:8: error: use of undeclared identifier 'close'
        err = close(client);

src/bridge.cpp:283:3: error: use of undeclared identifier 'close'
                close(server);
`

**Comment by AndrewBelt** [comment]
Fixed in fac8f8e. I'm playing wack-a-mole except with operating systems.

**Comment by dBiz** [comment]
The problem appear on Windows too ;)

 src/bridge.cpp:226:8: error: 'close' was not declared in this scope
  err = close(client);
        ^~~~~

In file included from src/bridge.cpp:2:0:
src/bridge.cpp: In lambda function:
src/bridge.cpp:283:3: error: 'close' was not declared in this scope
   close(server);

**Comment by dBiz** [comment]
I've managed to compile, just put back
#include <fcntl.h>

and it works!

**Comment by AndrewBelt** [comment]
Fixed in 0aa92f2e9a77c812487fb5bb78f90d0c164d6d50
