### ISSUE TITLE
make run/debug broken on Windows

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#792]
`make run` and `make debug` are broken on Windows. The `PATH` can contain a directory with spaces in the name, so the `PATH` environment variable must be quoted, like so:

```
ifeq ($(ARCH), win)
	# TODO get rid of the mingw64 path
	env PATH="${PATH}":dep/bin ./$<
endif

[...]

ifeq ($(ARCH), win)
	env PATH="${PATH}":dep/bin gdb -ex run ./Rack
endif
```

**Comment by AndrewBelt** [comment]
Thanks, fixed in 40144f7
