### ISSUE TITLE
Crash on Mac OS 10.11.6 at startup (0.5.1)

### ISSUE THREAD

**Issue by fractalgee** [VCVRack/Rack#795]
The install from VCVRack.com of Rack 0.5.1 for MacOS X crashes on startup in:

Thread 7 Crashed:
0   libcrypto.1.1.dylib           	0x000000010fb04345 ecp_nistz256_points_mul + 1333
1   libcrypto.1.1.dylib           	0x000000010fad58fc EC_POINT_mul + 76
2   libcrypto.1.1.dylib           	0x000000010fad2eef ec_key_simple_generate_key + 191
3   libcrypto.1.1.dylib           	0x000000010fb27fcb EVP_PKEY_keygen + 91
4   libssl.1.1.dylib              	0x000000010fc839aa ssl_generate_pkey + 58
5   libssl.1.1.dylib              	0x000000010fc98e21 tls_construct_client_key_exchange + 1585
6   libssl.1.1.dylib              	0x000000010fc97170 state_machine + 1600
7   libcurl.4.dylib               	0x000000010f9aa62d ossl_connect_common + 5894
8   libcurl.4.dylib               	0x000000010f9ad514 Curl_ssl_connect_nonblocking + 105
9   libcurl.4.dylib               	0x000000010f984f30 https_connecting + 23
10  libcurl.4.dylib               	0x000000010f99cb0d multi_runsingle + 1116
11  libcurl.4.dylib               	0x000000010f99c5b7 curl_multi_perform + 117
12  libcurl.4.dylib               	0x000000010f9978c1 curl_easy_perform + 375
13  com.vcvrack.rack              	0x000000010f6429ad rack::requestJson(rack::RequestMethod, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, json_t*) + 669
14  com.vcvrack.rack              	0x000000010f612fcc rack::checkVersion() + 108
15  com.vcvrack.rack              	0x000000010f5e6dcd void* std::__1::__thread_proxy<std::__1::tuple<void (*)()> >(void*) + 93
16  libsystem_pthread.dylib       	0x00007fff8543399d _pthread_body + 131
17  libsystem_pthread.dylib       	0x00007fff8543391a _pthread_start + 168
18  libsystem_pthread.dylib       	0x00007fff85431351 thread_start + 13

MacPro 2,1 with NVidea GTX 750 Ti and MacOS 10.11.6 and NVidea web driver for this version OS. 

What ails the libcrypto so much that it fails so badly?

**Comment by AndrewBelt** [comment]
Duplicate issue
