### ISSUE TITLE
Only one note is being played when multiple keys in midi device are pressed

### ISSUE THREAD

**Issue by DJDaniel7777** [VCVRack/Rack#796]
Hello everyone!
Maybe it sounds like a begginer question but... my midi device does not reproduce more than one note every time. Is it possible to make like a chord? Because if I press three keys together, only the last one that I have pressed is being played.
Thank you!

**Comment by AndrewBelt** [comment]
Please fill out the template when posting bug reports. Did it not show up when you posted, or did you just not read it?

**Comment by AndrewBelt** [comment]
You are using a monophonic MIDI interface and expecting it to be polyphonic. Read https://en.wikipedia.org/wiki/Polyphony_and_monophony_in_instruments
