### ISSUE TITLE
question about using Bridge

### ISSUE THREAD

**Issue by davephillips** [VCVRack/Rack#797]
I've built the latest source pull and notice that the Bridge is now explicit in the audio interface device selection. I'd like to test it if that's do-able at this point but I confess I have no idea where/how to begin. Any advice/suggestions ? I have a variety of Linux DAWs to test it, though most of my work is done on Bitwig or Ardour.

**Comment by AndrewBelt** [comment]
Not yet. Follow #31 for news and instructions. Closing this issue
