### ISSUE TITLE
SVG Knob v0.6 changes help needed

### ISSUE THREAD

**Issue by AScustomWorks** [VCVRack/Rack#798]
Pulled the latest master and I'll have to update all my knob graphics to the proper sizes, all right there but I have to make changes on the code side too I think:
I did a quick test updating one knob svg file, log says it loads fine but the graphic is missing.
I can click where the knob is supposed to be and change the parameter so I'm narrowing the error to here:
```c++
struct as_KnobBlack : SVGKnob {
	as_KnobBlack() {
                minAngle = -0.83 * M_PI;
		maxAngle = 0.83 * M_PI;
		sw->svg = SVG::load(assetPlugin(plugin, "res/as-knobBlack.svg"));
		sw->wrap();
		box.size = sw->box.size;
	}
};
```
Commented out box.size but nothing changes, so I'm missing something but can't find what it is.

Thanks!

**Comment by AScustomWorks** [comment]
Found the answer:
```c++
//replace the original line
sw->svg = SVG::load(assetPlugin(plugin, "res/as-knobBlack.svg"));
```
```c++
       //with this one:
	setSVG( SVG::load(assetPlugin(plugin, "res/as-knobBlack.svg")) );
```

**Comment by AndrewBelt** [comment]
Yes, `SVGKnob::setSVG()` sets the shadow based on the size of the internal SVGWidget.

**Comment by Coirt** [comment]
@AScustomWorks that's great freddy thanks for the post.

**Comment by gbrandt1** [comment]
hi, may i reopen this ... 
does anybody have examples for custom resizing of components after setSVG?

**Comment by AndrewBelt** [comment]
I have removed support for resizing knobs. It's bad behavior that shouldn't have been added in the first place. The correct thing to do is resize the SVG with Inkscape, which defined the "proper" size of the physical component.
