### ISSUE TITLE
missing knobs after refactor

### ISSUE THREAD

**Issue by JerrySievert** [VCVRack/Rack#799]
it looks like after the knob refactor, some have gone missing, for instance `RoundSmallBlackSnapKnob` is no longer available.

should we assume that those are gone for good and redevelop them locally, or is this just an oversight?

thanks!

**Comment by AndrewBelt** [comment]
I made a mistake and have corrected the sizes to Grayscale's original designs.
`RoundBlackSnapKnob` is the new class which is the same size as the old `RoundSmallBlackSnapKnob`. But if you want the 10mm size, you'll have to create your own subclass.

**Comment by JerrySievert** [comment]
(yes, I know about the knob changes, but `RoundBlackKnob` is a bit different size than `RoundSmallBlackKnob`, even discounting the shadow).

**Comment by JerrySievert** [comment]
aha, your message beat my second message.  thanks, I'll update!

**Comment by Coirt** [comment]
#798

FYI
