### ISSUE TITLE
Coloured ring around patch socket light up in colour of patch cable

### ISSUE THREAD

**Issue by sanderbaan** [VCVRack/Rack#80]
I would like to see if signal is coming out / in on a input/output, it hard to see whats going on in big patches. A way to do it is to light up the coloured  ring around the patch socket in the colour of the cable, it should flash at the rate of the signal going thru it. See the attached screenshot the yellow right should flash bright yellow then.

![screen shot 2017-09-14 at 20 44 32](https://user-images.githubusercontent.com/15910225/30448019-e6cf7e74-998d-11e7-9801-f432b8c86263.png)

**Comment by AndrewBelt** [comment]
Your screenshot isn't loading, but this is a good idea. A rifle switch could be put in the toolbar.

**Comment by sanderbaan** [comment]
Yes would be awesome :) thanks for considering

**Comment by AndrewBelt** [comment]
LEDs *inside* the black part of the stackable cables might be a good idea.

I don't know if these work IRL, but they would look nice in Rack (as a optional feature).

![](http://i.ebayimg.com/images/g/lAgAAOSwn9lXJ6xV/s-l300.jpg)

**Comment by milholen** [comment]
I like the "inside LEDs" (as an optional feature). Here's another real-world example:
https://division-6.com/shop/Jacklight-3.5mm-Red-Blue-Test-LED.html

**Comment by AndrewBelt** [comment]
![2017-10-08-152807_368x431_scrot](https://user-images.githubusercontent.com/338179/31320135-4cbb200a-ac3d-11e7-9712-e2d1ac0eb5ce.png)
It's actually in the codebase already but commented out

**Comment by sanderbaan** [comment]
Awesome! which part of the code? would like to check it out so can build a local build with it turned on

**Comment by AndrewBelt** [comment]
At the bottom of WireWidget.cpp

**Comment by sanderbaan** [comment]
Yes cool, I checked it out...it would even be greater if the color of signal is in the cable color, would that be hard to do? I think it will look better...

**Comment by AndrewBelt** [comment]
What should the negative color be?

**Comment by sanderbaan** [comment]
It now goes from black to green no? maybe from black to color of the cable

**Comment by AndrewBelt** [comment]
Look again, if the signal is negative the light turns red.

**Comment by sanderbaan** [comment]
Ah didnt notice..yes then it makes sense its like this.

**Comment by sanderbaan** [comment]
would be nice if it gets into 0.40 :)

**Comment by AndrewBelt** [comment]
Final design review before I decide to keep it. Too bright/dim, too large/small?

![2017-10-09-092839_962x388_scrot](https://user-images.githubusercontent.com/338179/31340505-5a350092-acd4-11e7-8a63-e2439701e55e.png)

**Comment by sanderbaan** [comment]
I think its perfect like this ;)

**Comment by AndrewBelt** [comment]
Added with 2c69f2f561b3ed49eaa44de411fedc4e2ba29994
