### ISSUE TITLE
Rack Build Issue with nanovg on Windows 7 x64 

### ISSUE THREAD

**Issue by dividetoinfinity** [VCVRack/Rack#804]
Hi, 

I am having issues with building: 

Operating system(s): Windows 7 x64
Commit hash: baadbda40d79008d1eacffdeecfdad221d42c8a5

I Cloned submodules:

	git submodule update --init --recursive

Then Built the dependencies locally:

	make dep

Then attempted to build Rack: 

        make

output:
make: cc: Command not found
compile.mk:53: recipe for target 'build/dep/nanovg/src/nanovg.c.o' failed
make: *** [build/dep/nanovg/src/nanovg.c.o] Error 127

Many thanks

**Comment by AndrewBelt** [comment]
Did you install the recommended dependencies from https://github.com/VCVRack/Rack#windows ?

**Comment by dividetoinfinity** [comment]
Many thanks for the prompt reply, great software btw : ) 

Yes, I used the MinGw64 command line in Msys2 as per the instructions and installed the prerequisities: 

pacman -S git make tar unzip mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake autoconf automake mingw-w64-x86_64-libtool

**Comment by AndrewBelt** [comment]
What does `cc --version` display?

**Comment by dividetoinfinity** [comment]
Not found : 0
$ cc --version
bash: cc: command not found

**Comment by dividetoinfinity** [comment]
Hi Andrew, 

I managed to get this working. I edited the compile.mk file and added the following a few lines down: 

CC=gcc

Again, many thanks for the awesome modular software - Looking forward to having a go at writing a few plugins. I would also be interested to hear if there is any other way to contribute : ) Adam Jocepos
