### ISSUE TITLE
Feature Reques: Rack/Module Introspection

### ISSUE THREAD

**Issue by dirkleas** [VCVRack/Rack#806]
Provide unified API mechanism for rack state and module state/feature introspection, with the later providing an enumeration of all runtime mutable features/state (for extra credit, include immutable features (ala' documentation, et'al). The most common use case would be rack/macro-level orchestration and modulation across "everything". A few of high-value scenarios would be 1) an "all-powerful" OSC (open sound control) modulation module, or 2) command line scaffolding/infrastructure for facilitating the modeling and auto-generation of patches, or 3) integration with emerging technologies like machine learning (ML), virtual reality (VR) for applied generative patches.

As always, TIA for your consideration. I look forward to implementing one or more of the use cases above and many more.

**Comment by AndrewBelt** [comment]
I have made `static std::vector<Module*> modules;` a global with a warning message, but it won't be supported and will be discouraged from using. dd402b8
