### ISSUE TITLE
Shadows tweak & Feedback

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Rack#811]
Just some thoughts and feedback on the shadows of knobs/ports

Firstly the static position of the shadow will cater towards dev's editing the shadow position themselves which will in turn make for different shadow positions for different modules which could look weird with multiple modules in rack. If the positioning is unionised so dev's can't override its position the standards in my honest opinion would make rack more appealing.

Currently the angle of the default shadow might do with some tweaking I feel to be just off to the left or right instead of straight down. The current shadows I think stick out just a little too much. If the idea of the shadow is to give the user a less flat background then working with the below angles might better aid this subtlety. Light source increased in distance away from the rack space towards the users space instead of vertically looking straight down, less shadow more 3D space. Small detail that the user may not think about but your brain will see it even if you are not aware it is there.
```
shadow->box.size = sw->box.size;
shadow->box.pos = Vec(-1, sw->box.size.y * 0.08); /*(multiplier)+longer cast, -shorter cast*/
```

I propose also a tracking system for the light source casting the shadow(s) in relation to the modules position on the rack. Where it is in relation to the module it is casting a shadow on. Middle on window left/right, left+right (dual). When you move a module around the shadow position changes also in real time or when you let go of the mouse. Hopefully this will not be too cpu intensive. This would give unity to the shadow position and the look of rack.

just a nod: LindenbergResearch has the `vg` shadow looking spot on also with the blur and subtlety.

**could switches be added to shadows, modules with the toggle type switch and even the flat type could benefit.

A little long winded for a Saturday just my thoughts on it, apologies if it sounds too negative.

**Comment by AndrewBelt** [comment]
I'm going to trust my designer on this one. The changes you've suggested follow 2005-2010 trends, but Rack breaks from these skeuomorphism rules.

**Comment by Coirt** [comment]
Okay that's all fine. Think we have one thing in common we are resolute enough to follow what we believe in.

**Comment by jonheal** [comment]
The shadows are a nice bit of eye candy, but from the screenshots I've seen, they are simple round shadows.These are not effective — and look wrong, actually — with non-perfectly-round (knurled) knobs.

**Comment by AndrewBelt** [comment]
@jonheal You have a lot of configuration to play with for shadows on Knob subclasses. See https://github.com/VCVRack/Rack/issues/258#issuecomment-372922717

**Comment by jonheal** [comment]
Took a look at 258. I don't know, Andrew, I think it's going to look like hell if everyone draws their shadows differently. There is enough questionable design with many modules as it is. Although the blur property might save the day for knurled knobs ...

**Comment by AndrewBelt** [comment]
People have already added shadows before I added the feature. (e.g. https://www.facebook.com/groups/vcvrack/permalink/163984910928328/). I wouldn't exactly call it hell. This feature just makes it simpler.

**Comment by jonheal** [comment]
I would contend that it is not terribly limiting to have all shadows pointing in the same direction and more or less looking similar. If Rack is departing from a 2D world, then I don't see the the harm in honoring the laws of physics in the process. As for the example above, Patrick Lindenburg is a good designer and knows what he is doing. This is a pretty good design, too, but the circular shadow below the heavily knurled knobs distracts and detracts. (https://www.facebook.com/photo.php?fbid=192503098192952&set=pcb.166621973997955&type=3&ifg=1)

**Comment by AndrewBelt** [comment]
Tell the creator of that plugin, I am not Marc Boule

**Comment by jonheal** [comment]
Ok

**Comment by jonheal** [comment]
Done.

I don't mind being the anal design police.
