### ISSUE TITLE
More potential segfaults with logger functions

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#813]
Searched the code and found two more instances of potential segfaults with the logger in certain edge cases:

- Missing substitution argument: `plugin.cpp:271`: `warn("Plugin %s download was unsuccessful");`
    - Should be: `warn("Plugin %s download was unsuccessful", slug);`
- Missing substitution argument: `audio.cpp:209`: `warn("RtAudio device %d has 0 inputs and 0 outputs");`
    - Should be: `warn("RtAudio device %d has 0 inputs and 0 outputs", device);`

**Comment by AndrewBelt** [comment]
Fixed in 1c53d7b
