### ISSUE TITLE
Textfield text color from white, now is black (probably a new feature ?)

### ISSUE THREAD

**Issue by antoniotuzzi** [VCVRack/Rack#826]
I've noticed that the textcolor for the textfield is now black and is almost invisible (at least on my OSX Macbook pro) when unselected

I'm attaching an example of the change, before and after (with a selected and unselected fields)

BEFORE
![screen shot 2018-03-20 at 11 38 45](https://user-images.githubusercontent.com/62518/37651578-da7f37fc-2c38-11e8-83ab-a9e24b9687c1.png)

AFTER
![screen shot 2018-03-20 at 11 39 15](https://user-images.githubusercontent.com/62518/37651591-e47730d4-2c38-11e8-901c-eef35d31736c.png)

Maybe we want to add a new field **"BNDtheme\* bnd_theme"** to the textfield.
At creation time **bnd_theme** is copied from the default using the **bndGetTheme()**

and "developers" can change fields in the copied **theme**

**Comment by AndrewBelt** [comment]
Fixed in 0190dfb
Will have someone else go over the default theme post-0.6

**Comment by antoniotuzzi** [comment]
adding for documentation:

NOW:
![screen shot 2018-03-20 at 19 31 47](https://user-images.githubusercontent.com/62518/37675403-73652b20-2c75-11e8-9d90-85a4af2884d3.png)

**Comment by AndrewBelt** [comment]
BTW, you need to update and recompile Blendish submodule to get the new UI style.

**Comment by antoniotuzzi** [comment]
thanks for the info !

**Comment by squinkylabs** [comment]
Also, of course, you can the the colors of your labels. That's what I did.
