### ISSUE TITLE
non-standard make files for plugins?

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#827]
Hi.

We know that VCV wants plugin developers to modify their makefiles as little as possible, and we certainly agree. Clearly all sort of terrible things would happen if people don't leverage the built in gcc flags, etc...

We have done a few things to our makefile, and want to be sure you think it's "ok".
- added a target `make test` that builds test.exe, our unit test program.
- added a command line flag `make _EXP=true` to build our test plugins. This just adds `-D _EXP` to FLAGS.

We think this is in the spirit of leveraging what should be leveraged, but wanted to check.

current makefile is [here]( https://github.com/squinkylabs/SquinkyVCV/blob/master/Makefile)

**Comment by AndrewBelt** [comment]
Yeah, those are fine. Some day I'll make a guide to show how to add shell commands to the main target as pre- and post-scripts.

**Comment by squinkylabs** [comment]
Cool - figured that was the case, but wanted to check. tx.
