### ISSUE TITLE
Toolchain to convert text to path for svg (requires inkscape)

### ISSUE THREAD

**Issue by david-c14** [VCVRack/Rack#828]
Since VCV can't support text in the svg resources, but I find it easier to design and edit them with text elements, I've just implemented a change in my build process to help me.

I've put my text based svg files into a subdirectory of res. Then I added the following to the bottom of the Makefile
```
# Make resources

RESOURCES += $(wildcard res/*.svg)

res: $(RESOURCES)
	
res/%.svg: res/src/%.svg
	inkscape -z -T -l=$@ $<

```

Now I can `make res` and it will use inkscape to convert all the text to paths in any updated source svg files.

Those options to inkscape:
-z no gui
-T text to path
-l export file

since res is not a usual target in the standard Makefile, I don't believe this will interfere with the standard builds for most people. The stripped files are included in the repository and don't need to be built.
But it does require inkscape.

**Comment by AndrewBelt** [comment]
Oh cool, didn't know about the `-T` flag.

I've added a `RESOURCES` variable to `plugin.mk`. Use with

```makefile
RESOURCES += res/hello

RACK_DIR ?= ../..
include $(RACK_DIR)/plugin.mk

# Note this must be after the include
res/hello:
	echo hello world
```

**Comment by david-c14** [comment]
Wow. 

Yes I am committing the path svgs as well as the text svgs.

**Comment by squinkylabs** [comment]
Can Inkscape also inline styles? I use Adobe XD to edit my panels, but the svgs need a trip through Illustrator to flatten the styles (and render the text to paths).

**Comment by AndrewBelt** [comment]
@squinkylabs Some styles are supported. https://github.com/memononen/nanosvg/blob/master/src/nanosvg.h#L1716-L1779

**Comment by david-c14** [comment]
I'm quite new to inkscape. I don't think it can do what you want without invoking the GUI; but even then it can be partly scripted from the command line.  

More complex stuff might be more effectively done using xslt.

**Comment by modlfo** [comment]
Closing this one as part of the cleanup.
