### ISSUE TITLE
Nothing works 

### ISSUE THREAD

**Issue by Eltanoloko** [VCVRack/Rack#83]
When loading modules, they have no knobs, no functions. the audible ones actually appear completel blank. any solution?

**Comment by AndrewBelt** [comment]
You haven't stated your OS, but I will guess this is a duplicate of #17.

**Comment by Eltanoloko** [comment]
Hi Andrew 

sorry, the os is Yosemite 10.10.5

**Comment by Eltanoloko** [comment]
And yet, it happens to me something very similar to issue 17
