### ISSUE TITLE
Building Fail on MacBookAir

### ISSUE THREAD

**Issue by ATGC2** [VCVRack/Rack#831]
Hello Community,

i'm a new Member. The Reason why i become a Member, is: learning to build a plugin and contributing to keeping this great project alive.

My Issue is the following:

at the Point "make dep" i get this Message: "make[1]: *** [lib/libglfw.dylib] Error 127"
and then this: "make: *** [dep] Error 2"

This is a Copy of my Procedure:

Last login: Tue Mar 20 12:31:18 on ttys001
MacBook-Air-4:~ VincenzoLuciano$ git clone https://github.com/VCVRack/Rack.git
Cloning into 'Rack'...
remote: Counting objects: 5715, done.
remote: Compressing objects: 100% (151/151), done.
remote: Total 5715 (delta 133), reused 111 (delta 53), pack-reused 5511
Receiving objects: 100% (5715/5715), 2.68 MiB | 369.00 KiB/s, done.
Resolving deltas: 100% (4369/4369), done.
MacBook-Air-4:~ VincenzoLuciano$ cd Rack
MacBook-Air-4:Rack VincenzoLuciano$ git submodule update --init --recursive
Submodule 'dep/glfw' (https://github.com/glfw/glfw.git) registered for path 'dep/glfw'
Submodule 'ext/nanosvg' (https://github.com/memononen/nanosvg.git) registered for path 'dep/nanosvg'
Submodule 'ext/nanovg' (https://github.com/memononen/nanovg.git) registered for path 'dep/nanovg'
Submodule 'ext/osdialog' (https://github.com/AndrewBelt/osdialog.git) registered for path 'dep/osdialog'
Submodule 'ext/oui-blendish' (https://github.com/AndrewBelt/oui-blendish.git) registered for path 'dep/oui-blendish'
Submodule 'dep/rtaudio' (https://github.com/thestk/rtaudio.git) registered for path 'dep/rtaudio'
Cloning into '/Users/VincenzoLuciano/Rack/dep/glfw'...
Cloning into '/Users/VincenzoLuciano/Rack/dep/nanosvg'...
Cloning into '/Users/VincenzoLuciano/Rack/dep/nanovg'...
Cloning into '/Users/VincenzoLuciano/Rack/dep/osdialog'...
Cloning into '/Users/VincenzoLuciano/Rack/dep/oui-blendish'...
Cloning into '/Users/VincenzoLuciano/Rack/dep/rtaudio'...
Submodule path 'dep/glfw': checked out '682f1cf203707f21c2eed4fa3f89c23c52accc49'
Submodule path 'dep/nanosvg': checked out '9a74da4db5ac74083e444010d75114658581b9c7'
Submodule path 'dep/nanovg': checked out '98e551351d020087b01ae0b1d3d2d1593e3ad01f'
Submodule path 'dep/osdialog': checked out '015d020615e8169d2f227ad385c5f2aa1e091fd1'
Submodule path 'dep/oui-blendish': checked out '383f24f6ed41facf25eda0d32b0f6bc9aee96e53'
Submodule path 'dep/rtaudio': checked out 'ce13dfbf30fd1ab4e7f7eff8886a80f144c75e5d'
MacBook-Air-4:Rack VincenzoLuciano$ make dep
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C dep
curl -OL https://github.com/nigels-com/glew/releases/download/glew-2.1.0/glew-2.1.0.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   603    0   603    0     0    307      0 --:--:--  0:00:01 --:--:--   307
100  746k  100  746k    0     0   157k      0  0:00:04  0:00:04 --:--:--  551k
tar xf glew-2.1.0.tgz
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C glew-2.1.0 glew.lib
cc -DGLEW_NO_GLU -DGLEW_BUILD -Os -Wall -W -Iinclude -dynamic -fno-common -pedantic -fPIC -std=c89  -o tmp/darwin/default/shared/glew.o -c src/glew.c
cc -dynamiclib -install_name /usr/local/lib/libGLEW.2.1.0.dylib -current_version 2.1.0 -compatibility_version 2.1 -o lib/libGLEW.2.1.0.dylib tmp/darwin/default/shared/glew.o  -framework OpenGL 
ln -sf libGLEW.2.1.0.dylib lib/libGLEW.2.1.dylib
ln -sf libGLEW.2.1.0.dylib lib/libGLEW.dylib
strip -x lib/libGLEW.2.1.0.dylib
sed \
		-e "s|@prefix@|/usr|g" \
		-e "s|@libdir@|/usr/local/lib|g" \
		-e "s|@exec_prefix@|/usr/local/bin|g" \
		-e "s|@includedir@|/usr/local/include/GL|g" \
		-e "s|@version@|2.1.0|g" \
		-e "s|@cflags@||g" \
		-e "s|@libname@|GLEW|g" \
		-e "s|@requireslib@||g" \
		< glew.pc.in > glew.pc
cc -DGLEW_NO_GLU -DGLEW_STATIC -Os -Wall -W -Iinclude -dynamic -fno-common -pedantic -fPIC -std=c89  -o tmp/darwin/default/static/glew.o -c src/glew.c
ar rv lib/libGLEW.a tmp/darwin/default/static/glew.o
ar: creating archive lib/libGLEW.a
a - tmp/darwin/default/static/glew.o
strip -x lib/libGLEW.a
# On Linux, default lib path is lib64, so change it back to lib.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C glew-2.1.0 GLEW_DEST="/Users/VincenzoLuciano/Rack/dep" LIBDIR="/Users/VincenzoLuciano/Rack/dep/lib" install
install -d -m 0755 "/Users/VincenzoLuciano/Rack/dep/include/GL"
install -m 0644 include/GL/wglew.h "/Users/VincenzoLuciano/Rack/dep/include/GL/"
install -m 0644 include/GL/glew.h "/Users/VincenzoLuciano/Rack/dep/include/GL/"
install -m 0644 include/GL/glxew.h "/Users/VincenzoLuciano/Rack/dep/include/GL/"
sed \
		-e "s|@prefix@|/usr|g" \
		-e "s|@libdir@|/Users/VincenzoLuciano/Rack/dep/lib|g" \
		-e "s|@exec_prefix@|/Users/VincenzoLuciano/Rack/dep/bin|g" \
		-e "s|@includedir@|/Users/VincenzoLuciano/Rack/dep/include/GL|g" \
		-e "s|@version@|2.1.0|g" \
		-e "s|@cflags@||g" \
		-e "s|@libname@|GLEW|g" \
		-e "s|@requireslib@||g" \
		< glew.pc.in > glew.pc
ar rv lib/libGLEW.a tmp/darwin/default/static/glew.o
r - tmp/darwin/default/static/glew.o
strip -x lib/libGLEW.a
install -d -m 0755 "/Users/VincenzoLuciano/Rack/dep/lib"
install -m 0644 lib/libGLEW.2.1.0.dylib "/Users/VincenzoLuciano/Rack/dep/lib/"
ln -sf libGLEW.2.1.0.dylib "/Users/VincenzoLuciano/Rack/dep/lib/libGLEW.2.1.dylib"
ln -sf libGLEW.2.1.0.dylib "/Users/VincenzoLuciano/Rack/dep/lib/libGLEW.dylib"
install -m 0644 lib/libGLEW.a "/Users/VincenzoLuciano/Rack/dep/lib/"
install -d -m 0755 "/Users/VincenzoLuciano/Rack/dep/lib/pkgconfig"
install -d -m 0755 "/Users/VincenzoLuciano/Rack/dep/lib/pkgconfig"
install -m 0644 glew.pc "/Users/VincenzoLuciano/Rack/dep/lib/pkgconfig/"
cd glfw && cmake . \
		-DCMAKE_INSTALL_PREFIX="/Users/VincenzoLuciano/Rack/dep" -DBUILD_SHARED_LIBS=ON \
		-DGLFW_COCOA_CHDIR_RESOURCES=OFF -DGLFW_COCOA_MENUBAR=ON -DGLFW_COCOA_RETINA_FRAMEBUFFER=ON
/bin/sh: cmake: command not found
make[1]: *** [lib/libglfw.dylib] Error 127
make: *** [dep] Error 2
MacBook-Air-4:Rack VincenzoLuciano$ -j$(nproc)
-bash: nproc: command not found
-bash: -j: command not found
MacBook-Air-4:Rack VincenzoLuciano$ make dep
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C dep
cd glfw && cmake . \
		-DCMAKE_INSTALL_PREFIX="/Users/VincenzoLuciano/Rack/dep" -DBUILD_SHARED_LIBS=ON \
		-DGLFW_COCOA_CHDIR_RESOURCES=OFF -DGLFW_COCOA_MENUBAR=ON -DGLFW_COCOA_RETINA_FRAMEBUFFER=ON
/bin/sh: cmake: command not found
make[1]: *** [lib/libglfw.dylib] Error 127
make: *** [dep] Error 2
MacBook-Air-4:Rack VincenzoLuciano$ make dep RTAUDIO_ALL_APIS=1
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C dep
cd glfw && cmake . \
		-DCMAKE_INSTALL_PREFIX="/Users/VincenzoLuciano/Rack/dep" -DBUILD_SHARED_LIBS=ON \
		-DGLFW_COCOA_CHDIR_RESOURCES=OFF -DGLFW_COCOA_MENUBAR=ON -DGLFW_COCOA_RETINA_FRAMEBUFFER=ON
/bin/sh: cmake: command not found
make[1]: *** [lib/libglfw.dylib] Error 127
make: *** [dep] Error 2
MacBook-Air-4:Rack VincenzoLuciano$ make dep
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C dep
cd glfw && cmake . \
		-DCMAKE_INSTALL_PREFIX="/Users/VincenzoLuciano/Rack/dep" -DBUILD_SHARED_LIBS=ON \
		-DGLFW_COCOA_CHDIR_RESOURCES=OFF -DGLFW_COCOA_MENUBAR=ON -DGLFW_COCOA_RETINA_FRAMEBUFFER=ON
/bin/sh: cmake: command not found
make[1]: *** [lib/libglfw.dylib] Error 127
make: *** [dep] Error 2

**Comment by ATGC2** [comment]
So please explain - what do i wrong.

**Comment by ATGC2** [comment]
High Sierra
MacBookAir5,1
Intel Core i5
1,7 GHz
L2-Cache: 256 KB
L3-Cache: 3 MB
RAM: 4 GB

**Comment by AndrewBelt** [comment]
Edit your post with #730

**Comment by ATGC2** [comment]
i solved the issue described above, with the following Commandline: 
sudo "/Applications/CMake.app/Contents/bin/cmake-gui" --install=/usr/local/bin

Thank You
