### ISSUE TITLE
Port to Chromium OS

### ISSUE THREAD

**Issue by pixiemcdixie** [VCVRack/Rack#834]
First off I have to say that I absolutely love VCV Rack! I have had many hours of fun with the software. This is not a bug, but a suggestion. Since I run Rack on my PC, and it runs flawlessly, I have thought about how much fun I would have with it on the go. I am a sound designer and do a fair bit of work in sound booths and the main thing I bring is my Chromebook. I am requesting that, if possible, VCV Rack could be ported to Chromebook as an application for the system, if possible? It would be a dream come true for that to happen. Thanks for reviewing my suggestion.

**Comment by AndrewBelt** [comment]
No, Rack will not be ported to Chromium OS.

**Comment by WIZARDISHUNGRY** [comment]
@pixiemcdixie you should be able to easily boot a Chromebook into a regular Linux distribution
