### ISSUE TITLE
Toggle switch state sometimes missing

### ISSUE THREAD

**Issue by AScustomWorks** [VCVRack/Rack#836]
Operating system(s): Os X 10.12.6
Version if official Rack release, commit hash and/or branch if from source: v0.5, v0.6

When a module using a toggle switch is loaded and the stored state is (right now not quite sure if 0 or >0), the switch state is not recognized so you have to make 2 clicks to have the switch start changing the state. 

You can test this on Fundamental SS-1 and SS-2 modules, click the randomize option until the switch graphic is on the top position, then click the switch to change it's state, it will be stuck until the second click.

**Comment by WIZARDISHUNGRY** [comment]
I've noticed that when reloading saved patches, on the first call to `step()`, parameters with a range that does not include 0.0 get 0.0. Is this related?

**Comment by AScustomWorks** [comment]
@WIZARDISHUNGRY: I don't think so but not sure. This one is tied to the ToggleSwitch component behavior, and happens with every module using this component.

I think I have seen your issue happening on module basis (when the developer adds more components disrupting the  components ID order). In this case the problem goes away by saving the patch again. This is one possible cause, but it may be something else, maybe open a new issue?

**Comment by AndrewBelt** [comment]
Closing. I'm assuming this has been fixed.
