### ISSUE TITLE
knobs don't work in Linux?

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#843]
Must be my crazy setup, but I just built 210bb70ed95af7fdd65f1964cd5a324e1f3903d2, and none of the knobs work. Clicking on a knob makes it go to the minimum value, and I can't drag it anywhere from there.

Caveat - I run Ubuntu inside VMWare on Windows 7. But the knobs have worked in the past.

**Comment by AndrewBelt** [comment]
Probably a VM issue. It works fine for me.

**Comment by johanneswolfgruber** [comment]
I had the same issue, try setting allowCursorLock to false in settings.json. See #22

**Comment by SynthMage00** [comment]
I had a similar issue when testing on Ubuntu 17.10 in a Virtualbox guest. If I have the time, I'll try testing on a bare-metal install and see if that resolves the issue. Like Andrew mentioned, I have a sneaking suspicion that it's something to do with the VM.

**Comment by AndrewBelt** [comment]
Yes, VMs can't grab your mouse, so you'll have to set `"allowCursorLock": false`
