### ISSUE TITLE
MacOSX minimize/restore oddity

### ISSUE THREAD

**Issue by jhoar** [VCVRack/Rack#846]
Operating system(s):
MacOSX 10.11.6

Version:
master bd99a855955fa905819436cea2095c8b7ee6e550

Description:
Once minimized, Rack does not restore by clicking on the icon in the dock. However, right-clicking on the icon (folder icon currently) and selecting 'Show All Windows' show the window with the title 'VCV Rack master' and allows the window to be restored.

**Comment by alto777** [comment]
I'm running Rack built about 10 hours ago (16:00 GMT) and see only normal behavior. Same MacOSX 10.11.6.

But hey, Show All Windows, never tried that, nice to know about. :-) I can actually read all my open terminals, for example. How long before "they" let us work on tiny little docs?
