### ISSUE TITLE
Workarounds to audio stuttering

### ISSUE THREAD

**Issue by Euphorbium** [VCVRack/Rack#848]
Don't know if this is a common knowledge, but if audio keeps stuttering, it is most likely because of graphics rendering. If you have a complex patch, with many modules, and it it keeps stuttering, you can pull away just the few modules that you need to see offscreen, away from other modules, so they are not visible, and this improves or eliminates the stuttering. Or you can map what you need to a controller knobs, and then slide offscreen, so only empty rack is rendered. Also, working fullscreen on a mac helps a lot.

I can't wait for the graphics optimisation, currently it is stuttering too much for live performance, at least on my laptop.

**Comment by squinkylabs** [comment]
there is quite a bit of disagreement about this. It is often reported.

**Comment by AndrewBelt** [comment]
Closing as not a concrete issue.
