### ISSUE TITLE
CircularShadow.cpp - C++ question I think

### ISSUE THREAD

**Issue by alto777** [VCVRack/Rack#849]
I found CircularShadow.cpp. It has a variable  "opacity" and the code seems to say that setting it to < 0.0 would suppress the drop shadow of, say, a knob.

I tried making a shadowless knob, viz:

struct myOwnKnob : SVGKnob {
	myOwnKnob() {
		box.size = Vec(40, 40);
		minAngle = -0.75*M_PI;
		maxAngle = 0.75*M_PI;
		setSVG(SVG::load(assetPlugin(plugin, "res/myOwnKnob.svg")));
// not in scope here...		opacity = -1.0;
	}
};

I'm totally bluffing, just matching patterns. Can "opacity" help and if so how/where should I set it?

**Comment by dllmusic** [comment]
shadow->opacity = 0.f;

**Comment by alto777** [comment]
Yes, super. I'll figure out why and mebbe learn something. Thanks!

 But it has to be strictly less than 0.0. -1.0 does the trick.

**Comment by dllmusic** [comment]
yes I though that 0 skipped that ... but it has to be less

**Comment by AndrewBelt** [comment]
opacity at 0.f is fine, why do you say otherwise?

**Comment by AndrewBelt** [comment]
Thanks, fixed in 63dd31f. Opacity at 0.f should disable it now.
