### ISSUE TITLE
Wrong syntax in Rack.sh prevents start up.

### ISSUE THREAD

**Issue by MaurizioB** [VCVRack/Rack#85]
The existing ```Rack.sh``` file doesn't seem to use standard syntax for bash path variables, resulting in an error while loading dependencies.
This should be the correct syntax, which correctly starts up Rack on my system (Gentoo Linux):

    #!/bin/bash
    LD_LIBRARY_PATH=".:./dep/lib/:$LD_LIBRARY_PATH" ./Rack

**Comment by AndrewBelt** [comment]
Rack.sh is a product for the distributable. Use `make run` if youre running from the source tree.
