### ISSUE TITLE
Rack freezes when using 2 core audio modules & Soundflower

### ISSUE THREAD

**Issue by Yuxtehol** [VCVRack/Rack#850]
## For bug reports:

Operating system(s): OS X High Sierra
Rack v0.6

Rack freezes when using 2 core audio modules and 2 Soundflower driver.
When deleting or making changes in the second module (9-16 in), Rack freezes completely

Terminal:

 [4.602 info] Opening audio RtAudio device 4 with 8 in 8 out
[4.606 info] Starting RtAudio stream 4

RtApiCore::getDeviceInfo: system error (CoreAudio unknown error) getting sample rate info.

[10.249 info] Stopping RtAudio stream 4

**Comment by AndrewBelt** [comment]
See https://vcvrack.com/manual/Core.html
Using multiple AUDIOs is experimental, and your experience may vary.
