### ISSUE TITLE
Creating Framebuffers fail

### ISSUE THREAD

**Issue by wilfriedE** [VCVRack/Rack#852]
Hello! I am working on a plugin for Rack at the moment and am attempting to do a Render to Texture. 
I've been running into a problem where whether I attempt to create a framebuffer with nvgluCreateFramebuffer or using glGenFramebuffers it fails. Any ideas why this might be?

**Comment by AndrewBelt** [comment]
This issue is old and likely obsolete. Comment if issue is still present. Closing.
