### ISSUE TITLE
Rack 0.6 master - Question about continuous encoder & json value

### ISSUE THREAD

**Issue by DomiKamu** [VCVRack/Rack#853]
Hi,

It's not a bug report nor feature request, simply help/assistance.
I'm using a knob as continuous encoder, it works fine including during initialization, but I'd like to know (if possible) how to reset its value to 0.0f, or pehaps to nearest "2 * M_PI" when I don't touch it or at init (to avoid too high json value in .vcv file)

      "model": "Metriks",
      "pos": [
        76,
        0
      ],
      "params": [
        {
          "paramId": 0,
          "value": 43.9259796 ---------> registered "absolute" value, can be high
        },

Thanks in advance.

**Comment by AndrewBelt** [comment]
Does right-clicking on it or resetting the module (right click on panel > Initialize) not work?

**Comment by DomiKamu** [comment]
Yes of course both are working, but... all are manually (human intervention). In fact my question was: this can be done automatically (when encoder is idle, untouched after a delay/timer, for example), or forced to 0.0 when loading vcv file.

**Comment by AndrewBelt** [comment]
No, communication from the engine thread to the main thread is not supported.
