### ISSUE TITLE
Asset licenses w/ GPL code

### ISSUE THREAD

**Issue by WIZARDISHUNGRY** [VCVRack/Rack#854]
This is not necessarily for Andrew; so everyone should feel free to chime in.

I'm developing a [module](https://github.com/WIZARDISHUNGRY/vcvrack-rtlsdr) that is derived from GPL source code. While I must continue to license the module's source code under the GPL, I'd like to include SVGs to brand it the same as my other modules without licensing these graphics under the GPL - similar to how the [panels for Core are copyrighted](https://github.com/VCVRack/Rack/blob/master/res/Core/LICENSE.txt) even though the source is open source. Is this permissible?

**Comment by AndrewBelt** [comment]
I am not your lawyer, but I can't see how graphics would be a derivative of source code, so the GPL on the original source code should not restrict its own distribution based on graphics that it is bundled with.

It's a different story if you're deriving your graphics from graphics licensed under the GPL (which some people do, but the GPL is not designed for that).

**Comment by dhemery** [comment]
The Copyright Handbook (from NOLO Press) begins its discussion of derivative works like this:

> an author can take expression that already exists, add new expression to it, and end up with something new—that is, a new and different work of authorship. Such works are called derivative works.

So while the graphics per se (the "new expression") may not be a derivative work, the module (which includes the graphics) would appear to be a derivative work.

As for what this means for your right to restrict the license for your graphics… I dunno. IANAL.

**Comment by AndrewBelt** [comment]
I'm going to close this as off-topic, because it is a generic question about the GPL instead of about Rack.
