### ISSUE TITLE
alto777_LFSR tone sequencer

### ISSUE THREAD

**Issue by alto777** [VCVRack/Rack#855]
I have managed to write a plugin, the first of several I want to do based on LFSRs, that I would like to have anyone test. It's on github at alto777 in the LFSR repository (v0.6.0 branch).

I am all ears. I would certainly like to know if I've gone wrong, where else I might seek testing and error reports  and of course suggestions for changes or improvements.

**Comment by WIZARDISHUNGRY** [comment]
I'd be more likely to test if it was listed as working on Rack v0.6

**Comment by phdsg** [comment]
you can request addition to the community repo (i.e. download manager) as described here: https://github.com/VCVRack/community#for-plugin-developers-addingupdating-your-plugin
