### ISSUE TITLE
Rack SDK: No issue, kudos!

### ISSUE THREAD

**Issue by alto777** [VCVRack/Rack#856]
The Rack SDK worked after the application of a bit of common sense. Thank you! I am sure this will increase the number of people who build and write plugins.

It came just a bit late for me, but that's just as well  - I learned quite a bit building "my own" Rack 0.5 and near-0.6 versions, the third time it was easy. :-) Now if I could just get the hang of git… my last innocent move with it disappeared a bunch of work and I remain baffled by some of the things that happen when I use it as well as things that don't. Happen. Never mind.

I again encourage the faint of heart. I had taken a glance at getting into the thick of it and decided it was without my capabilities. Building Rack was for sure an obstacle.

Studying the great number of plugins whose authors have shared source code has been very helpful, as has been combing (well, find/grepping) through Rack's code.

What a great time to be alive.

**Comment by modlfo** [comment]
@alto777 I'm closing this issue as part of the cleanup. 

I have been using the SDK to compile the Vult modules as well and works great.
