### ISSUE TITLE
Multiple Audio Interfaces fried something so badly that I can't open Rack at all, even after reinstalling!

### ISSUE THREAD

**Issue by vegannoise** [VCVRack/Rack#857]
I mistakenly opened 2 Audio Interfaces, which I saw afterward is experimental. It immediately crashed, and even after having uninstalled 0.5.1, restarted my computer and audio interface (Audiobox 1818VSL), and reinstalled it, it still won't open without crashing! I've also tried installing it into different folders, taking out all but the basic plugins, putting in all the new plugins, but nothing will let it open. 

It does appear that even though I've uninstalled it, when I add a clean install it must still be trying to open the last faulty file I'd had open because if I don't copy over the additional plugins into the new folder, I'll get an error saying that it couldn't find all the plugins that used to be there before it crashes completely. Is there a way to scrub its memory of what used to be there beyond just uninstalling?  I've also tried deleting my Windows Temp files to no avail. 

I'm using Windows 10 x64

Any idea what could have happened, or how I could get the new version to work again? 
I will say, older versions will open. Just not the newest. 
Thanks for your help!

**Comment by AndrewBelt** [comment]
Delete autosave.vcv from your local Rack directory.

**Comment by vegannoise** [comment]
Thanks very much! That fixed it! Had no idea that was there.
