### ISSUE TITLE
No sound after loading a patch

### ISSUE THREAD

**Issue by Euphorbium** [VCVRack/Rack#859]
[issue.vcv.zip](https://github.com/VCVRack/Rack/files/1855737/issue.vcv.zip)

## For bug reports:

Operating system(s):
VCV 0.5.1, Mac os

After saving this patch and trying to load it, sound is lost.

**Comment by n6smith** [comment]
Topograph 'Run' was not engaged.. Press Run button in Topograph and as far as I can tell and have tested... sound plays perfectly each and every time.  Note: Topograph does not save 'Run' state on save/loading... Request feature add via Valley's Github entry :)

**Comment by Euphorbium** [comment]
Thanks @n6smith . This is a topograph issue then.
