### ISSUE TITLE
new plugin manager won't synchronize (windows 7 v. 0.51)

### ISSUE THREAD

**Issue by newdudehere** [VCVRack/Rack#860]
When adding plugins to my account, they don't synchronize. It never worked (so I might be doing something wrong), so I just added them to the 'plugins' folder. Now I'm trying to get the 'audible instruments' plugin, but there is no download available. But when I add it to my account, they never work.
Ask if you need any specifics

**Comment by AndrewBelt** [comment]
I'm in the middle of migrating the server from 0.5 to 0.6. Re-test this after Rack 0.6 releases, and close if fixed.

**Comment by newdudehere** [comment]
ok, thank you

**Comment by wadaga** [comment]
hello, 
I've got the same probleme with Linux Debian Stretch and Linux Librazik (based on debian stretch) with VCVRack v0.5.1

ps : i will try also with the Rack 0.6 release and tell you

thank a lot for what you do

**Comment by wadaga** [comment]
With Rack v0.6, it's ok for me on Linux Librazik

thank you a lot !

**Comment by AndrewBelt** [comment]
Rack 0.6.0 has been posted on the homepage of vcvrack.com
