### ISSUE TITLE
Case sensitivity in plugin manager

### ISSUE THREAD

**Issue by almostEric** [VCVRack/Rack#861]
v 0.6
Was hoping this would be fixed in new version. Why is the sorting of module makers case sensitive? It forces you to go through the list twice when looking for someone. I get that this is kind of a Linux thing, but it is kind of annoying

**Comment by AndrewBelt** [comment]
That's the default sorting method for `std::string`, has nothing to do with Linux.
Should be an easy fix.

**Comment by AScustomWorks** [comment]
To me it looks odd to have developers names without uppercase, as that's not the way one usually writes, maybe tell the developers instead?

**Comment by almostEric** [comment]
Developers should be able to name their items however they want. Would you force Apple to call it an Iphone?

**Comment by sbcook0** [comment]
same as #446

**Comment by AScustomWorks** [comment]
While I agree with the example, the issue exists and I don't mean to force anybody, if anything, just to ask them to follow ancient writing rules to make the list look better... even if the sorting method changes, the list will look ugly ;)

**Comment by almostEric** [comment]
If you look at the plugin manager, you will see that they are displayed in a case-insensitive order. It is a trivially easy fix, and Andrew has stated he’ll take care of it 😊

**Comment by AndrewBelt** [comment]
Fixed in 1753453
