### ISSUE TITLE
terrible digi-fart noise

### ISSUE THREAD

**Issue by arghgr** [VCVRack/Rack#862]
My audio briefly conks out with an extremely loud sudden fart noise after running Rack for a few minutes. This issue only started cropping up when I began using many modules (over 40), and is preceded by several clicks/stutter in the audio, presumably from the high CPU load. Someone else on Reddit [also reported this issue](https://www.reddit.com/r/vcvrack/comments/7zwu8o/audio_issue/).

Operating system(s): Mac OSX Sierra 10.12.6 on an early 2015 MacBook Air
Version if official Rack release, commit hash and/or branch if from source: 0.5.1

Fart noise recording can be provided on request. If you're into fart sounds, it's quite magnificent. High expulsion velocity, mid-range tone. It almost blew my eardrums.

**Comment by AndrewBelt** [comment]
Not really reproducible / concrete.
