### ISSUE TITLE
Unofficial version via plugin manager

### ISSUE THREAD

**Issue by lindenbergresearch** [VCVRack/Rack#865]
Hi all,

somehow my modules published in a messy dev state via the plugin manager.
I don't know, if I am missed something, but now a version is around which really shouldn't be :-( 

Currently my make config uses 'VERSION = v0.6.0' and the master is always the current dev state, which could be a mess. All proofed versions are tagged and released.

It would be nice if this could be changed soon. I have create a v.0.6.0 which is stable and tagged.
Release is build for mac and other platforms will follow this day.

Thanks in advance,
Patrick

**Comment by lindenbergresearch** [comment]
The current version can be downloaded here:
https://github.com/lindenbergresearch/LRTRack/releases/tag/v0.6.0

**Comment by AndrewBelt** [comment]
Here's the new process for submitting community requests. https://github.com/VCVRack/community#for-plugin-developers-addingupdating-your-plugin
