### ISSUE TITLE
Raason 10: VST plugin does not open.

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Rack#866]
Version: 0.6.0 release
OS: Win7
DAW: Reason 10

Firstly congrats on release I can guess there will be many teething problems on launch. 

Issue I'm facing is in Reason 10 the VST plugin does not open at all so there is no way to configure anything. I discovered that I can get audio to pass through Reason if I put an input on the Bridge placeholder in Reason -
 
![audio](https://user-images.githubusercontent.com/12150421/38140750-12bd8244-342d-11e8-95b9-37b025ff5f24.JPG)

That is connected an input to the VST in Reason, audio passes, that's about all I can do. With no way to configure what ports are active on the VST bridge the only way to use Rack in Reason is on L/R master on a Mix channel. Meaning all tracks in VCV are summed to a L/R output on the bridge.

On a side note I was unaware that there was a disclaimer for rack 0.5.1 installs at the end of the Facebook post. Stupidly assumed it would be a clean install, not to worry my mistake... Might want to state first and foremost on the Facebook post that it will delete your 0.5 plug-ins folder. Luckily I have a back up somewhere not a big deal. 
Not making a new issue with this but the shortcut name for 0.5.1 is still for "VCV Rack v0.5.1"

**Comment by Coirt** [comment]
Getting a lot of crashes that are locking up my PC no option but to press the reset button on my case. How stable is it on mac with Reason? Not stable with Windows/Reason at all. Buffer issues also a lot of clicks. No idea how to route midi with the bridge.

Choosing the port in reason is very difficult without a VST popup window. Have to choose the % value which has smoothing issues 100/16(port#)=6.25% each port. Reason rounds this to about 7% - 0% to 7% is port#1 but in fact when choosing the port % value it will go from 0 to 7 to 5 to 7. This might be an issue within Reason as the VST placholder is trying to translate the % value and getting confused. It increments but should be a snap increment on the VST placeholder. It does increment but rounded to 7%. 

ASIO as the soundcard in Reason is having the buffer issues does not matter what buffer size is selected. MME and DX the buffer issues are extremely bad.

**Comment by AndrewBelt** [comment]
If you are expecting a VST editor window, there is none. DAWs must provide their own UI, and Reason is the worst at that.

**Comment by Coirt** [comment]
Its a big ask for a DAW to provide a UI for a VST, especially if the DAW is not designed to provide one in the first place.

Stability is an issue.

**Comment by AndrewBelt** [comment]
If there's a concrete issue about Bridge, please post it in the Bridge repository as an issue. If your issue is "build a VST GUI", you can post that, but keep in mind that it's a large task with not that much benefit in other DAWs so it might not be worth it.

I have to close all "it's not stable" issues because that is not a concrete task.

**Comment by Coirt** [comment]
Tell you what I'll let you figure it out yourself!
