### ISSUE TITLE
Dynamically loading an external image?

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/Rack#869]
I am trying to use osdialog to open an external image as background on a module, dynamically ( I mean, on the module interface while it is running)

So far everything compile and runs, ecept when i try to load the image I always get a "Failed to load SVG" in terminal

partial code:
` panel->setBackground(SVG::load(assetGlobal(path.c_str())));`

where path is obtained by an osdialog

error:

> Failed to load SVG .//Users/antonio_grazioli/Desktop/VCV/Rack/plugins/Autodafe-BlankPanel/res/AutodafeBlankPanel4.svg

could it be the double "//" at the beginning of the path?

**Comment by AndrewBelt** [comment]
The `path` variable contains an absolute path, so just use that directly without passing through `assetGlobal()`.

**Comment by antoniograzioli** [comment]
thanks! that works, I believe I could only use "asset"+Something to load SVG files

**Comment by antoniograzioli** [comment]
the SVG file is now loaded correctly, however trying to add the image as new background crashes everything.

The following code compiles correctly without warnings, but then fails when trying to  call "AddChild" apparently. I am surely doing something wrong. Any hint?


```
void AutodafeBlankPanel::loadImage(std::string path) {

SVGPanel *panel;

panel = new SVGPanel();

std::string strPath = path.c_str();

panel->setBackground(SVG::load(strPath));

AutodafeBlankPanelWidget *module = nullptr;

module->addChild(panel);
}
```

**loadImage** gets called after the OsDialog closes and passes the path correctly, SVG file is loaded correctly

**Comment by AndrewBelt** [comment]
```cpp
AutodafeBlankPanelWidget *module = nullptr;
module->addChild(panel);
```
See anything wrong here? :)

**Comment by antoniograzioli** [comment]
not that expert to see it :)

(must be related to pointers and something which doesn't exist at runtime, i guess...)

**Comment by AndrewBelt** [comment]
You're dereferencing a null pointer.

A better way to do what you're doing is store the `Panel` as a class variable of your `ModuleWidget` subclass and set `panel->background = SVG::Load(...)` when the button is pressed.
