### ISSUE TITLE
The plugin Interface API (stability to invest time?)

### ISSUE THREAD

**Issue by jackokring** [VCVRack/Rack#87]
Has the plugin interface API, such as how inputs, outputs, knobs and backgrounds, plus tick next calls stabalized yet? Just wondering, as any changes which break it would not be good for users when new cores come out. Just the compilation with ABI changes is enough to cause perhaps annoying support calls.

Should then the API be appended to the version number like 0.3.1-pl1 so that builders know when to do a new build, and users know when to upgrade for say plug-0.7.4-pl3 ...?

**Comment by AndrewBelt** [comment]
A "stable" API is planned when v1.0 releases, but software like this is hard to make ABI compatable. Plugins subclass `Module` and `ModuleWidget`, which may undergo ABI changes when anything in the header file is modified. So by "stable", I mean that I won't touch the header files until the next minor version number is incremented after v1.0. So, for example, plugins compiled for v1.0.0 will be compatible with v1.0.x but will have to be recompiled for v1.1.x.
