### ISSUE TITLE
Report module bugs from plugin manager

### ISSUE THREAD

**Issue by Euphorbium** [VCVRack/Rack#870]
pluggin manager used to show module website before rack 0.6, it was sometimes helpful to find the place to report module bugs. Now this feature seems gone, and I need to go google. It would be great to have a direct link from every module, to know where to report bugs.

**Comment by AndrewBelt** [comment]
Click on *Source* to go to the GitHub page for open-source plugins.

**Comment by Euphorbium** [comment]
Before it was available in the application itself. Now you need to go to the webpage.

**Comment by AndrewBelt** [comment]
I've moved all plugin information from the binary to the manifest files in https://github.com/VCVRack/community/. As the manifest format and API stabalizes, it will then be possible for Rack itself to use it to enhance plugin information.
