### ISSUE TITLE
API changes - 2 questions

### ISSUE THREAD

**Issue by ndrspcfd** [VCVRack/Rack#871]
A couple of questions, hope that's ok..

1) With the changes in constructing structs derived from ModuleWidget, the base class initializer uses the `module` pointer param directly, where previously we used `setModule()`. Suppose I have a module Foo, and its widget FooWidget. Can `Foo::step()` be unavoidably called by the engine during `FooWidget::FooWidget(Foo *)`? 

(Previously I was initialising a couple of Foo's data members in my FooWidget constructor, and had moved setModule() to the end of that so uninitialised members stopped causing segfaults in `Foo::step()` It's not ideal code, and if I continue with it there are workarounds, like a conditional at the start of step(), etc., but I'm interested in performance and coder convenience first, and purity second :) )

2) Perhaps not a fair question, but how much change do  you expect between 0.6 and 1.x plugin APIs compared to that between 0.5 and 0.6?

**Comment by AndrewBelt** [comment]
1. No. You should initialize your Module subclass in its constructor, not ModuleWidget's constructor.
2. 0.6-1.0 will probably have half the API changes as 0.5-0.6.

**Comment by ndrspcfd** [comment]
@AndrewBelt  Thanks for the replies. Regards "No. You should initialize.." To be clear, this is "Yes, the module's step() might be called by the engine anytime during the widget constructor, so no, don't do that," right?

A bit annoying because my module had ownership of some objects that wrapped both UI elements and their underlying inputs/params. but I do realise the fault is mine for breaking separation of concerns ... it was just so damn convenient ;-D

**Comment by AndrewBelt** [comment]
If Rack adds a headless version for video games and museum installations, you plugin will not work because it relies on its GUI to function. Your module should work even without a ModuleWidget.

**Comment by ndrspcfd** [comment]
I'm so afraid of the headless future! I will separate my concerns religiously from this day on! ;-D
