### ISSUE TITLE
Question: compiled Rack.exe filesize is bigger than installed (Windows)

### ISSUE THREAD

**Issue by DomiKamu** [VCVRack/Rack#876]
Hi,

It's just a question (not a bug report or feature request).

When I compile (Windows) Rack 0.6, its "Rack.exe" filesize is 26,373,194 bytes.
From installed version, its filesize is 2,240,512 bytes only.

Maybe compiled by myself having "debug" infos into exe, or official/installed is compressed (such UPX or equivalent)?

Thanks in advance.

**Comment by AndrewBelt** [comment]
Yup, you got it. Here's the line. https://github.com/VCVRack/Rack/blob/v0.6/Makefile#L159

**Comment by DomiKamu** [comment]
Thank you for this info. Closed.
