### ISSUE TITLE
MIDI to CV | How can I recive the MIDI from DAW?

### ISSUE THREAD

**Issue by starock** [VCVRack/Rack#877]
Rack 0.6.0
Mac OS  10.12
DAW: Live 10, Logic pro 10.4

My target:

Live or Logic pro ->creat a new MIDI track ->wirte some notes ->send MIDI to my soundcard's MIDI prot ->CVC Rack add MIDI-1 and recive the MIDI notes from my soundcard's MIDI prot.

Is that workable？ I have tried this, but dosen‘t work~ help please,thx :)

**Comment by dllmusic** [comment]
use MIDI IAC Driver on both.
Logic MIDI track to IAC
RACK MIDI in port (receiving from) IAC

**Comment by AndrewBelt** [comment]
Communicating with a DAW is not supported in Rack.
However, an upcoming product *Rack for DAWs* will be able to do this. See https://vcvrack.com/manual/FAQ#is-vcv-rack-available-as-a-vst-au-aax-plugin-for-daws
