### ISSUE TITLE
HELP request: is it possible to have BIT blitting of drawable surfaces ?

### ISSUE THREAD

**Issue by nysthi** [VCVRack/Rack#880]
I'm wondering if there is any way to do a bitblitting on the Widget surfaces
I need to move image portions around... :)

or, at least

would be possible to do a draw that is not "ERASING" the previous DRAW (in Widgets)? (so the surface contains the pixels history)

**Comment by AndrewBelt** [comment]
You can do software hackery with framebuffers, and it won't be easy, but that's about all I can tell you.

**Comment by nysthi** [comment]
found! (framebuffers are the solutions)
thank you
