### ISSUE TITLE
Another question on modified makefiles (turn off assert)

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#885]
It's an argument that's as old as assert(), but I would like to disable asserts in the released versions of my plugins.

To that end I am considering adding this to the makefile: `FLAGS += -D NDBUG`.

I don't that that will interfere with the (wonderful) new build-bots, but want to run it by you.

**Comment by AndrewBelt** [comment]
Yeah, that's fine.

**Comment by squinkylabs** [comment]
btw - if anyone has many asserts in their step function it can have a pretty big impact on performance. 2X in my case.
