### ISSUE TITLE
Is master going to remain the default branch in GitHub?

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#886]
In the past, the default branch was some version of 0.5, and master was the "wild west". Now that 0.6 is released will there be a new default branch? Just want to make sure I don't keep pulling master when I shouldn't.

**Comment by AndrewBelt** [comment]
I'll keep `master` the default forever on all VCVRack repos. `master` is in general not API/ABI compatible with any Rack release. You'll need to use the `v0.6` for that.

**Comment by AndrewBelt** [comment]
I've effectively renamed `master` to `v0.6`. It is the same thing, but it signals which compatibility version you are on.
