### ISSUE TITLE
Plugin makefile feature

### ISSUE THREAD

**Issue by baconpaul** [VCVRack/Rack#892]
Hi!

Embarrassingly, I suggested an update to my plugin where "make" worked and the plugins worked, but "make dist" did not. This is because (1) I'm a bonehead and (2) make dist wasn't something I did in my workflow, since the awesome community team now builds my dists.

So to avoid my making this silly mistake again, I added a rule to my Makefile which depends on dist, makes sure I'm all checked in to git, and then dumps out the markdown fragment for me to ask the community team to do an update. Basically the work I'd been doing by hand when I wanted to finish a version.

This is handy to me, but I thought I'd share it here in case you wanted to do it or version of it in plugin.mk. If you don't, that's fine with me too of course! 

Thanks

```
paul:~/dev/VCVRack/Rack/plugins/BaconPlugs$ git diff HEAD@{1}
diff --git a/Makefile b/Makefile
index ed2df75..917a18c 100644
--- a/Makefile
+++ b/Makefile
@@ -25,3 +25,16 @@ include $(RACK_DIR)/plugin.mk
 
 shadist:       dist
        openssl sha256 dist/$(SLUG)-$(VERSION)-$(ARCH).zip > dist/$(SLUG)-$(VERSION)-$(ARCH).zip.sha256
+
+COMMUNITY_ISSUE=https://github.com/VCVRack/community/issues/433
+
+issue_blurb:   dist
+       # Make sure we're committed
+       git diff --exit-code
+       git diff --cached --exit-code
+       @echo
+       @echo "Paste this into github issue " $(COMMUNITY_ISSUE)
+       @echo
+       @echo "* Version: v$(VERSION)"
+       @echo "* Transaction: " `git rev-parse HEAD`
+       @echo "* Branch: " `git rev-parse --abbrev-ref HEAD`

paul:~/dev/VCVRack/Rack/plugins/BaconPlugs$ make issue_blurb
rm -rf dist
mkdir -p dist/BaconMusic
# Strip and copy plugin binary
cp plugin.dylib dist/BaconMusic/
strip -x dist/BaconMusic/plugin.dylib
# Copy distributables
cp -R LICENSE.txt res docs patches README.md dist/BaconMusic/
# Create ZIP package
cd dist && zip -5 -r BaconMusic-0.6.1-mac.zip BaconMusic
  adding: BaconMusic/ (stored 0%)
  ..removed for clarity..
  adding: BaconMusic/LICENSE.txt (deflated 35%)
# Make sure we're committed
git diff --exit-code
git diff --cached --exit-code

Paste this into github issue  https://github.com/VCVRack/community/issues/433

* Version: v0.6.1
* Transaction:  67250da457009bb9bb23783d26c259792247201b
* Branch:  master
```

Finally please don't update to that tag. The tag I put into the community issue last night is the one which fixes my dist.

**Comment by squinkylabs** [comment]
I also make a bonehead mistake and broke my `make dist`

**Comment by AndrewBelt** [comment]
Closing as obsolete.
