### ISSUE TITLE
build fails on WIN10 during make DEP

### ISSUE THREAD

**Issue by antoniotuzzi** [VCVRack/Rack#893]
during make dep

compilations stops on **zlib** build:

after downloading  **https://www.zlib.net/zlib-1.2.11.tar.gz**

there is a message error from configure:

> Checking for gcc...
> Please use win32/Makefile.gcc instead.
> ** ./configure aborting.
> make: *** [Makefile:112: lib/libz.a] Error 1
> 

I solved doing these steps:

- a) cd to zlib folder
- b) make -f win32/Makefile.gcc
- c) move the libz.a to ../lib/

**Comment by modlfo** [comment]
I guess that it eventually worked. I'm closing this issue as part of the cleanup.
