### ISSUE TITLE
What to do with Rack SDK?

### ISSUE THREAD

**Issue by mcclure** [VCVRack/Rack#896]
I briefly did Rack plugin dev around 0.4, I want to get back into it.

The only way currently I know how to get plugin development instructions is this thread https://github.com/VCVRack/Rack/issues/258

The final post in the thread suggests the currently suggested way to build Rack plugins is to download the Rack SDK zip and read "the Building plugins section" of the Rack README.

The building plugins section in the README does not reference this SDK zip and also does not explain how to build the SDK zip, which just contains a smattering of .mk files.

What is the correct way to get started currently? Should I do something with this SDK zip or should I try to fish out my old 0.4 repo and update it?

Thanks!

**Comment by AndrewBelt** [comment]
It essentially replaces the Rack directory. You can put a `plugins/` folder in it or run
`RACK_DIR=<path to Rack-SDK> make dist` when building your plugin.

**Comment by mcclure** [comment]
Got it working now, you can close whenever, thanks!

**Comment by rackperson** [comment]
Hey, I'm having the same problem, how did you get it to work?

**Comment by AndrewBelt** [comment]
@rackperson For the sake of others who might help you, please ask in one place only so their work is not duplicated. https://www.reddit.com/r/vcvrack/comments/8c731z/help_with_sdk_please/

Your question is also not specific enough. Like all technical questions asked on the internet, please specify what you have tried and what step you cannot figure out.

**Comment by rackperson** [comment]
Hi, I was just trying to get help from different sources, this was trying to see how someone else solved a problem (the issue is closed afterall) the other was more of a general search for answers as I couldn't find anything related on the subreddit. 
I think I was just trying to figure my way around everything a bit too fast to be honest, thanks

**Comment by rackperson** [comment]
I think I can put my question better, essentially should I be running 
RACK_DIR=<path to Rack-SDK> make dist 
in msys under "cd plugins/Template" instead of running 
make -j2 ?

**Comment by rackperson** [comment]
I still think I'm doing something wrong:

Rackguy@Lenovo MINGW64 ~/rack/plugins/Template
$ RACK_DIR=<path to Rack-SDK> make dist
bash: path: No such file or directory

**Comment by rackperson** [comment]
If so I am currently getting the following

RackguyDouraid@Lenovo MINGW64 ~/rack/plugins/Template
$ make dist
rm -rf dist
mkdir -p dist/NewName
# Strip and copy plugin binary
cp plugin.dll dist/NewName/
strip -s dist/NewName/plugin.dll
# Copy distributables
cp -R LICENSE.txt res dist/NewName/
# Create ZIP package
cd dist && zip -5 -r NewName-0.6.0-win.zip NewName
/bin/sh: zip: command not found
make: *** [../../plugin.mk:52: dist] Error 127

I hope these questions are specific enough, I'm really not trying to be a nuisance just kinda confused

**Comment by mcclure** [comment]
I think that you should be setting RACK_DIR to something. You should download the rack SDK and for example if it's a directory named rack-sdk-0.6 in ~ put `RACK_DIR=~/rack-sdk-0.6 make dist`

Saying `a=b` before you run a command sets the environment variable `a` to `b`. Saying `a=` means "set a to an empty string" which if `a` is meant to be a path will probably confuse it.

**Comment by rackperson** [comment]
Oh I see, thanks a lot, very helpful!
