### ISSUE TITLE
Feature request/Discussion: Collapsible Favourites 

### ISSUE THREAD

**Issue by patman023** [VCVRack/Rack#899]
Would be nice to have Favourites in a collapsible folder, like the Manufacturers/Tags.

Maybe have it in the Manu-List as "!FAVOURITES", right before AS?

Justification: My Faves list is currently longer than the Manufacturers and Tags combined, because of the multi-line display. Would be nice to scroll to a tag quickly, if it's doable

**Comment by AndrewBelt** [comment]
The Module Browser no longer has a favorites feature, closing.
