### ISSUE TITLE
100% CPU use when no audio device is loaded

### ISSUE THREAD

**Issue by falkTX** [VCVRack/Rack#9]
At least on my system, if I don't have an audio device loaded and configured, Rack takes 100% of one cpu core.

**Comment by AndrewBelt** [comment]
The `step()` function of the AudioInterface module blocks when its buffer is full until it is consumed by the audio driver, and the audio engine loop relies on this to limit the rough number of loops per second. So if no AudioInterfaces in your rack has an active audio device selected, the engine will just blaze through the loop at 100% cpu.

Have any suggestions of solutions? Maybe `std::this_thread::sleep_for()`if the engine detects that the loop is going too fast?

**Comment by nofoto** [comment]
I am having a problem with this on my macbook and mac mini - if I add an audio device (core audio) the CPU usage goes straight up to 99%. This seems to make the laptop overheat!

**Comment by AndrewBelt** [comment]
The CPU of the Audio Interface goes to 100%. That's just idle CPU. I _really_ need to remove that because it misleads so many people.

**Comment by nofoto** [comment]
I'm talking about the CPU usage as shown in the mac Activity Monitor, not just the Rack interface and I'm sure the fan kicks in as if the computer is suddenly working really hard! (I've had another app that I've noticed doing this)

**Comment by AndrewBelt** [comment]
Fixed with eb28397
