### ISSUE TITLE
Any information on a distribution process?

### ISSUE THREAD

**Issue by jackokring** [VCVRack/Rack#90]
https://github.com/jackokring/Rack is a simple clone, with something started in the /plugin directory. Just gfx so far. The question is what's the open and closed source intents for new modules considering the main VCVRack site, and that as a point of customer interaction with a site? Also, with *SVGPanel* just added to the directory, what's the future of background graphics? More importantly, what is most efficient, leaving time for CPU sounds?

**Comment by AndrewBelt** [comment]
Both open and closed source plugins are planned.

The future of all graphics is SVG. Soon all PNG panels will be deleted in favor of SVG panels. The performance will be the same since SVGs are rendered to framebuffers once and never again.

**Comment by modlfo** [comment]
I'm preparing a few modules, I have released two so far https://github.com/modlfo/VultModules. Both have PNG panels because, for some strange reason, my SVG files were not rendered. I used Affinity Designer to design and export the SVG files.

@AndrewBelt  Do you have any plans to to use high resolution PNG panels for such cases when the SVG cannot be render or is rendered incorrectly?

**Comment by AndrewBelt** [comment]
Not all SVG features are supported. In fact, only groups and paths with fill and/or stroke will work. Gradients might added later if there's a need. So convert your text and clipping masks to raw paths.

It wouldn't be impossible to add multiple image resolutions but it'd be a bit messy.

**Comment by modlfo** [comment]
Thanks, I managed to use my SVG files. The problem is that when exporting from Affinity Designer the width and height of the main svg node is expressed in percentage not in pixels. If I fix that manually they are loaded correctly.

**Comment by antoniograzioli** [comment]
@modlfo try Inkscape

**Comment by modlfo** [comment]
@antoniograzioli I started designing the panels in Inkscape (in Linux). Inkscape on mac is terrible, that's why I use Affinity Designer on Mac.

**Comment by antoniograzioli** [comment]
yes Inkscape on mac uses x11 it's ugly

**Comment by AndrewBelt** [comment]
All that Rack assumes about pixel scaling is that the SVG is 96dpi. So you can use mm, in, etc.
