### ISSUE TITLE
BUG? Plugin <name> download was unsuccessful

### ISSUE THREAD

**Issue by BillBehrendt** [VCVRack/Rack#900]
Operating system(s): Windows 7 Professional SP 1
Version if official Rack release: VCV Rack 0.6.0

After install, the Fundamental.zip file was in the 'Program Files' folder and Rack only saw the MIDI plugin. I looked around and unzipped the Fundamental, placing it in the 'My Documents' folder and got that to work (YAY Excellent software!) and all the modules seem fine.

I logged into the web and the application and then closed the application. Went to the web Plugin Manager and selected several free plugins. Re-opened Rack (running as Administrator) and clicked the Update Plugin button. Briefly saw a message, caught the word 'downloading' and then... nada :D 

The log.txt file shows a lot of normal stuff but the last entries are 
```
[2.808 info] Downloading plugin Befaco 0.6.0 win
[4.670 warn] Plugin Befaco download was unsuccessful
[4.670 info] Downloading plugin ESeries 0.6.0 win
[4.670 warn] Plugin ESeries download was unsuccessful
[4.670 info] Downloading plugin SonusModular 0.6.0 win
[4.670 warn] Plugin SonusModular download was unsuccessful
[4.670 info] Downloading plugin SynthKit 0.6.0 win
[4.670 warn] Plugin SynthKit download was unsuccessful
```

Happens every time. Not a major deal, as I can do a lot of stuff with the base modules. I did also root around looking for file and folder permissions problems, etc, and tried what little I know, to no avail. Searched all sorts of things here and haven't found anything exactly like this (so assume it's me or my PC). I did see that some people do get the zip but I can't even get that far. I'm sure it's something dumb I'm doing wrong, but any help when you have some free time (if you're like me you just said "Hah! Free time?"), any help would be appreciated.

**Comment by AndrewBelt** [comment]
Are you able to log out and back in successfully? I wouldn't recommend running Rack as administrator, so try running as your normal user?

**Comment by BillBehrendt** [comment]
I can log in and out of both the application and the website. Turned off 'Run As Administrator'. No joy :D 
Also looked into a firewall problem - turned off the firewall long enough to try it again. Still no successful plugin download. Not a terribly pressing issue. We'll get it sorted at some point :)

**Comment by modlfo** [comment]
Closing since the issue seems to be solved on the user side.

**Comment by BillBehrendt** [comment]
Yes and also Win 10 doesn't have this problem :D
