### ISSUE TITLE
Fundamental mixer module in 0.6.0 seems to mistranslate values from old patches

### ISSUE THREAD

**Issue by vogelscheiss** [VCVRack/Rack#905]
Somehow in the course of updating the Fundamental mixer module from 0.5.1 to 0.6.0, which has involved a redesign using sliders instead of knobs, values programmed into knobs in 0.5.1 patches seem not to translate straight across, but instead seem altered. If the knob was controlling a tuning, that throws the patch out of tune.

**Comment by AndrewBelt** [comment]
It was changed to quadratic scaling, so it's only approximately equal.
It's already done, so nothing to do now.
