### ISSUE TITLE
Syncing plugins fails with compiled Rack version 0.6.0

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#906]
Source revision: 0.6.0
Platform: Ubuntu 16.04

Compile options: `RTAUDIO_ALL_APIS=1 RELEASE=1`

When I log in with my user credentials and hit `Update Plugins` nothing happens. The settings file in `~/.Rack` contains a valid token.

The log shows:

```
[981.698 warn] Plugin sync error: No response from server
```

Both, my updated `vcv-plugindownloader` and the released Linux version of Rack 0.6 work as expected and download plugins, so the server is OK. However, I would like to use `pulseaudio` and need to compile support myself.

Am I missing anything to make this work?

**Comment by AndrewBelt** [comment]
No idea, you'll have to debug the place where that error is generated.

**Comment by cschol** [comment]
I think I figured it out. Looks like the git tag `v0.6.0` is **not** what was released, because it is not working at that revision. Revision db28dbf353e5afbc7937690d1d43ae9d94ed26aa does however work. Can you please double-check that the `v0.6.0` tag is correct and maybe retag what was released? Thanks.

**Comment by AndrewBelt** [comment]
Thanks, fixed.
