### ISSUE TITLE
Forking Rack to change Core modules

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#907]
It occurred to me today that some of the core modules would be more to my liking if I added some attenuverters and other utilities to the modules themselves. 

Would it be shady or dishonorable to copy your code (with license info etc...), add some features and put a new panel on it?

**Comment by AndrewBelt** [comment]
Forking Core is forking Rack, and you'll have to follow https://github.com/VCVRack/Rack#licenses, which includes not using the name "VCV", the logo/icon, Core panels, and not commercially if the Component Library graphics are used.

**Comment by squinkylabs** [comment]
awesome!
