### ISSUE TITLE
Users Installing Wrong .zip File For Their OS

### ISSUE THREAD

**Issue by matthewfriedrichs** [VCVRack/Rack#908]
Every single customer support issue I have had for the past three months is users not putting the right .zip folder into their Rack/plugins directory.

If they get a master .zip with all three .zip releases for all operating systems, they do not unzip the .zip for their operating system inside of the master .zip file. If I let the user choose the file to download, they tend to pick the alphabetically ordered Module-0.X.0-lin.zip as it appears first in a list.

The current way Rack installs plugins from .zip files is great as long as the user has selected the correct .zip. It would cut down on user confusion if they could just place the master .zip file into the Rack/plugins directory and then let VCV Rack unzip the correct .zip file for their operating system next time it starts up. So it would unzip Module.zip then unzip the Module-0.X.0-Mac.zip inside of that folder if they are on a Mac.

I honestly wouldn't bring this up as an issue except for the fact that all of my customer support issues since Rack 0.5.0 have been some variation of the user not knowing what .zip to place into the Rack/plugins directory.

Needless to say, this is not an issue with modules on the Plugin Manager.

**Comment by AndrewBelt** [comment]
That's what the Plugin Manager is for. If your plugin isn't on the VCV Store, people will have problems finding the correct file, placing it in the right place, and unzipping it. However,

>they do not unzip the .zip for their operating system inside of the master .zip file

No need to unzip the `MyPlugin-0.6.x-arch.zip` package anymore. Rack 0.6.0 does that for you if it finds a ZIP in the `plugins/` directory.

Wait, are you distributing ZIP packages inside a GitHub repo? It's bad practice to commit binary blobs to git.

**Comment by matthewfriedrichs** [comment]
That is the main issue. If they get all three .zip files in side of a ```MyPlugin-0.6.x-.zip```, they then do not go inside of that .zip and extract the ```MyPlugin-0.6.x-arch.zip```.  They have no issue getting the file. Just installing it.

If ```MyPlugin-0.6.x-.zip``` containing all three .zip files is placed inside of the Rack/plugins directory, the correct ```MyPlugin-0.6.x-arch.zip``` is not unzipped by Rack. None currently are, but it would be ideal if Rack could also handle this step too. 

The .zip files are not distributed on GitHub in this instance.

**Comment by AndrewBelt** [comment]
In what case would a user obtain such a ZIP file containing all three ZIP files?

**Comment by AndrewBelt** [comment]
You could let them choose their platform or use https://gist.github.com/AndrewBelt/2c8fbe4ca24231a147e348391fa747d6 or use the VCV Store.

**Comment by matthewfriedrichs** [comment]
I am currently letting the end user choose their package.  For the next set of release updates, I will switch to the zip merge method to place all plugins into a ```MyPlugin-0.6.x-all.zip```. If there is already a standard naming convention I should use for that .zip file, please let me know. Otherwise, this issue should be solved.

**Comment by AndrewBelt** [comment]
`SLUG-VERSION.zip` is the convention for combined packages, but I'm actually recommending the separate ZIP method now.
