### ISSUE TITLE
Tag plugin pack repos for Rack 0.6.0

### ISSUE THREAD

**Issue by mkoskar** [VCVRack/Rack#911]
With Rack 0.6.0 released (and tagged) at least Fundamental (but also other plugin pack repos) should be also tagged with 0.6.0 compatible release.

**Comment by AndrewBelt** [comment]
I'm curious why you have this request.

**Comment by mkoskar** [comment]
I'm maintaining Rack package and per plugin pack package for ArchLinux in AUR. That means I build Rack and don't use binary package. Since 0.6.0 was released and tagged I set to update the package/s but what "version" of Fundamental should I include? Last tagged version is 0.5.1.

**Comment by AndrewBelt** [comment]
Okay thanks, fixed.
