### ISSUE TITLE
0.5.1 breaks favourites in 0.6

### ISSUE THREAD

**Issue by patman023** [VCVRack/Rack#914]
Win10Home
Rack 0.5.1 and Rack 0.6

Opening Rack 0.5.1 accidentally, ended up wiping the favourites list out for 0.6. 

Possible suggestion is to store favourites in a different file?
------
Replication: 09h58 opened 0.5.1, 10h00 opened 0.6 (files wont upload, will try in comments)

**Comment by AndrewBelt** [comment]
Rack 0.5 is no longer supported. If you need to run it, move your `Documents/Rack/` directory to a backup and restore after running.

**Comment by patman023** [comment]
[log_0958.txt](https://github.com/VCVRack/Rack/files/1904041/log_0958.txt)
[settings_0958.json.txt](https://github.com/VCVRack/Rack/files/1904043/settings_0958.json.txt)
[log_1000.txt](https://github.com/VCVRack/Rack/files/1904044/log_1000.txt)
[settings_1000.json.txt](https://github.com/VCVRack/Rack/files/1904046/settings_1000.json.txt)
