### ISSUE TITLE
Rack via RDP

### ISSUE THREAD

**Issue by antosond** [VCVRack/Rack#915]
Windows 10 on both computers.
When i use Rack via RDP and if I click "mouse down" on any drageable control, mouse cursor will disappear and control skip to max or min value. 
After "mouse up" mouse cursor appear in center of window.   
It occurs on all module controls toolbar sliders and on scroll sliders too. 
Buttons, switches, wiring and module moving is OK.

**Comment by AndrewBelt** [comment]
RDP doesn't allow your cursor to be locked from the host that's controlling it. Set `"allowCursorLock": false` in settings.json.
