### ISSUE TITLE
Weird engine sample rate when no audio used

### ISSUE THREAD

**Issue by MarcBoule** [VCVRack/Rack#919]
Operating system(s): Win10
Version if official Rack release, commit hash and/or branch if from source: 0.6

When no audio core module is used, the engine's sample rate is acting weirdly (inconsistently). Here is a test case to show the issue: stating from a clean Rack:
* set engine rate to 44.1 kHz
* instantiate a fundamental SEQ3
* observe the sequencer's clock rate (internal clock)
* change engine rate to 88.2kHz, 96kHz or other higher rate
* the sequencer's clock rate can be seen to be much higher when it should be unchanged
* now add a core audio module and select a valid sound device (set at 44.1k in my case, and not bridge)
* repeat the test and SEQ3's clocking is stable even when changing engine rates

Perhaps this is not a bug, but I found it strange so I thought I would notify it. I was working on a new sequencer, with no audio, and was getting some strange step() timings, i.e. the step() function was not being called ``engineGetSampleRate()`` times per second on higher engine sample rates.

It's not a problem for me, but if someone is using Rack without an audio device (for visualizations, or through bridge), then it may be an issue.

The issue is not present on Mac nor on Linux.

**Comment by DomiKamu** [comment]
Hi Marc, I've received your message this Sunday, also I've already observed this fact, as long as you don't don't set Audio module to existing audio device. It's also true when you change engine sample rate. This problem is exising in 0.5.1 (first version I was used when I have discover VCV Rack).

**Comment by phdsg** [comment]
see https://github.com/VCVRack/Rack/issues/665 for a mini explanation.

**Comment by MarcBoule** [comment]
Thanks @phdsg, since it is known by @AndrewBelt, I guess I close the issue then. Strange thing though, is that in 665 the problem is on Mac, and in my case, no issue on Mac nor Linux. In any case, it's a fringe effect, so no big deal. It was funny to read the original post in 665, it happened almost exactly like that for me, except with a sequencer instead of an EG. Cheers!
