### ISSUE TITLE
RedGreenBlueLight Widget Question

### ISSUE THREAD

**Issue by djpeterso23662** [VCVRack/Rack#920]
I searched and could not find any VCV Rack issues with the RedGreenBlueLight widget, so maybe it is just me.  I am working on a UI that needs several colors of lights, so I thought I would give the RedGreenBlueLight widget a try.  However, I am having a hard time hitting the desired colors using 0 - 255 brightness values from typical RGB websites, scaled down to 0.0f to 1.0f light widget values.  Have you developed any rules of thumb for hitting the correct color?  Or was this widget specifically for Warps and therefore designed to have pastel colors only?  Should I punt and use the OrangeYellowGreenCyanBluePurpleRedLight widget instead?  Thanks for your time!

**Comment by AndrewBelt** [comment]
Yes, `RedGreenBlueLight` uses the color scheme at the top of componentlibrary.hpp. You can create your own with exact RGB colors by subclassing and calling `addBaseColor()` for each color.

**Comment by djpeterso23662** [comment]
Okay, thanks for the pointers, @AndrewBelt, I will give it a try with addBaseColor() for each color.

**Comment by AndrewBelt** [comment]
Of course, you should only need three colors if you specify exact red/green/blue colors, because combining them should give you exact RGB colors.
