### ISSUE TITLE
Playback problem with PulseAudio

### ISSUE THREAD

**Issue by yshui** [VCVRack/Rack#921]
Operating system(s): Linux
Version if official Rack release, commit hash and/or branch if from source: master

When using Rack with pulseaudio, the audio will be broken up. There will be sound for a while, then it stops, and then starts again. Each cycle it about a second long.

Changing the buffer size doesn't change anything.

**Comment by AndrewBelt** [comment]
PulseAudio is not supported at the moment.

**Comment by yshui** [comment]
That's OK. But let's keep this issue open so we are aware there're problems with Pulse?

**Comment by modlfo** [comment]
Closing this issue. Audio related problems in Linux will be covered in #1317
