### ISSUE TITLE
Suggestion for ui improvements

### ISSUE THREAD

**Issue by razvanab** [VCVRack/Rack#922]
Left or right side panel with a list of all the modules.
example:

![example](https://user-images.githubusercontent.com/2854730/38814830-25725a56-419b-11e8-8fcc-b863acadd2f5.jpg)

**Comment by WIZARDISHUNGRY** [comment]
Just moving the placement of the existing module browser to the right hand side of the display would improve my workflow.

**Comment by ndrspcfd** [comment]
I think the addition of a detachable module browser / toolbox window, from which you can drag modules onto the main Rack window, would be nice in some situations, but I admit I'd far rather wait until after all obvious performance improvements and 1.0 features are in place.

**Comment by nay-seven** [comment]
For me a simple switch to lock the browser opened could be a first good step ?

**Comment by AndrewBelt** [comment]
I prefer the centered Module Browser position. It is closer to the average position you are looking at than the sides.
