### ISSUE TITLE
new linker error: `BrotliDecoderVersion

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#923]
pulled source last night. did clean in dep. In windows got link errors like this:
```
dep/lib\libcurl.a(libcurl_la-version.o):version.c:(.text+0x68): undefined reference to `BrotliDecoderVersion'
dep/lib\libcurl.a(libcurl_la-version.o):version.c:(.text+0x73): undefined reference to `BrotliDecoderVersion'
dep/lib\libcurl.a(libcurl_la-version.o):version.c:(.text+0x13b): undefined reference to `BrotliDecoderVersion'
```
I think I need libbrotli or libbrotli-dev, but either these aren't available via pacman, or they have different names.

**Comment by phdsg** [comment]
there's a brotli package in pacman but installing that doesn't fix this.
guess it has to do with how curl is configured/compiled...

**Comment by squinkylabs** [comment]
yeah, no "brotli-dev"...

**Comment by squinkylabs** [comment]
I'm able to build 0.6.0. I guess 0.6 is the "wild west" branch. Going to stick on 0.6.0 for mac, windows, and linux for now.

**Comment by AndrewBelt** [comment]
Fixed a few days ago.
