### ISSUE TITLE
single-o vst module

### ISSUE THREAD

**Issue by caseybasichis** [VCVRack/Rack#924]
I'm looking to write a simple vst wrapper to load single modules in an in-host vst plugin, no gui, host automation.

Is there a way to haul in the module selection modules so purchased ugens can be used, or is those function tightly bound?

Any obstacles stand out?

**Comment by AndrewBelt** [comment]
That seems nearly impossible because you have to resolve thousands of symbols from the compiled VCV Rack plugin binary. Run `nm -gu plugin.so` on your favorite plugin to see how many symbols you'd need to resolve.

>Is there a way to haul in the module selection modules so purchased ugens can be used, or is those function tightly bound?

I can't parse this sentence.
