### ISSUE TITLE
Feature Request: GUID instead of ordinals for modules/wires instance IDs in .vcv files

### ISSUE THREAD

**Issue by dirkleas** [VCVRack/Rack#925]
Please consider using GUIDs instead of ordinal values for module (wiring pairs). This would make it much easier for supplemental tooling to work with .vcv files. For example, it would be extremely helpful to implement/use a scaffolding/utility cli tool to compose multiple patch fragments, identify/correct renamed slugs, perform patch analytics, move/reorganize modules, etc., and ordinal values add to the complexity of such implementations.

Thanks in advance for your thoughtful consideration.

**Comment by AndrewBelt** [comment]
The position of each object in the "wires" array can be considered the unique ID. Same with objects in the "modules" array. Perhaps I don't understand why you need this.

**Comment by dirkleas** [comment]
I'll assume a "magic rack CLI" exists with "everything" built in and easy to use for this comment. Let's look at an example use case of wanting to reuse a portion of a patch -- say one wanted to occasionally reuse a number of modules, configured and wired up a certain way. One could call the CLI with appropriate args and out pops some tasty JSON. Later, to reuse that exported fragment in a patch -- they could use the CLI to import the fragment into the new patch with some additional args that say where it should go (e.g. row, cols, etc. with all sorts of magical auto-formatting, etc.). Having ordinal keys on modules and thus the associated wiring requires that the entire patch be reasoned about to resolve ordering considering both existing and new aspects. GUIDs would allow the scope of work required in this import use case to be dramatically reduced, alleviating the ordering concerns.

**Comment by dirkleas** [comment]
I'm experimenting with some simple modifications to RackWidget to support importing patches by overloading fromJSON() to clear() by default, but optionally not clear(). Multiple imports cause segfault when attempting to exit Rack -- looks like it's due to the assumed clear() and ordinal references becoming jumbled. This is another use case in support for concrete keying of modules/wire references. a "key" based on the plugin+module+position with an appropriate separator then hashed would be appropriate -- ideally derivable by patch cotext and deterministic based on module movement over time in the active patch and subsequent imports? Code available upon request.

**Comment by AndrewBelt** [comment]
All objects in the .vcv patch file have IDs, as of Rack v1, which are incremented from 1 after the patch is initialized.

**Comment by AndrewBelt** [comment]
Rack v2 will use randomly generated 53-bit integers for module and cable IDs.
