### ISSUE TITLE
Suggestion: User-created objects consisting of groupings of connected modules in functional units

### ISSUE THREAD

**Issue by vogelscheiss** [VCVRack/Rack#927]
For the suggestion box:
It would be great and very helpful if there were in some future release of VCV Rack a way of saving functional groupings of connected modules, for import into new patches.

For instance, I've created an 808 hi hat patch, but it consists of about 12 modules. It would be great to be able to create a group like that, do a Save As e.g. User Object / 808HiHat, then be able to import that  object – with its interconnections intact – into my future patches.

Whether that's conceivable or possible obviously I don't know. :)

**Comment by ZuluEchoRomeOscar** [comment]
See https://codepen.io/nebularnoise/details/PRQMpp for a stop gap solution: it takes two .vcv files and merges them into a third.

**Comment by dirkleas** [comment]
also noodling some rack [cli scaffolding](https://github.com/dirkleas/rackcli) as a clearing house for this and tons of other use cases... it'll be a cross-platform binary(s) as it interacts with the local rack instance, installed plugins/modules, and patches. thoughts? w00t!

**Comment by Strum** [comment]
@dirkleas 

Great idea, could be developed into a very useful tool.

**Comment by AndrewBelt** [comment]
Avoid "+1" and "me too" comments. Please vote on feature requests by using the Thumbs Up/Down reaction on the first post.

**Comment by AndrewBelt** [comment]
Users seem to be satisfied with [PackOne](https://github.com/stoermelder/vcvrack-packone) STRIP, so I believe this issue can be closed.
