### ISSUE TITLE
How To Use VCVBridge in FL Studio 12?

### ISSUE THREAD

**Issue by ezzong** [VCVRack/Rack#934]
Hi guys, i’m such a noob that i felt stupid to ask this question, but i’ve yet to find a helping answer on using VCVBridge in FL Studio. As much as i really enjoy using the standalone app i would really like to record and multitrack the sounds that i have created in Rack.
I’ve added the VCVBridge in my mixer effects list, but that seems to do nothing. I would really appreciate the step by step instruction because all i could find on the internet is instructions for Ableton only.
Thank you very much.

**Comment by nay-seven** [comment]
here a link in FB group:
[[https://www.facebook.com/groups/vcvrack/permalink/170745043585648/](url)](FB link)

**Comment by ezzong** [comment]
i'm really sorry but that link seems error or blocked by my internet service, i can't access it. Will it be possible to copy the directions directly here? Appreciate it

**Comment by nay-seven** [comment]
sorry, this video is not on youtube , but directly on Facebook grooup, 
you can find it by using the search function of the Group.
I can't give you directions, cause i don't use FL studio myself.

**Comment by modlfo** [comment]
Closing because the Bridge is discontinued.
