### ISSUE TITLE
C++ How should this really be done?

### ISSUE THREAD

**Issue by alto777** [VCVRack/Rack#935]
OK, I am alarming myself with successes ~~hacking~~ modifying this C++ stuff, again a testament to the design of Rack and not my giant brain.

I made a nice slide fader, and later turned it horizontal after seeing, I thought, that it was mostly a matter of the SVGs. It worked except very slowly, of course it turns out that it is based on Knobs which appreciate only vertical mouse dragging…

I added 

	void onDragMove(EventDragMove &) override;

to my SVGSlider object, and then did this:

	void horizontalSlidePot::onDragMove(EventDragMove &e)
	{
		float temp = e.mouseRel.x;
		e.mouseRel.x = e.mouseRel.y;
		e.mouseRel.y = temp;

		SVGSlider::onDragMove(e);
	}

which sorta offends me but works a charm.

How should it be done? I also thought that maybe Knob's onDragMove could work no matter you move the mouse H or V - when the drag is done the mouse position is unchanged anyway, so why not?

**Comment by baconpaul** [comment]
Ha that’s a cute hack.

The reason it works is ondragmove in svgslider uses e.mouserel.x explicitly and ignores e.mouserel.y

https://github.com/VCVRack/Rack/blob/e90301faf3fc7e5515220f7b8e8770a1ea4c0f04/src/ui/Slider.cpp#L20

Is the line you want. So your solution is fine (although pedantically you may want to use a - on your transformation of relative y moves to get a proper 90 degree rotation) but the other solution would be to cnp the onmousemove from svgslider into your class as an override and change the x to y.

**Comment by alto777** [comment]
Thank you, that makes sense. I wish I had kept better track of the detective work that went into this, one of my first steps deep into. It.

My horizontal slider goes the same way I move the mouse, perhaps I was lucky - I was fully prepared, from your comment, to find that in my excitement about getting it to work I failed to notice that it was backwards…

**Comment by baconpaul** [comment]
Oh yeah the relevant part of your rotation was correct. My comment was self-identified as pedantic because if you set rel.x to rel.y you should probably set rel.y to -rel.x, even though it is unused. Chuckle.

You could also imagine an arbitrarily-rotated-svg-slider which uses sin and cos to adjust the relative x and y in the slide and uses nvgRotate() in the draw method and adjusts the hit tests and bounds. That would be the most pointlessly over-engineered way to proceed (and I’m not seriously suggesting it of course).

**Comment by baconpaul** [comment]
Oh shoot you are right of course. I should have looked at my notes from when I subclassed it.

Anyway SVGSlider and SVGFader are both instances of Knob and FrameBufferWidget. Knob has a very similar onChange behavior vis-a-vis x

https://github.com/VCVRack/Rack/blob/e90301faf3fc7e5515220f7b8e8770a1ea4c0f04/src/app/Knob.cpp#L31

but then also supports slow drags with mod. But still that line just uses y.

I still think your diff is the right way to proceed though.

**Comment by AndrewBelt** [comment]
@alto777 Your first guess is close to what I'd do. Just don't modify `e` since it can affect other widgets.
```cpp
void onDragMove(EventDragMove &e) override {
	EventDragMove eFlipped = e;
	eFlipped.mouseRel = Vec(e.mouseRel.y, e.mouseRel.x);
	SVGSlider::onDragMove(eFlipped);
}
```

**Comment by alto777** [comment]
@AndrewBelt Of course, better. I thought briefly of re-exchanging x and y after the call-through! But thought why bother?  I admit to not appreciating that the variable is passed by reference.

@baconpaul Haha, not to be picky, but the original line you quoted from Slider just uses x… as I was falling asleep I thought wait, why do Sliders work if they use y? And I wondered until I tried it if all this time the UI Sliders had been responding to vertical mouse movemetns. Not. :-)

thanks for the help.
