### ISSUE TITLE
Document the concurrency model for plugins

### ISSUE THREAD

**Issue by korfuri** [VCVRack/Rack#939]
Hi, and thanks a lot for the awesome product that is Rack! I've been playing with it and its module SDK for a few days, and I'm starting to make some modules that have what looks like possible data races. I wasn't able to find documentation on this topic, so I'm raising this here.

What is the concurrency model for plugins? I understand that 2 modules shouldn't expect to be executed in any particular sequence or even at different times, but am I correct in making the following assumptions:
- step() may not be invoked more than once per instance of a module at any given time (i.e. you don't start processing the next sample while the current one hasn't finished)
- draw() for a GUI element on a given module and step() for that module may not be in execution at the same time (this is important if the GUI and the module hold references to one another so the GUI can display module info)

Are there other pitfalls that I should be aware of, concurrency-wise?

I realize, of course, that the API may change in the future including concurrency guarantees, but I'd like to make sure I'm not missing a mutex in my code for now :)
Thanks!

**Comment by AndrewBelt** [comment]
`Module::step()` is called by the engine thread only.
`Widget::step()` and `Widget::draw()` is called by the main thread only.
