### ISSUE TITLE
Rack + RtAudio + JACK crashes when many outside JACK clients are present.

### ISSUE THREAD

**Issue by caoliver** [VCVRack/Rack#940]
I usually use a number of synths, samplers, and effect at the same time.  I found that Rack crashes when the core/audio module is present when there are a number of other clients present.

I'm running Slackware Linux 14.2.  JACK is JACK2.  RtAudio module is the bundled module configured to enable JACK.  The crash seem to happen when RtAudio opens a jack connection in order to
enumerate the other ports.  The arguments to that call look good, and the Futex call should involve Rack specified parameters.  Do we have a stack corruption issue?  Attached please find a stack dump for the simplest version of this crash.  (The other clients were nine instances of foo-yc20 though the bug was initially discovered with different clients.)

---- Backtrace follows ----

Script started on Wed 02 May 2018 02:15:26 PM EDT
GNU gdb (GDB) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-slackware-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./Rack...done.
(gdb) run
Starting program: /tmp/.oliver_kyUjzG/Rack/Rack 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[0.000 info] Rack master
[0.000 info] Current working directory: /tmp/.oliver_kyUjzG/Rack
[0.000 info] Global directory: ./
[0.000 info] Local directory: ./
[0.197 info] Loaded font ./res/fonts/DejaVuSans.ttf
[0.197 info] Loading settings ./settings.json
[0.197 info] Saving settings ./settings.json
[New Thread 0x7fffe81b9700 (LWP 17366)]
[New Thread 0x7fffe43c5700 (LWP 17367)]
[New Thread 0x7fffe4344700 (LWP 17368)]

Thread 1 "Rack" received signal SIGSEGV, Segmentation fault.
0x00007fffec63843e in Jack::JackLinuxFutex::Connect(char const*, char const*)
    () from /usr/local/lib/libjack.so.0
(gdb) bt
#0  0x00007fffec63843e in Jack::JackLinuxFutex::Connect(char const*, char const*) () at /usr/local/lib/libjack.so.0
#1  0x00007fffec6390d9 in Jack::JackLibClient::Open(char const*, char const*, int, JackOptions, JackStatus*) () at /usr/local/lib/libjack.so.0
#2  0x00007fffec639fe7 in jack_client_open_aux(char const*, JackOptions, JackStatus*, __va_list_tag*) () at /usr/local/lib/libjack.so.0
#3  0x00007fffec63a173 in jack_client_open () at /usr/local/lib/libjack.so.0
#4  0x00007ffff42c3b93 in RtApiJack::getDeviceCount() (this=<optimized out>)
    at RtAudio.cpp:1970
#5  0x00007ffff42c735e in RtAudio::RtAudio(RtAudio::Api) (this=0xe36500, api=<optimized out>) at RtAudio.cpp:200
#6  0x0000000000440a2d in rack::AudioIO::AudioIO() (driver=0, this=0x7fffe43c6080) at src/audio.cpp:58
#7  0x0000000000440a2d in rack::AudioIO::AudioIO() (this=0x7fffe43c6080)
    at src/audio.cpp:10
#8  0x000000000046b15b in rack::Model* rack::Model::create<AudioInterface, AudioInterfaceWidget, rack::ModelTag>(std::string, std::string, std::string, rack::ModelTag)::TModel::createModuleWidget() (this=0x7fffe43c6080)
    at src/Core/AudioInterface.cpp:25
#9  0x000000000046b15b in rack::Model* rack::Model::create<AudioInterface, AudioInterfaceWidget, rack::ModelTag>(std::string, std::string, std::string, rack::ModelTag)::TModel::createModuleWidget() (this=0x76fcb0)
    at src/Core/AudioInterface.cpp:127
#10 0x0000000000484c37 in rack::ModelItem::onAction(rack::EventAction&) (this=<optimized out>, e=...) at src/app/ModuleBrowser.cpp:166
#11 0x0000000000484de1 in rack::BrowserListItem::onDragDrop(rack::EventDragDrop&) (this=<optimized out>) at src/app/ModuleBrowser.cpp:92
#12 0x0000000000484de1 in rack::BrowserListItem::onDragDrop(rack::EventDragDrop&) (this=<optimized out>, e=...) at src/app/ModuleBrowser.cpp:86
#13 0x0000000000456d68 in rack::mouseButtonCallback(GLFWwindow*, int, int, int) (window=window@entry=0x798100, button=0, action=<optimized out>, mods=<optimized out>) at src/window.cpp:115
#14 0x000000000045758c in rack::windowRun() () at src/window.cpp:142
#15 0x000000000045758c in rack::windowRun() () at src/window.cpp:433
#16 0x0000000000436aac in main(int, char**) (argc=<optimized out>, argv=0x7fffffffe408) at src/main.cpp:57
(gdb) quit

**Comment by caoliver** [comment]
I can't use the editor from this browser.  I mean the futex should NOT involve any Rack supplied params.  Eeek.

**Comment by AndrewBelt** [comment]
See #730

**Comment by caoliver** [comment]
Good grief!  I've dealt with far worse (basically worthless) PRs in the software I've developed and contributed to without complaint.  Toughen up!

```
GNU gdb (GDB) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-slackware-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./Rack...done.
(gdb) run
Starting program: /tmp/.oliver_kyUjzG/Rack/Rack 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[0.000 info] Rack master
[0.000 info] Current working directory: /tmp/.oliver_kyUjzG/Rack
[0.000 info] Global directory: ./
[0.000 info] Local directory: ./
[0.197 info] Loaded font ./res/fonts/DejaVuSans.ttf
[0.197 info] Loading settings ./settings.json
[0.197 info] Saving settings ./settings.json
[New Thread 0x7fffe81b9700 (LWP 17366)]
[New Thread 0x7fffe43c5700 (LWP 17367)]
[New Thread 0x7fffe4344700 (LWP 17368)]

Thread 1 "Rack" received signal SIGSEGV, Segmentation fault.
0x00007fffec63843e in Jack::JackLinuxFutex::Connect(char const*, char const*)
    () from /usr/local/lib/libjack.so.0
(gdb) bt
#0  0x00007fffec63843e in Jack::JackLinuxFutex::Connect(char const*, char const*) () at /usr/local/lib/libjack.so.0
#1  0x00007fffec6390d9 in Jack::JackLibClient::Open(char const*, char const*, int, JackOptions, JackStatus*) () at /usr/local/lib/libjack.so.0
#2  0x00007fffec639fe7 in jack_client_open_aux(char const*, JackOptions, JackStatus*, __va_list_tag*) () at /usr/local/lib/libjack.so.0
#3  0x00007fffec63a173 in jack_client_open () at /usr/local/lib/libjack.so.0
#4  0x00007ffff42c3b93 in RtApiJack::getDeviceCount() (this=<optimized out>)
    at RtAudio.cpp:1970
#5  0x00007ffff42c735e in RtAudio::RtAudio(RtAudio::Api) (this=0xe36500, api=<optimized out>) at RtAudio.cpp:200
#6  0x0000000000440a2d in rack::AudioIO::AudioIO() (driver=0, this=0x7fffe43c6080) at src/audio.cpp:58
#7  0x0000000000440a2d in rack::AudioIO::AudioIO() (this=0x7fffe43c6080)
    at src/audio.cpp:10
#8  0x000000000046b15b in rack::Model* rack::Model::create<AudioInterface, AudioInterfaceWidget, rack::ModelTag>(std::string, std::string, std::string, rack::ModelTag)::TModel::createModuleWidget() (this=0x7fffe43c6080)
    at src/Core/AudioInterface.cpp:25
#9  0x000000000046b15b in rack::Model* rack::Model::create<AudioInterface, AudioInterfaceWidget, rack::ModelTag>(std::string, std::string, std::string, rack::ModelTag)::TModel::createModuleWidget() (this=0x76fcb0)
    at src/Core/AudioInterface.cpp:127
#10 0x0000000000484c37 in rack::ModelItem::onAction(rack::EventAction&) (this=<optimized out>, e=...) at src/app/ModuleBrowser.cpp:166
#11 0x0000000000484de1 in rack::BrowserListItem::onDragDrop(rack::EventDragDrop&) (this=<optimized out>) at src/app/ModuleBrowser.cpp:92
#12 0x0000000000484de1 in rack::BrowserListItem::onDragDrop(rack::EventDragDrop&) (this=<optimized out>, e=...) at src/app/ModuleBrowser.cpp:86
#13 0x0000000000456d68 in rack::mouseButtonCallback(GLFWwindow*, int, int, int) (window=window@entry=0x798100, button=0, action=<optimized out>, mods=<optimized out>) at src/window.cpp:115
#14 0x000000000045758c in rack::windowRun() () at src/window.cpp:142
#15 0x000000000045758c in rack::windowRun() () at src/window.cpp:433
#16 0x0000000000436aac in main(int, char**) (argc=<optimized out>, argv=0x7fffffffe408) at src/main.cpp:57
(gdb) quit
A debugging session is active.

	Inferior 1 [process 17362] will be killed.

Quit anyway? (y or n)
```

**Comment by caoliver** [comment]
Oops.  I may have reacted hastily.  Are you receiving this via email and the lines are wrapped?  The lines are wrapped but broken in the proper places if viewed on github.  I will confess that getting a complaint about formatting when one has put effort into offering detail can bring out the rage in a person.  It looks like a gratuitous hoop through which to jump.  I may be wrong.  In any case, I'm thinking this needs the tender ministrations of valgrind.

**Comment by AndrewBelt** [comment]
You've also failed to fill out the bug report template. This issue is with Jack, not Rack.
