### ISSUE TITLE
No MIDI devices available

### ISSUE THREAD

**Issue by MaurizioB** [VCVRack/Rack#95]
Using a locally built Rack on a 32bit Linux platform (Gentoo Linux), the MIDI Interface module shows no available MIDI interfaces to use in the drop down menu.

**Comment by AndrewBelt** [comment]
What does this test program print?

	#include <stdio.h>
	#include <portmidi.h>

	int main() {
		Pm_Initialize();
		printf("%d\n", Pm_CountDevices());
	}
