### ISSUE TITLE
VCV Rack Development Roadmap

### ISSUE THREAD

**Issue by dirkleas** [VCVRack/Rack#951]
It would help to reduce duplicate efforts (e.g. redirect energy to non-duplicate contributions) in the community by having a strawman roadmap oriented towards developers of either VCV Rack or plugins/modules. This wouldn't have to be terribly detailed, just a list of bullets/comments per planned releases. This wouldn't imply commitment/obligation/etc., but merely let folks interested in contributing to work without duplicating efforts.

For example, if you're planning on features like module layout management, patch fragment import/export, midi output, MPE support, etc., then community members interested in contributing could either collaborate with you per your invitation or work on other features.

**Comment by AndrewBelt** [comment]
I was considering something like that, but it will probably do more harm than good. People would complain when I don't deliver something on time, even if I express that dates and tasks are completely arbitrary. Given that https://github.com/VCVRack/Rack/milestones is completely out of date and wrong, I imagine a textual list would be as well.

**Comment by dirkleas** [comment]
The requested roadmap purposely didn't include a time dimension -- I completely agree with your sentiments on the risk of time-oriented complaints.

**Comment by AndrewBelt** [comment]
If people want to create issues here for discussions, that's perfectly fine. See https://github.com/VCVRack/Rack#the-issue-tracker-is-the-official-developers-forum

**Comment by dirkleas** [comment]
that doesn't resolve the intent of this issue if people open discussions, especially for volunteer proposals unless you weigh in to correlate your plans -- hence, the roadmap request seems prudent

**Comment by AndrewBelt** [comment]
I don't understand. Are you asking if people may open issues to discuss making a clock multipler, so two people don't make a clock multiplier, or for people wanting to help with Rack itself?

**Comment by dirkleas** [comment]
rack itself -- see the examples I enumerated in the initial post above. the process for plugin/modules is quite clear

**Comment by AndrewBelt** [comment]
Ah. I don't accept contributions from unpaid developers because I would spend more time than if I just worked on it alone. If you want to work on a feature, I'll have to hire you, but nothing is urgent enough to justify the cost at this time. See #807. However, there are many areas regarding Rack where you *could* help, and it would be appreciated. I'll add that to the above issue.

**Comment by AndrewBelt** [comment]
Added https://github.com/VCVRack/Rack/issues/807#issuecomment-388254298

**Comment by dirkleas** [comment]
understood, thanks for the reference (convenience xref added to wiki) -- if folks desire capabilities not in rack, they may post "research" issues, but if they have interest in implementing/using said capabilities a fork w/t future PR is the appropraite route. please clarify if I'm not uderstading, thx otherwise

**Comment by AndrewBelt** [comment]
Yup, the "A complete feature design proposal" mentioned in my post is more than welcome for any feature request.

If someone's fork has a nice feature, I'll merge it, but to date I have not done that.

**Comment by modlfo** [comment]
Closing because the discussions seem to be over.
