### ISSUE TITLE
Sub-racks / custom modules?

### ISSUE THREAD

**Issue by trethaller** [VCVRack/Rack#955]
Wasn't able to find anything on this so: has there been any thought on implementing sub-racks or custom modules?
Right now polyphony involves duplication or using Gratrix which either way is quite painful. It would be awesome to be able to create a single voice as a custom rack, declare some inputs or parameters, and then load that voice as a module in a parent rack. With this you would basically not need Gratrix, you would just add N instances of your custom module.

To declare inputs or params in your custom module you would add `Param`s and `Input`s to your rack, either one per input/param (single jack) with a unique ID, or something with 1/4/16 slots like the MIDI modules.
You would have to declare outputs as well, but you could use the convention that AUDIO is the output, which has the benefit of making your sub-rack testable in standalone as well. 

Not sure yet how you would load the module in your parent rack, maybe all the .vcv files in some directories (including the dir of your current .vcv) would be scanned, and all the ones with input outputs would appear. 
You would have to generate a generic custom module widget depending on the input/outputs/params declared, unless again you use predefined slots. 
Workflow wise, it'd be useful to be able to hot-reload the module when the file has changed, so you can work with two instances and edit your sub-rack and parent rack simultaneously. Or even better, double-clicking on the module would open the sub-rack. 

As a side node, the ability to declare params would also be useful in VSTi mode, for presets for example.

--
_Edit: really love the project, I hadn't touched synths or dsp code in 10 years and I've been having a lot of fun so far!_

**Comment by ndrspcfd** [comment]
Unless I misunderstood, something like this has come up a few times before:

https://github.com/VCVRack/Rack/issues/209 , https://github.com/VCVRack/Rack/issues/655 , https://github.com/VCVRack/Rack/issues/927

**Comment by AndrewBelt** [comment]
Yeah, this feature request is too similar to the others listed.
