### ISSUE TITLE
Keybindings? 

### ISSUE THREAD

**Issue by Cordoha** [VCVRack/Rack#957]
Ubuntu 18.04
Rack Dev Version(built today)

Rebuilt Rack to see if keybindings/shortcuts would work, and there's currently no keybindings anymore. I can't duplicate modules, or make my mouse scroll at a lower DPI while pressing ctrl or shift while turning a knob.

Please replace the keybindings, they were super helpful.
Thanks

**Comment by AndrewBelt** [comment]
Works for me. What branch and commit hash are you on?

**Comment by Cordoha** [comment]
I believe it's just the master branch. I usually don't pull any others.

**Comment by Cordoha** [comment]
git show
commit bdead9603c0208913e6723aa6951832bb96d2a10 (HEAD -> master, origin/master, origin/HEAD)
Merge: a883f82 2a33037
Author: Andrew Belt <AndrewBelt@users.noreply.github.com>
Date:   Fri May 11 11:44:30 2018 -0400

    Merge pull request #953 from ArnaudE/master
    
    RtMidi Clients are named VCV Rack

**Comment by AndrewBelt** [comment]
Use the v0.6 branch since that's actively developed. You will likely need to clean and rebuild `dep/` after switching branches.

**Comment by Cordoha** [comment]
I've since compiled to 0.6.1dev. Keybindings don't work in Ubuntu 18.04.

commit de022e6f4a5695f425dc8915999c3dfde5316eb1 (HEAD -> v0.6, origin/v0.6, origin/HEAD)

**Comment by Cordoha** [comment]
Not familiar no. Not sure how to do that.

**Comment by Cordoha** [comment]
If you have the time, or a link to show me how to debug the information needed, let me know how to get what is needed so it can be fixed. I miss my keybindings.

**Comment by AndrewBelt** [comment]
Closing as obsolete.
