### ISSUE TITLE
Number of Params for Module is limited

### ISSUE THREAD

**Issue by almostEric** [VCVRack/Rack#958]
It seems there is a hard limit on the number of PARAMS (and I assume inputs and lights as well).
I'm trying to write a module that will not involve menu diving, but at about 130 parameters, RACK will crash

**Comment by AndrewBelt** [comment]
There shouldn't be a limit. Post the stack trace?

**Comment by almostEric** [comment]
It’s weird, when I got to a certain number of PARAMS, I would get a segmentation error on startup. But then I manually set the NUM_PARAMS to something silly like 400 and it runs.

**Comment by AndrewBelt** [comment]
That probably means you have undefined results in your code that's overwriting part of the Module class, so you should probably review your code or run it through a memory checker like valgrind.

**Comment by AndrewBelt** [comment]
Closing since you said you fixed it on Facebook.
