### ISSUE TITLE
how much GL memory can I use?

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Rack#959]
I think I know the answer, but the Q is:

If I allocate an image, is it an ok idea to hold onto it so I can use it next step call? Of should plugins give back all their GL memory between calls? ( I'm assuming that nanovg images live in GL texture buffers (in hardware)).

I'm guessing a plugin should not hold onto GL memory. If every plugin did it the system would stop working. But figured I would ask.

**Comment by AndrewBelt** [comment]
How big are your images? In the days of >256MB onboard GPUs, a 2MB image isn't much to worry about.

**Comment by squinkylabs** [comment]
good point. I'll give it a try and see how it goes. Semi related: is there any "contract" around plugins leaving the nanovg context in an particular state? If a plugin changes a transform or blend mode, should it restore everything before leaving the step() call?

**Comment by AndrewBelt** [comment]
Everything is saved/restored in `ModuleWidget::draw()`. The only thing you shouldn't do is accidentally mismatch any `nvgSave()` and `nvgRestore()` calls since that misaligns the state stack.

**Comment by modlfo** [comment]
Closing this issue because loos it has been answered.
