### ISSUE TITLE
VCV Rack to MIDI (MTC)

### ISSUE THREAD

**Issue by nunooo** [VCVRack/Rack#961]
Was wondering if there is a way to get MIDI out of VCVRACK

I was hoping to go:

From Ableton to VCVRack via Link

In VCVRack use the clock divider

then Out of VCVRack to Midi Out to my external gear (Makenoise O-Coast for example)

Any chance?

**Comment by squinkylabs** [comment]
Would you really want MTC out? MTC is just an endless "wall clock". Good old MIDI start/stop/continue and clock might be more fun, but what would the interface be? A gate that when it goes low to high sends a start, hi to low a stop, plus a clock multiplier to take a slower clock up to 24 PPQ?

Oh, wait, I could see MTC.. but the module would need to let you set the "start" position in H:M:S:F:-... sounds complicated, though,

**Comment by nunooo** [comment]
I was using a plugin from Expert Sleepers (Clocker) to send clock to my Make-noise with Midi
It was great because I could choose the tempo (Ableton just sends regular clock, can't change it)

So I could have (for example) my O-Coast LFO running at 1/16ths instead of just the beat of Ableton's clock.  But was either with High Sierra OS or Ableton 10, this plugin doesn't work anymore..  Sure I could go Midi to a CV converter, then into a clock divider... but I don't have that eheh 

That's one example I can give you... I don't know how others might find it useful :)

**Comment by AndrewBelt** [comment]
CV-MIDI and other MIDI output modules were added in Rack v1.
