### ISSUE TITLE
state of Rack

### ISSUE THREAD

**Issue by alto777** [VCVRack/Rack#962]
What would I need to save and restore to ensure launching Rack identically? So far, refreshing autosave.vcv and settings.json are all I see.

I'm working on finding an error that manifests in module instantiation whether by adding or duplicating. Crash. So far I have not been able to create any consistently reproducible experiment. Still experiencing crashes after rolling back "everything" that I tinkered with, I started to consider the state of Rack and the autosave or known good *.vcv of my own. If I have managed to get a patch built with my plugin, it tolerates changes to my plugin across launches - until I add/do something that crashes Rack, then it's crashy no matter.

If I can dependably launch Rack w/ my plugin already there, I can spend some time draining the swamp and postpone the alligator thing.

I also wonder by what means Rack detects that its last run ended badly - sometimes it can, sometimes it deosn't.

**Comment by AndrewBelt** [comment]
I'm not sure what your question is.

All params are serialized/unserialized. If your module has other state information, you can add a `toJson()` and `fromJson()` method to your Module subclass.

**Comment by alto777** [comment]
If I replace autosave.vcv and settings.json with copies taken before I somehow trash things up, will I be able to consistently launch the same Rack?  Or does Rack save or consult anything else I could save away and replace (or delete) before I launch it again?

Not my module's state, Rack's state after, it seems, launching and opening autosave.vcv and applying settings.json. Is there anything else?

I just want things that can be in a known state. Clean slate. Fresh start.

I'm thinking about things like hidden files, preferences, phase of the moon, that kind of thing.

My other question is just curiosity: by what means does Rack detect that its last run ended badly?

**Comment by AndrewBelt** [comment]
Yes, those two files should be all that Rack loads. Of course, other plugins could load whatever they need, but Rack doesn't have control of that.

See https://github.com/VCVRack/Rack/blob/v0.6/src/main.cpp#L45-L56 for the answer to your second question. It describes it better than I would.

**Comment by alto777** [comment]
Thank you, yes. I had a sorta elaborate "stage" and this will help my confidence and bolster my first assumptions. I have something wrong way higher (sooner) than I thought, but it has a low probability of causing trouble, hence much spuriosity and caprice in the diagnosis phase.

Fun!
