### ISSUE TITLE
change Knob settings via switch?

### ISSUE THREAD

**Issue by Phal-anx** [VCVRack/Rack#964]
Need help. I wanted to know if it is possible to change from...

addParam(ParamWidget::create<BlueLargeKnob>(Vec(77, 32), module, Delay::TIME_A_PARAM, 0.0f, 26.5f, 13.0f));

to..

addParam(ParamWidget::create<BlueLargeKnob>(Vec(77, 32), module, Delay::TIME_A_PARAM, 0.0f, 1.0f, 0.5f));

with a switch on the module itself instead of the right-click menu. I know how to implement the right-click menu option but I would rather have a switch on the module itself.
How would the code for this look like? I tried quite I few things but could get it to work.

Any help is very appreciated!

**Comment by AndrewBelt** [comment]
Leave it up to your DSP code to rescale the param value depending on the switch state. Something like
```cpp
float x = params[SOME_PARAM].value;
if ((int) params[STATE_PARAM].value == 0)
    x *= 26.5f;
```

**Comment by Phal-anx** [comment]
ok if this is the better way then I m going to do it this way. thanks for your input!
