### ISSUE TITLE
Rack-to-MIDI Core modules proposal

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/Rack#966]
Feedback welcome.

## 1-MIDI

Inputs

- Pitch
	- 1V/oct
	- rounds to nearest MIDI note
	- 0V = C4
	- A change in value will produce a "note off" and "note on" MIDI message. Initially, there will be no artificial rate-limiting, so you will be limited by the speed of your MIDI hardware only. Be careful when sending audio-rate signals. When a good balance between speed is found, could add later.
- Gate
- Velocity
- Aftertouch
- Pitch wheel
	- Range -5V to 5V
- Mod wheel
- Transport
	- Start
	- Stop
	- Continue
- Clock

So far, this is exactly the appearance of MIDI-1 except without Retrigger and a second Clock input. So if we use a similar design, we have space for two more inputs. Ideas?

## TRIG-MIDI

- Copy inputs from MIDI-TRIG

## CC-MIDI

- Copy inputs from MIDI-CC
- Weird name, perhaps call them MIDI-CV and CV-MIDI instead?

## 4-MIDI

- Probably won't do. You should be able to use multiple 1-MIDI modules.
- If we do, copy inputs from MIDI-4

**Comment by MarcBoule** [comment]
Is there a reason you chose 0V = C3? I would have thought it would be like the Rack voltage standards (0V = C4). https://vcvrack.com/manual/VoltageStandards.html

**Comment by AndrewBelt** [comment]
Sorry, meant C4. MIDI octave numbers themselves aren't a fully-agreed standard.

**Comment by mhetrick** [comment]
TRIG-MIDI will be very useful for sequencing, say, an Elektron box from VCV. One consideration is that Velocity is still very important for drum programming. I would be in favor of 4-MIDI to clean up the workflow when outputting to a drum machine.

One edge case consideration: some drum machines (Analog RYTM and Nord Drum) use one MIDI channel per-track so that you can sequence melodic percussion (i.e. all channel 1 messages are the bass drum track only). I believe that this is optional on the Nord and mandatory on the RYTM. However, this edge case likely warrants a 3rd-party module based on the 4-MIDI source instead of adding per-output channel controls on 4-MIDI.

**Comment by AndrewBelt** [comment]
@mhetrick I'm not sure how 4-MIDI would be useful for drum machines. That would be better for quadrophonic hardware synthesizers. Perhaps https://github.com/VCVRack/Rack/issues/967 is a better solution.

For drum machine using different channels, I've created https://github.com/VCVRack/Rack/issues/968

**Comment by djpeterso23662** [comment]
VCVRACK users are always pushing toward the cutting edge. Someone will probably want to generate MIDI output similar to a Roli Seaboard or Block.

**Comment by djpeterso23662** [comment]
The trig to MIDI functions like the Ladik M-215, M-216, and M-217 would be super useful. Thanks so much for working on this request, @andrewbelt!

**Comment by djpeterso23662** [comment]
Are there any considerations when you are trying to build a slow MIDI LFO?

**Comment by AndrewBelt** [comment]
@djpeterso23662 Not really, slow LFOs would just generate slow CC changes.

**Comment by armandvedel** [comment]
I'd like CV to Midi note to be as flexible as possible. For instance, imo the module should have the option to wait for a gate to generate note on and off (in addition to the option of automatically changing in value when the voltage changes).  Also, instead of just rounding, it would be great if it could round while also simultaneously producing pitch bend data to do microtuned notes.

**Comment by shurikenyo** [comment]
Can you please do the pitchbend value Rack to MIDI 14 bit? Many seem to just do it the same 7 bit as any other CC#...My Doepfer dark energy's midi to CV interface for example is only 7 bit for the pitchbend (i guess skimping on the DAC)...but my good old EMU Command Station has 14 bit values internally for the pitchbend. 

Also how about a converter/re-routing module for the MIDI where we can convert midi CC# to SysEx or NRPN or polyaftertouch messages...but that may be for another thread..like the midi solutions event processor.
http://midisolutions.com/prodevp.htm

thx

**Comment by djpeterso23662** [comment]
Perhaps the 7-bit or 14-bit or whatever setting could be on the right-click context menu for all the MIDI output modules?

**Comment by VSpellbound** [comment]
{request]
Polyphonic version with 6 х 1V/oct, 6 х Velocity etc.

**Comment by AndrewBelt** [comment]
@armandvedel For your first request, a MIDI "note on" message will be generated only when GATE is high. Does this satisfy your request?
For your second, I think that is better left to an external specialized module that someone might develop. The reason is that you need the pitch bend amount (+/-1, 2, ..., or 12 semis) in order to generate meaningful pitch wheel messages. It would also need to assume a tuning like equal temperament. Currently it only assumes 1/12 V per semi, which is approximately every 12-note tuning after rounding, depending on how your MIDI hardware interprets it. A "CV to note + pitch wheel" would need to consider small changes in the temperament.

**Comment by armandvedel** [comment]
@andrewbelt Regarding the first request, yes that would work. I guess I would just have to put an S+H before the module if i wanted to send a note on only when gate goes high. As for the second, please someone make the described module!

**Comment by AndrewBelt** [comment]
@shurikenyo @djpeterso23662 Since I don't have a 14-bit MIDI input or output device, I can't test the feature, so I'll have to wait until I buy one.

**Comment by AndrewBelt** [comment]
@VSpellbound I'll consider the 4-MIDI (quadrophonic interface), but for six, perhaps someone could contribute a module to the Gratix plugin. It's easy to add Rack's full MIDI capability to your module. Add a `MidiInputQueue` to your module and put `MidiMessage msg; while (midiInput.shift(&msg)) {...}` in your `Module::step()` function. For the GUI, add a `MidiWidget` to your `ModuleWidget` or implement your own using your own custom design.

**Comment by AndrewBelt** [comment]
@armandvedel Now that I think about it, the feature

>A change in value will produce a "note off" and "note on" MIDI message

is unnecessary. It is more straightforward and low-level (thus a better design for the Core MIDI modules) to only generate "note on" and "note off" for the value of the CV input at the time of the gate trigger. Users who wish to have the original behavior can retrigger using other modules.

**Comment by armandvedel** [comment]
@AndrewBelt I agree that this is the better implementation

**Comment by djpeterso23662** [comment]
Does anyone on this thread use MIDI to control lighting rigs?  It will be a really powerful use of this feature!

**Comment by armandvedel** [comment]
Program change and Sysex, I guess would be the next most popular, for vintage hardware people.

**Comment by alectron** [comment]
Re: 'I still need ideas for two free input ports on 1-MIDI.'
Take this with a grain of salt as I am just getting my feet wet with modular... and I do not have an MPE capable device (but eyeing one...) - is there anything sensible to add to the midi module to enhance midi from MPE capable devices ?

**Comment by AndrewBelt** [comment]
@alectron Could you explain in detail what those two inputs would be, and how it would relate to MPE?

**Comment by alectron** [comment]
@AndrewBelt I'm mostly thinking out loud... I know too little about signal & midi processing to be able to contribute anything 'in detail' for this unfortunately as I am mostly an end-user of such :D 
But, I would have thought there might be additional signals to MPE in order to allow per-note vibrato & slide. Sounds like this is possible with Eurorack modules, alas, one would need a few specialized ones to allow so:

**Comment by AndrewBelt** [comment]
For the 1-MIDI module, MPE doesn't really make sense since that module is monophonic anyway, but I was wondering if there was some other unusual feature you were thinking of.

**Comment by shurikenyo** [comment]
"but what possible Sysex data could be converted from a voltage?"
The actual data part of the sysex message would be the only converted data...you would manually set the device ID, adress etc for the sysex message...then the CV from rack would only change the data part of the sysex message. Could be real handy..i have a few boxes that have limited configurable CC# channels for external control that would like this feature.  But i think Sysex is quite a bit slower so maybe there is a need to cap the rate for SysEx stuff.

Any chance for support for polyaftertouch? (maybe the CV to CC# module could have a rightclick option choosing CC# or poly aftertouch (Also called key pressure) I have a few devices that use poly aftertouch (KeyP) on some parameters..it is quite a rare thing i guess NRPN is more common...KeyP would be great to be able to use fo drums and pads...so to have it on the input module would also be great!

highnote, low note, last note priority. (but that would be for the input module, maybe via rightclick menu?) 

Ideas for the extra jack...midi song position? not sure maybe it would put things out of sync?! but could be a cool feature to be able to move around the timeline on a external midi device via CV from rack!

it would be nice with a little midi utility module for only one message at the time...but it could be selectable via a pulldown menu..stuff selectable could be: (taken from the Lemur editor)
80 - Note Off
90 - Note On
A0 - Key Pressure
B0 - Control Change
D0 - Channel Pressure
E0 - Pitch Bend
F0 - System Exclusive
F2 - Song Position
F3 - Song Select
F5 - Bus Select
F6 - Tune Request
F8 - Timing Tick
FA - Start Song
FB - Continue Song
FC - Stop Song
FE - Active Sensing
FF - System Reset

Just some ideas...

**Comment by AndrewBelt** [comment]
@shurikenyo Not following. You're welcome to implement this in your own module though!

**Comment by armandvedel** [comment]
@AndrewBelt Regarding sysex, some synths, such as the Roland Alpha Juno, only let you change parameters via sysex. It's kind of niche, but for those synths sysex is as indispensable as midi CC. However, I can also see why it would make sense a separate module, as one would need to specify the format of the sysex string differently for each synth..

**Comment by cunabula27** [comment]
@djpeterso23662 I use midi to drive all my VJing and am just learning to directly control openFrameworks sketches with midi, so yes this will be an excellent addition to Rack.

**Comment by squinkylabs** [comment]
I've never understood how 14 pitchbend is supposed to work. does the combined "value" change when the device gets the msb? the lsb? both in sequence? seems like   00 7f -> 01 00 could jump... does it matter?

**Comment by AndrewBelt** [comment]
@djpeterso23662  The MIDI Out panels haven't been designed yet, and no code yet. The gamepad MIDI driver was added a couple weeks ago.

**Comment by TronicLabs** [comment]
MIDI API Output?

**Comment by AndrewBelt** [comment]
@TronicLabs Be more specific about your question?

**Comment by TronicLabs** [comment]
@AndrewBelt I refer to the implementation for the MIDI API
to have output devices, more precisely here
https://github.com/VCVRack/Rack/blob/v1/include/midi.hpp#L49

**Comment by AndrewBelt** [comment]
@TronicLabs Right, but what's your actual question?

**Comment by TronicLabs** [comment]
@AndrewBelt I'm sorry, the question is about the opportunity to have the complete MIDI API, so we would be able to implement modules that can communicate with the midi output.

**Comment by AndrewBelt** [comment]
The API will be added when the CV-to-MIDI modules are added.

**Comment by TronicLabs** [comment]
Since in your communications you said that now you would be mainly busy developing modules,
could we know when the CV-to-MIDI module is scheduled?

**Comment by AndrewBelt** [comment]
No time estimate. Subscribe to this thread to receive notifications about the feature.

**Comment by TronicLabs** [comment]
thanks, already subscribed to these threads from its early days, good work

**Comment by z-plane** [comment]
was just about to make this request, looking forward to it!

**Comment by AndrewBelt** [comment]
Added several weeks ago to v1.
