### ISSUE TITLE
Add to the File menu "Open Recent Files" entry

### ISSUE THREAD

**Issue by ShofB** [VCVRack/Rack#969]
Add an open recent files to the menu.  This should contain 10 or so entries with the last file opened filtering to the top.

**Comment by AndrewBelt** [comment]
In Rack v2, I've added "recentPatchPaths" to settings.json and a "Open recent" menu item.

![2019-12-14-175145_1600x900_scrot](https://user-images.githubusercontent.com/338179/70855549-8dbd1f00-1e9a-11ea-87e6-b21b2b064932.png)

**Comment by Coirt** [comment]
Lovely!

**Comment by nay-seven** [comment]
Thanks a lot !

**Comment by Dom2Dom99** [comment]
In Rack V2 ??
Where i can find this version ?
i wait for this... since a very long time...
:D

**Comment by AndrewBelt** [comment]
@Dom2Dom99 The source will be available hopefully in Jan 2020.
