### ISSUE TITLE
Feature Request: VCV Instance Bridge

### ISSUE THREAD

**Issue by graehu** [VCVRack/Rack#973]
Being able to bridge between two different instances of VCV. You could probably achieve the same thing with routing between different programs like jack or [Carla](http://kxstudio.linuxaudio.org/Applications:Carla) but it's not user friendly.

The use case is for module management and pre-building effects chain patches.
I'd imagine it implemented as another audio driver/midi driver on the core modules.

---

It should be noted that I tried bridging between two VCV instances with the bridge vst hosted in [Carla](http://kxstudio.linuxaudio.org/Applications:Carla) without success. The second instance of VCV couldn't connect to either of the bridge vsts I hosted in [Carla](http://kxstudio.linuxaudio.org/Applications:Carla).

**Comment by AndrewBelt** [comment]
This feature relies on running multiple instances of Rack, which is unsupported, so I won't add it.

**Comment by graehu** [comment]
Fair enough, I'll close this feature request. But before I do, do you have any plans for features similar to this? Even if it's just a way to blackbox a section of a patch. Like layers or [collapsed nodes](https://docs.unrealengine.com/en-us/Engine/Blueprints/BP_HowTo/CollapsingGraphs)

I realise that those ideas are very disconnected from the idea of a "virtual" modular synth. They were just the simplest examples I could think of for managing modules in a single instance of VCV I could think of.

**Comment by AndrewBelt** [comment]
Yes #129 #209 #655 are a few

**Comment by graehu** [comment]
Thanks, closed.
