### ISSUE TITLE
6.1 - MIDI inputs don't work on Win64

### ISSUE THREAD

**Issue by alfonso73** [VCVRack/Rack#974]
Hi,
compiled VCV 6.1 yesterday..everything is fine except MIDI inputs don't work. All the relevant MIDI modules list all the system drivers correctly but MIDI signal does not arrive.
I'm on Windows 10 64bit with Presonus Quantum as ASIO and MIDI interface.
best!
a.

**Comment by AndrewBelt** [comment]
When you click "New issue", is the template not showing up for you? We've had many issues recently where people aren't filling in the form with vital information like the commit hash.

**Comment by alfonso73** [comment]
Ops sorry Andrew. I just tried to follow the issue reporting rules. What's
the commit hash?

Il ven 25 mag 2018, 16:54 Andrew Belt <notifications@github.com> ha scritto:

**Comment by AndrewBelt** [comment]
Run `git rev-parse HEAD`

**Comment by alfonso73** [comment]
41d2a01cacc2225b2adcfc5e82545411d7a94a65

**Comment by alfonso73** [comment]
oh...i see that i didn't got the form when i started the new issue. Now if i press new issue i see the form with the 3 options

**Comment by AndrewBelt** [comment]
There was an older one when you posted, but I've added this new one in hopes of people filling it out.

Does a newer commit solve it? There are some updates beyond that commit in the MIDI driver.

**Comment by alfonso73** [comment]
still same problem with 42a55414cbd6b51a25eb89362bf0a41af18af9f3
I forgot to mention that even the QWERTY MIDI does not reveive any signal or at least nothing comes out from the CV outs

**Comment by titos-carrasco** [comment]
Same problem here with 42a55414cbd6b51a25eb89362bf0a41af18af9f3 on Linux Debian Testing
QWERTY/MIDI-CC/MIDI-TRIG fails to learn, and does not send any data
Gamepad works fine

Tag v0.6.0 works without problems

**Comment by titos-carrasco** [comment]
Last good commit in MIDI-CC/MIDI-TRIG was c774778663e7dad21f4cb2db1d4966559d04958e
Next commit after that, 531f348dc2ac3610dcf92d90040f19b3b6e1e783, has problems

**Comment by alfonso73** [comment]
@titos-carrasco good to know! is there a way to clone and compile a particular commit? This way i can test on my side to. thanks!

**Comment by titos-carrasco** [comment]
Sure, first time "git clone https://github.com/VCVRack/Rack.git" and follow instructions to make it. 
Then you can checkout a particular commit with "git checkout _**commit_number_id**_"
At the end, you can go back with "git checkout v0.6"

**Comment by alfonso73** [comment]
Thanks. With https://github.com/VCVRack/Rack/commit/c774778663e7dad21f4cb2db1d4966559d04958e i don't see any entry in the MIDI-1 module. So on Windows is even worst.

**Comment by titos-carrasco** [comment]
@alfonso73 see next image, Now I'm on c774778663e7dad21f4cb2db1d4966559d04958e , my notebook is an i3 with 4GBRam, running JACK and UMX61,Akai LPD8, Novation LaunchControl and a Behringer TC64 midi controllers. All working good in that commit

![image](https://user-images.githubusercontent.com/4842986/40588633-8c4ff07a-61ae-11e8-96cc-203c019aea29.png)

**Comment by AndrewBelt** [comment]
Fixed in f6ed130

**Comment by alfonso73** [comment]
That's great!
thanks!
sorry for my github ignorance. Should i do something like "git pull origin v0.6" to update my local repo?

**Comment by alfonso73** [comment]
Yes it works from MIDI devices! thanks. No signal from the QWERTY keyboard btw.

**Comment by AndrewBelt** [comment]
Yes, that's the right way to update your local repo.

The QWERTY keyboard works when only caps lock is enabled.

**Comment by AndrewBelt** [comment]
On second thought, since the keyboard isn't used for anything else when no widgets are focused, I've removed the caps lock requirement for the keyboard MIDI driver in 5e9238e.

**Comment by alfonso73** [comment]
Thanks! Now it works! Sadly i still don't have any joypad to try that new feature. Is there a way to change octave for the QWERTY input mode?

**Comment by AndrewBelt** [comment]
The ` and 1 keys if I recall. It doesn't remember which keys are down, so make sure all keys are released before switching octaves.
