### ISSUE TITLE
Limit screen activity to save CPU

### ISSUE THREAD

**Issue by bkkjohn** [VCVRack/Rack#978]
Drawing the onscreen graphics take A LOT of CPU power. On my i7 Windows machine with 2 displays, a very large patch may consume 36-40% CPU power (enough to make it stutter endlessly, even with maximum ASIO buffer size). Disabling one monitor may reduce it to about 30%, and minimizing the window (no VCV Rack display at all) drops it to ~10%.   Even when graphics are eventually optimized, at some point a patch may become so complex it hits a performance wall.

To allow bigger patches, provide a configuration menu option for (1) full animation; (2) limited animation (i.e., no red/green on inputs and outputs; (3) no animation.

**Comment by AndrewBelt** [comment]
The scene is redrawn every frame regardless of whether is changes, just like a video game, so disabling "animations" like Lights won't solve anything.
