### ISSUE TITLE
OpenGl erro

### ISSUE THREAD

**Issue by HypnosProject** [VCVRack/Rack#981]
I can not start the application because the error below always appears.
"Cannot open window with OpenGL 2.0 renderer. Does your graphics card support OpenGL 2.0 or greater? If so, make sure you have the latest graphics drivers installed."

I already updated the video drive for the latest version, I have hd graphics 3000, I already looked in several forums, but without success. Anyone know how to fix this error?

Grateful for the attention !

**Comment by rubyglow** [comment]
Win10?
https://www.facebook.com/groups/vcvrack/permalink/129318607728292/

**Comment by HypnosProject** [comment]
Yes, I already tested on win7 in a Virtual Machine and it worked perfectly

**Comment by AndrewBelt** [comment]
Please do not ignore the form it asks you to fill out when posting a bug report. This wastes unnecessary time for maintainers and volunteers when we ask questions to collect the information that would have initially been posted.

Operating system(s):
Version of Rack if using official binary, or commit hash and branch if compiling from source:
All hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

**Comment by HypnosProject** [comment]
Sorry for not reporting everything, let me know if you have any relevant information missing!
Version of Rack:v0.6
Win10
Core i3 2370M
Ram: 4gb
Intel HD 3000, Drive: 9.17.10.4229, OpenGL 3.1, OpenCL 1.1

**Comment by AndrewBelt** [comment]
Do you have an entry with `[warn] ...` in your Documents/Rack/log.txt file?

**Comment by HypnosProject** [comment]
this is the only entry you have in the log file:
[0.855 warn] GLFW error 65542: WGL: The driver does not appear to support OpenGL

**Comment by AndrewBelt** [comment]
Perhaps Intel HD 3000 does not implement the OpenGL 2.1 standard in full. Perhaps buy a new graphics card / computer?

**Comment by HypnosProject** [comment]
I tested on win7 with the same hd 3000 graphics card and it worked perfectly, maybe it's a compatibility problem with win10,

**Comment by AndrewBelt** [comment]
Yes, that seems to be consistent with what others have experienced.

**Comment by HypnosProject** [comment]
Thanks for the help, I'll close this topic

**Comment by HypnosProject** [comment]
as it can in win 10 the vcv rack does not work because of OpenGL, if on the same computer I use Reaktor 6 that needs OpenGl 2.1 in order to work.

**Comment by AndrewBelt** [comment]
What?

**Comment by HypnosProject** [comment]
When I try to open the vcv rack it shows me the OpenGL error, as if my hd 3000 did not support it, but when I open other applications that also use opengl, both in version 2.1 and 3.0 none of these applications return me an error.

**Comment by MrGalloway** [comment]
https://github.com/pal1000/save-legacy-intel-opengl Please check this out, pal1000 does a fantastic job there, there's even a patch for vcv specifically.

**Comment by HypnosProject** [comment]
Thank you very much, VCV Rack is working perfectly!

**Comment by CollectiveAwareness** [comment]
Hey There New user here !
Having the same problems with VCV rack 1.1.6, Didn't get how to fix it not much coding experience ..
Win 10
CPU: Intel core i3 2370M   
Ram: 4 GB
pretty sure we have the same PC haha
Love some help on how to code into VCV rack

**Comment by Petervos2018** [comment]
Go here : https://fdossena.com/?p=mesa/index.frag
Download the latest version. 
Put the dll in the rack folder and have fun.

**Comment by nisios** [comment]
msxrx thanks very much, super easy fix!! Click this, Bang problem solved for everyone!

AndrewBelt you were completely useless in this thread, go do something else please, your wasting everybody's time addin absolutely nothing to the solution. "Perhaps buy a new graphics card / computer?" lols
