### ISSUE TITLE
Eliminate multiple modules and connecting from input to output.

### ISSUE THREAD

**Issue by robertsyrett** [VCVRack/Rack#983]
Multiple modules take up valuable screen space and don't need to exist.  You can have one to many stacked cables to achieve the same effect.  I request the following changes:

1 Drag cords from output to input only.

2 Dragging from an input with a cord already connected generates a second cord.

3 Dragging a connected cable from an input deletes the connection.

This should prioritize one to many connections without having to waste space on mults and avoid undefined mixing on inputs.

Mults are good in the real world, but they are an unnecessary element in a software modular.

**Comment by AndrewBelt** [comment]
1. No, people like dragging from either direction.
2. No, dragging from an input will drag the existing cable.
3. It already does.

**Comment by robertsyrett** [comment]
So you don't perceive multiples as being wasteful us of screen space?

**Comment by AndrewBelt** [comment]
There's no need in VCV Rack to use multiples because all patch cables can be stacked on outputs.

**Comment by robertsyrett** [comment]
Well it's nice to know that you moderate on many fronts but what is the harm in engaging multiple communities at once?

**Comment by AndrewBelt** [comment]
I'm marking this as resolved, comment if I'm mistaken.
