### ISSUE TITLE
Mac build of Rack 0.6.0 omits plugin manager

### ISSUE THREAD

**Issue by CJunit** [VCVRack/Rack#985]
I built the latest as per instructions on OS 10.11.6 so that I could practice compiling modules. Focus has been trying modules not listed as being addable by the plugin manager. That works fine so far, enjoying trying some new modules. BUT the plugin manager is missing! I have dug for explanations in the readme and elsewhere but seen no mention of this. Is there a special argument or variable somewhere for this? 

Thanks! My kids and I are having a blast with this so far.

**Comment by AndrewBelt** [comment]
Compile with `make RELEASE=1`

**Comment by CJunit** [comment]
That sounds promising. But when I type it, it responds with only:

/Library/Developer/CommandLineTools/usr/bin/make -C dep
make[1]: Nothing to be done for `dep'.

With "make run" I get that same message, but then Rack loads and runs. With "make RELEASE=1" it just returns me to the terminal prompt and the message isn't followed up with anything. Any idea what I am missing?

**Comment by AndrewBelt** [comment]
You'll need to `make clean` if you've already build the project. Make doesn't rebuild automatically if a binary already exists.

**Comment by CJunit** [comment]
True, I was doing that before and forgot. It works! Thanks for your help and your patience

**Comment by AndrewBelt** [comment]
Actually, because of https://github.com/VCVRack/Rack/issues/258#issuecomment-399387595, the information in this issue is obsolete.
