### ISSUE TITLE
Rack crashes when using MIDI CC and MIDI-1 modules simultaneously

### ISSUE THREAD

**Issue by NikalMight** [VCVRack/Rack#986]
I'm on W10. If  I add a MIDI-CC module and a MIDI-1 module in the same project and set both of them to my Focusrite 6i6 MIDI port, Rack crashes. I assume this is because the 2 modules are fighting over the same MIDI device, but this means I can't use the keyboard and the CCs on my controller keyboard at the same time without some complicated workaround.

**Comment by AndrewBelt** [comment]
How did you post this issue? Did you click New Issue and then Bug Report?

**Comment by NikalMight** [comment]
I just clicked new issue. I'm not sure how to file a bug report specifically.

**Comment by AndrewBelt** [comment]
Weird. It should bring you to the page https://github.com/VCVRack/Rack/issues/new/choose. Can you confirm that clicking "New issue" above directs you to that page?
If so, did you click "Get started" next to "Bug report"? And did it show template text for that issue? We've had a large number of new issues without that form and I have no idea what's breaking it.

**Comment by david-c14** [comment]
Andrew,  If I go to the issues page on my mobile and press the + which it offers, I get a plain issue form, not the template choice at all.

**Comment by MarcBoule** [comment]
#818

**Comment by AndrewBelt** [comment]
@david-c14 Okay, thanks, that was it. I've added a default template which should be a fallback.

Assuming @NikalMight is using the Rack 0.6.0 release, this has already been solved in the `v0.6` branch, so closing.
