### ISSUE TITLE
A Dedicated Module Drag Handle for Repositioning Modules

### ISSUE THREAD

**Issue by JWhiteUX** [VCVRack/Rack#987]
It would be nice to have a drag handle or a point on the module where a user can click to reposition, so that users don't accidentally move modules when in fact they simply wanted to adjust a param or draw a patch cable.

The latter being something I find myself constantly dealing with as it seems a user can click and drag anywhere on a module to reposition it.

Alternatively, it might be as simple as only repositioning on a `long left-click` if the click occurs in the upper or lower regions of the modules, i.e the rails behind the module.

Red = Top Drag handle
Blue = Bottom Drag Handle
![artboard 2x](https://user-images.githubusercontent.com/12961108/40942206-4e6b7dc4-6802-11e8-8a08-8cac8b72654e.png)

**Comment by AndrewBelt** [comment]
A solution I like better is in #492.
