### ISSUE TITLE
module settings

### ISSUE THREAD

**Issue by martin-lueders** [VCVRack/Rack#989]
Hi,

I was wondering whether there is already a mechanism to store module settings, which should be stored in a system wide way, and independent of the patch.

Can we add module specific data into the settings.json file?

Cheers,
Martin

**Comment by AndrewBelt** [comment]
What you're describing is "module presets" #276, and it's planned at some point, so merging with that issue.

**Comment by martin-lueders** [comment]
OK. That sounds like the best solution. I will try this.

**Comment by AndrewBelt** [comment]
I declare the above as the "recommended" way of achieving plugin settings. It is very easy

```cpp
json_t *settingsJ = ...

std::string settingsFilename = assetLocal("MySlug.json");
FILE *file = fopen(settingsFilename.c_str(), "w");
if (file) {
	json_dumpf(settingsJ, file, JSON_INDENT(2) | JSON_REAL_PRECISION(9));
	fclose(file);
}

json_decref(settingsJ);

```

and you don't need to use JSON if .dat or .wav or .xml etc is a more appropriate format.

Loading can occur during the `init()` call. Saving can occur when the setting is changed.
