### ISSUE TITLE
Knobs not working properly as of e068ad9

### ISSUE THREAD

**Issue by MarcBoule** [VCVRack/Rack#990]
Operating system(s): Win10
Version of Rack : e068ad9

Knobs are behaving quite strangely since this last version above (might be a few comits before though, but not very many). I even did a fresh install, and they are snapping in only min, default and max positions. I cloned Fundamental, and also tried to copy over my VCV plugins from my pre-built 0.6 version (downloaded binary), and nothing is working properly.

Also perhaps related, when using the delete key to delete a module, the first other module we hover over with the mouse also gets deleted. Quite strange. 

I will edit this with more details when I finish work.

**Comment by AndrewBelt** [comment]
I can't replicate the knob issue.

However, the module deletion issue was a cause of switching to GLFW's sticky key implementation, which behaves differently because it doesn't "stick" the keys across adjacent frames.

**Comment by MarcBoule** [comment]
I'm back on my home computer now, so this followup below may be inconclusive : on my home computer, I had done a pull last night (eastern US time), and I did one just now, and everything works well. 

I'll re-test my work computer tomorrow and see if that fixes things, if you can keep the revert until then. If not, no problem, I don't want to stall any of your work though.

**Comment by AndrewBelt** [comment]
The revert is there to stay. Just test it and let me know if it breaks. If not, all is good.

**Comment by MarcBoule** [comment]
Everything works as normal, that seems to have been the cause. Thanks!
