### ISSUE TITLE
no plugin manager or fundamental plugins after compiling

### ISSUE THREAD

**Issue by Newk77** [VCVRack/Rack#995]
I needed Jack support so i compiled VCV Rack 0.6.1dev on ubuntu 16.04 (with kxstudio ppa core elements installed) like instructed on this site.
But at the moment i cannot do anything with it because it only has core modules and no Fundamentals.
Also no log-in function or of sorts plugin manager in the toolbar... i did used the plugin website buttons after logging in.. but i cant see where those end up.. not in the downloads or anything so dont know how to place them manually into plugins folder.
Did i do something wrong? or is this a feature that is missing from the compile-version?

**Comment by danballance** [comment]
Are you possibly missing the release parameter?
```
make RELEASE=1
```

This command enables the plug-in manager and then you can download commercial plugins etc like normal.

**Comment by AndrewBelt** [comment]
`make RELEASE=1` has been removed in b6b6ec8553c679cb95cf5f481b854e4754294c7f. There is now no different between the release and development builds. Run the development build with `make run` or `./Rack -d`, and the release build with `make runr` or `./Rack`.

**Comment by Newk77** [comment]
Yes i did `make run` like in the build instructions... seems like `./Rack` now by default starts the dev-build after that. Now i need to recompile to do `make runr`... or is there a CLI parameter like -d that does the opposite? (-r seemed not to do that trick)

**Comment by AndrewBelt** [comment]
A recompile is no longer needed to switch "build types", as it's now a runtime state. You should see the plugin manager when running the release build. If not, state how you're running Rack in detail.

**Comment by Newk77** [comment]
by the way if i do `./Rack -d` now on this version i can see on CLI that it's trying to open the patch called "-d" while starting up

**Comment by Newk77** [comment]
> If not, state how you're running Rack in detail
```
~$ cd Rack
~/Rack$ ./Rack
```

**Comment by AndrewBelt** [comment]
When posting issues (in any open-source project, not just Rack), always state the commit hash. `git rev-parse HEAD`

**Comment by Newk77** [comment]
allright i will! thanks for the help :)
