### ISSUE TITLE
Logging not ABI compatible between 0.6.1 (plugin) and 0.6.0 (app binary)

### ISSUE THREAD

**Issue by david-c14** [VCVRack/Rack#997]
plugins which use the logging function error, warn, debug or fatal are not ABI compatible with the 0.6.0 app if they are compiled against the 0.6.1.

This is because those functions have been replaced by macros which wrap new logging functionality.  The compiled plugin will import the new function, but that is not exported by the compiled app.

Operating system(s): all
Version of Rack: 0.6.0 official binary.

**Comment by AndrewBelt** [comment]
This falls under the rare case explained under Symbol Additions of https://vcvrack.com/manual/Version.html. The v0.X or vX plugin API/ABI is guaranteed to be compatible with future non-breaking revisions of Rack but not past versions.

**Comment by david-c14** [comment]
I was just worried that the 0.6.1 binaries for the main app are not yet available for people to download, so there's a risk that plugins will be incompatible.

**Comment by AndrewBelt** [comment]
Yes, that's why I pulled SubmarineFree.
