### ISSUE TITLE
Error compiling latest 0.6.1dev on Windows10 64bit

### ISSUE THREAD

**Issue by alfonso73** [VCVRack/Rack#998]
Please read https://github.com/VCVRack/Rack/issues/730 before posting any code or terminal output.

Operating system(s): Windows 10 64bit
Version of Rack if using official binary, or commit hash and branch if compiling from source:
7f6745ca58be1ab95cd13ad06cc79b6f01466a8a

Hi have this error when launching make run or make runr

make -C dep
make[1]: Entering directory '/home/fremen/Rack/dep'
make[1]: Nothing to be done for 'dep'.
make[1]: Leaving directory '/home/fremen/Rack/dep'
make: *** No rule to make target 'build/dep/osdialog/osdialog.c.o', needed by 'Rack.exe'.  Stop.

**Comment by modlfo** [comment]
You need to update the submodules. Then `make clean` and `make`

**Comment by alfonso73** [comment]
Thanks @modlfo. Which commands should I run before make clean?

**Comment by alfonso73** [comment]
i did
git submodule update --init --recursive
make clean
make 
make run

now it works
thanks!

**Comment by AndrewBelt** [comment]
Should be fixed in 5428ad3.
